### ISSUE TITLE
Airline line indicator symbol is empty / not found

### ISSUE THREAD

**Issue by alpertuna** [ryanoasis/nerd-fonts#100]
#### environment
- vim: 7.4
- OS: Debian Jessie
- terminal: XTerm
- $TERM variable: screen-256color-italic
- color configuration (:set t_Co?): 256
- font: DejaVu Sans Mono for Powerline Nerd Font Complete Mono.ttf

Hello,
A square character is appeared near line indicator, and I found g:airline_symbols.maxlinenr keeps that char and I am able to correct it from .vimrc, but I wonder why its default value is look like square.
That character is '☰'
![screenshot from 2016-08-24 16 17 34](https://cloud.githubusercontent.com/assets/12586695/17932159/5f183896-6a17-11e6-8d69-9ecbfc1998ea.png)

**Comment by ryanoasis** [comment]
Can you try https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/DejaVuSansMono/Regular/complete/DejaVu%20Sans%20Mono%20for%20Powerline%20Nerd%20Font%20Complete.ttf instead?

**Comment by alpertuna** [comment]
@ryanoasis 
I tried it but still the same. I looked #92, there is no problem like that, I can see that icons with my font.
The problem is about just this char I see.
I inspected the character and;

![screenshot from 2016-08-25 10 37 05](https://cloud.githubusercontent.com/assets/12586695/17961044/2beb9eae-6ab2-11e6-862a-63014225a538.png)

Its hex code is 2630
And that character is empty in font map
![screenshot from 2016-08-25 10 37 20-2](https://cloud.githubusercontent.com/assets/12586695/17961066/447d6b1e-6ab2-11e6-8b9e-da6b7601e008.png)

**Comment by ryanoasis** [comment]
Thanks for the details. Looks like the characters in range `2630` through `2637` (trigrams) are missing even in the [unpatched Nerd Fonts powerline source of DejaVu Sans](https://github.com/ryanoasis/nerd-fonts/blob/master/unpatched-sample-fonts/DejaVuSansMono/Regular/DejaVu%20Sans%20Mono%20for%20Powerline.ttf)

![screenshot_2016-08-26_08-48-46](https://cloud.githubusercontent.com/assets/8083459/18005765/0b421f9e-6b6a-11e6-924e-0d56ee627ef6.png)

--

So it looks like these were missing from the source font Nerd Fonts patches. This is not a bug with Nerd Fonts itself **however** we could make an improvement to patch in these missing glyphs if detected :smile:

**Comment by alpertuna** [comment]
+1 :blush:

**Comment by ryanoasis** [comment]
These are missing for some reason (along with many other glyphs that are in the Deja Vu Sans condensed).

I have not attempted to fix all of them (that would take way too long) but I did copy these trigrams from the appropriate condensed version to the mono versions for now.

I also updated Deja Vu fonts from version 2.33 to 2.37 (see [deja vu changelog](http://dejavu-fonts.org/wiki/Changelog))

**Comment by alpertuna** [comment]
Thanks :+1: I already use some alternative ways for missing glyps, so time is not problem :blush:

**Comment by ryanoasis** [comment]
What are the alternative ways you are using if you don't mind me asking? Fontconfig?

**Comment by alpertuna** [comment]
I use `Xresources` to set font, and I specified more than one font as fonts chain so that if a char is not defined, it searches next font family for that char.

**Comment by Finii** [comment]
Now really fixed for all fonts via #1125
