### ISSUE TITLE
Ligatures not working in some situations after patching Iosevka

### ISSUE THREAD

**Issue by Bahnschrift** [ryanoasis/nerd-fonts#1000]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Font ligatures are not working in some environments on a patched custom build of Iosevka. They seem to show up fine in Windows Terminal, but don't work at all in IntelliJ or VSCode, even with the appropriate settings to enable font ligatures. Ligatures work fine with the unpatched font.

#### 🔧 Your Setup

I'm using the following Iosevka build plan:
```toml
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "slab"
no-cv-ss = false
export-glyph-names = false

[buildPlans.iosevka-custom.ligations]
enables = [
    "centre-ops",
    "arrow",
    "arrow2",
    "trig",
    "eqeq",
    "exeq",
    "ineq",
    "eqeqeq",
    "exeqeq",
    "exeqeqeq",
    "eqexeq",
    "ltgt-diamond",
    "ltgt-slash-tag",
    "brst",
    "plusplus",
    "kern-dotty",
    "kern-bars",
    "logic",
    "llgg",
    "llggeq",
    # "dot-as-operator",
    "bar-triggers-op-centering",
    "html-comment",
    "brace-bar",
    "brack-bar",
    "connected-underscore",
    "connected-number-sign",
    "connected-tilde-as-wave",
    "connected-hyphen-as-semi-dashed-line"
]

[buildPlans.iosevka-custom.variants]
inherits = "ss20"

[buildPlans.iosevka-custom.variants.design]
zero = "dotted"
asterisk = "penta-low"
caret = "high"
paren = "flat-arc"
ampersand = "lower-open"
at = "fourfold-solid-inner"
lig-ltgteq = "slanted"
question = "corner"

[collectPlans.iosevka-custom]
from = ["iosevka-custom"]
```
I've also uploaded the `.ttc` [here](https://drive.google.com/file/d/1D4XBkMEToCC7Bzw-3N1l6saD0Z99vLks/view?usp=sharing). I'm patching the font on WSL with `./font-patcher iosevka-custom-sans.ttc --complete --mono`.

#### ★ Screenshots

When opening the patched font in fontforge, I get this message:
![image](https://user-images.githubusercontent.com/31170809/202900811-45738b89-0c81-4e15-b0b8-5408419d5b3f.png)
I'm not sure whether it is related or not, but I'll include it here just in case.

**Comment by Bahnschrift** [comment]
I'm unable to reproduce this anymore with the latest version of the font patcher. I'm not sure if it was previously caused by a problem with my setup or the patcher itself.

**Comment by realth000** [comment]
On August it worked well with the following versions:
nerd-font commit id: de9bb5b9bff7052478ebf059115a977d5df34b95
Nerd Fonts: 2.2.1
font-patcher script version: 3.0.2
iosevka: 16.0.1

But ligations disappeared when I upgrade iosevka to 16.6.0, after also upgrade Nerd Fonts to v2.3.0-RC (3.2.1) on master branch.
nerd-font commit id: 498ebf372bfc84731df6fe9411c909b4e97b1ec0

I patch ttf fonts using
``` bash
for f in `find iosevka0828 -type f`; do ./nerd-fonts/font-patcher $f --complete --quiet --windows --mono --makegroups --outputdir ./iosevka0828nf 2>/dev/null 1>&2; done
```
and add flag `--makegroups` according to #1019.
``` bash
for f in `find iosevka0828 -type f`; do ./nerd-fonts/font-patcher $f --complete --quiet --windows --mono --outputdir ./iosevka0828nf 2>/dev/null 1>&2; done
```

I didn't remember how I patched Iosevka on August, I will try again with 16.0.1 version later.

**Comment by Finii** [comment]
@realth000 

Maybe you should raise a new Issue, or are the details the same?

If this is the same as Bahnschrift's:

(Usual questions, answer all that are relevant)

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_
   - _Where did you get the file from (download link, self patched, source downloaded from link...)_
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_

When self-patching (except when using docker) which version of `fontforge`?

Please add description of concrete problem, best with screenshot.

Any links to your font files?

**Comment by Bahnschrift** [comment]
When this worked for me 2 days ago, I was using Iosevka 16.5.0 and font patcher 2.3.0 (3.2.1? not sure how the versions work), which were both the latest releases at the time.

**Comment by Finii** [comment]
@Bahnschrift thank you.

The first number is the "Nerd Font Release" number (at the moment 2.3.0-release_candidate), while the second number is independent from that the version of the patcher itself (because it is updated far more often then there are releases). 

My questions above were for @realth000 

`16.5.0` is a good hint. Some ligatures can be destroyed in the patching process, when we want to place a new icon where a ligature glyph was before. This can be prevented by giving `--careful`. The message while patching is then `Found essential glyph at ...` (while it is `existing glyph` for ordinary glyphs).

**Comment by realth000** [comment]
Yes, I checked again, the same.
Only have ligatures in Windows Terminal, not in IntelliJ Idea, VS Code and Wezterm.
![image](https://user-images.githubusercontent.com/59462104/205648944-0e280e16-b2a7-4b7a-91ee-008972a7b625.png)

<details><summary>Font name</summary>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible Bold Italic.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible Bold.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible ExtraBold Italic.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible ExtraBold.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible ExtraLight Italic.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible ExtraLight.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible Heavy Italic.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible Heavy.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible Italic.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible Light Italic.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible Light.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible Medium Italic.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible Medium.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible SemiBold Italic.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible SemiBold.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible Thin Italic.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible Thin.ttf'<br>
'Iosevka1204 Extended Nerd Font Complete Windows Compatible.ttf'<br>
</details>

[Download not patched Iosevka fonts](https://drive.google.com/drive/folders/1wszzmdyeU1EnIyyeRty7FTseTu4dh6a9?usp=share_link)
[Download patched fonts](https://drive.google.com/drive/folders/1Z0kTeEmu6rPCDD1N8N3b9TF4JN02okZq?usp=sharing)

--------------------------------------------

I patched fonts with:
* OS: Kubuntu2204
* Iosevka: 16.6.0
* Nerd Fonts: 498ebf372bfc84731df6fe9411c909b4e97b1ec0
* Font patcher: v2.3.0-RC (3.2.1)
* fontforge version: 1:20201107~dfsg-4build1

Patch command (already use `--careful`):
``` bash
for f in `find iosevka1204-1205 -type f`; do ./nerd-fonts/font-patcher $f --complete --quiet --windows --makegroups --careful --outputdir ./iosevka1204-1205NF-2 1>log 2>&1; done
```
Patch command log:
[iosevka_patch_command_log.txt](https://github.com/ryanoasis/nerd-fonts/files/10154597/iosevka_patch_command_log.txt)

--------------------------------------------

I use patched fonts in:
* Windows 10 21H2 19044.2251
* Windows Terminal: 1.15.2874.0 (have ligatures)
* IntelliJ Idea: 2022.3
* VS Code: 1.73.1
* Wezterm: 20220905-102802-7d4b8249

**Comment by Finii** [comment]
>     * fontforge version: 1:20201107~dfsg-4build1

There was a bug in `fontforge` that prevents correct ligature tables (sometimes; for example with Iosevka).
The PR has been pulled and is in effect with `Fontforge 2022 March Release`, so maybe try again with a more up to date fontforge?

**Comment by Finii** [comment]
That (the internal fontforge error message window) is the same error as @Bahnschrift described in the original Issue description. So maybe that is also a hint for Bahnschrift to use a more recent fontforge.

**Comment by Finii** [comment]
See also
* #694 
* #742 
* #750

**Comment by Bahnschrift** [comment]
> That (the internal fontforge error message window) is the same error as @Bahnschrift described in the original Issue description. So maybe that is also a hint for Bahnschrift to use a more recent fontforge.

Back when it wasn't working for me, I tried with both the march release of fontforge and with fontforge built straight from the main branch of the source.

As far as I can tell, it was either updating my copy of iosevka or the patcher script that fixed it for me.

**Comment by Finii** [comment]
Just for the protocol:

> the March release of fontforge

It can be missleading to call it such, because they have
* Fontforge 2020 March Release
* Fontforge March 2022 Release

(Yes, with the order differnt :grimacing:)

**Comment by Bahnschrift** [comment]
I should probably add that when I did get it to work, I was using fontforge built from [this commit](https://github.com/fontforge/fontforge/tree/8ce3216d492d4a249ffec163c005d098df28e58c).

**Comment by realth000** [comment]
I built latest fontforge and it works well with latest Iosevka. Thanks!!! @Finii @Bahnschrift
