### ISSUE TITLE
[Glyph Request] The Vitruvian Man

### ISSUE THREAD

**Issue by NathanC** [ryanoasis/nerd-fonts#1001]
**Is your feature request related to a problem? Please describe.**

I'm looking for a more interesting glpyh to generally represent "human", for my shell prompt.

**Describe the solution you'd like**

It would be awesome if a version of Leonardo da Vinci's [The Vitruvian Man](https://en.wikipedia.org/wiki/Vitruvian_Man) was added. From Wikipedia:

> [It is] justly ranked among the all-time iconic images of Western civilization

Given da Vinci's work as an engineer and scientist, this seems like a really fitting glyph to have in nerd fonts, and I can imagine a few cool uses. I'm honesty surprised it's not in any of the major icon packs currently.

**Additional context**

I'm not an artist, so I don't have a mockup, which I know will make this low priority. There are some examples [in flat icon here](https://www.flaticon.com/free-icons/vitruvian-man). One example:

![vitruvian man icon, source: https://www.flaticon.com/free-icon/da-vinci_1923316?term=vitruvian%20man&page=1&position=9&page=1&position=9&related_id=1923316&origin=tag](https://user-images.githubusercontent.com/6182419/202928676-951dc50b-5037-4eb6-b0d3-8432341c5836.png)

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
