### ISSUE TITLE
OSError: Font generation failed

### ISSUE THREAD

**Issue by luiz00martins** [ryanoasis/nerd-fonts#1002]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
After running `fontforge.exe -script 'font-patcher' 'Monocraft.otf'`, I got an the following error:
```
Nerd Fonts: Processing Monocraft (1/1)
No configfile given, skipping configfile related actions
Adding 177 Glyphs from Seti-UI + Custom Set
╢████████████████████████████████████████╟ 100%
Adding 198 Glyphs from Devicons Set
╢████████████████████████████████████████╟ 100%

Done with Patch Sets, generating font...

Save Failed
Traceback (most recent call last):
  File "C:\Users\luizh\Programs\nerd-fonts\font-patcher", line 1427, in <module>
    main()
  File "C:\Users\luizh\Programs\nerd-fonts\font-patcher", line 1412, in main
    patcher.generate(sourceFonts)
  File "C:\Users\luizh\Programs\nerd-fonts\font-patcher", line 339, in generate
    sourceFont.generate(outfile, bitmap_type=bitmaps, flags=(str('opentype'), str('PfEd-comments')))
OSError: Font generation failed
```

Expected behavior:
Patching of the font.

Example symbols:
None.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Monocraft.otf
   - https://github.com/IdreesInc/Monocraft
- Windows Terminal (powershell)
- Windows 10 Home 19044.2251

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/43142209/203277335-eeeee0aa-bce1-4037-b6ed-0f59d918dbc7.png)

**Comment by Finii** [comment]
Just opening it in `fontforge` GUI mode and generating a new font...

![image](https://user-images.githubusercontent.com/16012374/203379976-cb7d01f8-d144-4d5a-95cf-4aa1b35462a9.png)

This is obviously either a font or a `fontforge` problem.

**Comment by luiz00martins** [comment]
Should I raise it in Monocraft's repo?

**Comment by Finii** [comment]
(I suspect, this is due to the recent changes (rewrite) introduced by Skef with https://github.com/fontforge/fontforge/pull/4685, but that is just a hunch, one would need to do a proper `biscect` run which I have no time for at the moment.)

Using an older `fontforge` (in this case 2020-11-07) solves the problem:

Maybe you should raise an Issue over there (fontforge).

![image](https://user-images.githubusercontent.com/16012374/203381440-e7cd2cc5-f48f-4c27-8e48-f43e6ba27c1f.png)

**Comment by Finii** [comment]
> Should I raise it in Monocraft's repo?

Maybe. The `fontforge` code change with PR 4685 made it (`fontforge`) more susceptible to errors in the font files.
The error message I got (MonotonicFindAlong) hints that something is amiss with the font itself.

Older `fontforge` gloss over font authoring errors (ignores them) more often I have the feeling.

**Comment by Finii** [comment]
Hmm, maybe ... can you try to create the patched font in some other dir? Do you have write access in `Program Files (x86)/`?

Maybe add `--outputdir` like so:
```
./fontforge.exe -script 'C:\Users\luizh\Programs\nerd-fonts\font-patcher' 'c:\Users\luizh\Downloads\Monocraft.otf' --outputdir 'c:\Users\luizh\Downloads'
```

**Comment by luiz00martins** [comment]
Confirmed. Ran as administrator, and it generated the font.

Should this have a better error message, or can I close as complete?

**Comment by Finii** [comment]
We can use `os.access(..., os.W_OK)` [1], but I'm not sure it will work on Windows [2].

Maybe you can quickly try if this would trigger in your case (and if the message helps ;)

```diff
diff --git a/font-patcher b/font-patcher
index 4fe8b11bd..d0503f93b 100755
--- a/font-patcher
+++ b/font-patcher
@@ -323,6 +323,8 @@ class font_patcher:
                     layer = l
                     break
             outfile = os.path.normpath(os.path.join(self.args.outputdir, sourceFont.familyname + ".ttc"))
+            if not os.access(outfile, os.W_OK):
+                sys.exit("{}: Can not create output file '{}'".format(projectName, outfile))
             # the `PfEd-comments` flag is required for Fontforge to save '.comment' and '.fontlog'.
             sourceFonts[0].generateTtc(outfile, sourceFonts[1:], flags=(str('opentype'), str('PfEd-comments')), layer=layer)
             message = "\nGenerated: {} fonts in '{}'".format(len(sourceFonts), outfile)
@@ -331,6 +333,8 @@ class font_patcher:
             if not fontname:
                 fontname = sourceFont.cidfontname
             outfile = os.path.normpath(os.path.join(self.args.outputdir, fontname + self.args.extension))
+            if not os.access(outfile, os.W_OK):
+                sys.exit("{}: Can not create output file '{}'".format(projectName, outfile))
             # the `PfEd-comments` flag is required for Fontforge to save '.comment' and '.fontlog'.
             bitmaps = str()
             if len(self.sourceFont.bitmapSizes):
```

[1] https://docs.python.org/3/library/os.html#os.access
[2] [SO link](https://stackoverflow.com/questions/47227065/python-how-to-find-out-if-a-directory-is-writable#comment81418805_47227065)

**Comment by luiz00martins** [comment]
Unfortunately, it seems like it doesn't trigger in my setup. Still got the same error:
```
Traceback (most recent call last):
  File "C:\Users\luizh\Programs\nerd-fonts\font-patcher", line 1431, in <module>
    main()
  File "C:\Users\luizh\Programs\nerd-fonts\font-patcher", line 1416, in main
    patcher.generate(sourceFonts)
  File "C:\Users\luizh\Programs\nerd-fonts\font-patcher", line 343, in generate
    sourceFont.generate(outfile, bitmap_type=bitmaps, flags=(str('opentype'), str('PfEd-comments')))
OSError: Font generation failed
```

**Comment by Finii** [comment]
This is what I feared from Eryk Sun's comments on SO :-(
And adding Windows specific code (like Eryk suggested) is nothing I would want.

We could suppress the traceback and just output the error, but that would not really be of any help I guess.
It says "Font generation failed" and we can not determine the reason any more precise, unfortunately, I guess.

**Comment by luiz00martins** [comment]
That seems fair.

Should I leave it open in case anyone picks it up, or should I close it as the canonical answer? (I imagine most people who have this problem are just going to search on the issues for the error message and find this).

**Comment by Finii** [comment]
I would close this. It can still be found, even if you search for `is:open` it shows it under `closed: xxx issues match`.

You are the first who had this 'can not write' issue; the other OS issues that we fixed in the meantime happened far more frequent. Otoh, I like to have all failure-modes covered. But in this case it seems ... very hard.

**Comment by luiz00martins** [comment]
All right. Thank you! I really appreciate you help.
