### ISSUE TITLE
brew install fails

### ISSUE THREAD

**Issue by endlesslight0** [ryanoasis/nerd-fonts#1003]
```
❯ brew install font-fira-mono-nerd-font
==> Downloading https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.1/FiraMono.zip
Already downloaded: /Users/light/Library/Caches/Homebrew/downloads/9652ec8b6a18df45e0cc250ab401e140a3178d2d5351730be633dd61c2a6fca3--FiraMono.zip
==> Installing Cask font-fira-mono-nerd-font
==> Purging files for version 2.2.1 of Cask font-fira-mono-nerd-font
Error: It seems the Font source '/opt/homebrew/Caskroom/font-fira-mono-nerd-font/2.2.1/Fira Mono Bold Nerd Font Complete.otf' is not there.
```

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/203956729-ffe35180-f7ac-4d5e-b331-70af8c39f4cb.png)

:unamused: 

Apart from the fact that this is still `2.2.1` and not `2.2.2`.

**Comment by Finii** [comment]
In fact I believe (have to check) that `Fira` was a RFN and thus we have `Fura`, but that has changed meanwhile, and now we could/should name it `Fira` again. Note to self: Check upstream font source, I think there was something mentioned.

**Comment by anupj** [comment]
I have this same issue. What's the fix?

**Comment by Finii** [comment]
@anupj You can only either wait some days or install the font manually (which is simple), just grab the `zip` from the [release page](https://github.com/ryanoasis/nerd-fonts/releases), unpack it and throw all the font files into your fonts folder.

I'm currently working on improving the cask situation, as discussed [here](https://github.com/Homebrew/homebrew-cask-fonts/pull/6649). That will take some days, maybe a week until all works and the casks are automagically updated.

**Comment by anupj** [comment]
Thank you @Finii ! Appreciate the prompt response 🙏

**Comment by p-linnane** [comment]
@Finii Hi. I'm a Homebrew maintainer. Please let me know if there is anything you need from our side and I'll be happy to help if I can.

**Comment by Finii** [comment]
@p-linnane Thank you! Maybe you can tell me if you would rather get one bigger PR that contains all (needed) updates, or multiple PRs, one for each font that needed an update?

I just finished the actual cask file generation stuff, now turning to the CI part...

**Comment by p-linnane** [comment]
I would say that one PR would be fine, but it depends on how many fonts are changed at the same time. I believe our CI matrix caps out at 256, so if it's under that it should be fine.

**Comment by Finii** [comment]
Fixed with
* https://github.com/Homebrew/homebrew-cask-fonts/pull/6682

**Comment by Finii** [comment]
@p-linnane 

Maybe you can give me advice on this Homebrew question:

According to https://docs.brew.sh/Brew-Livecheck one should not use `:github-latest`, at least I read that so

> Only use the GithubLatest strategy when it’s necessary and correct.

At the moment we do this:

```
  livecheck do
    url :url
    strategy :github_latest
  end
```

Shall we change that to

```
  livecheck do
    url :url
    strategy :git do |tags|
      tags.map { |tag| tag[/^v(\d+\.\d+\.\d+)$/] }
    end
  end
```

(Does that even make any difference for the Github rate limiter?)


And maybe coming back to my previous question, does `font` in your answer mean 'cask of a font' or 'adding all font files in all casks'?


Thank you,  Fini

**Comment by p-linnane** [comment]
@Finii In this case I think `:github_latest` is appropriate because GitHub pre-releases are used (for example `v2.3.0-RC` currently at the top of the release page).

'Cask of a font' is what I was referring to. Basically just the number of individual files changed in one PR can't be more than 256.
