### ISSUE TITLE
Cannot patch nerd font Meslo LGS with codicons

### ISSUE THREAD

**Issue by hgoumner** [ryanoasis/nerd-fonts#1005]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

I cannot patch the nerd font Meslo LGS Regular with the codicons package due to the following error:

`  File "/home/hristo/Documents/nerd-fonts/font-patcher.py", line 1427, in <module>
    main()
  File "/home/hristo/Documents/nerd-fonts/font-patcher.py", line 1407, in main
    patcher.patch(sourceFonts[-1])
  File "/home/hristo/Documents/nerd-fonts/font-patcher.py", line 302, in patch
    self.copy_glyphs(SrcStart, symfont, patch['SymStart'], patch['SymEnd'], patch['Exact'], patch['ScaleGlyph'], patch['Name'], patch['Attributes'])
  File "/home/hristo/Documents/nerd-fonts/font-patcher.py", line 956, in copy_glyphs
    currentSourceFontGlyph = min(possible_codes)
                             ^^^^^^^^^^^^^^^^^^^
ValueError: min() arg is an empty sequence
`

This is the command i use: `fontforge -script font-patcher.py MesloLGS\ NF\ Regular.ttf --custom codicon.ttf`

And this is the structure of the directory as explained [here](https://github.com/mortepau/codicons.nvim#how-to-patch-fonts)

![image](https://user-images.githubusercontent.com/11947421/204089950-124b78f5-c3e6-4185-a3af-a7373aa43210.png)

Expected behavior:

I expect to have a patched font being written in the directory.

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Meslo LGS NF Regular.ttf
   - _Where did you get the file from (download link, self patched, source downloaded from [link...)_
       - From [here](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/M/Regular/complete/Meslo%20LG%20M%20Regular%20Nerd%20Font%20Complete.ttf)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
    - Tilix 1.9.5
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
    - Linux Fedora 37

#### ★ Screenshots (Optional)

I'm trying to set up the nvim-dap ui package which requires the codicons. This is what is currently being displaced with the wrong icons:

![image](https://user-images.githubusercontent.com/11947421/204090233-dc4d216f-6c09-475e-9822-66037b388a0d.png)

**Comment by Finii** [comment]
Sorry to hear of the problem, and thanks for the report. This looks like a real bug.

Just one question: You take an already patched font (`Meslo LG M Regular Nerd Font Complete.ttf`) and patch it again?

Anyhow I will try to reproduce.

**Comment by Finii** [comment]
Ah now I get it. The linked manual as 'old', `codicons` is now part of the normal (complete) Nerd Font patch set, so there is no need to do what you try to do.

Anyhow I will try to reproduce.

**Comment by Finii** [comment]
The script is confused by the `.notdef` glyph

![image](https://user-images.githubusercontent.com/16012374/204091771-9f741b55-11a6-4d85-ad21-178ac32da93c.png)

Creating PR to fix.

Thanks again for reporting the bug.

And ... you do not need to self-patch, `codicons` are part of the Nerd Font set since [`v2.2.0`](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.2.0).
Although it's not the most current rev, but `codicons 1.5`, so maybe you want to do it anyhow. You will see the warnings, that patching has been skipped for most of the icons.
