### ISSUE TITLE
Overpass Mono Nerd Font spacing issues

### ISSUE THREAD

**Issue by TheKamboy** [ryanoasis/nerd-fonts#1007]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
The spacing of the letters is too big!

Expected behavior:
They should be closer together.

Example symbols:
Most likely all symbols

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Overpass Mono Regular Nerd Font Complete Mono Windows Compatible.otf
   - from this GitHub page
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ Windows Terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Windows 11

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/204127316-6217eb2c-04d1-4929-bde6-d3a77928a6f7.png)

**Comment by Finii** [comment]
Fixed in latest release (2.3.3)
