### ISSUE TITLE
[Feature Request] Add JuliaMono TypeFace to Nerd Fonts Projects

### ISSUE THREAD

**Issue by Atreyu-94** [ryanoasis/nerd-fonts#1011]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
 In the scientific context, many mathematical symbols that are present in the UNICODE format are used, but most monospaced fonts do not have support for these symbols.  However, the version of Nerd Fonts for this typeface does not yet exist.

**Describe the solution you'd like**
JuliaMono has extensive support for the UNICODE format, and each update adds more symbols.

**Describe alternatives you've considered**
 I don't know of any other typeface with such a wide Unicode support

**Additional context**
 The source website is: https://juliamono.netlify.app/
 The project's GitHub repository is: https://github.com/cormullion/juliamono

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
