### ISSUE TITLE
Add fonts to Microsoft Store

### ISSUE THREAD

**Issue by cglong** [ryanoasis/nerd-fonts#1013]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
It's annoying having to manually check for and download new versions of a patched font.

**Describe the solution you'd like**
It'd be great if Nerd Fonts were available for installation and auto-update via the Microsoft Store.

**Describe alternatives you've considered**
Occasionally checking for updates to the fonts I use, or perhaps setting up something like RSS to monitor changes to the repo.

**Additional context**
N/A

**Comment by Finii** [comment]
Is [Choko](https://chocolatey.org/) not working for you? (I have never used it.)

**Comment by Finii** [comment]
https://community.chocolatey.org/packages?q=nerd

**Comment by cglong** [comment]
Good find! I personally prefer [Scoop](https://scoop.sh/) over Chocolatey, and I see now there's [an official bucket](https://github.com/matthewjberger/scoop-nerd-fonts) containing these fonts 🙂

This definitely helps address the problem as listed in the issue, but I personally think the Microsoft Store would be more advantageous, due to its ubiquity and built-in support for autoupdates.

**Comment by Finii** [comment]
Thanks for the idea.
I have no clue how to do that, as detailed above.
Closing this for now.
