### ISSUE TITLE
Suggest shallow cloning of repo

### ISSUE THREAD

**Issue by zeorin** [ryanoasis/nerd-fonts#102]
Suggest in the docs that users clone the repo with `git clone --depth 1` if they're not looking to contribute and just want to get the fonts easily. Together with the improved install script from #101 this makes it real easy to get and stay up to date without wasting bandwidth or disk space.

**Comment by ryanoasis** [comment]
Good idea. Yes I looked again and it is still not clear that one does not need to clone the repo and if they contribute shallow should be sufficient. Thanks

**Comment by nowox** [comment]
+1
