### ISSUE TITLE
Add Input Mono font.

### ISSUE THREAD

**Issue by huge-pancake** [ryanoasis/nerd-fonts#1021]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add Input Mono (https://input.djr.com/).

**Describe alternatives you've considered**

**Additional context**
I can't patch fonts by myself so I'm here for a official addition.

**Comment by Finii** [comment]
There is this commit:

80587bfcd358e0c `Removed InputMono folder and misc files (font license issue)`

one would need to investigate if the license of InputMono changed meanwhile.

**Comment by Finii** [comment]
No, the license is still not allowing it

![image](https://user-images.githubusercontent.com/16012374/207418291-203a1556-6695-44ea-9c01-ed5beedccc3b.png)

and does so **very specifically**:

![image](https://user-images.githubusercontent.com/16012374/207418650-848f65bd-3fc4-4550-a91e-28bddd08d604.png)


That means: Sorry, but we are not allowed to distribute a patched version of the font, You have to patch it on your own.
Which is usually not complicated. See https://github.com/ryanoasis/nerd-fonts#font-patcher

**Comment by Finii** [comment]
You can ask in this Issue if you need help with self patching. I know the documentation is ... not perfect.
Please add information on your OS in case you ask.

**Comment by huge-pancake** [comment]
OK thank you.
I can not patch it by myself was just because I can not download any releases of this repo or just clone (too big, and in China, GitHub have no server, so it will be very slow).
I'll try to download with a proxy.

System info: Windows 11 Pro 22636
I was expected to patch fonts in Void Linux (WSL) because it is easier to download the dependence s.

**Comment by huge-pancake** [comment]
I finally did it!

**Comment by Finii** [comment]
> because I can not download any releases of this repo or just clone (too big

Usually you should not download / clone the repo. There is a zip file that contains everything you need:
https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/FontPatcher.zip

> because it is easier to download the dependencies.

The dependencies are just `fontforge` and `python`. I believe you could also use the docker container under Windows, but for that you need to setup the docker environment.

> I finally did it!

Great :tada: :+1:
