### ISSUE TITLE
Caskaydia Cove: some of symbols are not centered correctly

### ISSUE THREAD

**Issue by mrtnvgr** [ryanoasis/nerd-fonts#1022]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Some of symbols are not centered correctly.

Expected behavior:
All symbols are centered.

Example symbols:
"🌤️" "🌕"

Resolves: qtile/qtile#4062

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   -  Caskaydia Cove Nerd Font Complete (Bold).otf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - I tried files from website, latest release, master branch.
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - The issue appears in [qtile](github.com/qtile/qtile), not in terminal emulator.
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Linux

#### ★ Screenshots (Optional)

![](https://i.imgur.com/ECpjSL2.png)

![](https://i.imgur.com/O7sR33t.png)

**Comment by Finii** [comment]
Sorry to hear of your problems.

I do not fully grasp the problem yet. What do I see in the screenshots?

![image](https://user-images.githubusercontent.com/16012374/207422656-15d274d2-9301-4557-9b44-562994dae238.png)

In the upper one already the square brackets seem to far down? But the 'sun behind cloud' looks well centered with the `C`:

![image](https://user-images.githubusercontent.com/16012374/207423045-c711ca72-c30c-4d97-92b0-4c2ca80b86b6.png)

Hmm, or do you mean it should be one 'pixel' further down?

What is the other line showing?

And maybe you can fill in the symbols as TEXT and not images. They might or might not be displayed correctly in your browser, but I can use [1] to extract the codepoints in question. Maybe you can give the codepoints?

[1] https://onlineunicodetools.com/convert-unicode-to-code-points

Here is a different glyph (cant font yours) and it is centered vertically:

![image](https://user-images.githubusercontent.com/16012374/207425906-a70d6977-9a54-4ffb-b554-cf3b11ecb8ae.png)

Measured the square bracket's top and bottom are at y=1634 and y=-214.
The weather icon maxima are at y=1883 and y=-462.

So the weather icon is 249 more 'up' and 248 more 'down' which is as far centered as one gets with integers.

**Comment by utbrott** [comment]
I'm pretty sure it's just a visual "bug" that we have here, because of the weather icons being slightly less tall than the circle icon that's shown for comparison.

**Comment by Finii** [comment]
@utbrott Yes, I guess they mean that whole shift-up. As discussed in the `qtile` issue. But I see nothing that can be done from the font side, apart from using the `Nerd Font Mono` variant. I believe it is a quirk in font scaling on the client side.
