### ISSUE TITLE
Windows 11 powershell font

### ISSUE THREAD

**Issue by p6002** [ryanoasis/nerd-fonts#1023]
The font is too tight, no matter what type I choose. 
https://i.ibb.co/HTJGQTs/s-20221213-203742.png
How to fix it?

**Comment by 237dmitry** [comment]
In my environment this font (3270 NF) is normal width. But border symbols are not (only in Windows Terminal, in conhost is nice)

![pwsh](https://user-images.githubusercontent.com/78153320/207852538-ae081749-7fe8-44c1-bdd2-e4752dde0827.png)

![far](https://user-images.githubusercontent.com/78153320/207852568-b4040634-e592-42a8-b188-6b57e474168c.png)

**Comment by 237dmitry** [comment]
If this "narrow" font is only in Windows Terminal try to disable "Atlas Engine" font rendering.

**Comment by Finii** [comment]
@p6002 You seem to have the font with the broken small letter `m`:

![image](https://user-images.githubusercontent.com/16012374/209830273-69c01e8b-27d6-4f7b-b9d2-17bb16c931fa.png)

I remember a fix for that bug over at `fontforge` but I have forgotten the state.

You don't state which font you use. If you need help please fill in the whole Issue template :grimacing:
