### ISSUE TITLE
Caskaydia Cove: symbol alignment issue

### ISSUE THREAD

**Issue by mrtnvgr** [ryanoasis/nerd-fonts#1025]
#### 🗹 Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
![](https://i.imgur.com/SqYcgzq.png)

Expected behavior:
![](http://0x0.st/o5SF.png)

Example symbols:
-.-

Resolves: qtile/qtile#4066

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - CaskaydiaCove Nerd Font Bold
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Website
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - [qtile](https://duckduckgo.com/?q=qtile&ia=web)'s status bar
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Linux

**Comment by Finii** [comment]
Which Caskaydia version do you have?

**Comment by mrtnvgr** [comment]
> Which Caskaydia version do you have?

I have a week-old version

**Comment by Finii** [comment]
Thank you.

Ah I see, that is a coding ligature, deliberately added...:

![image](https://user-images.githubusercontent.com/16012374/208939027-455a345f-cdec-4bf2-b677-cba17dd79e6e.png)

https://github.com/microsoft/cascadia-code/wiki/Coding-ligature-coverage

**Comment by mrtnvgr** [comment]
Thank you for your fast responds! I guess I can close this issue?

**Comment by Finii** [comment]
Thanks :-)

You can see/test the ligatures if you use the font in `writer` or `Word` or whatever:

![Peek 2022-12-21 16-29](https://user-images.githubusercontent.com/16012374/208942267-3dea9f15-17e0-4f05-b503-807e962c15e4.gif)

They all aim to make code more readable. Note the small width changes. Even two-dots is not as wide as two single dots.
