### ISSUE TITLE
Roboto Mono: ș and ț characters look like zalgo

### ISSUE THREAD

**Issue by Secret-chest** [ryanoasis/nerd-fonts#1030]
They're used in Romanian.
![image](https://user-images.githubusercontent.com/74449186/209438289-c95110c3-e350-43ca-a7bb-62dc90c61241.png)
First one is ș, second is ț rendered in your font.

**Comment by Finii** [comment]
Codepoints `0219` ș and `21b` ț

These are not touched by Nerd Fonts at all.

Hmm, and it is contained in the current font (patched and unpatched):
![image](https://user-images.githubusercontent.com/16012374/209829401-d465b774-1430-481a-bddf-f1f8011da4ce.png)

Unfortunately you did not fill the Issue form completely.
Anyhow, it must be something with your setup and/or how you entered the glyphs?

Please reopen if you still feel there is a problem with the font(s), but we would need more information to help.
