### ISSUE TITLE
Fedora repo does not exist for Hack

### ISSUE THREAD

**Issue by TH3-S4LM0N** [ryanoasis/nerd-fonts#1031]
#### 🎯 Subject of the issue

Experienced behavior:
The package manager instructions for installing `Hack` for Fedora say to enable the `heliocastro/hack-fonts` copr project, but it doesn't exist.

Expected behavior:
N/A

Example symbols:
N/A

#### 🔧 Your Setup
None of these are applicable as you can't install it.

#### ★ Screenshots (Optional)
N/A

**Comment by Finii** [comment]
Sorry to hear that Fedora package seems to be broken.

Can you point me to the location where they day it? (Like a linkto that or something)
> package manager instructions for installing Hack for Fedora say

The Fedora packages are not even on 'my radar': https://github.com/ryanoasis/nerd-fonts/discussions/881#discussioncomment-3488054

Usually 3rd party packaging is done by other projects.

> `heliocastro/hack-fonts`

This sounds like the unpatched Hack, not the Nerd Font one, anyhow.

**Comment by TH3-S4LM0N** [comment]
Sorry I didn't make this clear, I don't see how contacting maintainer because there is no maintainer, as in this should be removed not fixed.

> Can you point me to the location where they day it? (Like a linkto that or something)
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack#package-managers

**Comment by Finii** [comment]
Ah now I get it. The copied 'original repo' page.
You are right, and/but it affects a lot of fonts.

**Comment by Finii** [comment]
Fixed (by removing)
* c9ba9f88df6d  `Unify all source READMEs`
