### ISSUE TITLE
Font patcher

### ISSUE THREAD

**Issue by girishji** [ryanoasis/nerd-fonts#1034]
Regarding using font patcher, does it have dependencies and need that the whole repository be cloned?
Please add some information to  the readme page.

**Comment by Finii** [comment]
Which language readme are you refering to?

In the english one the dependencies are given here: https://github.com/ryanoasis/nerd-fonts#font-patcher
* Python
* `python-fontforge`

----

>  need that the whole repository be cloned?

![image](https://user-images.githubusercontent.com/16012374/210425526-a9a45007-92be-4ae0-833c-a4200e0b9b7a.png)

----

Depending on your OS I would recommend
* Using the `font-patcher` docker: https://hub.docker.com/r/nerdfonts/patcher
* Using the `FontPatcher.zip` that contains a snapshot of this repo with all needed to patch: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.0-RC/FontPatcher.zip

Note that the docker container is always up-to-date (i.e. `HEAD`), while the zip is bound to the release cycle.

---

In total I do not know which information shall be added? (Except you talk about the readme translations).
The zip file is missing from the readme, that is true. Volunteers to write something welcome.

**Comment by Finii** [comment]
No answer.
