### ISSUE TITLE
Cannot use OTF fonts for conhost, requires showing all fonts in Windows Terminal

### ISSUE THREAD

**Issue by heaths** [ryanoasis/nerd-fonts#1035]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
CaskaydiaCove Windows Compatible NF does not show up for conhost.exe, and only the Mono fonts (no ligatures) show up for Windows Terminal. Looking at existing bugs, this has been reported quite a few times and was apparently fixed, though subsequent comments say it still occurs.

Looking at #994 it seems this could be because OTF isn't well-supported. Could a TTF download be offered as well, if not a combination of OTF and TTF. IIRC, some fonts used to be distributed that way: both in an archive, though I may be thinking of a different forge.

Expected behavior:
CaskaydiaCove NF fonts show up everywhere I'd like to use them: conhost.exe, wt.exe, code.exe, etc.

Example symbols:
N/A

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Several in a font family e.g., "Caskaydia Cove Nerd Font Complete Windows Compatible Regular.otf"
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - This site via direct download.
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - conhost.exe and wt.exe
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows

**Comment by Finii** [comment]
Hmm, the fastest solution four you would be to switch to https://github.com/adam7/delugia-code instead.
That is (as `Caskaydia`) a Nerd Font patch of `Cascadia`, but all `ttf`.

The problem with `ttf` vs `otf` is ... well, `ttf`s lacks some features that `otf`s have, that some people expect.
Of course Nerd Font could deliver the patched fonts in both formats, but that raises other issues, mostly related to packaging.

**Comment by heaths** [comment]
Thanks for the referral, and about the note you left on the linked issue: that's a fair point. I've seen it before years back with some Powerline fonts, but as you noted: one has to be careful not to install both.

Ideally, Windows would fix whatever isn't working correctly with OTF; though, it sounds more like it has to do with variable width fonts sneaking in. Nerd Font wouldn't do that itself, would it? Perhaps it was already there. I'm not really a font person, though, so any guesses are based more on what I was reading on various sites related to this problem.

At any rate, it's only been a problem with conhost.exe terminals which I almost never use - especially since Windows 11 started supporting either conhost.exe wt.exe (to which I set wt.exe, of course :).

**Comment by Finii** [comment]
> variable width fonts sneaking in. Nerd Font wouldn't do that itself, would it?

Nerd Fonts is using Fontforge, and that can not (*) work with variable fonts. So it's impossible to patch VFs with `font-patcher`, see also
* #960

(*) Well, it can, but not really ;-D

**Comment by heaths** [comment]
Thanks. There was a few other issues about font capabilities I didn't fully grok (I know font files declare various caps, but that's about it) so perhaps it's something there. Whatever the case, I hadn't traditionally seen those with TTFs on Windows. Even in Windows Terminal, for some reason I only see the "Mono" variations of CaskaydiaCode show up by default, but since I like the ligatures I have to check a box to show all fonts. conhost.exe doesn't support that, but "Mono" variations don't show up either. Again, though, I don't really care about conhost.exe since I try to avoid it.

**Comment by Finii** [comment]
> Even in Windows Terminal, for some reason I only see the "Mono" variations of CaskaydiaCode show up by default,

That is because the terminal assumes some kind of 'grid' of chars that means all chars have to be of equal width (i.e. 'monospaced'). Terminals that can handle non-monospaced fonts and still keep 'the grid' have to do something more.

> but since I like the ligatures I have to check a box to show all fonts

Ligatures is orthogonal to 'monospaced'. I mean, this is completely unrelated. And both ttf and otf can have ligatures.

**Comment by Finii** [comment]
`Nerd Font Mono` means the symbols fit into one monospace cell.
`Nerd Font` is still monospaced but the symbols extrude to the right into the neighboring cell to get bigger symbols.

The character 'width' can differ from the real bounding box.

Maybe of interest
* #969 
* #951
