### ISSUE TITLE
Error when using Docker

### ISSUE THREAD

**Issue by arcdigital** [ryanoasis/nerd-fonts#1042]
#### 🎯 Subject of the issue

Experienced behavior:
Trying to patch fonts using docker, but it errors out.

Expected behavior:
Fonts are patched successfully.

Error:
```
$ docker run -v /path/MonoLisa/ttf:/in -v /path/patched/ttf:/out nerdfonts/patcher
Running with options:
Error relocating /usr/bin/fontforge: FindProgRoot: symbol not found
```

This happens with all the MonoLisa fonts (the error repeats for each file found) as well as FiraCode. Since the error shows up multiple times if I put multiple files in the directory, it seems to be reading the fonts fine.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - MonoLisa-Regular.ttf
   - I also tried FiraCode-Regular.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - From the MonoLisa website
   - https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - probably not relevant since i'm using docker...but iterm2
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - macOS Ventura, arm64, docker

**Comment by Finii** [comment]
Hmm, `FindProgRoot()` is in `gutils` of `fontforge`, I first thought it might be a `libfontforge.so` problem but it seems no.

**Comment by Finii** [comment]
Hmm, Alpine already updated to Fontforge Jan 2023 Release, maybe that is broken.

**Comment by arcdigital** [comment]
Yep, no fonts at all - at first I thought maybe it was the MonoLisa font specifically, but then I tried FiraCode since that one  should definitely work and had the same issue.

Are you seeing the same issue on amd64? I tried adding `--platform linux/amd64` to my `docker run` command and I'm still getting the same error, but the docker amd64 emulation doesn't always work properly...so it could still be an arm specific issue.

**Comment by Finii** [comment]
That seems to be a broken `fontforge` built in Alpine.... also on amd64:

![image](https://user-images.githubusercontent.com/16012374/211532019-bdd8d0f0-4427-4aeb-8390-0701945b2d22.png)

**Comment by Finii** [comment]
Works on `amd64` now. Can you check on `arm`?

Thanks for reporting.

**Comment by arcdigital** [comment]
Yep, working now for me as well! Thanks for the quick fix!
