### ISSUE TITLE
OverpassMono isn't spacing lines

### ISSUE THREAD

**Issue by marshallishere** [ryanoasis/nerd-fonts#1043]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

The OverpassMono doesn't seems to have the spacement that Overpass Mono normally has.

Expected behavior:

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Overpass Mono Regular Nerd Font Complete Mono.otf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - The oficial website
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - [foot](https://codeberg.org/dnkl/foot)
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Fedora Workstation 37
#### ★ Screenshots (Optional)

![Captura de tela de 2023-01-10 11-53-07](https://user-images.githubusercontent.com/110747746/211586192-70602b3b-b110-4fc7-8c17-5bdf85209000.png)

**Comment by Finii** [comment]
Just from the look of it I assume the difference comes from the fact that the original has a `linegap` of 266 (open space without anything between lines).

This should have been fixed by #943.

Before I dive into your problem, can you give me the font's version number?

**Comment by Finii** [comment]
Hmm, on `master` the vertical spacing seems to be ok, but the horizontal spacing... ??!

![image](https://user-images.githubusercontent.com/16012374/211621150-bb44db7b-6c23-4537-a0d1-cc3bf6d3776b.png)

Lets see how it turns out if we patch with the latest patcher?

![image](https://user-images.githubusercontent.com/16012374/211621789-d67449fa-7d36-4308-9a19-b02727831faa.png)

**Comment by Finii** [comment]
Overpass Mono is not monospaced :-(

![image](https://user-images.githubusercontent.com/16012374/211625653-ec0841eb-5731-45cc-bf8c-ac0181337699.png)

Ah, its the IJ-ligature:

![image](https://user-images.githubusercontent.com/16012374/211627962-a5e17152-70b7-4e6e-bb79-4054bf441c34.png)

**Comment by Finii** [comment]
So maybe you have `v2.2.2` or even older font installed.
Can you try `v2.3.0-RC` https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.0-RC/Overpass.zip
and see if the **vertical** problem is gone there? The **horizontal** problem will be fixed with PR above.

**Comment by marshallishere** [comment]
My spacing issue is now fixed. Thanks!
