### ISSUE TITLE
Broken links on 'nerd-fonts/patched-fonts/Hack/readme.md'

### ISSUE THREAD

**Issue by PeterMortensen** [ryanoasis/nerd-fonts#1049]
#### Broken links on 'nerd-fonts/patched-fonts/Hack/readme.md'

All five links in sub section *"A typeface designed for source code"* in the [nerd-fonts/patched-fonts/Hack/](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack) "readme.md" are broken (*"Bitstream Vera"*, *"DejaVu"*, *"changelog"*, *"CONTRIBUTING.md"*, and *"FAQ"*).

**Comment by Finii** [comment]
Thanks for reporting!

**Comment by Finii** [comment]
(In fact that is 'just a copy' of the README.md of `Hack`. Imho it should not be there at all, because it leads to all the unpatched fonts; but that is how historically all patched-fonts READMEs look like. I guess that should be changed for all fonts.)

**Comment by Finii** [comment]
Tried a new 'format' with
* Iosevka https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Iosevka
* Mononoki https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Mononoki

We should not copy the upstream pages I believe; just state which version we use and link the page.
If you have time, maybe have a look and tell me what you think. Can change all other fonts then.
