### ISSUE TITLE
JetBrainsMono v2.304 released

### ISSUE THREAD

**Issue by jaywonchung** [ryanoasis/nerd-fonts#1050]
JetBriainsMono released [v2.304](https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.304), the first release since Jul 30, 2021.
It'd be great if the new font can be patched an updated here.

Thanks a lot!

**Comment by Finii** [comment]
Thanks for the information.

I will try to squeeze it in with the imminent `v2.3.0` release.
