### ISSUE TITLE
Windows Compat name comes out as "NF" and "NF Mono"

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#1054]
> @Finii I just updated to 2.3.0 NF fonts and Mononoki's mono font has been renamed from "Mononoki NFM" to "Mononoki NF Mono". Not sure why this was necessary when the other NF fonts on my system still use "NFM" in their name, or perhaps this was a mistake? The past two times NF's Mononoki has updated I've had to fiddle with application font settings to get things working again.

_Originally posted by @redactedscribe in https://github.com/ryanoasis/nerd-fonts/issues/575#issuecomment-1387118726_
            

This is a bug.

It should be one of
* `Nerd Font`
* `Nerd Font Mono`
* `NF`
* `NFM`

Maybe I put the fix into #1028, lets check

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/213192843-13fcee22-796f-422c-ae32-3068894628ad.png)

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/213193211-3211a5c0-ad3d-42ec-92b5-75c30e2132aa.png)

![image](https://user-images.githubusercontent.com/16012374/213193327-d7a2212f-a2a9-4edc-a4ee-47d436a1d6fb.png)

**Comment by Finii** [comment]
Affected: All `--makegroups` fonts.

i.e.
* Cascadia Code
* Iosevka
* JetBrains Mono
* mononiki

**Comment by Finii** [comment]
Fonts come out correct now.
I will do a bugfix release later, have to fetch my kids now, srry

**Comment by Finii** [comment]
@redactedscribe How did you update? First I thought via Casks, but the you would not have Windows Compat fonts...

I guess (hope) we do not need to release `v2.3.1` but can live with a patched release :grimacing:

**Comment by redactedscribe** [comment]
I used Scoop. A patched release means just reloading the same 2.3.0 which is now fixed?

**Comment by Finii** [comment]
I have right now no clue how Scoop works :grimacing: 

I'm sitting in the car, patcher is running, will upload fixed fonts afterwards via mobile data which can take time.
Then the fonts are at least correct in the repo.

Afterwards I want to re-package the zip files, but that is even more data and so that will probably not happen while I'm on the go but in two hours or so. Then I can inject the new zip archives into the `v2.3.0` release, so that at least it looks smoothly afterwards.

I hope not many packagers already did update.
Except Cask, which I updated, but that I can fix. The casks check the zip file sha256sums...

**Comment by redactedscribe** [comment]
For GitHub releases, Scoop checks the releases page every so often for a version number greater than it last saw. Fixing the archive will likely make Scoop complain that the checksums no longer match. If it's just for a handful of fonts, it should be easy enough to put in some PRs for the [scoop-nerd-fonts bucket](https://github.com/matthewjberger/scoop-nerd-fonts/tree/master/bucket). Maybe @jonz94 knows more.

**Comment by Finii** [comment]
Reasons for the issue:

I intended to also put #1028 into the `v2.3.0` release. I checked all the resulting fonts.
But shortly before release I though #1028 should wait until `v3.0.0` as this renames things which should be a major release.
So I backed off.

But one of the commits in that PR was vital for this release (see above).
Once mentioned I immediately recognized the commit, and found out it has not made it into the release.
Sigh. Sorry!

**Comment by Finii** [comment]
Maybe a `v2.3.0p1` :thinking: 

This is what I would do at work, do not know if all packagers know such version number constructs.

**Comment by Finii** [comment]
[Release v2.3.1](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.1)

**Comment by redactedscribe** [comment]
Thanks a bunch @Finii. Back to Mononoki NFM. Minor issue: The font versions weren't updated as far as I can tell. They all still read 2.3.0. A lot of moving parts. It happens.

**Comment by Finii** [comment]
> They all still read 2.3.0

That was deliberate (*). Anyhow I expect `v2.3.1` to be rather short lived anyhow.
With `v2.2.0` we got a `v2.2.1` and `v2.2.2` in short succession.
This is not really a bug but rather a glitch in the naming I'd say. But there will come real bug reports in, I'm sure, and for that we anyhow need to repatch all fonts.

Whatever ;)

===

(*) Maybe the reasoning seems flawed in retrospection, but it was along these lines:
* I dont want a 2.3.1 but rather a 2.3.0-p1
* I dont know if packaging systems can work with such a number, so
* Use 2.3.1 as fancy way to say 2.3.0.p1 - as release version but not in the fonts - to trigger packagers updates
* Internally use as much as possible of the 2.3.0 fonts to avoid
  * time consuming repatching of all font files
  * faster but error prone version editing of all font files
  * having the smallest possible commit (the repo is so large already)
* Reuse 2.3.0's zip archives for the bugfix release
* That fonts have version 2.3.0
* Keep the few newly generated font files at the same version number for 'consistency'
* /shrug ;-)
