### ISSUE TITLE
Scaling inconsistency between text and glyphs

### ISSUE THREAD

**Issue by dstoliker** [ryanoasis/nerd-fonts#1056]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
After upgrading to the latest version of the Hack nerd font via homebrew, there is an an apparent inconsistency between text and glyph scaling. I have a command line prompt configured with Oh My Posh with powerline symbols. After upgrading my font to the latest version, the glyphs no longer line up vertically. The glyphs are now taller. See screenshots below.

Expected behavior:
Text and glyphs should align as they did before the upgrade.

Example symbols:
\ue0b6
\ue0b4

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Hack Regular Nerd Font Complete.ttf_
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Mac cask homebrew install
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - iterm2
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - MacOS 12.6.2 (Monterey)

#### ★ Screenshots (Optional)

Powerline bar as it appeared before font package upgrade:
<img width="205" alt="before update" src="https://user-images.githubusercontent.com/30450350/213335703-b24cba6d-3ce8-46e8-9c6f-921d4febeca9.png">

After upgrade:
<img width="214" alt="after update" src="https://user-images.githubusercontent.com/30450350/213335736-166c11b5-11f9-4b95-bd72-e7ecb1d24b0a.png">

iTerm2 font settings:
<img width="565" alt="font settings" src="https://user-images.githubusercontent.com/30450350/213335769-c52cc7b7-e110-4915-b798-844a66b8d667.png">

**Comment by Finii** [comment]
Sorry to hear that. Can see the differences...

![image](https://user-images.githubusercontent.com/16012374/213361008-8776149d-31d3-444d-a403-ae001af852f5.png)

**Comment by Finii** [comment]
Thanks for reporting. And thanks for a complete report with all the details I need to reproduce :+1:

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/213361769-bdb43f57-e799-4531-845d-22424cd786c8.png)

**Comment by Finii** [comment]
Oh man, do I hate the metrics inconsistencies :unamused: 

And whats this
![image](https://user-images.githubusercontent.com/16012374/213363244-01f6727a-6d57-42c7-bfaf-ab523cf3adc6.png)

**Comment by Finii** [comment]
On my machine with `tilix`

![image](https://user-images.githubusercontent.com/16012374/213379037-c89c0752-6c6a-4a55-aace-08f88683abdc.png)

When I can see it, it should be 'easy' to fix.

**Comment by Finii** [comment]
Systematic examination of all source fonts regarding vertical metrics, one file of each font chosen at random.



```
find src/unpatched-fonts -iname '*.[ot]tf' | \
  sed -E 's! !\\!g;s!([^/]*/[^/]*/[^/]*).*!\0 \1!' | \
  sort | uniq -f 1 | sed 's! .*!!;s!\\! !g;s!^!"!;s!$!"!' | \
  xargs font-line report
```

| Font | hhea/UPM | typo/UPM | win/UPM | use typo metrics | gap | win/mac |note |
|---|---|---|---|---|---|---|---|
| 3270 | 1.09 | 1.0 | 1.09 | X | X | :red_square:  | forgot to set typo-gap? |
| Agave | 1.12 | 1.0 | 1.12 | X || :red_square: ||
| Anonymous | 1 | 1 | 1 ||| :heavy_check_mark: ||
| Arimo | 1.15 | 1.09 | 1.15 || X | :heavy_check_mark: ||
| Aurulent | 1.3 | 1.09 | 1.3 ||X| :heavy_check_mark: ||
| BigBlue | 1 | 1 | 1 | X || :heavy_check_mark: ||
| Bitstream Vera | 1.16 | 1.2 | 1.16 || X | :heavy_check_mark: ||
| Cascadia | 1.16 | 1.16 | 1.32 | X || :heavy_check_mark: ||
| CodeNewRoman | 1.17 | 1.17 | 1.17 || X | :heavy_check_mark: ||
| Couisine | 1.13 | 0.842 | 1.13 ||| :heavy_check_mark: ||
| DaddyTime | 1.25 | 1.25 | 1.25 | X || :heavy_check_mark: ||
| DejaVu | 1.16 | 1.2 | 1,16 || X | :heavy_check_mark: ||
| Droid | 1.16 | 1.07 | 1.16 || X | :heavy_check_mark: ||
| Fantasque | 1.05 | 1.05 | 1.05 | X | X | :heavy_check_mark: ||
| Fira | 1.23 | 1.23 | 1.23 | X || :heavy_check_mark: ||
| Fira Mono | 1.4 | 1.4 | 1.4 || X | :heavy_check_mark: ||
| Gohu | 1.18 | 1.18 | 1.18 | X | X | :heavy_check_mark: ||
| Go Mono | 1.16 | 1.16 | 1.16 || X | :heavy_check_mark: ||
| **Hack** | 1.16 | 1.2 | 1.16 || X | :heavy_check_mark: ||
| Hasklig | 1.26 | 1 | 1.26 ||| :heavy_check_mark: ||
| HeavyData | 1.15 | 1.09 | 1.15 || X | :heavy_check_mark: ||
| Hermit | 1.56 | 1.09 | 1.56 | X | X | :red_square: ||
| iA writer | 1.3 | 1.3 | 1.3 || X | :heavy_check_mark: ||
| IBM Plex | 1.3 | 1.3 | 1.3 || X | :heavy_check_mark: ||
| InconsolataGo | 1.05 | 1.05 | 1.05 ||| :heavy_check_mark: ||
| Inconsolata | 1.05 | 1.05 | 1.46 | X || :heavy_check_mark: ||
| Inconsolata LGC | 1.46 | 1 | 1.46 || X | :heavy_check_mark: ||
| Iosevka | 1.25 | 1.25 | 1.25 | X | X | :heavy_check_mark: ||
| JetBrains Mono | 1.32 | 1.32 | 1.32 | X || :heavy_check_mark: ||
| Lekton | 1 | 1 | 1.7 ||| :red_square: ||
| Liberation | 1.13 | 0.842 | 1.13 ||| :heavy_check_mark: ||
| Lilex | 1.3 | 1.3 | 1.3 || X | :heavy_check_mark: ||
| Meslo | 1.55 | 1.59 | 1.55 || X | :heavy_check_mark: ||
| Monofur | 1 | 1 | 1 | X || :heavy_check_mark: ||
| Monoid | 1.33 | 1.33 | 1.33 | X || :heavy_check_mark: ||
| Mononoki | 1.12 | 1.2 | 1.12 || X | :heavy_check_mark: ||
| M+ | 1.49 | 1.09 | 1.49 || X | :heavy_check_mark: ||
| Noto | 1.17 | 1.17 | 1.17 ||| :heavy_check_mark: ||
| OpenDyslexic | 3.58 | 1.94 | 3.58 ||| :heavy_check_mark: ||
| Overpass | 1.53 | 1.27 | 1.53 | X | X | :red_square: ||
| ProFont | 1.23 | 1.23 | 1.23 ||| :heavy_check_mark: ||
| ProggyClean | 0.812 | 1 | 0.812 ||| :heavy_check_mark: ||
| Roboto | 1.17 | 1.05 | 1.2 || X | :red_square: | 'alomst ok' |
| ShareTech | 1.13 | 1.13 | 1.13 ||| :heavy_check_mark: ||
| SourceCode | 1.26 | 1 | 1.26 ||| :heavy_check_mark: ||
| SpaceMono | 1.48 | 1.48 | 1.48 | X || :heavy_check_mark: ||
| Terminus | 1.1 | 1.09 | 1.1 | X | X | :red_square: | 'almost ok' |
| Tinos | 1.15 | 1.04 | 1.15 || X | :heavy_check_mark: ||
| Ubuntu | 1.15 | 1.02 | 1.15 || X | :heavy_check_mark: ||
| Ubuntu Mono | 1 | 0.907 | 1 || X | :heavy_check_mark: ||
| Victor Mono | 1.41 | 1.41 | 1.41 | X | X | :heavy_check_mark: ||


Most crucial is that WIN does use the other gaps?! See https://learn.microsoft.com/en-us/typography/opentype/spec/recom#baseline-to-baseline-distances

**Comment by Finii** [comment]
I will combine this with #1055

**Comment by Finii** [comment]
Problematic cases:

* 3270
* Agave
* Hermit
* Lekton [1]
* Overpass
* Roboto
* Terminus

[1] Mismatch detected, defaults to TYPO should use WIN

**Comment by tjapro** [comment]
Sorry, to ask this here but I cannot find what I want ...

@dstoliker Where/What is these glyphs (the ones right in the line begining)?

![image](https://user-images.githubusercontent.com/7900361/215814063-6de10530-b91b-4b23-bc77-28d7a01f9c5f.png)

**Comment by Finii** [comment]
This rounded line? At `2570`:

![image](https://user-images.githubusercontent.com/16012374/215821345-6d4bcc83-c878-44d3-9fc8-b7a8c3f6b35d.png)

**Comment by Finii** [comment]
While doing `v3.0.0` ... Lekton is still problematic, too big gaps between lines:

![image](https://user-images.githubusercontent.com/16012374/235376038-0b4e6c27-9a9d-4a01-bc97-98929d25a7df.png)

Lets have a look at the table from above:

![image](https://user-images.githubusercontent.com/16012374/235376067-3e5bcbef-e28f-4015-bdd1-26a1a3019563.png)

Lekton was the only font that selected TYPO but we forced it to WIN, because not all glyphs fit into the values from TYPO.
But that seems to be wrong. Examining the glyphs that are really bigger than the TYPO line spaces, these are only graphical glyphs that shall span multiple lines. So I guess we should revert that change and render Lekton with the TYPO values.
