### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by peter73421** [ryanoasis/nerd-fonts#106]
by installing single fonts I,m getting:

:~/nerd-fonts# ./install.sh Hack
Fontconfig warning: "/etc/fonts/conf.d/10-powerline-symbols.conf", line 1: unknown element "html"
Fontconfig warning: "/etc/fonts/conf.d/10-powerline-symbols.conf", line 1: unknown element "body"
Fontconfig warning: "/etc/fonts/conf.d/10-powerline-symbols.conf", line 1: unknown element "a"
Fontconfig error: "/etc/fonts/conf.d/10-powerline-symbols.conf", line 1: invalid attribute 'href'

can you help or fix where is problem?

Thank you.

**Comment by ryanoasis** [comment]
1. Do you get that message only on the install script?
2. Does the font actually install (copy)?
3. Can you try to run other bash scripts to see if you get similar fontconfig warnings and errors?

The install script (before the much more advanced one recently merges see #101) simply copies files from the repo to the OS specific appropriate fonts folder.

Quick search, this could be similar/possibly related: https://bbs.archlinux.org/viewtopic.php?id=186894

But as of now I do not see this being something to do with Nerd Fonts itself :relaxed:

**Comment by ryanoasis** [comment]
@peter73421 I am closing this for now. Feel free to follow up if you still have the issue or any questions. Thanks

I am fairly certain this is not an issue with Nerd Fonts itself
