### ISSUE TITLE
Existing dot-braille looks bad. Let's switch to block-braille. 

### ISSUE THREAD

**Issue by clort81** [ryanoasis/nerd-fonts#1064]
I have an issue with existing nerd fonts, as they use dot-shaped braille characters, versus the block-shaped characters of textart fonts.
![braille_chars](https://user-images.githubusercontent.com/51511737/213897622-959fc47b-b020-4692-9c6b-db09d263be80.png)
[braille_chars.ans.gz](https://github.com/ryanoasis/nerd-fonts/files/10473587/braille_chars.ans.gz)

I have noticed that people who view braille characters on monitors are not blind, so the use in textart is greater for them than the use in reading the language for the blind.

I provide examples here showing how block-braille is preferable.

Sample info display in terminal, 74 columns wide.
![dotbraille_vs_block_braille-menus](https://user-images.githubusercontent.com/51511737/213896045-91f5427a-909e-45c5-ae1d-23fd0a3736ce.png)
Sample text menu for comparison with your fonts is attached here.
[fancy_monitor2.txt.gz](https://github.com/ryanoasis/nerd-fonts/files/10473521/fancy_monitor2.txt.gz)

![dotbraille_vs_block_braille-art](https://user-images.githubusercontent.com/51511737/213896049-a790db20-3c53-404f-ba32-12f09bcc57e7.png)
[aubrey_de_grey.ans.gz](https://github.com/ryanoasis/nerd-fonts/files/10473569/aubrey_de_grey.ans.gz)

![dotbraille_vs_block_braille-art2](https://user-images.githubusercontent.com/51511737/213896432-4b8c2837-3945-43d6-9585-99c411e5d9c9.png)
[flowergirl.ans.gz](https://github.com/ryanoasis/nerd-fonts/files/10473571/flowergirl.ans.gz)

Here's a screenshot from a classic MS-DOS game from the '90s, in a 160 column terminal.
![dotbraille_vs_block_braille-game](https://user-images.githubusercontent.com/51511737/213896580-d774990b-861b-448e-b24a-194e661c057c.png)
Sample text is here for your own tests:
[wcsample.ans.gz](https://github.com/ryanoasis/nerd-fonts/files/10473548/wcsample.ans.gz)

All text converted with https://hpjansson.org/chafa/
https://github.com/hpjansson/chafa

Sample fonts with block-braille can be found here.
http://viznut.fi/unscii/
I have patched terminus-12 bitmap, but cannot patch truetype fonts.

Please spread the word to font designers and other font projects.
Also users of 'kitty' terminal will find that the software substitutes it's own drawing for braille and block-art glyphs, making it useless for this application.

**Comment by Finii** [comment]
Actually Nerd Fonts does **not** patch in any Braille glyphs.
If you have a patched font that contains Braille glyphs they are 'inherited' from the original/unpatched font.

So we can not 'switch', we can only 'introduce', which is #837.

**Comment by Finii** [comment]
The new Braille feature lets you choose between `circle`, `rectangle` and `gapless`

* #1980
