### ISSUE TITLE
Is there a flutter version?

### ISSUE THREAD

**Issue by swordbe** [ryanoasis/nerd-fonts#1066]
The project is great. Is there a flutter version? Flutter is an open source mobile application software development kit developed by Google for developing applications for Android, iOS, Web, Windows, macOS, Linux Desktop, Google Fuchsia. Flutter is making efforts to games, Metaverse, and web3. ![flutter](https://user-images.githubusercontent.com/122947293/213731917-caf3dfd0-db1d-4b1c-ba21-85d8f0985396.png) https://github.com/flutter/flutter 项目非常棒 有flutter版本吗？Flutter是一个由谷歌开发的开源移动应用软件开发工具包，用于为Android、iOS、Web、We'bWindows、macOS、Linux Desktop、Google Fuchsia开发应用。 Flutter正在向游戏、元宇宙、web3发力。

**Comment by Finii** [comment]
I believe: no.

Also can't see how this would fit into a dev kit. :thinking: 

Anyhow, all 'packaging' for Nerd Fonts is done by other individuals outside this repo. Feel free create a 'flutter package' and we can put it (a link to it) on the homepage.

**Comment by Finii** [comment]
I must say ...
What is this? And I even put energy into the answer...
Spamming hundredths of repos with the same question? :-(

![image](https://user-images.githubusercontent.com/16012374/213982664-33b8a78c-f311-43da-8768-3b6fb1d07f74.png)
