### ISSUE TITLE
v2.3.2 Symbols-{1000,2048}-em Nerd Font Complete.ttf breaks layout

### ISSUE THREAD

**Issue by amezin** [ryanoasis/nerd-fonts#1069]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
After upgrade from v2.3.1 to v2.3.2, the layout of Firefox UI seems broken: in some places - a lot more whitespace than before, or text incorrectly offset to the bottom. Also affects some websites.

Removal/downgrade of the packages: [ttf-nerd-fonts-symbols-1000-em](https://archlinux.org/packages/community/any/ttf-nerd-fonts-symbols-1000-em/) or [ttf-nerd-fonts-symbols-2048-em](https://archlinux.org/packages/community/any/ttf-nerd-fonts-symbols-2048-em/) fixes the problem.

Expected behavior:
No change after package upgrade

Example symbols:
N/A. Lables without any special symbols are affected.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Symbols-1000-em Nerd Font Complete.ttf
   - or Symbols-2048-em Nerd Font Complete.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Arch Linux packages: [ttf-nerd-fonts-symbols-1000-em](https://archlinux.org/packages/community/any/ttf-nerd-fonts-symbols-1000-em/), [ttf-nerd-fonts-symbols-2048-em](https://archlinux.org/packages/community/any/ttf-nerd-fonts-symbols-2048-em/)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - No issues in the terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Arch Linux (rolling)

##### GitHub

Before:

![Screenshot from 2023-01-24 09-28-20](https://user-images.githubusercontent.com/1273397/214235321-32c8c8b2-6bc5-41ad-bd0c-7a58f32714c5.png)

After:

![Screenshot from 2023-01-24 09-25-40](https://user-images.githubusercontent.com/1273397/214235355-b00290de-160e-41cc-b713-5f781802beeb.png)

##### Firefox tabs and address bar

Before:

![Screenshot from 2023-01-24 09-28-54](https://user-images.githubusercontent.com/1273397/214235146-381bbe6c-a52f-4739-8f30-d9c3d5651fa4.png)

After:

![Screenshot from 2023-01-24 09-24-14](https://user-images.githubusercontent.com/1273397/214235112-8be38ba3-a360-4306-ba80-c2de8d469e36.png)

##### Firefox menu

Before (fits on screen):

![Screenshot from 2023-01-24 09-22-21](https://user-images.githubusercontent.com/1273397/214234801-d57ace8b-9acb-4b0f-b5c3-1cdc235b2a8d.png)

After (doesn't fit on screen):

![Screenshot from 2023-01-24 09-23-39](https://user-images.githubusercontent.com/1273397/214234840-5d29a000-bd2c-4ece-8914-866a8f4a2479.png)

**Comment by Finii** [comment]
Do you have the `2.3.2-1` package (or without `-1`)?
I wanted to download the package, can not find a download link quickly, maybe you have a tip?

**Comment by Finii** [comment]
>  I wanted to download the package, can not find a download link quickly, maybe you have a tip?

Found it ;-)

**Comment by Finii** [comment]
Ah I see...

The package needs a `2.3.2-2`, will try to reach the maintainer.

**Comment by Finii** [comment]
@polyzen I guess you are the maintainer of [ttf-nerd-fonts-symbols-2048-em](https://archlinux.org/packages/community/any/ttf-nerd-fonts-symbols-2048-em/)

Can you please do a repackage of both Symbols Only fonts? You were too fast, I fixed a bug in the Symbols Only font right after release and changed the release zip file, but obviously not fast enough. Yes, I would normally have done `2.3.3` or `2.3.2-p1` release, but I thought I was ahead of the packagers ;-)

![image](https://user-images.githubusercontent.com/16012374/214239177-4eb32b31-64ad-4206-8a35-547b2285a688.png)

**Comment by Finii** [comment]
@amezin Do you know a better way to reach [Daniel M. Capella](https://archlinux.org/packages/?maintainer=polyzen)?

**Comment by Finii** [comment]
:thinking: .o(  I really really hate how the Nerd Fonts releases work  )

If we can not sort this out 'soon' (whatever this means) I can push out a new release and hope that it triggers an automatic rebuild of the arch package.

**Comment by amezin** [comment]
> @amezin Do you know a better way to reach [Daniel M. Capella](https://archlinux.org/packages/?maintainer=polyzen)?

No.

I've opened a bug report in Arch Linux too: https://bugs.archlinux.org/task/77254

**Comment by Finii** [comment]
It breaks 'everywhere'. I noticed the problem right after release when the Nerd Fonts webpage used the new font and it was bOrkeN. That's why I fixed it immediately and (just) changed the archive file.

**Comment by freswa** [comment]
Hey,
another ArchLinux maintainer here. I ran into this issue as well and woul like to help out. Though, we're loading the fonts from e.g. `https://raw.githubusercontent.com/ryanoasis/nerd-fonts/v$pkgver/patched-fonts/NerdFontsSymbolsOnly/complete/Symbols-1000-em%20Nerd%20Font%20Complete.ttf` where the archive doesn't really matter. Could you pull a `2.3.2.1` or `2.3.3` release please?

In my experience fixing bugs in releases is a rabbit hole. Better pull another release and keep the release of shame than trying to fix it. We run into this kind of things more often then we'd like to :)

Your efforts maintaining this repo are much appreciated. I love the font collection :+1:

**Comment by Finii** [comment]
Ok, let me fix the missing license files (code is like 10 years old), and then I re-release.

**Comment by polyzen** [comment]
> @amezin Do you know a better way to reach [Daniel M. Capella](https://archlinux.org/packages/?maintainer=polyzen)?

Pinging me on GitHub is sufficient, you could also [use my email or IRC](https://archlinux.org/people/trusted-users/#polyzen).

> @amezin Please check 2.3.3 in [community]

@freswa, the packages didn't make it all the way to the repos, but that's resolved now. :p

**Comment by Finii** [comment]
See
* #1073

**Comment by amezin** [comment]
`ttf-nerd-fonts-symbols-2048-em 2.3.3-1` doesn't cause any issues now

**Comment by Finii** [comment]
:tada: Thanks for reporting back!
