### ISSUE TITLE
nf-mdi-sleep conflicts with Chinese characters

### ISSUE THREAD

**Issue by so1ar** [ryanoasis/nerd-fonts#1070]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue
I am using Arch Linux and installed [Sarasa-Gothic](https://github.com/be5invis/Sarasa-Gothic) along side nerd-fonts from Arch's official repo, and configured the fontconfig like this:

```
  <!-- Default monospace fonts-->
  <match target="pattern">
    <test name="family">
      <string>monospace</string>
    </test>
    <edit name="family" mode="prepend" binding="strong">
      <string>Sarasa Mono SC</string>
      <string>Symbols Nerd Font Mono</string>
    </edit>
  </match>
```

In the terminal the Glyph displays fine except nf-mdi-sleep, which is conflicts with a Chinese character.

Experienced behavior:

The glyph displays as a Chinese character.
![1674559271_grim](https://user-images.githubusercontent.com/54471528/214279220-070c7c7e-15c3-4ebf-949f-c32ac5786997.png)

Expected behavior:

The glyph should looks like this.

![1674559404_grim](https://user-images.githubusercontent.com/54471528/214279404-96ebfcda-3b2e-44af-b0f3-f0d952d95b56.png)

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_ `sarasa-semibold.ttc`
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   -  https://archlinux.org/packages/community/any/ttf-sarasa-gothic/ and https://archlinux.org/packages/community/any/ttf-nerd-fonts-symbols-2048-em-mono/
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Alacritty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Latest version of Arch Linux

**Comment by Finii** [comment]
`nf-mdi-` is in the wrong unicode block (i.e. the one reserved for Chinese glyphs.
You need to switch to the `nf-md-` code.

![image](https://user-images.githubusercontent.com/16012374/214289376-b5d43873-85a8-4131-9976-cb49ca44a67b.png)


See also
* #773 
* #365 
* #716

The `nf-mdi-` will be dropped with `Nerd Fonts v3.0.0`, users need to switch to `nf-md-`.
