### ISSUE TITLE
JetBrains Mono Nerd Font Ligatures (`{{`) broken in 2.3.x

### ISSUE THREAD

**Issue by pat-s** [ryanoasis/nerd-fonts#1072]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Before v2.3.x, `{{` were untouched.
Now, with ligatures enabled, they are turned into some weird icons (see screenshot below).
It can be reproduced by toggling ligatures on/off.

NB: I don't know if 2.3.2 or 2.3.0 introduced the issue.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   `JetBrainsMono Nerd Font Mono` (v2.3.2)
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - homebrew cask
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - VSCode
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - macOS

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/8430564/214344768-c99e8d09-6f54-4c99-8970-ec5ba4686afc.png)

**Comment by Finii** [comment]
Can not recreate with `v2.3.3`:

![image](https://user-images.githubusercontent.com/16012374/214397048-2df59308-5758-4a50-9e22-560ccde4f85f.png)

Probably solved by #1058?

**Comment by Finii** [comment]
Do you get the same strange glyphs in some text software like `writer` or `word`?

**Comment by Finii** [comment]
Maybe in upstream? c6b3b0841

Did you check unpatched `JetBrains Mono` 2.304?

**Comment by Finii** [comment]
The font file looks good:

![image](https://user-images.githubusercontent.com/16012374/214401328-36bd72ee-3f78-466c-81a1-c208b22fbf77.png)


Is `#{` working? Should look like this (whatever that is)

![image](https://user-images.githubusercontent.com/16012374/214400788-a346faa6-0c4e-4527-bb59-07a657f94be0.png)

**Comment by Finii** [comment]
Looks good on my machine

![image](https://user-images.githubusercontent.com/16012374/214487876-3e520e01-259c-49ac-bdbf-fad0d985ae6e.png)

![image](https://user-images.githubusercontent.com/16012374/214487916-ae560f04-eaad-417b-b292-ed329b533fbf.png)

Please provide equivalent screenshots.

**Comment by pat-s** [comment]
I have

```
  "editor.fontFamily": "JetBrainsMono Nerd Font Mono, Menlo, Monaco, 'Courier New', monospace",
  "editor.fontLigatures": true
```

![image](https://user-images.githubusercontent.com/8430564/214891701-44012e15-309b-4165-b83b-02f0e1e4a7cc.png)

Changing `JetBrainsMono Nerd Font Mono` to `JetBrainsMono Nerd Font` (from your screenshot, note the stripped "mono") solved the issue! Probably missed the renaming on my side then?
Yet I am using this font for more than a year in VSCode and haven't touched the config since then.

But great to have it working again!

**Comment by Finii** [comment]
Oh, I did not realize you had the `Nerd Font Mono` variant, lets see

Works just the same...

![image](https://user-images.githubusercontent.com/16012374/214904419-4df42f97-76c0-40e0-9b63-f746d4e440cf.png)

Did you miss the single quotes around the name?

I have just the 2 fonts installed, though:

```
fc-list | grep JetB
/home/fini/.local/share/fonts/JetBrains Mono Regular Nerd Font Complete Mono.ttf: JetBrainsMono Nerd Font Mono:style=Regular
/home/fini/.local/share/fonts/JetBrains Mono Regular Nerd Font Complete.ttf: JetBrainsMono Nerd Font:style=Regular
```

Lets 'simulate' the full cask installation....

```
$ cp git/nerd-fonts/patched-fonts/JetBrainsMono/**/*.ttf .local/share/fonts
$ fc-list | grep JetB | wc -l
128
```

Still all ok in `vscode`. This is the version I'm using:

![image](https://user-images.githubusercontent.com/16012374/214905728-f3a7b0bb-f910-4660-8496-18d6c6fd7247.png)


Hmmm,

![image](https://user-images.githubusercontent.com/16012374/214907162-42b96a61-c66b-4af0-b3a0-93f9eacf1d48.png)

the naming is not ok. Strangeness!

Maybe try to remove all fonts and just install Regular and Bold of the normal fonts that you use and see if that works.
If it works, it is most likely a naming issue.

**Comment by Finii** [comment]
Regarding naming:

Ah, I see, the `config.cfg` is not reached. The code that searches for the config is buggy, I found that out here: #1068 and fixed it only for the licenses :unamused: 

So the naming is not using the corrected naming scheme (puwww! :sweat_smile: )
It goes down only 1 directory, but JetBrains Mono is layed out to have it '2 down' :roll_eyes: 

![image](https://user-images.githubusercontent.com/16012374/214908119-4ede83e1-774f-4045-b2ae-6df91f6622c1.png)

I will fix that and maybe you want to try the name-corrected fonts? But that means un-installing the cask and manually installing the new ones.

**Comment by Finii** [comment]
Here are the fonts with fixed family names...
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono

Maybe you can try them out? There is a higher possibility that it also fixes your problem.

**Comment by pat-s** [comment]
> Maybe you can try them out? There is a higher possibility that it also fixes your problem.

My problem is fixed by just stripping the second "Mono" in the font name, see my last comment.

Is there any difference between "JetBrainsMono Nerd Font Mono` and `JetBrainsMono Nerd Font`?

I am hesitant trying to put fonts manually somewhere. Happy to help testing if you can give me a full code block for testing :) I can also just test a new release and report back. But again, for me the issue is solved by just renaming the font in VSCode.

**Comment by Finii** [comment]
`v3.0.0` cask is out. Maybe give it a try.

> Is there any difference between "JetBrainsMono Nerd Font MonoandJetBrainsMono Nerd Font`?

Explained that for example here: https://github.com/ryanoasis/nerd-fonts/discussions/1103
