### ISSUE TITLE
Sauce Code Pro Italic Nerd Font Complete (Mono) can't be opened on Windows

### ISSUE THREAD

**Issue by Jackenmen** [ryanoasis/nerd-fonts#1084]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
When trying to open files "Sauce Code Pro Italic Nerd Font Complete Windows Compatible.ttf" and "Sauce Code Pro Italic Nerd Font Complete Mono Windows Compatible.ttf" unpacked from the `SourceCodePro.zip` in v2.3.3 release, I see an error: "The requested file <path> is not a valid font file.":
![image](https://user-images.githubusercontent.com/6032823/214965812-43540dc4-b541-4141-9067-0405118c9b55.png)

Expected behavior:
I expect to be able to install these two fonts, the same as I am able to install the other 26 fonts that are part of the `SourceCodePro.zip` in the v2.3.3 release.

Example symbols:
N/A

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Sauce Code Pro Italic Nerd Font Complete Windows Compatible.ttf
   - Sauce Code Pro Italic Nerd Font Complete Mono Windows Compatible.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - `SourceCodePro.zip` downloaded from v2.3.3 release on GitHub: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/SourceCodePro.zip
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - N/A
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows 10 22H2 (OS Build 19045.2486)

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/6032823/214965812-43540dc4-b541-4141-9067-0405118c9b55.png)
![image](https://user-images.githubusercontent.com/6032823/214965315-f57e330f-e665-4ce6-ba1f-4ceff177080c.png)

**Comment by Finii** [comment]
All 4 fonts affected of `Italic`.

**Comment by Finii** [comment]
Opens ok in `fontforge`
https://wakamaifondue.com/beta/ shows metadata but no glyphs.

![image](https://user-images.githubusercontent.com/16012374/215025027-0f66e753-fb53-4ca1-9a94-d115d1a1c97f.png)

Why do we have two (2) italic versions? All other styles/weights have just one file (as expected):
![image](https://user-images.githubusercontent.com/16012374/215028962-c1203cd9-95c5-465a-891b-7e5ad50992d4.png)
Both source files do open under Windows, though.

**Comment by Finii** [comment]
I guess the problem is that we work concurrently on patching both, creating the same one output file and the 'does not blend'.

Where do they come from?

![image](https://user-images.githubusercontent.com/16012374/215029712-eeae8283-063a-416e-b140-bb901bcadf5f.png)

Patching both individually (without `-j`) and testing, both work individually.
So the reason IS the parallel processing of same named font files and tweaking them.

**Comment by Finii** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/16012374/215037295-84bdccc2-2e98-42ad-b52b-ae9d47853389.png)

Please find the corrected files here (until the next release at least):

https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/SourceCodePro/Italic/complete

**Comment by Finii** [comment]
Thanks for reporting!
