### ISSUE TITLE
Visually label the vector fonts

### ISSUE THREAD

**Issue by webknjaz** [ryanoasis/nerd-fonts#1088]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**

Using bitmap fonts is sometimes unacceptable, but there is no easy way of learning which ones are shipped in vector format.

**Describe the solution you'd like**

I think that both README and the website should have some sort of labels marking the fonts that are vector as opposed to bitmap.

**Describe alternatives you've considered**

Manually iterating over all the font files in the repo.

**Additional context**

I use [Kitty] terminal emulator. It features GPU rendering, letting it display things smoothly. As a side effect, it needs vector fonts as a hard requirement — the bitmap ones are unsupported: https://github.com/kovidgoyal/kitty/issues/807#issuecomment-413473970.
This issue should probably be mentioned @ https://github.com/ryanoasis/nerd-fonts/wiki/Terminal-Emulators.

[Kitty]: https://sw.kovidgoyal.net/kitty/

**Comment by Finii** [comment]
I had the impression all fonts have contours (albeit I believe with some I though: _How bad can auto-vectorization be?)_, but some have bitmaps additionally. Which is 'new', previous Nerd Font releases dropped the bitmaps in the fonts.
* #939

Do you have an example?

**Comment by Finii** [comment]
Which Nerd Fonts released font does **not** have outline (vector) glyphs?
All symbols are outlines anyhow.

I do not get what the problem is. Labeling vector fonts means: all fonts. What would be the benefit?

Please reopen if you see need.

**Comment by webknjaz** [comment]
Ah, I didn't realize that. Maybe I got confused. If I stumble upon a specific example, I'll let you know.
