### ISSUE TITLE
Wrong name for "glyph-source-fonts/PowerlineExtraSymbols.otf"

### ISSUE THREAD

**Issue by blueyed** [ryanoasis/nerd-fonts#109]
https://github.com/ryanoasis/nerd-fonts/blob/master/glyph-source-fonts/PowerlineExtraSymbols.otf has "Droid Sans Mono for Powerline Plus Nerd File Types Mono:style=Regular" as its name (according to `fc-list`).

I am looking currently into using the fonts separately, i.e. `URxvt.font: xft:UbuntuMono:size=8,xft:DejaVu Sans Mono,xft:monospace,xft:Symbola,xft:FontAwesome:size=4,xft:UbuntuMonoDerivativePowerline Nerd Font` (instead of `UbuntuMonoDerivativePowerline Nerd Font` at the beginning), because the rendering of `UbuntuMono` is slightly better with the unpatched/original font for me.  That's why I've noticed that the name for `PowerlineExtraSymbols` is off.

**Comment by blueyed** [comment]
A similar issue: `glyph-source-fonts/Powerline.otf` does not only contain the powerline symbols..  I could not find a font that would only contain those glyphs, and it might be not that useful, since it might depend on the other characters / the height of the base font?!

It is the same for the extra font I guess (which has "Create Powerline symbol only font for fontconfig" as TODO left).

btw: I wonder if it would make sense to re-use existing codepoints for a specialized PowerlineSymbols font, e.g. from the geometric shapes block (http://shapecatcher.com/unicode/block/Geometric_Shapes)?!
This way it would look OKish without a powerline font already..

**Comment by blueyed** [comment]
What about providing a PowerlineExtraSymbols font, which contains only the Powerline symbols (plus the extra ones)?
Could that be used by itself, similar to Font Awesome, or is it necessary to be scaled in some way according to the base font?

**Comment by ryanoasis** [comment]
Trying to catch up here. Let me know if I miss something...

> https://github.com/ryanoasis/nerd-fonts/blob/master/glyph-source-fonts/PowerlineExtraSymbols.otf has "Droid Sans Mono for Powerline Plus Nerd File Types Mono:style=Regular" as its name (according to fc-list).

This was created in a rush and so while it does have the 'extra powerline symbols' it also has other glyphs and metadata that it shouldn't :blush: 

> That's why I've noticed that the name for PowerlineExtraSymbols is off.

Oh okay sure, yeah I think this ideally should be fixed

> It is the same for the extra font I guess (which has "Create Powerline symbol only font for fontconfig" as TODO left).

Yeah ideally we would have a [fontconfig](84) for all of these symbols so alternatively users could forgo having to use a patched font (where fontconfig is supported).

> btw: I wonder if it would make sense to re-use existing codepoints for a specialized PowerlineSymbols font, e.g. from the geometric shapes block (http://shapecatcher.com/unicode/block/Geometric_Shapes)?!
This way it would look OKish without a powerline font already..

Ah okay I think you are saying to have a font that overrides these locations with a powerlinish version and fallback to the originals without? Interesting idea for sure. I am not sure that would be a high priority when you look at the current issues and improvements that are still needed :stuck_out_tongue: :worried: 

> What about providing a PowerlineExtraSymbols font, which contains only the Powerline symbols (plus the extra ones)?

This is what the PowerlineExtraSymbols font on that [other repo](https://github.com/ryanoasis/powerline-extra-symbols) _ideally_ should have but in the rush of creating it that's not the case :disappointed: 

> or is it necessary to be scaled in some way according to the base font?

Yeah there are scaling issues still, I am not sure off the top of my head which EM it currently has but the patcher isn't doing scaling correctly at the moment.
