### ISSUE TITLE
JetBrains Mono wrong J character

### ISSUE THREAD

**Issue by dahmc** [ryanoasis/nerd-fonts#1091]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
`JetBrains Mono Nerd Font Mono` font:

The uppercase `J` character seems wrong.

This is how it looks like on current master: 
<img width="46" alt="CleanShot 2023-01-29 at 13 05 58@2x" src="https://user-images.githubusercontent.com/75008413/215325278-896edb5d-887a-473d-b179-752f393ad20a.png">

Expected behavior:
<img width="42" alt="CleanShot 2023-01-29 at 13 11 05@2x" src="https://user-images.githubusercontent.com/75008413/215325305-f0ff0025-0cba-4711-ae9e-24f29acb0331.png">

So the top stroke is missing somehow.

#### 🔧 Your Setup

- _Which font are you using?_
   - `JetBrains Mono Nerd Font Complete Mono Regular.ttf`
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - DL from master
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - kitty 0.26.5
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - macOS 13.2

#### ★ Screenshots (Optional)

Old version, from like 6 month ago
<img width="520" alt="CleanShot 2023-01-29 at 13 14 31@2x" src="https://user-images.githubusercontent.com/75008413/215325438-6d346855-8645-4c30-a6a8-f9a899c4067c.png">

Latest Master
<img width="512" alt="CleanShot 2023-01-29 at 13 13 46@2x" src="https://user-images.githubusercontent.com/75008413/215325450-4bb8d3d2-f3fe-4529-a3be-4c76ad9e9eca.png">

**Comment by Finii** [comment]
Thanks for the report!

Hmm, fresh downloaded the current release from their webpage:

![image](https://user-images.githubusercontent.com/16012374/215330126-daa8135d-fec0-4384-bcae-3ce9dda8fac2.png)

Strangeness. Investigating.

**Comment by Finii** [comment]
See 
* https://github.com/JetBrains/JetBrainsMono/issues/597

**Comment by dahmc** [comment]
Ah thanks, I didn't see that issue on their repo!

**Comment by Finii** [comment]
Seems intended, see my comment there.
Closing this, we can update when they change.

Thanks again for reporting.

**Comment by Finii** [comment]
Note

* #https://github.com/JetBrains/JetBrainsMono/issues/574#issuecomment-1305420328
