### ISSUE TITLE
SHA256 mismatch when downloading from HomeBrew

### ISSUE THREAD

**Issue by andy941** [ryanoasis/nerd-fonts#1102]
Experienced behavior:
I am trying to download nerd-fonts with HomeBrew on my Mac M1 (pro).

Expected behavior:
I expect to be able to download and install the fonts via homebrew, I have done that in the past with Macs with no issues. They were Intel MacOS machines, if that makes a difference.

Example symbols:
Here is an example Error:

``` bash
brew install --cask homebrew/cask-fonts/font-ubuntu-mono-nerd-font
==> Tapping homebrew/cask-fonts
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-cask-fonts'...
remote: Enumerating objects: 66134, done.
remote: Counting objects: 100% (199/199), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 66134 (delta 138), reused 175 (delta 120), pack-reused 65935
Receiving objects: 100% (66134/66134), 13.05 MiB | 24.11 MiB/s, done.
Resolving deltas: 100% (48890/48890), done.
Tapped 2007 casks (2,042 files, 16.1MB).
==> Downloading https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.2/UbuntuMono.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/27574418/4ed02a8c-00c2-49cf-b81e-b13319089592?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53
                       -=O=-         #     #     #    #                       
Error: SHA256 mismatch
Expected: bcad6c904a1d1fc6167cc738d2379586707d689a96e623a9f65d6c6ea716d723
  Actual: 89ce1dd64b36dfe1ad85db7dbed5d0c03c60d30a82a20f5c0cd0695083248a74
    File: /Users/afinocchio/Library/Caches/Homebrew/downloads/00a8e35abb0edaf4c71558d74d833c85b1e8bae0430b2c1e073c39ea48ea2578--UbuntuMono.zip
To retry an incomplete download, remove the file above.

```
What I have tried:
- tapping the cask first, then installing
- doing a `brew cleanup --all`
- untapping and tapping the cask again
- Trying different fonts
- Switching off my VPN

Nothing made a difference so far.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
As said above, the problem is found with any font I try to download from the home-brew/cask-fonts cask.
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
HomeBrew
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
Kitty 0.26.5
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
macOS Monterey v12.5 - MacBook M1Pro 16

#### ★ Screenshots (Optional)
NA

Thank you for the help,
Andrea

**Comment by Finii** [comment]
Sorry to hear of your issues, lets have a look ...

![image](https://user-images.githubusercontent.com/16012374/216274064-7aa4e4b5-fdcf-472c-afd3-65f15c5abc29.png)

So archive checksum and cask value are the same.

I have no clue where this comes from

```
Expected: bcad6c904a1d1fc6167cc738d2379586707d689a96e623a9f65d6c6ea716d723
  Actual: 89ce1dd64b36dfe1ad85db7dbed5d0c03c60d30a82a20f5c0cd0695083248a74
    File: /Users/afinocchio/Library/Caches/Homebrew/downloads/00a8e35abb0edaf4c71558d74d833c85b1e8bae0430b2c1e073c39ea48ea2578--UbuntuMono.zip
```

I am no Homebrew user. Maybe try to remove `/Users/afinocchio/Library/Caches/Homebrew/downloads/00a8e35abb0edaf4c71558d74d833c85b1e8bae0430b2c1e073c39ea48ea2578--UbuntuMono.zip` by hand?

**Comment by andy941** [comment]
Hi,
 Thanks for the prompt response. I forgot to mention, I tried deleting the file as suggested by HomeBrew, no luck. The only things I can think of are:
- the cask is broken (out-of-date hashes)
- There is some M1 specific issue (no clue what it might be tho)
- This is my company laptop, there might be some safety feature messing up the SHA calculation (added encryption step before the hash is calculated?)

Feel free to delete close this issue if you don't know what might be the problem. I tried to open it to see if you might have encountered this problem already in the past. I can't find much by googling.

**Comment by Finii** [comment]
Btw, this `-all`, I do not have that:

![image](https://user-images.githubusercontent.com/16012374/216312141-c966f5bf-3c66-47fd-ba6c-3d87dbaffbcc.png)

Here I need to just run `brew cleanup -s`

**Comment by andy941** [comment]
sorry you are right, I got confused. It's --prune=all.
My sha256 is wrong (same as what brew was telling me):
89ce1dd64b36dfe1ad85db7dbed5d0c03c60d30a82a20f5c0cd0695083248a74

I tried the cleanup you suggested, no luck.

**Comment by Finii** [comment]
Maybe raise an issue at Homebrew-cask-fonts?

You did not show the file-size.
The hash `89ce` is strange, it is not even the hash of another release, I believe.

Unpack the zip and look into the contents?

```
$ unzip -v UbuntuMono.zip
Archive:  UbuntuMono.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
 2197392  Defl:X  1181311  46% 2023-01-23 13:11 da6e3d61  Ubuntu Mono Bold Nerd Font Complete.ttf
 2197464  Defl:X  1181352  46% 2023-01-23 13:11 f8259a0a  Ubuntu Mono Bold Nerd Font Complete Windows Compatible.ttf
 2149688  Defl:X  1147690  47% 2023-01-23 13:14 a9d4d75d  Ubuntu Mono Bold Nerd Font Complete Mono.ttf
 2149736  Defl:X  1147725  47% 2023-01-23 13:14 0f88d3fc  Ubuntu Mono Bold Nerd Font Complete Mono Windows Compatible.ttf
 2170640  Defl:X  1156284  47% 2023-01-23 13:14 36331808  Ubuntu Mono Italic Nerd Font Complete Mono Windows Compatible.ttf
 2218368  Defl:X  1189573  46% 2023-01-23 13:11 557ced1c  Ubuntu Mono Italic Nerd Font Complete Windows Compatible.ttf
 2218304  Defl:X  1189543  46% 2023-01-23 13:11 cc4d4e1b  Ubuntu Mono Italic Nerd Font Complete.ttf
 2170600  Defl:X  1156252  47% 2023-01-23 13:14 964c0b11  Ubuntu Mono Italic Nerd Font Complete Mono.ttf
 2211748  Defl:X  1185252  46% 2023-01-23 13:11 698d953f  Ubuntu Mono Nerd Font Complete.ttf
 2164048  Defl:X  1151650  47% 2023-01-23 13:14 592fd4dc  Ubuntu Mono Nerd Font Complete Mono.ttf
 2211812  Defl:X  1185281  46% 2023-01-23 13:11 abbf9d5d  Ubuntu Mono Nerd Font Complete Windows Compatible.ttf
 2164084  Defl:X  1151678  47% 2023-01-23 13:14 8b4583c8  Ubuntu Mono Nerd Font Complete Mono Windows Compatible.ttf
 2222316  Defl:X  1201255  46% 2023-01-23 13:11 fca7c426  Ubuntu Mono Bold Italic Nerd Font Complete Windows Compatible.ttf
 2174564  Defl:X  1167623  46% 2023-01-23 13:14 13d19399  Ubuntu Mono Bold Italic Nerd Font Complete Mono.ttf
 2174588  Defl:X  1167653  46% 2023-01-23 13:14 a1fa1999  Ubuntu Mono Bold Italic Nerd Font Complete Mono Windows Compatible.ttf
 2222264  Defl:X  1201230  46% 2023-01-23 13:11 56349129  Ubuntu Mono Bold Italic Nerd Font Complete.ttf
    4673  Defl:X     1990  57% 2023-01-23 13:14 88e9330a  LICENCE.txt
    8980  Defl:X     3738  58% 2023-01-23 13:14 a34cd607  LICENCE-FAQ.txt
     196  Defl:X      122  38% 2023-01-23 13:14 379eea7a  readme.md
--------          -------  ---                            -------
35031465         18767202  46%                            19 files

$ strings 'Ubuntu Mono Nerd Font Complete.ttf' | grep 'Nerd Fonts'
Version 0.80;Nerd Fonts 2.3.2
```

Last resort might be the `rm -rf "$(brew --cache)"`.

**Comment by Finii** [comment]
Hmm, I just triggered a Cask update (to `v2.3.3`) maybe that will solve your problems by pure out-dating :-D

**Comment by Finii** [comment]
Why are there only 47 changed casks, we have 52 fonts iirc?
What is missing? This is an automaton, it is impossible something goes wrong ;-) :-D

![image](https://user-images.githubusercontent.com/16012374/216318360-09070459-0796-495f-8d41-8ee69eaf5d47.png)

**Comment by andy941** [comment]
Fingers crossed, should it be 2.3.3 now or have to wait for the merge?

**Comment by Finii** [comment]
`brew` fetches the latest git repo, so it will be only available after they merge the PR.
But usually that happens within some very few hours.

**Comment by Finii** [comment]
Merged

**Comment by andy941** [comment]
The cask was updated but I still have the same error. It's really weird.

**Comment by Finii** [comment]
Did you do the `rm -rf` thing?

I guess I am out of ideas. You should raise an Issue at Homebrew-font-casks or Homebrew itself.

**Comment by Finii** [comment]
Same error?

Did the hash (i.e. `Actual: 89ce1dd64b36dfe1ad85db7dbed5d0c03c60d30a82a20f5c0cd0695083248a74`) change?

Do link this issue in the other issue if you raise one over there.

**Comment by andy941** [comment]
I did try the `rm -rf`, thanks for the help! I'll close this now, I might raise the issue with Homebrew.
Thank you!
