### ISSUE TITLE
Add M PLUS 1 Code and improve M+ README

### ISSUE THREAD

**Issue by paulcarroty** [ryanoasis/nerd-fonts#1104]
`1mn`, `1m`, `1c` and `1p`, `2p` -  failed to find the difference in README.

**Comment by Finii** [comment]
Oh, thanks for reporting.

Which readme to you mean? This?

![image](https://user-images.githubusercontent.com/16012374/216536889-d58eba05-14bd-4cb5-9fbf-15a7feaa2fd5.png)

From their [website](https://mplusfonts.github.io) (always refer to the original font's documentation if you want to know something about a specific source-fiont):

`1` and `2` denote a slightly different visuals, `1` is _modern_ and `2` is _classic_

![Peek 2023-02-03 08-27](https://user-images.githubusercontent.com/16012374/216538429-18e7372a-2466-4ebf-b427-56d56277edbe.gif)

`p` is proportional
`m` is monospaced
`c` is for_code

`n` ... is another variation, maybe 'new'?

![image](https://user-images.githubusercontent.com/16012374/216539717-ed5d7f5d-8275-45fe-a73c-7e10c9a90913.png)

_On the left `1m` and `1mn` on the right_

**Comment by Finii** [comment]
The **M+** we have here is `1.063` which is rather old (2018). Will be (hopefully) updated for `Nerd Fonts v3.0.0` to ...?? `1.006`.
They seem to have broken the version numbers when switching to Google Fonts?

Whatever, currently they do not have the single-letter names anymore.

**Comment by paulcarroty** [comment]
They provide 3 `Code` fonts now:

- M PLUS 1 Code
- M PLUS Code Latin 50
- M PLUS Code Latin 60

with human-readable [file names](https://github.com/coz-m/MPLUS_FONTS/tree/master/fonts/otf).

`n` can be Code version 'cause `C` is the same, but who knows.

**Comment by Finii** [comment]
Has this been solved by 1868c68c8b7?

I do not see Latin 50/60 in the diff :thinking:

**Comment by paulcarroty** [comment]
You need to add `MplusCodeLatin50` and `MplusCodeLatin60` too, except them both all is set tho.

**Comment by Finii** [comment]
Release is in repo, release as packages pending.
