### ISSUE TITLE
urxvt - some glyphs shown as square [] in specific font size

### ISSUE THREAD

**Issue by tigerinus** [ryanoasis/nerd-fonts#1105]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

This is more of a question asking for help: I recently switched over to `urxvt` from `gnome-console`, the see that certain glyphs shown as []

Experienced behavior:

![image](https://user-images.githubusercontent.com/7172560/216662562-59ec8230-0c38-4837-8bbe-1189ca85ac8f.png)

Expected behavior:

The glyphs should not be shown as []

Example symbols:

```
 ~  dotfiles   master ✚ 1  
```

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
```
Fira Code Regular Nerd Font Complete Mono.ttf
Fira Code Bold Nerd Font Complete Mono.ttf
```

- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - 
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode

- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_

  urxvt

```
URxvt*background: [90]#000000
URxvt*clipboard.autocopy: false
URxvt*colorUL: Cyan
URxvt*cursorColor: Magenta
URxvt*depth: 32
URxvt*fading: 38
URxvt*font: xft:FiraCode Nerd Font Mono:size=10
URxvt*foreground: White
URxvt*iso14755: false
URxvt*keysym*C-S-0x43: eval:selection_to_clipboard
URxvt*keysym*C-S-0x56: eval:paste_clipboard
URxvt*letterSpace: -1
URxvt*loginShell: true
URxvt*matcher*button: 1
URxvt*perl-ext-common: default,selection-to-clipboard,matcher
URxvt*scrollBar: true
URxvt*scrollBar_right: true
URxvt*scrollColor: #1A1A1A
URxvt*scrollTtyKeypress: true
URxvt*scrollTtyOutput: false
URxvt*scrollWithBuffer: false
URxvt*scrollstyle: plain
URxvt*skipScroll: true
URxvt*underlineColor: Blue
URxvt*underlineURLs: true
URxvt*url-launcher: /usr/bin/xdg-open
URxvt*visualBell: true
```

If I change the size from `size=10` to `size=12`, then it looks OK:
![image](https://user-images.githubusercontent.com/7172560/216664358-5ce163e2-bff2-4a9d-8704-9e7c1fb647ad.png)

- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - 

  Ubuntu (Jammy)

**Comment by tigerinus** [comment]
A workaround - update `~/.Xresources` with:

```
URxvt*font: xft:FiraCode Nerd Font Mono:pixelsize=13
Xft*rgba: rgb
```

**Comment by Finii** [comment]
Maybe you should / could prefer some nice outline font for that glyph via fontconfig. Then you can decide which fallback font is used by urxvt and not some random (possibly bitmap) font.
