### ISSUE TITLE
Inconsistent size for weather-symbols

### ISSUE THREAD

**Issue by Bacaliu** [ryanoasis/nerd-fonts#1107]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

The Weathersymbols aren't the same size dependent on if they rain or not and if they have the sun in them or not. Even with multiple spaces after them they don't grow horizontally like in previous versions.

Expected behavior:

In Version 2.2.2-2 (which is installed on my local system) when a space was inserted right next to the symbols, they would grow to give the sunbeams more horizontal space which made them very much the same size as the equivalent symbol for night. Showers would shift the cloud and sun slightly up so they could stay the same size as a cloud without rain.

Example symbols:

-  
-  
-  
-  

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - `Symbols-2048-em Nerd Font Complete.ttf`
   - `Symbols-2048-em Nerd Font Complete Mono.ttf`
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   -  download link
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   -  None. I use the Font on my website.
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   -  Doesn't matter
     - Laptop: Arch Linux 6.1.9-arch1-1
     - Server: Debian 11.6
     - Client: any

#### ★ Screenshots (Optional)

v2.2.2-2 [as expected, very uniform size]
![grafik](https://user-images.githubusercontent.com/83137280/216817653-33da22fb-a365-4179-8d9e-5c9cc67d0811.png)

v2.3.3 [sun with rain is to small]
![grafik](https://user-images.githubusercontent.com/83137280/216817473-85edf3af-6c2d-44cf-9704-00e25f9c5fb2.png)

v2.3.3, Mono [much worse]
![grafik](https://user-images.githubusercontent.com/83137280/216817617-17e43415-05f3-43e5-8171-f317f44a0279.png)

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/216820099-6a9a19f0-3528-49c3-ae8f-69f2dd3cbd81.png)

Strange, should have been fixed by
* #916 

Examining...

**Comment by Finii** [comment]
Ahh,

```python
        WEATH_SCALE_LIST = {'ScaleGroups': [
            range(0xf095, 0xf0b0 + 1), # moon phases
            range(0xf0b7, 0xf0c3 + 1), # wind strengths
            range(0xf053, 0xf055 + 1), # thermometer
            [0xf06e, 0xf070 ], # solar eclipse
            [0xf042, 0xf045 ], # degree sign
        ]}
```

Obviously there is no rule for the clouds :grimacing:

**Comment by Finii** [comment]
The real reason is
* #748 

as they are individually down-scaled.

This is in fact a problem. Needs some thinking.

**Comment by Finii** [comment]
@Bacaliu 

> v2.3.3, Mono [much worse]

Can you explain the 'much worse' part here? Worse because of what? What is actually bad?

**Comment by Finii** [comment]
Maybe you can also explain a bit your use case.

That glyphs 'grow' depending on amount of blanks after them is a very client (terminal emulator) specific behavior.

**Comment by Finii** [comment]
After fix we have all clouds the same size (left old, right new; blue line above means: changed)

![image](https://user-images.githubusercontent.com/16012374/217517663-a9e3fe0e-cda5-4196-860e-cd085ad3c160.png)

The biggest icons are right in the beginning, 'strong wind with sun behind clouds' or something, and all other clouds need to be equally small to preserve size-equality.

**Comment by Finii** [comment]
Maybe these belong to the same set?

![image](https://user-images.githubusercontent.com/16012374/217520940-69a5b831-6201-4957-9ff5-af4d1d63ef49.png)

That would mean adding them to the group and they will come out smaller.

**Comment by Bacaliu** [comment]
> Can you explain the 'much worse' part here? Worse because of what? What is actually bad?

In the Mono Font the sizes are different for day or night; that looks more bad than just rain making the cloud smaller. If displaying multiple symbols for different daytimes next to each other the difference in size is very obvious.

> Maybe you can also explain a bit your use case.

I use the symbols to display a weather forecast:


![grafik](https://user-images.githubusercontent.com/83137280/217600802-7f2e0b2b-4f83-43b8-b3e5-1339a37f5d0d.png)

```html
...
<div class="weather-column-cell" style="line-height: 1.75;
  background: linear-gradient(
  #76b3d5,
  30%,
  #6fb8e0,
  30%,
  #6fb8e0,
  60%,
  #7dadca,
  60%,
  #7dadca,
  85%,
  #5fc6f8
  85%,
  #5fc6f8
); border-radius: 2em;" title="stark bewölkt">
  <span class="nf" style="font-size: 1.3rem; text-align: center; margin-left: 0.5rem;
                color: black;">  </span>
</div>
...
```
I just put the icon inside a div with a gradient representing the sky.

> That glyphs 'grow' depending on amount of blanks after them is a very client (terminal emulator) specific behavior.

I suspected that because they grow differently in Emacs/Kitty/Browser. Just thought there was a /right/ way of growing.

The fixed version looks much better to me. Although I'm not sure if the most used cloud only or even sun/moon should be at the same location and have the same size. But looking at the svg versions on [erikflowers/weather-icons](https://erikflowers.github.io/weather-icons/) it seems to be intended that e.g. `wi-day-sunny` or `wi-day-sunny-overcast` are not exactly aligned and sized with the others. 

> Edit: Or are all the circled glyphs an independent group and the bottom one should be bigger?

Looking on linked site the top four belong together (no weather-information, just rise/set) and the lower two (day-hot and day-haze)
