### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by santagada** [ryanoasis/nerd-fonts#111]
What is the support for macOS (OSX)(10.11.6)?

I tried multiple fonts with and without windows versions and looking at the characters on Terminal.app Font Book.app and iterm2.app and the results were:

1) anonymice almost works, the powerline symbols are bigger than the characters but on iterm2 you can choose a font for special chars 2 points smaller and then they almost match.

2) Sourcecode pro, profont and Iosevka don't work at all and all have heavily distorted powerline extended chars

schreenshot:

<img width="836" alt="screenshot 2016-10-21 09 18 28" src="https://cloud.githubusercontent.com/assets/225897/19589917/63e07746-976f-11e6-944d-ce8b5ef5f638.png">

This is the same behavior with the others

3) A warning message is shown for the installation of those fonts:

<img width="620" alt="screenshot 2016-10-21 09 20 31" src="https://cloud.githubusercontent.com/assets/225897/19590037/05695e66-9770-11e6-9eec-e512290a19dc.png">

Is there fonts that work perfectly on macOS?

**Comment by santagada** [comment]
maybe #107 will fix this?

**Comment by ryanoasis** [comment]
@santagada Mostly yes, yes it should 😄

**Comment by ryanoasis** [comment]
Fixed/closed with v1.0.0
