### ISSUE TITLE
[Fura Mono] Font does not appear in Command Prompt/Powershell font options

### ISSUE THREAD

**Issue by Tyler799** [ryanoasis/nerd-fonts#1110]
#### 🗹 Requirements

- [*] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful (It could be related to https://github.com/ryanoasis/nerd-fonts/issues/924 if some flag is not being set to mark it as monospace, as then it would not appear in the options)
- [*] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [*] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
The Windows-compatible Fura Mono font does not appear in the font options available to any of the Windows terminal tools. (Command Prompt, Powershell, WSL)

It does however appear in other applications, like WordPad.

Expected behavior:
The font would appear as an option in the "Fonts" tab.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Fura Mono Regular Nerd Font Complete Mono Windows Compatible.otf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraMono/Regular/complete
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Command Prompt/Powershell/WSL
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows 10

**Comment by Finii** [comment]
The reason is that `cmd` does only work with TrueType fonts, but that is an OpenType/CFF font.

If we would create it with `--ext ttf` it works (see image below).

The difference is in the way the outlines are encoded.

![image](https://user-images.githubusercontent.com/16012374/217739835-b3b12505-b608-402e-8abf-6323a858db7f.png)

**In principle my answer would be: `CMD` needs `ttf` and you choose `otf`**

But that raises the question why we encode them as `otf` (well, apart from the fact that we just keep the encoding)?
And in principle we could also produce a otf with ttf outlines.
I guess this needs some investigation.

For the time being, I can only point you to 'self patching'. Or if you need just that one font I can put it somewhere for you to download.
Or use Windows Terminal instead of the raw CMD tool thing.

**Comment by Tyler799** [comment]
Thank you for the explanation. 

I only need one: Fura Mono Regular Nerd Font Complete Mono Windows Compatible.otf

I'm not just using CMD, I'm also using things like WSL, which uses the same terminal framework.

**Comment by Finii** [comment]
No problem, let me provide you the fonts in a fork...

Here you go: https://github.com/Finii/nerd-fonts/tree/fira-mono-ttf/patched-fonts/FiraMono

> symbols needed to make the Starship Prompt work properly

What is Starship Prompt :-D
On https://starship.rs/ they say 'a Nerd Fonts font' is enough. Which symbols are missing and where do they come from?

**Comment by Finii** [comment]
No, `otf` and `ttf` support the same number of glyphs. In fact the differences between otf and ttf are minuscle. Where our `otf` is in fact a postscript font that just uses otf as container, but that all should not matter.

And I can see the branch symbol in the `ttf`

![image](https://user-images.githubusercontent.com/16012374/217896790-8eea4575-6c74-4954-b21f-8dcebb26304f.png)

Which codepoints are missing? Maybe enter the glyps in a comment here as text (copy and paste), I can then use for example [1] to extract the codepoint.

[1] https://onlineunicodetools.com/convert-unicode-to-code-points

**Comment by Tyler799** [comment]
Actually now the branch symbol is appearing. I hadn't checked since the prompt looked broken.

But some are still missing. Here is one, the prompt symbol: ❯

Another is here: 🔒

**Comment by Finii** [comment]
Both symbols are not in the Nerd Fonts set.

The `>` like thing is one of the `276F` set, that Nerd Fonts does not patch in (although I remember we have an issue to add them, somewhere, maybe).

![image](https://user-images.githubusercontent.com/16012374/217900996-59bbe886-c5d2-4c37-aec0-a07766a6c71e.png)
_Lots and lots of parentheses like things_

And the lock is somewhere else altogether, it comes from the `NotoColorEmoji` I guess.


Ah, here
* #414

**Comment by Tyler799** [comment]
So, the issue is now that the Starship prompt claims it only needs a Nerd Font, but in fact uses symbols that only a small number of patched Nerd Fonts actually have?

**Comment by Finii** [comment]
Well, I do not know how Starship works.

With the powerline prompts that I use, there is some kind of infrastructure, and then one gets the real look-and-feel from 'someone' there are usual suspects. But they just make their presets available, If they use a different font the glyph they use is missing. But that would not be a fault of the core project.
And anyhow, every user can replace everything in the prompts to their liking.

So, I do not know how much you can 'blame' Starship for the fact you have a not widely present glyph in your prompt.

**Comment by Tyler799** [comment]
> So, I do not know how much you can 'blame' Starship for the fact you have a not widely present glyph in your prompt.

Those are default symbols. I modified the prompt slightly to do things like disable path truncation, but all the symbols are the defaults. 

So yeah, I blame Starship. They could have easily said in their instructions "We only support fonts X, Y, Z" and things would have been easier. 

I'll take a look at powerline, if it's possible to use in the places I want it. 

Thanks.

**Comment by Finii** [comment]
Note to self: Maybe model after my old code here

https://github.com/adam7/delugia-code/pull/30/commits/646548b16202ec6ca34fc2a8f422369fcd23ee9f

We added for some time `2262` `2263` `26A1` `276F`

**Comment by Finii** [comment]
Here is a list of the glyphs that starship expects of a Nerd Font

https://starship.rs/presets/nerd-font.html
https://starship.rs/presets/toml/nerd-font-symbols.toml

| name | glyph | codepoint | status |
|---|---|---|---|
| [aws] |   | `E33D` |
| [buf] |  | `F49D` |
| [c] |  | `E61E` |
| [conda] |  | `F10C` |
| [dart] |  | `E798` |
| [directory] |  | `F83D` | :red_circle: |
| [docker_context] |  | `F308` |
| [elixir] |  | `E275` |
| [elm] |  | `E62C` | :red_circle: |
| [git_branch] |  | `F418` |
| [golang] |  | `E627` | :red_circle: |
| [guix_shell] |  | `F325` |
| [haskell] |  | `E777` |
| [haxe] | ⌘ | `2318` |
| [hg_branch] |  | `F418` |
| [java] |  | `E256` |
| [julia] |  | `E624` |
| [lua] |  | `E620` |
| [memory_usage] |  | `F85A` | :red_circle: |
| [meson] | 喝 | `FA36` | :red_circle: |
| [nim] |  | `F6A4` | :red_circle: |
| [nix_shell] |  | `F313` |
| [nodejs] |  | `E718` |
| Alpine |  | `F300` |
| Amazon |  | `F270` |
| Android |  | `F17B` |
| Arch |  | `F303` |
| CentOS |  | `F304` |
| Debian |  | `F306` |
| DragonFly |  | `E28E` |
| Emscripten |  | `F205` |
| EndeavourOS |  | `F197` |
| Fedora |  | `F30A` |
| FreeBSD |  | `F30C` |
| Garuda | ﯑ | `FBD1` | :red_circle: |
| Gentoo |  | `F30D` |
| HardenedBSD | ﲊ | `FC8A` | :red_circle: |
| Illumos |  | `F737` | :red_circle: |
| Linux |  | `F31A` |
| Macos |  | `F302` |
| Manjaro |  | `F312` |
| Mariner |  | `F1CD` |
| MidnightBSD |  | `F186` |
| Mint |  | `F30E` |
| NetBSD |  | `F024` |
| NixOS |  | `F313` |
| OpenBSD |  | `F739` | :red_circle: |
| openSUSE |  | `F314` |
| OracleLinux |  | `F836` | :red_circle: |
| Pop |  | `E2A3` |
| Raspbian |  | `F315` |
| Redhat |  | `F316` |
| RedHatEnterprise |  | `F316` |
| Redox |  | `F517` | :red_circle: |
| Solus | ﴱ | `FD31` | :red_circle: |
| SUSE |  | `F314` |
| Ubuntu |  | `F31B` |
| Unknown |  | `F22D` |
| Windows |  | `F871` | :red_circle: |
| [package] |  | `F8D6` | :red_circle: |
| [python] |  | `E235` |
| [rlang] | ﳒ | `FCD2` | :red_circle: |
| [ruby] |  | `E791` |
| [rust] |  | `E7A8` |
| [scala] |  | `E737` |
| [spack] | 🅢 | `1F162` | _not part of NF_ |

:red_circle: = Glyph will vanish with `Nerd Fonts v3.0.0`

The `276F` is not mentioned here.

**Comment by Finii** [comment]
All 6 heavy brackets are now part of every Nerd Fonts font:

![image](https://user-images.githubusercontent.com/16012374/218133455-548f32cd-897e-4534-bfc8-95ac27a39ea1.png)

via 59c5cb5

`276C` `276D` `276E` `276F` `2770` `2771`
