### ISSUE TITLE
add pnpm icon

### ISSUE THREAD

**Issue by tjx666** [ryanoasis/nerd-fonts#1114]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**

Now, misssing the pnpm icon. pnpm: https://pnpm.io/

I want to show it in my terminal like node icon:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/218243506-9e5b79a8-0046-4fa4-b723-0dc3383d3df5.png">

**Describe the solution you'd like**

The icon may look like the official website logo.

@zkochan

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
