### ISSUE TITLE
Fira Code NF/NFM cannot displaying `|=`  as ligatures

### ISSUE THREAD

**Issue by FlyToEarth** [ryanoasis/nerd-fonts#1115]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue
Experienced behavior:
I found `|=` is not displaying as ligatures with `Fira Code Nerd Font Regular` and `Fira Code Nerd Font Mono Regular`. I dont know if other fonts have this problem.

Expected behavior:
Expect to display properly as with original `Fira Code`

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - `Fira Code Regular Nerd Font Complete Windows Compatible.ttf`
   - `Fira Code Regular Nerd Font Complete Mono Windows Compatible.ttf`
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - [https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip)
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows

#### ★ Screenshots (Optional)
![image](https://user-images.githubusercontent.com/44717715/218270534-edf3bf3c-18cd-4818-b376-7b42390b3798.png)
![image](https://user-images.githubusercontent.com/44717715/218270570-50e7b8b0-ab06-47f6-9952-06ebf9dc286d.png)
![image](https://user-images.githubusercontent.com/44717715/218270609-3c02051f-0183-4757-8fef-56f83b22ba66.png)

**Comment by Finii** [comment]
Thanks for reporting.

Which Fira Code version do you use?
My Fira Code does not have that ligature?

![image](https://user-images.githubusercontent.com/16012374/218285542-80cc96b2-a057-4f63-960e-b84ac5ecfe41.png)

Nerd Fonts patches Fira Code 6.002.

Ah I see, probably you use a pre Fira Code 6 version?

See https://github.com/tonsky/FiraCode/releases/tag/6

![image](https://user-images.githubusercontent.com/16012374/218285646-e8c56584-a5ae-4c8f-9a8b-22f3b7c83fb4.png)

* https://github.com/tonsky/FiraCode/issues/974

**Comment by Finii** [comment]
Here, how to activate the ligature...:
Note that I use the Nerd Font font.

![Peek 2023-02-12 00-47](https://user-images.githubusercontent.com/16012374/218285829-f1a885c5-080e-420a-9b61-482d21b8bcda.gif)

**Comment by FlyToEarth** [comment]
oh, thanks a lot!! My FC is v5.002 so I still have `|=` ligature default.
Also I found `Fira Code wiki` introduce two ways to make ligatures into a new font so I can make some Custom settings based on the `Fira Code NFM` like `Fira Code`:
https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets#baking-in-stylistic-sets-into-the-font-file
In this way, ligatures can display correctly in some IDEs that cannot config font ligatures.

Anyway, I'm sorry if my English makes you confused because Im a Chinese college student, We don't have much chance to practice English.😬🤐
