### ISSUE TITLE
3270 missing original license and copyright notices

### ISSUE THREAD

**Issue by rbanffy** [ryanoasis/nerd-fonts#112]
#### Subject of the issue

Missing license file. The 3270font project builds upon work that dates back to the 1980's and requires distribution of the license file (updated, if needed) along with derived works. From the license, "Redistributions in binary form must reproduce the above copyright notice"

**Comment by ryanoasis** [comment]
Apologies and thank you. Good work on the font by the way 👍 

I have tried my best to respect all the fonts licenses especially after making some mistakes early on. I think somehow here I "just missed it". I will also add the repo link

I will fix and merge this asap
