### ISSUE TITLE
Add Biglinux Linux distribution logo icon

### ISSUE THREAD

**Issue by talesam** [ryanoasis/nerd-fonts#1127]
I would like you to add the logo of the Brazilian distro Biglinux (www.biglinux.com.br) which I belong to. We are going to start using ZSH and I would like to have the icon, therefore, of biglinux in the zsh command terminal, as I verified that the most usual and correct way would be to add the icon in the collection of sources that you have, I believe that it would add more.

The SVG logo can be downloaded here: https://cloud.talesam.org/s/88wDocdnKQLLN9e

Which parameter do you use to identify the operating system and assign the correct icon to it? We are derived from Manjaro, but when I installed ZSH, the Manjaro icon appeared, it assigned this icon according to some identification in the system that is used.

**Comment by Finii** [comment]
The logo of a distribution should be added upstream, i.e. at [Font Logos](https://github.com/lukas-w/font-logos).

Nerd Font will then get the logo from them.

> Which parameter do you use to identify the operating system and assign the correct icon to it?

We just provide the font. What is displayed in the zth prompt depends on your setup, often it is not any parameter but hard coded :grimacing:
