### ISSUE TITLE
Include Operator Mono

### ISSUE THREAD

**Issue by jab** [ryanoasis/nerd-fonts#1130]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
I recently noticed there's a GitHub topic, [Operator Mono](https://github.com/topics/operator-mono), for repos about a very nice font for coding. (https://github.com/kiliman/operator-mono-lig is currently the most popular of these.) I was wondering if you might accept a PR to include this font along with the others that are included in this project.

**Describe the solution you'd like**
Operator Mono is included along with the other fonts in this collection.

**Describe alternatives you've considered**
An alternative is to obtain this font from other sources. However, including it within nerdfonts would allow e.g. Nix users to obtain it via [the "nerdfonts" Nix package](https://search.nixos.org/packages?show=nerdfonts), which would make it easier to obtain for Nix users (and similarly for other package ecosystems).

**Additional context**
Thanks for your work on this project!

**Comment by jab** [comment]
(Meant to say, I looked through the other issues in https://github.com/ryanoasis/nerd-fonts/issues?q=operator+in%3Atitle but none of them actually requested including this font with the other nerd fonts.)

**Comment by Finii** [comment]
Thanks for suggesting Operator Mono as new font.

You mention https://github.com/kiliman/operator-mono-lig
Did you actually read their readme...

![image](https://user-images.githubusercontent.com/16012374/220256278-ee74f48d-13e2-47a0-81dd-1d5d0410b7f3.png)

We can not include Operator Mono due to its licensing. It is not a free font.
That is why other issues are often about problems while self-patching it.
Self-patching your own (payed) files is the only way to get Operator Mono legally.

![image](https://user-images.githubusercontent.com/16012374/220257239-4005a558-68da-4c2b-b4e8-fc160d83c507.png)

Sorry but that is how it is.

**Comment by Finii** [comment]
Apropos Nix packages... following the link you provided:

![image](https://user-images.githubusercontent.com/16012374/220266158-12a3e09a-f8c9-420e-b8ac-9836d039e9c9.png)

That is only `v2.2.2` while we are at `v2.3.3` already :thinking:

**Comment by jab** [comment]
(If you switch to [nixpkgs "unstable"](https://search.nixos.org/packages?channel=unstable&query=nerdfonts) you'll see `v2.3.3` is there already:
<img width="894" alt="Screenshot 2023-02-21 at 6 54 37 PM" src="https://user-images.githubusercontent.com/64992/220485437-03658bd7-b39e-4883-94d8-771754efaaef.png">
)

I missed that about the license, too bad. I'm not a font expert, and haven't been keeping track of all the free vs. proprietary variants of the same font, potential license changes, etc., and assumed this might be possible based on the other repos distributing Operator Mono. Sorry about that.

Curious if you know about any free (maybe still up-and-coming) font that's inspired by Operator Mono and that may be an option here in the future. (I found [this](https://medium.com/@docodemore/an-alternative-to-operator-mono-font-6e5d040e1c7e) about combining Fira Code with another font from 7 years ago, but wonder if you maybe know of anything else in the works.

**Comment by Finii** [comment]
Thanks for the hint about nixpkgs, I will add that to my list of repackagers (https://github.com/ryanoasis/nerd-fonts/discussions/881#discussioncomment-3488054)

Font licensing is hard, and usually (cough) you can get any font you have to pay for also somewhere as download; it needs some research to find out if a particular font is now free or not. There are even github repos that contain expensive fonts that should not be redistributed (in contrast to: can be downloaded on some 'shady' warez site).

I do not know of any Operator look-alike project. But that does not say much.
New fonts will often 'register' at https://www.programmingfonts.org, where you can easily test them out.
Some new fonts are also here at Nerd Font (click link:) https://github.com/ryanoasis/nerd-fonts/labels/%E2%9D%B2Aa%E2%9D%B3%20new%20font
You need to look also into 'closed', to clean up issues I usually transfer the new-fonts to somewhere else.
