### ISSUE TITLE
[Feature Request] Add icon for neorg

### ISSUE THREAD

**Issue by matthewsia98** [ryanoasis/nerd-fonts#1135]
svg available [here](https://github.com/nvim-neorg/neorg/blob/main/res/neorg.svg)

**Comment by Finii** [comment]
We just recently added `orgmode` and now already there is an 'org mode clone', that needs a different icon? :thinking: 

* #342 
* #833

**Comment by roland-5** [comment]
It's not a clone. It's different app to create notes. Theirs syntax are different. Norg is markup language like markdown or org.

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
