### ISSUE TITLE
FontForge must be installed before running this script. BUT IT IS

### ISSUE THREAD

**Issue by CavalcanteLeo** [ryanoasis/nerd-fonts#115]
It says that I need to install FontForge on my mac, but it is installed 
macOS Sierra 10.12.1 (16B2555)

<img width="488" alt="captura de tela 2016-12-05 as 01 17 13" src="https://cloud.githubusercontent.com/assets/1735944/20872787/9385c334-ba88-11e6-8856-fa3fb0f0b4ce.png">

![captura de tela 2016-12-05 as 01 13 37](https://cloud.githubusercontent.com/assets/1735944/20872727/129a203a-ba88-11e6-9e74-bc5c21139188.png)

**Comment by ryanoasis** [comment]
Hmm I think this message is a bit misleading so my apologies.

This comes if the fontforge python support is not installed.

Can you try this `brew install fontforge --with-python` ?

**Comment by CavalcanteLeo** [comment]
Got an error to install with brew..
But do I really need to (re)install again, even if I already have it?


![captura de tela 2016-12-05 as 01 48 55](https://cloud.githubusercontent.com/assets/1735944/20873522/55dde550-ba8f-11e6-8063-8608615f9ddf.png)
<img width="1280" alt="captura de tela 2016-12-05 as 01 47 21" src="https://cloud.githubusercontent.com/assets/1735944/20873523/55f7f120-ba8f-11e6-9827-abc51558e992.png">

**Comment by ryanoasis** [comment]
I think it depends if it has the python bindings.

Are you able to execute `fontforge` from command line?

**Comment by CavalcanteLeo** [comment]
somehow, after my 3rd "brew update" and "brew doctor" I could install it. It makes completely no sense. But worked

**Comment by ryanoasis** [comment]
@CavalcanteLeo 

I am glad you got it figured out :smile: 

That is weird I am not sure why you were having troubles but doesn't seem to be related to Nerd Fonts itself. Can we close this issue?

---

It seemed like you went through some pain getting things setup :worried: but if you would like to make it easier for all of us going forward please feel free to contribute to the [dev setup of the wiki](https://github.com/ryanoasis/nerd-fonts/wiki/Contributor-Developer-Setup). 

By the way this is what I started working on after my primary OS itself stopped working just recently... so I was having to set things up all over again :laughing: :sob:
