### ISSUE TITLE
[wiki][patch] Fix some broken links in the wiki with web archived version, patch included

### ISSUE THREAD

**Issue by Calciferz** [ryanoasis/nerd-fonts#1153]
Hello! A few links are broken. See the patch attached below for the fix (can't edit wiki). Thank you.

#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

**Experienced behavior:**
Broken links in wiki page: https://github.com/ryanoasis/nerd-fonts/wiki/Real-World-Mentions-&-Usage-(Sightings)
**Expected behavior:**  Working links
**Example symbols:**  -- Not an issue with the fonts --

### 🩹 Patch

Patch (git, zip): [0001-Fix-some-broken-links-with-archived-version.zip](https://github.com/ryanoasis/nerd-fonts/files/11066413/0001-Fix-some-broken-links-with-archived-version.zip)

Links:
* [Revamp your Mac OSX terminal experience (Web archive)](https://web.archive.org/web/20190508163338/http://blog.gabrielfortuna.net:80/revamp-your-mac-osx-terminal-experience/)
* [Terminal Development That Doesn't Suck (Web archive)](https://web.archive.org/web/20161028091320/http://kevindiale.com/terminal-development-that-doesnt-suck/)
* [Introduction to the world of ricing (Web archive)](https://web.archive.org/web/20161227200933/https://zoug.me/introduction-to-ricing/)  
* [Ricty + Powerline + NERDFonts (Web archive)](https://web.archive.org/web/20170203145426/http://do.kalaclism.com/items/6789873727d34f38b71ff1c0143b5fc6)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - N/A
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - N/A
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - N/A
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - N/A

#### ★ Screenshots (Optional)

N/A

**Comment by Finii** [comment]
Thanks for reporting and fixing :heart_eyes:

**Comment by Finii** [comment]
Done. Thanks again.

![image](https://user-images.githubusercontent.com/16012374/227707067-9ab9770e-0afd-4053-97aa-c415bcd1dd73.png)

**Comment by Finii** [comment]
@allcontributors add @Calciferz for doc
