### ISSUE TITLE
In Lilex Medium cyrillic capital Ы is broken

### ISSUE THREAD

**Issue by ShinyZero0** [ryanoasis/nerd-fonts#1157]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Cyrillic capital letter Ы has chopped off right vertical line as on screenshot in Kitty terminal emulator as well as in FontForge. It's only with any Medium weight version. Bold, regular and light are ok.

Expected behavior:
Normal look of letter

Example symbols:
ЫЫЫЫЫЫЫ

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
 - Lilex Medium Nerd Font Complete, any of ttf/otf; Mono/not; Windows-compatible/not
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
 - Releases archive v2.3.3
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
 - Kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
 - Linux Fedora 37 (Nobara)

#### ★ Screenshots (Optional)
![Чт 30 мар 2023 13:36:23 MSK](https://user-images.githubusercontent.com/105050391/228814669-163cd380-c404-423d-9a39-515beee02b37.png)

**Comment by Finii** [comment]
git checkout v2.3.3:

<img width="1082" alt="Screenshot 2023-03-30 at 18 54 48" src="https://user-images.githubusercontent.com/16012374/228909542-7d273200-818a-454f-86ea-44cefca63dd7.png">

**Comment by Finii** [comment]
Meanwhile we updated Lilex to 1.100 but still existing:

<img width="1084" alt="Screenshot 2023-03-30 at 18 58 43" src="https://user-images.githubusercontent.com/16012374/228910514-12c3bacb-c80f-41fa-b99e-1bfbee1da881.png">

**Comment by Finii** [comment]
Hmm, Lilex is strange.

With 1.0 -> 1.100 they dropped the Light weight.
With 1.100 -> 2.000 they reintroduce Light but drop Medium.

So with 2.000 this problem will be solved by ... removing Medium :grimacing: 
I did not check the variable font, and why there is such an issue at all.

**Comment by Finii** [comment]
Thanks for reporting! Excellent report with all the necessary info!

Well, I do not know if dropping Medium really helps you (because Regular seems to be too thin for you), but that is what they did upstream and we can only follow upstream. Just wanted to raise this issue there, but the Medium weight is gone now...

If you really want Medium you can take the VF and export a Medium instance, and then self patch ... sorry.

**Comment by Finii** [comment]
Lilex fixed this today and it will go into (their) 2.100.
