### ISSUE TITLE
Add codepoint screenshot for Patched/Complete Octoicons

### ISSUE THREAD

**Issue by kaymmm** [ryanoasis/nerd-fonts#116]
## Add codepoint screenshot for Patched/Complete Octoicons

The codepoints for the octoicons in the complete sets are moved to avoid clashing with the FontAwesome code points, but the README doesn't make mention of this (I discovered this via the Powerlevel9k git issues). It doesn't make sense to have two screenshots on the README with both sets of codepoints, but maybe it could go in the Wiki? I've attached a Font Forge screenshot that mirrors the one in the README but shifted for the Patched/Complete fonts.

![patched-complete-octoicons](https://cloud.githubusercontent.com/assets/2266804/21038280/208a9d1a-bd89-11e6-829c-db2a900b46ec.png)

**Comment by ryanoasis** [comment]
@kaymmm Hey thanks for this I do appreciate it :smile: 

Sorry for the delay. We have been hard at work on [v1.0.0](https://github.com/ryanoasis/nerd-fonts/tree/0.9.0) :smile: 

> but the README doesn't make mention of this

Yeah... and this has caused confusion before... which is clearly understandable. I had been wanting to change this on the readme as well so I agree 100%

> It doesn't make sense to have two screenshots on the README with both sets of codepoints, but maybe it could go in the Wiki?

Again I agree with this. README should have the codepoints for the 'complete' variation and maybe below a link to the Wiki to view the original codepoints. Something like that I think you are saying.

I envision it as something like this:

---

### Octicons
> GitHub's icons. / repo / ([website](https://octicons.github.com))

#### Nerd Font Complete Codepoints:*
![nerd-fonts-complete-octicons](https://cloud.githubusercontent.com/assets/2266804/21038280/208a9d1a-bd89-11e6-829c-db2a900b46ec.png)

<sub>* To avoid conflicts between icon sets these were modified. To view the original codepoints see the [Wiki](link-to-relevant-octicons-page)</sub>

---

Any thoughts? I am open to any suggestions that make things better and easier :smile:

**Comment by kaymmm** [comment]
I like your idea. My only suggestion is to be explicit which versions of the fonts use these codepoints. Perhaps something like: "To avoid conflicts between icon sets, these were modified in the 'Complete' fonts. To view the original codepoints see the Wiki."

**Comment by ryanoasis** [comment]
Thanks, we'll go with that
