### ISSUE TITLE
Font Patcher: UnboundLocalError: cannot access local variable 'box_keep' where it is not associated with a value

### ISSUE THREAD

**Issue by hrqmonteiro** [ryanoasis/nerd-fonts#1170]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Following error when trying to patch font (tried all the methods):

```
fontforge -script font-patcher Roboto-Regular.ttf -c
Copyright (c) 2000-2022. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20220308
 Based on sources from 2022-07-21 00:00 UTC-ML-D-GDK3.
Nerd Fonts Patcher v2.3.3 (3.7.1) (ff 20220308) executing
The following table(s) in the font have been ignored by FontForge
  Ignoring 'hdmx' horizontal device metrics table
Traceback (most recent call last):
  File "/home/hrq/Downloads/nerd-fonts-master/font-patcher", line 1943, in <module>
    main()
  File "/home/hrq/Downloads/nerd-fonts-master/font-patcher", line 1923, in main
    patcher.patch(sourceFonts[-1])
  File "/home/hrq/Downloads/nerd-fonts-master/font-patcher", line 326, in patch
    self.setup_patch_set()
  File "/home/hrq/Downloads/nerd-fonts-master/font-patcher", line 880, in setup_patch_set
    'default': {'align': 'c', 'valign': 'c', 'stretch': 'xy', 'params': {'overlap': 0.02, 'dont_copy': box_keep}},
                                                                                                       ^^^^^^^^
UnboundLocalError: cannot access local variable 'box_keep' where it is not associated with a value
```

Expected behavior:
Not to happen this error?

Example symbols:
I don't get this.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
  None, trying to patch
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
  Google Fonts
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   Error happens in any terminal emulator
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
  Fedora 37

#### ★ Screenshots (Optional)

![Screenshot from 2023-04-13 18-40-50](https://user-images.githubusercontent.com/17055027/231889050-efd60c6d-76da-4b0b-9125-0aec2d13a276.png)

**Comment by Finii** [comment]
Sorry to hear of your problem :-(
I must have butchered something, fixing right away...

**Comment by hrqmonteiro** [comment]
Thanks a lot!
