### ISSUE TITLE
[Feature Request] Add icon for astro

### ISSUE THREAD

**Issue by BrunoKrugel** [ryanoasis/nerd-fonts#1172]
**Requirements**

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
[Astro](https://astro.build/) filetype does not have an icon in nerd-fonts

**Describe the solution you'd like**
An icon for .astro file types 

**Additional context**
SVG available [here](https://github.com/PKief/vscode-material-icon-theme/blob/main/icons/astro.svg).

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
