### ISSUE TITLE
Bitstream Vera is RFN

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#1173]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

`Bitstream Vera` has a RFN like license, that is rather explicit.
We do not do any renaming, which is wrong.

Experienced behavior:
Font name `Bitstream Vera Nerd Font`

Expected behavior:
Font name does not contain `Bitstream` and/or `Vera`, as stated https://github.com/ryanoasis/nerd-fonts/blob/master/src/unpatched-fonts/BitstreamVeraSansMono/Bitstream%20Vera%20License.txt

![image](https://user-images.githubusercontent.com/16012374/233370474-00a6c208-41b7-4740-91e8-b003721e8936.png)

![image](https://user-images.githubusercontent.com/16012374/233765565-3b8bb3dc-3786-47b8-871a-0ba036e4e988.png)

#### 🔧 Your Setup

n.a.

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/16012374/233370168-0d211704-3cb5-47dd-bb10-533415279530.png)

**Comment by Finii** [comment]
Any name ideas very welcome! (If someone reads this...)

**Comment by 237dmitry** [comment]
Vitstream Bera Sans Mono ))

**Comment by Finii** [comment]
A shorter name would be better, though (*).

`Vitsream Bera`
`Stream Wera`
`Bitstrom Vero`
`BS Wera`

Here what we replace at the moment:
```
SourceCodePro            SauceCodePro
Hermit                   Hurmit
Hasklig                  Hasklug
ShareTechMono            ShureTechMono        
IBM-plex                 Blex
Terminus                 Terminess    
Liberation               Literation    
iA-Writer                iM-Writing
Anka/Coder               AnaConder  
Cascadia Code            Caskaydia Cove
IBM 3270                 3270    
```

(*) Do not forget the the original name is `Bitstream Vera Sans Mono` which is longer than anything else...

**Comment by Finii** [comment]
`Bytestream Vira`

via https://github.com/ryanoasis/nerd-fonts/issues/998#issuecomment-1520225512
