### ISSUE TITLE
Caskaydia Cove has broken infinite ligatures

### ISSUE THREAD

**Issue by OldWorldOrdr** [ryanoasis/nerd-fonts#1184]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

ligatures that extend infinitely as you keep adding more characters, such as - and =, are too short on kitty, I originally files a bug report with kitty since it renders correctly on Windows Terminal and Termux, but they said it was an issue with the font and I should file a report here
My original kitty bug report: https://github.com/kovidgoyal/kitty/issues/6220
My kitty config: https://oldworldorder.gay/kitty.conf

Expected behavior:

The ligatures should be the correct length

Example symbols:

`--------------------------------------a`
`======================================a`

pasting these in kitty with the right font will show a gap between the end of the `-` or `=` and the `a`
#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - I put everything from the `CascadiaCode.zip` file in `/Library/Fonts` and set my font name in the kitty config to `CaskaydiaCove Nerd Font Mono`, so there's not really one filename, it's everything in the `CascadiaCode.zip` file
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Downloaded from https://www.nerdfonts.com/font-downloads, which appears to link directly to the github releases
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Mac OS X, also happens on linux

#### ★ Screenshots (Optional)

<img width="602" alt="Screen Shot 2023-04-30 at 6 08 58 PM" src="https://user-images.githubusercontent.com/57970114/235378368-7b0d5a3d-0995-49ec-b9ec-97355050b91c.png">

**Comment by longnguyen2004** [comment]
What version are you using? v3.0.0 or previous

**Comment by Finii** [comment]
Sorry to hear of that problem.

I guess that (Nerd Font version) would make no difference.
Did you try the non-Mono version (`Caskaydia Cove Nerd Font - Regular`)?

I know there is a bug in fontforge that breaks tables sometimes, was too lazy to fix that yet - hoped we are not afftected. But then I only test 'normal' ligs, never thought someone would use THAT :grimacing: 

But than ... thinking and seeing that visually, maybe it is a wrong assumption in the (my) code.

Kitty makes certain assumptions how a font should look like. Most interesting is always if a normal text processor (`writer`, `word`) does the same:

![image](https://user-images.githubusercontent.com/16012374/235408726-790b5889-c49c-42e6-99a3-db287376e38b.png)

Did you try the original, i.e. `Cascadia Code` in `kitty`, does it work with that font?

Still being in the release aftermath, will take some time until I can tackle normal issues.

**Comment by Finii** [comment]
Your kitty conf, condensed:

```
font_family      CaskaydiaCove Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13.0
url_color #FFFFFF
url_style straight
repaint_delay 7
sync_to_monitor yes
remember_window_size  no
initial_window_width  648
initial_window_height 405
foreground #FFFFFF
background #1C1C1C
selection_foreground #000000
selection_background #FFFFFF
color0 #0F0F0F
color8 #5E5C64
color1 #C01C28
color9 #DB3A3A
color2  #26A22A
color10 #2EC736
color3  #B68708
color11 #E9AD0C
color4  #12499B
color12 #2A7BDE
color5  #A347BA
color13 #C061CB
color6  #2AA1B3
color14 #33C7DE
color7  #D0CFCC
color15 #FFFFFF
editor /usr/local/bin/nvim
wayland_titlebar_color background
```

My kitty conf:
```
font_family CascaydiaCove NFM
font_size 15
```

I do not even see any ligature. Maybe my kitty is too old?

![image](https://user-images.githubusercontent.com/16012374/235409819-a3ae828d-77f0-436f-bebd-d6c85dbc1737.png)

**Comment by longnguyen2004** [comment]
> I know there is a bug in fontforge that breaks tables sometimes

When will we switch to something like fontmake/fonttools? 😆

**Comment by Finii** [comment]
> > I know there is a bug in fontforge that breaks tables sometimes
> 
> When will we switch to something like fontmake/fonttools? laughing

As soon as possible. As that would enable also patching VFs.

Otoh I burned so much time for 3.0.0 now, I need to spend some time now for my day-work before starting something time consuming again.
* https://github.com/ryanoasis/nerd-fonts/milestone/25?closed=1

**Comment by OldWorldOrdr** [comment]
> What version are you using? v3.0.0 or previous

2.3.3, made this issue right before 3.0.0 came out.  I tried with 3.0.0 and the bug is still present on MacOS (Big Sur), but not Arch Linux, maybe I misremembered experiencing the bug on linux.

> perhaps my kitty is too old

I'm using the latest kitty version

> Did you try the non-Mono version (`Caskaydia Cove Nerd Font - Regular`)?

setting font to `Caskaydia Cove Nerd Font - Regular` in my kitty config doesn't fix it

**Comment by Finii** [comment]
Thanks.

Did you compare with the unpatched `Cascadia Code` - if it's an issue already there it has nothing to do with Nerd Fonts' patching. Then it is just something like 'Kovid thinks this font (i.e. Cascadia Code) is buggy'.

**Comment by Finii** [comment]
@OldWorldOrdr 

Can not reproduce (with `kitty` build from HEAD):

![image](https://user-images.githubusercontent.com/16012374/235891439-dbd905d3-e5f7-4483-9e65-94c6a97e063a.png)

Maybe some already fixed bug?

**Comment by OldWorldOrdr** [comment]
Only happens on macos, I need to edit the bug description to clarify that
