### ISSUE TITLE
Installer no longer works in version 3.0.0

### ISSUE THREAD

**Issue by aidan-mundy** [ryanoasis/nerd-fonts#1185]
#### 🗹 Requirements
- [ x ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [ x ] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [ x ] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
```
$ sudo ./install.sh -S -C Hack
removed '/usr/local/share/fonts/NerdFonts/.uuid'
removed directory '/usr/local/share/fonts/NerdFonts'
mkdir: created directory '/usr/local/share/fonts/NerdFonts'
cp: missing destination file operand after '/usr/local/share/fonts/NerdFonts'
Try 'cp --help' for more information.
/usr/local/share/fonts/NerdFonts: caching, new cache contents: 0 fonts, 0 dirs
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded
```

Install claims to succeed, but actually fails on `cp: missing destination file operand` and does not copy any font files. v3.0.0 fails, but v2.3.3 succeeds. 

Expected behavior:
Install should complete successfully and copy all font files.

#### 🔧 Your Setup

- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - git clone & git checkout v3.0.0
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - gnome
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Ubuntu 22.04

**Comment by Finii** [comment]
Sorry to hear that, let me see...

**Comment by Finii** [comment]
Ah yes. Will be fixed after breakfast.

**Comment by Finii** [comment]
Fixed via https://github.com/ryanoasis/nerd-fonts/commit/da651cf5a895af67eca502a6a3bcc4c1ea363395
