### ISSUE TITLE
Missing Azure Icon in 3.0.0

### ISSUE THREAD

**Issue by Tiberriver256** [ryanoasis/nerd-fonts#1186]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
When attempting to use this icon

![image](https://user-images.githubusercontent.com/6989492/235455239-da16f12a-eae1-45dd-aca1-c02e75cfdea8.png)

It does not seem to render:

![image](https://user-images.githubusercontent.com/6989492/235455268-91fcdb58-abbb-45a3-8a6e-2efe4ec71bcf.png)

Expected behavior:
It should render

Example symbols:
ebe8

![image](https://user-images.githubusercontent.com/6989492/235455239-da16f12a-eae1-45dd-aca1-c02e75cfdea8.png)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - CaskaydiaCove Nerd Font
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - main branch of this repo
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Windows Terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows 11

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/6989492/235455558-16d2dcf8-eb52-4715-8ee0-d58ef0389c5a.png)

**Comment by Finii** [comment]
The glyph is there:

![image](https://user-images.githubusercontent.com/16012374/235462437-0b4a6bb2-3f23-4360-9926-af7e314a3333.png)

Sure you have 3.0.0 installed? Rebootet?

**Comment by Finii** [comment]
If you cant find the reason, feel free to reopen. Tnx.

**Comment by MO2k4** [comment]
@Tiberriver256 did you figure out, what was the issue? i notice the missing azure icon with Fira Code Nerd font as well

**Comment by Finii** [comment]
Starting up some Windows box...

**Comment by Tiberriver256** [comment]
For some reason, it looks like I only have up to the `E7xx` range for glyphs before it jumps straight to the `F0xx`

Searching inside [this file](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/CascadiaCode/Regular/CaskaydiaCoveNerdFont-Regular.ttf).

![2023-05-04_9-34-17](https://user-images.githubusercontent.com/6989492/236222885-d8be5451-4a95-4d5c-a2ab-075e36331a0d.gif)

**Comment by Finii** [comment]
Well,

* Did not have any Caskaydia installed yet
  * If you do, remove all Caskaydia and **reboot**
* Download Caskaydia Cove Nerd Font 3.0.0 Release zip
* Unzip
* Select all font files and choose install
* Run Windows Terminal
* Select `CaskaydiaCove NF`
* etc ... see image:

![grafik](https://user-images.githubusercontent.com/16012374/236221190-0be1c566-6e16-40f8-8d68-26f135160f8f.png)

I see no problem.

Here the settings:

![grafik](https://user-images.githubusercontent.com/16012374/236223335-bcf52bd6-3f39-4e80-b53c-72cecf9f4c5f.png)


![grafik](https://user-images.githubusercontent.com/16012374/236222406-8d1c841f-4186-4408-9308-9dbc27ac79c2.png)

_Nice, Caskaydia Cove Nerd Font Propo can not be selected_

**Comment by Tiberriver256** [comment]
Reinstalled from the release zip, and now I've got it 🤷‍♂️

Thanks for the help!

![image](https://user-images.githubusercontent.com/6989492/236225653-5261ffdc-47e4-4217-8065-e1c400c9fe54.png)

**Comment by Finii** [comment]
> For some reason, it looks like I only have up to the E7xx range for glyphs before it jumps straight to the F0xx

That looks like a Nerd Font version 2.1.0 or something.

Make sure to uninstall all Caskaydia Code fonts, reboot, then install 3.0.0 fonts.
Double check version in font settings:

![grafik](https://user-images.githubusercontent.com/16012374/236227282-345ddcb3-2802-44e0-ab82-1d129939e317.png)

check for 3.0.0

![grafik](https://user-images.githubusercontent.com/16012374/236227669-d975d16f-9837-4860-a101-e45e54bca3db.png)

**Comment by Finii** [comment]
> Reinstalled from the release zip, and now I've got it 🤷‍♂️

Usually installing a new version over an old version does work in windows.
But only if the old font was not corrupt ;-D
Sometimes it does not work, like ... on your machine obviously. The 2.1.0 fonts had many bugs font-technically, though...
