### ISSUE TITLE
Document the new code points

### ISSUE THREAD

**Issue by musjj** [ryanoasis/nerd-fonts#1189]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
The list of code points are not documented.

**Describe the solution you'd like**
Document the code points. I need this info, because the Kitty terminal has a special way of loading nerd fonts. 

For it to work, you need to specify the normal non-nerd version of the font, and it will automatically load symbols from the nerd version as needed. 

But the JetBrains Mono font is named inconsistently (`JetBrainsMono Nerd Font` and `JetBrains Mono`), and I think this breaks the auto-loading.

So I have to manually specify the codepoints this way:
https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font
```
font_family JetBrains Mono
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,
U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,
U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,
U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 JetBrainsMono Nerd Font
```

But this broke on the last update. I assume that the mapping have changed somewhat, so it would be nice to have it documented somewhere.

**Comment by Finii** [comment]
Maybe https://github.com/ryanoasis/nerd-fonts/blob/master/glyphnames.json can help you?

At least on superficial glance your specification looks good, just
* drop `U+F500-U+F8FF`
* exchange `U+F400-U+F4A9` to `U+F400-U+F532`

The documentation would be https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points but I did not manage to update many docs yet...

> But the JetBrains Mono font is named inconsistently

That depends on what you mean by consistency. That naming scheme is in effect for Nerd Fonts for ... long.
(i.e. dropping the blanks in the original name)

**Comment by musjj** [comment]
I've tried your change, glyphs are no longer blanked out, but it's now displaying the wrong glyphs. It works fine on Wezterm, so I'm pretty sure the program I'm using is outputting the correct code points.

Not sure what's wrong here. For now, I'm just gonna stick to the previous version.

**Comment by Finii** [comment]
Updated https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points, so the original issue is fixed.

**Comment by musjj** [comment]
I've updated my code points in my kitty config, but it's still displaying the wrong glyphs. I don't think this is caused by the recent backwards compatibility-breaking update, because Wezterm works just fine.

```
# Seti-UI + Custom
symbol_map U+E5FA-U+E6AC Symbols Nerd Font
# Devicons
symbol_map U+E700-U+E7C5 Symbols Nerd Font
# Font Awesome
symbol_map U+F000-U+F2E0 Symbols Nerd Font
# Font Awesome Extension
symbol_map U+E200-U+E2A9 Symbols Nerd Font
# Material Design Icons
symbol_map U+F0001-U+F1AF0 Symbols Nerd Font
# Weather
symbol_map U+E300-U+E3E3 Symbols Nerd Font
# Octicons
symbol_map U+F400-F532,U+2665,U+26A1 Symbols Nerd Font
# Powerline Symbols
symbol_map U+E0A0-E0A2,U+E0B0-E0B3 Symbols Nerd Font
# Powerline Extra Symbols
symbol_map U+E0A3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D4 Symbols Nerd Font
# IEC Power Symbols
symbol_map U+23FB-U+23FE,U+2B58 Symbols Nerd Font
# Font Logos
symbol_map U+F300-U+F32F Symbols Nerd Font
# Pomicons
symbol_map U+E000-U+E00A Symbols Nerd Font
# Codicons
symbol_map U+EA60-U+EBEB Symbols Nerd Font
# Heavy Angle Brackets
symbol_map U+E276C-U+2771 Symbols Nerd Font
# Box Drawing
symbol_map U+2500-U+259F Symbols Nerd Font
```

**Comment by bew** [comment]
@musjj Wezterm was probably working fine because it's using the internal nerdfont symbols, not the one you installed. (wezterm didn't update its nerdfont version afaik)

**Comment by Finii** [comment]
> I've updated my code points in my kitty config, but it's still displaying the wrong glyphs.

I do not understand clearly what your issue is. Maybe really raise a new issue. This issue here (documentation missing) is solved, right?

**Comment by musjj** [comment]
Yes, I've put an edit at the bottom of my post clarifying that the issue has been solved, but I guess it's hard to notice.

The issue was caused by incorrect codepoints (due to the recent update), but I misdiagnosed the issue because I forgot about Wezterm's built-in nerd fonts

**Comment by Finii** [comment]
Thank you for clearing this up! :+1:
