### ISSUE TITLE
Standardize console message with prefix of [Nerd Fonts] always

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#119]
#### Standardize console message with prefix of [Nerd Fonts] always

The output messages in the Python and various shell scripts should have a standardized prefix so that we know if the message comes from Nerd Fonts or another program (such as FontForge). This will help with debug and issues where we ask for output.

**Comment by morrme** [comment]
So for example, you want messages like this
`echo "# No release version given, must give semver release versionin format: #.#.#, e.g. 1.1.0"`
prefixed with [Nerd Fonts] like

`echo "# [Nerd Fonts] No release version given, must give semver release version in format: #.#.#, e.g. 1.1.0"`

**Comment by ryanoasis** [comment]
@morrme Yep, that is basically correct :smile: 

Preferably there would be some sort of defined variable I think as well, for example see: https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/upload-archives.sh#L24

Let me know if you have any other questions or suggestions (open to any good ones :blush: )

**Comment by morrme** [comment]
Why wouldnt the message on this line:
https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/upload-archives.sh#L20

be prefixed?

**Comment by ryanoasis** [comment]
@morrme Yes it should be in my opinion :smile:

**Comment by vladyio** [comment]
Hey, guys. I'd like to take this issue, and I have a question about [this line](https://github.com/vladyio/nerd-fonts/blob/master/bin/scripts/generate-casks.sh#L55):

Should it be like `printf "#$LINE_PREFIX Found Font: %s\n" "${fonts[$i]}"`?

And also about Python scripts, e.g. [this one](https://github.com/vladyio/nerd-fonts/blob/master/bin/scripts/fpfix.py#L16), shoud it be like that? 

    sys.stderr.write("{LINE_PREFIX}[fpfix.py] ERROR: Please enter a path to the font file".format(LINE_PREFIX=LINE_PREFIX)

**Comment by ryanoasis** [comment]
@vladyio Hey thanks however I think @morrme chimed in first.

I believe @morrme is taking up this item. Are you taking this on @morrme ?

---

@vladyio, if @morrme is not working on it you could take it up. If not you could take on other issues or possibly other improvements or general standardization on the scripts if you have ideas :smile:

**Comment by morrme** [comment]
Yes, I'd already been working on this.

**Comment by vladyio** [comment]
Oh, okay. Sorry then :)

**Comment by ryanoasis** [comment]
@vladyio No worries (some of that is my fault). I really appreciate the initiative you took however and looked like you were making good progress :smile: 

I hope this doesn't dissuade you from possibly contributing to other tickets or opening a Pull Request of anything you might have found in the scripts! :blush: 

Would love to have more contributors :heart:
