### ISSUE TITLE
Victor Mono icon sizes seem to have changed in a recent update (v3?)

### ISSUE THREAD

**Issue by ezzatron** [ryanoasis/nerd-fonts#1195]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

- Icons are much smaller than they used to be prior to updating Victor Mono.

Expected behavior:

- Icon sizes remain consistent after updating Victor Mono.

Example symbols:

- `` (GitHub logo)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - `VictorMonoNerdFontMono-SemiBold.ttf` (I'm not 100% sure, in iTerm it was `VictorMonoNerdFontComplete-SemiBold 17` before the update, and `VictorMonoNFM-SemiBold 17` after)
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - I installed `font-victor-mono-nerd-font` via https://github.com/Homebrew/homebrew-cask-fonts
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - iTerm2 3.4.19
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - macOS Ventura 13.3.1

#### ★ Screenshots (Optional)

This is what the icons looked like before the update:

<img width="920" alt="Screenshot 2023-01-23 at 11 55 17" src="https://user-images.githubusercontent.com/100152/235813415-b7b451ca-648a-4455-9cf0-9ffe0fb5bfb5.png">

This is after:

<img width="691" alt="Screenshot 2023-05-03 at 10 15 07" src="https://user-images.githubusercontent.com/100152/235813443-1d0000e5-8915-400d-83c3-84608b07f45d.png">

**Comment by Finii** [comment]
> VictorMonoNerdFontMono-SemiBold.ttf (I'm not 100% sure, in iTerm it was VictorMonoNerdFontComplete-SemiBold 17 before the update, and VictorMonoNFM-SemiBold 17 after)

Well, the 'before' image shows a `Nerd Font` variant and the 'after' images shows a `Nerd Font Mono` variant.

So before you seem to indeed have used
`VictorMonoNerdFontComplete-SemiBold` (note: not `Nerd Font *Mono* Complete`)

Afterwards you use `VictorMonoNFM-SemiBold` (where `NFM` stands for `Nerd Font Mono`.

As you installed the cask you should have all variants installed.
Should be sufficient to change your `iTerm` config, remove the `M` from the family name:

` VictorMonoNF-SemiBold`

Please report back if that fixes your problem and/or close this issue :-)
