### ISSUE TITLE
otf file cannot be opened on Windows7

### ISSUE THREAD

**Issue by strrchr** [ryanoasis/nerd-fonts#12]
All ttf files are OK.
And otf files of https://github.com/powerline/fonts are OK.
But otf files of this project cannot be opened on Windows7.
Does anyone else has this problem?

**Comment by ryanoasis** [comment]
@strrchr Sorry about this yes there is a problem. I ran into this a week or so ago. 

Windows has trouble installing fonts with internal font name longer than **31 characters**. If you have fontforge you can try to regenerate with a **shorter name** or you would have to wait for a patch (I need to regenerate all the fonts with names that work on windows **and** give an option to the patcher to limit to 31 characters)

I assume you were seeing something similar to this:
![selection_23_06_15_09 38 32_367x168_001](https://cloud.githubusercontent.com/assets/8083459/8307314/01d95c8c-198c-11e5-90c2-2caa45b4b557.png)

**Comment by ryanoasis** [comment]
OKay so it is not related to just the filename. I will have to take another look. the `ttf` fonts seem to install okay on windows (so far)

**Comment by ryanoasis** [comment]
*not* actually fixed (accidentally marked as fix in a commit)

**Comment by ryanoasis** [comment]
This is no longer an issue (**_except for font 3270_**),

tested opening the following fonts (otf version):

- **_3270-Medium Nerd Font Complete Windows Compatible (failing)_**
- AurulentSansMono-Regular Nerd Font Complete Windows Compatible
- Code New Roman Bold Nerd Font Complete Windows Compatible
- Droid Sans Mono for Powerline Nerd Font Complete Windows Compatible
- Fura Code Regular Nerd Font Complete Windows Compatible
- Fura Mono Regular for Powerline Nerd Font Complete Windows Compatible
- Hasklug Nerd Font Complete Mono Windows Compatible
- Hurmit Medium Nerd Font Complete Windows Compatible
- Inconsolata for Powerline Nerd Font Complete Windows Compatible
- Meslo LG M Regular for Powerline Nerd Font Complete Mono Windows Compatible

**Comment by ryanoasis** [comment]
tested opening the following fonts (otf version):

- :white_check_mark: 3270-Medium Nerd Font Complete Windows Compatible (now passing!) 
- :white_check_mark: AurulentSansMono-Regular Nerd Font Complete Windows Compatible
- :white_check_mark: Code New Roman Bold Nerd Font Complete Windows Compatible
- :white_check_mark: Droid Sans Mono for Powerline Nerd Font Complete Windows Compatible
- :white_check_mark: Fura Code Regular Nerd Font Complete Windows Compatible
- :white_check_mark: Fura Mono Regular for Powerline Nerd Font Complete Windows Compatible
- :white_check_mark: Hasklug Nerd Font Complete Mono Windows Compatible
- :white_check_mark: Hurmit Medium Nerd Font Complete Windows Compatible
- :white_check_mark: Inconsolata for Powerline Nerd Font Complete Windows Compatible
- :white_check_mark: Meslo LG M Regular for Powerline Nerd Font Complete Mono Windows Compatible
- :white_check_mark: OpenDyslexic Regular Nerd Font Complete Mono Windows Compatible
- :white_check_mark: Overpass Mono Regular Nerd Font Complete Mono Windows Compatible
- :white_check_mark: Sanity check on all other (ttf) fonts - one style per family (Windows 7)
