### ISSUE TITLE
Implement and enforce standards for Bash (shellcheck)

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#120]
#### Implement and enforce standards for Bash (shellcheck)

I currently enable [shellcheck ](https://github.com/koalaman/shellcheck) in my Vim when I am editing the bash scripts for this project but it would be nice to comb through the current scripts and make them compliant and even better would be to setup some sort of task (Travis CI) to check these when devs make Pull Requests

**Comment by andrewimeson** [comment]
I have it working, but there are a lot of shellcheck complaints that will either need to be fixed, ignored globally, or exempted on a case-by-case basis within each script. I have excluded SC2034 globally, as that seemed sensible.

Should I make a pull request now, or is there more work that needs to be done? I will need to update a few references that specifically point to my fork of the repo before submitting my pull request, and you will have to log in to Travis CI to add it for your repo.

[andrewimeson/nerd-fonts/tree/add-shellcheck-ci](https://github.com/andrewimeson/nerd-fonts/tree/add-shellcheck-ci)

**Comment by ryanoasis** [comment]
@andrewimeson Awesome sounds great so far. Thanks for contributing :smile: 

> Should I make a pull request now, or is there more work that needs to be done?

Probably more work to be done but the PR can be a WIP too. Let me think about this a little? :blush: 

I am also going to go ahead and remove most of the labels so no one else works on this :smile:

**Comment by andrewimeson** [comment]
@ryanoasis I'm thinking it probably makes sense to submit the pull request that adds CI apart from any code changes that fix the problems that CI discovers.

There are probably some enhancements I could make the Travis CI configuration so that it takes less time to run.

**Comment by ryanoasis** [comment]
@andrewimeson Ah yes that makes more sense. You have my support to go ahead with the separate PRS 😄
