### ISSUE TITLE
Fonts Patching requests: Envy Code R

### ISSUE THREAD

**Issue by DizzyC** [ryanoasis/nerd-fonts#1205]
I would love to see **Envy Code R** patched - https://damieng.com/blog/2008/05/26/envy-code-r-preview-7-coding-font-released/
The author Damien Guard (https://github.com/damieng) is prepared to grant permission for this: https://github.com/ryanoasis/nerd-fonts/issues/386#issuecomment-1408890859

Although it is 15 years old, this font is still quite beloved for programming and terminal use.

**Comment by damieng** [comment]
I'm happy to grant more liberal licence terms - I've not modified the font in a decade.

**Comment by damieng** [comment]
I've now licenced it under SIL 1.1

**Comment by Finii** [comment]
Thank you!

Im still in the release aftermath, and then some docu modernization, then this can come in 3.1.0

Thank you again, Fini

**Comment by Finii** [comment]
Now with `v3.0.2` out I guess bug fixing phase is over.

I remember when I last worked on this, to my surprise the advance width in the UFO was some strange `1103` or something, while it is `1100` in the released `ttf` file. The outlines themselves seemed to be untouched, so maybe you wanted to just increase letter spacing a bit? Or is it a mistake? @damieng 

![Screenshot 2023-06-05 at 18 56 54](https://github.com/ryanoasis/nerd-fonts/assets/16012374/8f263364-6f00-4d5e-b9f8-fd71e416d651)

**Comment by damieng** [comment]
I suspect this was a mistake with my conversion to UFO from FontLab 5 but I thought your tools patch the TTF binary?:

The problem with the UFO's is that all the hinting did not come across so it won't look anywhere near as good on Windows etc.

**Comment by Finii** [comment]
> I thought your tools patch the TTF binary

I just could not find any place where I can download that with the new license. Just the UFO had that, and that was 0.8, while the ttf was 0.79, so ... But I read this as "the TTF shall have the same license as the UFO and feel free to use it" :-)
That makes of course everything much more simple.

**Comment by damieng** [comment]
Yes, please consider the 0.8 version of Envy Code R also under the new license. I can attach the final binaries to the release page of the repo if you like.

**Comment by Finii** [comment]
Noticed you did that (putting the ttf in a github release)! Thank you!
