### ISSUE TITLE
some glyphs not updated to new codepoints

### ISSUE THREAD

**Issue by FlyingPotato-131** [ryanoasis/nerd-fonts#1206]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

some glyphs that have been moved are not displayed when using the new codepoints, but are displayed when using the old ones

Expected behavior:

said glyphs are displayed when using new codepoints

Example symbols:

namely f0343 and f05fd do not work while f842 and fafc (their old codepoints) do

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - SymbolsNerdFont-Regular.ttf
   - SymbolsNerdFontMono-Regular.ttf
   - FiraCodeNerdFont-*.ttf (was used for testing)

- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - symbols from the aur, then from [the website](https://www.nerdfonts.com/font-downloads)
   - fira from the aur
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - konsole, but the issue persists in Rofi, Firefox, basically anywhere (except for fontmatrix)
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - EndeavourOS Qtile (basically Arch Linux), updated several hours ago

**Comment by Finii** [comment]
I checked the zip archives from nerdfonts.com and they do not contain glyphs at the `F800` region:

The AUR packages are also updated to 3.0.0 has far as I can see.

Somehow the old versions must have persisted on your system. Try to reboot and/or update the `fc-cache`. Check the version number in the actual fonts you have installed maybe?

**Comment by FlyingPotato-131** [comment]
I have rebooted and updated fc-cache (in fact those were the first things I did), the installed aur package is version 3.0.0-2. very strange...

**Comment by Finii** [comment]
You could check `fc-list ':charset=f841'` to see where the old icon(s) come from.
Replace the codepoint with one of the new ones (ex `f0343`) and check that they are listed.
?

**Comment by Finii** [comment]
I, for example, have also Delugia installed that has not yet been updated to Nerd Fonts 3

```
$ fc-list ':charset=f841'
/home/fini/.local/share/fonts/DelugiaComplete-Bold.ttf: Delugia:style=Bold
/home/fini/.local/share/fonts/DelugiaComplete-Italic.ttf: Delugia:style=Italic
/home/fini/.local/share/fonts/DelugiaComplete.ttf: Delugia:style=Regular
/home/fini/.local/share/fonts/DelugiaComplete-BoldItalic.ttf: Delugia:style=Bold Italic

$ fc-list ':charset=f0343' | head
/home/fini/.local/share/fonts/VictorMonoNerdFont-Regular.ttf: VictorMono Nerd Font,VictorMono NF:style=Regular
/home/fini/.local/share/fonts/VictorMonoNerdFontMono-SemiBoldItalic.ttf: VictorMono Nerd Font Mono,VictorMono NFM SemiBold:style=SemiBold Italic,Italic
/home/fini/.local/share/fonts/DejaVuSansMNerdFont-Regular.ttf: DejaVuSansM Nerd Font:style=Regular
/home/fini/.local/share/fonts/VictorMonoNerdFontMono-ExtraLight.ttf: VictorMono Nerd Font Mono,VictorMono NFM ExtraLight:style=ExtraLight,Regular
/home/fini/.local/share/fonts/HasklugNerdFont-Regular.otf: Hasklug Nerd Font:style=Regular
/home/fini/.local/share/fonts/FiraCodeNerdFont-Regular.ttf: FiraCode Nerd Font:style=Regular
/home/fini/.local/share/fonts/CaskaydiaCoveNerdFont-Regular.ttf: CaskaydiaCove Nerd Font,CaskaydiaCove NF:style=Regular
/home/fini/.local/share/fonts/VictorMonoNerdFontMono-LightOblique.ttf: VictorMono Nerd Font Mono,VictorMono NFM Light Obl:style=Light Oblique,Italic
/home/fini/.local/share/fonts/VictorMonoNerdFontMono-BoldOblique.ttf: VictorMono Nerd Font Mono,VictorMono NFM Obl:style=Bold Oblique,Bold Italic
/home/fini/.local/share/fonts/RobotoMonoNerdFont-Regular.ttf: RobotoMono Nerd Font:style=Regular

$ fc-list ':charset=f0343' | wc -l
86

```

**Comment by FlyingPotato-131** [comment]
`fc-list ':charset=f841'` returns nothing (and so do any of the old codepoints), the new ones return what they seem to be supposed to do (it's basically saying that everything is fine)
this explains why fontmatrix shows that everything is correct, but the lack of glyphs everywhere else makes no sense in this case

**Comment by Finii** [comment]
I usually use `writer` (LibreOffice) to check if the fonts work 'generally'.
But given that fontconfig returns the expected results I'm at a loss what could be the issue on your system. :thinking:

**Comment by Finii** [comment]
The issue must be 'you have two independent fontconfigs in parallel' ;-D

I really have no clue, Arch should be pretty standard. If you would be on this Windows-Linux-Subsystem thing, there I do not know at all how the fonts work, but 'vanilla Arch'. :thinking:

**Comment by Finii** [comment]
Closed due to inactivity.
