### ISSUE TITLE
Implement and enforce standards for Python (Pyflakes)

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#121]
#### Implement and enforce standards for Python (Pyflakes)

Particularly interested in enforcing at least some sort of subset of PEP-8 standard for Python.

**Comment by waseem18** [comment]
Hi @ryanoasis 

I'm interested in taking this up.

However I noticed only two Python scripts `bin/scripts/fpfix.py` and `font-patcher`.
I'll put a PR for this as soon as I can. Let me know if you got any suggestions.

Thanks

**Comment by ryanoasis** [comment]
@waseem18 Thanks! That'd be great! :smile: 

Yes I believe that is correct there are only 2 python scripts currently.

I will remove the up for grabs label for now, this is all yours for now!

I don't have any particular suggestions but if I do I'll let you know. Also if you have any doubts feel free to ping me.

**Comment by ryanoasis** [comment]
@waseem18 still have interest in taking this up or can I open it back up?

Thanks :smile:

**Comment by waseem18** [comment]
Hi @ryanoasis ,

Sorry I couldn't get to work on this. I'm immersed in my work commitments so I'm afraid I might not be able to take this up anytime soon.

**Comment by ryanoasis** [comment]
@waseem18 Thanks for responding. I completely understand :smile: . I only asked now because I might soon take this on myself or open it back up.

That said we would love to have any contribution no matter how big or small from you in the future if you find yourself with any extra time. :smiley:

**Comment by EdgeKing810** [comment]
Can I take this up sir @ryanoasis ?

**Comment by waseem18** [comment]
This still seems to be open @EdgeKing810

**Comment by EdgeKing810** [comment]
You mind if I take it @waseem18 ?
I'll try to enfore PEP8 as much as I can...

**Comment by Finii** [comment]
Thanks for all the input.

I will set the future tag and close to clean up Issues. The closed future tags will get their own topic.
