### ISSUE TITLE
dwm window manager uses dropped codepoints

### ISSUE THREAD

**Issue by nitrogenxx** [ryanoasis/nerd-fonts#1212]
im using dwm window manger in archlinux 
today i updated this package (ttf-iosevka-nerd) now all the icons are missing in my status bar
please fix the issue

**Comment by Finii** [comment]
With Nerd Font Release `v2.3.x` some codepoints needed to be obsoleted, and they are finally removed with `v3.0.0`

I do not know dwm, but most probably they or you need to adapt the settings to utilise the new codepoints.

Please refer to Issue #1190:
* Explanation of the reasons [link to comment](https://github.com/ryanoasis/nerd-fonts/issues/1190#issuecomment-1530999114)
* Some possibly helpful links [link to comment](https://github.com/ryanoasis/nerd-fonts/issues/1190#issuecomment-1531147557)

Sorry for the pain, but dropping the codepoint was crucially needed (see reasons link, or [release overview](https://github.com/ryanoasis/nerd-fonts/releases) or [release notes](https://www.nerdfonts.com/releases) resp. [changelog](https://github.com/ryanoasis/nerd-fonts/blob/master/changelog.md)[
](https://github.com/ryanoasis/nerd-fonts/releases))

You might want to report the issue upstream, i.e. at dwm.

Thank you!
