### ISSUE TITLE
f482 went from symlink directory to bookmark slash?

### ISSUE THREAD

**Issue by duhdugg** [ryanoasis/nerd-fonts#1213]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

`f482` was previously showing a symlink directory icon, and now shows a bookmark slash icon

Expected behavior:

symlink icon

Example symbols:



#### 🔧 Your Setup

- ttf-firacode-nerd package from Arch repo

#### ★ Screenshots (Optional)

Before Upgrade (`ttf-firacode-nerd-2.3.3-3`)

![2023-05-07-162650_61x31_scrot](https://user-images.githubusercontent.com/1406429/236702079-45a2e657-ac36-45aa-87fc-c166ee3c78a9.png)

After Upgrade (`ttf-firacode-nerd-3.0.0-2`)

![2023-05-07-162710_65x28_scrot](https://user-images.githubusercontent.com/1406429/236702090-67807eef-7df4-4c8a-b7ac-3f0ae21781cc.png)

Using the `lsd` command to generate the above screenshots, which shows this codepoint for symbolic link directories.

## Related Issue

Submitted this issue to the octicons project as well: https://github.com/primer/octicons/issues/945

_Edit Fini: Changed codepoint number_

**Comment by Finii** [comment]
Sorry to hear that you lost a beloved icon with the update.

As you already found out the change is due to the Octicons update.

They dropped a lot icons; and the remaining folder icons changed to a more modern look.

That you see now the bookmark-slashed and not a `.notdef` (i.e. questionmark box) is because we reused the freed codepoints for newly added icons. The Octicons do not have native codepoints.

Unfortunately link-folder icons are not very widespread, so the only one left probably is this:

<img width="163" alt="Screenshot 2023-05-08 at 06 42 48" src="https://user-images.githubusercontent.com/16012374/236735605-c39993d8-1f02-42f3-8c8d-ffcf0a2c52f6.png">

But the 'folder' part looks quite different of course. Probably using that would mean to switch all folder related icons to Codicons.

Related is the general modernisation look-change of the folders, mentioned here https://github.com/ryanoasis/nerd-fonts/issues/1190#issuecomment-1532632029, with its related issue #1207.

**Comment by Finii** [comment]
Probably an Issue needs to be raised at `lsd`.

In principle we could of course keep the old style Octicons folder icons, but that would have to be with other codepoints, probably.

🤔 But that of course leads to maintenance hell... And if we do not follow updates of the sources, then we could stop updating at all. Hard.

**Comment by Finii** [comment]
I fear Octicons will not answer, and if they answer they will not change anything.

Can you create an Issue at `lsd` so that we can discuss together with them what to do?

**Comment by Finii** [comment]
If we come to a solution within the next days it could go into `v3.0.1`...

**Comment by Finii** [comment]
Maybe a good idea would be to add a symlink folder to the `nf-cutom-` folders, there are already some. But to have a unified look `lsd` would have to switch to that icons completely?

**Comment by Finii** [comment]
Or I can "hand draw" a combination of the updated Octicons (normal) folder and a link-arrow.

**Comment by Finii** [comment]
https://github.com/lsd-rs/lsd/blob/2fe3fcdd3564836962eab8ba6b1444996fe24e1e/src/theme/icon.rs#L85

Did any of the other also change meaning, we need a list of dropped/changed codepoints

**Comment by Finii** [comment]
| Icon | in source font | codepoint in Nerd Font |
|---|---|---|
| Missing octoface | F008 | F406 |
| Missing keyboard | F00D | F40B |
| Missing gist | F00E | F40C |
| Missing file-text | F011 | F40E |
| Missing file-pdf | F014 | F411 |
| Missing jersey | F019 | F416 |
| Missing radio-tower | F030 | F424 |
| Missing repo-force-push | F04A | F43E |
| Missing mail-reply | F051 | F443 |
| Missing arrow-small-right | F071 | F45C |
| Missing gist-secret | F08C | F46C |
| Missing no-newline | F09C | F476 |
| Missing arrow-small-up | F09F | F478 |
| Missing arrow-small-down | F0A0 | F479 |
| Missing arrow-small-left | F0A1 | F47A |
| Missing file-symlink-directory | F0B1 | F482 |
| Missing circuit-board | F0D6 | F493 |
| Missing watch | F0E0 | F49B |
| Missing text-size | F0E3 | F49E |
| Missing ellipses | F101 | F4A4 |
| Missing plus-small | F104 | F4A7 |

Checking if they use more...

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/236796953-a9e7a7b1-0a0a-4339-a8a0-7b782e5fdab0.png)

**Comment by siduck** [comment]
hi @Finii could you add this icon?  I can pay for it if you want

![image](https://user-images.githubusercontent.com/59060246/236962349-0714a7d2-8279-4fd6-9de2-e60455d48a2e.png)

**Comment by Finii** [comment]
> hi @Finii could you add this icon? **I can pay for it** if you want

I'm not doing this for money. I help for free if I can and feel that this project is respected.

**Comment by duhdugg** [comment]
I saw the latest update in my OS this weekend. It looks great. Thanks.

**Comment by Finii** [comment]
> I saw the latest update in my OS this weekend. It looks great. Thanks.

Thank you :heart:
