### ISSUE TITLE
Ubuntu Nerd Font having issues with ligatures displaying fi and fl wrong again

### ISSUE THREAD

**Issue by Quantenzitrone** [ryanoasis/nerd-fonts#1221]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
  - i know this has been a recurring issue (#509, etc), but there is no issue for version 3.0.0 yet and the other issues are locked
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
fi and fl are displayed as `nf-fa-music` and `nf-fa-search`

Expected behavior:
normal displaying of fi and fl

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Ubuntu Nerd Font
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Nixpkgs
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - terminal unaffected, as i use UbuntuMono there
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - NixOS GNU/Linux, Version 23.05.20230506.897876e (Stoat)

#### ★ Screenshots (Optional)

![image](https://github.com/ryanoasis/nerd-fonts/assets/74491719/4f7e7cc7-0909-4933-8b42-5297cbb647c6)
![image](https://github.com/ryanoasis/nerd-fonts/assets/74491719/e4e6972f-3207-4665-ae6a-6a7ee7e9e682)

Can anyone reproduce this, is it maybe only NixOS?

**Comment by Finii** [comment]
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/5bcef804-69bb-41b0-878f-d07057d89980)

**Comment by Finii** [comment]
Thanks again, fixed in 3.0.1 (will be)

**Comment by thyeun** [comment]
@Finii sorry the search `````` become ```fl``` (this one wrong) after update to latest version 3.0.1, ```fl``` is ```fl``` (this one correct)

**Comment by Finii** [comment]
In some fonts we could not solve this, where the ligature occupies the symbol codepoint directly.
But in most it should be solved, and if I read thyeun correctly Ubuntu is now fixed?
Some fonts map `f` `i` to a `fi` ligature that is only one 'cell' wide, which is of course unwanted, and we remove that ligature rules (I hope).

**Comment by thyeun** [comment]
@Finii See the below explanation. 

Version 3.0.0
`````` (f002) = `````` (f002) = correct
```fl``` = `````` = wrong

Verison 3.0.1
`````` (f002) = ```fl``` = wrong
```fl``` = ```fl``` = correct

**Comment by Finii** [comment]
Ubuntu is set up that `f`followed by `i`map to the ligature `f_i` (codepoint `FB01`) and that references the glyph `fi` (codepoint `F001`).

I do not know why the did this. Standard codepoint is `FB01`.

The reference `FB01` is the same as `F001` can only be removed by manual editing the font, we have no automatism for that.

What changed between 3.0.0 and 3.0.1 is that the patcher does not touch any "essential" glyphs, and also follows all references through the font (which can be many).

Patching in at `F001` is 'forbidden' at the moment, because that will (through the referense) touch a glyph that must not be touched (a latin letter (combination/ligature)).

I will think about that and how we can improve the situation.

**Comment by thyeun** [comment]
@Finii yup, that the issue i cant understand why they did that way. will it because this is a ```special``` to differentiate ```ubuntu mono``` and ```ubuntu```or differentiate for others font?

**Comment by Finii** [comment]
Maybe they did it to have a simpler design for the `ffi` ligature, but then, this does not make much sense.

Removing the stuff is rather hard programmatically, you have to analyze multiple tables and references and see how it all fits together; I can do this manually but I am not good enough to program something that does it.

**Comment by Finii** [comment]
> I will think about that and how we can improve the situation.

There are quite some fonts with this ...

```
DEBUG: Arimo-Bold.ttf Found essential Glyph at F001. Skipping...
DEBUG: Arimo-Bold.ttf Found essential Glyph at F002. Skipping...
DEBUG: Arimo-Regular.ttf Found essential Glyph at F001. Skipping...
DEBUG: Arimo-Regular.ttf Found essential Glyph at F002. Skipping...
DEBUG: FantasqueSansMono-BoldItalic.ttf Found essential Glyph at E008. Skipping...
DEBUG: FantasqueSansMono-BoldItalic.ttf Found essential Glyph at E009. Skipping...
DEBUG: FantasqueSansMono-Bold.ttf Found essential Glyph at E005. Skipping...
DEBUG: FantasqueSansMono-Bold.ttf Found essential Glyph at E006. Skipping...
DEBUG: FantasqueSansMono-Italic.ttf Found essential Glyph at E008. Skipping...    
DEBUG: FantasqueSansMono-Italic.ttf Found essential Glyph at E009. Skipping...    
DEBUG: FantasqueSansMono-Regular.ttf Found essential Glyph at E005. Skipping...   
DEBUG: FantasqueSansMono-Regular.ttf Found essential Glyph at E006. Skipping...   
DEBUG: InconsolataGo-Bold.ttf Found essential Glyph at F40A. Skipping...
DEBUG: InconsolataGo-Regular.ttf Found essential Glyph at F40A. Skipping...
DEBUG: LiberationSerif-BoldItalic.ttf Found essential Glyph at F004. Skipping...
DEBUG: LiberationSerif-Bold.ttf Found essential Glyph at F004. Skipping...  
DEBUG: LiberationSerif-Italic.ttf Found essential Glyph at F004. Skipping...
DEBUG: LiberationSerif-Regular.ttf Found essential Glyph at F004. Skipping...
DEBUG: Tinos-BoldItalic.ttf Found essential Glyph at F004. Skipping...
DEBUG: Tinos-Bold.ttf Found essential Glyph at F004. Skipping...
DEBUG: Tinos-Italic.ttf Found essential Glyph at F004. Skipping...
DEBUG: Tinos-Regular.ttf Found essential Glyph at F004. Skipping...
DEBUG: Ubuntu-BI.ttf Found essential Glyph at F001. Skipping...
DEBUG: Ubuntu-BI.ttf Found essential Glyph at F002. Skipping...
DEBUG: Ubuntu-B.ttf Found essential Glyph at F001. Skipping...
DEBUG: Ubuntu-B.ttf Found essential Glyph at F002. Skipping...
DEBUG: Ubuntu-C_modified.ttf Found essential Glyph at F001. Skipping...
DEBUG: Ubuntu-C_modified.ttf Found essential Glyph at F002. Skipping...
DEBUG: Ubuntu-LI.ttf Found essential Glyph at F001. Skipping...
DEBUG: Ubuntu-LI.ttf Found essential Glyph at F002. Skipping...
DEBUG: Ubuntu-MI.ttf Found essential Glyph at F001. Skipping...
DEBUG: Ubuntu-MI.ttf Found essential Glyph at F002. Skipping...
DEBUG: UbuntuMono-BI.ttf Found essential Glyph at F001. Skipping...
DEBUG: UbuntuMono-BI.ttf Found essential Glyph at F002. Skipping...
DEBUG: UbuntuMono-B.ttf Found essential Glyph at F001. Skipping...
DEBUG: UbuntuMono-B.ttf Found essential Glyph at F002. Skipping...
DEBUG: UbuntuMono-RI.ttf Found essential Glyph at F001. Skipping...
DEBUG: UbuntuMono-RI.ttf Found essential Glyph at F002. Skipping...
DEBUG: Ubuntu-M.ttf Found essential Glyph at F001. Skipping...
DEBUG: Ubuntu-M.ttf Found essential Glyph at F002. Skipping...
DEBUG: Ubuntu-RI.ttf Found essential Glyph at F001. Skipping...
DEBUG: Ubuntu-RI.ttf Found essential Glyph at F002. Skipping...
DEBUG: Ubuntu-R.ttf Found essential Glyph at F001. Skipping...
DEBUG: Ubuntu-R.ttf Found essential Glyph at F002. Skipping...
```

**Comment by thyeun** [comment]
@Finii one question, based from nerd cheatsheet, what is the different between codepoint ``````(f002) and ``````(e68f).

For me both look identical, but the codepoint is different and the codepoint (e68f) is appear correctly in ```Ubuntu nerd font``` for version 3.0.1
