### ISSUE TITLE
Enlarged glphys in FiraCode Mono

### ISSUE THREAD

**Issue by thpani** [ryanoasis/nerd-fonts#1229]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
After the v3.0.0 release, the `Mono` variant of `FiraCode` contains enlarged glyphs at codepoints U+276C to U+276F, compared to non-`Mono` variant and parent FiraCode 6.2.

Expected behavior:
Equal glyphs in all 3 fonts, as before v3.0.0

Example symbols:
U+276C to U+276F: ❬❭❮❯

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - `FiraCodeNerdFontMono-Regular.ttf`
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Homebrew `font-fira-code-nerd-font: 3.0.0`
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - `kitty`, macOS Terminal, also occurs in macOS TextEdit
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - macOS Ventura 13.3.1

#### ★ Screenshots (Optional)

<img width="374" alt="Screenshot 2023-05-11 at 11 29 00" src="https://github.com/ryanoasis/nerd-fonts/assets/82047/75db1555-0d7d-448d-ba70-682ecbd0a01e">

**Comment by Finii** [comment]
Fira Code 6.2 does **not** contain `276C` - `276F` (but just `2770` and `2771`):

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/65e24cc5-0845-4641-b1cb-34d3b52372c9)

The glyphs you see there are inplace replacements via fontconfig.

They are patched in with these settings

```c
{
   'Enabled': True,                                
   'Name': "Heavy Angle Brackets",         
   'Filename': "extraglyphs.sfd",                                     
   'Exact': True,       
   'SymStart': 0x276C,      
   'SymEnd': 0x2771,      
   'SrcStart': None,        
   'ScaleRules': None,                  
   'Attributes': SYM_ATTR_HEAVYBRACKETS       
}

SYM_ATTR_HEAVYBRACKETS = {
    'default': {'align': 'c', 'valign': 'c', 'stretch': 'pa', 'params': {'careful': True}}
}
```

probably we should add some padding? :thinking:
Otoh, these glyphs are different to ordinary glyphs, they should somehow always be scaled also in `Nerd Font` (i.e. just setting the padding will not help there).

Thanks for reporting! Need to think a bit about the solution.

**Comment by Finii** [comment]
You see this only with `v3.0.0` because previously Nerd Font did not patch in these glyphs, so you had fontfallback to the same font as with your original `Fira Code`. But there are a lot (?) people out there who do not have any font with the heavy brackets installed, that's the reason they are now added.

You can find out who supplies them with
```
$ fc-list ':charset=276c'
```

On my system it is mainly DejaVu:

```
$ fc-list :charset=276c -f '%{file}\n' | grep -v Nerd | grep '^/usr'
/usr/share/fonts/truetype/dejavu/DejaVuSans-BoldOblique.ttf
/usr/share/fonts/type1/urw-base35/D050000L.t1
/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Bold.ttf
/usr/share/fonts/truetype/freefont/FreeSerif.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-BoldOblique.ttf
/usr/share/fonts/X11/Type1/D050000L.pfb
/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Oblique.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf
```

**Comment by Finii** [comment]
They are even scaled differently, because one is width limited and the other height limited :unamused: 

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ea7de050-14a1-4a0c-b913-e757e371933e)

Creating some PR.

**Comment by Finii** [comment]
Hmm, notes for PR preparation:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/345ea6aa-2b30-4182-9eef-66d4d3a1cf5a)


Height of The Three Stooges is

1495, 1495, 1682, cell height in Hack 2408.

That calculates to a padding of 15% top and bottom. Sounds reasonable.

Maybe putting in old-style ScaleGlyph group to keep the scaling identical but individually centered. The un-centeredness really bothers me... What the heck Hack?!
