### ISSUE TITLE
New glyphs: GlimmerJS and GlimmerTS

### ISSUE THREAD

**Issue by NullVoxPopuli** [ryanoasis/nerd-fonts#1237]
Hello, I'd like to request that we add glyphs for the gjs and gts file extensions.
I'm willing to do the work, but wanted to open an issue, as recommended here: https://github.com/ryanoasis/nerd-fonts/discussions/1095

**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**

I know that nerd-fonts aggregates from a few glyph sets: https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points
so I don't know that it's exactly nerd-fonts' responsibility to add new glyphs -- but I'd like to know where to get started -- should I ask Devicons to add the new glyphs for the single-page-app framework file extensions?

**Additional context**

Current view of my editor, using nvim-tree: 
![image](https://github.com/ryanoasis/nerd-fonts/assets/199018/c2d92f3c-2b24-4c36-8616-669111247e28)

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
