### ISSUE TITLE
Chromebook terminal icons missing

### ISSUE THREAD

**Issue by Qwer-TeX** [ryanoasis/nerd-fonts#1239]
#### 🗹 Requirements

- [🗹] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [🗹] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [🗹] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
`**I have installed the CousineNerdFont, but instead of a icon there is just a box.**`

Expected behavior:
`**All of the icons show a small box instead of the icon which has to show.**`

Example symbols:

`    --> I copied the symbols from the nerdfont website and it still shows as a box :(`

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
- 
   **`CousineNerdFont*.ttf`**

- _Where did you get the file from (download link, self patched, source downloaded from link...)_
- 
   **- `Patched --> https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/Cousine.zip` **

- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
- 
**`I am using the chromebook terminal`**

- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
- 
**`I am using CLI Debian 11 inside chromeos 114.0.5735.12` **

#### ★ Screenshots (Optional)

![Screenshot 2023-05-13 3 15 56 PM](https://github.com/ryanoasis/nerd-fonts/assets/128016252/0dd035d1-6f00-48c8-a585-b9f82b01c1af)

**Comment by Finii** [comment]
How did you install the font?
How did you activate that font in your terminal (which you did not specify)?
Can you see/use it with LibreOffice Writer for example?

**Comment by Qwer-TeX** [comment]
> How did you install the font? How did you activate that font in your terminal (which you did not specify)? Can you see/use it with LibreOffice Writer for example?


I pasted the font in ~/.local/share/fonts folder and I tested if the font shows up on my text editor and it does except in the chromebook terminal.

But when I use another terminal like xfce4-terminal, the font shows.

**Comment by Finii** [comment]
I guess that is chrombook terminal's problem. I see no way how we can fix it on our end. Sorry.

**Comment by vdegenne** [comment]
Sadly it seems that ChromeOS terminal doesn't support icon fonts *yet(?)*. Feel free to send feedback from the ChromeOS feedback window, if enough people complain about  that, they might fix the issue in future updates
