### ISSUE TITLE
FiraCode: Some symbols not shown in the current version

### ISSUE THREAD

**Issue by diogo-rossi** [ryanoasis/nerd-fonts#1241]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Missing some icons on current version of FiraCode font (**current version**)

![image](https://github.com/ryanoasis/nerd-fonts/assets/57204023/30bd5f61-9512-41c3-8bb2-abc6cf506dac)

Expected behavior:

Show all icons like below (version downloaded from commit dfd186c2a43fa45409ba2a3d5d5ab831fba6fc01)

![image](https://github.com/ryanoasis/nerd-fonts/assets/57204023/11d3b49b-76f6-4310-9b44-adabad15a43d)

Example symbols:

**Show above**

#### 🔧 Your Setup

- _Which font are you using ?_
   - Before the problem (some previous version):
   `Fira Code Bold Nerd Font Complete Mono Windows Compatible.ttf`
   - After the problem (current version):
   `FiraCodeNerdFontMono-Bold.ttf`
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Before the problem:
   [`Fira Code Bold Nerd Font Complete Mono Windows Compatible.ttf`](https://github.com/ryanoasis/nerd-fonts/tree/dfd186c2a43fa45409ba2a3d5d5ab831fba6fc01/patched-fonts/FiraCode/Bold/complete)
   - After the problem:
   [`FiraCodeNerdFontMono-Bold.ttf`](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode/Bold)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   -  Windows Terminal
   - Gnome
   - konsole
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows 10
   - CentOS 7

#### ★ Screenshots (Optional)

**Show above**

Additional information:
I saw the folder does not have "Windows compatible" fonts anymore. Why is that?

Summary:
In commit dfd186c2a43fa45409ba2a3d5d5ab831fba6fc01 the font was OK. Now, it is not.

**Comment by Diogo-Rossi** [comment]
@Finii Thank you for clarify. Sorry for I didn't make a deeper search.
