### ISSUE TITLE
nf-hack behaves differently than the original hack-font

### ISSUE THREAD

**Issue by zeus86** [ryanoasis/nerd-fonts#1245]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
On `Arch` (x86_64, Kernel 6.3.2) with `Bash` on `Konsole` (23.04.1) and `oh-my-posh` the hack-font provided by the arch-repos (`extra/ttf-hack 3.003-3`) behaves differently on rendering e.g. powerline-symbols. The original hack-font already contains some powerline-symbols (which do render correctly in `konsole`), but the nf-hack font slightly squishes the symbols together (depending on font-size. however, the usable range is broken anyways, i usually use fonsize 10.0). On the example of the `right|left-hard-devider` icons, it looks like, as if the triangle is misplaced by 1px or so, see screenshots for details. While it doesn't look super-annoying, the original hack-font renders differently. So far i tested some more fonts (but without direct comparison to their original counterpart), namely dejavu-sans, 3270, anonymice-pro, meslo and sourcecode pro, but all of them seem to render slightly off, so i thought this was a konsole-issue, however, og-hack renders fine... (tested basically all other konsole-options which might have an influence but with no result)

Expected behavior:
Both fonts should behave identical

Example symbols:
- nf-pl-left_hard_divider
- nf-pl-right_hard_divider
- ...and many more (at least basically all useable dividers)
#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - `HackNerdFont-Regular.ttf` (but applies to mono-variants as well as other nf-fonts as well)
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   -  https://github.com/ryanoasis/nerd-fonts/releases/latest/download/hack.zip (by included downloader within `oh-my-posh`)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - konsole 23.04.1
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Arch Linux

#### ★ Screenshots (Optional)
fonsize=10:
original hack-font:  
![og-hack](https://github.com/ryanoasis/nerd-fonts/assets/11415964/ff1668b9-f77d-44c5-8fae-7a4b2ef54abe)  

nf-hack:  
![nf-hack](https://github.com/ryanoasis/nerd-fonts/assets/11415964/d1e2d683-8a6c-4b5f-ac68-8f5db65aea5b)  
another example with more colors:  
![nf-hack-root](https://github.com/ryanoasis/nerd-fonts/assets/11415964/19bb8438-1555-4a16-b580-ee50c30e4e6d)

**Comment by Finii** [comment]
Sorry to see your problem.

All pre-existing Powerline glyphs are (have to be) dropped when a font is Nerd Fonts patched. But I will check why there are differences.

By displaced 1 px you mean sidewards (1 px to the right)?
What I also maybe see is that they seem to be 1 px less tall and 1 px further up (meaning the whole symbol is 2 px less tall, but centered).

What you can try is to switch to monospaced antialiasing, that should remove the faint greenish line after "zeus".
All the differences look like an antialiasing/rescaling problem.

It is indeed possible to generate a font that does not show the faint lines (see #780), but that raises other problems in other terminals, so what we do not is a compromise. But I will check original Hack, how they solve it.

But please do write if this is your problem or something else?

**Comment by zeus86** [comment]
@Finii I think you are right, but the faint line is there regardless if i use the monospaced font or not, just some symbols (like the arch logo) are smaller in the monospace variant, the faint aliased line persists, or better "is unchanged". 

But yes, this is my problem :)

**Comment by zeus86** [comment]
interesting note on top of that: if i increase the vertical spacing between the lines in konsole, the effects gets even more pronounced (but i guess this comes from how `oh-my-posh` does the rendering of the background-colors).

**Comment by Finii** [comment]
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/04b50cfe-f72d-4bb9-b948-63c9ca843a55)
_Left to right: Hack, Nerd Font, Cascadia Code_

We have the least amount of overlap.
This is related to
* #780

Maybe we should revive that. Also our glyph has no "overlap patch" but is a simple triangle which becomes more and more problematic when overlap is increased.

Maybe we want to have this in 3.1.0, I would not change behavior again already in a bugfix release.

**Comment by Finii** [comment]
Somehow the cell height is higher than intended here:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/4ccebfaa-33ac-4865-bae0-ea77072ae7f0)

Hmm, `konsole` ... where do I get that from ;-) Sigh.

**Comment by zeus86** [comment]
> Hmm, konsole ... where do I get that from ;-) Sigh.
It is the default-shell of KDE/plasma :)

**Comment by Finii** [comment]
> ...and many more (at least basically all useable dividers)

Well, I guess the open triangle thing (also in my image above, the right one) has NO problem.
Maybe you can assemble a list of the really affected glyphs?
I guess all Powerline glyphs that end with a full surface either right or left.

**Comment by Finii** [comment]
Aaron really added that overlap surface to all relevant glyphs

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/d8e29046-0aa8-4fe5-b44c-1065429cf5e0)

That is far better than the overlap. I think we should mimic that for 3.1

**Comment by zeus86** [comment]
> Aaron really added that overlap surface to all relevant glyphs

lol, awesome finding :)

**Comment by Finii** [comment]
But he did not even clean up the insane amount of points in waveform or flames, just copied them unchanged over from here (and adding the side surface) :grimacing: 

Note to self: Clean that stuff up, opening the glyphs flame and waveform takes ages.

**Comment by memchr** [comment]
> Maybe we should revive that. Also our glyph has no "overlap patch" but is a simple triangle which becomes more and more problematic when overlap is increased.

I think it's a good idea to do that because this problem also presents in [SymbolsNerdFont-Regular.ttf](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/NerdFontsSymbolsOnly.tar.xz).This means that any aliases in the [10-nerd-font-symbols.conf](https://github.com/ryanoasis/nerd-fonts/blob/master/10-nerd-font-symbols.conf) will be affected. 

default:
![image](https://github.com/ryanoasis/nerd-fonts/assets/118117622/a3bd2a7c-7a79-40d8-9e91-3a2c9daed169)

Replace `U+E0B2` of `SymbolsNerdFont-Regular.ttf` with glyphs copied from the original hack font:
![image](https://github.com/ryanoasis/nerd-fonts/assets/118117622/4dce3f45-1bf8-4f87-babf-589610837eed)

**Comment by Finii** [comment]
WTF, it has an outline?!!

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/69f3de39-cb82-418d-ac15-e9cf8ae82097)

Editing and simplifying.

**Comment by Finii** [comment]
Okay, I just changed the full left and right triangles. Lets see if this is good; then we can expand to the other powerline glyphs.
Please report back after v3.1.0 (which will come out any day now).

**Comment by zeus86** [comment]
Awesome! Will test it right away, as soon the release is out!

However, shouldn't this issue be kept open (because it affects most likely many symbols, that aren't patched yet?)?

**Comment by Finii** [comment]
And we need to check that it works for the one icon at all ;-)

**Comment by zeus86** [comment]
just to report back, because i didn*t yet explicitly: i recently updated my nerd-fonts via the oh-my-posh font-installer (`oh-my-posh font install), and I'm happy tp report, that the nf-hack-font now looks as it should. crisp and clear on all zoom-levels in `konsole` under KDE on Arch. 

Thanks for your effort.
