### ISSUE TITLE
The Symbols Nerd Font is missing the Propo variant

### ISSUE THREAD

**Issue by xSmokes32** [ryanoasis/nerd-fonts#1247]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Downloading any nerd font after v3.0.0 should have 3 variants Nerd Font, Nerd Font Mono, Nerd Font Propo, but the Symbols Nerd Font is missing the Propo variant.

Expected behavior:

It should have it be like the other fonts.

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - SymbolsNerdFont-Regular.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/NerdFontsSymbolsOnly.zip
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - I noticed this when I was changing the font for polybar...
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Debian GNU/Linux

**Comment by Finii** [comment]
Well, in fact it is a bit more obscure.
What is missing is the `Nerd Font`.

For historic reasons the Symbols Only font has these names
* Symbols Only Nerd Font Mono is a `Nerd Font Mono`
* Symbols Only Nerd Font is a `Nerd Font Propo`.

To have a `Nerd Font` does not make much sense for the Symbols only font. That variant keeps the advance width of the unpatched font but get the symbols in the full size with “overhang” into the next ‘cell’. But what is that width? There is no unpatched font (technically there is, but it is empty and does not have any glyph and thus no advance width).

And by the way, not all fonts have all three variants. If the sourcefont is not monospaced there will be no `Nerd Font Mono`. That variant guarantees that all glyphs have the same width which will break the font (it becomes unusable). Examples are Agave or Ubuntu (nonMono).

**Comment by xSmokes32** [comment]
That's make sense, thanks for your reply and make things clear
