### ISSUE TITLE
Symbols Only: Provide ExtraBold variation too

### ISSUE THREAD

**Issue by N-R-K** [ryanoasis/nerd-fonts#1248]
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**

The icons in nerd-font patched fonts are too small for my statusbar (in [dwm](dwm.suckless.org/)), and thus I use the following config:

```c
static const char *fonts[]          = {
	"Font Awesome 5 Free Solid:size=14", // prioritize Awesome at size 14
	// fallback fonts at lower sizes
	// ...
};
```

I've been thinking of switching over to nerd-font symbol only, but unfortunately the default is too thin for my liking:

![new](https://github.com/ryanoasis/nerd-fonts/assets/79544946/69fc551d-1c36-4116-8627-6e4b89f455a5)

And this is `Font Awesome 5 Solid`:

![old](https://github.com/ryanoasis/nerd-fonts/assets/79544946/2b1ef9e7-e997-4117-a286-2dfab142db57)

**Describe the solution you'd like**

It'd be great if there was a ExtraBold variation of symbol only font similar to font-awesome-solid.

**Describe alternatives you've considered**
(None)

**Additional context**
(None)

**Comment by Finii** [comment]
Thanks for the suggestion!

Font awesome create the bold versions manually iirc.
There is no nice way to create a bold versions of a symbol.

In principle we could add the FA solid variant as new set. But that would of course not really solve your problem because you wound need to adjust all codepoints in the applications.

I would say is not feasible, sorry.

**Comment by Finii** [comment]
Adding to parallel universe to not forget this.

**Comment by N-R-K** [comment]
> I would say is not feasible, sorry.

Unfortunate, but understandable. I'll continue using the font-awesome 5 solid version then (annoyingly, font-awesome 6 seems to have added latin glyphs, so I cannot use it as a symbol-only font thus I'm stuck with 5).

In any case, thanks for considering.

**Comment by Finii** [comment]
It's very easy to throw out any glyphs you do not want from 6, here is a script somewhere, lets see

\*rumaging through files\*
\*sound of bits shuffled right to left\*

Ah, https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/generate-extraglyphs.py

I guess the code is quite readable and can be adapted to your usecase.
Just open the original font, `select` a `range` from `0001` to `DFFF` or so, and `clear` (i.e. remove) that glyphs, then `generate` a new font, done.

**Comment by Finii** [comment]
This is even more simple, but not Python ;-D

https://github.com/adam7/delugia-code/blob/master/extract-extra-glyphs

It runs directly in fontforge.

**Comment by N-R-K** [comment]
Thanks a lot! The python version seems like it'd be easier for me to modify. I'll have it bookmarked for the next time I'm fiddling around with my system config.

**Comment by Finii** [comment]
> There is no nice way to create a bold versions of a symbol.

One way is something like this:
https://github.com/ryanoasis/nerd-fonts/blob/master/src/unpatched-fonts/ComicShannsMono/make_bold

But the results are so bad :-(
