### ISSUE TITLE
Some icons missing

### ISSUE THREAD

**Issue by Akshzz-16** [ryanoasis/nerd-fonts#1257]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Tried many fonts and even downloaded the patch fonts from GitHub repo yet the icons for many directories were not visible.

Expected behavior:

The icons use to work before but now when I installed it again it wasn't working the way I expected.

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_ Hack nerd font mono
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   -  nerd font official website
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - 
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   -  using windows 11, powershell, Windows terminal.

#### ★ Screenshots (Optional)

<img width="567" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/82015294/68814735-f167-4fb2-85cb-af2c200879cc">

**Comment by Akshzz-16** [comment]
.

**Comment by Finii** [comment]
Sorry to see your problems.

Please copy and paste text with the missing glyphs (as text) into a comment here; we can then determine the codepoints and check what's going wrong.

My first thought is that you use `Nerd Font v2` codepoints still and did not update your - whatever it is that created that directory listing - to `v3`.

If the codepoints are in the 4 digit range, but removed with `v3`, see
* #1190

If the codepoints are all in the 5 digit range, maybe your `Windows terminal` has a problem, see
* #1246

**Comment by Ashvith10** [comment]
@Finii slightly out of topic, but would you consider adding a notice section at the start of the README.md, reminding about v3.0.0? That would help a lot of people who are clueless about the breaking changes.

**Comment by Finii** [comment]
@Ashvith10 That is an excellent idea!

Maybe you have an idea what to write and/or how?

> assuming that you're one of the many maintainers

For some definitions of 'many', yes :grimacing:

**Comment by Ashvith10** [comment]
@Finii I was thinking of something as simple as placing a note, at the very top of the `README.md` file:

> Note: v3.0.0 introduces a few breaking changes, [read changelog](https://github.com/ryanoasis/nerd-fonts/blob/master/changelog.md#v300) before creating an issue.

And then create a small section providing guidance on how to migrate. Here's how I did, in the case of Starship's [NerdFont Symbol Preset](https://starship.rs/presets/nerd-font.html):

1.  Copy the missing symbol and use a character map app, like GNOME Characters (this is what I used) or [Soscisurvey's tool](https://www.soscisurvey.de/tools/view-chars.php) - in this particular example,  (U+F8D6).
2. Ignoring the 'U+', paste the rest of the alphanumeric sequence in the NerdFonts cheatsheat: we get "nf-mdi-package_variant_closed".
3. To get the valid glpyh, replace "mdi" with "md" - this will give us the new, valid glyph, which, in our case is 󰏗 (U+F03D7).
4. Now we can copy the icon and paste it in the desired configuration file.

Thoughts? Perhaps, there might be a better way to replace the Unicode value?

**Comment by sharpicx** [comment]
Im still getting this icons missing, how do i fix this? nerdfix doesnt give the usage experiencing, and i still dont understand how to use that thing.
![image](https://github.com/ryanoasis/nerd-fonts/assets/44630640/7c60ac06-ca71-409d-8160-3fd20820cd38)


> @Finii I was thinking of something as simple as placing a note, at the very top of the `README.md` file:
> 
> > Note: v3.0.0 introduces a few breaking changes, [read changelog](https://github.com/ryanoasis/nerd-fonts/blob/master/changelog.md#v300) before creating an issue.
> 
> And then create a small section providing guidance on how to migrate. Here's how I did, in the case of Starship's [NerdFont Symbol Preset](https://starship.rs/presets/nerd-font.html):
> 
> 1. Copy the missing symbol and use a character map app, like GNOME Characters (this is what I used) or [Soscisurvey's tool](https://www.soscisurvey.de/tools/view-chars.php) - in this particular example,  (U+F8D6).
> 2. Ignoring the 'U+', paste the rest of the alphanumeric sequence in the NerdFonts cheatsheat: we get "nf-mdi-package_variant_closed".
> 3. To get the valid glpyh, replace "mdi" with "md" - this will give us the new, valid glyph, which, in our case is 󰏗 (U+F03D7).
> 4. Now we can copy the icon and paste it in the desired configuration file.
> 
> Thoughts? Perhaps, there might be a better way to replace the Unicode value?
> 
> Edit: [NerdFix](https://github.com/loichyan/nerdfix) looks like a better way to deal with obsolete icons.

**Comment by leo-bianchi** [comment]
Hello @Finii .
Im having the same problem with a similar scenario. Im using Windows 10 with Windows Terminal and oh-my-posh (v3) and MesloLGM Nerd Font. I made the setup today so I installed the latest and stable releases for everything.
Im missing the same icons as @Akshzz-16. + I saw that Im missing .xml file icon (which was updated on v3, i think). Could you say how can I provide you the codepoint for missing icons?

**Comment by Finii** [comment]
> Could you say how can I provide you the codepoint for missing icons?

Just mark the text that contains the icon (with a mouse probably) and copy the text including the icon. Then just paste that text into a comment here. It might or might not show up correctly in the browser, but in any way I can continue with that.

Or you paste the text into https://onlinetools.com/unicode/convert-unicode-to-code-points, below set the format to hex, and read the codepoints in the right hand side window.

Or just copy that one icon as text and paste it into https://www.nerdfonts.com/cheat-sheet. If it is or once was a Nerd Fonts icon it will show up (thanks to #1307).

**Comment by leo-bianchi** [comment]
> Or just copy that one icon as text and paste it into https://www.nerdfonts.com/cheat-sheet. If it is or once was a Nerd Fonts icon it will show up (thanks to #1307).

Thanks for the help!

codepoints:
U+F72D U+000A U+F880 U+000A U+F74E U+000A U+FD03 U+000A U+F5E7 U+000A U+F74C U+000A U+FB9B

binaries:
1111011100101101
1111100010000000
1111011101001110
1111110100000011
1111010111100111
1111011101001100
1111101110011011

**Comment by Finii** [comment]
That all seem to be codepoints > `F500`. They have been dropped with Nerd Fonts `v3`.

Please read
* https://github.com/ryanoasis/nerd-fonts/issues/1190#issuecomment-1530999114

That Issue should also give you hints how to fix the problem.

**Comment by riiyaa24** [comment]
Hello, I would like to work on this issue. Can you assign this to me?
