### ISSUE TITLE
CartographCF becomes CartographF Nerd Font Condensed

### ISSUE THREAD

**Issue by sounak-kun** [ryanoasis/nerd-fonts#1258]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Some weights of CartographCF is converted to Nerd Fonts as CartographF Nerd Font Condensed.
While I can't the share the font, the issue is with the metadata. Changing the metadata of any font similar to the attached image would result in this behavior.

Expected behavior:
All weights of CartographCF gets converted to CartographCF Nerd Font.

Example symbols:
None

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _CartographCF-Bold.otf_
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - self patched
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - alacritty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Linux, Fedora Workstation 38

#### ★ Screenshots (Optional)

![Screenshot from 2023-05-25 02-27-54](https://github.com/ryanoasis/nerd-fonts/assets/93094402/b30733c5-da2d-473a-a46a-ac99945652a9)
![Pasted image](https://github.com/ryanoasis/nerd-fonts/assets/93094402/a9ba78fb-d54e-4cf1-afb6-2a3a977566dc)

**Comment by sounak-kun** [comment]
Note: This is a regression from v2.3.3, where it used to become `Cartograph CF Bold Nerd Font Complete`.

**Comment by Finii** [comment]
Thanks for reporting, will try to reproduce.

You could share the debug information, that you get when patching with `--debug 2`.
But probably that would not help me. There is some debug missing in the FontnameParser :thinking: 

---

ah, just from re-reading that. It most probably takes the C of CF as the extremely shortened 'condensed' moniker.
I believe we do not need that anymore anyhow, that is a leftover from 'parse the filename' times fallback and `Ubuntu-C`.

**Comment by Finii** [comment]
```console
$ fontforge ~/git/nerd-fonts/font-patcher CartographCF-Bold.ttf --debug 2 2>/dev/null
Nerd Fonts Patcher v3.0.1-5 (4.3.2) (ff 20230101)
DEBUG: Naming mode 1
DEBUG: Monospace check: Panose is invalid ([0, 0, 8, 9, 0, 0, 0, 0, 0, 0]); glyph-width-mono True
INFO: Setting Panose 'Family Kind' to 'Latin Text and Display' (was 'Any')
DEBUG: Extended glyphs wider bounding box than basic glyphs
DEBUG: Final font cell dimensions 1230 w x 2725 h
DEBUG: 32/160 box drawing glyphs will be replaced
Adding 180 Glyphs from Seti-UI + Custom Set
╢████████████████████████████████████████╟ 100%
Adding 6 Glyphs from Heavy Angle Brackets Set
╢████████████████████████████████████████╟ 100%
Adding 160 Glyphs from Box Drawing Set
╢████████████████████████████████████████╟ 100%
Adding 198 Glyphs from Devicons Set
╢████████████████████████████████████████╟ 100%
Done with Patch Sets, generating font...
DEBUG: =====> Family (ID 1)      ok       (31 <=31): CartographF Nerd Font Condensed
DEBUG: =====> SubFamily (ID 2)   ok       ( 4 <=31): Bold
DEBUG: =====> Fullname (ID 4)    ok       (36 <=63): CartographF Nerd Font Condensed Bold
DEBUG: =====> PSN (ID 6)         ok       (27 <=63): CartographFNF-CondensedBold
DEBUG: =====> PrefFamily (ID 16) ok       (21 <=31): CartographF Nerd Font
DEBUG: =====> PrefStyles (ID 17) ok       (14 <=31): Condensed Bold
DEBUG: Tweaking 1/1
   CartographF Nerd Font Condensed Bold
   \===> 'CartographFNerdFont-CondensedBold.ttf'
```

**Comment by Finii** [comment]
Will be fixed with 'in parens version number' `4.3.3` (see PR above).

Thanks again for bringing this up.
Helped to throw out obsolete code :+1:

**Comment by Finii** [comment]
When you patch with default naming the names are not strictly conforming (i.e. too long):

```console
$ find . -name '*.ttf' -exec fontforge ~/git/nerd-fonts/font-patcher --dry {} \; 2>/dev/null | grep ERR 
ERROR: ====-< Family (ID 1)      too long (33 > 31): CartographCFExtra Nerd Font Light
ERROR: ====-< Family (ID 1)      too long (33 > 31): CartographCFExtra Nerd Font Light
```

If that is a concern for you (which is unlikely), you need to specify either `--makegroup 3` or `--makegroup 4` depending on your preference.

**Comment by Finii** [comment]
Hmm, did you patch different fonts or is `font-patcher` breaking the version :-o

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/73ffb228-a68e-490b-9c89-e56c93cd396d)

**Comment by Finii** [comment]
Hmm,

`CartographCFExtra Nerd Font Light`

What is `Extra`? This is another bug? Should be ExtraLight/ExtraBold?
I smell a general problem.

```console
$ fontforge ~/git/nerd-fonts/font-patcher CartographCF-ExtraBold.ttf --debug 2 --dry 2>/dev/null
Nerd Fonts Patcher v3.0.1-6 (4.3.3) (ff 20230101)
DEBUG: Naming mode 1
DEBUG: Monospace check: Panose is invalid ([0, 0, 9, 9, 0, 0, 0, 0, 0, 0]); glyph-width-mono True
INFO: Setting Panose 'Family Kind' to 'Latin Text and Display' (was 'Any')
DEBUG: Extended glyphs wider bounding box than basic glyphs
DEBUG: Final font cell dimensions 1230 w x 2743 h
DEBUG: 32/160 box drawing glyphs will be replaced
Done with Patch Sets, generating font...
DEBUG: =====> Family (ID 1)      ok       (27 <=31): CartographCFExtra Nerd Font
DEBUG: =====> SubFamily (ID 2)   ok       ( 4 <=31): Bold
DEBUG: =====> Fullname (ID 4)    ok       (32 <=63): CartographCFExtra Nerd Font Bold
DEBUG: =====> PSN (ID 6)         ok       (24 <=63): CartographCFExtraNF-Bold
DEBUG: =====> Filename 'CartographCFExtraNerdFont-Bold.ttf'
```

**Comment by Finii** [comment]
```| Fullname                                                                                                                                                     
|-------------------------------                                                                                                                               
| Cartograph CF Extra Bold                                                                                                                                     

| Family
|-------------------------------
| Cartograph CF Extra Bold
 
| Subfamily                      
|------------------------------- 
| Extra Bold  
```

Ah yes, they insert a blank where they should not. Maybe we should handle that also, although that is not really 'conforming' to have `Extra Bold` instead of `ExtraBold`. Modifiers ought to stick to what they modify.

**Comment by Finii** [comment]
> That makes sense. That makes me wonder, why did that issue not occur in 2.3.3 though?

The default was `--makegroups 0` for pre `v3.0.0` releases, meaning old/broken re-naming system where the patcher does not try to 'understand' the font name but just sticks `Nerd Font` at some place in some name fields (but not all :unamused: )

> If I may suggest an alternative, we could pass the name of the font as a command line argument, like `--name Cartograph CF`, which could help the parser to handle fonts with non-conforming names.

That would not exactly help, as all those Cartograph fonts have different weights or styles, and if we do not autodetect them you would need to specify them specifically for each of the fonts.
And it is not very hard to be blank-tolerant there, I just need to write that down in code. We never had such a font before, that's why it's not handled.

**Comment by Finii** [comment]
Addendum:

```
    # --makegroup has an additional undocumented numeric specifier. '--makegroup' is in fact '--makegroup 1'.
    # Original font name: Hugo Sans Mono ExtraCondensed Light Italic
    #                                                             NF  Fam agg.
    # 0  turned off, use old naming scheme                        [-] [-] [-]           
    # 1  HugoSansMono Nerd Font ExtraCondensed Light Italic       [ ] [ ] [ ]
    # 2  HugoSansMono Nerd Font ExtCn Light Italic                [ ] [X] [ ]    
    # 3  HugoSansMono Nerd Font XCn Lt It                         [ ] [X] [X]
    # 4  HugoSansMono NF ExtraCondensed Light Italic              [X] [ ] [ ]
    # 5  HugoSansMono NF ExtCn Light Italic                       [X] [X] [ ]
    # 6  HugoSansMono NF XCn Lt It                                [X] [X] [X]
```

**Comment by sounak-kun** [comment]
> That would not exactly help, as all those Cartograph fonts have different weights or styles, and if we do not autodetect them you would need to specify them specifically for each of the fonts. And it is not very hard to be blank-tolerant there, I just need to write that down in code. We never had such a font before, that's why it's not handled.

I could probably run it as
```bash
for FONT in cartograph-cf/*; do fontforge -script font-patcher --complete --name "Cartograph CF" $FONT; done
```
but I do understand the value of a proper solution. Thank you again. For the time being, I guess I'll patch it with `--makegroup 0`.

**Comment by Finii** [comment]
Patcher with the fix available now as docker or zip.
