### ISSUE TITLE
Mononoki patched fonts have "UniqueID" where "Regular", "Bold", and "Italic" should go

### ISSUE THREAD

**Issue by gwerbin** [ryanoasis/nerd-fonts#126]
Mononoki patched fonts say "UniqueID" where they would typically say "Bold", "Regular", or "Italic". The "BoldItalic" variant has the correct name.

**Comment by ryanoasis** [comment]
Hmm that's weird. I'll look into it. Thanks

**Comment by paul** [comment]
I also have the same issue. Additionally, the "UniqueID" typeface renders as bold italic in my iTerm2.


![2017-04-01 at 6 11 pm](https://cloud.githubusercontent.com/assets/184/24590911/136c4622-17b3-11e7-8bc6-00f9b4efb0b6.png)
