### ISSUE TITLE
update windows 11 icons

### ISSUE THREAD

**Issue by Y0J1G3N** [ryanoasis/nerd-fonts#1266]
Windows 11 has been released for a few years now.
![image](https://github.com/ryanoasis/nerd-fonts/assets/43652659/ae3fdf90-beea-4cb7-b5bb-6bfb30f1c645)
The result of the search icon is still in the style of Windows 10.

**Comment by Finii** [comment]
https://www.howtogeek.com/798298/every-microsoft-windows-logo-from-1985-to-2022/

**Comment by Y0J1G3N** [comment]
Will it be updated to the Windows 11 icons shown above?

**Comment by Finii** [comment]
Would that be good or bad or?

**Comment by Y0J1G3N** [comment]
I lean towards good.

**Comment by Finii** [comment]
Just 'lean toward good'? What is missing for full 'yeah that'd be cool'?

**Comment by Y0J1G3N** [comment]
Yeah, that'd be awesome! I'm totally in favor of it!‎|•'-'•) ✧

**Comment by Finii** [comment]
Sometimes it is hard to fully grasp what people mean with written text. Just wanted to make sure you have no reservations (maybe the gap size is wrong or whatever). :+1:

**Comment by Finii** [comment]
Plugging this into v3.1.0
