### ISSUE TITLE
Please add tags to docker images

### ISSUE THREAD

**Issue by Karmenzind** [ryanoasis/nerd-fonts#1267]
![image](https://github.com/ryanoasis/nerd-fonts/assets/17923071/5baff39c-d97f-4e4c-aa49-8918276ab6b6)

I'm using the patcher image in my script (`docker run --rm -v $in_path:/in -v $out_path:/out nerdfonts/patcher -c --also-windows`). 
It seems that the new version may break the old buildings.
Please add tags to images, so the users can write the specific version in their scripts to avoid unknown changes. 
Thanks a lot!

**Comment by Finii** [comment]
But there are no tags no nothing regarding this in the repo; how should anyone know what is which with that.

Is your problem not solved by the digest/hash thing of docker itself?
`docker container ls -a` or something? Have no docker on current machine.

**Comment by Finii** [comment]
Ah, it's called `image ID`

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/fbd584a6-6250-42b7-bec4-3550556aad70)

And you can always use the images you downloaded some years ago ;-D

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/b12a5e07-9dd3-4e3a-af02-45f7c90f014f)
_Example of running my locally stored 2.3.0 image_

**Comment by Karmenzind** [comment]
@Finii Hi Finii,
Thanks for your kind reply. Hardcoding the digest/hash can solve my problem. 
But I think it will be better to use version (like you said, in-parens version or simple date) as tags, just to make it more readable like common docker images as below.
![image](https://github.com/ryanoasis/nerd-fonts/assets/17923071/718944b2-b5ee-4a5f-a5fc-b5291de08f32)

**Comment by Finii** [comment]
I can try something.

A problem is that I have zero rights at that docker repo so I can not iron out any mistakes 😬

**Comment by Finii** [comment]
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/4ab675b0-257c-4cd4-8e5f-1fc15d30b611)

Hmm, maybe we also need to add the tag `master`, is that possible? `master` has been the synonym to `latest` previously. I would rather remove the `master` image, but I guess I can not :grimacing:

**Comment by Finii** [comment]
Fixed.

Thanks for the suggestion!

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/46d86a41-a331-4dd2-ad75-1501f2eb82e3)

**Comment by Finii** [comment]
@allcontributors please add @Karmenzind for ideas

**Comment by Finii** [comment]
Hah, now we have the current and the previous patcher :+1:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/c85f2d16-43b6-48f6-8600-4b63e5ac1592)

**Comment by mdschweda** [comment]
> I can try something.
> 
> A problem is that I have zero rights at that docker repo so I can not iron out any mistakes 😬

@Finii @ryanoasis 

Did the project change hands? There is still an open seat in the Docker Hub org and I happen to have ownership rights.
