### ISSUE TITLE
some icons are missing

### ISSUE THREAD

**Issue by sharpicx** [ryanoasis/nerd-fonts#1268]
![image](https://github.com/ryanoasis/nerd-fonts/assets/44630640/99be5427-e9a7-48bf-b766-9a9bc2ee4240)

i just reinstalled my arch linux on my new device, and i got so much of outadded components here, nerdfont included. i dont know what the problems are, but in my old device, i never tried to update all of my packages, because im afraid and tired to fix the new bugs. where do i get the previous version of nerd fonts with `complete` title in its file name?

edited: nevermind, i have solved this with [nerdfix](https://github.com/loichyan/nerdfix/)

**Comment by Finii** [comment]
> where do i get the previous version of nerd fonts with `complete` title in its file name?

Any release before `v3.0.0`:
https://github.com/ryanoasis/nerd-fonts/releases

**Comment by sharpicx** [comment]
> > where do i get the previous version of nerd fonts with `complete` title in its file name?
> 
> Any release before `v3.0.0`: https://github.com/ryanoasis/nerd-fonts/releases

thanks, this one is what i was looking for!
