### ISSUE TITLE
Powerline glyphs do not align in console

### ISSUE THREAD

**Issue by Hebgbs** [ryanoasis/nerd-fonts#128]
OS: Ubuntu 16.10
Shell: zsh
Shell theme: PowerLevel9K
Term: fbterm

Reproduction steps
*Attempt in a fresh install of Ubuntu; I was unable to use fbterm without rebooting, problems may be encountered in a live session.*
**In X session**
```
sudo apt install git zsh fbterm
git clone https://github.com/bhilburn/powerlevel9k.git ~
git clone https://github.com/ryanoasis/nerd-fonts.git ~
sudo chmod +x ~/nerd-fonts/install.sh
~/nerd-fonts/install.sh
touch ~/.zshrc
# It may be more ideal to generate a .zshrc first, then editing it by hand.
printf "export TERM=\"xterm-256color\"\nsource /home/$USER/powerlevel9k/powerlevel9k.zsh-theme" | tee -a ~/.zshrc
sudo gpasswd -a $USER video
sudo chmod u+s /usr/bin/fbterm
```
**In TTY console**
```
fbterm -n "SauceCodePro Nerd Font" -s 16
# Provided as an example; Applies to all available, at all sizes
export TERM=fbterm
```

**Comment by ryanoasis** [comment]
@Hebgbs thanks for the report (and a detailed one at that!). I will look into it when I get some time but I cannot promise when :disappointed:

**Comment by Hebgbs** [comment]
It's fine man. If you just want to install it on your system and _get to the point_ (assuming you use Ubuntu / Debian, probably erroneously), you can do `sudo fbterm` then inside that `export TERM=fbterm` for 256 colours.

I should had provided more details behind it; fbterm needs non-root users in video group else it claims you must be root to use fbterm's VESA stuff and not permit its use anyway. A dumb error in design IMO, but explained in its man page why `fbterm` "Needs" `sudo`.

I like to provide options where users don't have to immediately pollute their systems with this stuff however they can. even if it means they have to go to certain lengths to try things out because then users don't have to waste time uninstalling it from their system. Makes sense yeah? That, and the newbies can give it a try.

**Comment by ryanoasis** [comment]
I know I never got around to looking into this for you but the latest fonts for v1.1.0 have just been uploaded.. let me know if they improve things if you can :smile:

**Comment by xxx** [comment]
I can't speak for @Hebgbs, and I don't use fbterm, but I had what sounds like this same powerline alignment problem, and upgrading just now to 1.1.0 took me from [before](http://i.imgur.com/AewsARH.jpg) to [after](http://imgur.com/wA8NNHM.jpg). Same change with powerlevel9k theme. So yay maybe?

**Comment by LuRsT** [comment]
@Hebgbs Have you tried with the new updated fonts so we can close this?

**Comment by ryanoasis** [comment]
House Keeping (re-open if still is an issue @Hebgbs)
