### ISSUE TITLE
Lilex macOS punctuation issue

### ISSUE THREAD

**Issue by frkd-dev** [ryanoasis/nerd-fonts#1296]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Lilex font punctuation looks displaced to the right in macOS (terminal and vscode)

Expected behavior:
Lilex font punctuation on macOS is rendered centered and looks the same as on the programmingfonts.org

Example symbols:
a.b,c:d;e(f)g[h]i-j'k"l

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - LilexNerdFont-Regular.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Downloaded from Nerd Fonts
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - iterm2 and vscode
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - OS X

#### ★ Screenshots (Optional)

programmingfonts.org
<img width="210" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/129271/9448ed12-f768-448a-8735-00bddf2732e2">

macos vscode
<img width="225" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/129271/47c771e8-d348-456e-b20f-d7b1ac8b3cc7">

macos iterm2
<img width="198" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/129271/1330888f-b988-4eee-99cc-881bb2cee7ad">

**Comment by Finii** [comment]
Thanks for reporting, and closing ;)

How did you figure it out, that it were old fonts? I need to learn macOS related stuff :-)

**Comment by frkd-dev** [comment]
I've opened the Font Book app and looked through the installed fonts. The Lilex font should have 3 styles:

<img width="150" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/129271/688695fc-82ab-4d85-9d4e-5cbf2500973e">

But in my case, it have shown 6 styles which pointed me out that some old fonts were present in the system. I believe some old font versions had this "displaced punctuation" issue and macOS picked the older one somehow. I completely removed the Lilex font and reinstalled the latest one once again. The issue is gone.
