### ISSUE TITLE
Add DM Mono font 

### ISSUE THREAD

**Issue by tigerinus** [ryanoasis/nerd-fonts#1299]
**Requirements**

* [x]  I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
* [x]  I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
* [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**

[DM Mono](https://github.com/googlefonts/dm-mono) is a 3 weight, 3 style family designed for DeepMind. DM Mono was loosely based off of DM Sans, with a reduction in contrast and less geometric proportions. I think it makes codes and scripts looking great and would make a great addition to Nerd Fonts.

**Describe the solution you'd like**

Distribute this font with necessary patches.

**Describe alternatives you've considered**

https://github.com/minhuw/dm-mono-nerd-font 

**Additional context**

![image](https://github.com/ryanoasis/nerd-fonts/assets/7172560/79296de7-d628-4c00-8c0f-c876127d7bea)

**Comment by RahulSoni2532** [comment]
assign this to me i can add a DM mono font @tigerinus

**Comment by tigerinus** [comment]
> assign this to me i can add a DM mono font @tigerinus

I'm afraid I don't have the right for issue assignment.

**Comment by maltherd** [comment]
Daring a little @RahulSoni2532 in case this issue was forgotten :)
Have a nice day

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
