### ISSUE TITLE
Legacy computing block?

### ISSUE THREAD

**Issue by flowchartsman** [ryanoasis/nerd-fonts#1301]
**Requirements**
There is [at least one](https://github.com/dokutan/legacy_computing-font) SIL Open licesned font that has the recently-codified l[egacy computing](https://en.wikipedia.org/wiki/Symbols_for_Legacy_Computing) glyphs. Is it fit for inclusion? I'd love to use some of these symbols for graphing.

**Comment by RebeccaRGB** [comment]
The font used in the code charts is based on [Kreative Square](http://www.kreativekorp.com/software/fonts/ksquare/) which is SIL OFL licensed.

**Comment by flowchartsman** [comment]
Oh, nice, and it looks quite professional, too. But of course I guess I should expect that from the author of bits n' picas (thanks for that, by the way, I've made heavy use of it for [greybeard](https://github.com/flowchartsman/greybeard).I am especially impressed to see what looks like the full complement of sextants and octants. Now that's thorough.

I didn't see support for this in the Nerdfonts distribution, but fonts being what they are, I'm sure it can also act as a fallback. Do you have any recommendations for best practices here? I'd love to have access to all of these symbols in addition to the nerdfont distribution, however I'm aware that this can be a fiddly process.

**Comment by RebeccaRGB** [comment]
Thanks for the kind words. :)

I don't have much advice to give, unfortunately. Fallback fonts work differently in different applications, and I'm not familiar with how Nerdfonts works, so I couldn't offer advice for integrating KSquare into it specifically. But in general, KSquare's glyphs are designed to be integrated into other fonts by (non-uniformly) scaling them to fit the destination font's character cell (including shifting the baseline to compensate for the different ascent and descent).

**Comment by RebeccaRGB** [comment]
I wrote a python script that generates the vast majority of legacy computing symbols. It only needs the target font's ascent, descent, and character width. There are some optional parameters as well. It's in this repository: https://github.com/RebeccaRGB/slcgen

**Comment by oshaboy** [comment]
There's also the newer [Symbols for Legacy Computing Supplement](https://www.unicode.org/L2/L2022/22016.htm#170-C15) which is planned for Unicode 16

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
