### ISSUE TITLE
Displaying icon as hexa not working or incorect icon

### ISSUE THREAD

**Issue by quentinlamamy** [ryanoasis/nerd-fonts#1304]
#### 🗹 Requirements

Up to date font
Visual studio code with this config
```json
    "debug.console.fontFamily": "DroidSansM Nerd Font Mono",
    "debug.console.fontSize": 20,
    "editor.fontFamily": "DroidSansM Nerd Font Mono",
    "editor.fontSize": 20,
```

#### 🎯 Subject of the issue

Experienced behavior: The icon is not showing in hex or incorect icon is displayed

Expected behavior: Have the right icon :)

Example symbols:
nf-fae-apple_fruit, nf-md-exit_to_app

#### 🔧 Your Setup

-  DroidSansM Nerd Font Mono
- Downloaded from Website (and reinstalled to be sure)
- VSC debug console and VSC terminal
- OSX

#### ★ Screenshots (Optional)

```javascript
console.log("\udb81\uddfc",String.fromCharCode(parseInt("f05fc",16)),"\ue29e",String.fromCharCode(parseInt("029e",16)))
````
Print :

VSC terminal
<img width="127" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/6804887/c9ed3162-da20-404b-9acf-d823f097df66">
VSC debug console
<img width="127" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/6804887/bc05516e-5f94-476f-9054-59d75c75f70e">

**Comment by Finii** [comment]
I can not see the problem; it is shown in both images, 1st icon? Or what do you mean?
I believe the `fromCharCode` does not work with 5 digit codepoints :thinking:

**Comment by Finii** [comment]
Closing: no response.
