### ISSUE TITLE
website: Add ability to search by icons

### ISSUE THREAD

**Issue by ad-chaos** [ryanoasis/nerd-fonts#1307]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
There are cases that I find myself into sometimes when I have the glyph with me but not its name or codepoint.
It would be nice to be able to search for the codepoint and/or name of a glyph by literally putting it into the search box of the cheat-sheet.
There are several reasons to know the name of the glyph, to use it in a webpage, to look for alternatives when they get removed, etc.

**Describe the solution you'd like**
Since the names and codepoints are ascii only, we can make the assumption that if the query has any other character it is most probably an icon and proceed to search for that icon.

**Describe alternatives you've considered**
The way I do it right now is by doing `hex(ord("<the-icon>"))` in python then copying the hex value and paste that into the search box to get the name of the icon.

**Additional context**
I do have a patch with me, but this repository is huuge hence didn't make a PR

```diff
diff --git a/cheat-sheet.js b/cheat-sheet.js
index 2e1d4d97..e17f76e5 100644
--- a/cheat-sheet.js
+++ b/cheat-sheet.js
@@ -125,14 +125,16 @@ document.addEventListener('DOMContentLoaded', function () {
     }
 
     function searchGlyphs() {
-        let searchTerm = elementGlyphSearch.value;
+        let searchTerm = [...elementGlyphSearch.value]
+                    .map((char) => char.codePointAt(0) > 128 ? char.codePointAt(0).toString(16) : char)
+                    .join("");
 
         let prefixSearchEnabled = true;
         let emptyResultsMessage = `<span style="font-size: 30px;">No matches found</span>`;
 
         if (searchTerm === "") {
             // MiniSearch doesn't allow empty searches and we want to show the bottom info
-            emptyResultsMessage = "Enter (part) of a word to search for or enter space / blank (' ') to show all icons"
+            emptyResultsMessage = "Enter (part) of a word or icon to search for or enter space / blank (' ') to show all icons"
         } else {
             if (searchTerm === " ") {
                 prefixSearchEnabled = false;
```

**Comment by Finii** [comment]
Excellent idea, thank you.

I usually use online tools like https://onlinetools.com/unicode/convert-unicode-to-code-points to do just that.
To determine the codepoint of reported bad glyphs.

Trying your patch...
