### ISSUE TITLE
Icons are missing from different fonts

### ISSUE THREAD

**Issue by cabiamdos** [ryanoasis/nerd-fonts#1310]
#### 🗹 Requirements

- [ x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [ x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [ x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

I have found something related but it isn't helpful, so I am opening this issue here. 
![image](https://github.com/ryanoasis/nerd-fonts/assets/82284393/f30bf403-665b-4d07-9c36-882e2c4c4c3c)

As you can see here I am using on the left the "CaskaydiaCove NFM" which is the most recent font that I installing by using "oh-my-posh font install" and then selecting the CaskaydiaCove, and on the right the "CaskaydiaCove Nerd Font" (https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip?WT.mc_id=-blog-scottha -o cove.zip) which I installing from this github repo.
<br>
As you can see some icons are missing, one version has the icons that the other version doesn't have & vice-versa. It has happened to me with more fonts too.
<br>
So my idea here was to mere the fonts, so I tried this script:

```
import fontTools.ttLib as tt
import fontTools
from fontTools.merge import Merger
from fontTools.ttLib import TTFont
import os

current_path = os.path.dirname(os.path.abspath(__file__))

font1 = current_path + nameOfFirstFont.ttf
font2 = current_path + nameOfSecondFont.ttf
font3 = current_path + outputOfFont.ttf
merge_fonts(f

def merge_fonts(font1_path, font2_path, output_path):
    font1 = font1_path
    font2 = font2_path

    font3 = fontTools.merge.Merger().merge([font1, font2])

    # Save the merged font to the output path
    font3.save(output_path)
```

But it didn't work. I also tried merging the fonts using the "fontForge" exe program but it didn't work.
Also appart from the powershell I have the same issue using the CMD and the bash in ubuntu.
<br>
I have also folled this instructions (https://ohmyposh.dev/docs/faq#after-updating-my-nerd-font-to-a-newer-version-the-prompt-displays-unknown-characters) but they doesn't work for me. I am not sure if it is a problem that has to do with oh-my-posh or nerd fonts.

Expected behavior:

I expect to see the icons correctly in the lastest version of the fonts, all the icons.

Example symbols:

#### 🔧 Your Setup
![image](https://github.com/ryanoasis/nerd-fonts/assets/82284393/05d94ebb-6aa0-4964-b242-428b9aed494a)
oh-my-posh v17.5.3
windows 10

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_
   - Also the font names are really really confusing, because if I enter in font forge -> font info - I have "Fontname", "Family Name", "Name For Humans", and in the powershell it is impressive but I can't change the font on the terminal, only on an ugly interface by selecting "properties" and then changing the font, it doesn't even display all the fonts
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - 
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - 
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - 

#### ★ Screenshots (Optional)

Last night I couldn't sleep. Anyways thanks for your attention

**Comment by cabiamdos** [comment]
edit I am thinking if I can do something like this (https://github.com/fontforge/fontforge/issues/1816) and replace the icons that are missing or that I see missing manually, this could help.
<br>
Let me see if I can fix like this, I will keep it update here. But ideally I would like to merge missing unicode characters from one font to another. Thanks for your attention

**Comment by cabiamdos** [comment]
I end up trying to generating the font from the font generator, howerver, I get the following results:
![image](https://github.com/ryanoasis/nerd-fonts/assets/82284393/a08a8c27-e56a-4427-89c1-d7c0a0fcb567)

It seems there is no space

**Comment by Finii** [comment]
The icons have moved codepointes.

* Release notes 3.0.0 https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0
* Announcement in release notes 2.3.3 https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3
* Main discussion topic, with helpers to solve the problem: Issue 1190

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/e369ab57-09a9-4a21-8052-61a58858a8ab)
