### ISSUE TITLE
Programmingfonts.org now also features Gohu nerd font

### ISSUE THREAD

**Issue by braver** [ryanoasis/nerd-fonts#1312]
Hi, I'm the maintainer of programming fonts.org. We've recently added Gohu, in both [11](https://www.programmingfonts.org/#gohufont-11) and [14](https://www.programmingfonts.org/#gohufont-14) pixel sizes. You might want to add a preview link to the [downloads page](https://www.nerdfonts.com/font-downloads). If you need to pick one, I would default to the 14 size, the bigger size is a better illustration of the character of the font.

**Comment by Finii** [comment]
Thanks for the pointers! :tada:
I will change asap.
