### ISSUE TITLE
Error patching Input Mono Condensed font

### ISSUE THREAD

**Issue by linrongbin16** [ryanoasis/nerd-fonts#1314]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

<img width="988" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/6496887/95625e9e-b93f-42e5-baef-8a0f49d9565e">

There's an error:
```
ERROR: ====-< Family (ID 1)      too long (36 > 31): InputMonoCondensedIta Nerd Font Thin
   InputMonoCondensedIta Nerd Font Thin
   \===> 'InputMonoCondensedItaNerdFont-Thin.ttf'
```

Expected behavior:

patch font successful.

Example symbols:

#### 🔧 Your Setup

OS: macOS 13.4.1, apple M1 MAX chip
Input Font: https://input.djr.com/download/
brew install fontforge
latest nerdfont font-patch script.

**Comment by Finii** [comment]
```
$ fontforge font-patcher ~/Downloads/input_font/Input_Fonts/InputMono/InputMonoCondensed/InputMonoCondensed-ThinItalic.ttf --debug

Nerd Fonts Patcher v3.0.2-16 (4.4.2) (ff 20230101)
DEBUG: Naming mode 1
DEBUG: Monospace check: Panose says "monospaced"; glyph-width-mono True
DEBUG: Extended glyphs wider bounding box than basic glyphs
DEBUG: Font has negative right side bearing in extended glyphs
DEBUG: Final font cell dimensions 624 w x 1320 h
ERROR: ====-< Family (ID 1)      too long (36 > 31): InputMonoCondensedIta Nerd Font Thin
DEBUG: =====> SubFamily (ID 2)   ok       ( 7 <=31): Regular
DEBUG: =====> Fullname (ID 4)    ok       (36 <=63): InputMonoCondensedIta Nerd Font Thin
DEBUG: =====> PSN (ID 6)         ok       (28 <=63): InputMonoCondensedItaNF-Thin
DEBUG: =====> PrefFamily (ID 16) ok       (31 <=31): InputMonoCondensedIta Nerd Font
DEBUG: =====> PrefStyles (ID 17) ok       ( 4 <=31): Thin
DEBUG: Tweaking 1/1
DEBUG: Changing lowestRecPPEM from 8 to 6
```

... examining

**Comment by Finii** [comment]
Obviously they use the non-standard abbreviation `Ita` for `Italic` ...

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/d1186d20-b08a-47c8-9864-6a87aa8aa274)

Why don't we use the PS name?

_From font-patcher:_
```python
if FontnameParserOK and self.args.makegroups > 0:
    use_fullname = isinstance(font.fullname, str) # Usually the fullname is better to parse
    # Use fullname if it is 'equal' to the fontname
    if font.fullname:
        use_fullname |= font.fontname.lower() == FontnameTools.postscript_char_filter(font.fullname).lower()
    ...
    parser_name = font.fullname if use_fullname else font.fontname
    ...
    n = FontnameParser(parser_name, logger)
```

That test makes no sense? :thinking: 

It always takes the fullname, even if the PS name differs? I need a :coffee: and then I dig into `git blame`.
Maybe I overlook something?

**Comment by Finii** [comment]
Ah, that was:

```python
    use_fullname = True # Usually the fullname is better to parse
    use_fullname |= self.sourceFont.fontname.lower() == FontnameTools.postscript_char_filter(self.sourceFont.fullname).lower()
```
(until abf3016d), where the `= True` is obviously a later addition

And .. there seems to be no history on that code (6d86114a). Did I squash the commits?!? :sob:

**Comment by Finii** [comment]
Sorry, I just can not squeeze this in my time schedule right now.
But to help you, locate this code in the `font-patcher`:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/5a80a9ec-ccbe-4438-b15e-b7ebec01e225)

And replace

```diff
-            use_fullname = isinstance(font.fullname, str) # Usually the fullname is better to parse
+            use_fullname = false
```

That should fix the names in your case.

I would need to check all the pre-patched fonts in the repo and some more before any commit in that part of the code can be merged. I remember doing a lot of rename runs and checking fonts - which took ages back then. Meanwhile more debugging is in place, so it will definitively not take me several days like before, but in a few hours I will leave with a group of adolescents on a camping trip and need to prepare stuff. :tent:

**Comment by linrongbin16** [comment]
Thanks for your suggestion!
Let's leave this issue open to track it.

**Comment by Finii** [comment]
That ERRORs are basically there for me, when I patch a new font, that the `--makegroups` option must be tweaked and put into the `config.cfg` file in the appropriate `unpatched-fonts/` dir.

```console
$ cat src/unpatched-fonts/CascadiaCode/config.cfg
config_patch_flags="--makegroups 4"
```

**Comment by linrongbin16** [comment]
Oh thanks

**Comment by Finii** [comment]
I would keep this open because of the wrong "Ita"

Need to recheck if the PS name vs fullname and evt add a cmdline swirch.

Thanks for reporting btw.

**Comment by linrongbin16** [comment]
sure

**Comment by Finii** [comment]
Examined all `src/unpatched-fonts/` and indeed the fullname is better to parse for a lot (felt like 15%) of the fonts and with not a single one the PSname was better.

Often the PS name has strange abbreviations, and it misses of course the blanks or other separators for parts, apart from the name-style separator `-`. That makes the parsing particularly difficult.

So Input Mono seems to be exceptional in this case - that the strange abbreviations are in the fullname and the PSname has the better content.
