### ISSUE TITLE
patched font "Lucida console" for Win7' CMD please

### ISSUE THREAD

**Issue by jazei-AR** [ryanoasis/nerd-fonts#1320]
Hi, I am using win7.
using CMD FOR VIM 
cmd has only 3 fonts 1 is utf-8: **Lucida console**
may be you can do the patched font.
thank you regards!

**Comment by Finii** [comment]
As far as I can see `Lucida Console` is not a 'free' font and thus we can not distribute it (even patched).

If you need a `Lucida Console Nerd Font` you have to patch that on your own (if that is allowed).

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/b33e192a-6b7a-48ad-97b0-8b85842f1ffb)
