### ISSUE TITLE
Lilex fonts' "Thin" and "Bold" weights all are labeled "Normal", thus not installable next to the "Regular" weight

### ISSUE THREAD

**Issue by LeoniePhiline** [ryanoasis/nerd-fonts#1333]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Lilex fonts' "Thin" and "Bold" weights all are labeled "Normal", thus not installable next to the "Regular" weight.

This applies to "Lilex", "Lilex Mono" and "Lilex Propo".

Expected behavior:

Each file should contain a font labelled with the according font weight. E.g. the File called "LilexNerdFont-Bold.ttf" should contain a font named "Lilex Nerd Font, Bold", not "Lilex Nerd Font, Normal".

Example symbols:

Not relevant

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
  - LilexNerdFont-Bold.ttf
  - LilexNerdFont-Regular.ttf
  - LilexNerdFont-Thin.ttf
  - LilexNerdFontMono-Bold.ttf
  - LilexNerdFontMono-Regular.ttf
  - LilexNerdFontMono-Thin.ttf
  - LilexNerdFontPropo-Bold.ttf
  - LilexNerdFontPropo-Regular.ttf
  - LilexNerdFontPropo-Thin.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - GitHub, Release 3.0.2 Assets section
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Konsole, but that's not relevant. Installation fails.
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - OpenSUSE Tumbleweed

#### ★ Screenshots (Optional)

![grafik](https://github.com/ryanoasis/nerd-fonts/assets/22329650/0e4671e1-3a98-4e84-9e89-f32afd161e50)
![grafik](https://github.com/ryanoasis/nerd-fonts/assets/22329650/cd8a1d4f-0036-4741-8dce-920c43e16f60)

Can't install "Bold" as it has the same internal font name as "Regular", namely "Normal":

![grafik](https://github.com/ryanoasis/nerd-fonts/assets/22329650/7f8df6ec-1ce0-44d5-b983-d4d1618763ec)

Each weight needs its own name.

**Comment by LeoniePhiline** [comment]
Same problem on a different font: "Thin" is labelled "Light".

Thus, "Thin" is not installable next to the actual "Light" font weight:

![grafik](https://github.com/ryanoasis/nerd-fonts/assets/22329650/d5e387b7-1ca1-4a91-8034-3f97b83c64c7)

**Comment by Finii** [comment]
Sorry to hear of your problems.

Unfortunately I can not reproduce.

Quick check on MacOS, which is normally very picky about fonts. I installed the 3 (Regular, Bold, Light) `Nerd Font` versions only:

<img width="1030" alt="Screenshot 2023-08-06 at 07 50 19" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/2a978d7a-f6b5-4cac-9c74-5f1c839e871a">

And looking into the naming, this looks good. Here the Bold variant, there is not even a mention of `Normal`:

<img width="887" alt="Screenshot 2023-08-06 at 07 54 12" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/2dec861f-6559-4db5-ae05-0e40b569e264">

And the `Thin` font:

<img width="887" alt="Screenshot 2023-08-06 at 07 54 32" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/f1f69bc4-9747-4b16-9325-94d241ba9a82">

You see the Thin font has two possible names, for old "just RIBBI names" applications it is `Lilex Nerd Font Thin`-`Regular` and for applications that can work with more than 4 styles it is `Lilex Nerd Font`-`Thin` (preferred names).

ID1 and ID2 ("Family" and "Styles (SubFamily)") form one name.
ID16 and ID17 ("Preferred Family" and "Preferred Styles") form another naming scheme.

I usually work with Linux, but I can not make out what (which application) `Schriftenbetrachter` is. From what I see in the screenshots it is strange too 😬 It tries to translate font names (transmogrifies `Thin` to the German `Leicht`).

Maybe you can try a different font manager, or install the fonts just by throwing them into `~/.local/share/fonts` via command line `cp`. Then try if you can see the fonts in e.g. LibreOffice Writer. It is like 25 years ago that I ever used Suse, so I do not know if you need to manually trigger a font cache update after copying the font files. And Writer needs to be restarted when fonts have been installed.

**Comment by LeoniePhiline** [comment]
Thanks for your response!

Would it be ok to keep the issue open? I need to find time to figure out the details with the new awesome information you gave me.

Maybe it's a bug in KDE's font viewer / fonts configuration app. I'd be curious to find out more and report in their bug tracker (linking to here) if that's the case.

Do you happen to know / like to recommend a Linux app to view font detail properties like the label-pairs you've show in your screenshots?

**Comment by Finii** [comment]
Shure, let it open.

To examine font files
* `fontforge` [(on Github)](https://github.com/fontforge/fontforge) (used for images above) (open a font, Element -> Font Info -> TTF Names)
* `showttf` or `ttfdump` (part of fontforge resp texlive)
* fontTools, maybe [ttx](https://fonttools.readthedocs.io/en/latest/ttx.html)

But they all just give you some name parts, and you need a understanding how they are to be used.
Maybe this is good to read https://learn.microsoft.com/en-us/typography/opentype/spec/name (kind of reference manual) or [this](https://glyphsapp.com/learn/naming) as a more learning centric explanation.
In boils down to know how the ID1/2, ID16/17, and ID21/22 are to be used and maybe what ID4 should be.
You can also find various discussions on the names in font forums. Important is to know that the IDs have different names attached to them in different applications, the only reliable referebne is the ID number not the "ID Name" like "Preferred Family".

Also worth to know that Nerd Fonts never sets ID21/22. It created RIBBI fonts sets in ID1/2 (of course) and the full style is only available in ID16/17. For ID1/2 the unrepresentable styles are represented via Family names instead.

RIBBI means Regular-Italic-Bold-BoldItalic. That is the "classic set" for applications that have an "Italics" and "Bold" button for the selected font. Sometimes that applications automatically generate missing styles (creates an oblique version of a font with no Italic style by slanting the glyphs, with ... mixed results).

What you maybe should examine is if the unpatched Lilex has the same problem. Its naming is about the same as the patched font, see

<img width="887" alt="Screenshot 2023-08-06 at 14 14 25" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/2bc3e56a-1c68-4bcc-bc66-bdf1a1441a5a">

<img width="887" alt="Screenshot 2023-08-06 at 14 12 18" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/1b70737d-9305-43a4-bd8b-3ff9915bdb90">

**Comment by Finii** [comment]
Thanks for the input, I will investigate (sorry for the delay)

**Comment by Finii** [comment]
You are right, the unpatched font already has `book` where it should have `bold`:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/7658e722-3c5c-44d1-9db4-a70eba426be2)

We do not tough the weight, assuming it is correct in the source.

I will check most recent source fonts and update NF accordingly if that is the case.

**Comment by Finii** [comment]
This is not in the 2.200 release, but we do not have `medium` anyhow ;-D

https://github.com/mishamyrt/Lilex/pull/13

**Comment by Finii** [comment]
Implemented a check for weight inconsistencies.

There are quite some more, but Lilex was the worst:
https://github.com/ryanoasis/nerd-fonts/pull/1358#issuecomment-1736605509

Thanks again for the thorough analysis here!

**Comment by Finii** [comment]
@allcontributors please add @LeoniePhiline for bug
