### ISSUE TITLE
Add Hybrid fonts

### ISSUE THREAD

**Issue by abdlmutii** [ryanoasis/nerd-fonts#1335]
**Requirements**

- [ ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [ ] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [ ] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Would like https://github.com/ghazyami/hybrid-mono-fonts but with icons

**Describe alternatives you've considered**
Would like https://github.com/ghazyami/hybrid-mono-fonts but with icons
So it's kawkab mono and jetbrains mono in the same time, but with the nerdy icons

**Additional context**
Nothing.

**Comment by SanyaArora123** [comment]
Hey @Finii , I would like to work on this .Kindly assign this to me.

**Comment by Finii** [comment]
Oh, I can not assign anyone, but feel free to create a PR.

Probably use #1318 as example / blueprint.

**Comment by Finii** [comment]
Please set `"repoRelease": false` for the font; see also
* #1360

**Comment by riiyaa24** [comment]
Hello, I would like to work on this issue. Can you assign me this PR?

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
