### ISSUE TITLE
Add documentation for "less" LESSUTFCHARDEF (Private Use Area characters definition) option

### ISSUE THREAD

**Issue by tkapias** [ryanoasis/nerd-fonts#1337]
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Issue**

On Linux,[less](https://github.com/gwsw/less), the most common pager, will no longer print Private Use Area characters by default.
I don't know when the transition took place, the version present in the Debian testing repositories  (590) does still display Nerd-fonts characters, but the compiled master (633) no longer displays them.

A [commit](https://github.com/gwsw/less/commit/dc4fa8c8c47dce999b9fdbd841f16b503b7d8632) dated September 25, 2022 introduces a new option (`LESSUTFCHARDEF`) that allows you to declare the type of character display according to the code points range.

Using this option to declare [code points listed in the wiki](https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points) with the last version force less to display Nerd-fonts characters.

``` bash
export LESSUTFCHARDEF=23fb-23fe:p,2665:p,26a1:p,2b58:p,e000-e00a:p,e0a0-e0a2:p,e0a3:p,e0b0-e0b3:p,e0b4-e0c8:p,e0ca:p,e0cc-e0d4:p,e200-e2a9:p,e300-e3e3:p,e5fa-e6a6:p,e700-e7c5:p,ea60-ebeb:p,f000-f2e0:p,f300-f32f:p,f400-f532:p,f500-fd46:p,f0001-f1af0:p
```

**Solution**

I think that instructions to export the correct variable should be given to Nerd-fonts users in the wiki or the readme.

**Other**

![image](https://github.com/ryanoasis/nerd-fonts/assets/45816387/95389823-a451-4a90-8d64-5002d69755ed)

**Comment by acidghost** [comment]
Thanks for the fix!

I just spent an entire morning trying to pin-point the issue. I found this #1337 issue while looking for the code points used by Nerd Fonts.

For additional reference, I the version of less that introduced the `LESSUTFCHARDEF` is [632](http://greenwoodsoftware.com/less/news.632.html), more details are discussed in gwsw/less#275.

From what I understand of the linked issue PUA characters were never meant to be displayed. Maybe it has something to do with the v3 changes in Nerd Fonts?

**Comment by Finii** [comment]
`more` is just more then `less` ;-D

After I took me years to switch from more to less I probably will switch back ;-)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/5eca4738-69e4-49c8-b1f2-3df6072b0e6a)

I will try to come up with a documentation change.
Thank you both very much!! :medal_sports:

**Comment by Cyb3rGhoul** [comment]
Can you assign me this issue?

**Comment by Finii** [comment]
@Cyb3rGhoul Of course, thank you

**Comment by powerman** [comment]
Here is value suitable for Nerd Fonts v3.2.1:
```sh
LESSUTFCHARDEF=23fb-23fe:w,2665-2665:w,2b58-2b58:w,e000-e00a:w,e0a0-e0a3:p,e0b0-e0bf:p,e0a0-e0c8:w,e0ca-e0ca:w,e0cc-e0d7:w,e200-e2a9:w,e300-e3e3:w,e5fa-e6b5:w,e700-e7c5:w,ea60-ec1e:w,ed00-efce:w,f000-f2ff:w,f300-f375:w,f400-f533:w,f0001-f1af0:w
```

**Comment by injust** [comment]
> Here is value suitable for Nerd Fonts v3.2.1 **non-Mono** version (with nice double width large icons 😄):
> 
> ```shell
> LESSUTFCHARDEF=23fb-23fe:w,2665-2665:w,2b58-2b58:w,e000-e00a:w,e0a0-e0a3:p,e0b0-e0bf:p,e0a0-e0c8:w,e0ca-e0ca:w,e0cc-e0d7:w,e200-e2a9:w,e300-e3e3:w,e5fa-e6b5:w,e700-e7c5:w,ea60-ec1e:w,ed00-efce:w,f000-f2ff:w,f300-f375:w,f400-f533:w,f0001-f1af0:w
> ```
> 
> Mono version will needs the same value with all `:w` replaced by `:p`.

How is this value generated? I'm not sure how to tell which code points are double-width.

Also, I think `e0a0-e0c8:w` overlaps with `e0a0-e0a3:p` and `e0b0-e0bf:p`?

**Comment by powerman** [comment]
> How is this value generated? I'm not sure how to tell which code points are double-width.

Manually. :disappointed: 

> Also, I think `e0a0-e0c8:w` overlaps with `e0a0-e0a3:p` and `e0b0-e0bf:p`?

Yeah, sorry, it was a typo I have already fixed somewhere else but missed to fix here: it should be `e0c0-e0c8:w` (just fixed in my original comment).

**Comment by injust** [comment]
According to https://github.com/gwsw/less/blob/v661/less.nro.VER#L2015-L2017, the code point ranges can also be single code points. It's probably clearer to do that for `2665`, `2b58`, and `e0ca`, which results in:

```
LESSUTFCHARDEF=23fb-23fe:w,2665:w,2b58:w,e000-e00a:w,e0a0-e0a3:p,e0b0-e0bf:p,e0c0-e0c8:w,e0ca:w,e0cc-e0d7:w,e200-e2a9:w,e300-e3e3:w,e5fa-e6b5:w,e700-e7c5:w,ea60-ec1e:w,ed00-efce:w,f000-f2ff:w,f300-f375:w,f400-f533:w,f0001-f1af0:w
```

**Comment by nikunjmathur08** [comment]
Is this issue still open? Can I work on this? @tkapias

**Comment by Finii** [comment]
Absolutely! 

Sent from Nine
________________________________

**Comment by tkapias** [comment]
Please do @nikunjmathur08,

I was still using the outdated values that I wrote in the first comment. 

I will now switch to the ones in [@injust's post](https://github.com/ryanoasis/nerd-fonts/issues/1337#issuecomment-2220690587).

The only way to close this issue will probably be by finding an updated and parsable list of codepoints in the repository (I don't know if they are listed in other places than the [wiki](https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points)) and writing a script in [`bin/script/`](https://github.com/ryanoasis/nerd-fonts/tree/master/bin/scripts/) to help users generate the right env variables for less.

**Comment by Finii** [comment]
glyphnames.json in the repo root has all codepoints. But not as range but individually. 


Sent from Nine

________________________________

**Comment by Finii** [comment]
@allcontributors please add @nikelborm for doc

**Comment by injust** [comment]
> To avoid constantly updating ranges you can just use this:
> 
> ```shell
> export LESS="-r"
> export LESSUTFBINFMT='*n%C'
> ```

I'm not convinced that this is a good idea.

less' man page says (in all caps too):
> USE OF THE -r OPTION IS NOT RECOMMENDED.

**Comment by powerman** [comment]
@Finii The ranges recommended in [the wiki](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting#solution-1):
```sh
export LESSUTFCHARDEF=23fb-23fe:p,2665:p,26a1:p,2b58:p,e000-e00a:p,e0a0-e0a2:p,e0a3:p,e0b0-e0b3:p,e0b4-e0c8:p,e0ca:p,e0cc-e0d4:p,e200-e2a9:p,e300-e3e3:p,e5fa-e6a6:p,e700-e7c5:p,ea60-ebeb:p,f000-f2e0:p,f300-f32f:p,f400-f532:p,f500-fd46:p,f0001-f1af0:p
```
differs a lot from ones in https://github.com/ryanoasis/nerd-fonts/issues/1337#issuecomment-2220690587 - why?

Also, wiki does not mention needs to use `:w` (wide char) for most (but not all) ranges for non-Mono version of a font.

**Comment by Finii** [comment]
Its not recommended because

http://www.greenwoodsoftware.com/less/faq.html#dashr

Well... I believe `less` wants to be too smart, in my book it should only spill out the text.
The Wiki just shows possibilities to circumvent the ... problematic ideas `less` has, everyone can choose what she or he wants to follow. ;)

P.S. I must say I become more and more frustrated with `less`, so I see myself falling back to `more` often.

**Comment by Finii** [comment]
> differs a lot from ones in https://github.com/ryanoasis/nerd-fonts/issues/1337#issuecomment-2220690587 - why?

I believe I took the sequence from this PR, did I not?
Ah, there has been an improvement suggestion. Sure we can change that. (Doing that now)

I wanted a script to create that ranges string ;)

About the `:w` ... what? Some `less` lover should tell me what to put up in the Wiki  ;-)

**Comment by Finii** [comment]
Using `-R` now instead of `-r` which does virtually the same but has no capital letters ;-D

<img width="965" alt="Screenshot 2024-11-20 at 11 43 42" src="https://github.com/user-attachments/assets/2d885f88-d0ad-47c7-be74-162329d656ff">

**Comment by Finii** [comment]
@powerman I must admit I do not want to dig any further into one application's problem with just displaying text. I understand their intention etc pp, but them, how often would anyone be affected by it irl? I certainly NEVER. `less`-ing a file that has color sequences in it and expecting the paging to be completely flawless? Grunt. 🤷‍♀️ 

So, please `less` experts, come up with a text that suits you all and I will paste it 😀

**Comment by powerman** [comment]
Sure, no problem!

Current wiki says:

> You can use the LESSUTFCHARDEF environment variable to specify the code points for PUA characters. This can be done as follows:
> LESSUTFCHARDEF=23fb-23fe:w,2665:w,2b58:w,e000-e00a:w,e0a0-e0a3:p,e0b0-e0bf:p,e0c0-e0c8:w,e0ca:w,e0cc-e0d7:w,e200-e2a9:w,e300-e3e3:w,e5fa-e6b5:w,e700-e7c5:w,ea60-ec1e:w,ed00-efce:w,f000-f2ff:w,f300-f375:w,f400-f533:w,f0001-f1af0:w
> Note that the ranges might get out of sync over time. To avoid constantly updating ranges you can just use this more clunky approach:

I propose to change in this way:

```diff
 You can use the LESSUTFCHARDEF environment variable to specify the code points for PUA characters. This can be done as follows:
+# If you're using non-Mono version of Nerd fonts:
 LESSUTFCHARDEF=23fb-23fe:w,2665:w,2b58:w,e000-e00a:w,e0a0-e0a3:p,e0b0-e0bf:p,e0c0-e0c8:w,e0ca:w,e0cc-e0d7:w,e200-e2a9:w,e300-e3e3:w,e5fa-e6b5:w,e700-e7c5:w,ea60-ec1e:w,ed00-efce:w,f000-f2ff:w,f300-f375:w,f400-f533:w,f0001-f1af0:w
+# If you're using Mono version of Nerd fonts:
+LESSUTFCHARDEF=23fb-23fe:p,2665:p,2b58:p,e000-e00a:p,e0a0-e0a3:p,e0b0-e0bf:p,e0c0-e0c8:p,e0ca:p,e0cc-e0d7:p,e200-e2a9:p,e300-e3e3:p,e5fa-e6b5:p,e700-e7c5:p,ea60-ec1e:p,ed00-efce:p,f000-f2ff:p,f300-f375:p,f400-f533:p,f0001-f1af0:p
 Note that the ranges might get out of sync over time. To avoid constantly updating ranges you can just use this more clunky approach:
```

**Comment by Finii** [comment]
Btw, the ranges are out of sync already anhow, because we added codepoints.

I did not want to put much time into this, I dont have time 😭 

But as I see this:

```
e200-e2a9:w,e300-e3e3:w,e5fa-e6b5:w,e700-e7c5:w,ea60-ec1e:w
```

WHY do we need to be so accurate?
I would just set all PUA and PUA-A as `:w` or `:p`, and if it's empty it's empty.
That makes the line much more readable and still correct enough and we can add two lines, one for mono and one for non-mono.... ?

**Comment by Finii** [comment]
```
LESSUTFCHARDEF=23fb-23fe:p,2665:p,2b58:p
```

Are these really needed, that are ordinary glyphs which do not have ambiguous width according to unicode, iirc.
This whole issue is extremely annoying. I would raise an Issue at less.

Anyhow applying your suggestion.

**Comment by powerman** [comment]
> WHY do we need to be so accurate?

You may be right and we don't need this.

Some ranges needs special attention because they're still single-width even in non-Mono version of fonts: `e0a0-e0a3` and `e0b0-e0bf`. All other ranges may be combined in fewer larger ranges.

**Comment by Finii** [comment]
Here we see which are 1 and which 2 cells (if 2 cells are allowed):

```python
        SYM_ATTR_POWERLINE = {
            'default': {'align': 'c', 'valign': 'c', 'stretch': '^pa', 'params': {}},

            # Arrow tips
            0xe0b0: {'align': 'l', 'valign': 'c', 'stretch': '^xy', 'params': {'overlap': 0.06, 'xy-ratio': 0.7}},
            0xe0b1: {'align': 'l', 'valign': 'c', 'stretch': '^xy', 'params': {'xy-ratio': 0.7}},
            0xe0b2: {'align': 'r', 'valign': 'c', 'stretch': '^xy', 'params': {'overlap': 0.06, 'xy-ratio': 0.7}},
            0xe0b3: {'align': 'r', 'valign': 'c', 'stretch': '^xy', 'params': {'xy-ratio': 0.7}},

            # Inverse arrow tips
            0xe0d6: {'align': 'l', 'valign': 'c', 'stretch': '^xy', 'params': {'overlap': 0.05, 'xy-ratio': 0.7}},
            0xe0d7: {'align': 'r', 'valign': 'c', 'stretch': '^xy', 'params': {'overlap': 0.05, 'xy-ratio': 0.7}},

            # Rounded arcs
            0xe0b4: {'align': 'l', 'valign': 'c', 'stretch': '^xy', 'params': {'overlap': 0.06, 'xy-ratio': 0.59}},
            0xe0b5: {'align': 'l', 'valign': 'c', 'stretch': '^xy', 'params': {'xy-ratio': 0.5}},
            0xe0b6: {'align': 'r', 'valign': 'c', 'stretch': '^xy', 'params': {'overlap': 0.06, 'xy-ratio': 0.59}},
            0xe0b7: {'align': 'r', 'valign': 'c', 'stretch': '^xy', 'params': {'xy-ratio': 0.5}},

            # Bottom Triangles
            0xe0b8: {'align': 'l', 'valign': 'c', 'stretch': '^xy', 'params': {'overlap': 0.02}},
            0xe0b9: {'align': 'l', 'valign': 'c', 'stretch': '^xy', 'params': {}},
            0xe0ba: {'align': 'r', 'valign': 'c', 'stretch': '^xy', 'params': {'overlap': 0.02}},
            0xe0bb: {'align': 'r', 'valign': 'c', 'stretch': '^xy', 'params': {}},

            # Top Triangles
            0xe0bc: {'align': 'l', 'valign': 'c', 'stretch': '^xy', 'params': {'overlap': 0.02}},
            0xe0bd: {'align': 'l', 'valign': 'c', 'stretch': '^xy', 'params': {}},
            0xe0be: {'align': 'r', 'valign': 'c', 'stretch': '^xy', 'params': {'overlap': 0.02}},
            0xe0bf: {'align': 'r', 'valign': 'c', 'stretch': '^xy', 'params': {}},

            # Flames
            0xe0c0: {'align': 'l', 'valign': 'c', 'stretch': '^xy2', 'params': {'overlap': 0.01}},
            0xe0c1: {'align': 'l', 'valign': 'c', 'stretch': '^xy2', 'params': {}},
            0xe0c2: {'align': 'r', 'valign': 'c', 'stretch': '^xy2', 'params': {'overlap': 0.01}},
            0xe0c3: {'align': 'r', 'valign': 'c', 'stretch': '^xy2', 'params': {}},

            # Small squares
            0xe0c4: {'align': 'l', 'valign': 'c', 'stretch': '^xy2', 'params': {'overlap': -0.03, 'xy-ratio': 0.86}},
            0xe0c5: {'align': 'r', 'valign': 'c', 'stretch': '^xy2', 'params': {'overlap': -0.03, 'xy-ratio': 0.86}},

            # Bigger squares
            0xe0c6: {'align': 'l', 'valign': 'c', 'stretch': '^xy2', 'params': {'overlap': -0.03, 'xy-ratio': 0.78}},
            0xe0c7: {'align': 'r', 'valign': 'c', 'stretch': '^xy2', 'params': {'overlap': -0.03, 'xy-ratio': 0.78}},

            # Waveform
            0xe0c8: {'align': 'l', 'valign': 'c', 'stretch': '^xy2', 'params': {'overlap': 0.01}},
            0xe0ca: {'align': 'r', 'valign': 'c', 'stretch': '^xy2', 'params': {'overlap': 0.01}},

            # Hexagons
            0xe0cc: {'align': 'l', 'valign': 'c', 'stretch': '^xy2', 'params': {'overlap': 0.02, 'xy-ratio': 0.85}},
            0xe0cd: {'align': 'l', 'valign': 'c', 'stretch': '^xy2', 'params': {'xy-ratio': 0.865}},

            # Legos
            0xe0ce: {'align': 'l', 'valign': 'c', 'stretch': '^pa', 'params': {}},
            0xe0cf: {'align': 'c', 'valign': 'c', 'stretch': '^pa', 'params': {}},
            0xe0d0: {'align': 'l', 'valign': 'c', 'stretch': '^pa', 'params': {}},
            0xe0d1: {'align': 'l', 'valign': 'c', 'stretch': '^pa', 'params': {}},

            # Top and bottom trapezoid
            0xe0d2: {'align': 'l', 'valign': 'c', 'stretch': '^xy', 'params': {'overlap': 0.02, 'xy-ratio': 0.7}},
            0xe0d4: {'align': 'r', 'valign': 'c', 'stretch': '^xy', 'params': {'overlap': 0.02, 'xy-ratio': 0.7}}
        }
```
_Two cell wide glyphs have a `2` in `stretch`_

**Comment by powerman** [comment]
It's worth to note it's not just a less-only issue. E.g. for vim/neovim we also needs to define ranges for wide glyphs if we're using non-Mono font versions:

https://github.com/powerman/config.nvim/blob/c60bd4039ebb3ec6adb84b86dcc7163c6316b574/lua/nerd-fonts.lua#L6-L27

If some of these ranges can be combined or extended to became more future-proof then it would be nice to have a list of such "future-safe" ranges somewhere in Nerd Font docs.

**Comment by Finii** [comment]
PUA: `E000` - `F8FF`
PUAA: `F0000` - `FFFFF`

Powerline always just 1 cell:
`E0B0` - `E0BF` and `E0D2` - `E0D4`

Ignoring the inverse triangles:

```
LESSUTFCHARDEF=e000-e0af:w,e0a0-e0bf:p,e0c0-e8ff:w,f0001-fffff:w
```

**Comment by Finii** [comment]
Ah, yes, they are just default handled. Hmm, but the default rule is `pa` 🤔 
Need to understand my code, hold on ;)

💭 And how `less`s files with Powerline symbols in them

**Comment by powerman** [comment]
And what about `23fb-23fe,2665,2b58`? They're double-width in non-Mono.

**Comment by Finii** [comment]
What about a font that is not Nerd Font patched and has them inside already? It's not that they are uncommon in normal fonts.

BTW, all glyphs are one cell wide only, expect for the Nerd Font Propo font, so I believe this is moot, we should set `:p` everywhere.

**Comment by powerman** [comment]
> expect for the Nerd Font Propo font

Yeah, that's exactly one I'm using. :smile: 

```
URxvt*font:             xft:D2CodingLigature Nerd Font Propo:style=Regular:size=24,xft:Segoe UI Symbol,xft:Symbola
URxvt*boldFont:         xft:D2CodingLigature Nerd Font Propo:style=Bold:size=24,xft:Segoe UI Symbol,xft:Symbola
```

**Comment by powerman** [comment]
Maybe "Mono/non-Mono" should be corrected to "Propo", not sure.

**Comment by Finii** [comment]
```
LESSUTFCHARDEF=e000-e8ff:p,f0001-fffff:p
```

For `Nerd Font` and `Nerd Font Mono`; `Nerd Font Propo` has individual width anyhow so this makes no sense anyhow: There is no cell grid anymore, so one or two width is not applicable.

**Comment by Finii** [comment]
I must admit, what is the difference between setting `:p` (printable) and `:w` (wide character 2 space) anyhow?

I believe even for a Propo font it must be 'p', because it is one character, where character count is handled by `less`. How wide the glyph is is solved by the terminal emulator and has nothing to do with the number of characters.

So I guess you, with Propo font, still get perfect (for some definition of perfect) results when printable is used.

Need to research what wide means and does.

**Comment by Finii** [comment]
https://github.com/gwsw/less/issues/275

<img width="965" alt="Screenshot 2024-11-20 at 12 40 43" src="https://github.com/user-attachments/assets/68098b6c-28a6-48ec-ba28-59b03208645b">

This is not true, to my knowledge. PUA code may NOT be control characters, they are always ordinary glyphs.
And they are always one-character codepoints.

So from a `less` point of view it is `p`.

In a proportional font you might use `w` (2 "cells" wide), but in reality there is no concept of a cell in proportional fonts. That illusion is created by the terminal emulator. And how that handles 'ambiguous width' characters with respect to advance width is depending on IT. For example I believe Windows Terminal will just shrink the glyph down into what it believes is one cell.

**Comment by powerman** [comment]
Terminal:
![image](https://github.com/user-attachments/assets/3ecfbf93-f612-4f99-bb38-448b56b692b2)
Less with "large" (a lot of ranges) `LESSUTFCHARDEF`:
![image](https://github.com/user-attachments/assets/a6ec293e-ed8b-4f65-9786-e9ffaf00abe2)
![image](https://github.com/user-attachments/assets/617cfe88-2344-4c07-a09e-749ff22f9fdd)
Less without `LESSUTFCHARDEF`:
![image](https://github.com/user-attachments/assets/b6df3ef4-960f-4855-a987-ebe037683b1e)
Less with `LESSUTFCHARDEF=e000-e8ff:p,f0001-fffff:p`:
![image](https://github.com/user-attachments/assets/8a96ba51-fd66-4ec2-81be-d47003b454b9)

So, yeah, looks like these lower ranges are handled correctly by default.

My `unicode-symbols.txt` file was created a long time ago so it may contains some outdated ranges, but there are some ranges which does not work with `LESSUTFCHARDEF=e000-e8ff:p,f0001-fffff:p`:
```
<U+EA60> nf-cod-add; ea60
<U+EA61> nf-cod-lightbulb; ea61
...
<U+EC1D> nf-cod-git_fetch; ec1d
<U+EC1E> nf-cod-copilot; ec1e

<U+ED00> nf-fa-location_dot; ed00
<U+ED01> nf-fa-medapps; ed01
...
<U+F2FE> nf-fa-poo; f2fe
<U+F2FF> nf-fa-magento; f2ff

<U+F300> nf-linux-alpine; f300
<U+F301> nf-linux-aosc; f301
...
<U+F374> nf-linux-postmarketos; f374
<U+F375> nf-linux-qt; f375

<U+F400> nf-oct-light_bulb; f400
<U+F401> nf-oct-repo; f401
...
<U+F532> nf-oct-zoom_out; f532
<U+F533> nf-oct-bookmark_slash; f533
```

**Comment by Finii** [comment]
Added a comment in the aforementioned Issue at `less`.

Thank you for testing. But what you test is just your terminal emulator and not less at all, right?

<img width="438" alt="Screenshot 2024-11-20 at 13 12 51" src="https://github.com/user-attachments/assets/a8e1e335-ab4b-4504-a673-958a5e731462">

How much the cursor advances after `2665` for example has nothing to do at all with `less` and it's setting, that is a terminal emulator decision and less does only need to know/decide if the line is cut off on the right or something.

So the difference between `p` and `w` is not how the glyph is rendered (that does your terminal and `less` has no power to change any of that), but only what less thinks on which cell coordinate the cursor is after outputting the characters, for purposes of correctly paging.

**Comment by Finii** [comment]
I will already add you as contributor 💚 This is not to silence you ;)
Thank your for all the input / dialogue.

**Comment by Finii** [comment]
@allcontributors please add @powerman for doc

**Comment by Finii** [comment]
Oh :-D

**Comment by Finii** [comment]
<img width="974" alt="Screenshot 2024-11-20 at 13 39 15" src="https://github.com/user-attachments/assets/04c0f531-15f2-43f7-bbeb-fc6896251d5e">

**Comment by Finii** [comment]
🤦‍♀️ 

Whatever, correcting, tnx

**Comment by Finii** [comment]
<img width="974" alt="Screenshot 2024-11-20 at 13 44 27" src="https://github.com/user-attachments/assets/50290e51-effb-4539-8e4e-4b400062b567">

**Comment by Finii** [comment]
/spent 3h

Wah, this is not Gitlab ;)

**Comment by powerman** [comment]
Sorry about this! :)

I'm a bit afraid to saying so, but to me it looks like your latest version (one with `:w`) should include these too: `23fb-23fe:w,2665:w,2b58:w`.

Thanks!!!

P.S. Probably I'll have to update ranges in https://github.com/powerman/wcwidth-icons this way too.

**Comment by Finii** [comment]
This whole issue that `less` creates in so ridiculous...

WHY is it assuming `2665` is single width, when unicode says it's ambiguous?
For the PUA they said: Its ambiguous width, so we can not display it.

And then, why not assuming `E000` to be single width, as it does with `2667`

<img width="511" alt="Screenshot 2024-11-20 at 15 32 09" src="https://github.com/user-attachments/assets/69fed616-797b-4573-b663-cbaf67a3f849">

**Comment by nikelborm** [comment]
> ```shell
> export LESSUTFBINFMT='*n%C'
> ```

For the PUA they said: Its ambiguous width, so we can not display it.
Just curious about what effect LESSUTFBINFMT here does?

**Comment by Finii** [comment]
I would assume ...
```
*     I have no clue
n     normal (not bold or whatnot)
%C    just use the char itself
```

@powerman They themselves suggest to set what we do:

<img width="1441" alt="Screenshot 2024-11-20 at 16 14 34" src="https://github.com/user-attachments/assets/54b3f3e2-113c-4380-89e0-7bcae4e1599f">

**Comment by nikelborm** [comment]
I've read the doc, I mean practically does it help to render character beutefully? It helped for in all of such cases where I've seen this `<U+E000>` kind of rendering them, because `*n%C` should render all characters as is

**Comment by Finii** [comment]
"Beautifully"? Well, that is all just about enabling `less` to know how long one line is, to cut it off at the right place.

It has nothing to do with how the glyphs are rendered/placed by the terminal. `less` can not influence that.

Now the question is what you mean by beauty ;)

**Comment by nikelborm** [comment]
> "Beautifully"? Well, that is all just about enabling `less` to know how long one line is, to cut it off at the right place.
> 
> It has nothing to do with how the glyphs are rendered/placed by the terminal. `less` can not influence that.
> 
> Now the question is what you mean by beauty ;)

Sorry I'm not a native speaker. I don't know how to say it in other words. It's the less's job to give to the terminal the character. And if less sees some character which is no whitelisted it prints it as sequence of ascii characters representing the hex of the initial charcter. I mean that `<U+E000>` is ugly and whatever symbol was behind is beatifull.

**Comment by Finii** [comment]
This is why `less` wants to know how wide the character is rendered by the terminal...

```
$ cd git/nerd-fonts
$ less -S font-patcher
```

<img width="589" alt="Screenshot 2024-11-20 at 16 27 39" src="https://github.com/user-attachments/assets/31ac3941-7197-40fa-bdb3-2fefed41f824">

_Less cutting off long lines, needs to knpow how wide each char is rendered_

**Comment by nikelborm** [comment]
> ```shell
> export LESSUTFBINFMT='*n%C'
> ```

Setting this variable at least gives the terminal the chance to decide if it can render it. In other case the terminal emulator (?) (GUI program) just gets sequence of ascii characters

And basically I'm asking if you set this vat, will your terminal be able to render the character or is it just breaks?

**Comment by Finii** [comment]
> And basically I'm asking if you set this var, will your terminal be able to render the character or is it just breaks?

Well, your terminal can render what it can. `less` does not know nor can it change that behaviour. So setting the variable does not change the terminal's capabilities.
With the variable un-set `less` just "protects" the user from strange line-endings by not outputting whole ranges of characters.

If you set this `*p%C` it should pass all characters unchanged, and not change them to the "user friendly" (or not) hexdump format that noone wants. If the terminal can display it depends on your terminal and used font.

**Comment by powerman** [comment]
> how wide the terminal renders a glyph (which it also can not ask for

At a glance - `less` can ask for it: using [wcwidth(3)](https://www.man7.org/linux/man-pages/man3/wcwidth.3.html). The correctness of result will depends, of course, but it's anyway better to fix such a response in a single place than fix it for each individual app like `less` or `vim` which decide to not use this API.

**Comment by Finii** [comment]
But it can not ask the terminal, and that is free to render them as it likes. 🤷‍♀️ 

All these problems do not occur if you use `Nerd Font` or `Nerd Font Mono`, the fonts designed for terminal uses, that utilize additional blanks for rendering purposes, that the typical applications all understand. `Nerd Font Propo` is a new addition and intended to use in proportional contexts like GUI elements etc.

**Comment by powerman** [comment]
> All these problems do not occur if you use `Nerd Font` or `Nerd Font Mono`

These fonts has much more critical issue: too small icons, all using just 1 cell! :cry: Small enough to be hardly usable at all - at least for people with less than perfect vision.

**Comment by Finii** [comment]
Hmm, `Nerd Font` and `Nerd Font Propo` has the icon in the exact same size.

Only `Nerd Font Mono` scales them down into one cell.

🤷‍♀️ 

Maybe have a look at #1103, but then, you know that already I guess.

**Comment by powerman** [comment]
Ahh, I see. Thanks for the explanation!

TBH, I don't think this will change anything, to me at least. Having to add extra space after an icon always feels like a bug to me. It turns out to be a feature… well, it happens. :smile: These extra spaces really creates issues with a lot of tools: they might insert an unwanted line wraps after an icon, they might show only left half of an icon if it happens to start at last cell, and probably worst of these is icon is often not in the middle of a word but at the end or is a separate "word" which leads to having 2 spaces after an icons which many tools will "fix" by removing 2nd "extra" space.

So, to me it looks like only real way to solve these issues is to use Propo fonts, use `LD_PRELOAD=/path/to/libwcwidth-icons.so` to ensure most apps (including terminal) will know all icons a 2-cell wide, plus additionally configure (or patch) few "too clever" apps like `less` or `vim` which are hardcode their own lists of wide codepoints instead of using `wcwidth(3)` API. This may feels like a "hacks", but I'd prefer to have such a 2-3 hacks in my whole OS+apps setup than "extra space after each icon" hack **in each text file**, shell prompt configuration, etc.
