### ISSUE TITLE
Ubuntu Mono missing Bold and Italic versions

### ISSUE THREAD

**Issue by dan-santana** [ryanoasis/nerd-fonts#134]
Currently only the patched `Ubuntu Mono Regular` is provived by this repository, missing the Bold, Italic and Bold+Italic versions of it.

**Comment by ryanoasis** [comment]
Going to upgrade Ubuntu fonts to version from `0.80` to `0.83` and add the missing ones (non mono) from here: http://font.ubuntu.com/
