### ISSUE TITLE
CaskaydiaCove Nerd Font Mono adds ligatures

### ISSUE THREAD

**Issue by portus-zephyr** [ryanoasis/nerd-fonts#1341]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
CaskaydiaCove Nerd Font Mono adds ligatures

Expected behavior:
CaskaydiaCove Nerd Font Mono should not have ligatures

should be the same as in https://github.com/microsoft/cascadia-code
> Cascadia Mono: a version of Cascadia that doesn't have ligatures

Example symbols:
```
===> 
```

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - `CaskaydiaCoveNerdFontMono-Regular.ttf`
   - `CaskaydiaCoveNerdFontMono-Bold.ttf`
   - `CaskaydiaCoveNerdFontMono-BoldItalic.ttf`
   - `CaskaydiaCoveNerdFontMono-ExtraLight.ttf`
   - `CaskaydiaCoveNerdFontMono-ExtraLightItalic.ttf`
   - `CaskaydiaCoveNerdFontMono-Italic.ttf`
   - `CaskaydiaCoveNerdFontMono-Light.ttf`
   - `CaskaydiaCoveNerdFontMono-LightItalic.ttf`
   - `CaskaydiaCoveNerdFontMono-SemiBold.ttf`
   - `CaskaydiaCoveNerdFontMono-SemiBoldItalic.ttf`
   - `CaskaydiaCoveNerdFontMono-SemiLight.ttf`
   - `CaskaydiaCoveNerdFontMono-SemiLightItalic.ttf`
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/CascadiaCode.zip
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   -  EndeovorOS

#### ★ Screenshots (Optional)
![image](https://github.com/ryanoasis/nerd-fonts/assets/66728045/6e067d6b-3555-47b0-a627-33435cc1610d)

**Comment by Finii** [comment]
I am not sure, but I guess you expect `CaskaydiaCove Nerd Font Mono` to be like `Cascadia Mono`.

(What you say is: CaskaydiaCove Nerd Font Mono should not have ligatures, should be the same as in https://github.com/microsoft/cascadia-code.)

I guess that is a misunderstanding. The `Mono` in `Nerd Font Mono` is not from `Cascadia Mono` but specifies a Nerd Fonts variant that might have ligatures.

If you are after a Nerd Font variant of `Cascadia Mono` that would be called `CaskaydiaMono Nerd Font Mono` (depending on what you want). Note the two `Mono`s and that they specify different things.

Please reopen if you mean something else.


P.S. A prepatched version of `Cascadia Mono` is available as `Delugia Mono`, but I had no time unfortunately to update that.
