### ISSUE TITLE
Icons suddenly shrunk with no changes to configs

### ISSUE THREAD

**Issue by JetpackJackson** [ryanoasis/nerd-fonts#1343]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
> the section there did not apply to me, as the fonts were working and now they are not
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
For a few days, I noticed a strange issue with my Firefox icon in my sway-launcher-desktop, it changes when the cursor selects it (see video, it also shows the second issue). However, now many of the icons are shrunk in size with no changes in regards to my setup or updates. I tried reinstalling and rebuilding the font cache, but it didn't help.
In addition, new entries in my history file have an extra space inbetween the default icon and the name of the application.

Expected behavior:
Icons are not shrunk.

Example symbols:
history file:
263 /usr/share/applications/discord-ptb.desktopdesktop󰙯 Discord PTB
197 /usr/share/applications/librewolf.desktopdesktop LibreWolf
35 /usr/share/applications/syncthing-gtk.desktopdesktop Syncthing GTK
32 /usr/share/applications/libreoffice-startcenter.desktopdesktop󰏢 LibreOffice
30 /usr/share/applications/obsidian.desktopdesktop󰛓 Obsidian
14 /usr/share/applications/com.github.xournalpp.xournalpp.desktopdesktop Xournal++
12 /usr/local/share/applications/anki.desktopdesktop Anki
11 /usr/share/applications/schildichat-desktop.desktopdesktop󰴻 SchildiChat
6 /usr/share/applications/google-chrome.desktopdesktop Google Chrome
6 /usr/share/applications/codium-wayland.desktopdesktop󰘐 VSCodium - Wayland
3 /usr/share/applications/nvim.desktopdesktop Neovim
2 /usr/share/applications/org.musicbrainz.Picard.desktopdesktop  MusicBrainz Picard
2 /usr/share/applications/lmms.desktopdesktop󰎈 LMMS
2 /usr/share/applications/audacity.desktopdesktop󰎄 Audacity
1 /usr/share/applications/org.qbittorrent.qBittorrent.desktopdesktop qBittorrent
1 /usr/share/applications/gimp.desktopdesktop󱇣 GNU Image Manipulation Program
1 /usr/share/applications/digilent.waveforms.desktopdesktop󰥛 Digilent Waveforms
1 /home/jet/.local/share/applications/wine/Programs/LTspice/LTspice.desktopdesktop  LTspice

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - /home/jet/.local/share/fonts/ArzteSans-MonoRoman.ttf: Ärzte Sans,Ärzte Sans Mono Roman:style=Mono Roman,Regular
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - I got the mono font from the Die Ärzte website, bademeister.com, but I've never had an issue with the icons before.
   - Pacman repositories (ttf-nerd-fonts-symbols and ttf-nerd-fonts-symbols-common)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Arch Linux, SwayWM

#### ★ Screenshots (Optional)

https://github.com/ryanoasis/nerd-fonts/assets/88674707/04a01696-a0a4-45de-94f3-7601b6b904cc

![fontsmall](https://github.com/ryanoasis/nerd-fonts/assets/88674707/1dcea5cf-e148-4f58-977b-97c1047a132c)

**Comment by Finii** [comment]
Hmm, it seems that all 'normal' icons are in the 4-hex-digits range while the small ones are in `Fxxxx` (5 digits) range:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/7f68630d-d225-424e-95d9-a19d513f4c46)

Hmm, no, that is not entirely true. :thinking: 

I'm not sure how your font setup is, but I guess you have this ArzteSans as selected font and get in the Nerd Fonts via fontfallback from SymbolsOnly, right?

From the screenshot with the `fs-list` output I see that you have installed both / maybe all,
* `Symbols 2048em` **and** `Symbols Only 1000em` (a)
* `Symbols Nerd Font Complete` **and** `Symbols Nerd Font Complete Mono` (b)

(a)
You should settle on one of them. Usually 2048em. There can be no reason to have both installed that I can think of. I can not think of any reason to install the 1000em variant at all ;-D

(b)
The `Nerd Font` icons are wide, while the `Nerd Font Mono` icons are small.
If you do not specify the font to use fontconfig will choose any font for you that has the requested glyph. So it will be randomly select small or wide icons to replace missing-in-ArzteSans glyps.
Suggest: Remove the variant you do not want.

Please report back if removing 3 of the 4 Symbols Only fonts helps you ;-)

**Comment by Finii** [comment]
You can check which font can provide a concrete icon like this:

`fc-list :charset=f066f` (discord, "small" in your screenshot)
`fc-list :charset=f268` (chrome, "big" in your screenshot)

The list should come up with just one (1) font or you will have an ambiguity when that icon is requested via fontfallback.
And/or you need rules in your fontconfig, but people seldom have these.

**Comment by Finii** [comment]
Maybe look into https://github.com/kovidgoyal/kitty/issues/3591

**Comment by JetpackJackson** [comment]
Ah ok! I'm not at my computer right now, but I did remove some of those symbol fonts a few weeks ago (I was cleaning up fonts from when I was installing everything to see what it looked like lol). I did also notice that a few days ago many of the icons returned to normal. My other laptop doesn't seem to have this issue, so I'll check the font stuff and get back to you.

**Comment by JetpackJackson** [comment]
So I had only one of the symbol fonts, but I also found that I had the ttf-nerd-fonts-symbols package installed, so that is also probably another point of conflict.

**Comment by Finii** [comment]
Closed due to inactivity.
