### ISSUE TITLE
Add Fira Code's progress bars and spinner. 

### ISSUE THREAD

**Issue by oshaboy** [ryanoasis/nerd-fonts#1345]
**Requirements**

- [*] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [*] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [*] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
It's not a problem it's a request for more symbols from Fira Code.

**Describe the solution you'd like**
I would like the Fira Code progress bar and spinner to be added to the font. 

**Describe alternatives you've considered**
The only fonts I know that support Fira Code's progress bar and spinner are Fira Code and Iosevka. 

**Additional context**
![](https://raw.githubusercontent.com/tonsky/FiraCode/master/extras/progress.png)

Fira Code added glyphs for a progress bar and spinner in the PUA. Not much software support for them is out there. It feels like they should be glyphs in nerd fonts but they aren't.

**Comment by oshaboy** [comment]
Shouldn't this be added to #1095. I didn't know about that thread when I made this issue

**Comment by mikesmithgh** [comment]
Hey 👋, this is really nice. I am using Fira Code Nerd Font `v3.1.0` and can see the spinners.

I modified `test-fonts.sh` locally for expirementing.

```sh
	echo "Nerd Fonts - Fira"
	print-unicode-ranges ee00 ee0b ee10 ee15
	echo
	echo
```
![fira-nerd-fonts](https://github.com/ryanoasis/nerd-fonts/assets/10135646/b9cae492-4462-40f0-9be8-11c4e82a935e)

I have a question around what this ticket actually means for implementation.

1. Since I can see the symbols, does this mean that this is already implemented in `v3.1.0` ?
or
2. Will this add these symbols be patched to all Nerd Fonts and maybe use another private-use unicode area?

**Comment by Finii** [comment]
Type `fc-list :charst=ee00` and see where the icons come from. Nerd Font does not patch in anything at `EE00`, see https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points#overview

The spinners are originally in Fira (so if you use Fira or a patched version of it) they are there.
This Issue aims to steam them from Fira and put them in all fonts.

**Comment by oshaboy** [comment]
Yeah a lot of terminals if you don't have characters in the default font it tries fallback fonts.

**Comment by mikesmithgh** [comment]
> Type `fc-list :charst=ee00` and see where the icons come from. Nerd Font does not patch in anything at `EE00`, see https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points#overview
> 
> The spinners are originally in Fira (so if you use Fira or a patched version of it they are there). This Issue aims to ~steam~ _steal_ them from Fira and put them in all fonts.

Thanks! 

```
fc-list ':charset=ee00' | grep Fira
/Users/mike/Library/Fonts/FiraCodeNerdFont-Regular.ttf: FiraCode Nerd Font:style=Regular
```

That makes sense, I am using Kitty and explicitly setting the [symbol_map](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.symbol_map) to `FiraCode Nerd Font`

I got excited when I saw these and didn't realize they were Fira exclusive. I look forward to you ~~steaming~~ stealing them 🙂

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
