### ISSUE TITLE
Hermit font is misspelled as Hurmit

### ISSUE THREAD

**Issue by Cpt0r** [ryanoasis/nerd-fonts#135]
As per title.  Minor thing but thought I'd mention it.

**Comment by ryanoasis** [comment]
@Cpt0r Thanks but this is actually on purpose and not an issue. :smile: 

For more info why see: https://github.com/ryanoasis/nerd-fonts/pull/131#issuecomment-280954653

---

I will create an issue to make name changes clearer

**Comment by Cpt0r** [comment]
Ah righto, yea I searched for possible related issues but found nothing.

**Comment by ryanoasis** [comment]
No worries @Cpt0r I am creating the issue right now! You are not the only one confused :wink:
