### ISSUE TITLE
nf-oct-markdown (\uf48a) icon problem

### ISSUE THREAD

**Issue by jonahfang** [ryanoasis/nerd-fonts#1352]
#### 🗹 Requirements

nf-oct-markdown (\uf48a) should work after install https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Hack.zip

#### 🎯 Subject of the issue

Experienced behavior:
I use iTerm2 (v3.5.0beta11) with macOS Monterry, and installed v3.0.2 Hack Nerd Font.
The nf-oct-markdown (\uf48a) icon does not show:
<img width="568" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/16301509/fcd8e182-28c6-448d-b6a4-51ed992f09af">

Expected behavior:
The above icon should work.

**Comment by Finii** [comment]
Hmm, although this is not Hack but Lilix, it works and I can not reproduce

<img width="397" alt="Screenshot 2023-09-22 at 16 37 16" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/45fa93ad-5861-448e-b079-2a8b253d3144">

But I have 3.14.19. Maybe a problem of the beta? Looks so when some icons work and other not.
Can you reproduce with the non-beta?

**Comment by Finii** [comment]
To make sure this is not a iTerm2 oddity, can you reproduce the error with the ordinary Terminal?

**Comment by jonahfang** [comment]
I tested it with version 3.14.19 of iTerm2, the icon shows ok.

**Comment by Finii** [comment]
But then it seems more like a problem of the iTerm beta and not the font itself, right?
Maybe you should raise an Issue over there.
Suggest linking this issue to the report there.
