### ISSUE TITLE
Copying the icon of `nf-cod-code` makes editors crash.

### ISSUE THREAD

**Issue by aspizu** [ryanoasis/nerd-fonts#1353]
1. Copy `nf-cod-code` from the website.
2. Paste into Helix editor.

Crash also happened when pasting in Discord.

**Comment by Finii** [comment]
But it is not out fault when some editors are not unicode-ready?
At least the content of the paste-buffer looks correct when I click here:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/4753e12a-e31e-4407-ae84-02b7f84409de)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/85fd74ad-618d-4662-8589-f3cf91e57b74)
