### ISSUE TITLE
Add latest material icons

### ISSUE THREAD

**Issue by NoahAndrews** [ryanoasis/nerd-fonts#1354]
**Requirements**

This [alternative memory icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Amemory_alt%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) is the particular one I'm interested in, but it looks like Google added a lot of new ones in August.

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Comment by ojasaklechayt** [comment]
Can I try this under hacktoberfest 2023 ?

**Comment by UjjawalGu** [comment]
i can do this can you assign me this task

**Comment by Finii** [comment]
Thanks for suggesting the update. But what you reference is **Material Symbols** and what we patch in is **Material Icons**.
And you reference the Google fonts, while Nerd Fonts uses https://github.com/Templarian/MaterialDesign
In particular we base on https://github.com/Templarian/MaterialDesign-Font which has not been updated/changed relative to the version we use - but there is an open issue over there ...
