### ISSUE TITLE
Responsive Design Issue: div.subtlecircle Overflow on Small Screens (< 767px)

### ISSUE THREAD

**Issue by VitthalGund** [ryanoasis/nerd-fonts#1367]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
I have observed the **div.subtlecircle** element overflows out of its parent container below 767px width. This same problem also occurs in the Terminal Fonts Examples container, where the **div.subtlecircle** images overflow in the same manner as in the feature section. This is not good for smaller screen sizes less than 767px, which breaks the design of the website for devices with screen sizes less than 767px.

Expected behavior:
The rounded logo should be overflow for screen sizes less than 767px. This can be solved by applying and modifying the existing CSS on that page.

#### 🔧 Your Setup

- **Which terminal emulator are you using?**
   - Google Chrome

- **Which operating system are you using?**
   - Windows 11

I want to work on this issue, can assign it to me and also based on my observation the I am not able to find the appropriate CSS file to make changes, can get any kind of document which explain the structure, or it would be great if any explain comments only.

#### ★ Screenshots (Optional)

Experienced behavior:
![image](https://github.com/ryanoasis/nerd-fonts/assets/97181033/a2b08b07-2672-4a84-8751-f7436bdb0819)

Expected behavior:
![image](https://github.com/ryanoasis/nerd-fonts/assets/97181033/c59d8721-0b18-4957-826d-e86915b20b00)

**Comment by Finii** [comment]
Thanks for reporting the issue! I never noticed that.

Interestingly the other circle seems to be less broken:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/75d16e64-8b8c-46a7-b713-712b320c8c4e)

But then, the upper circle (with the icons) is even broken on wider widths: It is not centered within the pale turquoise backdrop

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ed638907-90d5-453c-819c-9ed80ab3da4a)

To work on this you need to check out the `gh-pages` branch. You can test any changes you did locally with `jekyll s` (see README.md in gh-pages branch). The `subtlecircle` is probably here ;-)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/97610346-af82-4dc5-a9d7-a2bcbc2edbb4)

The other circles behave different, but maybe more gracefull, when the widths gets small, for example

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/26e6c9e9-b50a-4b11-8ee9-bd074fb82c5f)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/145970ac-030f-4bbe-b4f9-65255ef4a08d)

**Comment by Finii** [comment]
I assume you want to work on this for Hacktoberfest? We do not do 'assignments' usually, is that needed for the fest?

**Comment by Finii** [comment]
Apart from the circle, there is more breaking when the width decreases, see https://github.com/ryanoasis/nerd-fonts/issues/1366#issuecomment-1746202861

**Comment by VitthalGund** [comment]
Hi @Finii,

Thank you for your response and for pointing out the related issue #1366. I appreciate your prompt attention to this matter.

Regarding the assignment aspect, you are correct; it's not typically our practice to assign issues. However, as we are participating in Hacktoberfest, I was simply looking for a way to contribute effectively during this event. If there's a preferred approach for Hacktoberfest contributions within the project, please do let me know so that I can align with the community's guidelines.

I will certainly take a look at issue #1366 to see if there's an opportunity to address the broader breaking issue you've mentioned. I believe it's essential to ensure a consistent user experience, especially on smaller screens.

If there are any specific instructions or additional details you'd like me to consider while working on this, please feel free to share. I'm here to contribute positively to the project and follow best practices.

Thank you for your guidance, and I look forward to making a meaningful contribution to the "nerd-fonts" project.

Best regards,
Vitthal Gund

**Comment by Finii** [comment]
Thank you @VitthalGund !

I guess we could also just drop the fork-me banner when it starts to be a problem. On very small sizes it is not shown anyhow.
And I believe serious work (i.e. forking) is not to be expected with small screen devices.

:thinking: 

I think whatever YOU feel is appropriate will be good :+1: I'm no web designer and have no strong opinions :-)

Also I always wondered if that banner is any good. Does not anybody know you can fork? And if not, why does it lead to the gh-pages branch instead to the default (master) branch?

**Comment by VitthalGund** [comment]
Hi @Finii,

Thank you for your feedback and your trust in my approach. I appreciate your insights, and I'm glad to have your support in addressing this issue.

Based on our discussion, here's the plan moving forward:

1. We will consider dropping the "Fork-me" banner and, in its place, add a 'Visit GitHub Repository' button just below the 'number of stars' and 'forks.' This will provide a more user-friendly way for visitors, including those on smaller screens, to easily find and access the repository.

2. We will ensure that this solution is implemented effectively to enhance the user experience.

3. Additionally, we will investigate and resolve any issues with the banner's link, whether it's a typo or a misconfiguration. We want to ensure that users are directed to the correct repository branch.

Once these changes are made, we can revisit the issue and confirm that it's been successfully resolved.


Best regards,
Vitthal Gund

**Comment by VitthalGund** [comment]
Hii @Finii,

As per our discussion, we initially considered adding the button just below the 'number of stars' and 'forks,' which would redirect the user to the GitHub repository. However, after implementing this change, I realized that it may not provide the best user experience.

The issue with placing the link in that location is that if a user scrolls down to other sections of the page and then decides to visit the GitHub repository, they would have to scroll back up to access the link. This could potentially be frustrating for users. In an effort to improve user-friendliness, it might be more effective to provide the link in a location that's easily accessible no matter where the user is on the page.

Regarding the question you raised about the link leading to the gh-pages branch instead of the default (master) branch, I've addressed that as well. As I suspected, it was likely a typo in the link. I've corrected this by using the following link: [https://github.com/ryanoasis/nerd-fonts/tree/master](https://github.com/ryanoasis/nerd-fonts/tree/master). This will ensure that users are directed to the master branch as expected.

### Here are the before and after screenshots of the implementation:
#### Before:
![image](https://github.com/ryanoasis/nerd-fonts/assets/97181033/81daeea8-8a9a-452c-b7a3-b0f4d8424230)

#### After:
![image](https://github.com/ryanoasis/nerd-fonts/assets/97181033/d68ef0b0-a264-4ed4-b36a-b3936df86e55)

I hope these changes align with your expectations and improve the overall user experience. If you have any further suggestions or feedback, please feel free to share. Your input is greatly appreciated!

Best regards,
Vitthal Gund

**Comment by Finii** [comment]
Fixed by #1368
