### ISSUE TITLE
Enhancing overall design of the website.

### ISSUE THREAD

**Issue by sarthak-star** [ryanoasis/nerd-fonts#1370]
**Requirements**
We need to enhance the design of the overall website.

I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
It is not a problem but a major need.

**Describe the solution you'd like**
I would like to add some hover effects and change some sizing and fonts to give the website a better look.

**Comment by Finii** [comment]
Thanks for the suggestion.
I do not feel comfortable with a complete redesign and believe small incremental improvements are better.
As there seem to be no big shortcomings.

If you have concrete suggestions; but in principle I believe the site is ok. Sorry.

**Comment by ryanoasis** [comment]
Hi! The website isn't great but functional and there were some nice improvements to the search performance I noticed a while back. 

I don't know if a full rewrite is worth the effort but up to hear different opinions. I threw something together with Jekyll which was at least not horrible to make updates over time. There are definitely a few bugs in the website layout (especially on mobile) I'd love to fix.

Cheers!
