### ISSUE TITLE
Enhance User Experience: Improve Access to GitHub Repository Link

### ISSUE THREAD

**Issue by VitthalGund** [ryanoasis/nerd-fonts#1372]
#### Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
As part of our discussion, we identified a user experience issue with the "Fork-me" banner on smaller screens. The banner becomes problematic, and accessing the GitHub repository can be inconvenient for users.

**Describe the solution(s) you'd like**
We propose two solutions to enhance the user experience:

1. **Solution 1**: Drop the "Fork-me" banner when it starts to be a problem on very small screens. Replace it with a 'Visit GitHub Repository' button just below the 'number of stars' and 'forks.' This will provide an easily accessible link for users, regardless of screen size.

2. **Solution 2**: Add a GitHub icon on the bottom left corner with some margin and padding. This icon will serve as a persistent and easily accessible link to the GitHub repository. Users can click the icon to visit the repository no matter where they are on the page, eliminating the need to scroll back up.

We are open to considering either solution based on community feedback and preferences.

**Additional context**
We also identified an issue with the link in the "Fork-me" banner leading to the gh-pages branch instead of the default (master) branch. This issue has been addressed and corrected with the following link: [https://github.com/ryanoasis/nerd-fonts/tree/master](https://github.com/ryanoasis/nerd-fonts/tree/master).

#### Before:
![image](https://github.com/ryanoasis/nerd-fonts/assets/97181033/81daeea8-8a9a-452c-b7a3-b0f4d8424230)

#### After:
![image](https://github.com/ryanoasis/nerd-fonts/assets/97181033/d68ef0b0-a264-4ed4-b36a-b3936df86e55)

Assign me this issue.

If you have any questions or need further information, please feel free to ask.

**Comment by Finii** [comment]
Both solutions look nice. And the tiny github cat is really cute! Much better than the diagonal banner.

But then it just allows an easy path to the github repo and does not say that we love to be forked.
On the other hand, I believe it is not necessary to say that.

As further input, I believe only very few people will ever follow that link, so it is maybe not needed to have it prominent and/or always accessible.

And the fork banner already allows to immediately fork:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/eae7873d-3035-4900-891b-480891738915)

**Comment by VitthalGund** [comment]
Hey,

I appreciate your feedback on both solutions. 
I believe the tiny GitHub cat icon is a subtle but effective way to provide access to the repository for contributors. It balances accessibility and user-friendliness.
May I proceed with the tiny GitHub cat icon as our solution?

Best regards,
Vitthal Gund

**Comment by Finii** [comment]
I would be grateful! 



________________________________

**Comment by VitthalGund** [comment]
Hey @Finii,

It seems I accidentally unassigned myself from the issue. My apologies for the oversight. I'm still actively working on it and would like to be reassigned.
Could you please reassign the issue to me? I appreciate your help with this.

Thank you.

**Comment by Finii** [comment]
Solved via #1373
