### ISSUE TITLE
Website tab-line scaling switch points

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#1375]
#### 🎯 Subject of the issue

On the website www.nerdfonts.com the tab bar has a strange behavior when the screen width changes...

When decreasing the width from 'very wide' at some point the tab bar will wrap to a second line, and with further width decrease it will switch to shorter tab-titles and the to a smaller font.

The switchover points seem to be wrong. Maybe they are font dependent?

Experienced behavior:

**full width**
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ee471b48-a5aa-4100-8604-18f106e13118)

**smaller wraps tab-line into second line**
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/437b9567-65cf-4d9f-a488-31f659f1497e)

**smaller wraps more**
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/7218282e-14cb-44e0-89a1-5e15fac81d47)

**smaller switches to short titles, but still to long**
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/43e5c35d-b243-4c07-91ec-1481bf986433)
 
**smaller, now a smaller font is used**
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ae883899-bf6f-4b66-9372-528312ad54aa)

**Comment by Ayush-gupta-dev** [comment]
I have gone through your readme.md file, and i would like to contribute in this repository, please assign this issue to me @Finii .

**Comment by Finii** [comment]
Assigned ;)
The website is in the `gh-pages` branch. You can check your changes locally by running `jekyll s` on your machine and pointing your browser to the URL given by jekyll

**Comment by Ayush-gupta-dev** [comment]
@Finii  confirming, in this image you basically want to display all short titles in one line?

![smaller switches to short titles, but still to long](https://github.com/ryanoasis/nerd-fonts/assets/137040550/76e5c1e9-1c29-4892-802d-acfef7b6c027)

**Comment by Finii** [comment]
Yes.

The tab line should be one line, always (as far as I think tab lines should work).

We have several switchover points.
Obviously the switchover points (depending on SCREEN width) do not match the actual font used or something.

Switching to short-tab-titles ("CHEAT CHEAT" -> "ICONS", etc) must come earlier (i.e. with wider widths already), to avoid two lined tab-line.

Switching to the smaller font also is too late.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/cdad36c6-7c8c-4a2a-b333-7bab1e2a9a0c)

In the upper image switch to the short titles should come when the tab-line starts to overflow. Now we overflow two items before it switches to short titles.

And then, the lower image: The tab lines is now too short already for short titles with big font, here it should already be short-titles small font.

**Comment by Ayush-gupta-dev** [comment]
okay i understood your problem, you basically want a better **responsive navbar** for your website.

There are bugs too in the navbar.

![this is a bug](https://github.com/ryanoasis/nerd-fonts/assets/137040550/07d95d02-4e18-4c90-97b9-876592bd10b4)

<img src="https://github.com/ryanoasis/nerd-fonts/assets/137040550/9562f664-5f9f-424b-a25e-cd2e1e605d2b" alt="Image Alt Text" width="200" >

### since links are lot  do you want me to add collapse navigation feature for smaller screens? @Finii

**Comment by Finii** [comment]
In fact we have these 'zoom levels':
```
/*
 super tiny size (phones)
 point at which nav wraps
 without decrease font size
 */
@media only screen and (max-width: 326px) {
}

/* tiny size (phones) */
@media only screen and (max-width: 380px) {
}

/* mid size (tablets, landscapes) */
@media only screen and (max-width: 679px) {
}

/* anything not desktop */
@media only screen and (max-width: 767px) {
}
```

Nav should only wrap at 'super tiny size', as commented.
I guess the pixel widths given here are just slightly off.

**Comment by Finii** [comment]
And this fixes the second switchover point

```diff
index 64f2c3814..4585a0066 100644
--- a/_includes/css/nerd-font-tweaks.scss
+++ b/_includes/css/nerd-font-tweaks.scss
@@ -679,6 +679,13 @@ a.nerd-font-button:before {
        }
 }
 
+@media only screen and (max-width: 785px) {
+       nav ul li {
+               min-width: 50px;
+               line-height: 40px;
+       }
+}
+
 /* anything not desktop */
 @media only screen and (max-width: 767px) {
        .container h1 {
```
