### ISSUE TITLE
Introduce 0xProto font

### ISSUE THREAD

**Issue by ktekinay** [ryanoasis/nerd-fonts#1379]
**Requirements**

- [ X ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [ X ] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [ X ] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Please consider converting the 0xProto font, available here:

https://github.com/0xType/0xProto

**Describe alternatives you've considered**
N/A

**Additional context**
This has become my new favorite programming font for its readability and handling of ligatures, but it looks the icons and other niceties that Nerd Fonts brings.

Thanks.

**Comment by Finii** [comment]
> the name of the font does not show up on the Downloads page, just the description and links.

See #1411

I will upload the preview images in a few minutes, the real release will take a bit more time, esp. because we still wait for the people at Monaspace.
