### ISSUE TITLE
Font Linux symbols aren't present

### ISSUE THREAD

**Issue by agriffis** [ryanoasis/nerd-fonts#138]
The screenshot in the README shows the Font Linux symbols starting at 0xf100. However they don't seem to be present when I load `DejaVu Sans Mono Nerd Font Complete Mono.ttf` in fontforge:

![screenshot from 2017-03-07 17-37-56](https://cloud.githubusercontent.com/assets/50637/23706792/a59a8b56-03dd-11e7-9452-f465fa1c78ec.png)

### My setup
* font is `DejaVu Sans Mono Nerd Font Complete Mono.ttf`
* terminal emulator is `gnome-terminal` (doesn't matter in this issue though)
* Fedora 25

**Comment by ryanoasis** [comment]
Thanks again @agriffis,

Confirmed that the readme gives the wrong codepoints (it gives the original codepoints which cannot be used due to conflict)

Discussed on the [gitter chat](https://gitter.im/ryanoasis/nerd-fonts?at=58c091ee00c00c3d4fdc2ee0)

**Comment by No0n3Left** [comment]
They were moved to f3xx, instead of f1xx. Just found them kinda randomly looking for them. I don't know how to update the image though, I tried but its hard to replace the 1 with a 3 and make it blend in.

**Comment by agriffis** [comment]
@No0n3Left you just need an updated screenshot. Here's the one from gitter conversation.

![screenshot from 2017-03-08 20-23-33](https://cloud.githubusercontent.com/assets/50637/23920371/c135ea66-08d0-11e7-9311-f2a11f9a7753.png)

I thought about updating it too, but I was surprised to see `readme.md` making image references from the wiki. I haven't seen that technique before on github, so I left off.

**Comment by ryanoasis** [comment]
> I thought about updating it too, but I was surprised to see readme.md making image references from the wiki. I haven't seen that technique before on github, so I left off.

Yeah that might not be the best place to put these images going forward if it's harder for people to contribute.

I think I carried that method over from [VimDevIcons](https://github.com/ryanoasis/vim-devicons) but in that project the purpose was to offload the images to reduce download size when users update their plugin.. in Nerd Fonts that's probably a stupid reason because the repo is already so large that a few additional images shouldn't matter.

Any thoughts anyone else?

**Comment by PrzemekSkw** [comment]
@ryanoasis Hi, will You be so nice and help me add fedora logo to my terminal theme? I use zsh shell and tilix terminal. I install Powerlevel9k theme and add some codes to .zshrc file:
`POWERLEVEL9K_MODE='awesome-patched'
source  ~/Programy/powerlevel9k/powerlevel9k.zsh-theme
SAVEHIST=100
HISTFILE=~/.zsh_history

POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon battery dir_writable dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( status ip time)
POWERLEVEL9K_OS_ICON_BACKGROUND="white"
POWERLEVEL9K_OS_ICON_FOREGROUND="black"
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M \uE868  %d.%m.%y}"

POWERLEVEL9K_BATTERY_CHARGING='yellow'
POWERLEVEL9K_BATTERY_CHARGED='green'
POWERLEVEL9K_BATTERY_DISCONNECTED='$DEFAULT_COLOR'
POWERLEVEL9K_BATTERY_LOW_THRESHOLD='10'
POWERLEVEL9K_BATTERY_LOW_COLOR='red'
POWERLEVEL9K_BATTERY_ICON='\uf1e6 '`

and my terminal looks like this:
![tilix](https://cloud.githubusercontent.com/assets/25219988/24699439/4478ce50-19f4-11e7-8e48-1d862b7a8cb0.png)

Now I want to add fedora logo after linux logo. Can You help me please?

**Comment by agriffis** [comment]
@PrzemekSkw This is not the right place to ask for help. Try [gitter](https://gitter.im/ryanoasis/nerd-fonts)

@ryanoasis I think we can just put these images in the repo like you suggested. They're small beans compared to the fonts themselves. I'll make a PR that does that and then fixes this issue.

**Comment by ryanoasis** [comment]
@PrzemekSkw Love your desktop wallpaper. Yeah this is probably not the best place for this as @agriffis mentioned but one thing you will have to change the mode to the nerd fonts one. Honestly I am not sure the best way to modify a specific segment to insert a specific glyph.

@agriffis Yes that is best thanks. I agree original reason I gave makes no sense. I saw the PR thanks for that. Will merge by this weekend :+1:

**Comment by PrzemekSkw** [comment]
@ryanoasis I find solution thx :)
That's the wallpaper:
[https://www.google.pl/search?q=lego+star+wars+wallpaper+hd3&tbm=isch&imgil=o6TEy0YJLAQMYM%253A%253B5ur5VvNDT4WieM%253Bhttp%25253A%25252F%25252Fwallpapermonkey.com%25252Funcategorized%25252Fstar-wars-wallpaper-iphone-hd%25252F&source=iu&pf=m&fir=o6TEy0YJLAQMYM%253A%252C5ur5VvNDT4WieM%252C_&usg=__rz7QC9nvqMpptjUiOEcdo1JMCq4%3D&biw=1600&bih=759&ved=0ahUKEwiCyOSZnY_TAhWkDMAKHdZ1DgUQyjcIKQ&ei=iuPlWILbAqSZgAbW67ko#imgrc=o6TEy0YJLAQMYM:](url)
