### ISSUE TITLE
Icon for Neovim in custom?

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#1383]
### Discussed in https://github.com/ryanoasis/nerd-fonts/discussions/1380

<div type='discussions-op-text'>

<sup>Originally posted by **georgeguimaraes** October 13, 2023</sup>
Hi,

Would you consider adding Neovim icon as custom directly into nerd-fonts?

Reasons:

1. There's no Neovim icon in upstream repos. However, there are some PRs lingering in some upstream repos that appear discontinued:

    - https://github.com/lukas-w/font-logos/pull/93 (font-logos appear to be unmaintained)
    - https://github.com/vorillaz/devicons/issues/151 (vorillaz/devicons appears to be unmainted, last commit 6y ago)

2. Even the "popular, maintained devicons/devicons" (as described in https://github.com/ryanoasis/nerd-fonts/issues/615) does not have a Neovim icon yet. And their last release was 17 months ago. So even if a PR was accepted upstream, there's gonna be a potentially huge delay until nerd-fonts can use that.

3. There's already `custom-vim` in Nerd Fonts (which I'm using as replacement for a neovim logo).</div>

**Comment by georgeguimaraes** [comment]
Tks for creating the issue!
