### ISSUE TITLE
Icons rendering/showing properly in VSCode integrated terminal, but not in standalone PowerShell

### ISSUE THREAD

**Issue by tusan-tsvetkoff** [ryanoasis/nerd-fonts#1388]
- [-] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [-] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [-] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Running `ls` inside VsCode's integrated terminal:
![image](https://github.com/ryanoasis/nerd-fonts/assets/47631858/85646ec2-3674-4a90-a496-36ffdc03019a)

Running `ls` inside my PowerShell (in the same directory):
![image](https://github.com/ryanoasis/nerd-fonts/assets/47631858/3047bc92-545a-45c3-92d5-8caa616eb482)

I should also note that nvim's webdevicons are having the same behavior in Neovim, as in, not displaying properly (<?> instead of that actual glyph/icon).

What I've concluded is that it seems to be related to all the `md` glyphs.
I've also made sure to update `oh-my-posh`, as well as running this command `oh-my-posh config migrate glyphs --write`

Expected behavior:

Ideally, the '<?>' icons in PowerShell should be whatever they are in VsCode's integrated terminal, which is also running PowerShell as far as I am concerned.

Example symbols:

**From PowerShell:**
󰪷  README.md
󰙨  tests <- **directory**

**From VsCode's terminal:**
󰪷  README.md
󰙨  tests
#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _JetBrainsMonoNerdFontMono-Regular.ttf_
   - Due to the fact I am running on Windows 10 and have no access to `settings.json`, this is how it appears inside my Properties selection:   
![image](https://github.com/ryanoasis/nerd-fonts/assets/47631858/8b791978-94c9-47f4-b796-695b28332db7)
   - Inside VsCode I simply set the integrated terminal's font family to `JetBrains Nerd Font Mono`
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - [Latest stable release](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.2)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Windows Terminal(?), PowerShell 7.3.8
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows 10

#### ★ Screenshots (Optional)

**From within PowerShell:**
![image](https://github.com/ryanoasis/nerd-fonts/assets/47631858/d07c599d-df3b-4d71-bd1b-c3ba6cf32890)

**Properties:**
![image](https://github.com/ryanoasis/nerd-fonts/assets/47631858/6fa3febb-ff24-4782-9f7b-9aa507369c85)

**Comment by tusan-tsvetkoff** [comment]
Apparently I am a bit of an idiot. Had never installed the Windows Terminal from the Windows Store. Installed it and fixed all my issues.

**Comment by Finii** [comment]
The non-WindowsTerminal terminals (i.e. `cmd` and the like) are not able to display 5 digit unicode codepoints, due to the software design. Microsoft uses UTF16 internally (instead of the now ubiquitous UTF8) but only 1 `wchar_t` value per character, so ... 

A nice explanation can be found here:
https://devblogs.microsoft.com/commandline/windows-command-line-unicode-and-utf-8-output-text-buffer/

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ec8d160e-1b5f-47bb-8ad2-238ef77f9c89)

The way to go is to use Windows Terminal (as you found out), the modern alternative.
