### ISSUE TITLE
Fira Code Alignment Problem

### ISSUE THREAD

**Issue by sencer** [ryanoasis/nerd-fonts#139]
`:` character, and perhaps others, are misaligned compared to the Fira itself.

**Comment by ryanoasis** [comment]
Hmm those shouldn't be modified but I will take a look. Thanks!

**Comment by ryanoasis** [comment]
@sencer I am not seeing this. Can you add more detail or a screenshot? Also which 2 fonts exactly are you comparing?

**Comment by ryanoasis** [comment]
closing this. @sencer please feel free to re-open if you can provide some more details :smile: thanks
