### ISSUE TITLE
[CaskaydiaCove] Slashed zero has wrong height

### ISSUE THREAD

**Issue by Alecton4** [ryanoasis/nerd-fonts#1390]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Normal slashed zero has wrong height compared to other numbers, but italic slashed zero is fine. The original [Cascadia Code 2111.01](https://github.com/microsoft/cascadia-code/releases/download/v2111.01/CascadiaCode-2111.01.zip) doesn't have the issue. Also, the doted zero is fine. 
**Update**: Version 2.3.3 is fine, staring from 3.0.0 the height is wrong.

Expected behavior:

The regular slashed zero should have the same height as other numbers.

Example symbols:

`0`

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - `CaskaydiaCoveNerdFont-Regular.ttf`
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/CascadiaCode.zip
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Visual Studio Code 1.83.0
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - openSUSE Tumbleweed 20231006
   - KDE Plasma Version: 5.27.8
   - KDE Frameworks Version: 5.110.0
   - Qt Version: 5.15.10
   - Kernel Version: 6.5.4-1-default (64-bit)
   - Graphics Platform: X11

#### ★ Screenshots (Optional)

Using VSCode settings `"editor.fontLigatures": "'liga', 'calt', 'ss03', 'ss05', 'ss08', 'ss20', 'zero'"`:

![image](https://github.com/ryanoasis/nerd-fonts/assets/43232804/8a2f74b7-5358-478a-a84b-b1ad9e9c466b)

Using VSCode settings `"editor.fontLigatures": "'liga', 'calt', 'ss03', 'ss05', 'ss08', 'ss20'"`:

![image](https://github.com/ryanoasis/nerd-fonts/assets/43232804/94c985c4-f516-4aea-acd8-012aa126e8a9)

**Comment by Finii** [comment]
Sorry to hear of your problem.

The problem seems to be a sublel one, both glyphs have the exact same height of 1440 units.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/e788adc8-f4f1-43a3-a6ad-deeaf67dd90b)

This could be the hinting. Do you still see it if you increase the font size?

**Comment by Alecton4** [comment]
@Finii I tried adjusting `"editor.fontSize"`, found that font size `14`-`16` will have this issue, `<=13` or `>=17` will not.

**Comment by Finii** [comment]
Thanks for the information. This really sounds like a hinting problem.

Unfortunately `Cascadia Code` hinting is done properly (by Aaron / "Microsoft") only for the variable font anymore.
For the static font we have the choice of `ttfautohint` (which ~is bad~ differs a lot from the manually hinted original variable font) or at the moment we use `VisualTrueType`. I also looked into one other autohinter, but VTT seemed best.

I will check if the slashed-zero is somehow not hinted (it has a very high codepoint) and if so how to include it in the autohinting.

**Comment by Alecton4** [comment]
@Finii Sorry I'm unfamiliar with the font design area, but I think the original `Cascadia Code` that works fine on my machine is not installed as "variable font". I installed the content in `otf/static` from [the package folder](https://github.com/microsoft/cascadia-code/releases/download/v2111.01/CascadiaCode-2111.01.zip).

**Comment by Finii** [comment]
The glyph `zero.zero` ('slashed zero') is hinted, but the program is far shorter...:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/6fb335f9-8e22-4680-af92-9de0ddc450ed)

----

Regarding
> I installed the content in otf/static from [the package folder](https://github.com/microsoft/cascadia-code/releases/download/v2111.01/CascadiaCode-2111.01.zip).

The static versions there are hinted via `ttfautohint` which results in a considerable height difference compared to the variable font. See [cascadia-code/issues/371](https://www.github.com/microsoft/cascadia-code/issues/371).
As most? (at least a lot) people seem to have both (patched and unpatched) installed on their machine they all complain that the patched font (using the original static version, `ttfautohint`) and the unpatched font (variable font, manually hinted) do not look similar (because different hinting). For that reason we at NF re-hint the static fonts with `VTT` to get a better switch-over experience.

**Comment by Finii** [comment]
I again tried to fix this in VTT, but I did not find anything that would solve this.

As we depend on automatic / original hinting we can not do much here.

* Wait for a Cascadia Code static with nice hints (imho: will not come (back; we once had it))
* Remove the hints from all `zero` variants :clown_face: 
* Wait for Nerd Fonts to work with variable fonts (will take a year or more, if at all)
* Do some manual magic ... ah let me try something

**Comment by Finii** [comment]
Strange, when I look into the antialiasing, the size is almost always the same, and if it differs the slashed-zero is bigger.
And the italic version is identical.

:thinking: 

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/cdb0261e-e54a-4ed7-8038-ef3a8da37204)

Is the effect only in the VSCode thing? Maybe they use their own font renderer :grimacing: 

Also the code is **identical** for `zero.zero` normal and italic (just the point numbers change).

Hmm, even on Windows there is no difference

![Kooha-2024-03-14-13-34-17](https://github.com/ryanoasis/nerd-fonts/assets/16012374/a45eb0cd-9933-4c47-b42c-f9bb28393822)

This seems to be a one-off artifact. I have no idea what we possibly can do here. Sorry,
