### ISSUE TITLE
Add Frutiger Font

### ISSUE THREAD

**Issue by ShreyashIngle** [ryanoasis/nerd-fonts#1395]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ShreyashIngle** [comment]
Please add the Frutiger font

**Comment by Finii** [comment]
Thanks for the suggestion.

Any particular reasons / what distinguishes this font from all others?
Maybe you also have a link to share here?

**Comment by ShreyashIngle** [comment]
Thank you for considering my suggestion.

Fruitiger is a unique and aesthetically pleasing font known for its clean
and modern design. Its distinct characteristics make it a versatile choice
for various design projects. Unfortunately, I don't have a specific link to
share, but you can find more information about Fruitiger through online
font repositories or the official website of its creator.

**Comment by Finii** [comment]
Frutiger by Linotype (Designer Adrian Frutiger) is a commercial font as far as I can see.

See for example https://en.wikipedia.org/wiki/Frutiger_(typeface)

https://www.linotype.com/de/2534/frutiger.html
https://www.myfonts.com/search?query=frutiger

The stolen fonts I have found have sometimes even still the SFType bit set.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/1c16321a-6604-4734-bc59-83c038472c04)

Maybe you mean some other Frutiger.

**Comment by ShreyashIngle** [comment]
Ok, no problem.
