### ISSUE TITLE
Add the Glimmer Icons in search icon cheat sheet section 

### ISSUE THREAD

**Issue by ShreyashIngle** [ryanoasis/nerd-fonts#1396]
**Requirements**

- [ ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [ ] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [ ] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Finii** [comment]
None of the required fields filled. Closing as there is no content in the Issue (except maybe the title).
