### ISSUE TITLE
Make Contributor Page Responsive for Small Screens

### ISSUE THREAD

**Issue by VitthalGund** [ryanoasis/nerd-fonts#1399]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful.
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help.
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help.

#### 🎯 Subject of the issue

**Experienced behavior:**
As individuals new to open source, it's disheartening to notice that the Contributor page is no longer responsive. I discovered this issue when working on Issue #1384 and received a reply from @Finii [here](https://github.com/ryanoasis/nerd-fonts/issues/1384#issuecomment-1775392780). As a responsible contributor, I decided to analyze and address this issue optimally.

The Contributor page functions well in desktop view. However, when the screen width falls below 715px, it starts causing problems by overflowing rows in the table that represents individual contributors. To resolve this issue, I made modifications to base.scss, as follows:
```
@media screen and (max-width: 715px) {
  table {
    border: 0;
  }

  table caption {
    font-size: 1.3em;
  }

  table thead {
    border: none;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
  }

  table tr {
    border-bottom: 3px solid #ddd;
    display: block;
    margin-bottom: 0.625em;
  }

  table td {
    border-bottom: 1px solid #ddd;
    display: block;
    font-size: 0.8em;
    text-align: right;
  }

  table td::before {
    content: attr(data-label);
    float: left;
    font-weight: bold;
    text-transform: uppercase;
  }

  table td:last-child {
    border-bottom: 0;
  }
  tr {
    display: flex !important;
    justify-content: center;
    align-items: center;
    flex-direction: row;
    flex-wrap: wrap;
  }
  td {
    display: flex;
    justify-content: center;
    margin: 15px;
    width: fit-content;
    text-align: center !important ;
  }
  a {
    justify-content: center;
  }
}

```

Expected behavior:
For screen sizes less than 715px (width), I've added media queries to change the display of table rows to flex, aligning elements and text at the center both vertically and horizontally. I also added flex-wrap: wrap to wrap elements when they start overflowing from their parent element, which is a table. This modification ensures that the Contributor page works smoothly across all screen sizes. Additionally, I introduced spacing between elements in rows to prevent overcrowding.

🔧 Your Setup
- Operating System: Windows 11
- Browser: Chrome

#### ★ Screenshots (Optional)
Before:
![image](https://github.com/ryanoasis/nerd-fonts/assets/97181033/abac0f37-aba7-4af7-bcb0-48bc03c19790)
![image](https://github.com/ryanoasis/nerd-fonts/assets/97181033/759fd328-5a28-44de-a849-17a35f0f38ec)
![image](https://github.com/ryanoasis/nerd-fonts/assets/97181033/b0e46c90-3254-489a-a069-1b236871949d)

After:
![image](https://github.com/ryanoasis/nerd-fonts/assets/97181033/656b4504-c966-4119-9fb1-e54407192ca3)
![image](https://github.com/ryanoasis/nerd-fonts/assets/97181033/364ee1cf-ea08-4415-9a3e-48adabe6221d)
![image](https://github.com/ryanoasis/nerd-fonts/assets/97181033/470c20ea-4cbe-4850-9661-1eee619a65c1)

**Comment by Finii** [comment]
Thanks for raising the Issue and the proposed solution!! :tada:

The solution still has issues, because it does wrap the table rows, the table structure itself is still preserved:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/caf9ca33-e611-4adc-9895-18d9757123fa)

_Big divider after every 7 persons_

It also has strange jumps of the padding when the screen width is changed, and the vertical alignment is jumping:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/35c39cad-6b2e-41de-8ac5-35c3a95606d3)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/c79ceb2f-c582-48ee-9fe7-3d3e5f3f575a)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/aaaaecae-6c05-4f79-bd54-390154c8a38f)

I believe the concept of a TABLE is wrong here.

Changed that to a free floating thing with a78dcd7fdbbbbec
Let me update the gh-pages, :hammer:

**Comment by Finii** [comment]
After:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/c2274db3-a256-476d-8463-63341dfb733d)
