### ISSUE TITLE
Suffix 'Mono' to differentiate between font types

### ISSUE THREAD

**Issue by Cpt0r** [ryanoasis/nerd-fonts#140]
#### Subject of the issue

Please mark the monospaced version as eg. 'Hurmit ... Mono' so it's possible to install fixed and variable width versions and select between them.

This would allow using the mono version for code/terminal and variable width for glyphs to avoid the 'small glyph' issue reported elsewhere.

#### Your Setup

N/A

#### Optional

<img width="213" alt="screen shot 2017-03-16 at 10 20 13" src="https://cloud.githubusercontent.com/assets/8690075/23974934/2d3ae95c-0a32-11e7-99f1-8a5a1127b4d8.png">

**Comment by Cpt0r** [comment]
Nevermind... https://github.com/bhilburn/powerlevel9k/issues/430#issuecomment-287084613

**Comment by ryanoasis** [comment]
@Cpt0r hmm so when I saw your screenshot I thought it was an issue. Seems like fontbook is grouping them without considering the 'Mono' portion. I think we only have that in the filename :thinking:

**Comment by Cpt0r** [comment]
Yep that's what I meant, wasn't clear - the 'Mono' is missing from the embedded font family name.

I concluded no one else would want this 'fixed' but maybe I was too quick to close this issue.

**Comment by ryanoasis** [comment]
@Cpt0r Yeah this actually does look like an issue (if someone is going to use both mono and non-mono versions)
