### ISSUE TITLE
An error occurred when the noto font used fi or fl

### ISSUE THREAD

**Issue by 1538379200** [ryanoasis/nerd-fonts#1400]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
This problem occurs when I use fonts that contain sans, but NotoMono is fine.
I tried issue #879, but it didn't work.

Expected behavior:
Fonts can be displayed normally

Example symbols:
fix  config  flask

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   -  NotoSansMNerdFontMono-Medium.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - release 
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - neovide、powershell 7
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows 11

#### ★ Screenshots (Optional)

![image](https://github.com/ryanoasis/nerd-fonts/assets/42434762/e54f59a2-f21b-4c37-9008-2f2bb06a09a8)

**Comment by Finii** [comment]
Sorry to hear of your problem.

Ah I see, we remove only Liga 14 - 18, but obviously that is in 34. That is a mistake by me.

<img width="934" alt="Screenshot 2023-11-03 at 23 36 19" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/16197de5-0cc9-4cad-9279-ab220a08dc76">

**Comment by 1538379200** [comment]
Is it necessary for me to wait for the next version in order to be able to use it?😭

**Comment by 1538379200** [comment]
I would like to utilize the NotoSansMNerdFontMono font series, and it would be greatly appreciated if you could provide a Notosansmnerdfontmono-regular.ttf file. Currently, the NotoSansMNerdFontMono-Medium.ttf font is displaying correctly.😊

**Comment by Finii** [comment]
Here is the complete `Nerd Font Mono` set
* as `xz` because that reduces the size considerably (6 MB instead of 40 MB)
* additional `zip` layer because Github does not know/allow xz only zip :roll_eyes: 

[NotoSansMNerdFontMono.tar.xz.zip](https://github.com/ryanoasis/nerd-fonts/files/13279682/NotoSansMNerdFontMono.tar.xz.zip)

I hope you can unpack it. Zip is quite common, and modern `tar` can handle `xz` automagically.

**Comment by 1538379200** [comment]
thank you😊
