### ISSUE TITLE
some powerline chars can't display on windows with xshell.

### ISSUE THREAD

**Issue by ColinZeb** [ryanoasis/nerd-fonts#141]
such as \u21B5.
i'm trying patch a font:consolas ,and it's use on windows 10 with xshell. my command text is "./font-patcher -w -c -s ~/consola.ttf".
now , some powerline char not work. i need help。

**screenshot**
![f](https://files.gitter.im/ryanoasis/nerd-fonts/TbzB/zsh.png)

**Comment by debiansid** [comment]
Try it on SecureCRT

**Comment by ColinZeb** [comment]
securecrt work right. 
and how can i if fix it with xshell?

**Comment by debiansid** [comment]
It is related client , so I doubt you can fix it

**Comment by debiansid** [comment]
It did not work on putty either

**Comment by ColinZeb** [comment]
on mintty, did't display correct either.

**Comment by ColinZeb** [comment]
But meslolg font  work is completely on xshell or mintty

**Comment by anselal** [comment]
The icons do not show up correctly on MobaXterm either, which is basically based on putty..

**Comment by Finii** [comment]
`21B5` is not touched by Nerd Fonts? If it's not there in the original font it will not be there in the patched font?
