### ISSUE TITLE
Add the "replacement table" for the new icons onto the "Cheat sheet" search.

### ISSUE THREAD

**Issue by frenchiveruti** [ryanoasis/nerd-fonts#1415]
Sorry, I know there are protocols and all for good issues, no time.  

The requirement is simple:
Add a link to this:
https://github.com/ryanoasis/nerd-fonts/issues/1059#issuecomment-1404891287 
Here: 
https://www.nerdfonts.com/cheat-sheet 

This would save time when having to update several codes.

**Comment by Finii** [comment]
> This would save time when having to update several codes.

Well, even more time is saved by using the nerdfixer :-}

But let see. Can not invest more time now as you also do not invest time.

**Comment by frenchiveruti** [comment]
> > This would save time when having to update several codes.
> 
> Well, even more time is saved by using the nerdfixer [1] :-}
> 
> But let see. Can not invest more time now as you also do not invest time.
> 
> [1] https://github.com/loichyan/nerdfix
> 
> _Edit: Add nerdfix link_

Thanks for the link :D

**Comment by Finii** [comment]
I guess this would be really nice, but to get this into the web page is quite some work and there is no realistic hope of ever doing it :-(
