### ISSUE TITLE
Incomplete Installation Instructions

### ISSUE THREAD

**Issue by wheelerlaw** [ryanoasis/nerd-fonts#1417]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**

Many of the options in the [Font Installation](https://github.com/ryanoasis/nerd-fonts#font-installation) section of the readme don't include any instructions on installing the fonts, only downloading the font to the current working directory. 

For example, Option 2 includes a `curl` command to put a font file in the current working directory, but no information on what to do next in order to get applications to be able to use the font. Same goes for Options 5 and 6. 

I also searched the wiki and the FAQ and they both only really include information on downloading the fonts.

**Describe the solution you'd like**
Some documentation created with installation instructions on what commands to run in order to actually install the font. I presume that downloading the font to the current working directory isn't enough to get applications to be able to use them. 

**Describe alternatives you've considered**
Might be worth adding a section in the header bar of the project homepage (nerdfonts.com) named "Font Installation" with some general instructions on installing the fonts for the various popular platforms. 

**Additional context**
n/a

**Comment by c99SRS** [comment]
@wheelerlaw pls assign this to me.
