### ISSUE TITLE
Zero Width Joiner (ZWJ) Support

### ISSUE THREAD

**Issue by chuxubank** [ryanoasis/nerd-fonts#1418]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to combine two nerd-icons together.
For emoji, we can have 
```
👨‍👩‍👧‍👦 = 👨<200d>👩<200d>👧<200d>👦
```
But nerd icon do not have that feature.

**Describe the solution you'd like**
Support ZWJ so we can combine any existing nerd icons together.

**Describe alternatives you've considered**
Define some common combined nerd icons?

**Additional context**
https://www.compart.com/en/unicode/U+200D

**Comment by Finii** [comment]
Thanks for the suggestion.

This would be a completely new scope of Nerd Fonts.
Someone must maintain the combinations.
I fear there is noone who would do this. Unless you volunteer :-)
