### ISSUE TITLE
[website / github] MartianMono.zip is 404

### ISSUE THREAD

**Issue by nerdCopter** [ryanoasis/nerd-fonts#1420]
#### MartianMono.zip link is 404
Experienced behavior:
Cannot download MartianMono via https://www.nerdfonts.com/font-downloads (https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/MartianMono.zip)

Expected behavior:
MartianMono.zip exists

**Comment by Finii** [comment]
Please read pinned issue
* #1411
