### ISSUE TITLE
FiraCode icons don't show correctly in VSCode

### ISSUE THREAD

**Issue by nguyendviet** [ryanoasis/nerd-fonts#1421]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Some icons don't show properly in VSCode. E.g.: the balance icon is shown as
<img width="28" alt="Screenshot 2023-11-19 at 15 46 49" src="https://github.com/ryanoasis/nerd-fonts/assets/30057363/53843cd2-0c5f-489e-9c7f-ca6afc728fe0">

I can't paste the text here because it'll show up correctly. That's why I included a screenshot of what I see.

Expected behavior:
⚖️

Example symbols:
⚖️

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - FiraCodeNerdFont-Regular.ttf
   - FiraCodeNerdFontMono-Regular.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://www.nerdfonts.com/font-downloads
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - zsh
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - OS X 14.1.1 (23B81)

#### ★ Screenshots (Optional)

<img width="28" alt="Screenshot 2023-11-19 at 15 46 49" src="https://github.com/ryanoasis/nerd-fonts/assets/30057363/53843cd2-0c5f-489e-9c7f-ca6afc728fe0">

**Comment by Finii** [comment]
Sorry to hear of your problem! But the scales are the right thing?

The codepoints in your pasted text seem to be U+2696 U+FE0F

And that is exactly what is shown. On my machine this pages looks like this:

<img width="450" alt="Screenshot 2023-11-20 at 00 56 51" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/adcc2932-b800-45d5-9b7d-710f89720a3c">

Not sure what you expect. Here what the codepoints are defined as:

<img width="577" alt="Screenshot 2023-11-20 at 01 06 15" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/e6fad780-764c-4ffe-967a-b64a69cd6ac8">

<img width="746" alt="Screenshot 2023-11-20 at 01 06 41" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/f6544b21-1fd2-4cf8-80e3-444658a74f45">

**Comment by nguyendviet** [comment]
@Finii Thanks for your answer.

I expect it to show like on [programmingfonts](https://www.programmingfonts.org/#firacode)

<img width="735" alt="Screenshot 2023-11-19 at 20 30 33" src="https://github.com/ryanoasis/nerd-fonts/assets/30057363/e9bb16e1-c3fa-4c53-9871-9d456367e478">
