### ISSUE TITLE
Monaspice download link points to non-existing target

### ISSUE THREAD

**Issue by woha** [ryanoasis/nerd-fonts#1425]
https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Mononoki.zip

**Comment by Finii** [comment]
Sorry, see #1411 

80% chance release trigger will be in a few hours.

**Comment by woha** [comment]
Thank you very much!

**Comment by Finii** [comment]
Sorry, only NOW finished with `font-logos`, had some problems there and needed to do a bugfix release `font-logos-1.1.1` :grimacing: 
Font Logos is needed for Nerd Fonts:
* #1424

Now I need to sleep, again another delay, sorry :disappointed:
