### ISSUE TITLE
Geist Mono Patch

### ISSUE THREAD

**Issue by nemanjastanic** [ryanoasis/nerd-fonts#1426]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Geist Mono is under patched fonts here: https://github.com/ryanoasis/nerd-fonts?tab=readme-ov-file#patched-fonts

However, it does not exist in the pached-fonts directory: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/GeistMono

**Comment by Finii** [comment]
Please note #1411 when you tick `[x] I have searched the issues for my issue` :grimacing: ;-)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/315961cd-76ee-4060-a15e-cf2c2a7ba908)
