### ISSUE TITLE
nerd-fonts not working on MacOS Sierra 10.12.3 zsh 5.2 (x86_64-apple-darwin16.0)

### ISSUE THREAD

**Issue by debiansid** [ryanoasis/nerd-fonts#143]
#### Subject of the issue
nerd-fonts not working on MacOS Sierra 10.12.3 zsh 5.2 (x86_64-apple-darwin16.0)+oh-my-zsh with powerlevel9k theme
_Describe issue here_
```
/Users/xyz/.oh-my-zsh/custom/themes/powerlevel9k/functions/icons.zsh:152: character not in range
/Users/xyz/.oh-my-zsh/custom/themes/powerlevel9k/functions/utilities.zsh:86: command not found: print_icon
powerlevel9k_vcs_init:32: command not found: print_icon
powerlevel9k_vcs_init:33: command not found: print_icon
powerlevel9k_vcs_init:43: command not found: print_icon
prompt_dir:3: character not in range
right_prompt_segment:32: command not found: print_icon
right_prompt_segment:38: command not found: print_icon
```
#### Your Setup

- Sauce Code Pro Nerd Font Complete Windows Compatible.ttf 	
-  iTerm2 3.0.15
- MacOS Sierra 10.12.3_

#### Optional
`awesome-patched` + [+`SourceCodePro+Powerline+Awesome+Regular.ttf`](https://github.com/stefano-meschiari/dotemacs)  works on those setup.

**Comment by ryanoasis** [comment]
Thanks for the update. Glad you got it sorted out :smile:

**Comment by sushovannits** [comment]
What was the resolution?
