### ISSUE TITLE
Monospice and VScode problem

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#1432]
Am I doing something wrong? Here's my `terminal.integrated.fontFamily` (vscode) and the results:

## `FiraCode NFM Retina`
![image](https://github.com/ryanoasis/nerd-fonts/assets/19306384/43ec1a1e-92cf-4cb2-8a45-c616392769c6)
## `MonaspiceNe NFM`
![image](https://github.com/ryanoasis/nerd-fonts/assets/19306384/95d11e82-0159-4921-8f12-895114d02730)

_Originally posted by @Logerfo in https://github.com/ryanoasis/nerd-fonts/issues/1403#issuecomment-1821394932_

**Comment by Finii** [comment]
I can see two issues
* percent is 'above' zero partially
* steering wheel thing becomes box

Which issue are you referring to?
What is your Platform? VScode is available on a lot.
Your settings as screenshot maybe?
What is the codepoint of the steering wheel? Possibly just copy and paste the glyph as text in a comment (I can then look up the codepoint).

**Comment by Logerfo** [comment]
> Which issue are you referring to?

To the Kube symbol.

> What is your Platform?

Windows 11 Pro 22H2
VSCode 1.84.2
Electron: 25.9.2
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

> Your settings

```jsonc
{
  "terminal.integrated.commandsToSkipShell": [
    "workbench.action.files.newUntitledFile",
  ],
  "terminal.integrated.cursorStyle": "line",
  "terminal.integrated.fontFamily": "MonaspiceNe NFM",
  "terminal.integrated.fontSize": 13,
  "terminal.integrated.rightClickBehavior": "default",
  "terminal.integrated.defaultProfile.windows": "Git Bash",
  "terminal.integrated.splitCwd": "inherited",
  "terminal.integrated.tabs.enabled": true,
  "terminal.integrated.enableMultiLinePasteWarning": false,
  "terminal.integrated.profiles.windows": {
    "GitBash": {
      "path": "D:\\Git\\bin\\bash.exe",
    },
  },
}
```

> copy and paste the glyph as text

```sh
100 C:\repos ﴱ dev0
```

**Comment by Finii** [comment]
<img width="1247" alt="Screenshot 2023-11-22 at 18 03 01" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/178b1461-521f-41ce-a367-34e99d43f318">

Interesting, your percent is `F295`. And the wheel is `FD31`.

Quick check:

<img width="632" alt="Screenshot 2023-11-22 at 18 05 35" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/67735a21-9006-4981-8840-eee6a6fd1de6">

`FD31` has been relocated to `F0833`.
If you have problems with the 5 digit codes, I believe there is another similar icon with a 4 digit code from some software or service, I just can not remember its name. Ah you hinted "kube":

<img width="565" alt="Screenshot 2023-11-22 at 18 13 08" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/9e78aca4-041e-4ad3-8588-4f4644af3182">

Well, looks different.
