### ISSUE TITLE
Monaspice look always bold

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#1433]
Is it just me or does Monaspice look like it's always emboldened?

(Monaspice on the left with FiraCode for comparison):

![VSCodium_2023-11-21_21-35-04](https://github.com/ryanoasis/nerd-fonts/assets/25013746/12c3d1b6-91a2-46d5-9a9f-41e14174bf58) ![VSCodium_2023-11-21_21-35-49](https://github.com/ryanoasis/nerd-fonts/assets/25013746/22b5b5aa-96e8-47c2-afa2-f37f3f6a1c69)

I downloaded Monaspice via the [scoop-nerd-fonts Scoop bucket](https://github.com/matthewjberger/scoop-nerd-fonts). Haven't used the official non-patched Monaspace so I can't say if this is expected.

The Monaspice font used is `MonaspiceNe NFM`.

_Originally posted by @redactedscribe in https://github.com/ryanoasis/nerd-fonts/issues/1403#issuecomment-1821570917_

**Comment by redactedscribe** [comment]
@Finii Thanks for moving the issue.

**Comment by Finii** [comment]
Sorry to hear of your problem.

For me it looks like your FiraCode is not Regular?

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/d3cef68d-1586-4568-ad0f-55e105698c67)

**Comment by Finii** [comment]
I'm too stupid ...

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/4193d1a5-815a-4d0b-831e-f9b365a7682f)

**Comment by Finii** [comment]
So yes, Monaspace Regular seams to be slightly heavier than FiraCode Regular.

**Comment by redactedscribe** [comment]
I guess you mean to say that this is indeed expected. First impression was that it seems broken, but maybe this really is how it's supposed to look. I guess it's an issue with Monaspace itself.

**Comment by Finii** [comment]
We patch these:
```
weights=(Regular Italic Bold BoldItalic Medium MediumItalic)
```

But there are also
* ExtraLight
* Light
* SemiBold
* ExtraBold

Maybe try the Light weight from https://github.com/githubnext/monaspace/tree/main/fonts/otf.
We could add a weight if there is demand.

**Comment by Finii** [comment]
But of course using `Light` breaks the RIBBI set, I have no clue what your client uses for bold then, `Bold`? Not font at all but it does the bold face from the base face arithmetically? With some clients you can select 'normal' and 'embolded' font separately, then you could select `Thin` and `Medium` for ex.

**Comment by redactedscribe** [comment]
Using VS Codium with `"editor.fontWeight": "normal"`. The values which change `MonaspiceNe NFM`'s weight are `400`, `500`, `600` (or `normal`, `medium`, `bold`).

I just went through a bunch of other fonts to compare to and it seems Monaspace is just a heavier font by default.

Interestingly, it's also heavier compared to what https://monaspace.githubnext.com/ shows. Here are some screenshots comparing the font in VS Code (newly downloaded zip, only font changed) to the font as seen on the Monaspace site using Firefox.

Side-by-side:

![Code_2023-11-21_22-51-57](https://github.com/ryanoasis/nerd-fonts/assets/25013746/ccb46f1f-c1b0-4d7a-a075-350f853c0c31)

Overlaid:

![Code_2023-11-21_22-53-20](https://github.com/ryanoasis/nerd-fonts/assets/25013746/c1c7d9bd-899b-4862-9324-91dc9e599e44)

**Comment by redactedscribe** [comment]
Inspecting the `@keyframes` word using Firefox shows that they are using a font weight of 300. Strange to showcase your font with something other than the default?

![firefox_2023-11-21_23-02-23](https://github.com/ryanoasis/nerd-fonts/assets/25013746/f9687680-5268-4d8f-8206-63a9e186b042)

**Comment by thewinger** [comment]
+1 to adding the Light weight to the font

**Comment by Finii** [comment]
Ok, I ll add this now but will come only on next release. Can put the prepatched archive here if that helps?

Sent from Nine
________________________________

**Comment by redactedscribe** [comment]
> Ok, I ll add this now but will come only on next release. Can put the prepatched archive here if that helps?

I'd be interested to see the result.

**Comment by Finii** [comment]
[Monaspace_only_Light.tar.xz.zip](https://github.com/ryanoasis/nerd-fonts/files/13440346/Monaspace_only_Light.tar.xz.zip)

This is just the `Light` and `LightItalic` fonts. Again `xz` packed because otherwise too big for a comment, afterwards `zip` packed because Github does not allow `xz` :roll_eyes:

**Comment by redactedscribe** [comment]
Thanks @Finii. It is less heavy, but only marginally. Here's MonaspiceNe NFM `normal`/`400` in VS Codium compared to `300`, and Consolas `400` on the far right (opening the images in separate tabs and switching between them helps):

![VSCodium_2023-11-22_17-39-33](https://github.com/ryanoasis/nerd-fonts/assets/25013746/4415022a-a25a-4043-9325-46bfde909bd3) ![VSCodium_2023-11-22_17-31-10](https://github.com/ryanoasis/nerd-fonts/assets/25013746/57f70368-da4a-4a08-9c50-c56cd75ed60e) ![VSCodium_2023-11-22_17-42-51](https://github.com/ryanoasis/nerd-fonts/assets/25013746/6688bfad-40bf-4797-bac1-fd2103311af9)

I think `200` (so ExtraLight) for Monaspice would be closest to most other monospace fonts I'm seeing at their regular font size of `400`.

(Whilst comparing fonts, I've had to change font size +/- 2 to keep them roughly the same size, not sure how much of a role that plays in my tests. Maybe it would've been better to vary the line spacing instead.)

**Comment by Finii** [comment]
I just wanted to mention that the weight unit (100-900) is arbitrary units. Although there are 'suggestions' it is not a measure in any way.

One person's fatal error is another person's most common case ;-)

**Comment by Finii** [comment]
Just had to laugh so hard ;-)

* https://github.com/canonical/Ubuntu-fonts/issues/99
