### ISSUE TITLE
Update Ubuntu Nerd Font to use refreshed 2023 Ubuntu Font

### ISSUE THREAD

**Issue by olivercalder** [ryanoasis/nerd-fonts#1435]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
The Ubuntu fonts, originally designed in 2010-2011, received a redesign and re-release in 2023, making them variable and including various other improvements and extensions to the old design. The current Ubuntu Nerd Fonts are still based on the old 2010 version.

**Describe the solution you'd like**
I would like the Ubuntu Nerd Fonts to be rebased on the new 2023 Ubuntu Fonts. This would only need to apply to the latin/cyrillic/greek character sets, not to the symbols which make up the bulk of the Nerd Font symbol set.

**Describe alternatives you've considered**
An alternative would be to continue to use the old 2010 Ubuntu Fonts as they exist now, but I believe this is undesirable, as I think it is preferable for the Ubuntu Nerd Font to be a drop-in replacement for the stock Ubuntu font, which is now substantially different. Ubuntu preserves the original Ubuntu Font as the `ubuntu-fonts-classic` package, with the new fonts in the `ubuntu-fonts` package --- a similar approach could be taken with the Ubuntu Nerd Fonts, for those who wish to continue using the old Ubuntu Fonts.

**Additional context**
The newest release of the Ubuntu font can be found at: https://github.com/canonical/Ubuntu-fonts/releases/tag/v.1001

**Comment by Finii** [comment]
Thanks for suggesting.

We had this some month ago already, and the problem was that Nerd Fonts can only patch static fonts, and the new Ubuntu font is only available as variable font. This just does not work.
Maybe they in the meanwhile added static fonts to their set, I will check out, and also try to link the past discussion.

**Comment by Finii** [comment]
<img width="1004" alt="Screenshot 2023-11-22 at 18 20 48" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/57d200d2-c0d0-4136-b2c4-5b96750e5bdf">

Ah, ok. Will definitely do that in the next release. Thanks again for reminding.

**Comment by Finii** [comment]
* https://github.com/ryanoasis/nerd-fonts/issues/1302

**Comment by Finii** [comment]
This seems to be somehow breaking so a different name/pack would be good?

**Comment by olivercalder** [comment]
My proposal would be to transition the existing fonts to "Ubuntu{, Mono} Classic", and use the updated v.1001 fonts as "Ubuntu{, Mono}", for a few reasons:
1. I think most users would prefer an Ubuntu Nerd Font which matches the current Ubuntu Font,
2. Unless installed via a package manager, I don't think most users are updating the Nerd Fonts they've installed on their system, and
3. If they update the Ubuntu Nerd Fonts and are appalled by the changes, they can install the "Classic" versions and all will be well.

This is just my opinion, of course. I do think that it would be preferable for "Ubuntu Nerd Font" to match the new Ubuntu Font going forward, as the latter will only become more ubiquitous as other OSs and systems are updated in the future.

**Comment by dawidd6** [comment]
Canonical started naming it's newest variation of their font - Ubuntu Sans. See https://github.com/canonical/Ubuntu-Sans-Mono-fonts. As a fan of the current/classic Ubuntu font, I would like nerd-fonts not to break it and instead introduce the newest release of this font in a different name (possibly UbuntuSansMono).
