### ISSUE TITLE
Update base font Source Code Pro from 2.038 to version 2.042

### ISSUE THREAD

**Issue by scjb** [ryanoasis/nerd-fonts#1437]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
The font Source Code Pro contained in Nerd Fonts is still on version 2.038

Expected behavior:
Nerd font SauceCodePro should be based on Source Code Pro 2.042

#### 🔧 Your Setup

- _Which font are you using?_
   - SauceCodeProNerdFont-Regular.ttf
- _Where did you get the file from_
   - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.0/SourceCodePro.zip
   - downloaded from Nerd Font github repo
   - The SourceCodePro font 2.042 is available at https://github.com/adobe-fonts/source-code-pro
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Windows Terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows 10 22H2

**Comment by Finii** [comment]
Thanks for the hint. For some reason I missed that, already with 3.0.0?!
Can not remember we did not do that because of issues.
Tagging for next release.

**Comment by Finii** [comment]
The glyphs themselves are unchanged between 2.038 and 2.042 (checked the outline compare).
Hinting differs slightly, and some table stuff.
I guess the change is rather hard to notice at all.
