### ISSUE TITLE
Glyph Request: Retro Computer Logos

### ISSUE THREAD

**Issue by oshaboy** [ryanoasis/nerd-fonts#1447]
**Context**
[Fairfax HD](https://www.kreativekorp.com/charset/font/FairfaxHD/) and [Nishiki Teki](https://umihotaru.work/nishiki-teki_pua.pdf) already have these if you want a source font. In those they are mostly meant for compatibility with Retro Computing Fonts.

**Logos in no particular order:**
Name | Fairfax Assignment | Nishiki-teki Assignment |
----| ----- | ------- 
Atari | FFCE4 | F896 
Commodore | FFCE5| F897 
Amiga | FFCE6/FFCE7 | F898/F899
Acorn | FFCF0 | F883
Apple Lisa | FFCF1| F882
Bell Labs | FFCF8 | 
Data General|FFCF9| FDBF9 
Atari in 2 parts | FFCFA+FFCFB | FDBFA+FDBFB  
Commander X16 (Not technically retro but close enough)| F5FF | F5FF

There are also some old PUA Emoji that were too "IP Encumbered" for Unicode which should probably be a different Issue. And the Google Assistant Logo. Also some really weird stuff like Betty Boop, Bob Dobbs in 4 parts, Logo of the Workers Party of Korea, and something called a "Dogcow". Which I think are out of scope for nerd fonts. 

![image](https://github.com/ryanoasis/nerd-fonts/assets/35503208/0f108618-d186-4300-b4d4-ab59398c6630)
![image](https://github.com/ryanoasis/nerd-fonts/assets/35503208/c5789100-c7bd-4a09-bd23-393365281b9d)

Paging #1095.

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
