### ISSUE TITLE
Glyph Set Request: Kurinto Aux

### ISSUE THREAD

**Issue by oshaboy** [ryanoasis/nerd-fonts#1448]
https://www.kurinto.com/pdf/Kurinto_CodeChart_Aux.pdf

Ignore all the conlang stuff. There's the Creative Commons block in F700-F72F. Icons at F5000-F544F and logos at F5450-F55FF. There are a lot there that have no nerd font equivalent. It's also SIL Open Font Licensed. 

Paging #1095

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
