### ISSUE TITLE
Glyph Set Request: Catrinity. 

### ISSUE THREAD

**Issue by oshaboy** [ryanoasis/nerd-fonts#1449]
https://catrinity-font.de/downloads/CatrinityPrivateUseArea.pdf

Mostly Colorful Board and Card Game pieces. Are color fonts ok for nerd fonts?

paging #1095 .

**Comment by Finii** [comment]
> Are color fonts ok for nerd fonts?

Color glyphs are (currently) not possible. We discussed that at length somewhere else but multiple factors prevent that.
I believe supporting variable fonts is more important than color glyphs and only one would even be remotely possible (because of developer resource shortage).

**Comment by Finii** [comment]
Compare
* #1301

with Kreatve Square that also contains board and card game icons.

**Comment by oshaboy** [comment]
Catriny contains a LOT more game icons than Kreative Square tho.

**Comment by oshaboy** [comment]
Also it seems like Catrinity has fallback glyphs for all the game icons anyway.

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
