### ISSUE TITLE
Shell variables with established names for icons

### ISSUE THREAD

**Issue by powerman** [ryanoasis/nerd-fonts#145]
I've gathered established names for all icons from many places and created https://github.com/powerman/nerd-fonts-sh to make it easier to use icons in shell scripts. In case there are several established names - I've provided aliases.

It may make sense to merge these files into your repo - this should make it easier to keep them in sync with font changes. If you'll do this - I'll close my repo. If you don't wanna merge them - you may like to add link to my repo.

I was unable to find established names for some icons (16 for Powerline Extra Symbols, 5 for Custom and 8 for Devicons), I suppose it's mostly for icons you've added on your own. So, if you know names for them - please send me PR. :)

**Comment by ryanoasis** [comment]
@powerman That's just... awesome :tada: 

I would :heart: to see this in the Nerd Fonts repo :blush: 

---

Yeah the powerline extra symbols I didn't give official names (can work on that) and yes there were some other custom ones added. On Devicons not sure why some might not have.

If you want I can try to add this to the next release (1.1) I just haven't spent much time on dev :cry: so maybe this weekend I can get a preliminary branch together for 1.1 :smile: 

---

This is not exactly related but I am working on a test script that will print out the glyphs but that is mostly for testing the font after patching where these scripts you mention are more for use in scripts (like you mentioned). Nevertheless here is some preview:

(WIP)
![c2f20262-0f39-11e7-8c77-c74dd0dd2af3](https://cloud.githubusercontent.com/assets/8083459/24531252/a0fa073e-1585-11e7-8198-8b61db44dc35.png)

**Comment by powerman** [comment]
If you like I can push these scripts, but let me know which directory/names I should use. I'll open PR to let you review, of course.

**Comment by ryanoasis** [comment]
If you would like to create a branch here go for it you have my blessing :smile: (just please not master -- though I don't think you can).

I will create a 1.1 branch this weekend I believe

I think in bin/scripts makes sense but maybe there could be another sub-dir there.. I am not 100% sure. I will think about it some more.

**Comment by ryanoasis** [comment]
Closed with PR #147
