### ISSUE TITLE
glyph does not fill whole height, is it the problem of my terminal?

### ISSUE THREAD

**Issue by Sejen27** [ryanoasis/nerd-fonts#1450]
**Environment**
OS : Ubuntu 23.10
Terminal : tmux,  GNOME Terminal 3.49.92, GNOME 45
Font : Hack Nerd Font v3.1.1

![2023-12-03 16-34-15](https://github.com/ryanoasis/nerd-fonts/assets/16253972/96ec1f40-1625-4d36-a180-c99fbf374ac4)
I have tried some old versions of the Hack Nerd Font at 2020 and 2021 year, but this problem still exists. What should I do to fix this ?

**Comment by Finii** [comment]
This looks bad, sorry to hear that.

I guess you downloaded the release artifact, let me try...

**Comment by Sejen27** [comment]
@Finii  Thank you for your reply ! Below is my settings:
![Screenshot from 2023-12-04 18-59-36](https://github.com/ryanoasis/nerd-fonts/assets/16253972/4faf3f32-782c-4f94-812c-517ba7e72fe4)
I found that it was the language I used (Chinese)  that caused the problem, when I change language to English, problem solved.
Is there a solution if I use Chinese?

**Comment by Sejen27** [comment]
Hi @Finii , are the sizes of these glyph normal? Are they a litter small?
![Screenshot from 2023-12-05 11-24-02](https://github.com/ryanoasis/nerd-fonts/assets/16253972/2996600c-c9db-4022-a5de-1f88b7165128)
![image](https://github.com/ryanoasis/nerd-fonts/assets/16253972/881cb6c6-cfd9-46b6-943b-a6b827e097e9)

**Comment by Finii** [comment]
> Are they a litter small?

The icons are one 'cell' wide, i.e. the same width as the `M`.
Try the `Hack Nerd Font` (without `Mono`) for bigger icons.

**Comment by Sejen27** [comment]
> > Are they a litter small?
> 
> The icons are one 'cell' wide, i.e. the same width as the `M`. Try the `Hack Nerd Font` (without `Mono`) for bigger icons.

Thank You

**Comment by Sejen27** [comment]
> The system language My chinese font is "Microsoft Yahei" (msyh.ttc, copied from Windows 10)
> 
> ![image](https://private-user-images.githubusercontent.com/16253972/287710545-0ae1d62f-2176-431c-8c6d-5ad4c1ac6519.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjkxODksIm5iZiI6MTcwMTc2ODg4OSwicGF0aCI6Ii8xNjI1Mzk3Mi8yODc3MTA1NDUtMGFlMWQ2MmYtMjE3Ni00MzFjLThjNmQtNWFkNGMxYWM2NTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5MzQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5YmFhZGY5MmVjMDk1MTQwZTJjNjJiOGVmZWFkNDEzOTA1NzZiMTc4YmYyNDEwMjY5ZTU1MGFmMDUxNjViN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9JibDPMcqzLLVYZ8Kxntk42E3I4_NqBm9NwEpCJf4Ro) ![image](https://private-user-images.githubusercontent.com/16253972/287712872-8bf1a268-8414-4ab7-bb9b-c3a53adf908d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjkxODksIm5iZiI6MTcwMTc2ODg4OSwicGF0aCI6Ii8xNjI1Mzk3Mi8yODc3MTI4NzItOGJmMWEyNjgtODQxNC00YWI3LWJiOWItYzNhNTNhZGY5MDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5MzQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZjNhOTFmMWUwODk0YWFjMmMwODk2OGY4ZDcwNGM4NTliMDU5MWFjYzc5ZTcwZTkzYTZlZDg1MDQxOWNiNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n26vxf_-2ZPvefSZEqW-7SPNDuviRCKDhU3hMABT7rA)

@Finii Is there a solution?

**Comment by Finii** [comment]
This week I'm on a conference, will try to find some time experimenting.
I have no idea just so.

Sent from Nine

________________________________

**Comment by vegawong** [comment]
Has the same issue, the system language set to English then it works. Has any solution to support Chinese System Language?
