### ISSUE TITLE
When do we get our inverse U+E0B0 Triangle?

### ISSUE THREAD

**Issue by a-usr** [ryanoasis/nerd-fonts#1451]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
Some Terminals dont apply effects like transpaency to foreground colors.

**Describe the solution you'd like**
Inverted version of U+E0B0 and other powerline symbols without already existing inverse counterparts

**Describe alternatives you've considered**
U+E0D4: Looks bad

**Additional context**
This has been requested on multiple occasions, for example [Here](https://github.com/ryanoasis/powerline-extra-symbols/issues/7)
Also, its not like the svg's have to be made from scrap, some already exist in the Powerline Extra Repo ([here](https://github.com/ryanoasis/powerline-extra-symbols/blob/master/src/uniE0D7_Powerline_normal-left-inverse-cutout.svg) for example)

**Comment by Finii** [comment]
Note to self:
Check if this is still a problem with Win11 (i.e. Windows Terminal)

**Comment by Finii** [comment]
> U+E0D4: Looks bad

Can you explain why? Looks bad for your use case, or is there an issue with the icon itself?

**Comment by Finii** [comment]
Are you willing to test the new glyphs?
I can create patched fonts for your preferred sourcefont and you can try.
Please specify which font you'd like to test @a-usr.

**Comment by a-usr** [comment]
> > U+E0D4: Looks bad
> 
> Can you explain why? Looks bad for your use case, or is there an issue with the icon itself?

It's not the icon itself, but it just don't match with what I need in my use case (specifically the empty line in the middle and the fact that the angle of the triangle when the symbol has the background colour as foreground and vice versa)

**Comment by Finii** [comment]
> I would love to test CascaydaCove

You can find that in the PR: https://github.com/ryanoasis/nerd-fonts/pull/1490#issuecomment-1902035907

Please report back in the PR thread.
