### ISSUE TITLE
Add font support for Chinese character which is called 方正润玉圆宋

### ISSUE THREAD

**Issue by CoolPlayLin** [ryanoasis/nerd-fonts#1453]
This kind of font of Chinese character is beautiful and comfortable to see （Personally）

![image](https://github.com/ryanoasis/nerd-fonts/assets/96709586/cc46469e-66ce-41f0-ac45-e71dc1456e94)
![image](https://github.com/ryanoasis/nerd-fonts/assets/96709586/a2b3a997-c460-425f-ad99-fdbbd28a559b)

Website: https://www.foundertype.com/index.php/FontInfo/index/id/6169

I have already downloaded this font, if you agree to add it, I'll open a Pull Request❤️

**Comment by CoolPlayLin** [comment]
The LICENSE of it for person or family

>Founder Font Home Edition User License Agreement
>
>User instructions:
>
>This "Founder Font Home Edition User License Agreement" (hereinafter referred to as the "Agreement") is between you and Beijing Peking University Founder Electronics Co., Ltd. (hereinafter referred to as "Founder Electronics Company") regarding the installation and use of the Founder Font software accompanying this agreement and the contents thereof. Legal Agreement for the included fonts (hereinafter collectively referred to as the "Font Software"). Before using all or any part of this "Font Library Software", you shall accept all the terms and conditions stipulated in this agreement, especially the following provisions: (a) Use (Articles 3 and 4); (b) ) Intellectual Property Rights (Article 5); (c) Warranty (Article 6) and Liability (Article 7). The installation and use of this font software indicates that you agree to accept the terms of this agreement and abide by this agreement. Otherwise, please do not install and/or use this font software.
>
>Founder fonts are works of art stipulated in the Copyright Law, and Founder font software is computer software stipulated in my country's Computer Software Protection Regulations. Founder Electronics Co., Ltd. enjoys all the intellectual property rights of this font software. Any use of the "Font Library Software" without the legal and express authorization of Founder Electronics is an infringement. Founder Electronics only allows you to use this font software for personal, non-commercial purposes on the premise of complying with the terms of this agreement.
>
>1. illustrate.
>
>1.1 Font software description:
>
>This "Font Library Software" refers to all content stored in files, floppy disks, CD-ROMs or other media that contains one or more fonts attached to this Agreement, including but not limited to computer software, fonts, manuals and other printed materials, and CD-ROMs Envelopes and other packaging materials (except for printing materials, packaging materials, etc. that are not printed by Founder Electronics Company by other agents, sellers, etc.). The font formats involved in this font software include but are not limited to True type format, Open type format, PostScript Type 1, Type 0 format and CID format.
>
>1.2 Description of art works:
>
>The fonts included in the font library software are works of art, so your use of the works of art must comply with relevant regulations such as the Copyright Law of the People's Republic of China and the Implementation Regulations of the Copyright Law of the People's Republic of China.
>
>2. definition.
>
>"User" or "you" refers to the natural person who purchases a copy of a genuine software product from an agent or distributor authorized by Founder Electronics, and directly installs and uses this font software and the fonts included in this font software on his computer.
>
>Users should install and use this font software and the fonts included in this font software in accordance with this agreement.
>
>3． Use of font software.
>
>If you obtain the font software from Founder Electronics Company or its authorized agents or distributors, and subject to your compliance with the terms of this agreement, Founder Electronics Company will grant you the following non-exclusive license for this font software, allowing you to Use this font software in accordance with the following purposes specified in this agreement:
>
>3.1 Installation and use: You can only install and run this font software on a computer equipped with Windows or Mac OS for personal, non-commercial use. You are not allowed to use this font software on two or more electronic computer devices at the same time. ;
>
>3.2 Screen display or output: You can use the fonts included in this font software for screen display; you can also output the font images generated by this font software to a device connected to the computer where the software is installed for display or printing. Export fonts, such output may only be used for your personal, non-commercial use.
>
>3.3 Backup: To prevent the copy from being damaged, you can make a backup copy of the font software. The scope of use of this copy is consistent with the original copy.
>
>If your use requirements exceed the scope of this agreement, in particular, if you copy, distribute or exhibit the font software in this agreement for commercial purposes (including words and font combinations with copyright in art works by Founder Electronics, etc.) or use the font library to If the software is used for other purposes, please contact Founder Electronics immediately to obtain the corresponding use authorization.
>
>4． Restrictions on the use of font software.
>
>4.1 You may not copy, modify, copy, decompile, disassemble, reverse engineer, convert, translate, split this font software, or otherwise attempt to obtain the source code from this software, or extract from this software documentation Its substantial part is used for other applications.
>
>4.2 You may not sell, rent or lend the font software to the public alone or incidentally, or distribute the font software to the public through gifts, transfers or wired or wireless networks.
>
>4.3 Regardless of whether you use it for commercial or non-commercial purposes, you may not provide the trial version of Founder Fonts and the fonts it contains to third parties without the permission of Founder Electronics, either individually or incidentally. If you use part or all of the Founder font in the following forms (including but not limited to), you must obtain written authorization from Founder Electronics in advance:
>
>4.3.1 Use Founder fonts directly, format converted or modified in the company’s internal office processes;
>
>4.3.2 Use Founder fonts directly, format converted or modified in trademarks and various logos;
>
>4.3.3 Use Founder font directly, format converted or modified in various product promotion materials (such as store posters, print advertisements, TV advertisements, outdoor advertisements, online advertisements, etc.) and product manuals;
>
>4.3.4 Use Founder font directly, format converted or modified in product packaging, decoration and signage;
>
>4.3.5 Use Founder fonts directly, format converted or modified for use on websites, corporate publications, internal newspapers, periodicals, and video materials;
>
>4.3.6 Use Founder font directly, format converted or modified in audio-visual products and exhibition displays;
>
>4.3.7 Convert the whole or part of the electronic file corresponding to the Founder font directly or in format, and then apply it in an embedded manner to websites, computer programs or electronic products with visual display functions;
>
>4.3.8 Other situations that require written approval from Founder Electronics.
>
>4.4 If you have not obtained the express authorization from Founder Electronics, you may not perform the following actions on some or all of the fonts, including but not limited to: publishing, signing, modifying, distributing, renting, exhibiting, screening, broadcasting, and information network dissemination. , adaptation, compilation, etc.
>
>4.5 Other behaviors that should be prohibited or restricted by law.
>
>5． intellectual property.
>
>This font software and the fonts it contains, as well as any copies authorized by you to make from Founder Electronics, are products with intellectual property rights owned by Founder Electronics (except if there are other intellectual property statements for this "font software" product). This font software has applied for trademark registration. The structure, organization and code of this font software and all information related to this font software are the trade secrets of Founder Electronics. Based on the above situation, this font software and the fonts it contains (i.e., artistic works) are protected by the Copyright Law of the People's Republic of China, the Computer Software Protection Regulations, the Trademark Law of the People's Republic of China and other intellectual property laws and regulations and international conventions. , treaty protection. Except as expressly permitted in this agreement, any other infringement of Founder Electronics’ intellectual property rights is prohibited.
>
>6． Limited Warranty.
>
>6.1 On the premise that you comply with the terms of this agreement, Founder Electronics Company guarantees:
>
>(a) This font software meets the functions described in the accompanying written materials;
>
>(b) the support services provided to you are consistent with those described in the accompanying written materials;
>
>6.2 The total liability of Founder Electronics and its authorized suppliers to you and all compensation you enjoy are limited to one of the following two:
>
>(a) Refund the price (if any) you paid when you purchased the font software product that does not comply with the provisions of Article 6.1 of this Agreement;
>
>(b) Modify or replace font software that does not comply with the provisions of Article 6.1 of this Agreement. The warranty period of the replaced font software product is the remaining period of the original warranty period or thirty days from the date of replacement (whichever is longer).
>
>When making a claim, you must submit it to Founder Electronics or its authorized supplier within ninety (90) days after purchasing the font software and only if an invoice for the purchase of the font software is available.
>
>6.3 If the font software becomes unusable due to accident, improper use or incorrect operation, the limited warranty terms of this agreement shall not apply.
>
>6.4 The aforementioned Article 6.2 stipulates the sole and exclusive remedy for Founder Electronics Company or its authorized suppliers to breach the warranty in Article 6.1 of this Agreement. To the maximum extent permitted by applicable law, Founder Electronics and its authorized suppliers make no other warranties, express or implied, with respect to the font software, including but not limited to the merchantability, suitability, title or lack thereof of the font software products. Infringement and Implied Warranties of Provision or Non-Provision of Support Services
>
>7． Limitation of Liability.
>
>In no event shall Founder Electronics or its authorized suppliers be liable for any losses, claims or expenses or any consequential, special, incidental, indirect, punitive or other losses of any kind (including but not limited to loss of profits, loss of business, interruption, loss of business information) and shall not be liable for any claims or expenses of any third party, even if Founder Electronics or its authorized suppliers are informed in advance of the possibility of such damage. In any case, the total liability of Founder Electronics Company or its authorized suppliers under any terms of this agreement shall be limited to the actual price paid by you to purchase this software product (if any). However, if you have reached a separate written agreement with Founder Electronics Company regarding authorized use, Founder Electronics Company’s liability shall be subject to the terms of that written agreement.
>
>8. License terminated.
>
>Once you violate the terms of this agreement, Founder Electronics may terminate this agreement at any time, withdraw the authorization, and require you to bear corresponding legal responsibilities.
>
>9. Governing Law and Jurisdiction.
>
>This Agreement shall be interpreted in accordance with the laws of the People's Republic of China.
>
>If you have a dispute with Founder Electronics over issues related to this font software, you and Founder Electronics both have the right to file a lawsuit with the people's court with jurisdiction over where Founder Electronics is located.
>
>If you have any questions about this agreement or wish to obtain any information about font licensing, please contact Founder Electronics Co., Ltd. as follows:
>
>Beijing Peking University Founder Electronics Co., Ltd.
>
>Address: Founder Building, No. 9, 5th Street, Shangdi Information Industry Base, Haidian District, Beijing

>Postal code: 100085
>
>Tel: 4006-516763
>
>Email: font_sales@founder.com
>
>Website: http://www.foundertype.com

<details>
<summary>Original Content</summary>
<p>
方正字库家庭版用户许可协议

用户须知：

本《方正字库家庭版用户许可协议》（以下简称“协议”）是您与北京北大方正电子有限公司（以下简称“方正电子公司”）之间有关安装、使用本协议附随的方正字库软件及其中所包含的字体（以下共同简称“字库软件”）的法律协议。您在使用本“字库软件”的所有或任何部分前，应接受本协议中规定的所有条款和条件，特别是其中对下列内容的规定：（a）使用（第3、4 条）；（b）知识产权（第5条）；（c）保证（第6条）及责任（第7条）。安装、使用本字库软件的行为表示您同意接受本协议的条款，并遵守本协议。否则，请不要安装和/或使用本字库软件。

方正字库字体属于著作权法规定的美术作品，方正字库软件属于我国计算机软件保护条例规定的计算机软件，方正电子公司享有本字库软件所有的知识产权。任何未经方正电子公司合法、明示授权而使用“字库软件”的行为均为侵权行为。方正电子公司只允许您在遵守本协议各项条款的前提下个人、非商业目的使用本字库软件。

1．说明。

1.1 字库软件说明：

本“字库软件”指附随了本协议的包含一款或多款字体的文件、软盘、光盘或以其他形式介质储存的所有内容，包括但不限于计算机软件、字体、说明书等印刷材料，以及光盘封套等包装材料（其他代理商、销售商等非方正电子公司自行印制的印刷材料、包装材料等除外）。本字库软件中所涉及的字库格式包括但不限于True type格式、Open type格式、PostScript Type 1、Type 0格式和CID格式。

1.2 美术作品说明:

字库软件所包含的字体是美术作品，因此您对该美术作品的使用要遵循《中华人民共和国著作权法》以及《中华人民共和国著作权法实施条例》等有关规定。

2．定义。

“用户”或“您”是指向方正电子公司授权的代理商或经销商购买正版软件产品复制件，并直接在计算机上安装、使用本字库软件及本字库软件所包含字体的自然人。

用户应依照本协议安装、使用本字库软件及本字库软件所包含的字体。

3．字库软件的使用。

如您从方正电子公司或其授权的代理商或经销商处取得字库软件，并且以您遵守本协议的条款为前提，方正电子公司即授予您以下关于本字库软件的非独占性许可，允许您按照本协议规定的如下用途使用本字库软件：

3.1 安装使用：您仅可以在一台装有Windows或Mac OS的电子计算机上安装、运行本字库软件供个人非商业使用，不得在两台或两台以上的电子计算机设备上同时使用本字库软件；

3.2 屏幕显示或输出：您可以将本字库软件所包含的字体用于屏幕显示；您也可以在将通过本字库软件所生成的字形图像输出至与安装软件的计算机相连的设备上进行显示或打印进行字体的输出，此类输出只能供您个人、非商业目的使用。

3.3 备份：为防止复制品损坏，您可以制作字库软件备份副本一份，该副本的使用范围与原复制品一致。

如果您的使用需求超出了本协议的使用许可范围，尤其是，您出于商业目的复制、发行或者展览本协议字库软件（包括方正电子公司具有美术作品著作权的单字以及字体组合等）或将字库软件用作其他用途，请即时与方正电子公司联系以获取相应的使用授权。

4．字库软件的使用限制。

4.1 您不得对本字库软件进行复制、修改、仿制、反编译、反汇编、反向工程、转换、翻译、拆分，或以其他方式试图从本软件取得源代码，或从本软件文档中摘取其实质部分作其他应用。

4.2 您不得单独或者附带地以出售、出租、出借等方式向公众发行或通过赠与、转让以及有线或者无线网络传播本字库软件。

4.3 无论您出于商业目的还是非商业目的，您不得单独或者附带地将方正字库试用版产品及其所包含的字体提供给未经方正电子许可的第三人使用。如果您在以如下形式（包括但不限于）使用部分或全部方正字体时，必须事先获得方正电子公司的书面授权许可：

4.3.1 将方正字体直接、格式转换或修改后用于企业内部办公流程中；

4.3.2 将方正字体直接、格式转换或修改后用于商标、各类标识中；

4.3.3 将方正字体直接、格式转换或修改后用于各类产品宣传推广材料(如卖场海报、平面广告、电视广告、户外广告、网络广告等)、产品说明书中；

4.3.4 将方正字体直接、格式转换或修改后用于产品包装、装潢、标牌中；

4.3.5 将方正字体直接、格式转换或修改后用于网站、企业内刊\内报、期刊、视频资料；

4.3.6 将方正字体直接、格式转换或修改后用于音像制品、展览展示中；

4.3.7 将方正字体对应的电子文件整体或部分直接或格式转换后，以嵌入的方式应用到网站、计算机程序或带有可视化显示功能的电子产品中；

4.3.8 其他应当由方正电子公司书面许可的情况。

4.4如果您没有获得方正电子公司明确的授权许可，不得对其中的部分或全部字体实施下述行为，包括但不限于：发表、署名、修改、发行、出租、展览、放映、广播、信息网络传播、改编、汇编等。

4.5 其他依法应被禁止或者限制的行为。

5．知识产权。

本字库软件及其所包含的字体以及方正电子公司授权您制作的任何副本均为方正电子公司具有知识产权的产品（本“字库软件”产品存在其他知识产权声明的除外）。本字库软件已经申请商标注册。本字库软件的结构、组织和代码以及与本字库软件相关的所有信息均为方正电子公司的商业秘密。基于前述情形，本字库软件及其所包含的字体（即美术作品）受《中华人民共和国著作权法》、《计算机软件保护条例》、《中华人民共和国商标法》和其他知识产权法律法规及国际公约、条约的保护。除本协议中明确的许可，禁止其他任何侵犯方正电子公司知识产权的行为。

6．有限保证。

6.1 在您遵守本协议条款的前提下，方正电子公司保证：

(a) 本字库软件符合附随书面材料所述的功能；

(b) 为您提供的支持服务与附随的书面材料中所述相符；

6.2 方正电子公司及其授权供应商对您所承担的全部责任，以及您所享有的所有补偿以下列两者之一为限：

(a) 退还您购买不符合本协议第6.1条规定的字库软件产品时已支付的价款（如有）；

(b) 修正或更换不符合本协议第6.1条规定的字库软件。经更换的字库软件产品的保证期限为原保证期剩余的期限或自更换日起计三十天（以时间较长者为准）。

进行索赔时，您必须在购得本字库软件后九十（90）天内、且仅在可提供购买本字库软件发票的情况下，向方正电子公司或其授权供应商提出。

6.3 本字库软件因事故、不当使用或错误操作而造成无法使用的，不适用本协议的有限保证条款。

6.4 前述第6.2条规定了方正电子公司或其授权供应商违反本协议第6.1条保证时的唯一和专有的补偿方式。在适用法律所允许的最大范围内，方正电子公司及其授权供应商就本字库软件不做其他明示或默示的保证，包括但不限于对字库软件产品的适销性、适用性、所有权或无侵权以及提供或不提供支持服务的默示保证

7．责任限制。

方正电子公司或其授权供应商在任何情况下都不对任何损失、索赔或费用或任何因果的、特殊的、意外的、间接的、惩罚性的或其他任何损失（包括但不限于利润损失、营业中断、商业信息的遗失）承担任何责任，也不对任何第三方的索赔或费用承担赔偿责任，即使方正电子公司或其授权供应商事先被告知该损害发生的可能性。不论任何情况，方正电子公司或其授权供应商依照本协议任何条款下所承担的全部责任，均限于您购买本软件产品所实际已付的价款（如果有的话）。但是，如果您已经与方正电子公司就授权许可使用另行达成书面协议，则方正电子公司的赔偿责任以该书面协议条款为准。

8．许可终止。

一旦您违反本协议的条款，方正电子公司随时可能终止本协议、收回授权，并要求您承担相应法律责任。

9．适用法律与管辖。

本协议适用中华人民共和国法律的解释。

如您与方正电子公司就本字库软件的相关问题发生争议，您与方正电子公司均有权向方正电子公司所在地有管辖权的人民法院提起诉讼。

如果您对本协议有任何疑问或者希望获得有关字体授权许可的任何信息，请通过如下方式与方正电子公司联系：

北京北大方正电子有限公司

地址：北京市海淀区上地信息产业基地5街9号 方正大厦

邮编：100085

电话：4006-516763

邮箱：font_sales@founder.com

网址：http://www.foundertype.com
</p>
</details>

**Comment by CoolPlayLin** [comment]
no need to add

**Comment by Finii** [comment]
From the license I believe we are not allowed to put the font here and also not allowed to modify (i.e. patch more icons into) it. Sorry.

But you already closed ;-)
