### ISSUE TITLE
Wrong character for U+2588 (Full Block) in D2Coding

### ISSUE THREAD

**Issue by hdd1013** [ryanoasis/nerd-fonts#1454]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
U+2588 (Full Block), commonly used in progress bars, was incorrectly patched into a "Biohazard" symbol

Expected behavior:
U+2588 (Full Block) in D2 Coding Ligature Nerd Font should show the correct Block element symbol

Example symbols:
█, U+2588, Block Elements

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - D2CodingLigatureNerdFontPropo-Bold.ttf
   - D2CodingLigatureNerdFontPropo-Regular.ttf
   - D2CodingLigatureNerdFontMono-Regular.ttf
   - D2CodingLigatureNerdFontMono-Bold.ttf
   - D2CodingLigatureNerdFont-Regular.ttf
   - D2CodingLigatureNerdFont-Bold.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - The affected font files are currently being distributed on the main nerd-fonts repository, oh-my-posh website, and oh-my-posh's font install command.
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Windows Terminal, Lxterminal, Konsole
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Applies to all major operating systems (Windows, OS X, Linux, Raspberry Pi OS-Also a linux)

#### ★ Screenshots (Optional)

![d2codingu2588](https://github.com/ryanoasis/nerd-fonts/assets/7456108/bbf3dd01-2d51-40b2-b9ff-995f667f676d)
Normal Full Block symbol in the original D2Coding Font

![d2codingnerdu2588](https://github.com/ryanoasis/nerd-fonts/assets/7456108/567bff58-7b55-40d3-9d51-604e5e44315f)
Incorrect symbol in the Nerd Font

![d2block](https://github.com/ryanoasis/nerd-fonts/assets/7456108/9ec72fa1-2e79-4906-aed7-4225e105c873)
Screenshot of terminal output with the affected font

**Comment by Finii** [comment]
Unpatched font does not have it, checking where it comes from

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/7b887b97-c7f7-40f5-8830-7896d122aba2)

**Comment by Finii** [comment]
They (D2Coding) link `2588` and `E286` to make it 'one glyph' and with FontAwesomeExtension we patch into `E286`.

There is code that detects such cases, but obviously not good enough, or it had a different problem target, checking code.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/455c7225-6e9f-48ea-914b-83228f93c1e4)
