### ISSUE TITLE
Add Twilio Sans Mono

### ISSUE THREAD

**Issue by refact0r** [ryanoasis/nerd-fonts#1458]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

It would be great if you guys could add a nerd font version of https://github.com/twilio/twilio-sans-mono. Thanks!

**Comment by CoolPlayLin** [comment]
Hello @refact0r 
Your font is in #1465

**Comment by Finii** [comment]
Superseeded as CoolPlayLin pointed out.
