### ISSUE TITLE
zap (26A1) is wide

### ISSUE THREAD

**Issue by powerman** [ryanoasis/nerd-fonts#146]
#### Subject of the issue

I've no idea is this an issue with fonts or Vim or terminals. Somehow "zap" icon became 2-symbol wide in Vim, while in shell/mcedit/mousepad it looks normal.

```
$ echo "'⚡'" 
'⚡'
$ echo "'⚡'" | vim -u /dev/null --noplugin -
# vim shows this, note extra space after zap:
# '⚡ '
```

This is not happens with all other icons, only with this one.

#### Your Setup

I've tried several fonts: RobotoMono Nerd Font, DroidSansMono Nerd Font, etc.
I've tried several terminals: uxrvt, konsole.
I'm using Gentoo Linux.

**Comment by ryanoasis** [comment]
@powerman Hey thanks for the report. I am seeing the same. It looks like this is how it is in the source (octicons).

Will do some more investigating.. but looks like to fix this would have to be some tweaking to the patcher script

**Comment by ryanoasis** [comment]
3 years later still a mystery :laughing: :cry:

**Comment by LeviticusNelson** [comment]
It looks the same even 5 years later, unless there was any patches that I am not aware off

**Comment by Finii** [comment]
Firstly, you see the zap is 'yellow'. The zap patched in by Nerd Fonts is black-and-white.

On my machine it comes from `Noto Color Emoji` which is given precidience over the selected font by fontconfig rules.
When I remove the Google font I get a nice one-cell-wide black-and-white zap.

The fontconfig line on my machine is here:

```
/etc/fonts/conf.avail/60-generic.conf:			<family>Noto Color Emoji</family> <!-- Google -->
```

So, what you get is what you (or some distro guy) has set up. Change your setup to get what you want ;-)

**Comment by powerman** [comment]
@Finii Actually it's you see yellow zap - because GitHub (or browser) show it this way. :smile: In my console it's black&white. Anyway, today, about 6 years later, I don't have this issue, at least in vim using command I reported long time ago.
![изображение](https://user-images.githubusercontent.com/1354301/215481905-42c1b037-436c-448e-8a2c-6027aed71ed7.png)

**Comment by Finii** [comment]
> @Finii Actually it's you see yellow zap - because GitHub (or browser) show it this way

Well, no:

![image](https://user-images.githubusercontent.com/16012374/215510689-c2237911-255c-45b6-8e25-53067333a4c0.png)

_Top `tilix` with `NotoColorEmoji.ttf` removed, then copied into fonts and restarted `tilix`: Color zap_
_Entered zap via `ctrl`+`shift`+`u` `2` `6` `a` `1` `enter`_

**Comment by Finii** [comment]
> I don't have this issue, at least in vim using command I reported long time ago

Well, your b&w zap **still** looks like 2 widths wide :grimacing: So issue is still there ;-)

**Comment by powerman** [comment]
> Well, your b&w zap **still** looks like 2 widths wide grimacing So issue is still there ;-)

The issue isn't in "2 width wide", it's in "2 with wide symbol itself plus 1 extra space symbol".

**Comment by LeviticusNelson** [comment]
For JetBrainsMono Nerd Font, it now only has the 1 extra space: 
<img width="331" alt="Screenshot 2023-01-30 at 10 27 30 AM" src="https://user-images.githubusercontent.com/54561718/215563609-49f94595-8d14-4cbc-b504-00c30edd6578.png">

**Comment by Finii** [comment]
@LeviticusNelson which exact font are you using?

**Comment by Finii** [comment]
@powerman 
I guess I do not get it :grimacing: Maybe you can show with more screenshot and also tell me which font and terminal you use please.

**Comment by Finii** [comment]
It uses FreeSerif, but that is also NOT 2 'cells' wide.

I believe that is an extra handling in the terminals. Is it marked as 'is two wide' in the unicode table?

![image](https://user-images.githubusercontent.com/16012374/215572319-e4def729-d009-43fd-b1c4-54b90c2d5816.png)

**Comment by Finii** [comment]
After removing all fonts that have a 'zap', so that tofu will be shown...:

![image](https://user-images.githubusercontent.com/16012374/215683881-c791cafa-6d58-4344-a239-748e33bfb41b.png)

Still the 'zap' takes 2 cells.

<details>

Before

![image](https://user-images.githubusercontent.com/16012374/215684412-674639c5-fa11-42ab-8b2a-9f689b1dacf8.png)

After

![image](https://user-images.githubusercontent.com/16012374/215684492-b40f31e4-8398-4bc9-aafe-1d71238562eb.png)

</details>

**Comment by Finii** [comment]
According to unicode a terminal HAS TO render `zap` as `wide` character (i.e. 2 cells wide)

https://www.unicode.org/Public/15.0.0/ucd/EastAsianWidth.txt

![image](https://user-images.githubusercontent.com/16012374/215691597-b826e846-654b-417f-a3b4-13b1bb743e00.png)

The classification is `W`. See also https://www.unicode.org/reports/tr11/

For example in `windows terminal` you see this in the code here: https://github.com/microsoft/terminal/blob/main/src/types/CodepointWidthDetector.cpp

Whatever the font says is ignored and it is rendered 2 cells wide.

**Comment by Finii** [comment]
We had equivalent problems with the MaterialDesignIcons that are/were erroreously in the `F900` - `FDFF` blocks, and some symbols were 'wide' while other were 'narrow' in terminals, but in the font all were the same width.

![image](https://user-images.githubusercontent.com/16012374/215693749-fc1425bb-d8f0-4f7c-aa44-ae40e35b158b.png)
