### ISSUE TITLE
Why are my fonts being uninstalled

### ISSUE THREAD

**Issue by Agent-E11** [ryanoasis/nerd-fonts#1466]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Sometimes, when I turn off my computer, the fonts are "uninstalled", so that I have to go back and install them again for them to work. They aren't _really_ being uninstalled, because when I try to install them again it tells me that they are already installed, but my terminal says that it the font is unavailable. The issue is fixed after I install them again (until it breaks again)

Expected behavior:

Fonts should stay available

Example symbols:

N/A

#### 🔧 Your Setup

- Font: Caskaydia Cove Nerd Font
    - CaskaydiCoveNerdFont-<variation>.ttf
    - CaskaydiCoveNerdFontMono-<variation>.ttf
    - CaskaydiCoveNerdFontPropo-<variation>.ttf
    - (I have all of these installed, but the specific one I selected for the terminal is "CaskaydiaCove Nerd Font Mono")
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
    - https://www.nerdfonts.com/font-downloads (CaskaydiaCove Nerd Font download)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Windows terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows 11

**Comment by Agent-E11** [comment]
Update: For some reason, it doesn't happen at every reboot

**Comment by Finii** [comment]
Sorry to hear of your problem.

I read you download the Caskaydia archive (zip or xz), unpack it and install the fonts 'normally' by double-clicking them?

If the fonts vanish, are they still visible in the 'fonts overview' dialogue (or how that is called, am not a frequent Windows user)?
Are the font files still existing in the file system?

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/57eea28d-4257-4b48-938b-3b167f1f5279)
_Font overview thing_

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/3b72bf1f-26f7-4e74-a635-b64731641558)
_Path where user installed fonts are on my machine_

I usually install fonts under Windows the same way, in user mode, and never had this problem.
Maybe try installing system-wide (as admin)?

**Comment by Finii** [comment]
Closed due to no response.
