### ISSUE TITLE
EnvyCodeR not on programmingfonts.org

### ISSUE THREAD

**Issue by JupiLogy** [ryanoasis/nerd-fonts#1467]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Click on "preview on programmingfonts.org" button under EnvyCodeR font.
Goes to programmingfonts.org but the font used in the preview is not the EnvyCodeR font.

Expected behavior:
Preview on programmingfonts.org uses EnvyCodeR font.

Example symbols:

n/a

#### 🔧 Your Setup
n/a

#### ★ Screenshots (Optional)

n/a

**Comment by Finii** [comment]
Hmm, there is no Envy Code R anymore it seems, there are only 3 fonts starting with `E`?
I am quite sure I remember that it was on programming fonts :thinking: 

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/cec68b8f-7206-4ff5-9479-9b0e1f4e43e4)

Ah yes, they had it, added in 2019 with this commit over there:

* https://github.com/braver/programmingfonts/pull/46
https://github.com/braver/programmingfonts/commit/aabeae58a294ac5fa8d27b88fb3653d1b237b183 `fix #48, #46: add envy code r`

Lets see when/why it has been removed...

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/a19285a5-8cee-4e84-aec0-5af7a455b181)


Ah ha! But in the PR mentioned above they said they asked the author for the permission to include the font.
(We did the same, btw.)

Hmm, I can not find any additional information, that was not part of a PR it seems.

Plan:

* Raise issue over there involving the font author
* Fix (remove) link here

**Comment by Finii** [comment]
https://github.com/braver/programmingfonts/issues/145

**Comment by Finii** [comment]
Thanks for pointing the problem out. Lets see if this can be resolved by Koen and/or Damien.

**Comment by damieng** [comment]
Yeah I gave permission a while back, not sure why it got removed from there and here.

**Comment by JupiLogy** [comment]
Looks to be resolved, thank you guys :)
