### ISSUE TITLE
JetBrainsMono NFM (Light, Thin, etc.) broken since v3.1.1

### ISSUE THREAD

**Issue by wookayin** [ryanoasis/nerd-fonts#1473]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

JetBrainsMono NFM Light is broken. It has different color when rendered by some terminals, and another terminal claims that the font description "JetBrainsMono NFM" style: "Light" not found.

Looking at the binary file, `{ family = 'JetBrainsMono NFM Light', weight = 'Regular' }` seems to work. Wait, what is "JetBrainsMono NFM Light"?

There is a font name "JetBrainsMono NFM Light" which works OK, instead of "JetBrainsMono NFM" with style/weight = Light. Font name change is an unexpected, breaking change. 

Since more than two terminals have some issues with "Thin" or "Light" style font (Other weights are fine), I assume that this is a problem of Font, given that the font update was only a minor patch release.

Expected behavior:

It was fine in v3.1.0. The font renders OK in a "light" style.

Example symbols: Every single character.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   -  JetBrainsMonoNerdFontMono-Light.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Homebrew 
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Wezterm nightly, Alacritty 0.13
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - macOS Sonoma

#### ★ Screenshots (Optional)

v3.1.1 Light, on Wezterm: see https://github.com/wez/wezterm/issues/4126

![v3.1.1 Light](https://github.com/wez/wezterm/assets/1009873/b4a24106-50d6-4640-88cb-6f61438b3f37)

Look at dimmed foreground (white) color. Also, `M.setup_fonts()` where `M` is **boldfaced**. The color are different than `setup_fonts()`, both are #ffaf00.

v3.1.1 Regular: works Fine

![v3.1.1 Regular](https://github.com/wez/wezterm/assets/1009873/d2b12442-9e64-4acd-8305-ba432cc7a3c1)

Alacritty

<img width="796" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/1009873/efa77b74-770f-46a3-b559-3300e3ba6b5a">

**Comment by wookayin** [comment]
Related #1434 #1439

**Comment by wookayin** [comment]
This is basically a duplicate of #1434 which reverts the breaking change made in v3.1.0.

Resolution: Use the old name **`JetBrainsMono Nerd Font Mono`**, not `JetBrainsMono NFM`.

**Comment by Finii** [comment]
Is this really solved? I cant wrap my head around all this right now, maybe because its 1st of January and I'm tired ;-)
I lost track in my head what has been changed when, sorry.

**Comment by wookayin** [comment]
Happy new year! I can't really explain why it broke when it used the "NFM" name **only for Light and Thin** (probably v3.1.1 does not have these font family...), but after changing the name to what it was used to "... Nerd Font Mono" everything seems fine.
