### ISSUE TITLE
Add luau icons

### ISSUE THREAD

**Issue by lopi-py** [ryanoasis/nerd-fonts#1474]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

[Luau](https://luau-lang.org/) is a growing language that deserves its own icon. For reference, [here](https://github.com/luau-lang/site/blob/master/logo.svg?short_path=5525394) is the official svg and [here](https://github.com/JohnnyMorganz/luau-lsp/blob/main/editors/code/assets/file-icon-dark.svg?short_path=e21a037) that one for vscode. It would be nice if nerd fonts supported luau :)

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
