### ISSUE TITLE
Firacode In Winget

### ISSUE THREAD

**Issue by AndreM222** [ryanoasis/nerd-fonts#1481]
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Describe the solution you'd like**
I will like for the nerd fonts to be added in winget. I will like to not have to add a third party package manager like scoop for installing a font.

**Comment by Finii** [comment]
Thanks for the suggestion.

I have no clue what winget is. As all other 3rd party packagers this change would need a volunteer who has interest in it, and this is not done by Nerd Fonts. That volunteer can set the repackaging up in a appropriate way and be triggered by Nerd Font releases (as all the other package systems).

Personally, I would never use a third party package manager to install fonts (as you said) but just install the fonts directly from the Nerd Font release archives. I never have and never will understand why people would want to not install the fonts manually/the ordinary way. Just download the `xz` archive, open it, select all fonts, right click and install. 😬

**Comment by AndreM222** [comment]
Winget is the package manager that windows come with. The reason I like to install using the cli is because I can as well update it quite fast if there is an update

**Comment by AndreM222** [comment]
Besides the update there is also the thing about automizing setups. If you do not get it there no one will understand why you do not get and why you never will. Automizing is something you should know about, wasting time clicking on installing it is just not good.

learn about time management bro.

**Comment by Finii** [comment]
> learn about time management bro.

`(o_O)`

Sorry I wasted any time here. Time management bro!

**Comment by AndreM222** [comment]
> Thanks for the suggestion.
> 
> I have no clue what winget is. As all other 3rd party packagers this change would need a volunteer who has interest in it, and this is not done by Nerd Fonts. That volunteer can set the repackaging up in a appropriate way and be triggered by Nerd Font releases (as all the other package systems).
> 
> Personally, I would never use a third party package manager to install fonts (as you said) but just install the fonts directly from the Nerd Font release archives. I never have and never will understand why people would want to not install the fonts manually/the ordinary way. Just download the `xz` archive, open it, select all fonts, right click and install. 😬

Sorry I got angry because of the message. I should have kept my cool in the comment. But do not speak like people who want to install it through cli are wrong. If you like to install it through entering the web and making your clicks that is fine but talking about it like it makes no sense and you don't want to make sense out of it is not right brother.

I do apologize for my angry comment

**Comment by AndreM222** [comment]
Thanks for your time on answering though
