### ISSUE TITLE
CaskaydiaMono-3.1.1 and CaskaydiaCove-3.1.1 do not work in Notepad++

### ISSUE THREAD

**Issue by k9fvm** [ryanoasis/nerd-fonts#1482]
(Windows 11)
Is there someone use notepad-plus-plus?
CaskaydiaMono-3.1.1 does not work in notepad-plus-plus ( with DirectWrite_ setting 'ON' )
CaskaydiaMono-3.1.0 works good.
Hack-3.1.1 works good.

I reported this issue on notepad-plus-plus too.
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14578

**Comment by Finii** [comment]
I believe Hack is not affected by the Family Name problem, so maybe Notepad++ is having the same problem as VisualStudio2022?

Unfortunately 'does not work' is a bit unspecific.

Using the Notepad++ issue to discuss this.

See also
* #1242
* #1406
* #1434
* #1439

**Comment by k9fvm** [comment]
@Finii 

CaskaydiaCove-3.1.1 does not work too with notepad++ ( with DirectWrite_ setting 'ON' )
I put some screenshots here:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14578

**Comment by Finii** [comment]
This is the same problem as VisualStudio2022.

See also
* https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14578#issuecomment-1889121983
