### ISSUE TITLE
New Glyph Request: Half block with inner rounded corners

### ISSUE THREAD

**Issue by rockorager** [ryanoasis/nerd-fonts#1484]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
I want to make nice looking "buttons" in a TUI. I can make nice "pills" using `U+E0B6` and `U+E0B4` by sandwiching some text with those. It would be nice to have something that resembled a more "modern" look than a "pill".

**Describe the solution you'd like**
`U+2590` RIGHT HALF BLOCK with rounded inner corners (and the mirror image for the left half block). With glyphs like these, once could sandwich text and get a nicer looking "button", and also not have to add a space between successive buttons to account for whitespace. Think firefox tabs. 

**Describe alternatives you've considered**
As mentioned above, the "pill".

**Additional context**
Here's a concept (done with janky css):

![image](https://github.com/ryanoasis/nerd-fonts/assets/476352/6a274b0f-3e8d-42c0-92bb-f720550eb664)

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095

**Comment by nela** [comment]
Any traction on this? `u+f2f5` and `u+f2f6` are almost there, just without the arrows?

**Comment by Finii** [comment]
`f2f5` (without arrow) is a line, but the original question was for a filled thing, like `e0b6` but a bit more rouded-squareish.

![Image](https://github.com/user-attachments/assets/6b06a229-5550-4c61-8730-dd294b61f08b) ![Image](https://github.com/user-attachments/assets/e562316e-ad3a-474a-80a7-90891d95146a)

The problem, otoh, is not technical on the drawing side. The question is more the should we add it, on which codepoints, will it be used, has it the usual powerline glyph (as opposed to icon glyphs) problems, and how to solve them.

There is also some suggestion of a more complete set of these 'rounded and filled boxdrawing' glyphs - on gitter [here](https://matrix.to/#/!NGXkYoRJZfunkxTUKN:gitter.im/$yw-DM3S2tH-iHgaNPj4RBgMEpabpp0MmVcWYl7J6IVM?via=gitter.im&via=matrix.org&via=aria-net.org). Taking their imagery to show here:

![Image](https://github.com/user-attachments/assets/13a9ff10-a68a-4246-8e7c-8e759f0292e4)

suggesting this set:

![Image](https://github.com/user-attachments/assets/0b32346b-f4b1-4c57-9ab6-667a72b422bc)

where the last glyph is the same as the 3rd suggested by @qwerasd205

**Comment by qwerasd205** [comment]
If rounded corner pieces are added it would be ideal for them to effectively be filled versions of the rounded corner box drawing character, so it's important that they meet the center of the edge- which does make the design for the abutting ones somewhat tricky.

**Comment by qwerasd205** [comment]
I'd suggest this set:
<img width="628" alt="Image" src="https://github.com/user-attachments/assets/fbdbd00f-1127-4989-995a-089033c64562" />
(Light gray for clarity to indicate separate pieces)

**Comment by qwerasd205** [comment]
As for the "will it be used" question-- I'm almost certain that if these are made widely available due to inclusion in the nerd font glyph set then they will see a lot of adoption in modern TUI interfaces.

**Comment by qwerasd205** [comment]
Sorry for a lot of separate responses, one last thing -- I've been considering making a fairly comprehensive set of glyphs specifically designed to allow for better TUI drawing, which I would implement directly in [Ghostty](https://github.com/ghostty-org/ghostty), such that they're drawn dynamically like we already do with box drawing characters and similar.

*So*: if you happen to know an available PUA area section (not used by anything widespread) where I could put 40 to 50 glyphs or so, or if you know a good way to determine what sections are occupied, I would greatly appreciate it!

(And of course, these glyphs would be included in that set, so if you wanted to include them in NerdFonts after that then you could use those same codepoints)

**Comment by nela** [comment]
@Finii Thanks for taking the time to reply and shed light on the challenges. I think those proposed sets do indeed satisfy most of the usecases.

Potentionally, I wonder if icons with a single rounded corner might be useful, for all 4 corners that is? It would allow to create larger 'box' - such that if we combine four pieces, each having a rounded corner of their own, they would make a larger rectangle with rounded corners. Similar to the first 4 in your proposed set, just having full height, rather than half height. It seems to me it would allow to store information in two lines, all having rounded corners. (I don't have the opportunity the provide an image atm, hopefully that explanation made some sense). 

Regarding the interest for and usage of these, one could have a look at r/unixporn and places people post their rice, to notice that these styles are often used for statusbar tags, buttons. It would be nice to make these styles coherent with the TUI.
