### ISSUE TITLE
Why Symbols Nerd Font Mono is not single-width?

### ISSUE THREAD

**Issue by zzhaolei** [ryanoasis/nerd-fonts#1486]
use `CommitMono Nerd Font Mono`(`brew install font-commit-mono-nerd-font`):
<img width="114" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/17561793/b7cf428c-903e-4127-91d1-1d4063f6e0cf">

use `Symbols Nerd Font Mono`(`brew install font-symbols-only-nerd-font`):
<img width="115" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/17561793/2919975f-1165-4cf2-bc65-0c6575ba3ab6">

Is this a bug?

**Comment by Finii** [comment]
In your second image you mix two fonts, the symbol-only font and some text font.
Their respective "cell" size can be different, and in your image they are different.

It depends on your terminal if two monospace fonts with different advance widths are rescaled to match each other's width.

**Comment by zzhaolei** [comment]
Maybe I understand your explanation🤔.
I would use a combination of `CommitMono` and `CommitMono Nerd Font Mono`

**Comment by Finii** [comment]
Think like this:

(I did not look up the actual values, so the numbers are just examples)

Commit Mono has a width of 900. All glyph have that width.
Commit Mono Nerd Font Mono also has 900. The Icons are scaled such that they match the width (in the patching process).
Symbols Only Mono has a width of 1024.

Now if you mix Commit Mono and Symbols Only Mono the resulting font-combination has widths of 900 and 1024 and is not monospace anymore.
