### ISSUE TITLE
Monaspice is missing ligatures

### ISSUE THREAD

**Issue by ThePyroTF2** [ryanoasis/nerd-fonts#1487]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Monaspice has no ligatures!
Expected behavior:

Monaspice should have ligatures. Monaspace does.
Example symbols:

`=>`, `->`, `==`, etc.
#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - `MonaspiceNeNerdFontMono-Regular.otf`
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - [Link on Nerd Fonts download page](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Monaspace.zip)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Linux, Debian 12

**Comment by Finii** [comment]
Well, I checked with Radon to really "see" the font is selected, and the ligatures work there.
I would assume they also work with Neon.

Maybe you did not enable the StyleSets?
I have no clue how StyleSets are activated with Kitty.
You can also freeze the Sets into a specific fonts for example with https://github.com/MuTsunTsai/fontfreeze
Monaspace says:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/445795b3-cf7d-48ec-a1bc-144e47c63518)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/4a4cf62f-4633-4a2c-a999-b011a83d5a71)

If you think that is not the problem please supply your Kitty settings.

**Comment by ThePyroTF2** [comment]
Yeah, the font behaves properly in VSCode as well. Sorry, I should have double-checked. This must be a Kitty issue.

**Comment by Finii** [comment]
> This must be a Kitty issue.

Just looked at Kitty docu, and it seems you need to

```
font_features ss01 ss03
```

in your `kitty.conf`.

Well, I'm not a Kitty user, but something along that lines should work.
