### ISSUE TITLE
[Icon request] Add ChucK logo please

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#1489]
### Discussed in https://github.com/ryanoasis/nerd-fonts/discussions/1479

<div type='discussions-op-text'>

<sup>Originally posted by **gacallea** January 10, 2024</sup>
Hi :)

As the title says, I would like to suggest the addition of an icon for [Chuck](https://chuck.cs.princeton.edu).

Logo is here: 
![Chuck logo](https://chuck.cs.princeton.edu/doc/images/chuck-logo2023w.png)

If I had the skills I'd try to patch and contribute. I hope this can be implemented.

Please and thank you

EDIT1:

just in case, this is how I set it for the time being. Mostly posting for the extension and name:

```
[...]
    {
      "nvim-tree/nvim-web-devicons",
      opts = {
        override_by_extension = {
          ["ck"] = {
            icon = "󰧚",
            color = "#80ff00",
            name = "ChucK",
          },
        },
      },
    },
[...]
```
</div>

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095

**Comment by gacallea** [comment]
Hi @Finii :)

I was just checking the `add chuck glyph` status and I see it was removed from `v3.2.0`. I'd like to know if it will make it in the next one, please? No hurry/rush/pressure, just curious.

Please and thank you

**Comment by Finii** [comment]
Sorry, I just lack any good system for adding glyphs to the core set. I mean, selecting which should go in. usually I try to avoid it and direct people to seem inclusion in upstream icon sets.
When doing 3.2.0 I had so many things to do and include, so on the glyph addition side I believe we just had old 'Ada' being added.
I guess I should start a more systematic approach.
But then, it is extremely hard to judge if an icon is 'important' or not.

And did I not do some more work? I remember having that icon in the editor ...

Ah, there are two Issues for the same thing :grimacing: 
* #1489 (this)
* #1479

Ah, 1479 is a discussion and therefor not suited for 'serious work'.

Anyhow, I saw now some issues with the border, I guess that made me not-include it, because the outline was not 'clean', and manual cleanup takes some time that I could not find.

## Copying the comments here:

SVG is here, quickly done using Inkscape and the original png image:

![chuck](https://github.com/ryanoasis/nerd-fonts/assets/16012374/6b007590-efbf-415f-a03f-cc2bab436544)

Maybe the square-brackets top and bottom are a bit thin?

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/bd18ff60-378c-4489-9348-38dbbeb24fd8)

## and

Looks unclean:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/82b3212d-cab5-47e2-8960-a3ef4f17b1d0)

**Comment by gacallea** [comment]
Hi @Finii 

all fair points. What you suggest I should do? Open an issue with another repo? I vaguely recall you saying that asking more upstream could be a better idea.

Also: this was my initial request https://github.com/ryanoasis/nerd-fonts/discussions/1479 the rest of discussions (this included) you opened yourself. :D

Please and thank you

**Comment by Finii** [comment]
Tried to come up with some solution to the add-an-icon problem.
You can see the other candidates and some meaningless metrics in the Issue linked above.
