### ISSUE TITLE
Please add missing icons for Fira Code for proper NvChad support.

### ISSUE THREAD

**Issue by pcroland** [ryanoasis/nerd-fonts#1491]
![img](https://telegra.ph//file/008ef62a08c299f238d0c.png)
Some icons are missing from Fira Code that are present in other fonts like Cascadia Code.

**Comment by Finii** [comment]
From the image I can not deduce the icon codepoints.
Can you insert the same thing _as text_ in a comment below?
It seems to be all the folder icons.

All fonts get the same icons, maybe your CascadiaCode is a pre v3 patch?

**Comment by pcroland** [comment]
  .git

**Comment by Finii** [comment]
<img width="690" alt="Screenshot 2024-01-21 at 09 10 44" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/21988bd0-bcf1-4b34-bf42-e2725edafc7a">

<img width="168" alt="Screenshot 2024-01-21 at 09 14 00" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/52377e98-92f9-4e79-bcde-807094ae0b32">
<img width="168" alt="Screenshot 2024-01-21 at 09 13 41" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/efde8bfc-6c3c-44e8-8ebd-7a55a325ed49">

The folder icon has been added here:1d770c8ae0
And was first released with `v3.0.1`.

Double checking the actual font file confirms it exists:

<img width="1090" alt="Screenshot 2024-01-21 at 09 22 16" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/f34fcf4a-7fd7-4aa4-83b0-eb58e6de0fca">

You probably have an old version of the font installed.
