### ISSUE TITLE
Comic Shanns is using circumflex instead of caron/wedge

### ISSUE THREAD

**Issue by freed00m** [ryanoasis/nerd-fonts#1492]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Czech languages use carons for diacritics charaters.

The following sentence contains all of Czech diacritics
"Příliš žluťoučký kůň úpěl ďábelské ódy"
Shows like this 
![20240119_23h07m37s_grim](https://github.com/ryanoasis/nerd-fonts/assets/9461698/e9f19609-1f9f-4ef4-b09e-a2602089c2a8)

Expected behavior:
`řšžčěňŘŠŽČĚŤĎŇ`to have caron
`ťď` is rarity to have caron modified to apostrophe-like stroke instead of caron

Example symbols:

#### 🔧 Your Setup
ComicShannsMonoNerdFontMono-Regular.otf
from Arch linux repository

Using foot terminal with sway environment running linux.

 | Installed package info:                               
 | Name            : otf-comicshanns-nerd                
 | Version         : 3.1.1-1

**Comment by Finii** [comment]
Uups that looks indeed strange.

Concentrating on one glyph, `ž`, codepoint `17e`.

Comparing here with `Cascadia Code`, the error is already in the source font:

<img width="1141" alt="Screenshot 2024-01-28 at 15 40 58" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/6946be29-f4e9-4c98-b6f6-792af9f64286">

And they even drew the glyph completely instead of just combining a regular `z` with a regular caron, like Cascadia does:

<img width="1033" alt="Screenshot 2024-01-28 at 15 42 44" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/e1301b9f-ed48-4109-9a6f-e7b7689c23f0">

I guess this at least fixes the non-combining chars, which would make it far easier to fix your problem:
* https://github.com/jesusmgg/comic-shanns-mono/pull/7

I will work a bit on this, maybe we can incorporate the fix upstream.

**Comment by Finii** [comment]
Even the stand alone caron is not a caron.
The Breve is ok, though.

<img width="361" alt="Screenshot 2024-01-28 at 16 30 53" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/c8e26dbb-003d-4c37-9e6a-10469c07ecfe">

_Wikipedia explaining how caron should look like_

<img width="1010" alt="Screenshot 2024-01-28 at 16 31 14" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/230b400b-7624-4976-8977-ac40c1c843f2">

_Caron next to Circumflex in Comic Shanns_

---

Then I found this here [1]:

<img width="624" alt="Screenshot 2024-01-28 at 16 50 31" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/8b35ac5d-4023-438b-a53d-f4111523f4ed">

which is a Nerd Font patch of Comic Mono, with the correct Caron, BUT the original Comic Mono [2] does not have it?!
There is no documentation on that patch, and to be honest the diacritics look rather out of place.

[1] Patched Comic Mono with diacritics: https://github.com/mavonarx/ComicMonoFonts
[2] Original Comic Mono: https://github.com/dtinth/comic-mono-font

**Comment by freed00m** [comment]
Is there a way for you to patch it on your end?

It has been [reported upstream in 2021](https://github.com/shannpersand/comic-shanns/issues/16), maybe font abandoned.

**Comment by Finii** [comment]
Is the list given in the issue description with the char list (expected behavior) complete?

Sent from Nine

________________________________

**Comment by freed00m** [comment]
Yes,

but to be sure, here  you have all Czech ones

```
áéěíýóúůžščřďťň
ÁÉĚÍÝÓÚŮŽŠČŘĎŤŇ
```
I also checked Slovak diacritics and there is no extra letters Czechs don't use that would be broken.

**Comment by Finii** [comment]
Note to self

`U+00E1` `U+00E9` `U+011B` `U+00ED` áéěí
`U+00FD` `U+00F3` `U+00FA` `U+016F` ýóúů
`U+017E` `U+0161` `U+010D` `U+0159` žščř
`U+010F` `U+0165` `U+0148` `U+00C1` ďťňÁ
`U+00C9` `U+011A` `U+00CD` `U+00DD` ÉĚÍÝ
`U+00D3` `U+00DA` `U+016E` `U+017D` ÓÚŮŽ
`U+0160` `U+010C` `U+0158` `U+010E` ŠČŘĎ
`U+0164` `U+0147` ŤŇ

**Comment by Finii** [comment]
Comic Shanns repos
* https://github.com/shannpersand/comic-shanns (the source)
* https://github.com/dtinth/comic-mono-font (comic mono fork, based on shannpersand's v1)
* https://github.com/jesusmgg/comic-shanns-mono (our upstream, based on shannpersand's v2)

**Comment by Finii** [comment]
@freed00m These look about right?

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ee3b583e-9278-49e4-abd0-af7d0f490704)

**Comment by freed00m** [comment]
@Finii I think the `ď` acute should not be touching, it looks weird like a completely new character. 
I think going a bit out of monospace should be acceptable.

I tried to look up fonts and can't find any that would have acute like stroke touching the letter.

![image](https://github.com/ryanoasis/nerd-fonts/assets/9461698/65853855-e0fd-4909-bafe-7522173b2199)

![image](https://github.com/ryanoasis/nerd-fonts/assets/9461698/cbe272db-f345-4722-aaf8-97cfd27489c7)

![image](https://github.com/ryanoasis/nerd-fonts/assets/9461698/ee4c9fc4-aca4-4698-9a39-48249a3887ed)

![image](https://github.com/ryanoasis/nerd-fonts/assets/9461698/8497d115-3d9a-45a8-b77b-61d91ba58956)

**Comment by Finii** [comment]
> I think going a bit out of monospace should be acceptable.

Ok, fixing

**Comment by Finii** [comment]
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/45b7da7a-7c3f-4571-8c3e-5a9143bab0f6)
 ok?

**Comment by freed00m** [comment]
Yes,

Though I am not sure if the view is not cut off top and bottom for the uppercase characters, but if it's there and just violating top bottom line space then it's looking good.

**Comment by Finii** [comment]
That is just an artifact from how `fontforge` determines what to show in this preview.

Thanks, I will merge.

**Comment by Finii** [comment]
> Though I am not sure if the view is not cut off top and bottom for the uppercase characters, but if it's there and just violating top bottom line space then it's looking good.

Ah well, that depends on platform and we fix it before we patch:

```python
# WIN line metrics obviously wrong, as Nerd Fonts sometimes prefers that, fix it already
font.os2_winascent = font.os2_typoascent
font.os2_windescent = -font.os2_typodescent
font.os2_use_typo_metrics = 1

font.generate('ComicShannsMono-Regular.otf')
```
_Excerpt of https://github.com/ryanoasis/nerd-fonts/blob/master/src/unpatched-fonts/ComicShannsMono/make_bold_

and later

```
DEBUG: Naming mode 1
DEBUG: Monospace check: Panose is invalid ([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]); glyph-width-mono True
INFO: Setting Panose 'Family Kind' to 'Latin Text and Display' (was 'Any')
INFO: Setting Panose 'Proportion' to 'Monospaced' (was 'Any')
INFO: Redistributing line gap of 200 (100 top and 100 bottom)
DEBUG: Extended glyphs wider bounding box than basic glyphs
DEBUG: Font has negative right side bearing in extended glyphs
DEBUG: Final font cell dimensions 550 w x 1200 h
```
