### ISSUE TITLE
Add solidity icon

### ISSUE THREAD

**Issue by Aviksaikat** [ryanoasis/nerd-fonts#1493]
## Summary

 Add solidity and vyper icons.

![image](https://github.com/ryanoasis/nerd-fonts/assets/31238298/0264ac16-a8ec-4c79-b451-27f2bdb5df8c)

**Comment by Finii** [comment]
Thanks for the suggestion.
Maybe you should explain what solidity and vyper are and why it is important to have their logos in Nerd Fonts.

Nerd Fonts is a collection of glyph sets and usually does not add individual glyphs unless in exceptional cases.

**Comment by Aviksaikat** [comment]
`Solidity` & `vyper` are high-level Ethereum programming languages. They are used for smart contracts development.

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095

**Comment by Finii** [comment]
added via devicon
