### ISSUE TITLE
Validate font glyph widths (including 3270)

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#15]
from: ryanoasis/vim-webdevicons/issues/57

reported issues in 3270 font. probably most, if not all fonts

need to validate and test the fonts :worried:

**Comment by rbanffy** [comment]
The newest release of my 3270 font (https://github.com/rbanffy/3270font/releases/tag/v2.0.4) has a lot of fixes (binary release can be downloaded as a zip). I would patch it myself, but you may be faster at that.

It also changes em size and fixes some issues the Google Fonts validation suite complains about.

**Comment by ryanoasis** [comment]
Cool, thanks, congrats! :tada: 

Happy to update it.

Also I might just close this issue because of the age and it would be pretty challenging and/or unnecessary (validating the glyph widths)
