### ISSUE TITLE
There is bug with using version 0.11, with some icons displaying as "?"

### ISSUE THREAD

**Issue by Baiyi27** [ryanoasis/nerd-fonts#1506]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Expected behavior:

There is an issue with using version 0.11, with some icons displaying as "?"
if using version 0.10, this issue will not occur
Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Meslo LG S Regular Nerd Font Complete.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - used `Install-Module -Name Terminal-Icons -Repository PSGallery`
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - pwsh in Windows Terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows v0.11

#### ★ Screenshots (Optional)
![screenshot](https://github.com/ryanoasis/nerd-fonts/assets/65945846/c7e32daa-dc0c-48ed-9d2f-8c40d8593f2b)
The left side of the screenshot is version 0.11, and the right side is version 0.10

**Comment by Baiyi27** [comment]
The screenshot above only shows some icons with issues and others. 
Sorry, I am using the Windows version of Windows 11 22h2

**Comment by Finii** [comment]
Sorry to see you have problems.

What do the version numbers 0.10 and 0.11 in the screenshot mean?
As that seems to be the same installed font (?) that might be the TerminalIcons module?
Than the problem must be the module and not the font?

Sent from Nine

________________________________

**Comment by Baiyi27** [comment]
@Finii This version is the version of this module. 0.11.0 is the latest version and there may be screenshot issues. 0.10.0 is the previous version, so there will be no display of "?".

**Comment by Finii** [comment]
Maybe 0.10.0 needs a Nerd Font < `v3.x.x` and they updated the codepoints to Nerd Fonts `v3.x.x+` on 0.11.0.
Probably check which _version_ the nerd font font has.
But obviously you managed to fix this yourself already! :+1:
