### ISSUE TITLE
10x times faster docker patch

### ISSUE THREAD

**Issue by nobk** [ryanoasis/nerd-fonts#1507]
I am using docker run nerdfonts/patcher for patch my custom iosevka fonts.
But I find that the fontforge command line is single process, only one CPU core are using.
So I changed the docker script, make it use all CPU cores.
And get 10x times faster when run docker patch on an i7-12700K.
Only need 2 lines modification.

**Comment by Finii** [comment]
I have only a Ryzen7 3700U so I would expect a speedup of 3.5, but that still is significant!

:tada:

Well, that's the reason why I use `gotta-patch-em` with `-j`. That also has the advantage to read the config file.
I guess we should someday unify the config files and incorporate them into the patcher itself. ... Sigh
