### ISSUE TITLE
Nerd font spacing wrong in gnome terminal

### ISSUE THREAD

**Issue by mcp292** [ryanoasis/nerd-fonts#1511]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Font spacing wrong in `gnome-terminal`. Downloaded Hack, Noto, RobotoMono, and FiraCode in the same manner described below. Same issue with all.

Expected behavior:

Correct font spacing (see correct rendering in Screenshots).

Example symbols:

See Screenshots.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Hack Nerd Font Mono, Regular
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Downloaded tar from [assets section of release](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.1.1). Extracted files into `~/.local/share/fonts/Hack`.
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - `gnome`
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Fedora Linux 39 (Workstation Edition)

#### ★ Screenshots (Optional)

Default "Monospace" (Noto Sans Mono, Regular):
![Screenshot from 2024-02-07 17-02-53](https://github.com/ryanoasis/nerd-fonts/assets/49123398/4fd492c7-aef4-4903-810a-84446a12cc4c)

Hack Nerd Font Mono, Regular:
![Screenshot from 2024-02-07 17-03-40](https://github.com/ryanoasis/nerd-fonts/assets/49123398/87b5b68a-4c6e-4eb0-a7f5-7668738e8532)
(Notice how it stretched my terminal on change. Resizing or re-opening terminal did not fix spacing.)

Settings:
![Screenshot from 2024-02-07 17-05-53](https://github.com/ryanoasis/nerd-fonts/assets/49123398/a5c17c52-1dac-47d4-a9d7-c2d1ed9b566b)

Correct rending in Fonts app despite this:
![Screenshot from 2024-02-07 17-05-59](https://github.com/ryanoasis/nerd-fonts/assets/49123398/ea32d913-7ac7-4c55-a911-09191acd40d4)

**Comment by Finii** [comment]
Sorry to hear of your problem ... investigating...

Downloaded 3.1.1 from release page as you linked above.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/25a05c4b-1f90-4176-a671-7ac9ec0a3718)

This looks ok on my machine:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/78fb95f2-add3-4b1a-ad64-f9b7e44041d4)

I work on `tilix` with `Delugia` (seen in the background), and the font does look different. I do not know any Hack-specific signature shape to look for, but at least it is selected, looks different than my default, and does not have the issue you have.

Did you close all `gnome-terminal` instances after installing the fonts?
Also your gnome terminal looks slightly different from mine.

Ah, typing `exit` into the terminal I notice how ~~**ugly**~~ uneven that looks, compare with Delugia below ;-)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/82ef2896-fe14-4a9b-8885-3a01bce8f677)

But I guess the zero with a vertical-bar-y dot is signature for Hack?
Seems like I have Hack in the `gnome-terminal` there.

I guess that is not a problem of the font but of your setup? Maybe try rebooting. Does the zero look like a Hack zero in your terminal?

**Comment by mcp292** [comment]
Thanks for your help! Reboot fixed it. That's my bad.

![Screenshot from 2024-02-08 11-43-46](https://github.com/ryanoasis/nerd-fonts/assets/49123398/fda71fed-a2c6-4721-81f2-cbd7a67766ec)
![Screenshot from 2024-02-08 11-49-03](https://github.com/ryanoasis/nerd-fonts/assets/49123398/e2c0bc07-ff6f-47b1-8df9-161e02e37057)

**Comment by mfdorst** [comment]
I also experienced this issue, and closing all terminal windows and reopening them fixed it. I wonder if it has to do with the fonts being installed while the terminal window is open.

**Comment by Finii** [comment]
For `tilix` when I want to see newly installed fonts without closing all preexisting windows, `tilix --new-process` comes in handy. Usually the font list is only read in on application start, and opening yet another window is no restart ;)
