### ISSUE TITLE
request nerd font patch for Titillium Web font

### ISSUE THREAD

**Issue by mh-firouzjah** [ryanoasis/nerd-fonts#1512]
Hello there, and thank you for your fantastic work! I've been pondering whether there exists a geekier rendition of the Titillium Web font (Titillium Web Nerd Font), but alas, my search has proven fruitless. So, I come to you with a humble request: would you be willing to create such a version? Your consideration would be greatly appreciated!

> The Qt Development brand uses the corporate typeface of the Qt brand system, Titillium Web.   
> ### Titillium Web is an open-source, free typeface available from the Google Fonts font library.

**Comment by Finii** [comment]
You use this in a terminal or in some IDE?

(Btw I strongly dislike the _We are the world_ attitude of Qt on C++ conferences 🙄, luckily for Titillium it is a stand alone project that just happens to be also used by these guys.)

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
