### ISSUE TITLE
Glyph Request: Ada Programming Language

### ISSUE THREAD

**Issue by brownts** [ryanoasis/nerd-fonts#1513]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

It appears the icon for the Ada programming language is missing.  There is an example icon available from file-icons.

https://github.com/file-icons/icons/blob/master/svg/Ada.svg

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_

**Comment by Finii** [comment]
Thanks for the suggestion!

I can not see where the Ada icon comes from, all Ada related resources seem to not-have it.
See it used sometimes used by 3rd party websites. But who and why attached it to 'Ada'?

Tried to find the commit with some comment in file-icons, but it was in the initial big blob of icons.

**Comment by brownts** [comment]
It appears it was the result of a community contest for an Ada language mascot.
- https://getadanow.com/#mascot
- https://test.adaforge.org/Goodies/Ada_Logo/

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
