### ISSUE TITLE
Getting an "illegal instruction" error

### ISSUE THREAD

**Issue by ThinkByDesign** [ryanoasis/nerd-fonts#1522]
#### 🗹 Requirements

FYI - the wiki page with a link to the template (https://github.com/ryanoasis/nerd-fonts/wiki/Reporting-Issues) gets a 404 error, so I'm trusting that the template below is correct.

#### 🎯 Subject of the issue

Experienced behavior:
The homepage (https://webinstall.dev/nerdfont/) says to run the following command for MacOS in terminal.app:
curl -sS https://webi.sh/nerdfont | sh 

When I do that (in zsh, though it shouldn't matter since it is piped to sh), I see the following:

>>> Welcome to Webi! - modern tools, instant installs.  <<<
    We expect your experience to be absolutely perfect!

    Success? Star it!   https://github.com/webinstall/webi-installers
    Problem? Report it: https://github.com/webinstall/webi-installers/issues
                        (your system is Darwin/arm64 with libc & curl)
sh: line 135: 72255 Done                    echo "${my_abs}"
     72256 Illegal instruction: 4  | sed "s:^${my_rel}:~:"

I have confirmed that sed is installed.
If I run the sed command by itself I get the following:
77708 illegal hardware instruction  sed "s:^${my_rel}:~:"

Expected behavior:
I was expecting it to install one or more of the nerd fonts.

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - I don't think I got that far
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - [(https://webinstall.dev/nerdfont/)]
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Stock/standard terminal.app
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - MacOS 14.2.1 (Sonoma) on an M2 Max MacBook

**Comment by Finii** [comment]
Well, I would NEVER do `curl ... | sh`. How bad can it be.

This is an issue with webinstall, we can do nothing to fix it. Webinstall is a 3rd party project - they just take the released files from here.

Anyhow, I would suggest using Homebrew to install the font(s) - if you need a helper thing:
https://github.com/ryanoasis/nerd-fonts?tab=readme-ov-file#option-2-homebrew-fonts

I personally would always just download the release archive and click the fonts in Finder:
https://github.com/ryanoasis/nerd-fonts/releases
