### ISSUE TITLE
Icons are not rendered properly when nerd font is used as a fallback font in urxvt

### ISSUE THREAD

**Issue by BeliyDot** [ryanoasis/nerd-fonts#1525]
I have wanted to have icons in lf, so I've installed one of nerd fonts (Cousine Nerd Font). Because Cousine wasn't looking same as Courier Prime, I've decided to use Courier as a base font, and Cousine as a fallback font. But the problem is, icons from nerd font are cut off in the termnial (urxvt, or to be more precise, rxvt-unicode-truecolor-wide-glyphs). For first I thought it was lf problem, but I saw it in neovim too.

https://github.com/ryanoasis/nerd-fonts/assets/133781890/42a46955-f6c9-467a-a56a-ce54740d62e1

Specs:
```
OS: Arch Linux x86_64 
Host: 82S9 IdeaPad Gaming 3 15IAH7 
Kernel: 6.7.6-arch1-1 
Shell: bash 5.2.26 
WM: xmonad 
Terminal: urxvt 
Terminal Font: courier-prime 
CPU: 12th Gen Intel i5-12450H (12) @ 4.400GHz 
GPU: NVIDIA GeForce RTX 3050 Mobile 
```

My ~/.Xresources:
```
URxvt*font: xft:courier-prime:bold:size=12,xft:Cousine Nerd Font:size=12
URxvt.geometry: 400x400


URxvt.reverseVideo: true
URxvt.scrollBar: false
URxvt.transparent: true
URxvt.tint: white
URxvt.shading: 10
```

Btw, when I use only the nerd font, the problem disappears.
I can assume that this problem refers to a size of a glyph box/character cell, but IDK how to change it without changing the base font size. And the problem persists until I set the size of nerd font to 6, but the icons are too small with that size.

**Comment by Finii** [comment]
I would suggest you just self-patch `Courier Prime`.

This seems no problem with the Nerd Fonts but struggling with the client setup, so sorry, I can not help here.
