### ISSUE TITLE
Several patched fonts are not included in the overall release archive

### ISSUE THREAD

**Issue by cinerea0** [ryanoasis/nerd-fonts#1529]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

In the version 3.1.1 release archive the following directories under patched-fonts do not contain any font files:
* 0xProto
* CascadiaMono
* CommitMono
* D2Coding
* GeistMono
* IntelOneMono
* IosevkaTermSlab
* MartianMono
* Monaspace

Expected behavior:

It is my understanding that all directories under patched-fonts should contain font files except for those with licensing issues.

Example symbols:

Not applicable.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - I discovered this while attempting to use 0xProto.
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://github.com/ryanoasis/nerd-fonts/archive/refs/tags/v3.1.1.tar.gz
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - foot
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Void Linux, I am the maintainer of the nerd-fonts package for that distribution.

#### ★ Screenshots (Optional)

Not a screenshot, but tree output of the patched-fonts directory: 
[tree.txt](https://github.com/ryanoasis/nerd-fonts/files/14470614/tree.txt)

**Comment by Finii** [comment]
Well, to keep the repo itself of manageable size and still add new fonts the release process changed as this
* Releases are available as release artifacts on the release page
* The repo archive is the source for the release and does not contain patched fonts

Thus patched fonts are not committed to the repo anymore. For easier transition this changed only for new fonts now, but the legacy in-repo releases will be dropped in the future for all fonts.

The the difference in the README of on old font and a new one (the ones you mentioned)

Old: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack

```
Option 1: Download already patched font

For a stable version download a font package from the release page
Or download the development version from the folders here
```

New: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Monaspace

```
Option 1: Download already patched font

For a stable version download a font package from the release page
Direct links for Monaspace.zip or Monaspace.tar.xz
```

If you need to download some/all patched fonts you can use for example
https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/fetch-archives.sh
