### ISSUE TITLE
AIGA Symbols

### ISSUE THREAD

**Issue by Eremiell** [ryanoasis/nerd-fonts#153]
Hi!

I found out your wonderful work only recently and I'd like first of all to express my appreciation.

While I philosophically side more with the fallback approach than to patching, especially as it theoretically automagically works with any and all fonts without extra work, what you have here is probably the most complete collection of glyphs I've seen so far.

Interestingly, there's very ancient and acknowledged icon set, you don't contain at the moment and that's the aforementioned AIGA Symbol set.

http://www.aiga.org/symbol-signs/

I've used it few times in the past and while I understand it's not as universally useful to devs as octicons or devicons, it might be a nice addition.

Alternatively if it doesn't sound like a great core idea (in the end, it's more public transport than online space iconography), it would be nice to have it at least as default off patching option.

**Comment by ryanoasis** [comment]
@Eremiell Thanks for this suggestion I will check it out :smile: 

Thanks for the kind words. Also yes I understand your reason for the fallback approach (I was completely new to that even existing when starting this :blush:) but it seems they both have their place.

Btw, there is a `--custom` flag in the patcher but having an explicit option is always better :smile:

**Comment by Finii** [comment]
> http://www.aiga.org/symbol-signs/

Link seems to have been moved here: https://www.aiga.org/resources/symbol-signs

Cave: The actual set is in a dropbox link. I archived the content if need be. There is no license given in the archive.

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
