### ISSUE TITLE
Font Patch Request for Kode Mono

### ISSUE THREAD

**Issue by fabiocosta0305** [ryanoasis/nerd-fonts#1533]
Please, this font is really neat

https://fontesk.com/kode-mono-typeface/

**Comment by Finii** [comment]
Thanks for the suggestion.

I guess without any description why this font is better than any other and what differentiates it from the already prepatched fonts, this will get hard.

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
