### ISSUE TITLE
Request: update 0xProto to latest version

### ISSUE THREAD

**Issue by MIvanchev** [ryanoasis/nerd-fonts#1534]
**Requirements**

- [ x ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [ x ] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [ x ] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

** Description **

0xProto Nerd Font is currently missing a lot of glyphs (i.e. 0x00B0 degree symbol) which do exist in the most recent upstream release. It would be great if you friends can update it :)

**Comment by Finii** [comment]
Fixed via
* #1516 

available after 3.2.0 release
