### ISSUE TITLE
Material Icons

### ISSUE THREAD

**Issue by Eremiell** [ryanoasis/nerd-fonts#154]
A similar yet completely different story to my previous enhancement proposal are Material fonts.

Originally made by Google, infused by made user made icons, it's a huge icon set connected very closely to today's web, mobile devices, etc.

The challenge in this one might be it's size.

https://materialdesignicons.com/
https://material.io/icons/

The font, especially the community version, is just huge. While I could imagine using quite some of the icons on daily basis, I'm not sure (mostly because I don't see as much as I'd like to into font space encoding and what's bearable) if it would be feasible to include it into nerd fonts.

Still, I found no mention of it anywhere, so I wanted to bring it to the sight.

**Comment by ryanoasis** [comment]
Yep thanks again. I am aware of them but I honestly haven't explored the possibility of adding them too deeply yet :smile: 

Yeah I am not sure about the feasibility either, that is a good concern to raise :thinking: 

> Still, I found no mention of it anywhere, so I wanted to bring it to the sight.

Yep, I can understand that

**Comment by georgelemental** [comment]
This project could be helpful:
https://zavoloklom.github.io/material-design-iconic-font/index.html

**Comment by ryanoasis** [comment]
Thanks @georgelemental 👍

**Comment by ryanoasis** [comment]
@georgelemental That does look like a nice project unfortunately it looks like it is now unmaintained:
- last commit was 2 years ago
- https://github.com/zavoloklom/material-design-iconic-font/issues/110

**Comment by akatrevorjay** [comment]
Interesting note about, say, using at least a subset of MDI is that they are all sized exactly the same too. Do we even have enough character slots left that are relatively unused? Honest question.

**Comment by ryanoasis** [comment]
@akatrevorjay That is a very legit concern/question.

Just in the Private Use Area we have up to 6.4k codepoints, it can be much larger if we can use the full unicode encoding.

> The Basic Multilingual Plane includes a PUA in the range from U+E000 to U+F8FF (6400 code locations). Plane Fifteen and Plane Sixteen have a PUAs that consist of all but their final two code locations, which are designated non-characters. The PUA in Plane Fifteen is the range from U+F0000 to U+FFFFD (65534 code locations).
