### ISSUE TITLE
BlexMono and IBM Plex Mono weights don't match

### ISSUE THREAD

**Issue by matterhorn103** [ryanoasis/nerd-fonts#1541]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
The BlexMono Nerd Fonts are lighter than the IBM Plex Mono fonts on my system with the same weight name.

Expected behavior:
1:1 weight correspondence.

Extra information:
Prior to updating to KDE Plasma 6.0.1 I already had lsd set up and working with the symbols-only Nerd Font as a fallback font. For some reason that stopped working and I will have to reconfigure my fonts. While exploring the other approach (using the patched font) I noticed the mismatch in weights.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - BlexMonoNerdFont-Medium.ttf (but same applies to others)
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/IBMPlexMono.tar.xz
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Konsole 24.02.0
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - OpenSUSE Tumbleweed 20240311

#### ★ Screenshots (Optional)

Above is BlexMono Medium, bottom is IBM Plex Mono Medium as obtained from the OpenSUSE Tumbleweed main repos. Both are at 10pt.

![Screenshot_20240314_133419](https://github.com/ryanoasis/nerd-fonts/assets/83813148/6418eff7-e9b6-4657-bd2b-1964bbc4ed56)
![Screenshot_20240314_133453](https://github.com/ryanoasis/nerd-fonts/assets/83813148/73875fbf-9bdd-407c-8293-f75708554c9f)

**Comment by matterhorn103** [comment]
By the way, the reason that using `SymbolsNerdFontRegular.ttf` as a fallback font no longer works in KDE Plasma 6 is due to is due to [this "bug"](https://bugs.kde.org/show_bug.cgi?id=478549).

It actually comes down to a [deliberate change](https://bugreports.qt.io/browse/QTBUG-110502) in Qt 6.5 to disable font fallback for PUA glyphs.

Hopefully if anyone looks to report the issue here they will find this comment.

**Comment by Finii** [comment]
Issue **1541** :-)
Well, 1541 will always remind me of my first very fast computer mass storage:
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/a56d183a-48e8-4d4b-b261-f870c8f67650)
Where we thrilled when it came about in the early 1980s...

Sorry, I digress.

`Konsole`; hmm, can you check this with some non-terminal program first, like Libreoffice Writer?
I have no `Konsole` installed and thus can not try (without leaving my lazy mode).

OH!! I see it, never mind. This should be an easy fix, hold on...

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/2af66a58-c8f8-48ba-a689-d671feee0f93)

**Comment by matterhorn103** [comment]
Hmm you're right, in LibreOffice Writer for example they look identical. Perhaps something to do with KDE/Plasma/Qt then – the differences are there both in Konsole and in the fonts section of the system settings menu. I'll investigate.

**Comment by Finii** [comment]
Well, I guess the problem is this:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/dc8c9037-e41a-4ad2-97b5-48a5957e8ab1)

The hinting in `otf` and `ttf` is completely different, maybe that is the problem. You can try installing the `ttf` version of IBM Plex from their repo https://github.com/IBM/plex/releases (or from our repo under `src/unpatched-fonts/`).

And I just noticed that they have had updates :grimacing: 

If you prefer to keep the Tumbleweed font, you could also try a self patch. That should be easy enough, for example with the docker-patcher (if you ever used docker before).

:thinking: :thought_balloon: Why has Tumbleweed an even older font than we have?

**Comment by Finii** [comment]
They did change the hinting in the 2.4 version (we have 2.3)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/e924b921-6654-4cac-b7cb-4149291b0b69)

**Comment by Finii** [comment]
Naming looks ok on our side (some time ago we had problems with fonts that had the wrong name).

**Comment by Finii** [comment]
AH, gotcha!

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ef5a7cfa-5827-4595-9a49-e288e2ca7c66)

lowestrecppem controls the hinting of small sizes; this should probably not be different.

**Comment by Finii** [comment]
> It actually comes down to a [deliberate change](https://bugreports.qt.io/browse/QTBUG-110502) in Qt 6.5 to disable font fallback for PUA glyphs.

How ridiculous is that? `oldherl` is of course right. The statement in the top indicates that any PUA glyph, even if available in the current font, is mapped to some random fallback font. That would be broken of course. But Qt knows better, as usual, than decades of people who thought how font systems can work most efficiently :roll_eyes:

**Comment by matterhorn103** [comment]
Ok yes, that seems to be it, the otf font is being rendered significantly bolder than the ttf in both Konsole and Kate, even with the most recent 6.4 release.
