### ISSUE TITLE
Support fonts with double-width icons in xterm/rxvt-unicode/zsh/vim/…

### ISSUE THREAD

**Issue by powerman** [ryanoasis/nerd-fonts#155]
https://github.com/powerman/wcwidth-icons provides .so library for LD_PRELOAD and patch for vim which enable support for full size icons in urxvt etc. It doesn't looks like this project is suitable for merging into nerd-fonts, but it may worth mention it in nerd-font's README/FAQ.

**Comment by ryanoasis** [comment]
@powerman Thanks. You may feel free to add/edit the Wiki :smile: Just created this page for instance: https://github.com/ryanoasis/nerd-fonts/wiki/Terminal-Emulators

**Comment by agriffis** [comment]
@powerman Wow, that's impressive! The wcwidth-icons README definitely needs some screenshots though ;-)

**Comment by ryanoasis** [comment]
Thanks people :smile: 

Closing via:
- https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting#why-do-the-glyphs-look-small-squished-or-not-full-width
- https://github.com/ryanoasis/nerd-fonts/wiki/Terminal-Emulators#urxvt
