### ISSUE TITLE
Include e6b2 in wiki's Glyph Sets section

### ISSUE THREAD

**Issue by madmaxieee** [ryanoasis/nerd-fonts#1552]
#### 🗹 Requirements

Include e6b2 in wiki's Glyph Sets section. The TOML icon (26b2) is included in the font and show on the cheatsheet in the website, but not included in the wiki's Glyph Sets.

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

Documentation left out some codepoints in the font.

Expected behavior:

Documentation to match the actual content of the font.

Example symbols:


#### 🔧 Your Setup

N/A

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - 
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - 
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - 

#### ★ Screenshots (Optional)
![CleanShot 2024-03-23 at 03 08 54](https://github.com/ryanoasis/nerd-fonts/assets/76544194/2676ea98-c366-4871-b7a1-6dc3af49f8cf)
![CleanShot 2024-03-23 at 03 07 19](https://github.com/ryanoasis/nerd-fonts/assets/76544194/747434de-7abb-4c90-8de4-f28e5acc7be1)

**Comment by Finii** [comment]
Fixed, thanks for reporting!

**Comment by Finii** [comment]
@allcontributors please add @madmaxieee for doc
