### ISSUE TITLE
Incorrect glyph of `nf-seti-rust`

### ISSUE THREAD

**Issue by chardon55** [ryanoasis/nerd-fonts#1556]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

It shows an arrow glyph.

Expected behavior:

It should show the logo of the Rust programming language.

Example symbols:

Icon: 
Class: `nf-seti-rust`
UTF: \ue68b

Btw bold fonts are fine. (****)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Fire Code.ttf
   - Lilex.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Arch Linux official package
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Alacritty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Arch Linux

#### ★ Screenshots (Optional)

<img width="56" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/44740171/43e2b0a4-ffe7-4c3c-9843-8e0a96ae9687">

**Comment by Finii** [comment]
Hmm, both the Regular and the Bold font contain Rust at `E68B`:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/e94b40ba-ccc2-4238-96aa-8fae74e925e1)

And even trying with `alacritty` I can not reproduce. Note `fc-list` and my `alacritty.yml` and the debug output.
Something with your setup must be awry?

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/48e0556f-edbb-4266-a51c-3fb2f2d4b11f)

**Comment by chardon55** [comment]
Oh strange. I guess maybe it's conflicted with other font patches on my computer. I'll check again.

Sorry for the trouble.
