### ISSUE TITLE
Add bun glyph

### ISSUE THREAD

**Issue by gu5e** [ryanoasis/nerd-fonts#1565]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Describe the solution you'd like**
Add the bun logo to the set

**Describe alternatives you've considered**
Using the 🍞 emoji.

**Comment by Finii** [comment]
Thanks for the suggestion!

Can you explain what 'the bun logo' is? Maybe with a link?

**Comment by zachcoyle** [comment]
@Finii It's a new js runtime. https://bun.sh/
![Bun Logo](https://github.com/ryanoasis/nerd-fonts/assets/908716/780b2b50-848f-4614-ac71-ba6b2258e8e6)

**Comment by Finii** [comment]
Thanks!

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095

It will be evaluated on next release.
