### ISSUE TITLE
Request adding full collection of font-linux

### ISSUE THREAD

**Issue by LER0ever** [ryanoasis/nerd-fonts#157]
#### Request adding full collection of font-linux

Currently the font-linux logos is not complete. Theres 24 icons in font-linux and only 20 in nerd fonts. As is said in the README, it's a icon font of popular linux distro, so I think each of the distro in there is a major one (or maybe not). I'm personally using Manjaro, AOSC and LinuxMint, and two of them are not in the Nerd Fonts. Since font-linux is not that big in size, it would be really great if full collection is added to nerd fonts.

#### Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ **Knack Nerd Font**
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ **Doesn't matter**
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ **Linux [Manjaro, AOSC]**

**Comment by ryanoasis** [comment]
@LER0ever Thanks I did not know this! :smile: :+1:

**Comment by ryanoasis** [comment]
Project has since changed name and purpose a bit. Now called "font-logos".

Here is a screenshot of what we have in Nerd Fonts vs what's available in the current font-logos:

![selection_010](https://user-images.githubusercontent.com/8083459/36074767-c6609fce-0f12-11e8-8238-9ff91553bc16.png)

**Comment by sambadevi** [comment]
Coming from bhilburn/powerlevel9k#751 I would like to request the OpenSUSE Tumbleweed Icon to be included as well

Also, the apple and android icons are already in Nerd Fonts afaik (Using `Knack Nerd Font`
 as well)
Apple being `\uE711` and `\uF179`
Android as `\uE70E` and `\uF17B`

**Comment by ryanoasis** [comment]
@sambadevi Yeah there are definite duplicates! Which happens when aggregating so many sets :smile: however right now there is no plan to try to remove duplicates, we let them coexist.

Is OpenSUSE Tumbleweed part of font-logos ? I don't see that only OpenSUSE

**Comment by sambadevi** [comment]
Ah my bad, no it’s not, would be a nice addition but seems like it’s not included in font-logos

**Comment by ryanoasis** [comment]
@sambadevi Looks pretty cool. Something similar to the left side of this image: https://news.opensuse.org/wp-content/uploads/2015/01/Tumbleweed.png ?

**Comment by sambadevi** [comment]
@ryanoasis I meant this one https://en.opensuse.org/Portal:Tumbleweed

**Comment by ryanoasis** [comment]
@sambadevi Ah gotcha. Let's see, I wonder if Font Linux has any plans to add it...
