### ISSUE TITLE
Where to add the Typst Icon?

### ISSUE THREAD

**Issue by Gaspartcho** [ryanoasis/nerd-fonts#1587]
This is not really a feature request, but I was planning on adding the [Typst](https://typst.app/) icon from [Iconify](https://icon-sets.iconify.design/simple-icons/typst/). However, I am not sure if I should add it directly to this repo, or add it to another one from which nerd-fonts gets its icons from (like [font-logos](https://github.com/lukas-w/font-logos)).

What should I do?

**Comment by Finii** [comment]
This is the 'backlog' of icon additions here, well, most will never be added here. Nerd Fonts is a icon-set aggregator and not an icon aggregator.

https://github.com/ryanoasis/nerd-fonts/discussions/1095#discussioncomment-4821804

**Comment by Finii** [comment]
Closing as I guess the question is answered.
Reopen if need be.
