### ISSUE TITLE
Some update changed PROPO glyphs size

### ISSUE THREAD

**Issue by DarkReaper231** [ryanoasis/nerd-fonts#1588]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
The propo glyphs were just fine couple of versions ago, I am not sure which version broke it because I haven't updated in like 3 months but
now the glyph sizes are just all over the place
some of them are just less bold than before

Also the leaf looked better before but that's just my opinion, the globe too

Expected behavior:
It should be same as it was before

Example symbols:
The problematic ones are: , , , , 󰖁, , , 

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Inconsolata Nerd Font Propo
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://archlinux.org/packages/extra/any/ttf-inconsolata-nerd/
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Arch Linux

#### ★ Screenshots (Optional)
Before:
![image](https://github.com/ryanoasis/nerd-fonts/assets/38611351/fc96f65e-b2a6-46d8-9331-a618472bf422)
![image](https://github.com/ryanoasis/nerd-fonts/assets/38611351/c2babc80-ccc3-48ba-8173-9d3e384652cb)
![image](https://github.com/ryanoasis/nerd-fonts/assets/38611351/b0e3b9a7-62b4-414f-be22-1e6c67f08f05)

After:
![image](https://github.com/ryanoasis/nerd-fonts/assets/38611351/63a7ea76-7eff-40a4-9533-c840c0c3cddb)
![image](https://github.com/ryanoasis/nerd-fonts/assets/38611351/cd9c0d6f-a7c4-430b-adc7-0bb0f1dc31f3)
![image](https://github.com/ryanoasis/nerd-fonts/assets/38611351/c3aa81cd-3d53-470b-8509-86dd4b99afd1)

**Comment by Finii** [comment]
Sorry to hear of your problems.

The icons listed as problematic are
| `F06C` | `F1B6` | `F269` | `F011` | `F0581` | `F048` | `F051` | `F2C9` |
|---|---|---|---|---|---|---|---|
| `fa-leaf` | `fa-steam` | `fa-firefox` | `fa-power_off` | `md-volume_off` | `fa-backward_step` | `fa-forward_step` | `fa-temperature_half` |

* With the exception of 'volume off' all icons come from Font Awesome
* When you use `Nerd Font Propo` the icon sizes are untouched by the patching
* Any size differences come from upstream, i.e. from updating Font Awesome which has different sizes now

Lets have a look, leaf seems unchanged

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/d718f108-9499-46ec-b157-49ab3ffa7e37)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/d2f4ad1b-a90d-4de7-b048-2b1917c74f33)

Maybe `firefox-browser` is more what you like (a bit taller?)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/8d76160a-494a-4dd2-b8fa-213be10410fc)

Backward got just more squarish

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/04c4f887-e1e4-4097-ac60-b143f4234e4f)

Maybe use another taller set for 'backward', for example `nf-md-skip_previous`?

So updates in design always will look strange to some while others see the old icons as too-old-fashioned and out of place.

**Comment by Finii** [comment]
I'm not sure yet, but I guess this is a not-a-bug unless I can be convinced it is.
Labeling but keeping open.

**Comment by Finii** [comment]
Implemented a small (10%?) increase in size, but some icons are just smaller after the update, and we do not scale them generally (just as a whole).
