### ISSUE TITLE
Using Windows EUDC Feature as a Font-Fallback with Nerd Fonts

### ISSUE THREAD

**Issue by sharkusk** [ryanoasis/nerd-fonts#159]
Hi Ryan,

I found the following tip to be useful when using Nerd Fonts under Windows and thought I would mention it in case you want to add it to your docs.

The EUDC feature of Windows can be used to define a fall-back font that will be used for Glyphs that are not found in the current font.  This means that a single NF font can be installed on a Windows machine, and the NF Glyphs will then be shown for all other fonts in the system.  No need to patch them all...

Info on EUDC can be found here:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd317836(v=vs.85).aspx 

Here's the registry entry I use for my system.  Please note: 1252 is the Windows page code for English, other languages will need to use a different numeric value for the page code.

```
Windows Registry Editor Version 5.00
;
; More info here: https://msdn.microsoft.com/en-us/library/windows/desktop/dd317836(v=vs.85).aspx
;
[HKEY_CURRENT_USER\EUDC\1252]
"SystemDefaultEUDCFont"="DejaVu Sans Mono for Powerline Nerd Font Complete Windows Compatible.ttf"
```

Regards,
Marcus

**Comment by agriffis** [comment]
Tangentially, I wonder if it would be possible to patch OS X's last resort font to include Nerd glyphs. If so, then it would be possible to use Nerd glyphs on all the three major operating systems without patching all the fonts.

https://en.m.wikipedia.org/wiki/Fallback_font#Apple.27s_Last_Resort_font
http://www.unicode.org/policies/lastresortfont_eula.html?utm_source=tuicool

**Comment by ryanoasis** [comment]
Hey Marcus! It's been a while :smile: . Thanks for this, I had no idea. Seems like a cool option for those who don't want to go the patched fonts route :+1: 

Good idea to add both of these to the wiki. I am totally up for that. Not sure when I would get around to that.. I did a lot of wiki work recently ... now I am on a website dev binge :laughing: 

---

By the way if either can feel free to contribute to the wiki to make it better if you desire. No worries there

**Comment by pablo-tapia** [comment]
@sharkusk thanks for the tip, I was struggling to make the NerdFonts work with the Ubuntu Bash for Windows and this solved the issue.

**Comment by ryanoasis** [comment]
This was great, closing because it is now in the wiki: https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points

**Comment by agriffis** [comment]
@ryanoasis FWIW I don't see the information from this issue on that wiki page
