### ISSUE TITLE
Glyph request: ddev

### ISSUE THREAD

**Issue by hanoii** [ryanoasis/nerd-fonts#1590]
I use https://github.com/ddev/ddev a lot, would love to have the logo available as a symbol to add it to my terminal windows!

Logos: https://ddev.readthedocs.io/en/stable/developers/brand-guide/#logos

I read #1095 but it says to also add the issue, so here it is.

cc @rfay

**Comment by Finii** [comment]
Thanks for the request! You did exactly use the right procedure :green_heart:

**Comment by hanoii** [comment]
Great, now how can one more this forward :)? Any 🍺 buying ?

**Comment by Finii** [comment]
After having a glance at ddev

> available as a symbol to add it to my terminal windows

where would you add it in a terminal? :scratch head:

> Any 🍺 buying

Sure :-D

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095

It will be evaluated on next release.
