### ISSUE TITLE
Patcher overrides Fira Code progress bars and spinners in fonts

### ISSUE THREAD

**Issue by AlexKurisu** [ryanoasis/nerd-fonts#1593]
#### 🗹 Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Patcher overrides Fira Code progress bars and spinners with Font Awesome icons, causing compatibility issues in terminals that have already implemented custom box-drawing for them and also with software that has support for those symbols as progress bars and spinners.

Expected behavior:
Nerd Fonts patcher should not override those symbols.

Example symbols:
U+EE00-U+EE0B (            )

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - IosevkaTermNerdFont-{Regular,Bold,Italic}.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://archlinux.org/packages/extra/any/ttf-iosevkaterm-nerd/
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Wezterm, Kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Arch Linux

#### ★ Screenshots (Optional)

![image](https://github.com/ryanoasis/nerd-fonts/assets/60626727/b68f279f-633e-45d8-b5c8-3cab10df235b)
![image](https://github.com/ryanoasis/nerd-fonts/assets/60626727/9c75452a-0d69-4dfa-a9d3-226f50ae5eaf)

**Comment by Finii** [comment]
Ugg, that is not good news.

> in terminals that have already implemented custom box-drawing for them and also with software that has support for those symbols as progress bars and spinners

Can you list some and maybe show (with an old font) what they do?

**Comment by Finii** [comment]
* #1345

**Comment by AlexKurisu** [comment]
>Can you list some and maybe show (with an old font) what they do?

Well, i have only one, and it is patched `pacman` package manager:
![image](https://github.com/ryanoasis/nerd-fonts/assets/60626727/138d8985-cfcf-4e04-9048-9fb043aaa820).
This is how it looks in `kitty`:
![image](https://github.com/ryanoasis/nerd-fonts/assets/60626727/71fea971-48ea-427b-80c5-473c3f66b4c0)
And this is how new Font Awesome symbols that replace them look in `kitty`:
![image](https://github.com/ryanoasis/nerd-fonts/assets/60626727/94d4464d-7d32-47bc-bd94-e07241f30635)

**Comment by Finii** [comment]
> and it is patched pacman package manager

Can you give instructions how and what 'patched' means? :->
