### ISSUE TITLE
`U+F001` displayed incorrectly in some Ubuntu and UbuntuMono font variations

### ISSUE THREAD

**Issue by eliminmax** [ryanoasis/nerd-fonts#1595]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

`U+F001` renders as a music note except when bold and/or italic, in which case it's what appears to be a ligature of "fi".  I first discovered this in the kitty terminal emulator, but the issue also occurred in XTerm with the font set to UbuntuMono Nerd Font

In LibreOffice, I set up a spreadsheet where I checked how `U+F001` was rendered in each of the following font families, with columns for regular, bold, italic, and bold italic (in a `details` block for space's sake:

<details><summary>view font list</summary>
<ul>
<ul>
<li><code>UbuntuMono Nerd Font</code></li>
<li><code>UbuntuMono Nerd Font Mono</code></li>
<li><code>UbuntuMono Nerd Font Propo</code></li>
<li><code>Ubuntu Nerd Font</code></li>
<li><code>Ubuntu Nerd Font Cond</code></li>
<li><code>Ubuntu Nerd Font Light</code></li>
<li><code>Ubuntu Nerd Font Med</code></li>
<li><code>Ubuntu Nerd Font Propo</code></li>
<li><code>Ubuntu Nerd Font Propo Cond</code></li>
<li><code>Ubuntu Nerd Font Propo Light</code></li>
<li><code>Ubuntu Nerd Font Propo Med</code></li>
<li><code>UbuntuSansMono NF</code></li>
<li><code>UbuntuSansMono NFM</code></li>
<li><code>UbuntuSansMono NF Medium</code></li>
<li><code>UbuntuSansMono NFM Medium</code></li>
<li><code>UbuntuSansMono NFM SemiBold</code></li>
<li><code>UbuntuSansMono NFP</code></li>
<li><code>UbuntuSansMono NFP Medium</code></li>
<li><code>UbuntuSansMono NFP SemiBold</code></li>
<li><code>UbuntuSansMono NF SemiBold</code></li>
<li><code>UbuntuSans NF</code></li>
<li><code>UbuntuSans NF Medium</code></li>
<li><code>UbuntuSans NFP</code></li>
<li><code>UbuntuSans NFP Medium</code></li>
<li><code>UbuntuSans NFP SemiBold</code></li>
<li><code>UbuntuSans NF SemiBold</code></li>
</ul>
</li>
</ul>
</details>

None of the UbuntuSans or UbuntuSansMono fonts had any problems. All of the Ubuntu and UbuntuMono fonts displayed the "fi" ligature in the italics and bold italics columns, and most of them displayed it for all 4 columns. 

Expected behavior:

`U+F001` consistently renders a music note icon

Example symbols:

n/a

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_

In my terminals, I use UbuntuMono Nerd Font Mono and it's bold, italic, and bold italic variations. In investigating this issue, I used the following, again, in a `details` block:

<details><summary>view font list</summary>
<ul>
<ul>
<li><code>UbuntuNerdFontPropo-BoldItalic.ttf</code></li>
<li><code>UbuntuNerdFontPropo-Light.ttf</code></li>
<li><code>UbuntuNerdFontPropo-Medium.ttf</code></li>
<li><code>UbuntuNerdFont-MediumItalic.ttf</code></li>
<li><code>UbuntuNerdFontPropo-MediumItalic.ttf</code></li>
<li><code>UbuntuNerdFontPropo-Regular.ttf</code></li>
<li><code>UbuntuNerdFont-Medium.ttf</code></li>
<li><code>UbuntuNerdFont-Regular.ttf</code></li>
<li><code>UbuntuNerdFont-Light.ttf</code></li>
<li><code>UbuntuNerdFont-Bold.ttf</code></li>
<li><code>UbuntuNerdFont-Italic.ttf</code></li>
<li><code>UbuntuNerdFontPropo-Condensed.ttf</code></li>
<li><code>UbuntuNerdFontPropo-Bold.ttf</code></li>
<li><code>UbuntuNerdFont-Condensed.ttf</code></li>
<li><code>UbuntuNerdFontPropo-Italic.ttf</code></li>
<li><code>UbuntuNerdFont-LightItalic.ttf</code></li>
<li><code>UbuntuNerdFontPropo-LightItalic.ttf</code></li>
<li><code>UbuntuMonoNerdFont-BoldItalic.ttf</code></li>
<li><code>UbuntuMonoNerdFont-Regular.ttf</code></li>
<li><code>UbuntuNerdFont-BoldItalic.ttf</code></li>
<li><code>UbuntuMonoNerdFontPropo-BoldItalic.ttf</code></li>
<li><code>UbuntuMonoNerdFontMono-BoldItalic.ttf</code></li>
<li><code>UbuntuMonoNerdFontPropo-Regular.ttf</code></li>
<li><code>UbuntuMonoNerdFontMono-Regular.ttf</code></li>
<li><code>UbuntuMonoNerdFontPropo-Italic.ttf</code></li>
<li><code>UbuntuMonoNerdFont-Italic.ttf</code></li>
<li><code>UbuntuMonoNerdFontPropo-Bold.ttf</code></li>
<li><code>UbuntuMonoNerdFontMono-Bold.ttf</code></li>
<li><code>UbuntuMonoNerdFont-Bold.ttf</code></li>
<li><code>UbuntuMonoNerdFontMono-Italic.ttf</code></li>
<li><code>UbuntuSansNerdFont-MediumItalic.ttf</code></li>
<li><code>UbuntuSansNerdFont-SemiBoldItalic.ttf</code></li>
<li><code>UbuntuSansNerdFontPropo-Medium.ttf</code></li>
<li><code>UbuntuSansNerdFont-Regular.ttf</code></li>
<li><code>UbuntuSansNerdFontPropo-Regular.ttf</code></li>
<li><code>UbuntuSansNerdFont-Italic.ttf</code></li>
<li><code>UbuntuSansNerdFontPropo-Italic.ttf</code></li>
<li><code>UbuntuSansNerdFontPropo-SemiBold.ttf</code></li>
<li><code>UbuntuSansNerdFont-Medium.ttf</code></li>
<li><code>UbuntuSansNerdFontPropo-Bold.ttf</code></li>
<li><code>UbuntuSansNerdFontPropo-SemiBoldItalic.ttf</code></li>
<li><code>UbuntuSansNerdFont-SemiBold.ttf</code></li>
<li><code>UbuntuSansNerdFont-Bold.ttf</code></li>
<li><code>UbuntuSansNerdFont-BoldItalic.ttf</code></li>
<li><code>UbuntuSansNerdFontPropo-MediumItalic.ttf</code></li>
<li><code>UbuntuSansNerdFontPropo-BoldItalic.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontMono-BoldItalic.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontPropo-Regular.ttf</code></li>
<li><code>UbuntuSansMonoNerdFont-SemiBoldItalic.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontPropo-MediumItalic.ttf</code></li>
<li><code>UbuntuSansMonoNerdFont-Medium.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontPropo-Medium.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontMono-SemiBold.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontMono-Italic.ttf</code></li>
<li><code>UbuntuSansMonoNerdFont-Bold.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontPropo-Italic.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontPropo-Bold.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontPropo-BoldItalic.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontMono-Regular.ttf</code></li>
<li><code>UbuntuSansMonoNerdFont-BoldItalic.ttf</code></li>
<li><code>UbuntuSansMonoNerdFont-Italic.ttf</code></li>
<li><code>UbuntuSansMonoNerdFont-SemiBold.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontPropo-SemiBoldItalic.ttf</code></li>
<li><code>UbuntuSansMonoNerdFont-MediumItalic.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontMono-Medium.ttf</code></li>
<li><code>UbuntuSansMonoNerdFont-Regular.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontMono-SemiBoldItalic.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontMono-Bold.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontMono-MediumItalic.ttf</code></li>
<li><code>UbuntuSansMonoNerdFontPropo-SemiBold.ttf</code></li>
</ul>
</li>
</ul>

</details>

- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Either GitHub Releases or nerdfonts.com - not sure which.
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - `kitty` and `xterm`
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Linux (specifically `Debian GNU/Linux 12 (bookworm)`, according to `lsb_release -d`).

#### ★ Screenshots (Optional)

Spreadsheet in Libreoffice illustrating issue ([nf-issue-demo.ods](https://github.com/ryanoasis/nerd-fonts/files/14898712/nf-issue-demo.ods)):

![image](https://github.com/ryanoasis/nerd-fonts/assets/33302691/7f01b651-25b5-4da8-a980-b335f8d11392)

*Note: I removed the UbuntuSans and UbuntuSansMono lines from the spreadsheet once I saw they were all fine.*

Illustration of issue in Kitty:

![image](https://github.com/ryanoasis/nerd-fonts/assets/33302691/5783992d-49a8-495c-9ee5-4a1f1a6141c9)

**Comment by Finii** [comment]
Thanks for reporting.
I remember that I fixed that some longer time ago :thinking:

**Comment by Finii** [comment]
* #1221 

:flushed:

**Comment by Finii** [comment]
Hmm, I can not reproduce.

Set up like this:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/a19f089e-c37b-49d1-91a8-c8fc29521e0d)

Then run LibreOffice Writer:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/a0665511-deac-4311-8040-6413c2669a0b)
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/7d431c11-676f-4305-8289-dec23ce94feb)

There **is** a difference between mechanics in the `Ubuntu Light` compared to the other `Ubuntu` fonts, but you specifically state `Ubuntu Mono` where no `Light` is available.

Maybe we should concentrate on a subset of the patched Ubuntu fonts. Please for example remove all Ubuntu Nerd Fonts and Ubuntu Sans Nerd Fonts, leaving only the Ubuntu Mono Nerd Fonts, which are 12 files.
Maybe check also the font versions, not that you have the issue with some old patch.
Important is to restart LibreOffice after changes in the font directory.
Also I never need to rebuild the font cache, your mileage may vary.

**Comment by eliminmax** [comment]
The issue is that the "fi" ligature appears instead of the music note, not the other way around. I think it's the inverse of the previous issue you linked.

**Comment by Finii** [comment]
Ah you assed your spreadsheet file, excellent :+1: 

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/78967c79-7ec0-4b0d-8c19-34cde8540279)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/bd211e1f-b678-4306-90c3-305490bf9828)


![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/9d7b7002-a358-4c9c-b83f-848bdfb2d421)

You did enter a codepoint directly, i.e. `F001`, and that is indeed the musical note.
Why do you think that is the `fi` ligature?

It's not, the `fi` ligature is at `FB01` in the Ubuntu fonts (at least in most).

The ligature lookup table says the ligature glyph name is `f_i`, and that is here:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/40225c5e-54fd-436e-99e6-1f2280e9c460)

The glyph at `F001` has the name `fi` and THAT is not referenced my anything inside the font.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/5cd52ffb-5d0a-4c00-af7a-b4a67d1f7517)

So, the question is, why do you insert some concrete codepoint, if you want the ligature you just type `f` and `i` and let the font do its magic? And IF you enter a codepoint, enter the correct one?

**Comment by Finii** [comment]
> The issue is that the "fi" ligature appears instead of the music note, not the other way around. I think it's the inverse of the previous issue you linked.

Ah, sorry, now I seem to understand :sweat_smile: , let me explain:

**Comment by Finii** [comment]
In the (few) Ubuntu fonts where at `F001` is **not** a musical note we can not remove that glyph without breaking the font.

If - in those fonts - the glyph would be patched to the music note glyph, and someone types `f` followed by `i` it would display the `note`. That is a ligature rule inside the font file and we can not easily change that.

We could remove the ligature rule, leaving the `f` and `i` as individual glyphs, but then the font is not intact anymore and looks bad where people expect a better looking ligature glyph.
We could take the ligature glyph and move it to some other codepoint, and then adjust the substitution tables in the font. But that is very hard to do automatically.
So we choose to not patch over 'essential' glyphs. Patching those glyphs breaks the font because of its substitution rules.

**Comment by Finii** [comment]
If you want to self-patch I can give you the patcher config to remove the ligature.

**Comment by Finii** [comment]
Hmm, I am a bit too dump (maybe sleep deprivation),

can reproduce finally :grimacing: 

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/186081ee-b8af-4c97-be8d-f3046b1c4316)

**Comment by Finii** [comment]
Thanks for reporting and nudging me in the right direction :+1:

**Comment by eliminmax** [comment]
I understand. I might just switch to a different Nerd Font.

**Comment by Finii** [comment]
I will fix that. Tomorrow.

Sent from Nine
________________________________

**Comment by Finii** [comment]
## Ubuntu

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/a9393185-a431-4cc0-b773-087cf924bf96)

## Ubuntu Mono

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/380236bd-e234-408f-81ff-76115b97b379)

**Comment by Finii** [comment]
@allcontributors please add @eliminmax  for bug

**Comment by Finii** [comment]
There was even a real bug in the code - UbuntuMono should never have had the fi-ligatures preserved (because it just had the glyphs but no rules in the font file to access them as ligs).
