### ISSUE TITLE
Add 'All Contributors' section to website

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#160]
#### Requirements

If you are **not** sure whether or not what you are reporting is actually an issue **or** you have a general question please message in the [Gitter Chat Room](https://gitter.im/ryanoasis/nerd-fonts)

By posting an issue you acknowledge the following:

- [x] Read https://github.com/kentcdodds/all-contributors, specifically: https://github.com/kentcdodds/all-contributors#mandatory
- [x] Familiarize yourself with the GitHub pages Jekyll website source: https://github.com/ryanoasis/nerd-fonts/tree/gh-pages
- [x] Familiarize yourself with website and layout: https://NerdFonts.com

#### Add an 'All Contributors' table and section

- Add an 'All Contributors' table similar to: https://github.com/kentcdodds/all-contributors#contributors
- Create new section (new file in `_pages/`)

**Comment by lucasreed** [comment]
I'll work on this.

**Comment by ryanoasis** [comment]
@lucasreed It's all yours 😄 . Let me know if you have any questions or need any help

**Comment by lucasreed** [comment]
I mention in my PR that it's just part 1. I have to convert the table format to something that jekyll likes before making the PR to gh-pages.

**Comment by lucasreed** [comment]
PR submitted for gh-pages modification as well. Between these two, it should close out this issue. 

One thing of note. Adding new folks to the contributors files in both master and gh-pages will be a manual process. I can attempt to automate this, but that would take more time. I did automate the initial populating of data to the gh-pages md file to save myself some time, but it was more of a one-off script.

**Comment by ryanoasis** [comment]
I'll need to update the contribution list but I am considering this closed for now.

Thanks again @lucasreed

**Comment by ryanoasis** [comment]
> I did automate the initial populating of data to the gh-pages md file to save myself some time, but it was more of a one-off script.

Do you mind posting or linking to this just in case it becomes useful?

**Comment by lucasreed** [comment]
@ryanoasis Sure, I'll make a gist when I get a few moments.

**Comment by ryanoasis** [comment]
@lucasreed Sounds good thanks. No rush!

**Comment by lucasreed** [comment]
@ryanoasis Sorry it took me so long (I have been really busy and it sort of slipped my mind)
https://gist.github.com/lucasreed/6d69c376ec0ddf88093dfb9bad514f09

Essentially what I did was copy the .all-contributorsrc out of the master branch to a different dir, and then run the script against that file (it's hardcoded in my gist as all-contributorsrc, without the leading dot [here](https://gist.github.com/lucasreed/6d69c376ec0ddf88093dfb9bad514f09#file-gh-pages-contributors-py-L7))

The reason I copied it somewhere else is so I could change to the gh-pages branch and still mess around with the script against the rc file.

Hope that helps!

**Comment by ryanoasis** [comment]
Thanks @lucasreed
