### ISSUE TITLE
BlexMono: doesn't work in Windows

### ISSUE THREAD

**Issue by endquote** [ryanoasis/nerd-fonts#1600]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

![Screenshot 2024-04-09 at 10 24 22 AM](https://github.com/ryanoasis/nerd-fonts/assets/330010/90659848-af3f-4e3b-b4d1-a5d3b73d0e43)

Expected behavior:

Was hoping to install the font. I think I have in the past.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - `BlexMonoNerdFont-Bold.ttf`
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.0/IBMPlexMono.zip
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - vscode/Windows 11
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows 11

**Comment by Finii** [comment]
Sorry to hear that there is a problem!

It seems I can not reproduce, at least on Windows 10:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/37c4d0c6-4f4f-4521-9a67-a9d530cd6a20)

Superficial checks on Linux did not yield anything strange, and also Apple's FontBook validation is all-green:

<img width="1470" alt="Screenshot 2024-04-09 at 22 37 41" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/5669f87f-00c3-410d-98b0-b29eadeeb1d5">

Could you install the font?
Is it visible in the Fonts Settings dialogue? (see my screenshot)
What is this 'Windows Font Viewer', how can I start that?
Why is the extracted font not in a subdirectory?
Can you show a screenshot of the font file in Windows Explorer (to see the size etc)

**Comment by endquote** [comment]
Installing the font gives the same error.
"Windows Font Viewer" is what comes up if you just double-click the font.
That font isn't in a subdirectory because I downloaded it raw from GitHub.

<img width="647" alt="Screenshot 2024-04-09 at 2 44 20 PM" src="https://github.com/ryanoasis/nerd-fonts/assets/330010/3a5dd6d5-215c-4ee9-8b13-fcd2d6ce98fa">

However, I think I know what the actual problem is. This is a corporate-controlled machine and I recall having issues installing fonts on these in the past, I think it's some group policy setting that I need my IT to change.

**Comment by Finii** [comment]
Maybe you should try downloading the zip or xz archive, unpack that, and try that font.

Your font has a different size. Images from your and my screenshots:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/eb3b46ab-5b45-493c-a5d9-7fd7f6066166)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/fbbb0cda-2c00-4be3-873c-3412bc35a66a)

And in the repo:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/5bd2d405-1266-4e1a-b9dd-6971ea2d0171)

2.06 MB * 1024 = 2,109.4 kB

Downloading it...

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ea817f48-1e1b-4a32-aade-f8e299d75ffe)

Something does indeed seem corrupt with that file; broken whilst downloading?

**Comment by Finii** [comment]
Size in detail

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/ffc75cf1-0e58-4b2e-ab7d-2040d12e4d9f)


One file 'in repo', one file downloaded from repo out ouf the three, one file from the archive

**Comment by Finii** [comment]
No Problem! Glad you could find the reason, or at least make it work on some other machine. 
You could of course try the unpatched font, if that could be installed. 
I could try on Windows 11 only when I wrestle the game laptop from my youngest kid :grimacing:

Fini

Sent from Nine
________________________________
