### ISSUE TITLE
[MonospiceNe NFM] VS Code does not allow 'Mono' font as terminal font

### ISSUE THREAD

**Issue by OliverRC** [ryanoasis/nerd-fonts#1602]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
I'd expect the 'mono' font to work in the terminal of VS code however it throws up a warning.

```
The terminal only supports monospace fonts. Be sure to restart VS Code if this is a newly installed font.
```

Expected behavior:
That the specially "mono" titled font would work in the VS Code (pwsh) terminal.

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - MonaspiceNe NFM
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - scoop
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - none
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows 11

#### ★ Screenshots (Optional)

![image](https://github.com/ryanoasis/nerd-fonts/assets/1888486/d4377e15-509c-4766-9c1a-45caae76aa20)

**Comment by Finii** [comment]
Hmm, maybe more information would be good?

**Comment by OliverRC** [comment]
Apologies this was published in error. I apologize, I will remove and republish a new issue

**Comment by Finii** [comment]
Thanks, will have a look probably in the afternoon (in some hours).

**Comment by Finii** [comment]
The relevant flags **are** set :thinking: 

_Excerpt of `ttx` dump:_

```xml
  <post>
    <formatType value="3.0"/>
    <italicAngle value="0.0"/>
    <underlinePosition value="-70"/>
    <underlineThickness value="72"/>
    <isFixedPitch value="1"/>
    <minMemType42 value="0"/>
    <maxMemType42 value="0"/>
    <minMemType1 value="0"/>
    <maxMemType1 value="0"/>
  </post>
    
  <CFF>
    <major value="1"/>
    <minor value="0"/>
    <CFFFont name="MonaspiceNeNFM-Regular">
      <version value="001.000;Nerd Fonts 3.2.0"/>
      <Notice value="copyright missing"/>
      <FullName value="MonaspiceNe NFM"/>
      <FamilyName value="MonaspiceNe Nerd Font Mono"/> 
      <Weight value="Regular"/>
      <isFixedPitch value="1"/>
      <ItalicAngle value="0"/>
      <UnderlinePosition value="-106"/>
      <UnderlineThickness value="72"/>

...

    <panose>                              
      <bFamilyType value="2"/>
      <bSerifStyle value="0"/>
      <bWeight value="0"/>
      <bProportion value="9"/>
      <bContrast value="0"/>
      <bStrokeVariation value="0"/>          
      <bArmStyle value="0"/>
      <bLetterForm value="0"/>

```
_isFixedPitch is true and Panose-Proportion is 9 (i.e. monospaced)_

**Comment by Finii** [comment]
Installed VSCode after installed the font (see picture above) and there is no problem?

![grafik](https://github.com/ryanoasis/nerd-fonts/assets/16012374/2e96575a-fa36-4419-8e3e-05f14e0371cb)

Lets retry with some more distinctive font...

**Comment by Finii** [comment]
There seems to be no problem?

![grafik](https://github.com/ryanoasis/nerd-fonts/assets/16012374/12c798cd-7ba0-4f60-a51a-4404b33518a0)

**Comment by Finii** [comment]
Maybe try to install it yourself / directly from the Release page:

https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.2.0

Please uninstall the old font first and then reinstall, overwrite-install usually has problems.

**Comment by Finii** [comment]
Ah, and please try, only installing that one font file. If that works and the complete package installed fails we need to look somewhere else. But first we need to make sure the singular and anlone installed font file works.

**Comment by Finii** [comment]
Not holding bugfix release 3.2.1 anymore, closing this.
3.2.1 release started.

**Comment by OliverRC** [comment]
I tried again today, and all looks good; Sorry for the wild goose chase.

**Comment by Finii** [comment]
Good news :+1: 
Thanks for reporting back!
