### ISSUE TITLE
Just found a typo on wiki

### ISSUE THREAD

**Issue by chansey97** [ryanoasis/nerd-fonts#1603]
https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points#additional-sets

Additional sets

- Heavy Angle Brackets (e276c-2771)
- Box Drawing (2500-259f)

Heavy Angle Brackets should be "276c-2771" instead of "e276c-2771".

**Comment by Finii** [comment]
Thanks for reporting! Fixed.

**Comment by Finii** [comment]
@allcontributors please add @chansey97 for doc
