### ISSUE TITLE
Add maple font

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#1607]
Could you add maple font please? It looks really nice!
[https://github.com/subframe7536/maple-font](https://github.com/subframe7536/maple-font)

_Originally posted by @geekyBoogiepop in https://github.com/ryanoasis/nerd-fonts/discussions/1095#discussioncomment-7686368_

**Comment by geekyBoogiepop** [comment]
Thank you!

**Comment by Finii** [comment]
Oh, sure (I forgot to add the usual explanation here).

The font proposal is transferred to the 'list of proposed fonts', and then the issue here is closed.
It is closed to keep the open-issues list concise to help work on real issues.
The list of proposed fonts will be (re)evaluated shortly before each release.
THIS issue is closed but kept unlocked, so that people can discuss the proposed font here, for example to add their +1.

See also
* #1095 

![image](https://github.com/user-attachments/assets/371da980-f02c-482d-ab63-07f0d05de5a4)

>  don't see Maple on the https://www.nerdfonts.com/font-downloads

Maybe maple seemed to have raised not enough interest, or let see..

* #1456 

> The upstream already provides the Nerd Fonts patched version, and as far as I can see they do a great job at it.
What is the reason that we should add it here? Has this been discussed with upstream?

So there is hardly a reason for the font here, if it already exists within the font project itself.
Esp as the font has RFN, we could not have a `Maple Nerd Font` but would need to rename it to (for example) `Syrup Nerd Font` ;)

Everything can be discussed of course, but that seems to be the state as of now.

**Comment by azzamsa** [comment]
> So there is hardly a reason for the font here, if it already exists within the font project itself.

Yes, turns out the upstream version already had Nerd-font release.
Thanks! 🧁
