### ISSUE TITLE
CaskaydiaCove Nerd Font -- "Arrow" Ligature

### ISSUE THREAD

**Issue by jesusvelezx** [ryanoasis/nerd-fonts#1609]
Hello! I want to report a problem with the **"Caskaydiacove Nerd Font"** ligatures, specifically in _regular_ and _semibold_ type. When creating an arrow with `-` and `>` = `->` signs it looks strange, as if they are not of the same thickness.

I attach some screenshots.

**IDE:** PyCharm Professional
**Font:** Caskaydiacove Nerd Font Mono -- Regular & SemiBold
**Reserved Font Name:** Cascadia Code
**Version:** 2111.01

**Psdt:** 
-- The first image is Regular type.
-- Second image is SemiBold type

![Issue2](https://github.com/ryanoasis/nerd-fonts/assets/79605135/7532a524-209f-4e73-ba19-f885804c4181)
![Issue1](https://github.com/ryanoasis/nerd-fonts/assets/79605135/3235c828-9340-48db-8b3a-e890cd19226e)
![image](https://github.com/ryanoasis/nerd-fonts/assets/79605135/7b7529dc-c29c-4837-a1cf-32ec4f0f1cd4)

**Thanks!!**

**Comment by Finii** [comment]
Lig looks ok in `writer`

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/05a88758-2acb-4cf5-9ada-51cdc07c189d)

The ligature uses these glyphs:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/1aef19ae-3caa-4743-800a-0efeb2522cea)

The point coordinates are exactly the same, but the hinting might be different.

Ah, yes, here

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/867f5662-124f-4d8f-9cb6-463ecbfb0b27)

Which OS are you on?

**Comment by jesusvelezx** [comment]
> Lig se ve bien en`writer`
> 
> ![imagen](https://private-user-images.githubusercontent.com/16012374/323488297-05a88758-2acb-4cf5-9ada-51cdc07c189d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0ODAwNjcsIm5iZiI6MTcxMzQ3OTc2NywicGF0aCI6Ii8xNjAxMjM3NC8zMjM0ODgyOTctMDVhODg3NTgtMmFjYi00Y2Y1LTlhZGEtNTFjZGMwN2MxODlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDIyMzYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTIxNThmMjE0YWM2OThmY2NmMGUzMGEyMjJlOWRjZjZmZDM2MTk0ZjUwNTMwYTJkN2RkMjg2ZTk5NjU3ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xmZfBN_UxFjbE_jbMX8nPRtioAO_DY42I2xJxuWCbfQ)
> 
> La ligadura utiliza estos glifos:
> 
> ![imagen](https://private-user-images.githubusercontent.com/16012374/323490414-1aef19ae-3caa-4743-800a-0efeb2522cea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0ODAwNjcsIm5iZiI6MTcxMzQ3OTc2NywicGF0aCI6Ii8xNjAxMjM3NC8zMjM0OTA0MTQtMWFlZjE5YWUtM2NhYS00NzQzLTgwMGEtMGVmZWIyNTIyY2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDIyMzYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMzE0OGNlNDYwZWMxOWRmYTY5OTkxNGI0MzcyNTg0YzA3NDk2MmJkZDA4MGVlMjA1MDg0ZWJhNWM0Y2NiMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WDEsSGmXyjBxfRgyJPnbCaegdKasYl2-s2lc_qsT9qA)
> 
> Las coordenadas de los puntos son exactamente las mismas, pero las sugerencias pueden ser diferentes.
> 
> Ah, si, aquí.
> 
> ![imagen](https://private-user-images.githubusercontent.com/16012374/323491343-867f5662-124f-4d8f-9cb6-463ecbfb0b27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0ODAwNjcsIm5iZiI6MTcxMzQ3OTc2NywicGF0aCI6Ii8xNjAxMjM3NC8zMjM0OTEzNDMtODY3ZjU2NjItMTI0Zi00ZDhmLTljYjYtNDYzZWNiZmIwYjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDIyMzYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxODQwMzg1MzEyMDAyODUwOTFlOTg4YTM1MTYwMjBmN2ZkYWZhYjdiMWUxNzUxNDYzODk1MjE1YTNmNTMzOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8tYgbl5FBt_kDjckN8xMl6aNZpNPl6IvNOLqqFkAak4)
> 
> ¿En qué sistema operativo estás?

I am using Windows 11
So there is a problem, isn't there?
Or, is it a problem with the IDE I'm using?

**Comment by Finii** [comment]
There is a problem.
And I implemented something that should fix it (see above PR #1613).

I need someone who sees it (I can not see the problem in my one Windows box, but I can only connect to it via RDP, and I believe hinting problems are not visible then, and the only other Windows box I can sometimes use is the Gaming Laptop of one of my children 😬 ).
So I need someone who sees it to try out the fonts after the change. If you would do it (i.e. remove all Caskaydia Cove, reboot, install the new ones, try out, ...) I can put them here... ?

**Comment by jesusvelezx** [comment]
Of course I can do it myself, I have no problem!

**Comment by Finii** [comment]
Here the Regular font with hopefully fixed arrows.
Reports appreciated.

[CaskaydiaCove_arrows.zip](https://github.com/ryanoasis/nerd-fonts/files/15049655/CaskaydiaCove_arrows.zip)

**Comment by jesusvelezx** [comment]
I just tested it and it works great. But still the semibold and bold have the same problem :(
I'm sorry, I just noticed it.

**Comment by Finii** [comment]
That is expected ;-) Only `Regular` is fixed in the `zip` file.

Do you need them? I can just upload which you need. `Nerd Font Mono` and the `Regular`, `Bold`, `SemiBold` and the `Italic` ones?

**Comment by jesusvelezx** [comment]
If it is possible to have all the fonts for me it would be great :)

**Comment by Finii** [comment]
Here a more complete set of patched fonts. The problem is that Github does not allow big archives in comments and also does not allow better archives than `zip` :roll_eyes: 

`CascadiaCode_subset_arrow.zip`

And here is a complete set of **all** fonts. To circumvent the Github shortcomings, this is an `xz` archive in a `zip` archive.
* Unpack the `zip` -> you get a `xz`
* Unpack the `xz` -> you get the fonts

You need some tool like 7-zip to unpack the `xz`.

Contents of the small subset:

<details>

```console
$ unzip -v CascadiaCode_subset_arrow.zip
Archive:  CascadiaCode_subset_arrow.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
 2581408  Defl:X  1339185  48% 2024-04-20 15:34 84663779  CaskaydiaCoveNerdFont-Regular.ttf
 2343208  Defl:X  1343516  43% 2024-04-20 15:36 1186f749  CaskaydiaCoveNerdFontMono-Italic.ttf
 2431548  Defl:X  1273497  48% 2024-04-20 15:36 0721c02f  CaskaydiaCoveNerdFont-Italic.ttf
 2490588  Defl:X  1407445  44% 2024-04-20 15:35 0000040e  CaskaydiaCoveNerdFontMono-Regular.ttf
 2492292  Defl:X  1408228  44% 2024-04-20 15:40 7a83b739  CaskaydiaCoveNerdFontMono-Bold.ttf
 2583112  Defl:X  1338882  48% 2024-04-20 15:39 4cd58b28  CaskaydiaCoveNerdFont-Bold.ttf
 2432792  Defl:X  1275467  48% 2024-04-20 15:38 23d381fd  CaskaydiaCoveNerdFont-BoldItalic.ttf
 2344452  Defl:X  1345810  43% 2024-04-20 15:38 08270cfd  CaskaydiaCoveNerdFontMono-BoldItalic.ttf
 2432336  Defl:X  1276373  48% 2024-04-20 15:50 431176fe  CaskaydiaCoveNerdFont-SemiBoldItalic.ttf
 2582516  Defl:X  1340144  48% 2024-04-20 15:49 5fa68881  CaskaydiaCoveNerdFont-SemiBold.ttf
 2491700  Defl:X  1409260  44% 2024-04-20 15:49 d95f73ae  CaskaydiaCoveNerdFontMono-SemiBold.ttf
 2343996  Defl:X  1346586  43% 2024-04-20 15:51 f8c5e7db  CaskaydiaCoveNerdFontMono-SemiBoldItalic.ttf
    4395  Defl:X     1939  56% 2024-04-20 15:52 1044e40d  LICENSE
    3467  Defl:X     1634  53% 2024-04-21 08:35 ca894118  README.md
--------          -------  ---                            -------
29557810         16107966  46%                            14 files
```

</details>

### Downloads

[CascadiaCode_subset_arrow.zip](https://github.com/ryanoasis/nerd-fonts/files/15050914/CascadiaCode_subset_arrow.zip) (12 fonts, 16 MB)

[CascadiaCode.tar.xz.zip](https://github.com/ryanoasis/nerd-fonts/files/15050956/CascadiaCode.tar.xz.zip) (36 fonts, 3 MB)

**Comment by jesusvelezx** [comment]
Oh man you are awesome! Thank you for the support!!
