### ISSUE TITLE
U+276F prompt character (❯) got smaller between 3.1.1 and 3.2.1

### ISSUE THREAD

**Issue by gibfahn** [ryanoasis/nerd-fonts#1611]
### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### Experienced behavior:

Prompt character is now small.

#### Expected behavior:

Prompt character is large and easy to spot in the terminal.

#### Example symbols:

- U+276F (❯) 

### 🔧 Your Setup

- Terminal: [kitty.app](https://sw.kovidgoyal.net/kitty/) 0.34.0, but it also reproduces with Terminal.app
   - Configuration (in case useful): [kitty.conf](https://github.com/gibfahn/dot/blob/16a690144d8c9457204441ec74e3142bf75ced86/dotfiles/.config/kitty/kitty.conf#L28)
- Font: `Hasklug Nerd Font Mono`, installed by brew from: [font-hasklug-nerd-font](https://github.com/Homebrew/homebrew-cask-fonts/blob/HEAD/Casks/font-hasklug-nerd-font.rb)
   - Brew [downloads from](https://github.com/Homebrew/homebrew-cask-fonts/blob/b415b1b34f996ced02785721a2fd30e5c5ea21e4/Casks/font-hasklug-nerd-font.rb#L5) https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Hasklig.zip
- OS: latest macOS

#### ★ Screenshots

Screenshots taken at the same zoom in kitty.app on old and new font versions:

| 3.1.1 | 3.2.1 |
| --- | --- |
| ![3.1.1](https://github.com/ryanoasis/nerd-fonts/assets/15943089/3747a6df-1d62-40df-ac16-80388312c8e0) |  ![3.2.1](https://github.com/ryanoasis/nerd-fonts/assets/15943089/de1fd3c3-fc56-406b-99f6-6576f0c09985) |

**Comment by Finii** [comment]
Sorry to hear of your size problem.

I can see it directly in the font :thinking: 

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/fafaed67-07d0-4b22-a94d-2850f694dfba)

Suspect
* #1564

Because from these heavy brackets people DO expect excessively big icons :thinking:

**Comment by Finii** [comment]
In this example the icon is (far) less tall than the small letter T, which is strange

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/f08512a0-b5ac-4dbb-9f29-22b0d51e8b09)

I will example in detail.

**Comment by Finii** [comment]
The cell heights difference is quite huge here?

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/a071bb47-11b5-4b1f-8929-68ac949bc093)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/20b7a20d-484c-4cef-96c7-0ce58e629eaf)

Not the case 'globally':

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/88dfcfc4-6e08-4079-ba04-d1b6f6faef8b)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/b9981ac0-dfa9-4766-af2f-188ba89324f5)



68% vs 76% ?


Hmm, thanks for reporting. This needs some consideration and a systematic check. I see the effect by the reason is not quite clear; and maybe that should have been marked with the `^` (fit to full height) modifier.

**Comment by Finii** [comment]
Ahh, one should read ...

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/fc984d63-ff90-4793-8234-e570cd912b22)

**Comment by Finii** [comment]
Ah, the heavy brackets are now two times shrunken, there was an old rule that already sized them down relative to the full cell:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/eff2642b-20af-406f-85a1-6d8e63d648c3)

The rule needs to be changed to `^pa1!` ....

**Comment by Finii** [comment]
@allcontributors please add @gibfahn for bug

**Comment by martinpelikan** [comment]
Apologies if this is unrelated or intended, but I noticed an **increase** in the size of some symbols in `ttf-firacode-nerd`, going from `3.2.0` -> `3.2.1` in my i3 status bar.

| `3.2.0` | `3.2.1` |
| --- | --- |
|![2024-04-18_19-08](https://github.com/ryanoasis/nerd-fonts/assets/3248296/456c0092-613c-4197-b69e-bfd508123448)|![2024-04-18_19-09](https://github.com/ryanoasis/nerd-fonts/assets/3248296/feb63bf6-b3c7-496e-863d-f62982282262)|

`U+F120` (`nf-fa-terminal`) and `U+F11B` (`nf-fa-gamepad`)

**Comment by Finii** [comment]
Where is the PR @Finii !!!?

**Comment by gibfahn** [comment]
Thanks for the detailed explanation and the solution! I don't know if it's helpful, but I filed your proposed solution as a PR. I _think_ that's right, don't have much experience in this area. https://github.com/ryanoasis/nerd-fonts/pull/1617

It's your change, so if you want to file your own PR for it fine by me, just trying to reduce some cycles for you 😁 .

**Comment by Finii** [comment]
Most probably you already read it, but if not... the cryptic rules have some explanation

```
# Stretch 'xz' or 'pa' (preserve aspect ratio)
# Supported params: overlap | careful | xy-ratio | dont_copy | ypadding    
# Overlap value is used horizontally but vertically limited to 0.01
# Careful does not overwrite/modify existing glyphs
# The xy-ratio limits the x-scale for a given y-scale to make the ratio <= this value (to prevent over-wide glyphs)
# '1' means occupu 1 cell (default for 'xy')
# '2' means occupy 2 cells (default for 'pa')
# '!' means do the 'pa' scaling even with non mono fonts (else it just scales down, never up)
# '^' means that scaling shall fill the whole cell and not only the icon-cap-height (for mono fonts, other always use the whole cell)
# Dont_copy does not overwrite existing glyphs but rescales the preexisting ones
#
# Be careful, stretch may not change within a ScaleRule!
```

```
'align': 'c', 'valign': 'c', 'stretch': '^pa1!', 'params': {'ypadding': 0.3, 'careful': True}
```

* Align horizontally and vertically in the center
* Scale it with preserved aspect ratio (x and y scale is equal) into 1 cell (default would be 'up to 2' for `pa`)
* Take the whole line-hight (`^`) and subtract 30% from the height (`ypadding`)
* Do the scaling also for proportional fonts
* Do not change preexisting glyphs
