### ISSUE TITLE
Font request: Space Grotesk

### ISSUE THREAD

**Issue by TheBeeBoi** [ryanoasis/nerd-fonts#1620]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Replace (or just keep) the Space Mono nerd font w/ Space Grotesk

**Describe alternatives you've considered**
Just keep using the Space Mono nerd font

**Additional context**
N/A

**Comment by TheBeeBoi** [comment]
Whoops! Forgot to check the new font discussions :P

**Comment by Finii** [comment]
> Whoops! Forgot to check the new font discussions :P

Hmm, do you mean #1095? I can't find Space Grotesk there?

**Comment by Finii** [comment]
According to [it's website](https://floriankarsten.github.io/space-grotesk/)

> Space Grotesk is a proportional sans-serif typeface variant based on Colophon Foundry's fixed-width Space Mono family (2016). Originally designed by Florian Karsten in 2018, Space Grotesk retains the monospace's idiosyncratic details while optimizing for improved readability at non-display sizes.

Proportional fonts are not really a target for Nerd Fonts, as they usually do not work well in terminals.
Can you explain why this font should be added?
