### ISSUE TITLE
Glyph e27f (nf-fae-atom) in "Cascadia Code NF" is filled in some areas where it should not be

### ISSUE THREAD

**Issue by TipaRiordan** [ryanoasis/nerd-fonts#1626]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
In the Gylph the hollow areas lose to the inner hexagon (small triangles) are filled.
![e27f CascadiaMonoNF](https://github.com/ryanoasis/nerd-fonts/assets/46349551/85580c2a-b280-4f21-8f9b-d2891d3e292e)
- did a quick check on all Cascadia [...] NF flavors, the issue seems to apply to all of them (no guarantee).

Expected behavior:
Glyph e27f (nf-fae-atom) in **Cascadia Code NF** should appear like shown in the CheatSheet: No area filled except nucleus, orbit lines and electrons. 
![e27f Icon](https://github.com/ryanoasis/nerd-fonts/assets/46349551/ba88e2a3-c729-4c00-ac76-233a4b960911)

Example symbols:
e27f

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   CascadiaCodeNF-Regular.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - https://github.com/microsoft/cascadia-code/releases/download/v2404.23/CascadiaCode-2404.23.zip
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Used Font in MS Word 2019, V. 16.0.10406.20006, 32-Bit. Snapshot above made there.
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
  - Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz   3.60 GHz
  - RAM		24,0 GB (23,9 GB verwendbar)
  - System Type 	64-Bit-OS, x64 processor
  - Windows 	10 Pro
  - Version		22H2
  - Build 		19045.4291
  - Windows Feature Experience Pack 1000.19056.1000.0

**Comment by Finii** [comment]
Good find!
Thanks a lot for reporting!

I forwarded the Issue to Cascadia's repo, see above.
