### ISSUE TITLE
Incorrect (?) width of glyph(s) in RobotoMono Font

### ISSUE THREAD

**Issue by TipaRiordan** [ryanoasis/nerd-fonts#1628]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
In MS Outlook 2019 as well as in Word 2019, set font to "RobotoMono Nerd Font", then entered **ef6d[Alt-C]X** (U+ef6d followed by X). Got this: 
![U-EF6D overlap](https://github.com/ryanoasis/nerd-fonts/assets/46349551/1462ec21-3358-4ff2-bb75-1a12379b1950)

Expected behavior:
The glyphs should not overlap when enetered sequentially on a line.
(don't know if that is a bug or a feature within a monospaced font ... overlapping is not present U+EF6D is followed by a blank. Maybe it's a workaround for integrating glyphs into a monspaced font even if the original width doesn't fit in there)
Inserted extra blank between U+EF6D and X:
![U-EF6D nonoverlap due to blank](https://github.com/ryanoasis/nerd-fonts/assets/46349551/5bf5a0c3-b11e-413a-8fe7-ec80e854bcfc)

Example symbols:
U+EF6D, U+EF6C (havn't tried more ...)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - RobotoMonoNerdFontMono-Regular.ttf (?)
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - downloaded from nerdfonts.com (https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/RobotoMono.zip)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - tried in MS Outlook 2019, MS Word 2019
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows 10 Pro, 22H2, Build 19045.4291, Windows Feature Experience Pack 1000.19056.1000.0

#### ★ Screenshots (Optional)

see above

**Comment by Finii** [comment]
You use `RobotoMono Nerd Font`. What you see is expected behavior.

If you do not want that, you can use `RobotoMono Nerd Font Mono` (usually for terminal use), or as you say `Word` the variant `RobotoMono Nerd Font Propo`.

See #1103 for an explanation.
