### ISSUE TITLE
Missing 1px line at the top of upper-left and upper-right triangles

### ISSUE THREAD

**Issue by ocosta** [ryanoasis/nerd-fonts#1629]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

When `nf-ple-upper_left_triangle` or `nf-ple-upper_right_triangle` are placed right next to a block glyph (eg. nvim and tmux status lines) there is a 1px difference at the top of the triangles. In fact, when we magnify the image, we can see that it's not that the the upper line is missing, there seems to be some anti-aliasing effect (see screenshot below).

Expected behavior:

Glyphs should be perfectly aligned.

Example symbols:

█

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_
   - `JetBrainsMonoNL Nerd Font Regular`
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - [JetBrainsMono.zip](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - `GNOME Console`, but also reproducible on `GNOME Terminal`
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Linux, Fedora 40 (GNOME 46)

#### ★ Screenshots (Optional)
nvim status bar:
![image](https://github.com/ryanoasis/nerd-fonts/assets/2768114/c043f268-cd24-418c-a7fa-f1ba0f8008d9)

tmux status bar:
![image](https://github.com/ryanoasis/nerd-fonts/assets/2768114/066ce291-c834-4cb8-bde5-f37f38e276ba)

Magnified:
![image](https://github.com/ryanoasis/nerd-fonts/assets/2768114/95baf9c8-3f26-4c73-a576-e40e0a38b99f)

**Comment by Finii** [comment]
Hmm, all the glyphs are on vertical coordinate 1027:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/f526e8d2-b349-48e4-beff-106f266ff74f)

But I can see the problem with Tilix and Delugia Regular

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/d27c9ed5-9f14-4ace-b9f8-557736ae4e79)

:thinking: 

Ah, this is Delugia 2111.01.2, let me try something more up to date...
Using latest JetBrainsMono, less obvious but still visible:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/43ea849d-b8c7-489f-a79e-fa3b06648c12)

Hmm. The other two triangular things are also too low, but that is less obvious.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/1d9447c6-fc46-4307-9629-6d61543efbd0)

**Comment by Finii** [comment]
Ah, forgot to mention: This is for LCD and monochrome subpixel rendering. Not for 'none' of course. So probably some rounding error.

**Comment by Finii** [comment]
Hmm, Cascadia Code has the same problem :-o

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/34650499-4061-4a1e-a271-86445284cb08)

**Comment by ocosta** [comment]
@Finii  thanks for the additional testing! Also, note that there is a faint vertical line between the block and the triangles, even the lower-left and lower-right ones (even though these last two don't have the "missing" 1px line above them).

**Comment by Finii** [comment]
I believe they are all a fraction of a pixel too low...

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/c3ceee6e-c428-4089-bb95-cf2a038bc093)

See the half-round thing is different top and bottom.
Also see the 'smudge' below the bottom triangular things.

Ah, hinting... detail view of the theoretical shape and how it is rendered to pixel shades:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/7ffcb312-bfe3-4cad-8fa7-c15e10d69688)

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/c020a2b0-aca8-4bdd-8258-ba4d6f135913)

---

The vertical lines have a known reason and a possible fix. That fix is employed only at the moment to some (most common) Powerline glyphs and will be expanded to all if there are no negative side effects; in principle the fix can break the glyphs for other clients :grimacing: But so far it seems to be good (no complains yet).

**Comment by Finii** [comment]
Just wanted to mention that I can imagine that we might not be able to fix that at all - because it is technically impossible to fix.

Meanwhile you can try to change your font size and see if that makes the effect bigger or smaller. I guess the effect is size depended.

The technical problem is that the 'full rectangle' against what we compare is no glyph at all, but just a colored blank. As there is no outline it follows other rules in the font rendering process...

**Comment by ocosta** [comment]
Got it, thanks for the explanation! Nice to hear that the vertical line might be fixed after all, looking forward to it.

I tried increasing the font size, but the problem kept creeping up :disappointed: 

If there was a glyph for the full rectangle, do you think this could maybe guarantee proper alignment? (we would still depend on nvim, tmux etc. also using it, but theoretically this is configurable)

**Comment by Finii** [comment]
There is FULL BLOCK at `2588`, but that does not help much, because the cell height in the terminal will be whatever it is, and if that is 1/4 pixel higher than the actual glyph that will show in some cases.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/0aac186e-0daf-4299-b91e-154a8e1e8e7d)

> I tried increasing the font size, but the problem kept creeping up 

I guess that can mean that for some sizes the problem got smaller?

**Comment by Finii** [comment]
What I mean, if you would use FULL BLOCK before the Triangular Thing:
* The top of the empty space and the Triangular Thing would be equal
* But the top of the letter background will fill the whole line height and you see the step here:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/e2043fc8-54be-4a0a-be92-115f07a9f912)

**Comment by Finii** [comment]
Hmm, the full block has hints, so that no greyscale pixels are created:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/4079bd86-542d-4b21-92cd-62f40aadecea)

But still it is not "tall" enough.

**Comment by ocosta** [comment]
> I guess that can mean that for some sizes the problem got smaller?

Not really, the problem happens differently -- now it overflows the upper border:
![image](https://github.com/ryanoasis/nerd-fonts/assets/2768114/1e5831ea-8adc-4b1a-a0be-2f3d5e4babf5)

Also, the other triangles (e.g. lower-left) started missing 1px line at the bottom:
![image](https://github.com/ryanoasis/nerd-fonts/assets/2768114/ac2fa8da-0461-4a94-93d3-c94e73570455)

Given this sort of erratic behavior, it does seem like a rounding issue.

**Comment by Finii** [comment]
Yes, that's the missing hinting, which would prevent greyscale filling of specified pixel-ranges.
It might be possible to add appropriate hints (true type instructions and blue zones for the otf fonts), but I have no instant good idea how to do it (what I usually have once the reason for some behavior is clear). :thinking:

**Comment by ocosta** [comment]
I understand... well, hopefully something will come up, let's give it some time :crossed_fingers:  Anyway, I appreciate all the effort so far :clap:

**Comment by Finii** [comment]
_Just found this in an old edit session, sending the comment now, might help me later for examinations:_

Hmm, the full block has hints, so that no greyscale pixels are created:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/4079bd86-542d-4b21-92cd-62f40aadecea)

But still it is not "tall" enough.
