### ISSUE TITLE
A little problem about Terminess Nerd Font

### ISSUE THREAD

**Issue by NitroCao** [ryanoasis/nerd-fonts#163]
Urxvt can not show a symbol, like this:
![2017-05-15-154323_1911x27_scrot](https://cloud.githubusercontent.com/assets/17915615/26047563/47e47254-3986-11e7-90b2-16a077cf2c6e.png)
It's on the right side of the status line.
OS: Arch Linux 4.10.3
URxvt: v9.22
Font used: Terminess (TTF) Nerd Font Complete Mono.ttf.
I've patched this font once using the script provided.

**Comment by JayceCao** [comment]
Another problem... When I use [spaceship-zsh-theme](https://github.com/denysdovhan/spaceship-zsh-theme), this font can not show icons normally  either... Here is the screenshot after executing `urxvt -fn "xft:TerminessTTF Nerd Font:regular:size=15"`:
![2017-05-15-183857_1416x209_scrot](https://cloud.githubusercontent.com/assets/17915615/26054054/df977bca-399d-11e7-911f-7ab451a9d533.png)

**Comment by ryanoasis** [comment]
@JayceCao hey thanks for the report and details :+1: . I will try to test this out but honestly it probably won't be anytime soon :blush:

**Comment by kierun** [comment]
Here is what I see using `nvim` with `airline`…

![screenshot](https://cloud.githubusercontent.com/assets/3079575/26445029/7b8f98c4-4136-11e7-99e0-a15d26dad385.png)

Although, my fonts might be a little old…

**Comment by ryanoasis** [comment]
@kierun Is that Terminess font? Is it the mono?

**Comment by kierun** [comment]
@ryanoasis Terminess font as started with `urxvt -fn "xft:TerminessTTF Nerd Font:regular:size=15"` and with a neovim session using airline.

**Comment by fuelen** [comment]
I have the same problem
https://github.com/equalsraf/neovim-qt/issues/297#issuecomment-310281472

**Comment by ryanoasis** [comment]
Yeah there is a problem here :worried: 

So for me it seems to work fine with `mono` variants but not the other:

`urxvt -fn "xft:TerminessTTF Nerd Font Mono:regular:size=15"`

**Comment by ryanoasis** [comment]
I know you shouldn't have to switch fonts.. but.. I seem to be having success with other fonts :thinking::

`urxvt -fn "xft:SauceCodePro Nerd Font:regular:size=15"`

**Comment by ryanoasis** [comment]
I feel like this is beyond what we can do, urxvt doesn't work well with double width glyphs, the monospaced TerminessTTF seems to be working well however still not 100% and also I have had better success with the 2.1.0 release.

```sh
urxvt -fn "xft:TerminessTTF Nerd Font Mono:regular:size=15" -bg "black" -fg "white"
```

### command line

![Selection_034](https://user-images.githubusercontent.com/8083459/78739406-0db73b00-7909-11ea-9551-bd32bd4cb5f8.png)

### vim

![Selection_035](https://user-images.githubusercontent.com/8083459/78739417-11e35880-7909-11ea-8bc6-29d693774ec6.png)

**Comment by Finii** [comment]
Should have been solved with
* #764 

Closing this now, please reopen if the problems persist with newest release (`v2.3.3`). Thank you.
