### ISSUE TITLE
Deprecation warning for `appcat` in `font-sourcecodepro-nerd-font`

### ISSUE THREAD

**Issue by maxnordlund** [ryanoasis/nerd-fonts#1633]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

```
$ brew info font-sourcecodepro-nerd-font
Error: Unexpected method 'appcast' called on Cask font-sourcecodepro-nerd-font.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
==> font-sourcecodepro-nerd-font: 2.0.0
https://github.com/ryanoasis/nerd-fonts
Installed
/usr/local/Caskroom/font-sourcecodepro-nerd-font/2.0.0 (39 files, 35.3MB)
... # More output
```

Expected behavior:

That `font-sourcecodepro-nerd-font` would use `livecheck` instead. Which, if I understand correctly, is the proper/new way of doing update checks.

Example symbols:

N/A

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Sauce Code Pro Light Italic Nerd Font Complete.ttf (Font)
   - Sauce Code Pro Bold Italic Nerd Font Complete.ttf (Font)
   - Sauce Code Pro Medium Nerd Font Complete.ttf (Font)
   - Sauce Code Pro Medium Italic Nerd Font Complete.ttf (Font)
   - Sauce Code Pro ExtraLight Nerd Font Complete.ttf (Font)
   - Sauce Code Pro ExtraLight Italic Nerd Font Complete.ttf (Font)
   - Sauce Code Pro Black Nerd Font Complete.ttf (Font)
   - Sauce Code Pro Black Italic Nerd Font Complete.ttf (Font)
   - Sauce Code Pro Nerd Font Complete.ttf (Font)
   - Sauce Code Pro Semibold Nerd Font Complete.ttf (Font)
   - Sauce Code Pro Semibold Italic Nerd Font Complete.ttf (Font)
   - Sauce Code Pro Light Nerd Font Complete.ttf (Font)
   - Sauce Code Pro Bold Nerd Font Complete.ttf (Font)
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - `brew install font-sourcecodepro-nerd-font`
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - iTerm
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - macOS Monterey 12.7.4

**Comment by maxnordlund** [comment]
I'm not sure if this is the right repo, but it's mentioned in the output of `brew info` so I figured it's a start.

**Comment by Finii** [comment]
Hey!

Hmm, I have no clue where you got the cask `font-sourcecodepro-nerd-font` from.
It is not in the current `homebrew-cask-fonts`.
And it is version `2.0.0`, which is ancient.

Whatever, the "official" Nerd Font cask is `font-sauce-code-pro-nerd-font.rb`; and that uses of course `livecheck`...

As I do not even know from which tap you got that cask I can not help at all.
Maybe just uninstall and use the official one.

**Comment by maxnordlund** [comment]
I got it from the official tap: (https://github.com/Homebrew/homebrew-cask-fonts). But I guess it's been a while, the PR to update to 2.0 was in 2020: https://github.com/Homebrew/homebrew-cask-fonts/pull/1608

Anyway, I just uninstalled them since I don't really use Source Code any more.

**Comment by Finii** [comment]
The topmost (most recent) commit was where the dash-less cask has been removed.

```console
$ git log -- Casks/font-sourcecodepro-nerd-font-mono.rb                                                        master 
commit 99949ee6979de9a99fdf6bb8a1a9c457c05fd747
Author: Monson Shao <holymonson@gmail.com>
Date:   Mon Apr 13 08:24:22 2020 +0800

    font-*-nerd-font: update to 2.1.0 (#1999)

commit 69560483c2ff7db7741094527558445da3049a52
Author: commitay <commitay@users.noreply.github.com>
Date:   Tue Jun 12 23:48:17 2018 +1000

    Remove appcast checkpoints (#1696)

commit bb0d8e009f048fa0e61023c7f66d2add3249b807
Author: Franz Greiling <fgr@sadmac.de>
Date:   Fri Apr 13 00:17:56 2018 +0200

    Add italics variant for SourceCodePro Nerd Font (#1669)

commit de7a8c8adab61c7b3d6286d521a4f8f756799189
Author: Thammachart Chinvarapon <Thammachart@users.noreply.github.com>
Date:   Tue Apr 3 04:29:07 2018 +0700

    Nerd Fonts 2.0.0 (#1654)

...
```

and then it continues like this, note that a general unification in naming style has happened:

```console
$ git log --reverse -- Casks/font-sauce-code-pro-nerd-font.rb
commit e8c2732486e9b403397fc7508ceb6cb105632455
Author: Waldir Pimenta <waldyrious@gmail.com>
Date:   Fri Jul 31 15:15:40 2020 +0100

    Add hyphens to Nerd Font cask names (#2236)

commit 3a39d3e1102f91d7218dca118935d59a9f255e03
Author: Markus Reiter <me@reitermark.us>
Date:   Sat Nov 26 01:49:54 2022 +0100

    Remove GitHub appcasts. (#6653)

commit fbc1e849516242c696200eb379e5a08013b50a8a
Author: Fini <ulf.fini.jastrow@desy.de>
Date:   Wed Dec 14 17:10:59 2022 +0100

    Update Nerd Font casks to v2.2.2 (#6758)
    
    [ci] Update Nerd Font casks to v2.2.2
    
    Co-authored-by: Finii <Finii@users.noreply.github.com>

...
```

Appcasts have been removed twice :grimacing:
