### ISSUE TITLE
Update 0xProto to 2.0

### ISSUE THREAD

**Issue by jackTabsCode** [ryanoasis/nerd-fonts#1634]
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

https://github.com/0xType/0xProto/releases/tag/2.000

**Comment by Finii** [comment]
???

* #1623
