### ISSUE TITLE
Homebrew/cask-fonts will soon be deprecated

### ISSUE THREAD

**Issue by p-linnane** [ryanoasis/nerd-fonts#1635]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. I'm opening this issue to inform the nerd-fonts maintainers of the upcoming deprecation of Homebrew/cask-fonts. All fonts will be migrated to the main Homebrew/cask repo.

We will migrate all nerd-fonts to the main Homebrew/cask repo and introduce a redirect so existing users will seem seamlessly transitioned. I would like to work together to find a time the nerd-fonts release workflow can be updated, and migrate the fonts at the same time so there is no disconnect. Please let me know if there are any questions.

cc @Finii who I've worked with before on this.

**Comment by Finii** [comment]
Thank you for the information! :+1:

I believe the change in our workflow will be easy. Was busy today and will be tomorrow, but I will come back to this on the weekend.

**Comment by p-linnane** [comment]
Sounds good. I will keep an eye on this thread. Thank you!

**Comment by p-linnane** [comment]
Closing as this migration has been finished for some time. Shout if you need anything @Finii!
