### ISSUE TITLE
Tilde character in Inconsolata font looks off

### ISSUE THREAD

**Issue by savchenko** [ryanoasis/nerd-fonts#1636]
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Tilde glyph appears to be squashed vertically.

Expected behavior:
Display of the tilde character `~` is clearly different to the minus symbol `-`.

Example symbols:
`~`

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - `InconsolataNerdFontMono-Regular.ttf`
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - This repository, v3.2.1
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - `foot`
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Debian Linux, Wayland, Sway.

#### ★ Screenshots (Optional)

![image](https://github.com/ryanoasis/nerd-fonts/assets/300146/a407526f-2262-4e10-96de-3f6be839f8df)

**Comment by Finii** [comment]
Your image at 800% without pixel interpolation:
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/e915bc01-868f-4917-a208-c17713914762)

This compares the unpatched (top) and patched fonts.
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/52b18a16-8b79-4e7e-9ec4-3f42349ac17e)

What you see after hinting is exactly as expected:
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/d56187bb-4085-40a8-a08e-4cf442fceaab)

I think the patched font is not different from the unpatched font for these two glyphs.
So you should rather report that at Inconsolata ;-)

Or to phrase it differently, what you suggest would need to be changed in the unpatched font, and that is unlikely.
I used Inconsolata for several (many) years with no problems as my main and only font for programming and never had an issue with the legibility :thinking: 

If I'm mistaken and the original Inconsolata looks different than the patched one on your system please report back, then we can investigate further!
