### ISSUE TITLE
Request: Add Inter font

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#1641]
### Discussed in https://github.com/ryanoasis/nerd-fonts/discussions/770

<div type='discussions-op-text'>

<sup>Originally posted by **mainrs** January 21, 2022</sup>
[Inter](https://github.com/rsms/inter) is a font that focuses on UI. It would be great to see it patched as well. This would allow one to use the font in polybar for example :) 

It should be noted that Inter provides "advanced" features through OpenType. Not sure how that plays with nerd fonts. 

__Edit:__ I found an AUR script that does this: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nerd-fonts-inter Looks that, for some reason, they had to patch font-patcher</div>

**Comment by Finii** [comment]
Closing because transferred to #1095

**Comment by Finii** [comment]
> "Inter" is a Reserved Font Name by Rasmus Andersson

We would need to rename the font. Any suggestion?

**Comment by mainrs** [comment]
I thought about `InterNerd`, as a play of words (`inter-` being a prefix for between or among). `Intra` is nice too! :D
