### ISSUE TITLE
Font patcher leaves non monspaced font.

### ISSUE THREAD

**Issue by rayzorben** [ryanoasis/nerd-fonts#1642]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
When I patch a monospace font with font-patcher the corresponding font does not seem to be monospaced. I have verified my base font is monospaced and shows up as selectable in programs that only allow monospaced fonts. I install my patched font (in Windows for all users) and it shows up in programs such as notepad.exe but not cmd.exe

Expected behavior:
Should remain monospace and selectable by cmd.exe and others that only allow monospace fonts.

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Custom Font
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - self patched
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - cmd.exe
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Windows

#### ★ Screenshots (Optional)
Here is the patched font not appearing in cmd.exe - but my non patched font installed at the same time and in the same way appears.

![image](https://github.com/ryanoasis/nerd-fonts/assets/7737834/114149dc-953c-4fe3-99a0-8cf1a79fc64c)

**Comment by Finii** [comment]
Sorry to hear of your problem.

Usually that should not happen. Can you post the output of a patch run with `--debug 2` added to the command line?
Best would be to additionally have the to-be-patched font available somewhere, so that I can reproduce. But maybe we see something in the output. Please also include your command line.

**Comment by Finii** [comment]
Is the font _Lucida Sans_ or _Lucida Console_ or something special?
The more details the better (best of course would be the actual font file).

https://lucidafonts.com

**Comment by rayzorben** [comment]
The font is 'Lucida Programmer', a modification I made to Lucida Console over 15 years ago to add in a more unique zero and pipe character and I think maybe 1 other small tweak. Here is a link

https://www.dropbox.com/scl/fi/r0xqtas73jjq4s4vsf8og/LucProg.ttf?rlkey=etidpbdei1eiwvejl71ngk8re&dl=1

**Comment by Finii** [comment]
Thanks for the link. Can you give me your `font-patcher` options?
Anyhow, I will try it out with 'regular' and `--mono`; `cmd` will need the mono option as it can not accept glyphs that are wider than one cell. Windows Terminal can for example.

**Comment by Finii** [comment]
Debug wise this looks good.

```
Nerd Fonts Patcher v3.2.1-41 (4.14.3) (ff 20230101)
DEBUG: Naming mode 1
DEBUG: Monospace check: Panose says "monospaced"; glyph-width-mono True
DEBUG: Final font cell dimensions 1234 w x 2048 h
DEBUG: 48/160 box drawing glyphs will be replaced
Adding 188 Glyphs from Seti-UI + Custom Set
╢████████████████████████████████████████╟ 100%
Adding 6 Glyphs from Heavy Angle Brackets Set
╢████████████████████████████████████████╟ 100%
Adding 160 Glyphs from Box Drawing Set
╢████████████████████████████████████████╟ 100%
Adding 198 Glyphs from Devicons Set
╢████████████████████████████████████████╟ 100%
Done with Patch Sets, generating font...
DEBUG: Weight approximations: OS2/PS/Name: 400/400/400 (from 400/'Book'/'')
DEBUG: =====> Family (ID 1)      ok       (26 <=31): LucidaProgrammer Nerd Font
DEBUG: =====> SubFamily (ID 2)   ok       ( 7 <=31): Regular
DEBUG: =====> Fullname (ID 4)    ok       (26 <=63): LucidaProgrammer Nerd Font
DEBUG: =====> PSN (ID 6)         ok       (18 <=63): LucidaProgrammerNF
DEBUG: Preserving bitmaps (5, 6, 7, 8)
DEBUG: Tweaking 1/1
DEBUG: Changing lowestRecPPEM from 8 to 12
   LucidaProgrammer Nerd Font
   \===> 'LucidaProgrammerNerdFont-Regular.ttf'
```

Now I need to find a Windows box, which will take some time (maybe in the evening today).

**Comment by Finii** [comment]
Ah, for `cmd` you need to add `--mono`, maybe you want to try that.

**Comment by rayzorben** [comment]
OK, here is what I got from just the command I ran

```
~/Downloads  ./FontForge.AppImage -script $PWD/font-patcher $PWD/LucProg.ttf -out /tmp
Copyright (c) 2000-2023. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20230101
 Based on sources from 2023-01-01 05:26 UTC-ML-TtfDb-D-GDK3.
 Based on source from git with hash: a1dad3e81da03d5d5f3c4c1c1b9b5ca5ebcfcecf
Nerd Fonts Patcher v3.2.1 (4.13.1) (ff 20230101)
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
Warning: Mac and Windows entries in the 'name' table differ for the
  Family string in the language English (US)
  Mac String: Lucida Console
  Windows String: Lucida Programmer
Warning: Mac and Windows entries in the 'name' table differ for the
  UniqueID string in the language English (US)
  Mac String: Lucida Console Regular; B&H alpha25
  Windows String: Lucida Programmer Regular; B&H alpha25
Warning: Mac and Windows entries in the 'name' table differ for the
  Fullname string in the language English (US)
  Mac String: Lucida Console
  Windows String: Lucida Programmer
Warning: Mac and Windows entries in the 'name' table differ for the
  Version string in the language English (US)
  Mac String: Version 1.60
  Windows String: Version 1.0
Warning: Mac and Windows entries in the 'name' table differ for the
  PostScript string in the language English (US)
  Mac String: LucidaConsole
  Windows String: LucidaProgrammer
Glyph 2 is called ".notdef", a singularly inept choice of name (only glyph 0
  may be called .notdef)
  FontForge will rename it.
The glyph named macron is mapped to U+02C9.
  But its name indicates it should be mapped to U+00AF.
The glyph named Delta is mapped to U+0394.
  But its name indicates it should be mapped to U+2206.
The glyph named Omega is mapped to U+03A9.
  But its name indicates it should be mapped to U+2126.
The glyph named mu is mapped to U+03BC.
  But its name indicates it should be mapped to U+00B5.
The glyph named fraction1 is mapped to U+2044.
  But its name indicates it should be mapped to U+2215.
Adding 188 Glyphs from Seti-UI + Custom Set
╢████████████████████████████████████████╟ 100%
Adding 6 Glyphs from Heavy Angle Brackets Set
╢████████████████████████████████████████╟ 100%
Adding 160 Glyphs from Box Drawing Set
╢████████████████████████████████████████╟ 100%
Adding 198 Glyphs from Devicons Set
╢████████████████████████████████████████╟ 100%
Done with Patch Sets, generating font...
   LucidaProgrammer Nerd Font
   \===> '/tmp/LucidaProgrammerNerdFont-Regular.ttf'
```

**Comment by rayzorben** [comment]
How do I add `--mono`? I tried just adding it into command line and I got the same output.

**Comment by Finii** [comment]
For the difference, I mean what `--mono` does, have a look here

* https://github.com/ryanoasis/nerd-fonts/discussions/1103

With mono the patcher output should mention the patched font name with `Nerd Font Mono`.

**Comment by Finii** [comment]
You forgot to add/keep your `-out` parameter :grimacing:

**Comment by Finii** [comment]
Btw, there are some (unrelated) issues with the LucideProgrammer font that `fontforge` complains about.
Some things overlooked when you modified the font.

```
Warning: Mac and Windows entries in the 'name' table differ for the
  Version string in the language English (US)
  Mac String: Version 1.60
  Windows String: Version 1.0
Warning: Mac and Windows entries in the 'name' table differ for the
  PostScript string in the language English (US)
  Mac String: LucidaConsole
  Windows String: LucidaProgrammer
Glyph 2 is called ".notdef", a singularly inept choice of name (only glyph 0
  may be called .notdef)
  FontForge will rename it.
```

**Comment by rayzorben** [comment]
Thanks, that gets me a monospaced font, but it seems that a glyph is missing? I did `--complete`. Notice the last line on the prompt on my font

![image](https://github.com/ryanoasis/nerd-fonts/assets/7737834/323fe6e8-1a3e-4bfd-9c20-8a63b33c6cb8)

Here is 'Hack Nerd'

![image](https://github.com/ryanoasis/nerd-fonts/assets/7737834/c2cdbd90-04c3-40f5-8625-328704b49dad)

**Comment by Finii** [comment]
The small arrow? That is most likely `2191` or one of these. The arrow set is not in the Nerd Fonts Patchset. If the original font does not have it it will not be added.

<img width="1010" alt="Screenshot 2024-05-30 at 05 47 19" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/52983dfc-3ee8-4e39-b509-485520d1a9b9">

**Comment by Finii** [comment]
I guess the original problem is solved, so closing.
Please reopen if you still have issues.
