### ISSUE TITLE
invalid escape sequence warnings when running font-patcher script

### ISSUE THREAD

**Issue by mearleycf** [ryanoasis/nerd-fonts#1643]
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

Experienced behavior:
I was performing a dry run of font-patcher to make sure it wouldn't return any errors, etc. When I run the following command, I get the following output:
```
❯ fontforge -script ~/Downloads/Nerd\ Fonts\ Patcher/font-patcher ~/patched_fonts/mononoki-nerd-fontv2/mononoki-Regular.otf --complete --dry --outputdir ~/patched_fonts/mononoki-nerd-font-v2/1.0.0/
Copyright (c) 2000-2023. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20230101
 Based on sources from 2023-01-01 05:27 UTC-D.
/Users/mikeearley/Downloads/Nerd Fonts Patcher/font-patcher:432: SyntaxWarning: invalid escape sequence '\='
  message = "   Generated {} fonts\n   \===> '{}'".format(len(sourceFonts), outfile)
/Users/mikeearley/Downloads/Nerd Fonts Patcher/font-patcher:448: SyntaxWarning: invalid escape sequence '\='
  message = "   {}\n   \===> '{}'".format(sourceFont.fullname, outfile)
/Users/mikeearley/Downloads/Nerd Fonts Patcher/font-patcher:2028: SyntaxWarning: invalid escape sequence '\.'
  if re.match("\.ttc$", args.extension, re.IGNORECASE):
Nerd Fonts Patcher v3.2.1 (4.13.1) (ff 20230101)
INFO: Setting Panose 'Family Kind' to 'Latin Text and Display' (was 'Any')
INFO: Setting Panose 'Proportion' to 'Monospaced' (was 'Any')
Done with Patch Sets, generating font...
```
Expected behavior:
As a test, I corrected those 3 issues, and they didn't print when I ran the --dry run again. Maybe the font-patcher script needs some minor updates? 

Example symbols:
n/a

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
mononoki (the original one--not the old archived patched one)
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
pretty sure I got it here: https://github.com/madmalik/mononoki
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
OS X Sonoma

**Comment by Finii** [comment]
Thanks for being observative and taking the time to report the issue :green_heart: 

This has already been fixed via cb0c9ed1e7b70 in in-parens-version `4.14.3` (you use `4.13.1`).

**Comment by D3vil0p3r** [comment]
> Thanks for being observative and taking the time to report the issue 💚
> 
> This has already been fixed via [cb0c9ed](https://github.com/ryanoasis/nerd-fonts/commit/cb0c9ed1e7b70a3149dfc55a6c3d5e5941be0eb3) in in-parens-version `4.14.3` (you use `4.13.1`).

I am getting the same issue when I use the latest stable 3.2.1 release. If the issue has been fixed in the git repo, could you please release a new stable release with this fix?

**Comment by jdanbrown** [comment]
+1 I just tripped over this too. @Finii Mind cutting a release for `v3.3.0`?
- https://github.com/ryanoasis/nerd-fonts/releases

My workaround is to manually clone the repo instead to get the commit you linked above (cb0c9ed1e7b70a3149dfc55a6c3d5e5941be0eb3). Unfortunately this takes much longer than it took to download the `FontPatcher.zip` (2.3mb) from the v3.2.1 release — looks like my shallow git clone needs to download ~1.2gb of data from github.
```
$ git clone --depth 1 --branch v3.3.0 git@github.com:ryanoasis/nerd-fonts.git
```

**Comment by Finii** [comment]
> My workaround is to manually clone the repo instead

Hmm, how do you get the 'old' patcher script?
Cloning the repo is not recommended, use the `FontPatcher.zip` or the Docker image.

The `FontPatcher.zip` contains all stuff you need, except `fontforge` itself.
There is the release one on the release page, but also a HEAD one in-repo that you can use.

The Docker is also on HEAD.

> Mind cutting a release for v3.3.0?

See https://github.com/ryanoasis/nerd-fonts/releases/tag/untagged-b0629bf76518b7c278c1
and
* #1742

**Comment by jdanbrown** [comment]
👍 Thanks, I see the v3.3.0 release now:
- https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.3.0
