### ISSUE TITLE
Instructions for adding a new font slightly confusing

### ISSUE THREAD

**Issue by kaBeech** [ryanoasis/nerd-fonts#1655]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Documentation for [adding new fonts](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md#steps-for-adding-a-new-font-or-removing-an-existing-font) in `contributing.md`

Experienced behavior:

When reading the "Steps for adding a new font..." section in `contributing.md`, [Step 4](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md#4-run-build-scripts) seemed to me to be saying to commit the newly patched font files (in reality the instructions are only to commit changes to `config.cfg`)

Maybe this is just my brain being weird, if so feel free to close this issue =)

On the other hand, if it's helpful I have [this commit](https://github.com/ryanoasis/nerd-fonts/compare/master...kaBeech:nerd-fonts:clarify-documentation) that clarifies the documentation and I'd be happy to open a PR for it if you like =)

Expected behavior:

The instructions in the "Steps for adding a new font..." section in `contributing.md`, Step 4 clearly advises to commit only changes to `config.cfg` and to not commit the newly patched font files

Example symbols:

N/A

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - N/A
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - [contributing.md](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - N/A
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - N/A

#### ★ Screenshots (Optional)

![contributing](https://github.com/ryanoasis/nerd-fonts/assets/97925125/d5f284d9-c1df-4f9f-9d5e-c0573e00eeb5)

Thanks!

**Comment by Finii** [comment]
Thanks!
Please check if the new wording is better :-D

**Comment by kaBeech** [comment]
Looks good - thanks @Finii!
