### ISSUE TITLE
Ligature support in ComicShannsMono

### ISSUE THREAD

**Issue by tylerlaprade** [ryanoasis/nerd-fonts#1659]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
ComicShannsMono does not have ligatures

**Describe the solution you'd like**
I would like ligatures as seen [here](https://github.com/wayou/comic-mono-font)

**Describe alternatives you've considered**
I can directly use [this](https://github.com/wayou/comic-mono-font), but its Bold (and the original parent's Bold) doesn't seem to work in VSCode. Also, the spacing is too narrow.

**Additional context**
N/A

**Comment by Finii** [comment]
What about using `ComicShannsMono Nerd Font` (https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/ComicShannsMono.zip) und pushing it through https://github.com/ToxicFrog/Ligaturizer ?

That's at least what Wayou said they did, in principle (well, taking some other upstream).

https://github.com/dtinth/comic-mono-font has some problems, that is the reason we use https://github.com/jesusmgg/comic-shanns-mono as upstream for the prepatched Comic Sans.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/35e27790-e2bc-4603-bc33-8460c02f410e)

Seems to be a Mac-only person :thinking:

**Comment by tylerlaprade** [comment]
Okay, I will try that. Should I contribute the result back to the repo, or do auto-generated ligatures not meet the standards of this project?

**Comment by Finii** [comment]
I believe it would be good to at least report back here in this thread.

I think it would not be good to incorporate the ligatur-ed font into Nerd Fonts, because
* a lot people do not like those ligatures
* we stick with upstream (there must be severe reasons to deviate from that)

I guess the ligs could be added as Stylistic Set (maybe they are already, I never myself tried the Ligaturizer), and then contributed to upstream (i.e. Jesusmgg's repo).

**Comment by tylerlaprade** [comment]
<img width="444" alt="image" src="https://github.com/ryanoasis/nerd-fonts/assets/5475199/0c66f1fb-36ee-4816-bf0d-c4ad129922cf">
I successfully added the ligatures to the font. They are opt-in, so if people don't like them, it's no different than the font without any ligatures. I'm happy with them, since "symbols" make sense to be more formal looking than letters anyway.
