### ISSUE TITLE
FuraCode equasl sign not showing

### ISSUE THREAD

**Issue by anchnk** [ryanoasis/nerd-fonts#166]
#### Subject of the issue

Fura Code Regular doesn't display equals signs in gnome-terminal. I am using neovim 0.1.7

#### Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_

**FuraCode Nerd Font Regular `Fura Code Regular Nerd Font Complete.otf`** 

- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ 

**gnome-terminal**

- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ 

**Linux 4.8.0-53-generic x86_64 Ubuntu 16.04 LTS**

#### Optional

- _Provide **screenshots** where appropriate_

![broken-fura](https://cloud.githubusercontent.com/assets/515506/26578155/0db138ec-452f-11e7-817d-889bbf7a598e.jpg)

**Comment by agriffis** [comment]
FuraCode and gnome-terminal are known incompatible: https://github.com/tonsky/FiraCode#terminal-support

If you use FuraMono then it should work since that's Fira without all the ligatures.

**Comment by anchnk** [comment]
Oh ok ! Thank you for your answer. That's good to know. I didn't checked the font repository. Sorry for that. I am closing that issue as it's not a relevant to the project.
