### ISSUE TITLE
[website complaint] Font names are non-searchable images

### ISSUE THREAD

**Issue by willhansen** [ryanoasis/nerd-fonts#1660]
#### 🗹 Requirements

- [ x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x ] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x ] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

1. Go to this url: https://www.nerdfonts.com/font-downloads
2. press Control-f
3. type "tinos"
4. Be unable to find the Tinos Nerd Font (which IS on the page)

Expected behavior:

jump to the name of the font on the page

The font titles are images.  You can't search them!

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_
   N/A
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - N/A
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - N/A
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - N/A

**Comment by Finii** [comment]
Thanks for reporting.

Please check if the fix is ok. The preview is an image (instead of real text) for several reasons, but I made the font name searchable (kind of) ;-)

**Comment by Finii** [comment]
Tested on Linux Firefox, then Chromium.

After committed checked on Safari, and that is the only browser that highlights the hidden text. How great is that! Adapted the size a bit to better match the image via a6d13d97c:

<img width="1357" alt="Screenshot 2024-06-19 at 10 10 42" src="https://github.com/ryanoasis/nerd-fonts/assets/16012374/97ebcb6d-6638-4219-84ea-b3d390082f2a">
