### ISSUE TITLE
Add `markdownlint` for maintain consistent coding style across the entire project

### ISSUE THREAD

**Issue by mdsanima** [ryanoasis/nerd-fonts#1665]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues)
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

## The Problem

I've noticed that most of the _Markdown_ files in this project are **very chaotically** written and do not adhere to **standard** documentation writing rules in `*.md` files. My editor shows many errors in these files.

## The Solution

Add linter configuration file for _Markdown_ and _CommonMark_ files. This tool is a style checker and formatting tool for the files based on the _CommonMark_ specification. The tool is available as a command line tool and works with _Prettier_ as well.

See the [markdownlint](https://github.com/DavidAnson/markdownlint) repository for more info.

## Proposed Fixes

I can create a pull request with the necessary files that will allow you to maintain the markdown files according to the established specifications and perform formatting of all the markdown files in this project. Formatting these files will not change the content of the documents, it will only correct them according to the specifications.

These fixes are intended to maintain consistent style across all _Markdown_ documentation files in this project.

**Comment by mdsanima** [comment]
@Finii I hope this helps for the code base docs writing.

**Comment by Finii** [comment]
This sounds very good! :+1:
Please go ahead :-)

**Comment by mdsanima** [comment]
Great, I'll add a pull request regarding this issue soon.
