### ISSUE TITLE
Add "ExtraLight" version to the monaspice nerdfonts

### ISSUE THREAD

**Issue by Asqiir** [ryanoasis/nerd-fonts#1670]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

Monaspice fonts are heavier than other, comparable fonts. [src](https://github.com/ryanoasis/nerd-fonts/issues/1433)
I am always a fan of light fonts, using the "Light" version normally.
I'd like to use the "ExtraLight" version of Monaspace Argon, but it is not contained in nerdfonts.

### Desired Solution

Add "ExtraLight" Version to monaspice fonts.

**Comment by Finii** [comment]
Same question as this: https://github.com/ryanoasis/nerd-fonts/issues/1433#issuecomment-1822463500

Ok, I ll add this now but will come only on next release. Can put the prepatched archive here if that helps?

_Next release is like ... after the summer ... assuming northern hemisphere I mean, so September or something_

**Comment by Asqiir** [comment]
@Finii yes, this would help a lot!
(I use nixos, slightly altered packages are among the easier things ;) )

**Comment by Finii** [comment]
After commit 264c7383e61f49eaf6aa62c2d1314626b3c0db82, running `update.sh` and clearing out 'normal' source fonts:

```console
$ NERDFONTS="--makegroups 4 --debug 2" ./gotta-patch-em-all-font-patcher\!.sh -jv /Monaspace
$ ./archive-fonts.sh Monaspace
```

[Monaspace.tar.xz.gz](https://github.com/user-attachments/files/16045057/Monaspace.tar.xz.gz)
_Only ExtraLight, double archive because ..., 5 MB_

**Comment by Finii** [comment]
> I use nixos, slightly altered packages are among the easier things ;)

Then self-patching is also easy ;-q

**Comment by Finii** [comment]
Geee, this AI shit is not worth any try... Tell me something that's not obvious.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/82be9eb0-4a10-4a09-9ed2-409486687b1c)

**Comment by Finii** [comment]
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/0a742eba-bf04-484b-82ed-eb584d671a41)

**NO**, we do **not** add

* Programming ligatures (e.g., !==, =>, and >>=) for improved code readability
* Symbols for various languages, such as Japanese, Korean, and Chinese characters
* Mathematical and scientific symbols
* Emoji and other Unicode characters

Well, all is Unicode so the last one is only a half lie.

**Comment by Finii** [comment]
![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/f1ae9e14-84ac-4427-9c74-59828970e743)

Sorry, who? That persons's not even on the contributors list...

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/eda24abf-4821-4a8b-9522-ea4493faf760)

Thank you. Never mind, I'll use a traditional search engine next time.

**Comment by Finii** [comment]
ExtraLightItalic is missing :woman_facepalming: 

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/c4546580-a29c-48b0-9531-bb088448f9b9)
