### ISSUE TITLE
[glyph request] Inclusion of Obsidian icon/glyph

### ISSUE THREAD

**Issue by claudiofreitas** [ryanoasis/nerd-fonts#1672]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

I searched for the obsidian Icon to use in my Waybar config, but I could not find it.
Also could not find it already requested by using the Github search inside the whole repository (code, issues, discussions, etc).

### Desired Solution

From the [official post](https://obsidian.md/blog/new-obsidian-icon/) from Obsidian, I think the first 2 icons without the encircling would work good:

![image](https://github.com/ryanoasis/nerd-fonts/assets/212832/9dee8c3f-6e4e-4463-bd9a-88733fbcf9f7)

They have a [Figma asset](https://www.figma.com/community/file/1246118009912598137), which I guess the SVG could be extracted from, which they mention in the [brand](https://obsidian.md/brand) section of the website.

I am not sure about any license limitations though.

### Alternatives Considered

In the meanwhile I am using the `nf-fa-gem` () as alternative.

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095

It will be evaluated on next release.

**Comment by viluon** [comment]
Should this be reopened? There's still no Obsidian icon in NF, correct?

As a side note, would it make more sense to use [sub-issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/adding-sub-issues) instead of discussions for consolidating glyph requests?

**Comment by Finii** [comment]
Removed this from #1095

<img width="955" height="174" alt="Image" src="https://github.com/user-attachments/assets/6d46de96-b947-4b45-9674-ec9da5ddbab9" />
