### ISSUE TITLE
Add support for Symbols for Legacy Computing in JetBrains Mono

### ISSUE THREAD

**Issue by Leonard-Pat** [ryanoasis/nerd-fonts#1674]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

Apologies in advance if this feature request does not belong here, im very new to the world of fonts and encodings, however I was wondering if it would be possible to add support for the unicode ranges U+1FB00..U+1FBFF. These represent the Symbols for Legacy Computing.

### Desired Solution

Be able to display these characters

**Comment by Finii** [comment]
Thanks for raising the issue.

Duplicate #1301

**Comment by Finii** [comment]
Forgot to close, this is a duplicate.
