### ISSUE TITLE
[glyph request] AMD/Nvidia branding

### ISSUE THREAD

**Issue by CarterSnich** [ryanoasis/nerd-fonts#1678]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

**Comment by Finii** [comment]
No problem description given, closing.
