### ISSUE TITLE
Hermit font doesn't supports some icons 

### ISSUE THREAD

**Issue by karambaq** [ryanoasis/nerd-fonts#168]
Font: Hurmit Nerd Font

Terminal: urxt

OS: Antergos Linux

http://imgur.com/a/WkJe1

**Comment by ryanoasis** [comment]
@karambaq Thanks for the report.

Can you tell which codepoint glyph you are using (where the box shows instead) ?

**Comment by karambaq** [comment]
@ryanoasis I tried other themes and I think is 127.

![1screenshot-2017-06-18_22 43 34](https://user-images.githubusercontent.com/14233969/27263702-9ca76a74-5477-11e7-8917-739a6e9d3b99.png)

**Comment by ryanoasis** [comment]
@karambaq Sorry for the delayed follow up.

I'm not sure what you mean by 127? is that the codepoint?

Could you give the unicode codepoint (hex) of the glyph that is not showing?
e.g. the Powerline right pointing divider glyph (``) is `e0b0`

**Comment by karambaq** [comment]
@ryanoasis How can I identify codepoint?

**Comment by RuRo** [comment]
@karambaq I don't know, why I spent the last 10 minutes writing this, but here you go:
1) Highlight the symbol in question.
2) Copy it. You can google how to copy/paste text in *your* terminal, but it's generally "highlight+middle mouse button", "Ctrl-Shift-C/V" or "Highligh+RightClick(Opens Menu)".
3) Enter `echo -ne "\0\0\0here\0\0" | hexdump -C`, where `here` is where you paste your symbol.
​ ​ ​ ​ For example, `echo -ne "\0\0\0\0\0" | hexdump -C`.
4) Post the output here.
​ ​ ​ ​ For example, `00 00 00 ef 80 8c 00 00`
5) Bonus. You can try to paste this symbol in various different terminals and text editors e.t.c. to see if this is your terminals fault.

**Comment by ryanoasis** [comment]
@karambaq Do you still have this issues? Do @RuRo's steps help ?

**Comment by karambaq** [comment]
How it should work:
https://camo.githubusercontent.com/aaf960637a61c997f5daf8b4249df193b1465507/687474703a2f2f692e696d6775722e636f6d2f6558566e7561482e6a7067

How it works with Hermit:
https://imgur.com/gallery/FJGWs

I don't understand what to copy? 127?

**Comment by LuRsT** [comment]
Hi @karambaq, @RuRo meant to copy the symbol itself. I would double check that the terminal is picking up the right font, it's a paint to configure urxvt to get the right font since it's just a string in a file. Is this still an issue?

**Comment by ryanoasis** [comment]
@karambaq cannot replicate the issue exactly, I am triaging issues and this one I think should be closed. Feel free to ping again if you still have the issues and can tell us which character is not showing.

URxvt is notorious for issues with double width characters, see: https://github.com/ryanoasis/nerd-fonts/wiki/Terminal-Emulators#urxvt
