### ISSUE TITLE
[glyph request] typst icon

### ISSUE THREAD

**Issue by jonsch318** [ryanoasis/nerd-fonts#1682]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

Missing Icon for typst in all sources.

[Typst](https://github.com/typst/typst) A new markup-based typesetting system that is powerful and easy to learn. It can be seen as an alternative to latex.

I think it is quite popular with the Typst LSP vscode extension getting 45.9K downloads.

### Desired Solution

Add the typst-t icon to custom glyps.

I asked for permissions from the authors, and it is a valid use of their right [https://typst.app/legal/brand](https://typst.app/legal/brand).

The icon looks like:

![t-glyph](https://github.com/user-attachments/assets/f033b3cf-1c35-4015-822c-24bd64808186)

### Alternatives Considered

I have asked seti-ui in an issue [https://github.com/jesseweed/seti-ui/issues/703](https://github.com/jesseweed/seti-ui/issues/703) to include it in their icon, pack. It is not clear if they let it pass, due to it being not popular enough.

**Comment by Finii** [comment]
Please note #1587 

Maybe head over to Font Logos and leave a comment there, so that it will trickle back into NF on the next release?

**Comment by Finii** [comment]
* https://github.com/lukas-w/font-logos/pull/136

**Comment by Finii** [comment]
Will come with `v3.3.0` with Nerd Fonts updating to newest Font Logos :+1: thanks to Ulices.

**Comment by Finii** [comment]
Closing this as it will come with the FontLogos update with v3.3.0, and I just try to work through all Issues right now...
