### ISSUE TITLE
No fonts in latest release v3.2.1 work properly on oh-my-posh 

### ISSUE THREAD

**Issue by BornAsSlayer** [ryanoasis/nerd-fonts#1683]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have checked the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

### Experienced Behavior

I wanted to use zed mono fonts for my terminal and vscode from Nerd Fonts but Instead, only a few glyphs worked properly and most didn't, I downloaded Jetbrains mono, zed and Caskaydia code, but nothing worked I got the same result. But then I tried using the custom font patcher to patch my fonts manually Even those didn't work, I had the same result. Then I painstakingly tried fonts from older releases and then the only ones which worked were the ones from release v2.3.3.

### Expected Behavior

I expected all fonts to work normally in oh-my-posh and vscode like usual.

But I also noticed something, when I downloaded from release 2.3.3 I had another font within the same fonts called jetbrains..NFM but in a newer release it was not there just jetbrainsmono... 

This is what I expected
![image](https://github.com/user-attachments/assets/f2727489-19cb-46ce-b452-5c4cf810fad5)

### Font Used

CaskaydiaCove Nerd Font, CaskaydiaMono Nerd Font, FiraCode Nerd Font, JetBrainsMono Nerd Font, ZedMono Nerd Font

### Source of Font File

tried patching and downloading from https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.2.1 

### Terminal Emulator (and the title of the terminal window)

Latest Windows Terminal - Powershell 7
Oh-my-posh v14.2.2

### Operating System and Version

Windows 10

### Screenshots

![image](https://github.com/user-attachments/assets/4c169309-4d7e-43d5-9e00-78d50a19d901)

![image](https://github.com/user-attachments/assets/92b4fc47-f7c5-4c70-8a63-fab34555586f)

![image](https://github.com/user-attachments/assets/2f48fe92-6f74-4ff5-be46-850bcb480cad)

**Comment by Finii** [comment]
> only a few glyphs worked properly and most didn't

Comparing your images:

![image](https://github.com/user-attachments/assets/01aee597-7273-434d-ad6f-f5a66bd35b55)

Some icons are missing, for example for the `Music` folder, lets see on the cheat sheet, searching for "music":

![image](https://github.com/user-attachments/assets/a3667880-be7d-4d65-8872-900dfc868803)

I believe your missing icon is the `F832` in the bottom right of my image. As you see that icon has been removed (with Nerd Font 3.x.x). Probably all the other missing items are also material design icons with the old codepoints.

See

* https://github.com/ryanoasis/nerd-fonts/blob/master/changelog.md#v300
* #1190

>  Oh-my-posh v14.2.2

Probably you should update, current is `oh-my-posh v23.4.1`.

If you customized your oh-my-posh setup, possibly you need ta adapt the codepoints. See for example

* https://github.com/JanDeDobbeleer/oh-my-posh/issues/5052
* https://github.com/loichyan/nerdfix

**Comment by Finii** [comment]
Here the `oh-my-posh` changelog, it has been fixed with `v19.23.1`:

![image](https://github.com/user-attachments/assets/68fe9f83-a7d7-430c-9b9c-549421222a07)

**Comment by Finii** [comment]
Regarding the v3.0.0 change:

![image](https://github.com/user-attachments/assets/b702b446-c93d-4d40-97da-160d9b0d569a)
