### ISSUE TITLE
Bump Intel One Mono to V1.4.0

### ISSUE THREAD

**Issue by KaiserCalm** [ryanoasis/nerd-fonts#1684]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

Intel One Mono is now on version 1.4.0, the version 1.3.0 is used in Nerd Fonts.

### Desired Solution

Intel One Mono would be updated to version 1.4.0, because that version now has support for ligatures and box drawing glyphs.

**Comment by azzamsa** [comment]
Related: https://github.com/intel/intel-one-mono/releases/tag/V1.4.0
