### ISSUE TITLE
[New Font Request] Tamsyn

### ISSUE THREAD

**Issue by pa-0** [ryanoasis/nerd-fonts#1685]
### Requirements

- [X] I have searched the issues for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

In my opinion, Tamzen (_Tamsyn_) is a classically beautiful monospaced font that deserves a place among the other nerd-fonts :) 

### Desired Solution

Original font: [_Tamsyn_ by Scott Fial (http://www.fial.com/~scott/tamsyn-font/)](http://www.fial.com/~scott/tamsyn-font/)

Patched fork: [_Tamzen_ (which includes Powerline symbols) by @sunaku](https://github.com/sunaku/tamzen-font)

**Comment by Finii** [comment]
This looks interesting! Thanka for the suggestion. 

Do you use the bitmap or outline (ttf) font(s)?

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095

It will be evaluated on next release.
