### ISSUE TITLE
NerdFonts improvements

### ISSUE THREAD

**Issue by mdSlash** [ryanoasis/nerd-fonts#1688]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

Hi there, I requested adding Lucide Icons Solid #1606 to NerdFonts, but it ended up creating a whole new project with over 60k icons per font! Since NerdFonts lacks a lot of icon sets, I’ve patched some of the fonts myself, but I’d rather not keep them to myself or keep reinventing the wheel.

### Desired Solution

I’m here to help with adding new icon sets to NerdFonts and creating custom ones. I also have some ideas to improve NerdFonts, like fixing glyph alignment issues (#1330) and the alignment of special glyphs. You can check out more about this and other alignment details in [icon-types-and-alignment](https://github.com/iconicFonts/iconic-fonts#icon-types-and-alignment).

### Alternatives Considered

- Add aliases to icons. I discussed this in [Improve Icon Search](https://github.com/iconicFonts/iconic-fonts/issues/87).
- When adding more icon sets and aliases, the `glyphnames.json` file will become large, so consider using `CSV` or another alternative method to manage this.
- Introduce new codepoints for the new icon sets.
- I also noticed that NerdFonts uses some iconic fonts instead of SVG icons. Why is that? Perhaps NerdFonts should use SVGs to insert glyphs instead.
- ...

### Additional Context

The main goal of this issue is to improve NerdFonts by adding new icons, enhancing glyph search, and fixing alignment issues. I’m happy to discuss any questions you have—I’m not asking for anything in return. I already have these enhancements and want to integrate them into NerdFonts. I just want to help ensure everyone can access the icons they need. If you’re interested, let me know. Thanks!

**Comment by Finii** [comment]
I'm not sure what this issue is about and/or what to do with it.
It feels like you fixed all your problems yourselves in/with iconicFonts.

> happy to discuss any questions you have

Well, I noticed two things with iconicFonts
* There seems to be no patching script or anything to see how the patched fonts are created
* The patched fonts link on the start page do not work
* Some of the patched fonts obviously violate their respective license terms
* The glyphs have alignment issues that will result in the dreaded vertical colored lines (see image below)
* Negative-and-positive-space glyphs, I was curious how that should work and I guess that will also result in vertical aliasing issues
* The readme already states that codepoints will change in the future, which is a no-go imho; users' worst nightmares come true
* Somehow the termini used in the descriptions are off, what is a glyph, what is a character, a codepoint etc.

Hmm, I do not really see how iconicFonts and Nerd Fonts should mix (as projects).

**Comment by mdSlash** [comment]
Thanks for this amazing feedback!

> There seems to be no patching script or anything to see how the patched fonts are created

Yeah, the project is in beta and obviously needs a lot of adjustment, so the scripts aren’t ready to publish yet. But I can put together a mini version and send it if you'd like to see the scripts.

> The glyphs have alignment issues that will result in the dreaded vertical colored lines (see image below)

If you’re referring to the extra padding on the left or right, I didn’t do it on purpose because Kitty makes them small.

> Negative-and-positive-space glyphs, I was curious how that should work and I guess that will also result in vertical aliasing issues

Yeah, I didn’t notice any vertical aliasing issues while using the glyphs, so they weren’t apparent to me.

> Hmm, I do not really see how iconicFonts and Nerd Fonts should mix (as projects).

Maybe IconcFonts project could provide icons for NerdFonts, including adding/creating new icons or modifying them.

> I'm not sure what this issue is about and/or what to do with it.

for starters:
- It’d be great to see more icon sets in NerdFonts.
- Center-aligning the icons would make them look better.

**Comment by mdSlash** [comment]
Hey again, Here’s the [patching script](https://github.com/iconicFonts/iconic-fonts/tree/font-patcher). BTW, I’m gonna archive the IconicFonts project due to license issues.

This script shows a different way to create patched fonts. Instead of using iconic fonts, it uses SVG files. From my POV, SVGs are more flexible for manipulating icons.

The script should create patched fonts with the same NerdFonts icons and codepoints.

Run `fontforge --script font_patcher font` to center icons in two bounding boxes, or add any argument to center them in a single bounding box, see https://github.com/iconicFonts/iconic-fonts/issues/98

I'm curious about the issues NerdFonts encounters when adding new icon sets. Is there anything preventing the addition of new ones?

If this wasn’t helpful. Feel free to close the issue. Thanks!
