### ISSUE TITLE
Add Icons for SpiceDB

### ISSUE THREAD

**Issue by Smithx10** [ryanoasis/nerd-fonts#1690]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

SpiceDB has a Schema Language and a small LSP.  While hovering in Neovim SpiceDB has no Language Icon.

https://authzed.com/docs/spicedb/concepts/schema

![image](https://github.com/user-attachments/assets/1b43cc7e-2856-42e0-bbd2-789a4498790c)

### Desired Solution

An Icon be added for SpiceDB Schema Language.

### Alternatives Considered

Living with no icon :(

**Comment by hasecilu** [comment]
Searching for "db" on https://devicon.dev shows 10 different icons, maybe it's better to open an issue/PR there.

**Comment by Finii** [comment]
Yes (nodding to Ulices). And I think one can always use some generic database icon.
I see an Issues is open at devicons.
