### ISSUE TITLE
Update my username

### ISSUE THREAD

**Issue by realguse** [ryanoasis/nerd-fonts#1692]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have checked the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

### Experienced Behavior

When looking at the contributors tab on the website, you can see me (previously known as "guse") there, i recently changed my username on all platforms and now this is outdated. So what I'm asking for is that "guse" gets changed to "realguse".

### Expected Behavior

It should say "realguse" instead of "guse"

**Comment by realguse** [comment]
This link here should also be updated: "https://github.com/ryanoasis/nerd-fonts/commits?author=gu5e"
to "https://github.com/ryanoasis/nerd-fonts/commits?author=realguse"

**Comment by Finii** [comment]
Note to self:

One PR for ex.:
https://github.com/ryanoasis/nerd-fonts/pull/1667
