### ISSUE TITLE
Add Gleam Language Glyph

### ISSUE THREAD

**Issue by LelouchFR** [ryanoasis/nerd-fonts#1707]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

I've been searching on the cheat-sheet for a gleam icon, but seems to find none, so I have to take a unknown star instead.

### Desired Solution

It would be great to have a specific Icon for it instead of having to take a star and drop color on it.

**Comment by Finii** [comment]
https://gleam.run/branding/

**Comment by Finii** [comment]
> and drop color on it

Well, the Nerd Font icons are (also) all monochrome (i.e. black on white if your text is black on white), so you would still need to drop a bit of color onto the icon.

**Comment by LelouchFR** [comment]
> > and drop color on it
> 
> Well, the Nerd Font icons are (also) all monochrome (i.e. black on white if your text is black on white), so you would still need to drop a bit of color onto the icon.

Yes I understand that, but as an example, you know that the facebook icon is the facebook icon because of how it's made and not a simple f, so it would be cool to have the same for the gleam language, you know what I mean.

**Comment by Finii** [comment]
Duplicate #1591
