### ISSUE TITLE
Alien Icon (some Weather icons rather small)

### ISSUE THREAD

**Issue by vurtune** [ryanoasis/nerd-fonts#1708]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

Alien  (e36e) icon is too small on FiraCode Mono

### Desired Solution

Can you make a little more bigger?
Like 󰢚 (f089a)

**Comment by Finii** [comment]
<img width="169" alt="Screenshot 2024-09-16 at 08 07 57" src="https://github.com/user-attachments/assets/b5f110a2-462a-4854-b449-815765ac04f1">
<img width="169" alt="Screenshot 2024-09-16 at 08 08 19" src="https://github.com/user-attachments/assets/dd8bd4cf-ab53-42c1-9eba-5b87b5bf2c0e">

The icon looks different ;-)

Hmm, the weather "extra" icons are all so small, let me find out why

<img width="1010" alt="Screenshot 2024-09-16 at 08 11 21" src="https://github.com/user-attachments/assets/a77d290a-c4cb-4205-ad39-aa2e041de9d0">

The scaling code is this (the original icon codepoint is `F075` so it falls into the last of all rules:

```python
        WEATH_SCALE_LIST = {'ScaleGroups': [
            [0xf03c, 0xf042, 0xf045 ], # degree signs
            [0xf043, 0xf044, 0xf048, 0xf04b, 0xf04c, 0xf04d, 0xf057, 0xf058, 0xf087, 0xf088], # arrows
            range(0xf053, 0xf055 + 1), # thermometers
            [*range(0xf059, 0xf061 + 1), 0xf0b1], # wind directions
            range(0xf089, 0xf094 + 1), # clocks
            range(0xf095, 0xf0b0 + 1), # moon phases
            range(0xf0b7, 0xf0c3 + 1), # wind strengths
            [0xf06e, 0xf070 ], # solar/lunar eclipse
            # Note: Codepoints listed before that are also in the following range
            # will take the scaling of the previous group (the ScaleGroups are
            # searched through in definition order).
            # But be careful, the combined bounding box for the following group
            # _will_ include all glyphs in its definition: Make sure the exempt
            # glyphs from above are smaller (do not extend) the combined bounding
            # box of this range:
            range(0xf000, 0xf0cb + 1), # lots of clouds and other (Please read note above!)
        ]}
```

The original set looks like this

<img width="1010" alt="Screenshot 2024-09-16 at 08 15 41" src="https://github.com/user-attachments/assets/91953740-3b7f-4899-ad34-df6e665104ff">

Ok, thank you. I will do a search for the reasons ;-D

**Comment by Finii** [comment]
These are the scale groups visually

![image](https://github.com/user-attachments/assets/63f59305-98e0-4a9d-bd3c-40d903365653)

Note the orange brackets, that scale all not-marked glyphs between them (the `lots of clouds and other` group).

Clearly some icons do not belong in there, and maybe this is a new group:

![image](https://github.com/user-attachments/assets/78f0c42a-b018-49bb-b83d-2ec10f522550)

Also noticed that one wind direction is not in the wind direction group :grimacing: (`F0B1`)
