### ISSUE TITLE
Enhancement Of the Webpage

### ISSUE THREAD

**Issue by AshmitaBarthwal** [ryanoasis/nerd-fonts#1718]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

Made Changes to the website to make it more attractive for the users.
Added CSS properties to achieve the task.

VEDIO DEMONSTRATION:

https://github.com/user-attachments/assets/6ecf8aee-08fd-425f-8b14-b74eea081fb9

**Comment by Finii** [comment]
Sorry, I believe a background that "moves" color is rather distracting.
When something "moves" it catches you eyes, but ... that is background.

Thanks for the proposal, though.
