### ISSUE TITLE
Missing glyphs - ethernet, RAM and perhaps maybe more

### ISSUE THREAD

**Issue by anmolsekhon590** [ryanoasis/nerd-fonts#1719]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have checked the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

### Experienced Behavior

  glyphs are missing. I use them to customize my operating system but they don't render after installed Fira Code Nerd Font.
I Also tried installing the Noto Nerd Font from official website and that doesn't render as well. Other glyphs I use from Fira Code Nerd Font seem fine 

### Expected Behavior

  glyphs should render correctly as it did a months ago

### Example Symbols or Text

  

please refer to the 2nd glyph (from left side) provided in the screenshot

### Font Used

Fira Code Nerd Font 

### Source of Font File

downloaded zip from website then installed manually to my ~/.local/share/fonts directory

### Terminal Emulator (and the title of the terminal window)

alacritty

### Operating System and Version

Arch Linux

### Screenshots

![image](https://github.com/user-attachments/assets/a37b51e6-f499-4ff2-aeab-b198c4f40501)

**Comment by Finii** [comment]
Codes missing after update:

![image](https://github.com/user-attachments/assets/2f718240-adf9-4ed8-8349-0030e59e65f1)

`F538` and `F796` mentioned.

![image](https://github.com/user-attachments/assets/5e45d14a-e101-4865-b9e9-a7104035e90b)

See
* #1190

They have been removed quite some time ago now.

As per https://github.com/ryanoasis/nerd-fonts/issues/1059#issuecomment-1404891287

```
f538 f0039   apple_safari
f796 f0297   gamepad_variant
```

**Comment by Finii** [comment]
A look into the release notes...:

https://www.nerdfonts.com/releases (open `v3.0.0`)

![image](https://github.com/user-attachments/assets/0604d74b-87ff-445c-a55f-52628cf75433)

**Comment by anmolsekhon590** [comment]
Thank you! Seems like all I needed was to copy the new icons from the cheat sheet and paste them in my xsetroot scripts I use for my window manager i.e., dwm
