### ISSUE TITLE
Add Elm Icon

### ISSUE THREAD

**Issue by tylerthehaas** [ryanoasis/nerd-fonts#172]
#### Requirements

Currently there is not a font that includes an icon for the elm programming language.  This would be very nice to have as I am programming in that language more and more.  Thanks!

**Comment by ryanoasis** [comment]
Thanks for the suggestion 😄

**Comment by xasx** [comment]
Perhaps Devicons is also a good address for a request regarding programming languages?!

**Comment by xasx** [comment]
Good news: https://github.com/konpa/devicon/issues/30

**Comment by AnwarShah** [comment]
@ryanoasis hi! I couldn't contact with you so I mentined you here. Are you okay if I extract only the patcher scripts and symbols and made them available in a public repo? I wanted to fork ,but the repo is huge! Waiting to hear from you

**Comment by ryanoasis** [comment]
@AnwarShah Hey, just wondering what is the reason you want to do this?

Of course you are free to do what you want basically as long as you extract the license un-modified as well (to comply with the MIT license as far as I understand).


FYI, a better place to contact me is either: [Gitter Chat](https://gitter.im/ryanoasis/nerd-fonts), [e-mail me](http://ryanlmcintyre.com/), or even [Twitter](https://twitter.com/ryanlmcintyre)

**Comment by AnwarShah** [comment]
@ryanoasis Thank you. I just wanted to have the scripts available separately so that I can have them wherever I want and may be sync with the main repo when there is an update. I like patching my own fonts.

**Comment by ryanoasis** [comment]
@AnwarShah Oh okay that makes sense. If you copy a majority of the scripts include the license and all should be good. You can do whatever you want with them.

The only thing I will say is if you make any improvements or fixes that can be generally applied I would appreciate it if you could submit those back upstream (via a PR) for benefit of Nerd Fonts community :smile: though you are not required to do so. :wink:

**Comment by AnwarShah** [comment]
@ryanoasis That's great. Thank you!

**Comment by ryanoasis** [comment]
@xasx That is good news but Nerd Fonts uses [vorillaz/devicons](https://github.com/vorillaz/devicons)
