### ISSUE TITLE
U+efc5 (nf-fa-memory) no icon showing since last update (maybe before but tuesday was working).

### ISSUE THREAD

**Issue by yohanduartep** [ryanoasis/nerd-fonts#1720]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related or helpful
- [ ] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [ ] I have checked the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

### Experienced Behavior

I used to have this icon instead of that frog to represent my RAM and this week it became this weird symbol.
![image](https://github.com/user-attachments/assets/4f6cdf00-ef17-48d6-a24a-0cbefa06699e)

### Expected Behavior

This icon is the expected one
![image](https://github.com/user-attachments/assets/32eb66fe-edf2-4689-a190-ae7b85fdf394)

### Example Symbols or Text

U+efc5


**Comment by Finii** [comment]
Sorry to hear of your problem.

The icon you see looks a bit like `U+2553`

<img width="790" alt="Screenshot 2024-10-27 at 10 32 22" src="https://github.com/user-attachments/assets/f1fe42bc-a6a0-444e-b2dc-a70ec79b029b">

but with the wrong height.

Anyhow. It's not "memory".

Unfortunately you did not fill all the details in the Issue report
* Font file used
* Terminal
* OS

And what did you update (yesterday?)?

If you are on a typical Linux you can try `fc-list :charset=efc5` to see which fonts have that codepoint.
Make sure you do select the Nerd Font in your terminal.

As there was no Nerd Font update in a longer time I believe this must be something else.

**Comment by yohanduartep** [comment]
Sorry i took too long to answer. It turns out after some updates now its working! Thx btw
