### ISSUE TITLE
Add Hover Effect to all the buttons

### ISSUE THREAD

**Issue by jenyyy4** [ryanoasis/nerd-fonts#1725]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

**Comment by jenyyy4** [comment]
@ryanoasis i would like to work on this, please assign it to me.

**Comment by Finii** [comment]
Sorry I believe hover effects are distracting.

See also
* #1370
