### ISSUE TITLE
Enhance icon search on the website

### ISSUE THREAD

**Issue by fxzxmicah** [ryanoasis/nerd-fonts#1728]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

The current website icon search is so bad that finding the icon you need is very difficult.

### Desired Solution

Might need a feature where users can add appropriate tags or aliases for each icon?

**Comment by abhi-github-159084** [comment]
I am interested to do this, please assign it to me

**Comment by Finii** [comment]
Very good idea!

But I fear this will become unmaintainable in the future. At the moment users might have an interest, but this will be a constant maintenance burden for all the future and a boring job when sets are updated etc. Given the number of active contributors here I guess it is not realistic.
