### ISSUE TITLE
Please add Supabase and Timescale glyphs

### ISSUE THREAD

**Issue by nikelborm** [ryanoasis/nerd-fonts#1730]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related or helpful
- [X] I have checked the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have reviewed the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for relevant information

### Problem Description

Would be very nice to have them

### Desired Solution

https://supabase.com/brand-assets
https://www.timescale.com/brand

### Additional Context
Impact:
1. https://github.com/supabase/supabase - 73к stars
2. https://github.com/timescale/timescaledb -  18k stars

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095

It will be evaluated on next release.
