### ISSUE TITLE
Wiki is no longer accurate

### ISSUE THREAD

**Issue by Gitoffthelawn** [ryanoasis/nerd-fonts#1736]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have checked the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

### Experienced Behavior

If I'm reading the [changelog](https://www.nerdfonts.com/releases) correctly, [the wiki](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting#which-font) is no longer accurate.

Specifically, the wiki states:
>
Pick your font family and then select from the 'complete' directory.

  -  If you are on Windows pick a font with the 'Windows Compatible' suffix.
       - This includes specific tweaks to ensure the font works on Windows, in particular monospace identification and font name length limitations
  - If you are limited to monospaced fonts (because of your terminal, etc) then pick a font with the 'Mono' suffix.
       - This denotes that the Nerd Font glyphs will be monospaced not necessarily that the entire font will be monospaced

but the changelog states:

>
This release fixes some long standing issues that are due to the naming of the fonts: There is a completely new naming scheme. This might be inconvientient *[sic]* for existing setups, sorry.  
   - Some fonts will have Nerd Font in the name while other have it abbreviated as NF. This is needed because some names just were too long. (Same for Nerd Font Mono and NFM.)
   - There are no Windows Compatible fonts anymore. All fonts work on all platforms.
   - The Complete from the font names (and the repo directories) has been dropped (Complete is the new normal).
   - The name parts will be ordered as expected with style and weight last (Somefont Bold Nerd Font -> Somefont Nerd Font Bold).
   - The filename will have no blanks anymore.

### Expected Behavior

Consistency! Accuracy! World Peace! 😄

**Comment by Finii** [comment]
Thanks!

Fixed (hopefully ;)

**Comment by Finii** [comment]
> inconvientient [sic]

:rofl:

**Comment by Finii** [comment]
Seems to be a real word :grin: 

![image](https://github.com/user-attachments/assets/cf6607b9-0c8d-4352-ae94-c1f8573b529d)

Will fix that (when I finally get the last PR ready, just waiting for the patch runs to see if it now finally patches correctly)...

And Allcontributors seems to be broken _again_ \*sigh\*

**Comment by Gitoffthelawn** [comment]
> Thanks!
> 
> Fixed (hopefully ;)

You're welcome!  That was quick.  Looks much better!

ROTFL regarding *inconvientient* 🤣 🤣 🤣
