### ISSUE TITLE
ISSUE_TEMPLATE.md has bad link

### ISSUE THREAD

**Issue by kballard** [ryanoasis/nerd-fonts#174]
The issue template has the following line:

- [ ] I have read or at least glanced at the [Wiki](https://github.com/ryanoasisnerd-fonts/wiki)

Note that the link here is bad, it's missing a / character.

**Comment by ryanoasis** [comment]
@kballard Good catch! Thanks. Would you like to submit a Pull Request to fix?

**Comment by kballard** [comment]
Submitted as #179.
