### ISSUE TITLE
After setting the line spacing, the icon is displayed abnormally

### ISSUE THREAD

**Issue by A-caibird** [ryanoasis/nerd-fonts#1743]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have checked the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

### Experienced Behavior

I'm using alacritty on macOS15 and after setting line spacing in the profile, the icon doesn't show up
When I set the line spacing, some of the font icons became larger, but some of them didn't

### Expected Behavior

I want all the icons to be scaled up, up, down, left and right

### Example Symbols or Text

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
bold = {family = "MesloLGS NF", style = "Bold" }
size = 12.00
offset = { x = 0, y = 10 }

### Font Used

[font] normal = { family = "MesloLGS NF", style = "Regular" } bold = {family = "MesloLGS NF", style = "Bold" } size = 12.00 offset = { x = 0, y = 10 }

### Terminal Emulator (and the title of the terminal window)

alacritty

### Operating System and Version

macOS15

### Screenshots

<img width="856" alt="image" src="https://github.com/user-attachments/assets/39d7aee3-ebf9-41df-a22e-5fcffc5a1213">

**Comment by Finii** [comment]
> I want all the icons to be scaled up, up, down, left and right

The font does not know what you select as offset and inter-line-spacing; there is no way for that information to reach even the most advanced code in OpenType fonts.
That must be handled by the client (i.e. `alacritty`) as only it knows the cell size one you do not use what the font expects.

For example `iTerm` does that - in some cases. I believe `alacritty` is one of the more bare bone clients with no frills.

The only way to reliably achieve what you want is self-patching with setting your desired cell size on patching. Then all the stuff is scaled to that cell size.

What you expect is technically not possible from the font side.

**Comment by A-caibird** [comment]
> > I want all the icons to be scaled up, up, down, left and right
> 
> The font does not know what you select as offset and inter-line-spacing; there is no way for that information to reach even the most advanced code in OpenType fonts. That must be handled by the client (i.e. `alacritty`) as only it knows the cell size one you do not use what the font expects.
> 
> For example `iTerm` does that - in some cases. I believe `alacritty` is one of the more bare bone clients with no frills.
> 
> The only way to reliably achieve what you want is self-patching with setting your desired cell size on patching. Then all the stuff is scaled to that cell size.
> 
> What you expect is technically not possible from the font side.

Thank you, i understand . Yesterday , by comparing terminal emulators like kitty, i discovered that the issue seems to be related to Alacritty's font rendering
