### ISSUE TITLE
.ttc files don't work

### ISSUE THREAD

**Issue by lilyball** [ryanoasis/nerd-fonts#175]
#### Subject of the issue

The font patcher doesn't handle .ttc files correctly. It produces a weirdly-named file that seems to contain the data for the first font in the .ttc file, though Font Book.app says it doesn't pass validation.

I tried this using /System/Library/Fonts/Menlo.ttc.

FWIW here's an [old unmerged PR](https://github.com/powerline/fontpatcher/pull/6) that adds support for .ttc files to the Powerline font patcher.

#### Your Setup

- macOS 10.12.5

**Comment by ryanoasis** [comment]
@kballard Okay thanks :smile: I wasn't aware of this.

It would be nice to support this eventually provided we get some help :blush:, however I would say this is not a high priority

**Comment by taohex** [comment]
I encountered this problem, too. Menlo is the default font in macOS, I think it's important.

**Comment by RuRo** [comment]
Same problem on Manjaro Linux with the default `Noto Sans` font.  
My workaround is to use `fontforge` to convert `.ttc` to `.ttf` before patching the font:  
`fontforge -lang=pe -c "Open(\$1);Generate(\$1:r+'.ttf')" SomeFont-Regular.ttc`

**Comment by ryanoasis** [comment]
I have some renewed interest in supporting this :smile:

**Comment by LuRsT** [comment]
We could add that bit that @RuRo mentioned to the docs or make this a future feature, since you have renewed interest in supporting this, is it going to be in the roadmap @ryanoasis ?

**Comment by ryanoasis** [comment]
>  since you have renewed interest in supporting this

Oh I did say that didn't I? :laughing: 

I think we can try to target v2.1.0 (i.e. next release) unless I am missing it looked somewhat straight forward to implement.

**Comment by benfrain** [comment]
Could this be the reason I can't patch `Iosevka Slab` following the readme? https://github.com/ryanoasis/nerd-fonts/discussions/735
