### ISSUE TITLE
Mono fonts have same family name as double-width fonts

### ISSUE THREAD

**Issue by kballard** [ryanoasis/nerd-fonts#176]
#### Subject of the issue

When generating single-width fonts, the PostScript Name and Full name of the font both identify it as Mono, but the Family doesn't. This means if I install both mono and double-wide versions of the same font, I end up with one font family that contains two "Regular" fonts. This makes it rather difficult to actually use properly.

Instead I think the patcher should add "Mono" to the family of the font.

#### Your Setup

- macOS 10.12.5

**Comment by RuRo** [comment]
Agreed! In fact, on some systems the font management gui doesn't even allow to have both the Mono and Normal variations installed at the same time, because "this font already exists".

**Comment by ryanoasis** [comment]
Thanks.

Yeah this does seem to be an issue. I believe we can fix it without much effort.

Related: #140

**Comment by kballard** [comment]
Submitted as #178.
