### ISSUE TITLE
Site: Wrong Link for Font Preview

### ISSUE THREAD

**Issue by crummyh** [ryanoasis/nerd-fonts#1766]
### Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have checked the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

### Experienced Behavior

The "preview" link for "departureMono" points to [https://www.programmingfonts.org/#departure-mono](https://www.programmingfonts.org/#departure-mono).

### Expected Behavior

It should point to [https://www.programmingfonts.org/#departure-mono](https://www.programmingfonts.org/#departure-mono)

### Font Used

DepartureMono

**Comment by Finii** [comment]
Thanks for noticing and reporting this!

**Comment by Finii** [comment]
@allcontributors please add @crummyh for doc
