### ISSUE TITLE
some icons don't display correctly in fbterm

### ISSUE THREAD

**Issue by shadow-absorber** [ryanoasis/nerd-fonts#1769]
### Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have checked the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

### Experienced Behavior

when running `:NvimWebDeviconsHiTest` in neovim some icons like the docker ones are displayed as a box with a question mark instead of the docker icon inside of fbterm

### Expected Behavior

when running `:NvimWebDeviconsHiTest` in neovim that all icons display properly

### Example Symbols or Text

```
󰡨  compose.yaml                DevIconDockerfile               ctermfg=68 guifg=#458ee6
󰡨  docker-compose.yml          DevIconDockerfile               ctermfg=68 guifg=#458ee6
󰡨  docker-compose.yaml         DevIconDockerfile               ctermfg=68 guifg=#458ee6
󰡨  containerfile               DevIconDockerfile               ctermfg=68 guifg=#458ee6
󰡨  .dockerignore               DevIconDockerfile               ctermfg=68 guifg=#458ee6
󰡨  dockerfile                  DevIconDockerfile               ctermfg=68 guifg=#458ee6
󰡨  compose.yml                 DevIconDockerfile               ctermfg=68 guifg=#458ee6
```

### Font Used

Mononoki Nerd Font Mono

### Source of Font File

ttf-mononoki-nerd arch linux extra repo

### Terminal Emulator (and the title of the terminal window)

fbterm

### Operating System and Version

endeavour os on 6.12.6-arch1-1kernel

### Screenshots

![brokenicon](https://github.com/user-attachments/assets/fcdfada3-3098-48d0-b626-02114d7d3460)

**Comment by Finii** [comment]
Sorry to hear of your problems.

Lets see

```
󰡨  compose.yaml                DevIconDockerfile               ctermfg=68 guifg=#458ee6
󰡨  docker-compose.yml          DevIconDockerfile               ctermfg=68 guifg=#458ee6
󰡨  docker-compose.yaml         DevIconDockerfile               ctermfg=68 guifg=#458ee6
󰡨  containerfile               DevIconDockerfile               ctermfg=68 guifg=#458ee6
󰡨  .dockerignore               DevIconDockerfile               ctermfg=68 guifg=#458ee6
󰡨  dockerfile                  DevIconDockerfile               ctermfg=68 guifg=#458ee6
󰡨  compose.yml                 DevIconDockerfile               ctermfg=68 guifg=#458ee6
```

This is always the same icon, `F0868`:

![image](https://github.com/user-attachments/assets/be27e791-6fc5-42d1-a8d9-82d0d4336551)

And that glyph exists in the font:

![image](https://github.com/user-attachments/assets/b0db6a02-0354-4517-8111-bcbee3dd7151)

I suspect this is a limit of`fbterm`. Did you try any other terminal emulator, a simple and 'dump' one that does render the glyphs on its own, like gnome terminal or tilix? I can not find any current code repository, and maybe it (fbterm) is just too old and unmaintained? The last version here https://code.google.com/archive/p/fbterm/ is from 2010 :grimacing:

**Comment by shadow-absorber** [comment]
it works in ghostty and alacritty and kitty so yeah probably specific to fbterm... fbterms most maintained handling is the aur package for arch which has a few patches

**Comment by shadow-absorber** [comment]
[https://salsa.debian.org/debian/fbterm](https://salsa.debian.org/debian/fbterm)
this is the upstream of the aur package
and this is the aur package link
[https://aur.archlinux.org/packages/fbterm](https://aur.archlinux.org/packages/fbterm)

**Comment by Finii** [comment]
I close this as this issue is a problem that (most probably) fbterm just stores ucs-2 instead of utf-16 or the nowadays popular utf-8.
That was a popular way to handle things back then, but breaks of course with todays codepoints.

In fact the same problem still (?) hounts Windows' old cmd command window that also seems to support utf-16 but in fact uses ucs-2 instead and can not represent any codes bejond FFFF.
