### ISSUE TITLE
add overpass-mono font

### ISSUE THREAD

**Issue by andyfitz** [ryanoasis/nerd-fonts#177]
Overpass-Mono fonts are great; it would be awesome to see it expanded to support the nerd-font extensions.

https://github.com/RedHatBrand/Overpass

What assistance is needed to port this font ?

**Comment by ryanoasis** [comment]
@andyfitz Thanks for the font suggestion.

As for supporting you can look here: [Steps for adding a new font or removing an existing font (wiki)](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md#steps-for-adding-a-new-font-or-removing-an-existing-font)

**Comment by tamirco2003** [comment]
On it.

**Comment by tamirco2003** [comment]
Wait, having some trouble patching it...

How do you test patch the font.

**Comment by tamirco2003** [comment]
Nevermind, gave up.
Up for grabs again.

**Comment by ryanoasis** [comment]
@tamirco2003 Oh no sorry about that. What was the trouble you ran into?

> How do you test patch the font?

You can either open up the font in FontForge or your OS character map program and visually inspect the glyphs at the various codepoints... or you can run the (test-fonts script)[https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/test-fonts.sh] from a terminal.

Sorry if that is too little too late. :disappointed:
