### ISSUE TITLE
Fira Code uses "square" for empty array ([])

### ISSUE THREAD

**Issue by aidanharris** [ryanoasis/nerd-fonts#180]
Before:

![](https://i.imgur.com/iCGX0hV.png)

After:

![](https://i.imgur.com/8txTCEd.png)

I'm using the FuraCode Nerd Font with the Retina variant at size 14 (in case it matters)

I think this "issue" should just go away if the font is re-patched with the latest version of the font although I'm not sure how to test this.

**Comment by ryanoasis** [comment]
@aidanharris Thanks for this 👍 . We'll make sure to upgrade before the next release and repatching

**Comment by ryanoasis** [comment]
@aidanharris I wasn't able to replicate this issue but moving forward with the update of Fira Code :smile:

**Comment by ryanoasis** [comment]
@aidanharris Hey did you close this because #181 was merged or because it isn't an issue or another reason? Thanks
