### ISSUE TITLE
Patching Menlo adds ligatures it shouldn't

### ISSUE THREAD

**Issue by kballard** [ryanoasis/nerd-fonts#186]
#### Subject of the issue

Patching Menlo changes the default setting of the "Common Ligatures" typography option, enabling ligatures when they normally aren't. If I open TextEdit and I switch the font to Menlo and look at the Typography options, it's got a setting for "Common Ligatures" that's off by default. If I switch to Menlo Nerd Font, that option becomes enabled by default. This means words like "pdflatex" are no longer monospaced (due to "fl") even though it's a monospace font. And this does affect Menlo Nerd Font Mono as well.

The Powerline font patcher has this issue as well (powerline/fonts#42).

#### Your Setup

- Menlo
- My terminal (Terminal.app) disables ligatures, so it's not a problem there, but it is a problem in general-purpose text editors.
- macOS 10.12.5
- Nerd Font patcher used was 39db2fb0c255c75e27de59a4ed8f211a867be59e

**Comment by ryanoasis** [comment]
@kballard Thanks for the report :smile: and details. I will try to take a look (but I can't say how soon that'll be)

**Comment by ryanoasis** [comment]
Seems we can solve this with `removePosSub`. I will play around with this this weekend 😄

**Comment by ryanoasis** [comment]
@kballard Seems we can deal with this but it affects multiple fonts with different possible ligatures.

Can you try this WIP font out (seems to be working for me!): 
[Meslo LG M Regular Nerd Font Complete Mono.ttf.zip](https://github.com/ryanoasis/nerd-fonts/files/1735281/Meslo.LG.M.Regular.Nerd.Font.Complete.Mono.ttf.zip)
