### ISSUE TITLE
Missing IDs for the patched Mononoki fonts

### ISSUE THREAD

**Issue by laughedelic** [ryanoasis/nerd-fonts#189]
#### Subject of the issue

I'm trying to install patched Mononoki fonts and here's what I see:

![screen shot 2017-08-04 at 9 45 36 am](https://user-images.githubusercontent.com/766656/28959213-b7528b0a-78f9-11e7-930d-2fb80d201272.png)

The problem is with the `UniqueID` appearing in Style and PostScript name fields (notice that the Unique name and Full name say that it's Italic). The only style that has correct ID is BoldItalic, the other 3 have this problem and are reported as duplicates: Regular, Italic, Bold.

#### Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   `mononoki Bold Italic Nerd Font Complete Mono.ttf`
   `mononoki Bold Nerd Font Complete Mono.ttf`
   `mononoki Italic Nerd Font Complete Mono.ttf`
   `mononoki-Regular Nerd Font Complete Mono.ttf`
    (checked also the ones without `Mono` suffix)
- maxOS Sierra 10.12.5

**Comment by laughedelic** [comment]
Sorry I just noticed that it's a duplicate of #126 😓  
So is it fixed in v1.1.0? When is it going to be released?

**Comment by ryanoasis** [comment]
Yep it will be fixed in v1.1.0

Should be released this weekend, at least I will push up the fonts and you'll be able to try it out.

Thanks

**Comment by ryanoasis** [comment]
Fonts have been uploaded. Feel free to test them out. :smile: 

Closing this for now

**Comment by laughedelic** [comment]
Thanks! Releases page still shows 1.0.0 as the latest. But I downloaded it from the repo files.

The IDs looks fine 👌 But when I was installing I got this error:

<img width="735" alt="screen shot 2017-08-05 at 15 29 34" src="https://user-images.githubusercontent.com/766656/28995878-b9668d6e-79f4-11e7-9cca-29292f022a11.png">

And _excatly the same_ for the Mono version of BoldItalic.

**Comment by ryanoasis** [comment]
You're right the release hasn't been built yet. Will be either today or tomorrow.

I don't think that warning is something to worry about but I will look into it more. Thanks
