### ISSUE TITLE
What is DZ vs non-DZ?

### ISSUE THREAD

**Issue by maxwellmckinnon** [ryanoasis/nerd-fonts#190]
Newbie to fonts here, and googling "DZ fonts" isn't educating me.

What is the difference between LG L, LG L DZ, LG M, etc? I believe L, M, and S correspond to Large, Medium, and Small. How about DZ? Can this be added to the documentation in the install instructions?

**Comment by Liquidmantis** [comment]
@maxwellmckinnon 
L M S refers to the top and bottom padding that affects the line spacing.

DZ is dotted zero rather than slashed.

**Comment by ryanoasis** [comment]
Thanks @Liquidmantis 

Also SZ would be 'slashed zero'

Perhaps we could add a blurb on the wiki to cover these and could consider this issue closed :smile:

**Comment by ryanoasis** [comment]
This is now in the wiki: https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting#what-do-these-acronym-variations-in-the-font-name-mean-lg-l-m-s-dz-sz

closing for now :smile: 

Thanks all
