### ISSUE TITLE
README needs to be updated 

### ISSUE THREAD

**Issue by betolink** [ryanoasis/nerd-fonts#191]
The [https://github.com/ryanoasis/nerd-fonts#option-6-ad-hoc-curl-download](https://github.com/ryanoasis/nerd-fonts#option-6-ad-hoc-curl-download) section has:

cd ~/.local/share/fonts && curl -fLo "Droid Sans Mono for Powerline Nerd Font Complete.otf" https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20for%20Powerline%20Nerd%20Font%20Complete.otf
 
which returns a 404, the URL should be updated to:

https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf

I guess it's the same for other URLs with the same https://raw.githubusercontent.com/ domain.

**Comment by reujab** [comment]
Thank you. This has been fixed in 79be9ae.
