### ISSUE TITLE
Powerline Extra Symbols does not work with powerlevel9k

### ISSUE THREAD

**Issue by shibumi** [ryanoasis/nerd-fonts#195]
#### Subject of the issue

_Describe issue here_

#### Your Setup

- Used font: inconsolata
- Terminal: Termite
- Distribution: Arch Linux

#### Optional

My Termite config:
```
[options]
font         = inconsolata 9
allow_bold   = true
cursor_blink = off
browser      = chromium
audible_bell = false
```

Output of your test-powerlines.sh script: (sorry for the white lines.. no idea why I have this)
![](https://paste.archlinux.de/V4i/)

As you can see the only stuff what is working is this > and < seperator... Do I need to create some fontconfig or other stuff? I installed nerd-fonts via this PKGBUILD from the AUR:

```
# Maintainer: Super Bo <supernbo@gmail.com>
pkgname=nerd-fonts-complete
pkgver=1.1.0
pkgrel=1
pkgdesc="collection of over 20 patched fonts (complete variant) for powerline, devicons, and vim-devicons: includes Droid Sans, Meslo, AnonymousPro, ProFont, Inconsolta, and many more"
arch=('any')
url='https://github.com/ryanoasis/nerd-fonts'
_url="https://raw.githubusercontent.com/ryanoasis/nerd-fonts/$pkgver/patched-fonts"
license=('MIT')
depends=('fontconfig' 'xorg-font-utils')
conflicts=(nerd-fonts-git)
install=$pkgname.install
source=(
    "$_url/Inconsolata/complete/Inconsolata%20for%20Powerline%20Nerd%20Font%20Complete%20Mono.otf"
    "$_url/Inconsolata/complete/Inconsolata%20for%20Powerline%20Nerd%20Font%20Complete.otf"
    "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/$pkgver/LICENSE"
)
md5sums=('1596d05214b737d5c6a4f3ad9f0db54f'
         'fffd2d2508c1ddfbc50b64cd5c6d8c53'
         '1ac517b2f87f57fb806d71676c1cfc01')

build() {
    for f in *%20*.otf; do
        mv "$f" "${f//\%20/ }"
    done
}

package() {
    install -d ${pkgdir}/usr/share/fonts/OTF/
    install -d ${pkgdir}/usr/share/licenses/${pkgname}
    install -Dm644 ${srcdir}/*.otf ${pkgdir}/usr/share/fonts/OTF
    install -Dm644 ${srcdir}/LICENSE ${pkgdir}/usr/share/licenses/${pkgname}
}
```

HINT: I have also some issues with other icons but not with all. Just some icon collision with chinese and japanese symbols..

**Comment by ryanoasis** [comment]
Thanks for the report

> Output of your test-powerlines.sh script: (sorry for the white lines.. no idea why I have this)

No need to apologize! That is actually from me and on purpose. I was trying to make it easier to identify any vertical overhangs on the powerline glyphs :smile: 

> Do I need to create some fontconfig or other stuff?

You don't need to create a fontconfig and shouldn't need to do anything other than install the font and set the terminal to use said font.

Are you sure the terminal is pointing to the Nerd Font variation of inconsolata (i.e. Inconsolata Nerd Font Complete) and not just the 'vanilla' Inconsolata ?

Have you tried in any other terminals? Can you try running and capture the output of the [`test-fonts.sh script`](https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/test-fonts.sh)

**Comment by shibumi** [comment]
problem is solved. I still used the old inconsolata font not the patched one. But I still have issues with the size of some icons. They are too small.

**Comment by ryanoasis** [comment]
@shibumi Great! Thanks for the update!

> But I still have issues with the size of some icons. They are too small.

You may be interested in issue #127
