### ISSUE TITLE
Add Iosevka Term variant (no ligations)

### ISSUE THREAD

**Issue by cemsbr** [ryanoasis/nerd-fonts#198]
#### Requirements

By posting an issue you acknowledge the following:

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### Subject of the issue

Iosevka Nerd Mono is displaying, for example, `a = a` in a way that the equal sign is larger and above both `a`s. I'm using gnome-terminal. To overcome this problem, there's the Iosevka Term variation that disables the ligations and everything looks normal in my setup. Maybe the Term variant could be used for the Nerd Mono instead of creating another Iosevka Nerd font.

#### Your Setup

- Iosevka Nerd Font Mono Regular
- gnome-terminal
- Debian stretch (stable, 9.1)

#### Optional

Let me know if you need screenshot.

**Comment by ryanoasis** [comment]
@cemsbr Hey thanks for the issue.

So basically you are suggesting to use the version without ligatures by default?

If you have a screenshot that would be nice to have.

**Comment by cemsbr** [comment]
Yes, that's it, for the Mono type. Patching Iosevka Term would solve this issue. Screenshots of gnome-terminal:

Iosevka Nerd Font Mono Regular
![iosevka_nerd_mono](https://user-images.githubusercontent.com/49481/31511975-d4e40aa8-af5f-11e7-80eb-edf88bb916fc.png)
![iosevka_term](https://user-images.githubusercontent.com/49481/31511984-dc590ef0-af5f-11e7-85cb-5f8f330f7d58.png)
Non-Nerd Iosevka Term Regular

**Comment by ryanoasis** [comment]
I think this one should do it: https://github.com/be5invis/Iosevka/releases/download/v1.14.0/02-iosevka-term-1.14.0.zip

I will look into it tomorrow or this weekend. 🤞

**Comment by masaeedu** [comment]
I'm grepping through fc-list for a ligature related variant of Iosevka but can't find anything. Does this mean the Iosevka fonts installed through nerd-fonts can't be used with ligatures enabled?
