### ISSUE TITLE
Add Tinos font

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#200]
#### Add Tinos font

Add a new font: Tinos

Follow the [Wiki instructions for adding a new font](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md#steps-for-adding-a-new-font-or-removing-an-existing-font)

* Mostly this involves:
  * Putting files in the right place
  * Running the patching script
  * Verifying (sanity check is fine) the glyphs in the font
  * Updating certain metadata in files (e.g. the readme)

**Comment by jerezereh** [comment]
I'll try it out.

**Comment by ryanoasis** [comment]
@jerezereh That was quick. Sure thanks. 👍

**Comment by ryanoasis** [comment]
Fixed with #201. Thanks again
