### ISSUE TITLE
Add Arimo font

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#206]
#### Add Arimo font

Add a new font: Arimo

Follow the [Wiki instructions for adding a new font](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md#steps-for-adding-a-new-font-or-removing-an-existing-font)

* Mostly this involves:
  * Putting files in the right place
  * Running the patching script
  * Verifying (sanity check is fine) the glyphs in the font
  * Updating certain metadata in files (e.g. the readme)

**Comment by Ksbugbee** [comment]
I'll tackle this for you.

**Comment by ryanoasis** [comment]
Hey @Ksbugbee! :smile: That was fast.

It's all yours, let me know if you need any help or have questions!

**Comment by ryanoasis** [comment]
Hey @Ksbugbee my bad, but could you try with a different font? Perhaps [Arimo](https://fonts.google.com/specimen/Arimo) ?

@bbrks Already has a PR for GoMono (#199)

**Comment by steoneill** [comment]
If this still needs doing im happy to.

**Comment by ryanoasis** [comment]
@steoneill I do not think this still needs assigning (as @Ksbugbee has worked on it in PR #207)

@steoneill If you would like, you can create a PR that tackles another font instead. There are quite a few other fonts you could add. The process is very similar for any additional fonts anyway :smile: 

You can find a font as long as the licesnse allows or if you want here are some ideas of fonts that could be patched still: InputMono, NotoMono, NovaMono.
