### ISSUE TITLE
Add Cousine font

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#208]
#### Add Cousine font

Add a new font: [Cousine](https://fonts.google.com/specimen/Cousine)

Follow the [Wiki instructions for adding a new font](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md#steps-for-adding-a-new-font-or-removing-an-existing-font)

* Mostly this involves:
  * Putting files in the right place
  * Running the patching script
  * Verifying (sanity check is fine) the glyphs in the font
  * Updating certain metadata in files (e.g. the readme)

**Comment by de-olagundoye** [comment]
This was done here https://github.com/ryanoasis/nerd-fonts/pull/209
