### ISSUE TITLE
Add 'Noto' font (all variations, including 'mono')

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#213]
#### Add 'Noto Mono' font

Add a new font: [Noto Mono](https://www.google.com/get/noto/#mono-mono)

Follow the [Wiki instructions for adding a new font](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md#steps-for-adding-a-new-font-or-removing-an-existing-font)

* Mostly this involves:
  * Putting files in the right place
  * Running the patching script
  * Verifying (sanity check is fine) the glyphs in the font
  * Updating certain metadata in files (e.g. the readme)

**Comment by djphan** [comment]
Hi I'd like to try and help with this.

**Comment by djphan** [comment]
Licensing checks out: Uses SIl - http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL

**Comment by ryanoasis** [comment]
Sure thanks @djphan it's all yours.

Let us know if you have any questions.

**Comment by ryanoasis** [comment]
@djphan Still interested in this or can I safely take it over?
