### ISSUE TITLE
'Hack' font updated to 3.000

### ISSUE THREAD

**Issue by aquatix** [ryanoasis/nerd-fonts#216]
#### Subject of the issue

The 'Hack' (Knack) font has got a new (major) release. It'd be great (coffee) if it could be updated in this awesome collection too :)

#### Your Setup

- Knack Regular Nerd Font Complete Mono.ttf
- `gnome`, `xfce4-terminal`
- Ubuntu Linux 17.10

**Comment by ryanoasis** [comment]
@aquatix Thanks for the update! Very cool.

What I found most interesting was the move to MIT license: 'the reserved font name “Hack” was eliminated from the license'

**Comment by aquatix** [comment]
Cool! Was wondering about the ramifications of the change of license, but this sounds really positive. Can't wait to have the updated version in nerd-fonts ;)

Thanks for this great project, it makes my CLI life so much better (and I live and breath terminals).

**Comment by aquatix** [comment]
Cool! Was wondering about the ramifications of the change of license, but this sounds really positive. Can't wait to have the updated version in nerd-fonts ;)

Thanks for this great project, it makes my CLI life so much better (and I live and breath terminals).

**Comment by aquatix** [comment]
Fascinating double post there. Anyway, I updated to v1.2.0, but I don't think the newer Hack font is in there?

Thanks for this collection anyway, it's awesome :)

**Comment by ryanoasis** [comment]
@aquatix 

> Fascinating double post there.

Hahah yeah I did notice that too :man_shrugging: 

> I updated to v1.2.0, but I don't think the newer Hack font is in there

Hmm I will take a look this weekend. Do you mean it is not there as in the features of that release or the internal version is wrong?

There was a font (I don't remember which) where the internal version on some of the font weights was incorrect.

> Thanks for this collection anyway, it's awesome :)

That really does mean a lot! Thanks! :smile: . Community is making it awesome :blush:

**Comment by aquatix** [comment]
Ah, no worries, was just wondering if anything happened with Hack, as the binaries seemed exactly the same (no pressure, just Need Updates :P ).

Figured you don't hear 'thank you' enough, so here it is again: thanks for your work!

**Comment by ryanoasis** [comment]
> Figured you don't hear 'thank you' enough, so here it is again: thanks for your work!

We can probably get Hack updated soon in master.. but the releases tend to go slow.. although a lot faster now with the new [KISS workflow](https://github.com/ryanoasis/nerd-fonts/wiki/Development-Workflow)... 

Thanks! :blush:

**Comment by aquatix** [comment]
KISS and 'release early, release often' are some of the better ideas to work with :) Big releases suck, they tend to grow larger and larger and suck energy to ensure everything still works.

I can wait ;)

**Comment by aquatix** [comment]
Yay :)
