### ISSUE TITLE
Character '\u21B5' is not displayed correctly

### ISSUE THREAD

**Issue by ColinZeb** [ryanoasis/nerd-fonts#219]
like this:
![return.png](https://i.loli.net/2017/11/28/5a1cc6318d213.png)

the font is consola.ttf from windows 10.
the command is `fontforge -script font-patcher -w -c -s -ext otf -out /var/www/download/fonts  ~/consola.ttf` and executed by ubuntu 16.04

result of execute 'fontforge --version '

> Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
>  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
>  with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
>  Based on sources from 00:15 UTC 31-Jul-2017-ML-D.
>  Based on source from git with hash: b9149c13e8f9464fc21473f1f676b36a2130775d
> no xdefs_filename!
> TESTING: getPixmapDir:/usr/share/fontforge/pixmaps
> TESTING: getShareDir:/usr/share/fontforge
> TESTING: GResourceProgramDir:/usr/bin
> trying default theme:/usr/share/fontforge/pixmaps/resources
> fontforge 00:15 UTC 31-Jul-2017
> libfontforge 20170731
>

**Comment by ryanoasis** [comment]
Thanks for the report 👍 . I'll look into this, but no promises as to when.

**Comment by ryanoasis** [comment]
`21b5` is not part of Nerd Fonts, most of the source fonts I look at don't have it. Even the Consolas I looked at doesn't include in the font. At least on my system that character is coming from Symbola.

However we _could_ add those to fonts that don't have particular symbols, using Symbola or similar.
