### ISSUE TITLE
Feature request: Could source/sauce code pro semibold be included?  

### ISSUE THREAD

**Issue by sagotsky** [ryanoasis/nerd-fonts#22]

**Comment by ryanoasis** [comment]
Sure :smile:

**Comment by ryanoasis** [comment]
Uploaded a bunch more fonts. Feel free to give 1 a try :smile:

**Comment by sagotsky** [comment]
Looks good!  Ty for the fast response too!

**Comment by ryanoasis** [comment]
Going to close this. Reopen if any specific issue related to just sauce code pro.
