### ISSUE TITLE
Roboto Mono fonts has incorrect horizontal spacing?

### ISSUE THREAD

**Issue by fornwall** [ryanoasis/nerd-fonts#220]
It looks like the Robot Mono fonts from nerd-fonts:

- https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/RobotoMono/complete/Roboto%20Mono%20Nerd%20Font%20Complete%20Mono.ttf

adds a lot of space compared to e.g. the one provided by google at:

- https://github.com/google/fonts/raw/master/apache/robotomono/RobotoMono-Regular.ttf.

See the following screen shots comparing them:

- From google:
![roboto-nerd-font-regular](https://user-images.githubusercontent.com/13117753/33507438-d36688ca-d748-11e7-8d0e-b90c1e5d5d56.png)

- From nerd-fonts:
![roboto-nerd-font-termux](https://user-images.githubusercontent.com/13117753/33507440-d3e14b28-d748-11e7-9313-1d7d5093cbe5.png)

**Comment by fornwall** [comment]
Sorry, a confusion from my part - forget it!

**Comment by ryanoasis** [comment]
@fornwall I haven't had a chance to look at this yet but thanks for reporting a possible issue :+1:

**Comment by joemaller** [comment]
This is still an issue, RobotoMono NF is about 15% wider than the Google Fonts download. It's too gappy to use comfortably in an editor.

![roboto-win](https://user-images.githubusercontent.com/8320/63231548-35775880-c1eb-11e9-825b-47f65a8ca2d4.png)

![roboto-mac](https://user-images.githubusercontent.com/8320/63231550-390adf80-c1eb-11e9-8d6e-76710e90c885.png)

**Comment by ryanoasis** [comment]
@joemaller Thanks for this! It's really helpful.

I am not sure exactly what is going on but I do see a difference between these 2:
* [Roboto Mono Nerd Font Complete.ttf](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/RobotoMono/Regular/complete/Roboto%20Mono%20Nerd%20Font%20Complete.ttf)
* [Roboto Mono Nerd Font Complete Mono.ttf](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/RobotoMono/Regular/complete/Roboto%20Mono%20Nerd%20Font%20Complete%20Mono.ttf)

The first *does* seem to match up with Google's version but the second does *not*. It would seem to make sense that the one you reference is the Nerd Font one ending in 'Mono' which has the issue.. :thinking:

**Comment by joemaller** [comment]
Sorry, I should have clarified. The single-line image is *Roboto Mono Nerd Font Complete Mono Windows Compatible.ttf* on Windows. The stacked alphabet is *Roboto Mono Nerd Font Complete Mono.ttf* on macOS. Both compared to the standard *RobotoMono-Regular.ttf* font downloaded from Google Fonts. 

Thanks for all of this!

**Comment by ryanoasis** [comment]
@joemaller Ah okay, thanks for clarifying. No apologies necessary :smiley:

**Comment by Finii** [comment]
Fixed by
* #1062
