### ISSUE TITLE
Powerline glyphs

### ISSUE THREAD

**Issue by karambaq** [ryanoasis/nerd-fonts#224]
#### 🎯 Subject of the issue

Patched font powerline symbols not aligned right. I mean, two or three pixels.

#### 🔧 Your Setup

- _Iosevka Patched font with -c -s -l flags_
- _iterm2_
- _OS X High Sierra_

<img width="782" alt="2017-12-18 19 06 27" src="https://user-images.githubusercontent.com/14233969/34115432-aee8fd62-e426-11e7-9fd7-4cb6c337a76b.png">

Top border:
![2017-12-18 19 11 31](https://user-images.githubusercontent.com/14233969/34115647-4f4fa76a-e427-11e7-9581-a1724987ea26.jpg)

Bottom border:
<img width="200" alt="2017-12-18 19 12 29" src="https://user-images.githubusercontent.com/14233969/34115706-6c456152-e427-11e7-8769-221b1323e87f.png">

**Comment by yacoob** [comment]
Looks very similar for me with Fantasque in iTerm2 (3.1.5). Depending on the font size, the separator is sticking out ever so slightly to the top or to the bottom:

Fantasque at 14pt, sticking out to the top
![screen shot 2017-12-22 at 01 11 07](https://user-images.githubusercontent.com/190463/34281360-236f2684-e6b6-11e7-8216-ff6a274f7361.PNG)

Fantasque at 18pt, sticking out to the bottom
![screen shot 2017-12-22 at 01 20 00](https://user-images.githubusercontent.com/190463/34281389-4764742c-e6b6-11e7-8c8a-487ff7b8ce6f.PNG)

FWIW, turning anti-aliasing off in iTerm2, results in the symbol being more or less in the middle at 14pt, and deformed significantly at 18pt:
![screen shot 2017-12-22 at 01 21 29](https://user-images.githubusercontent.com/190463/34281439-9cf888c4-e6b6-11e7-8fa3-c08bb0163d85.PNG)
![screen shot 2017-12-22 at 01 22 10](https://user-images.githubusercontent.com/190463/34281441-a054d93c-e6b6-11e7-9147-ae9c54859f69.PNG)

**Comment by ryanoasis** [comment]
We'll take a look at this. Thanks for the report and the screenshots both of you. 👍 

Glyphs can be notoriously finicky to align for prompt purposes.

**Comment by Finii** [comment]
I guess this is fixed by either of
* #1060
* 95bdc420dad
