### ISSUE TITLE
Request: Weather Icons

### ISSUE THREAD

**Issue by chrissnell** [ryanoasis/nerd-fonts#226]
#### 🎯 Subject of the issue

Request:  Please add Erik Flowers' "[Weather Icons](https://github.com/erikflowers/weather-icons) to your fonts.  :)

#### 🔧 Your Setup

- I'm using SauceCodePro Mono
- I use xfce4-terminal
- I'm using Arch Linux

**Comment by ryanoasis** [comment]
Cool thanks for the suggestion 😄 . Wow 222 is a lot

**Comment by chrissnell** [comment]
Yes!!!!!!!!!!!!  Thank you!
