### ISSUE TITLE
Add Elixir glyphs

### ISSUE THREAD

**Issue by dkarter** [ryanoasis/nerd-fonts#228]
#### 🎯 Subject of the issue

Can you please add glyphs for the elixir language? this includes files with the `ex`, `exs`, `eex` extensions. (that's all I can think of so far)

#### 🔧 Your Setup

- FuraCode Nerd Font
- iTerm
- OS X 10.13.2

#### ★ Optional

Currently in Vim:

<img width="345" alt="image" src="https://user-images.githubusercontent.com/551858/34464522-17277716-ee48-11e7-8482-f0181a2b412c.png">

In Atom:

<img width="271" alt="image" src="https://user-images.githubusercontent.com/551858/34464528-8574383a-ee48-11e7-8ee6-f038a96cb664.png">

Thank you for a great project!

**Comment by ryanoasis** [comment]
@dkarter Cool and great suggestion! :+1: 

> Thank you for a great project!

Thanks! :smile:

**Comment by dkarter** [comment]
@alexparker I took a look at the SVG in that commit you mentioned and it actually seems very simple, so I wonder if that result is coming from somewhere else, not sure where.

Here is the SVG when opened in Sketch:
![svg composition](https://i.imgur.com/oJSB7Fp.gif)

I tried finding the Elixir glyph locally in my FuraCode Nerd Font and after browsing for quite a while I couldn't find it. 

Locally I use something else at the moment:

```vim
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['ex'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['exs'] = ''
```

Which looks like this:

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/551858/45903544-afbb1500-bdaf-11e8-9b91-8b7d28810945.png">

If you can paste which character you used to get to that glyph I might be able to dig a little deeper.

**Comment by alexparker** [comment]
That's interesting @dkarter. When I paste your unicodes into my vim, the same ones i see in your show up:
![screen](https://d.pr/i/zY27hy+)

But this is what i see in my nerdtree:
![screen](https://d.pr/i/E3TJas+)
here's the code:
```
    mix.exs
    repo.ex
```
