### ISSUE TITLE
Hasklug ExtraLight & Light are not working

### ISSUE THREAD

**Issue by atomi** [ryanoasis/nerd-fonts#231]
#### 🎯 Subject of the issue

Hasklig Light and ExtraLight work fine on VSCode but Hasklug Nerd Font,ExtraLight and Hasklug Nerd Font,Light do not (possibly others as well) However,  the Font Viewer on Linux does display them correctly. 

#### 🔧 Your Setup

Hasklug ExtraLight Nerd Font Complete.otf On Linux

**Comment by ryanoasis** [comment]
Oh no, thanks for the report! :+1:

**Comment by ryanoasis** [comment]
Hey @atomi, just tried `Hasklug ExtraLight Nerd Font Complete.otf` and it looks to be working fine for me:

![selection_008](https://user-images.githubusercontent.com/8083459/35787624-8fc35174-09fd-11e8-9af5-8585e190ba99.png)

**Comment by atomi** [comment]
I no longer can find the Hasklug Complete.otf files I thought they were at https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hasklig

**Comment by atomi** [comment]
@ryanoasis Your image shows 'Hasklug Nerd Font' and that works for me as well, but 'Hasklug Nerd Font ExtraLight' does not.

**Comment by ryanoasis** [comment]
@atomi Hmm that's because the font names actually the same (not taking into account the weight).

You should be able to do something like this:
```
"editor.fontWeight": "100"
```

**Comment by atomi** [comment]
Yeah I figured that out. But the original Hasklig font is able to use the Extra Light font style by using the font name. I wasn't sure if that was expected behavior for your Hasklug font.

**Comment by ryanoasis** [comment]
@atomi Ah okay now I gotcha, yeah you are correct it is not behaving as one would expect.

So there is an issue here.. the ttf family name isn't being updated 😟 

It is actually using the canonical font name, so as long as you don't have Hasklig installed this should actually use the Nerd Fonts patched version from what I can see:
```
"editor.fontFamily": "'Hasklig ExtraLight'"
```

See below the issue:

![selection_009](https://user-images.githubusercontent.com/8083459/36005962-4e39bd02-0d08-11e8-8258-fee1a8a248e4.png)

**Comment by atomi** [comment]
Ah I see. Glad we figured it out.  :smiley: 

Thank you for the work around.

**Comment by ryanoasis** [comment]
Might have a fix for this. @atomi mind trying out a patched font if I upload it?

**Comment by atomi** [comment]
Yeah of course. but I'm out tonight. I'll have to test tomorrow.

**Comment by ryanoasis** [comment]
@atomi Appreciate it, don't feel obligated, no worries whenever you are able :smile: 

It is here for you when you can/want to test it out:

[Hasklug Nerd Font Complete (Correct String ID).ttf.zip](https://github.com/ryanoasis/nerd-fonts/files/1754557/Hasklug.Nerd.Font.Complete.Correct.String.ID.ttf.zip)

**Comment by atomi** [comment]
Yeah it is working with `'Hasklug Nerd Font'` in VSCode... Looking forward to the update.

Thanks again.

**Comment by ryanoasis** [comment]
@atomi Great! Thanks for checking
