### ISSUE TITLE
Document ttf-ancient-fonts

### ISSUE THREAD

**Issue by jamrizzi** [ryanoasis/nerd-fonts#232]
For some reason, on Ubuntu I had to install ttf-ancient-fonts to get this to work.

```
sudo apt-get install ttf-ancient-fonts
```

Shouldn't this be documented?

**Comment by ryanoasis** [comment]
Hmm that is strange. Should not be required at all.

What was the issue you were having? Glyphs not showing?

**Comment by jamrizzi** [comment]
Correct

**Comment by ryanoasis** [comment]
Which glyphs were you not seeing? The powerline characters (e.g. `e0b0`) ?

![selection_007](https://user-images.githubusercontent.com/8083459/35484094-e4d9ede8-0418-11e8-8fe7-5e0f5d16e4d0.png)

I don't think it makes sense to me why install these fonts would have any effect on completely different glyphs. Perhaps the font cache got cleared while or after installing the fonts?

**Comment by jamrizzi** [comment]
How to you clear the font cache, I ran `fc-cache` several times and it didn't help. The glyphs that weren't working were more specific ones, like the devicons.

**Comment by jamrizzi** [comment]
The operating system I'm using a minimal Ubuntu server, maybe installing `ttf-ancient-fonts` installed some other dependencies I needed to display the fonts.

**Comment by ryanoasis** [comment]
@jamrizzi That is odd to me that the package would be needed simply to use fonts with private use glyphs but obviously it seems to have solved something for you so there is probably something going on.

Perhaps it was some other dependency but I wouldn't know which it was.

This would take some exploring or attempt to replicate.

How did you setup your Ubuntu server? Any specific iso you started from? https://www.ubuntu.com/download/server ?

**Comment by jamrizzi** [comment]
I'm sorry, I've determined this was an unrelated issue. Sorry for the confusion.

**Comment by ryanoasis** [comment]
@jamrizzi Good to hear. Thanks!
