### ISSUE TITLE
New font to include: Mfizz

### ISSUE THREAD

**Issue by nogweii** [ryanoasis/nerd-fonts#233]
#### 🎯 Subject: [font-mfizz](https://github.com/fizzed/font-mfizz)

[Font Mfizz](http://fizzed.com/oss/font-mfizz) seems to have some higher quality vectors for particular icons, and covers some other ones not yet covered by the current set.

**Comment by ryanoasis** [comment]
@evaryont Thanks for the suggestion. At first I thought this was a font but it's actually a font glyph set.

Quite a few of these we already have but definitely some unique ones here! Given that Nerd Fonts currently does not care about duplicate glyphs (it just aggregates the sets) I don't think that would prevent us from adding the whole set.

**Comment by ryanoasis** [comment]
Yeah we can use the ttf font. This should be fairly straight forward to include. The thing that will take time is repatching all of the fonts 😉 

Looks like the mfizz are mapped to `f100` through `f188`. However that range conflicts with some other Nerd Font glyph set so we just have to offset the range. 😄

**Comment by hpfr** [comment]
[As with](https://github.com/ryanoasis/nerd-fonts/issues/615#issuecomment-980969419) #615 (thanks for the link):
> The [file-icons](https://github.com/file-icons/atom) project might be an even better replacement. It looks to have unified styling and optimized SVG's across the old [devicons](https://github.com/file-icons/DevOpicons), ***[MFizz](https://github.com/file-icons/MFixx) icons***, and many new [file-icons](https://github.com/file-icons/icons) icons.
>
> These can also replace most of the existing nf-custom icons, except the folder ones, I guess.

As an aside, the file-icons sets would probably make Symbols Nerd Font able to fully replace [the fonts used in the most popular Emacs icon package](https://github.com/domtronn/all-the-icons.el#resource-fonts), which would be a big help:
> The fonts provided with this packages are locked down to a version for unicode character mapping values. In the future, these may be automatically generated.

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
