### ISSUE TITLE
Add patched sourcecodepro italics

### ISSUE THREAD

**Issue by petobens** [ryanoasis/nerd-fonts#236]
The provided [SauceCodePro font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/SourceCodePro) doesn't have a patched italics version of the official [SourceCodePro Font](https://github.com/adobe-fonts/source-code-pro). Is it possible to add a patched version of this style to the repo? Thanks in advance!

**Comment by ryanoasis** [comment]
@petobens Thanks for bring this to our attention :+1: 

Going to try to get this into the next version.. possibly :smile:

**Comment by petobens** [comment]
Awesome! Thank you :)

**Comment by petobens** [comment]
Hi @ryanoasis, terribly sorry to bother you again but I might tested this wrongly. Are the italics fonts actually added? This folder seems empty: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/SourceCodePro/Italic 

I tried selecting `Italic` style in my terminal (Alacritty) configuration and the that particular style doesn't seem to be available.
Thanks in advance!

**Comment by petobens** [comment]
Ping @ryanoasis
