### ISSUE TITLE
Glyphs not showing on Hack font

### ISSUE THREAD

**Issue by varunagrawal** [ryanoasis/nerd-fonts#238]
#### 🎯 Subject of the issue

When using the Hack font on terminator, the nerd-font glyphs don't render correctly.

See the image below:
![glitch1](https://user-images.githubusercontent.com/975964/36510918-bca3e8b0-1732-11e8-80e9-43d211c553d6.png)

This might be a regression due to a recent update (#216). The Knack font works fine.

#### 🔧 Your Setup

- Hack font
- Terminal: Terminator
- Ubuntu 16.04

**Comment by ryanoasis** [comment]
Thanks for reporting :+1: , will check it out when I get time

**Comment by varunagrawal** [comment]
If it helps, the glyphs show up correctly on almost every other font I have tried.

**Comment by ryanoasis** [comment]
@varunagrawal Yes that might be helpful info. Thanks!

**Comment by Finii** [comment]
I guess this has been fixed at least by #1060, although Hack is not one of the most problematic fonts.
Please reopen if still problematic.
