### ISSUE TITLE
some of the symbols not showing correctly under windows

### ISSUE THREAD

**Issue by kaijajan** [ryanoasis/nerd-fonts#239]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue
Some of the symbols not showing correctly under windows 10 and putty

I really like the work you provided to make terminals look way better. Thanks so much.

Here's issue I encoutered, I tried to installed patched-font from the git repo (up-to-date)
And only very few fonts could display symbols correctly.
I believe Meslo series work just fine.
Please check the two images below, left window present putty using meslo font, while right window present putty using BitstreamVeraSansMono fonts
Most of the fonts work like BitstreamVeraSansMono display a blank square for some symbols.

Anyone has idea how to make the fonts work like Meslo series showing correct symbols?

#### 🔧 Your Setup
- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
Meslo (All windows compatiable ttfs)
BitstreamVeraSansMono ((All windows compatiable ttfs)

- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
putty (self built putty from putty git repo which with true color supported)
putty ssh to remote ubuntu with zsh + oh-my-zsh installed + pure prompt installed (https://github.com/sindresorhus/pure)
neovim with nerdtree + devicons installed

- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Windows 10

#### ★ Optional

https://imgur.com/a/sUZkX
https://imgur.com/a/oR23A

**Comment by ryanoasis** [comment]
@kaijajan Thanks for the report!

> I really like the work you provided to make terminals look way better. Thanks so much.

Appreciate that, thank you.

---

Hmm those glyphs are actually not patched with Nerd Fonts, those depend on the individual fonts.. of course we could always add the equivalent if they are in fact missing...

For example:

![selection_013](https://user-images.githubusercontent.com/8083459/36929688-96272e04-1e62-11e8-94e7-d21033542184.png)

**Comment by kaijajan** [comment]
@ryanoasis

Thank you for the reply.
I thought those symbols were a part of this nerd fonts, my mistake.
I also installed nerd fonts on my macOS which works insanely good.

I checked the original ttf files, and only very few did contain those symbols, but how come the other fonts patched work fine under macOS, even w/o those symbols.

Really thank for your support.

**Comment by LuRsT** [comment]
I guess we can close this one @ryanoasis

**Comment by anselal** [comment]
I have the same issue on windows with MobaXterm which is based on putty. Most fonts are not shown up ion the available list inside MobaXerm or putty.

**Comment by HappyCerberus** [comment]
I also have the same problem. Is there any resolution?

**Comment by ryanoasis** [comment]
Here I am digging into old issues (sorry!)

@anselal sorry for the late ping, that looks really weird? did you ever find a solution?

@HappyCerberus could you provide a screenshot of what you're seeing and which font you're using exactly? Thanks.

**Comment by anselal** [comment]
The issue I had was with this command https://github.com/athityakumar/colorls

So, I stopped using it..

**Comment by bitroniq** [comment]
I have the same issue with PuTTY on Windows10. 
* FuraCode
* PuTTY
* devicons on vim

Missing icons of triangles in NERDtree representing folders

**Comment by maxsatula** [comment]
JFYI I have contacted PuTTY developer and he confirmed the issue with a small slice of the private use area in Unicode, U+F000 to
U+F1FF. Try PuTTY snapshot from 2021-02-15 or later and see if icons are displayed properly now. (Thanks to Simon, PuTTY author)

**Comment by jbertozzi** [comment]
Thanks @maxsatula seems to work better now. Seems there are still icon truncated with some fonts, but I managed to find one (Hack NF only visible following instruction [here](https://github.com/ryanoasis/nerd-fonts/issues/269#issuecomment-447621210)).

**Comment by Finii** [comment]
@jbertozzi If you encounter truncated icons you should probably use the `Nerd Font Mono` variant.

Multiple issues with "font-selectability" in Windows has been tackled in the meantime.

Thanks for all the input. Closing.
