### ISSUE TITLE
Font Awesome fonts are way too big

### ISSUE THREAD

**Issue by adambiggs** [ryanoasis/nerd-fonts#24]
After updating and trying to use some of the new Font Awesome glyphs, I noticed that in many of the patched fonts these glyphs display around twice as big as they should. Seems to only affect Font Awesome glyphs.

Interestingly, with a few of the patched fonts they show up normal size, but some of the other glyphs (like the `>` `<` symbols used by PowerLine) show up half-size.

**Comment by ryanoasis** [comment]
@adambiggs thanks. I did notice this myself but decided to push it up regardless :blush: On the bright side good to know there is interest :smile: 

I _think_ most of the problems are related to the original glyph font's **em** size. In particular I noticed **Font Awesome** source font I used had an odd em size of **1792**

**Comment by adambiggs** [comment]
Ya I was actually really happy to see the inclusion of FA. I want to use the WiFi and some other glyphs for my Tmux status bar :neckbeard:

**Comment by ryanoasis** [comment]
Hey my suspicion was correct so this _should_ be an easy fix but I still have to regenerate all the fonts :laughing: 

I also need to get caught up on the versioning and changelog (I like to stay organized)
