### ISSUE TITLE
Upgrade Fantasque Sans Mono to the latest version (1.7.2)

### ISSUE THREAD

**Issue by CarterLi** [ryanoasis/nerd-fonts#240]
#### 🎯 Subject of the issue

https://github.com/belluzj/fantasque-sans/releases

#### 🔧 Your Setup

N/A

#### ★ Optional

N/A

**Comment by ryanoasis** [comment]
@CarterLi Thanks for the heads up!

I guess we need a system to know when fonts release new versions :blush:

**Comment by CarterLi** [comment]
Thanks for your quick response! @ryanoasis

**Comment by ryanoasis** [comment]
Just happened to be on and actually we are almost at a point where upgrading them is trivial (knock on wood). :smile: 

I will be pushing the re-patched versions now.
