### ISSUE TITLE
Swap Font Awesome with Fork Awesome?

### ISSUE THREAD

**Issue by nogweii** [ryanoasis/nerd-fonts#241]
#### 🎯 Subject of the issue

[Fork Awesome](https://forkawesome.github.io/Fork-Awesome/) is a fork of Font Awesome with extra community icons.

#### ★ Optional

(I mostly want it for the [XMPP icon](https://forkawesome.github.io/Fork-Awesome/icon/xmpp/) but there is [more to it](https://forkawesome.github.io/Fork-Awesome/icons/#new) than just that one glyph.)

**Comment by ryanoasis** [comment]
Ah Font Awesome changes.. yeah ever since I saw version 5 I had some doubts how we will incorporate. 

So this forked from FA 4.7.

Right now they seem to have 32 icons added since 4.7

Ref: https://forkawesome.github.io/Fork-Awesome/whats-new/

Related: #221

**Comment by Finii** [comment]
Closed because moved to #1095

**Comment by Finii** [comment]
Fork awesome declared itself 'deprecated'; instead we updated to FA 6
Moving this off of #1095
