### ISSUE TITLE
Which git command should I use to clone this repos in order to patched my own font?

### ISSUE THREAD

**Issue by chenzhihuai1990** [ryanoasis/nerd-fonts#245]
This repos is too large. I just want to patched one font file, I am sure I need not the whole repos. But I don't which files or folds are necessary for me to patched my own font?
Can you tell me what files/folds or git command should I use?

**Comment by chenzhihuai1990** [comment]
I have found another same issue #73 , so I close it.

**Comment by ryanoasis** [comment]
@chenzhihuai1990 Hey sorry for the confusion on patching your own fonts. The instructions seem to be lacking in that area. I am going to update that at least.

> This repos is too large.

Ideally we would/should convert to an organization and have fonts in one repo and the tools in a separate repo.

> Can you tell me what files/folds or git command should I use?

You will need font-patcher and the src folder.
