### ISSUE TITLE
Meslo fonts ligature is broken

### ISSUE THREAD

**Issue by avoidik** [ryanoasis/nerd-fonts#248]
MesloLGM NF for Windows is broken because of ligature issue

Cross-linking related issues
https://github.com/mintty/mintty/issues/754
https://github.com/ryanoasis/nerd-fonts/issues/186

**Comment by ryanoasis** [comment]
Thanks. I need to look into it more. I'm assuming this is the non mono version? Does it happen with the unpatched version?

**Comment by avoidik** [comment]
Don't know is it patched or not. It is Meslo font-package taken from nerdfonts.com (Meslo.zip), only Windows-compatible fonts.

Target platform is Windows 7 and Windows 10

**Comment by ryanoasis** [comment]
Thanks for the update. Can you try the mono version?

I think the problem might be the source font itself but I'd need to test/replicate

**Comment by nickbudi** [comment]
Both the mono and non mono versions are broken for me.

**Comment by sagikazarmark** [comment]
The same problem occur with Iosevka Nerd Font for me.

**Comment by ohcibi** [comment]
To me it appears as if the FuraCode ligatures are also broken... I'm just trying to patch them myself to see if that fixes it.

**Comment by sideeffffect** [comment]
`FuraCode Nerd Font Mono` for me also doesn't show almost any ligatures
@ohcibi have you reproduced the issue when patching yourself?

**Comment by seefood** [comment]
FuraCode broken ligatures for me too. Original FiraCode has powerline so I'm making do with that for now :-)

**Comment by ohcibi** [comment]
@sideeffffect @seefood FuraCode Nerd Font *Mono* does not have any ligatures. Use the version that isn't called *Mono*.

**Comment by sideeffffect** [comment]
> FuraCode Nerd Font Mono does not have any ligatures

that should be considered a bug!

**Comment by ohcibi** [comment]
@sideeffffect no it should not. Its the point of Nerd Font Mono to exist. It does not mean that Nerd Font Non-Mono ist not a monospaced font. It means that Nerd Font Mono is free of any ambiguous width chars whatsoever. Please read the documentation about Nerd Font and Nerd Font Mono.

**Comment by sideeffffect** [comment]
@ohcibi fair enough

**Comment by seefood** [comment]
As far as I can tell, iTerm2 (macos) thinks it has ligatures (it allows ticking the box to enable them, which doesn't happen in other fonts, and when I do I see broken gliphs. E.g. *** displays as " /*" or something (not at the computer ATM). I'll look into the non mono version as you suggest.

**Comment by ohcibi** [comment]
@seefood this has nothing to do at all with any setting of iterm2 or whatever. NerdFont Mono **does not have ligatures**. Thats about it. You cant see ligatures because the font you are using does not have them. The version without Mono in its name has ligatures and thats about the difference between those two fonts. The Non-Mono is **with** ligatures, the Mono is **without**.

They really should change the name but changing font names is not a simple thing to do as all existing configs will break of course.

**Comment by seefood** [comment]
well, switching to Fura non-mono fixed it, but the Mono version still has a metadata field identifying it as having ligatures, I'm guessing this is an upstream issue, ignoring.

**Comment by sideeffffect** [comment]
> the Mono version still has a metadata field identifying it as having ligatures, I'm guessing this is an upstream issue

that shouldn't be an upstream issue -- Fira Code *does* have ligatures, no? So than if *Fura Code Mono* (in contrast to *Fura Code*) has metadata declaring ligatures, that looks like a `nerd-fonts` issue, right?

**Comment by ohcibi** [comment]
@Sideeffect yes exactly. Fira Code doesnt have this Limitation/distinction. Hence people are confused because the expectation is that both variants simply have ligatures and therefore issues about those are not even expected from people switching from fira to fura.

**Comment by segevfiner** [comment]
Here's another case of messed up ligatures https://github.com/microsoft/vscode/issues/84418

**Comment by segevfiner** [comment]
The newer version of the font in the repository that was patched from newer Meslo LG for Powerline doesn't have the issue. The newer Meslo LG for Powerline has the ligatures patched out to workaround this since they caused issues in other places as well.

**Comment by Finii** [comment]
There have been several ligature related fixes
* #977 
* #711 
* #1089

So I assume this is fixed ;-) Reopen if you have issues with the current release.
