### ISSUE TITLE
[osx] Font Book complains about duplicate fonts

### ISSUE THREAD

**Issue by adambiggs** [ryanoasis/nerd-fonts#25]
This isn't a huge problem, but might be easy to fix.

After installing all the patched fonts under OSX, many of them show up as duplicate fonts in the Font Book app.

Not sure if this is the exact cause, but I noticed when inspecting these fonts that the "Unique name" value is unchanged between variations of the same font.

**Comment by adambiggs** [comment]
Actually, it seems like this might be a bigger issue than I first thought...

In iTerm, switching between font variants of the same family seems to have unexpected results. Many of the variants are displayed exactly the same.

E.g. `Sauce Code Pro Black` looks identical to `Sauce Code Pro ExtraLight`.

**Comment by ryanoasis** [comment]
@adambiggs I thought I replied already (I guess not! sorry). Anyway thank you and I will try to see if I can figure something out
