### ISSUE TITLE
404 on screenshots page

### ISSUE THREAD

**Issue by 1ak31sha** [ryanoasis/nerd-fonts#252]
#### 🗹 Requirements

- [ ] A brief but descriptive _title_ of your issue
- [ ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [ ] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ ] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_

**Comment by ryanoasis** [comment]
@1ak31sha Thanks for the report! Good catch :+1: 

Created it here: https://github.com/ryanoasis/nerd-fonts/wiki/Screenshots
