### ISSUE TITLE
fl/fi Ligatures always appearing in patched Monaco font

### ISSUE THREAD

**Issue by timoxley** [ryanoasis/nerd-fonts#254]
I've even tried editing the patch script to remove *all* lookup tables, yet the damn ligatures continue to persist. 

i.e.

```
  for table in sourceFont.gsub_lookups:
      symfont.removeLookup(table)
```

Any ideas on what's going on? I'm guessing there's some default ligature setting being inherited? Is there a way to turn that off in the generated font?

Turning off `set macligatures` in vim is my temporary workaround.

**Comment by ryanoasis** [comment]
@timoxley Hey sorry not that I know of.

The ligatures are present in the source font pre-patching right?

What is the name of the tables that get removed in the iteration?

By the way the font-patcher is setup with the ability to remove subtables (but not tables) via `--removeligatures` in conjunction with `--configfile [json like config file]`

config example: https://github.com/ryanoasis/nerd-fonts/blob/master/src/unpatched-fonts/Meslo/config.json

**Comment by ryanoasis** [comment]
@timoxley Thanks for the details :+1: , that is strange. I would like to take a look but I cannot tell you when that'll be :sweat:

**Comment by timoxley** [comment]
@ryanoasis 

No action required on your part, was hoping it would be something you knew off the top of your head.

Oh, also note that when I first patched the font using --complete, the `fi` and `fl` ligatures were remapped – one became an icon for a telephone. This was an entertaining surprise when I discovered it in my editor.

## Source Font Monaco

![image](https://user-images.githubusercontent.com/43438/38241973-2aafe9f0-3766-11e8-8bea-9b3d35132487.png)

## After `font-patcher --mono --powerline --fontawesome --powerlineextra`

![image](https://user-images.githubusercontent.com/43438/38241990-388ec438-3766-11e8-9d02-7dae4ecbd091.png)

## After `font-patcher --mono --complete`

![image](https://user-images.githubusercontent.com/43438/38242003-3f733fc2-3766-11e8-8a1b-e5d2e90fe95e.png)

🥇

**Comment by sirplatypos** [comment]
I have been having the problem with the phone symbol and such as well using the AUR nerd-fonts-complete package.  Is there a way to get around this problem without patching all of the fonts by hand?

**Comment by timoxley** [comment]
@sirplatypos I just live with the phones

**Comment by sirplatypos** [comment]
I fixed the problem for myself by removing the subtable that replace the characters with the ligatures.  It had been set to replace the normal ff and such with the phone, the priority low symbol, etc.  If you're still having the problem, get font forge and remove the ligature subtable.

**Comment by sirplatypos** [comment]
[ubuntu-regular.zip](https://github.com/ryanoasis/nerd-fonts/files/2216439/ubuntu-regular.zip)
This is ubuntu nerd font regular with the table removed, in case anybody wants it.  I don't know how many other fonts have this issue.

**Comment by ykyuen** [comment]
+1 hving the same problem with Ubuntu font

**Comment by luispuerto** [comment]
I'm having the same problem with monaco font... and as @sirplatypos did I just remove the ligatures with fontforge and that is. I don't know if I've broken anything in the process but I hope I didn't. 
No more phones ☎️ .

**Comment by anelson** [comment]
I'm having this problem also using the latest version of the Arch linux AUR package `nerd-fonts-complete`.  In my case I'm using the "NotoSerif NerdFont".  Here's an example:

![image](https://user-images.githubusercontent.com/29393/54926564-3d232180-4f19-11e9-89c8-c2df433d14f3.png)

It's sufficiently annoying that I'm about to revert back to the regular Noto font family and use the NerdFont version only in the terminal.  Before I do that does anyone have a workaround (or better yet, a fix), other than manually editing the font in FontForge?

**Comment by stellarhoof** [comment]
The Ubuntu Condensed font also has this problem.

**Comment by ryanoasis** [comment]
Sorry for the late reply, yeah I think the real solution will involve not clobbering the ligatures but that will involve moving some of the codepoints of some glyphs. That would probably result in a `3.0` release (breaking change).

There is another workaround worth mentioning (if one patches themselves). that is using the `--careful` flag. That will ensure existing glyphs don't get clobbered, for example:

left: original font
center: straight up patch
right: patch with the `--careful` flag
![VictorMono-Regular-patching-comparisons](https://user-images.githubusercontent.com/8083459/62340492-9c2f0f00-b494-11e9-9360-2ac02fd43280.png)


Ref: https://github.com/ryanoasis/nerd-fonts/issues/57#issuecomment-515654441

**Comment by adk2266** [comment]
In the mean time, is there any chance of getting sirplatypos's fixed version on the readme list or releases page for easy discoverability, or do we not want that as an official version since it's missing some glyphs?

**Comment by jrwrigh** [comment]
@ryanoasis's solution isn't entirely complete (though this might be related to terminal). Using "Share Tech Mono", the ligature overlaps with the next character:

![image](https://user-images.githubusercontent.com/20801821/68334640-4cb23d80-0098-11ea-81c7-8a7be17d9667.png)
^^ This `flaflofle`

Note this is on Konsole 2.14.2, which is fairly old.

**Comment by revarcline** [comment]
Also having this problem with the downloaded version of Inconsolata Nerd Fonts Mono

**Comment by PonasKovas** [comment]
has there been any progress? I don't know much about fonts so I don't really know how to fix it for myself and the telephones are very annoying...

**Comment by timoxley** [comment]
@PonasKovas eventually you'll learn to love the telephones and it will look wrong to not have them. In these trying times, it's imperative to be able to ☎nd ways to accept things for what they are and move on, always better and stronger.

**Comment by jrwrigh** [comment]
@PonasKovas It's a fairly easy manual fix that I briefly mentioned in [my second edit here](https://github.com/ryanoasis/nerd-fonts/issues/254#issuecomment-550486987). You essentially:

1. Open the font in font forge
2. Find the offending characters (`fb01` and `fb02`) 
3. Delete the offending characters
4. Save the font

I had no experience in working with fonts before I did this and it didn't take too long.

**Comment by fabricio7p** [comment]
Same issue with Inconsolata Nerd Font from the AUR package

**Comment by fabricio7p** [comment]
> @PonasKovas It's a fairly easy manual fix that I briefly mentioned in [my second edit here](https://github.com/ryanoasis/nerd-fonts/issues/254#issuecomment-550486987). You essentially:
> 
> 1. Open the font in font forge
> 2. Find the offending characters (`fb01` and `fb02`) 
> 3. Delete the offending characters
> 4. Save the font
> 
> I had no experience in working with fonts before I did this and it didn't take too long.

im trying to do that but the font breaks when exporting.. how do i save it properly?

**Comment by 0xRainy** [comment]
> im trying to do that but the font breaks when exporting.. how do i save it properly?

Just went through this process.. Find the ligatures and clear the ones you don't want then File>Generate fonts>Choose the font type (ttf or CFF (which is OTF)) and leave all the options alone.

Don't know if it matters but they suggest running it as administrator

**Comment by pinpox** [comment]
Ring, ring... Also happening with `Overpass`.. any progress on this besides patching it myself?

**Comment by ibraheemdev** [comment]
Is there a fork with the fixed fonts for someone who doesn't want to patch manually?

**Comment by stelcodes** [comment]
Having the same phone problem on NixOS. I personally do not like the phones. `fi`

**Comment by pinpox** [comment]
I just ended up using the non-patched font as main font and defining the patched one as fallback in my terminal emulator. But I have since moved to a different font as I was starting to get bad dreams about ringing phones...

**Comment by zaibatsu-loli** [comment]
fi fi fi fi fi fi fi fi fi fi fi fi AAAAAAAAAAAAAAAAA MAKE THEM GO AWAY fi fi fi fi fi fi fi

**Comment by jef** [comment]
> I just ended up using the non-patched font as main font and defining the patched one as fallback in my terminal emulator

That's a great idea! Didn't think about that one...

**Comment by arminbw** [comment]
I had several different font versions floating around and [solved the problem by flushing the font caches and reinstalling the latest version](https://github.com/ryanoasis/nerd-fonts/issues/509#issuecomment-990129814).

**Comment by ryanoasis** [comment]
It's been a long time but I think I've got a better solution now.

Comment with screenshots here: https://github.com/ryanoasis/nerd-fonts/issues/509#issuecomment-992141907

**Comment by Finii** [comment]
Seems github did not pick up my 'PR will close this isse' tag :roll_eyes:

**Comment by jef** [comment]
> Seems github did not pick up my 'PR will close this isse' tag 🙄

I think if you use it without a colon and you can only use one issue ref per line:

```
Fixes #509
Closes #254
```

Something like that 😄

**Comment by mundodisco8** [comment]
Just commenting because I have the issue and wanted @pinpox to have a laugh.

**Comment by mundodisco8** [comment]
I downloaded the one from master (or maybe a branch called something like
Inconsolata-fix?) but yeah I have it working for now, and waiting for the
fix to be merged in a new release.

**Comment by joachimnielandt** [comment]
Just installed `nerd-fonts-complete` to see and figured I'd check if the phone was still present, which is was. The following fonts are afflicted (looked for the phone substitution using font-manager).

## Afflicted fonts
- Inconsolata Nerd Font
- Inconsolata Nerd Font Mono
- mplus Nerd Font
- mplus Nerd Font Mono
- NotoSansDisplay Nerd Font
- NotoSansDisplay Nerd Font Mono
- NotoSansMono Nerd Font
- NotoSansMono Nerd Font Mono
- NotoSerifDisplay Nerd Font
- NotoSerifDisplay Nerd Font Mono
- NotoSerif Nerd Font
- NotoSerif Nerd Font Mono
- OpenDyslexicAlta Nerd Font
- OpenDyslexicAlta Nerd Font Mono
- OpenDyslexic Nerd Font
- OpenDyslexic Nerd Font Mono
- Overpass Nerd Font 
- Overpass Nerd Font Mono
- ShureTechMono Nerd Font 
- ShureTechMono Nerd Font Mono
- SpaceMono Nerd Font 
	- note: Mono variant does not contain the error
- UbuntuCondensed Nerd Font 
- UbuntuCondensed Nerd Font Mono
- Ubuntu Nerd Font 
- Ubuntu Nerd Font Mono

**Comment by Finii** [comment]
The AUR is if course not up to date :-D, complain at the repo manager that it relies on releases and not HEAD ;-)

**Comment by joachimnielandt** [comment]
> The AUR is if course not up to date :-D, complain at the repo manager that it relies on releases and not HEAD ;-)

Ah yes, didn't notice that... I guess waiting for a new release isn't the end of the world :). Thx for the info!

**Comment by pinpox** [comment]
> complain at the repo manager that it relies on

Hm, maybe give him a call?

**Comment by joachimnielandt** [comment]
It makes sense for the AUR to fetch a release though? This project produces releases for a reason, I assume?

**Comment by Finii** [comment]
No yes. Please note the emoticons, that was a not serious comment.

I hope the 2.2.0 RC turns into a release soon...
But then, there are still some PR that I would love to see in 2.2 and not only in 3.0 :roll_eyes: 

I kind of do not get it... if you use Arch, why not selfpatch ;-D
If it would be Ubunterians... I could unterstand their dependence on release packages.
But then I saw how integrated Nerd Fonts is in the Arch dependencies, and I went like ... WAT?

**Comment by Finii** [comment]
This `fl` ligature transmogrifies into a telephone should have been fixed by
* #711 

All the AUR packages are also updated to `v2.3.3`, well, they are not in AUR anymore but in Community.
https://archlinux.org/packages/?sort=&repo=Community&q=-nerd
