### ISSUE TITLE
Typo at all Source Code* fonts

### ISSUE THREAD

**Issue by ccztux** [ryanoasis/nerd-fonts#255]
All Source Code Pro* files have a typo in release v2.0.0. They are now called: S**au**ce Code Pro*

**Comment by ryanoasis** [comment]
@ccztux Thanks I appreciate that you noticed this _however_ it is not a typo but is done on purpose :wink: .

Several of the fonts that are licensed under SIL OFL have a Reserved Font Name that we cannot use without breaching the license, these are to prevent that: https://github.com/ryanoasis/nerd-fonts/blob/2.0.0/font-patcher#L238-L252

see also: https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting#why-do-some-of-the-fonts-names-appear-incorrect-or-appear-to-have-typos
