### ISSUE TITLE
Menlo font patching issue with regular variant

### ISSUE THREAD

**Issue by devster31** [ryanoasis/nerd-fonts#256]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

I'm trying to patch Menlo on macOS, these are the commands I'm running on `fish` shell:
```
set -l fonts "Menlo Regular" "Menlo Bold" "Menlo Bold Italic" "Menlo Italic"
for f in $fonts
    fontforge -script font-patcher -c --mono -out . /System/Library/Fonts/Menlo.ttc($f)
end
```
and the patching seems to work fine, albeit with some messages related to the remapping of icons. When going in iTerm2 to set the new font something strange happens: with the Bold version everything seems fine but with the regular one, symbols seem inverted. The only variant that seems to be working is Bold itself, while Italic, Bold Italic and Regular all exhibit the same behavior depicted below.

#### 🔧 Your Setup

- _Which font are you using?_ Menlo (all variants)
- _Which terminal emulator are you using?_ `iTerm2`
- _Which shell are you using?_ `fish`
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ MacOS Sierra

#### ★ Optional

**Regular**
![Regular](https://i.imgur.com/LOMc5B3.png)
**Bold**
![Bold](https://i.imgur.com/FBMDfM7.png)

**Comment by ryanoasis** [comment]
@devster31 Thanks for the report! So strange. Saw your message on gitter.

**Comment by Finii** [comment]
`.ttc` are now supported directly via
* #783 

Please re-open if error persists.
