### ISSUE TITLE
BlexMono: All italic variants shown as duplicates (on macOS, at least)

### ISSUE THREAD

**Issue by alexbarton** [ryanoasis/nerd-fonts#257]
#### 🎯 Subject of the issue

macOS states that all italic variants of BlexMono (merged in #253 – tanks a lot!) are duplicates, and regardless of which one you select in the font selector you chose, the "text" variant is shown (besides the bold variant, which you can use, too).

This is not the case with the original IBM Plex font, so I think this is a problem with the patching?

#### 🔧 Your Setup

- Blex Mono Bold Italic Nerd Font Complete.ttf, Blex Mono ExtraLight Italic Nerd Font Complete.ttf, Blex Mono Light Nerd Font Complete.ttf, …
- macOS 10.13.4

#### ★ Optional

![duplicate font](https://user-images.githubusercontent.com/174961/38757961-35c1efa8-3f6f-11e8-9403-d6a43462e7f7.png)

**Comment by ahmedelgabri** [comment]
Same issue with Iosevka

<img width="1465" alt="screen shot 2018-05-10 at 22 56 25" src="https://user-images.githubusercontent.com/63876/39893861-665789f2-54a5-11e8-8963-b64fa7a7b4d1.png">
<img width="1465" alt="screen shot 2018-05-10 at 22 56 27" src="https://user-images.githubusercontent.com/63876/39893862-667736d0-54a5-11e8-90c5-9043a4078eb5.png">

**Comment by alexbarton** [comment]
Could this be related to IBM/plex#161?

**Comment by Slotos** [comment]
This is still an issue. I've managed to fix Hasklig using TTX and editing all postscript names to be shorter.

Generally speaking, `NerdFontMono` eats a lot of space, causes `name` warnings on macOS, and makes it impossible to name variant italic fonts without breaking them. Stripping it out allowed me to get working fonts.

**Comment by MarioRicalde** [comment]
@Slotos thanks for the lead on this. I was having a similar issue with Operator Mono. The issue is that Fontname doesn't fit the "bold" bits, so they are all the same name in temrs of Italics.

![image](https://user-images.githubusercontent.com/125900/87961722-c00bac00-ca7b-11ea-82ee-667c75e22d16.png)

**Comment by duganchen** [comment]
Well, the "SubFamily" of the Thin Italic variant of Plex gets detected as "Italic". This is another case where it's more reliable to just parse it from the filename.
