### ISSUE TITLE
MPlus: need to remove ``ligalookup01`` subtable to patch Material Design Icon

### ISSUE THREAD

**Issue by dkpsk** [ryanoasis/nerd-fonts#261]
# Problem
Some of the original M+ fonts (1p, 2p, 1c, 2c) have GSUB_Lookup named ``ligalookup01``, which ligature``ff``, `fi`, ``fl``, `ffi` and ``ffl`` into ``\ufb00``, ``\ufb01``, ``\ufb02``, ``\ufb03`` and ``\ufb04`` accordingly.  
([M+ 1m, 2m and 1mn do not have ``ligalookup01``](https://gist.github.com/dkpsk/d97a13e14e8de475a1f50551ea0338fe#file-orignalmplus).) 

Since NerdFont 2.0, ``Material Design Icon`` replaces these glyphs ([``\ufb01`` is phone_classic!](https://nerdfonts.com/?set=fb0#cheat-sheet)), these ligatures do not work properly.  

By removing this subtable manually with fontforge, this problem was solved.

# Solution
Add ``config.json`` to remove ``ligalookup01`` subtable.

**Comment by ryanoasis** [comment]
This is fixed with #711 which removes the old subtable entries for every glyph we are patching into the font. Previously we had been using those config files but that will be hard to maintain and the change to the patcher itself is a more fool proof solution.
