### ISSUE TITLE
 Sauce Code Pro is not able to be found by SecureCRT, gvim on Windows7/10

### ISSUE THREAD

**Issue by IsOverThere** [ryanoasis/nerd-fonts#263]
#### 🎯 Subject of the issue
Sauce Code Pro V2.0 is not able to be found by SecureCRT, gvim on Windows7/10.
In SecureCRT: Options->Session Options->Appearance->Fonts, in the font list SauceCodePro NF is not able to be found.
In Gvim: set guifont=SauceCodePro_NF:h11, it presents E596 Invalid font(s):  guifont=SauceCodePro_NF:h11
While
1. In the MS word/outlook, SauceCodePro NF can be found;
2. Inconsolata Nerd Font Complete Mono Windows Compatible.otf has no issues;
3. Ubuntu Mono Nerd Font Complete Windows Compatible.ttf is has the same issue;
4. Sauce Code Pro Nerd Font Complete Mono Windows Compatible.ttf with previous versions is OK;

#### 🔧 Your Setup

- Sauce Code Pro Nerd Font Complete Mono Windows Compatible.ttf V2.0
- SecureCRT, gvim8.0 1-1428
- Windows7, Windows10

**Comment by ryanoasis** [comment]
@IsOverThere Thanks for the report :+1: I don't know when I will look into it though.

**Comment by haasosaurus** [comment]
can you try the fonts in this branch of my fork to see if it fixes your issue?
https://github.com/haasosaurus/nerd-fonts/tree/regen-mono-font-fix

**Comment by IsOverThere** [comment]
Hi @haasosaurus again,
Just let you know, after restart the SW of SecureCRT, the icon is shown correctly, thanks.

**Comment by PlatypusPro** [comment]
Me too...
I can't use `SauceCodePro Nerd Font Mono` in my gVim 8.0 on Windows 10.
But this font can be found and used in other applications.

**Comment by bin** [comment]
Any progress on this issue?  I've had the same issue; `SauceCodePro NF` shows up in MS Word (so installed successfully), but not in gvim when trying to see all available with `:set guifont=*`.  Also doesn't work when manually loaded from vimrc.  I'll try patching my own, but I'm not optimistic.

**Comment by Finii** [comment]
I guess that should be solved with #764 and/or some other fixes later on.
Please reopen if problem is still there with latest release.
