### ISSUE TITLE
RobotoMono glyphs are too wide

### ISSUE THREAD

**Issue by iilonmasc** [ryanoasis/nerd-fonts#264]
This might relate to #15 

When using RobotoMono with blink.sh the glyphs appear to be wrong in size.

I first reported this to the blink team, however it seems to be a font issue (see blinksh/blink#498)

**Comment by yury** [comment]
Just a note:

It is not [recommended](https://github.com/ryanoasis/nerd-fonts#important-notices) to use fonts from master, but I have checked 2.0.0 - same thing.

**Comment by Finii** [comment]
Use the `Nerd Font Mono` variant if you want a strictly monospaced font.
Wide symbols (with right side bearing (overhang)) should work, depending on your terminal.
