### ISSUE TITLE
Overpass Mono Duplication issue between Bold and SemiBold variants

### ISSUE THREAD

**Issue by Thammachart** [ryanoasis/nerd-fonts#265]
#### 🎯 Subject of the issue

macOS's Font Book states that there is duplication in the Overpass Mono Nerd Font between `Bold` and `SemiBold` variants.

This issue exist on **both** Monospaced and Non-Monospaced glyphs versions.

Out of my observation, these two variants share the same PostScript Name on each version
- `OverpassMonoNerdFontComplete-Bold` on Non-Monospaced version
- `OverpassMonoNerdFontCompleteM-Bold` on Monospaced version

This issue does not exist on the [upstream font](https://github.com/RedHatBrand/Overpass) (Overpass Mono)

#### 🔧 Your Setup

- `Overpass Mono Bold Nerd Font Complete.otf`
- `Overpass Mono SemiBold Nerd Font Complete.otf`
- `Overpass Mono Bold Nerd Font Complete Mono.otf`
- `Overpass Mono SemiBold Nerd Font Complete Mono.otf`
- macOS High Sierra 10.13.4

### Non-Monospaced version
![Bold Non-Mono](https://user-images.githubusercontent.com/1731496/39758257-8b439bbe-52f9-11e8-8776-33b94f89adb7.png)
----
![SemiBold Non-Mono](https://user-images.githubusercontent.com/1731496/39758259-8b9bb830-52f9-11e8-9760-1e4946b7c9d1.png)
### Monospaced version
![Bold Mono](https://user-images.githubusercontent.com/1731496/39758698-d91ca51e-52fa-11e8-9cd4-e9851bdd25c9.png)
----
![SemiBold Mono](https://user-images.githubusercontent.com/1731496/39758701-d9c5ffb0-52fa-11e8-8537-b6dce3557bee.png)

**Comment by ryanoasis** [comment]
Thanks (especially for the details) :+1: 

Disclaimer: I cannot give any ETA, but this project will keep moving forward little by little! :smile:

**Comment by MarioRicalde** [comment]
I think this is the issue: https://github.com/ryanoasis/nerd-fonts/issues/257#issuecomment-661153972

**Comment by Finii** [comment]
The family naming is broken, it has been fixed (use `--makegroups` when patching). It the moment only in effect for some selected fonts, but `v3.0.0` will have it for all fonts. Closing this already.

* #717 (has some explanantions)
* #723 actually introduced the changes from 717
