### ISSUE TITLE
recommendation: change nerd-font license to SIL OFL 1.1

### ISSUE THREAD

**Issue by codinguncut** [ryanoasis/nerd-fonts#266]
#### 🎯 Subject of the issue

Currently it appears as if nerd-fonts is licensed under MIT license. This is very likely incompatible with many of the aggregated fonts. Solution: Carefully go through aggregated fonts and in all likelihood relicense nerd-fonts as "SIL OFL 1.1"

#### Details

Can you please make sure to honor the licenses of the aggregated fonts to make this usable in a license-conforming way, if you haven't already done so? I understand that your project is under MIT license, but are you 100% certain that the aggregated fonts are all compatible with that? (SIL open font, apache, etc.)

* FontAwesome svg icons proper are under CC-BY and the webfont is under SIL OFL 1.1
    * In the Font Awesome Free download, the SIL OLF license applies to all icons packaged as web and desktop font files.
    * I'm uncertain if repackaging the webfont would still fall under SIL OFL
    * "Attribution is required by MIT, SIL OFL, and CC BY licenses."
* MaterialDesign repo you linked is also SIL OFL
    * Community Icons - SIL Open Font License 1.1
    * Google Material Design Icons - Apache License 2.0
* Weather Icons are also SIL OFL
* Font Logo - "Unlicense"
* Some fonts may have additional clauses that may not be legally binding, but should be considered when aggregating

Also, it would be a good idea to make sure to reuse packacked upstream webfonts rather than going back to their differently licensed svg representations...

"The Open Font License is a free software license, and as such permits the fonts to be used, modified, and distributed freely (so long as the resulting fonts remain under the Open Font License)"

**Comment by ryanoasis** [comment]
@codinguncut Replied to your Gitter messages. Thanks for creating this issue.

I think this is a very important and we need to make sure we comply! :+1:

**Comment by clairernovotny** [comment]
Gentle bump on this? Is there any chance of getting the licenses reviewed again?

**Comment by ryanoasis** [comment]
Yes. I know it's been a while. I appreciate the bump and the initial break down. I still need to dig in but my initial understanding is that it is incorrect to label the entire project MIT because of the mixed licensing of the font and glyph sources. The patcher and scripts can be MIT and the generated fonts maintain their original license post patching

**Comment by ryanoasis** [comment]
I am not a lawyer but I have done a thorough audit and fixed a few issues. Documented the audit:

# License audit

So far the most restrictive license Nerd Fonts has to adhere to is SIL OFL 1.1

## Licenses found and basic summary of each

* MIT - all good do what you want basically
* CC 4 - share, adapt and change in any format is okay
* SIL OFL 1.1 - free to use, copy, merge, modify, redistribute with conditions: no selling, must contain this original license, must comply to the RFN (Reserved Font Names)
* NonCommercial-NoDerivs 3.0 Unported (CC BY-NC-ND 3.0) - share/copy and redistribute in any format
* Apache 2.0 - Basically permissive like MIT but a few things to note. Must include original copyright, note any significant changes to original code, copy of NOTICE file. Modified code does not need to remain under Apache 2.0.
* Creative Commons Attribution-ShareAlike 4.0 (CC BY-SA 4.0) - free to share and change. Must give proper attribution. Must distribute under same license. The font itself once patched indeed is.
* Bitstream Vera License v1.00 - do what want, no selling, must rename font.
* Do What The Fuck You Want To - the name summarizes the rules.
* Go License - Redistribution and everything is allowed. Only limitation is use of Google Inc. to endorse/promote.
* Vic Fieger License - free to do whatever you want
* Monofur Free License - free do what you want just require license file
* Bitstream License - do what you want, attribution required
* Ubuntu Font License 1.0 - do what you want, attribution and license must be included. There may be some ambiguity on the naming, but I believe we comply with it:
  * > (c) Modified Versions which are not Substantially Changed must be
renamed to both (i) retain the name of the Original Version and (ii) add
additional naming elements to distinguish the Modified Version from the
Original Version. The name of such Modified Versions must be the name of
the Original Version, with "derivative X" where X represents the name of
the new work, appended to that name.

## Original source works under Nerd Fonts repository

All files created such as `font-patcher` and any `ph` or `sh` script/source files are released under an MIT license.

## Glyph/icon sources

| Project                                          | License         |
| ------------------------------------------------ | ----------------|
| Devicons                                         | MIT             |
| Font Awesome                                     | SIL OFL 1.1     |
| Font Awesome Extension                           | MIT             |
| Font Logos                                       | Unlicensed      |
| IEC Power Symbols                                | MIT             |
| Material Design Icons                            | Apache 2.0      |
| Original Source (Seti-UI but modified)           | MIT             |
| Octicons                                         | MIT             |
| Pomicons                                         | CC BY-NC-ND 3.0 |
| Powerline Extra Symbols                          | MIT             |
| Powerline Symbols                                | Free License    |
| Weather Icons                                    | SIL OFL 1.1     |

### Additional notes

* font awesome - we use the fonts which are SIL OFL 1.1, the icons are CC 4.0. We also adhere to the RFN condition to the best of our ability
* weather icons - project is unfortunately dead, but added the OFL license files to comply.

## Fonts

* any/all SIL OFL 1.1 licensed fonts have their appropriate license and/or release note information provided in the original unpatched version folders _and_ the patched version folders.

| Font                          | License                      |
| ----------------------------- | ---------------------------- |
| 3270                          | SIL OFL 1.1                  |
| Agave                         | MIT                          |
| AnonymousPro                  | SIL OFL 1.1                  |
| Arimo                         | Apache 2.0                   |
| AurulentSansMono              | SIL OFL 1.1                  |
| BigBlueTerminal               | CC BY-SA 4.0                 |
| BitstreamVeraSansMono         | Bitstream Vera License v1.00 |
| Cascadia Code                 | SIL OFL 1.1                  |
| IBM Plex Mono                 | SIL OFL 1.1                  |
| CodeNewRoman                  | SIL OFL 1.1                  |
| Cousine                       | Apache 2.0                   |
| DaddyTimeMono                 | SIL OFL 1.1                  |
| DejaVuSansMono                | Free license                 |
| DroidSansMono                 | Apache 2.0                   |                
| FantasqueSansMono             | SIL OFL 1.1                  |
| FiraCode                      | SIL OFL 1.1                  |
| FiraMono                      | SIL OFL 1.1                  |
| Go-Mono                       | Go License                   |
| Gohu                          | Do What The Fuck You Want To |
| Hack                          | MIT                          |
| Hasklig                       | SIL OFL 1.1                  |
| HeavyData                     | Vic Fieger License           |
| Hermit                        | SIL OFL 1.1                  |
| iA Writer                     | SIL OFL 1.1                  |
| Inconsolata                   | SIL OFL 1.1                  |
| InconsolataGo                 | SIL OFL 1.1                  |
| InconsolataLGC                | SIL OFL 1.1                  |
| Iosevka                       | SIL OFL 1.1                  |
| JetBrainsMono                 | SIL OFL 1.1                  |
| Lekton                        | SIL OFL 1.1                  |
| LiberationMono                | SIL OFL 1.1                  |
| Lilex                         | SIL OFL 1.1                  |
| Meslo                         | Apache 2.0                   |
| Monofur                       | Monofur Free License         |
| Monoid                        | MIT                          |
| Mononoki                      | SIL OFL 1.1                  |
| MPlus                         | Free License                 |
| Noto                          | SIL OFL 1.1                  |
| OpenDyslexic                  | Bitstream License            |
| Overpass                      | SIL OFL 1.1                  |
| ProFont                       | MIT                          |
| ProggyClean                   | Free License                 |
| RobotoMono                    | Apache 2.0                   |
| ShareTechMono                 | SIL OFL 1.1                  |
| SourceCodePro                 | SIL OFL 1.1                  |
| SpaceMono                     | SIL OFL 1.1                  |
| Terminus                      | SIL OFL 1.1                  |
| Tinos                         | Apache 2.0                   |
| Ubuntu                        | Ubuntu Font License 1.0      |
| UbuntuMono                    | Ubuntu Font License 1.0      |
| VictorMono                    | MIT                          |

source: https://github.com/ryanoasis/nerd-fonts/blob/master/license-audit.md

**Comment by DHowett** [comment]
Pomicons, as CC BY-NC-ND, worries me. I'm also not a lawyer, but I would be concerned that distributing it in a set of other icons could be construed as a derivative work.

**Comment by ryanoasis** [comment]
Thanks @DHowett I will look into that one.

The project is now officially no longer overall MIT. Only the various bits and pieces. The LICENSE file as been updated (probably not for the last time 😢 )

**Comment by ryanoasis** [comment]
I see what you mean now.

https://creativecommons.org/licenses/by-nc-nd/3.0/

> No Derivative Works. You may not alter, transform, or build upon this work.
> For any reuse or distribution, you must make clear to others the license terms of this work. The best way to do this is with a link to this web page.
> Any of the above conditions can be waived if you get permission from the copyright holder

https://en.wikisource.org/wiki/Creative_Commons_Attribution-NonCommercial-NoDerivs_3.0_Unported

We may have to communicate with the project owner: "Any of the above conditions can be waived if you get permission from the copyright holder"

**Comment by ryanoasis** [comment]
Okay, wow I've forgotten about this but... Gabriele Lana _did_ give permission waaaay back in 2015 😅  

> @ryanoasis sorry, I didn't mean that, I was wandering if you are willing to include this font in your project

https://github.com/gabrielelana/pomicons/issues/2#issuecomment-108717674

**Comment by ryanoasis** [comment]
also for reference #14

**Comment by ryanoasis** [comment]
cc: @clairernovotny @codinguncut FYI

**Comment by ryanoasis** [comment]
For now I'm considering this closed. Feel free to further comment on this ticket though

**Comment by wez** [comment]
Over in https://github.com/wez/wezterm/issues/1521 we're considering bundling `Symbols Nerd Font` with wezterm and adding it as a default fallback, so that everyone can use the symbols without patching any fonts.

I'm also concerned about the Pomicons license, as it is the least free of the icon source licenses.

I'm curious about the scope of the permission that @gabrielelana granted, in particular, I'm wondering if that permission is transitive: does it allow anyone to re-distribute the fonts obtained from here under the terms of eg: SIL OFL 1.1.

From what I've read in your license audit doc, it is still listed as `CC BY-NC-ND` and @ryanoasis has permission to distribute, but the state of re-distribution for others is unclear.

It would be really helpful if @gabrielelana could make a statement along the lines of:

> I give permission to distribute and redistribute Pomicons as part of the Nerd Fonts project under the terms of \<LICENSE\>

so that we have a clear way to understand what terms they wish to apply and can resolve the ambiguity!

**Comment by gabrielelana** [comment]
@ryanoasis @wez sorry for the late reply

The only reason I had made pomicons is to share it with everyone, I'm not an expert in licences, I simply didn't want other people to sell the font. Question: with this intention in mind will be the "SIL OFL 1.1" the most appropriate licence today?

For now here's the statement you asked

I give permission to distribute and redistribute Pomicons as part of the Nerd Fonts project under the terms of SIL OFL 1.1

**Comment by wez** [comment]
@gabrielelana Thanks for responding! Licenses can be tricky and nuanced! SIL OFL seems to be a popular license and is rather flexible. It does prohibit sale of the font itself, however, it doesn't prevent others from selling software/bundles that include the font.

I'd recommend looking through this FAQ to get a sense of some of what it allows and whether is compatible with your intent:
https://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#2966a54b

I don't want you to feel pressured into using a license just because it is convenient for others, especially if that license doesn't match your intent!
