### ISSUE TITLE
Hand-pick glyphs to include in font-patcher with --careful

### ISSUE THREAD

**Issue by esn89** [ryanoasis/nerd-fonts#267]
#### 🎯 Subject of the issue

I want to use fontawesome, along with the ligatures in my font (Pragmata Pro) and to ensure that none of my ligatures get overwritten, I used the --careful flag.

Once that's done, I noticed that in my nerd-tree, I am missing some devicons such as Python and Golang

https://i.imgur.com/glQw5VW.png

#### 🔧 Your Setup

- PragmataPro Nerd Font.ttf
- iterm2
- OSX

#### ★ Optional
https://i.imgur.com/glQw5VW.png

I checked to see if the Python Glyph collides with my ligatures and it doesn't.  Is there anyway to pick just a handful, like 5 glyphs to include during patching WITH the --careful flag?

**Comment by ryanoasis** [comment]
@esn89 Thanks for the report! :smile: 

>  Is there anyway to pick just a handful, like 5 glyphs to include during patching WITH the --careful flag?

Not at the moment but that'd be a nice to have feature!!

**Comment by Finii** [comment]
Ligature needed glyphs are now automatically not patched via
* #1089
