### ISSUE TITLE
2.0 Fonts Can't Be Used in Windows cmd.exe/powershell.exe/wsl shells

### ISSUE THREAD

**Issue by brennanfee** [ryanoasis/nerd-fonts#269]
#### 🎯 Subject of the issue

It seems that something in the fonts changed to prevent the cmd.exe (windows console) from recognizing the fonts.  I'm aware that there are a few font flags that are required for cmd.exe to recognize the fonts (such as OEM_CHARSET for opentype and FF_MODERN for truetype).

This works with previous versions of the fonts (as recently as 1.2).  I even tried the old-school method of adding them to the registry (which isn't supposed to be needed anymore).

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_

I haven't tried them all but the ones I'm trying to get working are: Hack, SauceCodePro, Hasklug, Fura Code.  In every case, I installed the "Windows Compatible Mono" versions of the fonts.

- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_

Standard Windows cmd.exe or PowerShell.exe or any of the WSL shells (ubuntu).

- _Are you using OS X, Linux or Windows? And which specific version or distribution?_

Windows 10, 1803

**Comment by razvancioarga** [comment]
Same here:
 - have tried DejaVu Sans Mono Nerd Font Complete Windows Compatible.ttf
 - stardard cmd.exe, debian wsl, wsl-terminal
 - Windows 10, 1803

Tried the old regedit stuff, does not work at all. 

Could this be because of the latest Windows update?

**Comment by Thraka** [comment]
From what I've read online, windows won't list fonts that have a variable font width in them of some kind. I have a feeling that even though these are marked as mono spaced, there is something in there variable or not conforming to whatever base size is used, and windows is automatically excluding them.

**Comment by Thraka** [comment]
Is it possible that PR #283 fixes this!?

**Comment by haasosaurus** [comment]
@Thraka yeah i just tested it and it fixes it. at first it didn't work because i tried to patch an otf font, but once i patched the ttf version i could use it in cmd/powershell

**Comment by Thraka** [comment]
@haasosaurus Awesome! Did your patching tests run through all the fonts? Or do I have to download the source and build and generate fonts (I don't really want to do that).

**Comment by haasosaurus** [comment]
@Thraka i'm generating them all for you, but my computer sucks so it's taking a long time,  i would hope by tonight it will be done

**Comment by haasosaurus** [comment]
@Thraka try the fonts in this branch of my fork
https://github.com/haasosaurus/nerd-fonts/tree/regen-mono-font-fix

**Comment by RDeluxe** [comment]
I'm afraid it's still not working for me :(

**Comment by elentok** [comment]
@haasosaurus Thanks! I tried LiberationMono from your branch and it worked

**Comment by ezpuzz** [comment]
@haasosaurus I used your branch to patch `PragmataPro Mono Liga` (recently released) and it was able to be used in Powershell!  Unfortunately it destroyed the kerning between letters and all letters and symbols seemed to have additional space between them as compared to regular `PragmataPro Mono Liga` which was a dealbreaker for me.

`ffpython E:\repos\nerd-fonts\font-patcher "C:\Users\invad\Downloads\Pragmata Pro Regular\Pragmata Pro Regular\FSD - PragmataProMonoLiga-Regular.ttf" -s -w --careful --powerline --powerlineextra --octicons --out E:\repos\fonts`

![unpatched](https://user-images.githubusercontent.com/672182/46514300-fb3edb80-c811-11e8-820e-ecae3fd9f273.PNG)
![patched](https://user-images.githubusercontent.com/672182/46514301-fb3edb80-c811-11e8-82c4-318a0648e28c.PNG)

**Comment by kknox** [comment]
I discovered in 'Putty Configuration' -> Window -> Appearance, there is a check box 'Allow selection of variable-pitch fonts' that when enabled allowed me to use fonts in ssh that WSL or CMD.exe would not list.

**Comment by Andrioshe** [comment]
I actually got the same problem.. any fix?

**Comment by faridcher** [comment]
@haasosaurus 
could you please regenerate ttf files for Meslo font? in your branch, only otf versions are available. thanks

**Comment by brennanfee** [comment]
I can confirm that the "mono" versions of the fonts provided in @haasosaurus branch work in cmd.exe and powershell.exe

There are some minor issues (like the "italic" version of Source Code Pro seems to be missing from his branch)... but the general fix he provided does seem to work in Windows.

**Comment by cspotcode** [comment]
@haasosaurus I was hitting the same problem, and your PR fixed it for me.  I was even able to `--custom` Windows' Segoe UI Symbols font to get the prompt arrow used by https://github.com/sindresorhus/pure

Thank you!

**Comment by khmaies5** [comment]
still not working for me 
Windows 10 v1809

**Comment by Jaykul** [comment]
Isn't this just a dupe of #270 ?

**Comment by brennanfee** [comment]
I can confirm that this is fixed as of the 2.1 release.  I am closing this ticket.

**Comment by ABDULAZIZ94** [comment]
the 3270 works on my windows 10 cmd. i used it as thin client to nvim installed on an ubuntu. download it [here](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.1.0)

**Comment by mb2g17** [comment]
@haasosaurus font fix works on cmd.exe, however I had to uninstall my existing fonts before reinstalling the patched ones for it to show up on the cmd.exe properties.
