### ISSUE TITLE
No 'Complete Mono.ttf' version of 'SourceCodePro/Italic/' is available

### ISSUE THREAD

**Issue by snoblenet** [ryanoasis/nerd-fonts#271]
Please see: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/SourceCodePro/Italic

Compare to https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/SourceCodePro/Bold/complete for example.

Many thanks.

**Comment by ryanoasis** [comment]
Thanks for the report! It's appreciated!

Not sure what happened there

**Comment by snoblenet** [comment]
The font variant still seems to be missing?

**Comment by ryanoasis** [comment]
Not sure what happened, but v1.050 will get copied over. From https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it
