### ISSUE TITLE
install.sh incorrectly adding space before separator when imploding font names to install

### ISSUE THREAD

**Issue by gbiggs** [ryanoasis/nerd-fonts#280]
#### 🎯 Subject of the issue

When choosing a subset of fonts to install, the `install.sh` script concatenates all the font directories together separated by `" "` (a double quote, a space, and another double quote). However, because of the way it does the concatenating, installing three or more fonts causes all font directories except the first and last to have a space at the end of the string before the double quote. For example, with three fonts selected:

`/home/geoff/src/nerd-fonts/patched-fonts/Hack" "/home/geoff/src/nerd-fonts/patched-fonts/DejaVuSansMono " "/home/geoff/src/nerd-fonts/patched-fonts/DroidSansMono`

With four fonts selected:

`/home/geoff/src/nerd-fonts/patched-fonts/Hack" "/home/geoff/src/nerd-fonts/patched-fonts/DejaVuSansMono " "/home/geoff/src/nerd-fonts/patched-fonts/DroidSansMono " "/home/geoff/src/nerd-fonts/patched-fonts/LiberationMono`

This causes the `find` command to report that it cannot find the font directory for those fonts with an extra space:

    find: ‘/home/geoff/src/nerd-fonts/patched-fonts/DejaVuSansMono ’: No such file or directory
    find: ‘/home/geoff/src/nerd-fonts/patched-fonts/DroidSansMono ’: No such file or directory

I traced the problem to [this line](https://github.com/ryanoasis/nerd-fonts/blob/d1d9a7eb23fc9f5efc00c89cdd58694547a0df39/install.sh#L165) in the `implode` function in `install.sh` (line 165):

        printf -v "$retname" "%s" "$ret${*/#/$sep}"

As far as I can tell (my bash skills are not great), the first font directory is fine because it is in the `$ret` variable, and the last is fine because it doesn't need the separator appended, but for all the others, it is chopping the arguments after the space, not removing the space, and then appending the separator rather than replacing the space with the separator.

I had a go at replacing the search-replace with a call to `sed` but that messed up other calls to the function due to replacing *all* spaces. At that point I ran out of time to try and fix it myself.

A work-around is to install fonts two at a time by calling `install.sh` multiple times.

#### 🔧 Your Setup

- Terminal emulator: konsole
- Shell: GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
- Debian Linux 9

**Comment by ryanoasis** [comment]
Appreciate this report and thanks for the details and digging deep!

I use ShellCheck locally (and we use in the build) and have been fixing the warnings on the bash scripts but the install is clean, however there is definitely an issue regardless.

**Comment by Finii** [comment]
Thanks for the excellent examination and bug report!
