### ISSUE TITLE
Operator Mono Ligratures

### ISSUE THREAD

**Issue by Skyline404** [ryanoasis/nerd-fonts#286]
Hi, I'm using this comand `./font-patcher Operator\ Mono\ Book\ Regular.otf -c --careful`, but Ligatures are missing after patching.

It should be
<img width="506" alt="2018-07-29 17 36 22" src="https://user-images.githubusercontent.com/32412867/43367516-e17d705c-9356-11e8-82d1-8c0e07784ee9.png">

but it looks like
<img width="426" alt="2018-07-29 17 39 01" src="https://user-images.githubusercontent.com/32412867/43367518-e8840a1e-9356-11e8-8531-226c1b8b878b.png">

**Comment by ryanoasis** [comment]
Thanks. There are several issues with ligatures at the moment, Nerd Fonts is not ligature safe at the moment. :disappointed:

**Comment by ryanwmarsh** [comment]
@Skyline404 I ran this on the Operator fonts today (I use the screen-smart versions but I have the regular variant too), installed them all, and the italics are working just fine for me in VSCode.

```sh
find . -name "OperatorMono*.otf" -exec ./font-patcher -c --careful {} \;
```

**Comment by remailednet** [comment]
Like @Skyline404 originally I just installed the patched version of Operator Mono Book Regular.otf and 'lost' the italics. Of course, once I patched and installed the italic version everything worked as expected.

**Comment by xhaythemx** [comment]
> Hi, I'm using this comand `./font-patcher Operator\ Mono\ Book\ Regular.otf -c --careful`, but Ligatures are missing after patching.
> 
> It should be
> <img alt="2018-07-29 17 36 22" width="506" src="https://user-images.githubusercontent.com/32412867/43367516-e17d705c-9356-11e8-82d1-8c0e07784ee9.png">
> 
> but it looks like
> <img alt="2018-07-29 17 39 01" width="426" src="https://user-images.githubusercontent.com/32412867/43367518-e8840a1e-9356-11e8-8531-226c1b8b878b.png">

can you tell me please what color schema are you using please for your editor

**Comment by xhaythemx** [comment]
> @Skyline404 I ran this on the Operator fonts today (I use the screen-smart versions but I have the regular variant too), installed them all, and the italics are working just fine for me in VSCode.
> 
> ```shell
> find . -name "OperatorMono*.otf" -exec ./font-patcher -c --careful {} \;
> ```
> 
> @ryanoasis If @Skyline404 can confirm perhaps this issue could be closed?
> 
> I'm using the a different theme but I typed up the same code you have. It looks the same in my patched and unpatched Operator fonts.
> <img alt="screen shot 2018-09-30 at 6 56 54 pm" width="570" src="https://user-images.githubusercontent.com/824046/46264455-b13cb980-c4e2-11e8-8ac2-7f0cba52fe95.png">

can you tell me please what color schema are you using please for your editor

**Comment by Finii** [comment]
Ligatures should finally be preserved
* #1089

But what it looks like is what you want is **italice** and what you get is **slanted**, maybe auto-'italics'.
