### ISSUE TITLE
Inconsolata font source is deprecated

### ISSUE THREAD

**Issue by Elvyria** [ryanoasis/nerd-fonts#289]
#### 🎯 Subject of the issue

Original Inconsolata has noticible quality issues wich i cannot explain in the right way, but i can show. Is it possible to replace it with google one?

##### [Google Inconsolata](https://github.com/google/fonts/blob/master/ofl/inconsolata/Inconsolata-Regular.ttf) patched by myself
![image](https://user-images.githubusercontent.com/2061234/43904353-183c8dbe-9bf7-11e8-834b-4f25030bffbe.png)
##### [Original source and Inconsolata NF Mono Windows](levien.com/type/myfonts/Inconsolata.otf) from master branch
![image](https://user-images.githubusercontent.com/2061234/43904494-70ed8fd0-9bf7-11e8-82e1-c3664f490f67.png)

#####Original 18 cmder
![image](https://user-images.githubusercontent.com/2061234/43905846-9790cb18-9bfa-11e8-9c87-20c1d242308f.png)
#####Google 18 cmder
![image](https://user-images.githubusercontent.com/2061234/43905912-b5404b70-9bfa-11e8-894a-0ce00e7c56a5.png)

#### 🔧 Your Setup

- Inconsolata Nerd Font Complete Mono Windows Compatible.otf
- Windows 10

**Comment by ryanoasis** [comment]
We can update here, just that the official Inconsolata doesn't come with Powerline glyphs so we'll have to adjust the config to add those as well
