### ISSUE TITLE
Odd gap between glyphs and text

### ISSUE THREAD

**Issue by mhartington** [ryanoasis/nerd-fonts#29]
Not sure what happened, but since updating my fonts to include the new icons, I'm getting some weird spacing between the powerline glyphs and regular text.

<img width="408" alt="screen shot 2015-09-05 at 4 26 08 pm" src="https://cloud.githubusercontent.com/assets/2835826/9701152/42efa624-53eb-11e5-99f4-c9fdf2e68ff6.png">

Using other fonts that have powerline support do not have this issue.

**Comment by ryanoasis** [comment]
I've been away but I will look into this. I think one thing that needs to happen is to detect if the powerline characters are present in the font being patched and to *not* add (override) the already existing powerline glyphs.

per: https://github.com/ryanoasis/nerd-fonts/pull/28#issuecomment-137246730

**Comment by sethamclean** [comment]
I have the same issue using the pre-patched source code pro fonts

**Comment by kiranps** [comment]
@mhartington i think you are using tmux separator as | change it to "" blank

**Comment by dritter** [comment]
@kiranps I don't think so. I have the same issue without using tmux..

**Comment by sethamclean** [comment]
I have the same problem with "Sauce Code Powerline Plus Nerd File Types Mono Plus Font Awesome Plus Octicons Plus Pomicons.otf". My terminal is urxvt and I am seeing the gap in VIM with lightline.

**Comment by mudox** [comment]
I can reproduce the gap by increasing the horizontal character spacing in iTerm2, maybe it's a editor/terminal font rendering issue.

**Comment by dritter** [comment]
@mudox I left the character spacing untouched. And like @sethamclean I have it with "Sauce Code"-Font only. So this is definitely a font issue.

**Comment by sethamclean** [comment]
@mudox reducing the font spacing can remove the gap but the arrows are vertically too small as well. This results in a "road cone"  like shape.

**Comment by mhartington** [comment]
Yeah, using source code pro or hack, which has powerline support already, there isn't an issue.
So this is an issue where the glyphs that get patched are off by a pixel or two.

**Comment by ryanoasis** [comment]
I am working on _not_ overwriting powerline glyphs if they are already present in the font to be patched.

I thought this actually _may_ have been fixed for recently patched Sauce Code but https://github.com/ryanoasis/vim-devicons/issues/126 seems to suggest otherwise. I have not tested yet.

**Comment by mhartington** [comment]
Looking good! Happy to be closing this.

**Comment by voiprodrigo** [comment]
I have this problem, commented in https://github.com/ryanoasis/nerd-fonts/issues/26

**Comment by ryanoasis** [comment]
@voiprodrigo thanks

**Comment by cata0309** [comment]
2019, the issue is still present

**Comment by ryanoasis** [comment]
@cata0309 Could you attach a screenshot and give some more details (os, terminal, font and font size)?

I know it seems frustrating that this seemingly small issue may not be solved 100% for all scenarios but this is actually difficult to look perfect for all terms and fonts at all sizes. It seemed like this was solved and furthermore it made sense to spend time on the lower hanging fruit. Thanks

**Comment by cata0309** [comment]
![image](https://user-images.githubusercontent.com/35623921/59972331-dbb13400-9595-11e9-9ea2-6f8f0cd6fce5.png)
I am using Solus Linux Fortitude
Terminal: Gnome-terminal, tilda, tilix
font: Furacode NF Regular size 12
Name a  terminal that shows the fonts right, I will install right away.

**Comment by spinnau** [comment]
@cata0309 I also see this effect in GNOME-Terminal 3.32.2 running on GNOME desktop. Testing different fonts (DejaVu Sans Mono Regular, Fura Code Regular, Meslo LG L  Regular, Sauce Code Pro) and font sizes from 9 to 14 doesn't solve the problem.

After testing some hinting and anti-aliasing settings in GNOME Tweak Tool I have found that the gaps disappear by changing the anti-aliasing from Subpixel to Grayscale.

With Subpixel anti-aliasing:
![subpixel_antialiasing](https://user-images.githubusercontent.com/2995937/60541930-e6e12e00-9d12-11e9-8597-f891f5bb85e6.png)

With Standard (grayscale) anti-aliasing:
![grayscale_antialiasing](https://user-images.githubusercontent.com/2995937/60541975-09734700-9d13-11e9-8008-ad82c714bcf8.png)

GNOME Tweak Tool settings:
![Gnome_antialiasing_settings](https://user-images.githubusercontent.com/2995937/60541999-1a23bd00-9d13-11e9-9e31-d265bf97c5f9.png)

**Comment by cata0309** [comment]
Thank you, I will try that out ? What are you using ? Powerline 10k ?

mar., 2 iul. 2019, 22:55 spinnau <notifications@github.com> a scris:

**Comment by spinnau** [comment]
The theme used in the screenshots is powerlevel9k.

I have tried this on another computer, also with GNOME-Terminal 3.32.2 on GNOME desktop. The effect can be reproduced. With subpixel anti-aliasing the small gaps can be seen, but they are gone if the anti-aliasing is switched to grayscale. @ryanoasis so maybe this is just a rendering problem?

Both computers are running on arch linux with the same GNOME desktop version but with different graphics hardware and drivers. One computer uses nvidia drivers on X11 and a monitor with 110 ppi. The other computer runs intel graphics with modesetting driver on wayland and a monitor with 92 ppi.

**Comment by MIvanchev** [comment]
I have just hit this issue in 2021 (on Ubuntu MATE):

![Image](https://raw.githubusercontent.com/MIvanchev/images/7ef2476b7da97c55a8f42aae9b83e7fcfe9ac302/image.png)

**Comment by Finii** [comment]
@MIvanchev do you mean the faint line, circled yellow?

![image](https://user-images.githubusercontent.com/16012374/152726143-793b5689-79d2-4709-bebc-f2c23e282775.png)

We would need exact font name (and if you self patched or where you did download it, to examine the exact same file), terminal used, terminal font settings,
Maybe you can try if turning antialiasing to 'greyscale' fixes it? (See Tweak tool some comments furter up.)

**Comment by MIvanchev** [comment]
Hey @Finii, this line is exactly what I mean yes. This is Literation Mono size 12 downloaded directly from https://www.nerdfonts.com/. I use neovim-qt, default Gnome settings but changing them has no effect. Grayscale has no effect. The only thing that fixes this is disabling anti-aliasing completely.

**Comment by Finii** [comment]
I see it in Tilix:

![image](https://user-images.githubusercontent.com/16012374/152762070-7fa2bdce-cc63-47a6-82f9-c3c07146f177.png)

But it is gone when `greyscale`. 

![image](https://user-images.githubusercontent.com/16012374/152762520-7081289f-79cf-4faf-82a1-d025f1a3308e.png)


- Need to change to greyscale and close `tweaks`
- Need to focus on `tilix` (which obviously only redraws if active)

Anyhow, that is just kind of hotfix for you, possibly.

Just found out https://github.com/ryanoasis/nerd-fonts/discussions/779#discussioncomment-2123303
Let's see (ponder) what we can do in that manner.

**Comment by MIvanchev** [comment]
@Finii Could you try the triangle characters back to back?

**Comment by Finii** [comment]
Can you copy and paste the chars, then I do not need to find out which comes first in your setup? The whole line if possible, as text.

**Comment by Finii** [comment]
Cascadia Code again with extra neg. bearing on problematic (right in this case) side.

![image](https://user-images.githubusercontent.com/16012374/152764064-e586faee-08d1-4cb0-96b9-807610f765ab.png)

**Comment by Finii** [comment]
I use ordinary `neovim` running in `tilix`. Installed this Qt thing... where do I change the font :grimacing: 

If it does not work for you I bet it is some Qt font rendering blah... :roll_eyes:

**Comment by MIvanchev** [comment]
You change the font using `:GuiFont` in the ginit.vim file or in the editor itself. Try this text: 

**Comment by Finii** [comment]
Hmm, in `tilix` (running `neovim`) the glyphs are too wide (as one also would have anticipated by the `fontforge` outline windows above (unchanged 2446 width :unamused: )

![image](https://user-images.githubusercontent.com/16012374/152765977-7d5f3b7a-b94c-497f-8f0b-d7d9d56efa8e.png)

Anyhow:
![image](https://user-images.githubusercontent.com/16012374/152766633-f9d24b5b-569f-46f2-9945-045cdcc73f76.png)

Do you use `Literation Mono NF Mono` instead?

**Comment by MIvanchev** [comment]
I think this error exists on any nerd font, just do `:GuiFont! LiterationMono Nerd Font Mono:h12`

**Comment by Finii** [comment]
Hmm, I see it with LCD antialias:

![image](https://user-images.githubusercontent.com/16012374/152769809-0b607c93-185f-4a46-9d2d-5356fc212dfc.png)

but not with greyscale:

![image](https://user-images.githubusercontent.com/16012374/152770045-4d8547e5-abcc-4195-9789-de66e3ed8199.png)

* Change to `greyscale`
* Close `tweaks`
* restart `neovim qt`
* reload text file
* set `GuiFont`

Scaled up 400%:

![image](https://user-images.githubusercontent.com/16012374/152771372-02800fa7-bfc7-47b2-b29a-5117827ebe21.png)

(LCD antialias has these colored edges, i.e. left)

It's still there but very faint, can not see it without magnification.

**Comment by Finii** [comment]
Oh, and I'm on X11 not Wayland, if that is a difference :thinking:

**Comment by Finii** [comment]
Hmm, our `overlap` code seems to be broken?

![image](https://user-images.githubusercontent.com/16012374/152773775-35579616-81e0-40da-b095-9600aca635ea.png)

No negative bearing on left, but negative bearing on right.
Should be some overlap over the 'box' on both sides.

\\me starts up editor

**Comment by MIvanchev** [comment]
Hey, thanks for the extensive testing. Unfortunately I do still have it with. Even forcing grayscale with in `fonts.conf` doesn't change it. The shading along the edge is different but still extremely noticeable. 

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
  <match target="pattern">
    <test name="family" compare="eq">
      <string>LiterationMono Nerd Font Mono</string>
    </test>
    <edit name="rgba" mode="assign"><const>none</const></edit>
  </match>
</fontconfig>
```
I think I'm going to generate a bitmap grayscale font and work with that.

**Comment by MIvanchev** [comment]
Thanks, I'm really grateful for your insights!!! Btw this is not only in Qt, every tool on the system has it. It's some GNOME / FreeType weirdness. I was quick to blame Qt as well.

**Comment by Finii** [comment]
I guess this is solved now. Maybe you can check the font on your setup.
Can you self-patch from the PR or shall I put the font file somewhere to download?

**Comment by Finii** [comment]
Homeoffice sei dank ;-)

**Comment by MIvanchev** [comment]
Allerdings :)) Das ist echt großartig.

**Comment by MIvanchev** [comment]
Current result with `--complete`:

![Image](https://github.com/MIvanchev/images/blob/f566adb7-5097-442b-a82a-8fdde6d65531-1/image.png?raw=true)

**Comment by Finii** [comment]
This looks like `LiterationMono Nerd Font` (non-Mono). The triangular things have double-width there.
\*duh\* it's written in your vim ini :-D

I did not check the overlap for the non-`mono` version :grimacing:

Is it an improvement? I see faint lines. Do they bother? Maybe patch with 4% overlap :roll_eyes:

**Comment by MIvanchev** [comment]
Wait, what, it says mono in the name, I'm CONFUSED :D

**Comment by Finii** [comment]
`Literartion Mono Nerd Font` (not mono)
`Literartion Mono Nerd Font Mono` (real mono)

naming is hard...

**Comment by MIvanchev** [comment]
`--mono` plus 4% overlap worked :)

![Image](https://github.com/MIvanchev/images/blob/f566adb7-5097-442b-a82a-8fdde6d65531-2/image.png?raw=true)
