### ISSUE TITLE
Difference between upper right and left triangle

### ISSUE THREAD

**Issue by blueyed** [ryanoasis/nerd-fonts#294]
I have noticed a difference between nf-ple-upper_left_triangle (e0bc) and nf-ple-upper_right_triangle (e0be).

In Kitty terminal:
![kitty](https://user-images.githubusercontent.com/9766/46073314-d5b43100-c184-11e8-87bd-e145de30a423.png)

(patched urxvt):

![urxvt](https://user-images.githubusercontent.com/9766/46073320-dbaa1200-c184-11e8-8b87-d9c73ad1e3bb.png)

I am using `Ubuntu Mono Nerd Font Complete.ttf`.

**Comment by blueyed** [comment]
JFI: updated the desc / submitted to early (triggering a notification now, will delete it)

**Comment by Finii** [comment]
This is fixed, thanks for reporting, sorry for late reply.
