### ISSUE TITLE
vim-file icon (e62b) is not showing correctly in gnome terminal

### ISSUE THREAD

**Issue by alexs-jfrog** [ryanoasis/nerd-fonts#295]
#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ Nerd\ Font\ Plus\ Font\ Awesome\ Plus\ Octicons\ Regular\ 11
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
gnome
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
centos 7

#### ★ Optional
![screen shot 2018-09-26 at 5 00 53 pm](https://user-images.githubusercontent.com/39350157/46115848-d3b29800-c1ad-11e8-88a1-fe0745196862.png)
as you can see instead of vim-style letter "V" I am getting something else.
It looks like the DejaVu font is not patched completely.

Thank you in advance

**Comment by ryanoasis** [comment]
@alexs-jfrog sorry for the late reply. Thanks for the report

**Comment by Finii** [comment]
Hmm, I see also some other issues, but they should be fixed by now. Maybe try `v2.3.3`.

![image](https://user-images.githubusercontent.com/16012374/215294429-07c3e0ec-f1b4-4a32-86e6-3b8ad7710344.png)
