### ISSUE TITLE
powerline extra symbols included ?

### ISSUE THREAD

**Issue by ScriptorNY** [ryanoasis/nerd-fonts#30]
Hello,

I would like to know if these fonts also include the powerline extra symbols. I have tested some of theme with `xfd` but I didn't see any "flames" or other powerline extra symbols.

Thank you very much in advance :)

**Comment by ryanoasis** [comment]
Hey. No sorry I haven't included them yet but shouldn't be too hard to add another combination to get them included :)

I'll try to add them in when I can and I'll keep you updated on this ticket

**Comment by ScriptorNY** [comment]
Thank you very much for your quick response :) And thank you :)
