### ISSUE TITLE
Consideration of other fonts

### ISSUE THREAD

**Issue by DonaldTsang** [ryanoasis/nerd-fonts#300]
After browsing the internet I have found multiple fonts that may be useful.
If they are not useful, I would like to know what are the criterias of picking fonts. 
- [ ] https://twitter.github.io/twemoji/
- [ ] https://xtoolkit.github.io/Micon/
- [ ] https://github.com/google/material-design-icons
- [ ] https://github.com/legomushroom/iconmelon
- [ ] https://github.com/ionic-team/ionicons
- [ ] https://github.com/yusukekamiyamane/fugue-icons
- [ ] https://github.com/linea-io/Linea-Iconset

**Comment by ryanoasis** [comment]
Thanks for the list!

**Comment by DonaldTsang** [comment]
@ryanoasis I could also get those from other list articles if you want, but those 7 are all ones with large amount of icons.

**Comment by ira-bv** [comment]
On the flip side, here's a new font I found that's SIL OFL and is begging for a patching... https://quoteunquoteapps.com/courierprime/

**Comment by DonaldTsang** [comment]
- (7) https://designroast.org/best-free-icon-fonts-for-web-designers/
- (50) https://speckyboy.com/free-icon-fonts/
- (10) https://ourcodeworld.com/articles/read/755/top-10-best-free-icon-fonts-for-web-designers
- (30+) https://cssauthor.com/free-icon-fonts/
- (14) https://www.webfx.com/blog/web-design/free-icon-fonts/
- (18) http://designbump.com/18-best-free-icon-fonts/
- (5) https://cssreset.com/5-best-free-icon-fonts-for-your-next-project/
- (20) https://pixinvent.com/free-icon-fonts-for-commercial-use/
- https://www.codewall.co.uk/the-best-free-icon-font-libraries/
- (33) https://naldzgraphics.net/free-icon-fonts/
- (25+) http://www.andysowards.com/blog/2014/icon-fonts/
- (11) https://scotch.io/bar-talk/11-great-icon-fonts-for-your-projects
- (20) https://acodez.in/web-icon-fonts/

**Comment by DonaldTsang** [comment]
@ira-bv could you open another issuer this?

**Comment by ira-bv** [comment]
Okie doke.

**Comment by DonaldTsang** [comment]
2020 font goals: More coverage?

**Comment by ryanoasis** [comment]
> 2020 font goals: More coverage?

By more coverage you mean more fonts?

If so then yes always :smile: 

For this project my current goals are:
- Establish and stick to a predictable release cadence
- Explore Github actions for building the fonts and releases
- Triage and fix older issues before they are lost to the sands of time

**Comment by Finii** [comment]
> Issue 300 looks spartan

:rofl: 

Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
