### ISSUE TITLE
Missing Bold/Italic/BoldItalic variants of Meslo

### ISSUE THREAD

**Issue by segevfiner** [ryanoasis/nerd-fonts#302]
#### 🎯 Subject of the issue

The [Meslo](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Meslo) font is missing the Bold/Italic/BoldItalic variants despite them existing in the [original](https://github.com/andreberg/Meslo-Font) and [powerline patched](https://github.com/powerline/fonts/tree/master/Meslo%20Slashed) versions. I think they should be added, as otherwise the Bold/Italic/BoldItalic styles look ugly.

#### 🔧 Your Setup

- MesloLGM
- gnome-terminal
- Ubuntu 18.04.1 amd64

**Comment by ryanoasis** [comment]
I'll take a look this weekend. Thanks
