### ISSUE TITLE
Blex: No mentions of Blex in Changelogs and on Website.

### ISSUE THREAD

**Issue by AlmightyScientist** [ryanoasis/nerd-fonts#303]
Hey :)
It seems like `Blex` doesn't appear on the website / in the changelog / in the release tab of GitHub.
When will it be released ?

Thanks for the awesome work!

**Comment by AlmightyScientist** [comment]
Up.

**Comment by ryanoasis** [comment]
Thanks @AlmightyScientist . Looks like I dropped the ball on this

**Comment by ryanoasis** [comment]
I am going to tag this for the next release so it makes it in officially and not forgotten..

**Comment by ryanoasis** [comment]
Okay so IBM Plex (Blex) wasn't in 2.0, it is for this next release #253

Sorry for any confusion (this is what happens when you don't generate releases regularly enough :disappointed: )
