### ISSUE TITLE
Ubuntu Mono is weird about horizontal spacing

### ISSUE THREAD

**Issue by kud** [ryanoasis/nerd-fonts#306]
![image](https://user-images.githubusercontent.com/655838/49159801-9392a180-f325-11e8-9e12-5ff0d51ee2b5.png)

I don't have that with other fonts. :/

**Comment by kud** [comment]
And I have as settings "100%" for horizontal spacing.

**Comment by ryanoasis** [comment]
Thanks @kud. Have to look into this

**Comment by thiagodebastos** [comment]
This issue still persist in Windows 11. Did anyone find a fix?

**Comment by Finii** [comment]
Well, I could not reproduce.

Installed `Ubuntu Mono Nerd Font Complete Windows Compatible.ttf` and it shows up fine in the font preview and in a PowerShell window.

![image](https://user-images.githubusercontent.com/16012374/143815041-78d0396d-b828-4719-b43c-51e1afe6b9d9.png)

(Note that I installed just one of the two fonts in the Download folder.)

Please give more details
* Exact font file installed (downloaded from where)
* Which application shows wrong spacing
* Screenshots with complete application incl title bar
* Screenshot maybe with font chooser showing what you selected

**Comment by thiagodebastos** [comment]
> Well, I could not reproduce.
> 
> Installed `Ubuntu Mono Nerd Font Complete Windows Compatible.ttf` and it shows up fine in the font preview and in a PowerShell window.
> 
> ![image](https://user-images.githubusercontent.com/16012374/143815041-78d0396d-b828-4719-b43c-51e1afe6b9d9.png)
> 
> (Note that I installed just one of the two fonts in the Download folder.)
> 
> Please give more details
> 
> * Exact font file installed (downloaded from where)
> * Which application shows wrong spacing
> * Screenshots with complete application incl title bar
> * Screenshot maybe with font chooser showing what you selected

You know what I just uninstalled the Ubuntu fonts and tried again and now it works. I’m not able to reproduce anymore either 🤔 
Sorry to waste your time. I did have the issue for a few weeks but no longer.

**Comment by Finii** [comment]
I will close then. Please reopen if the problem resurfaces.
