### ISSUE TITLE
Add Unscii - a bitmapped unicode font

### ISSUE THREAD

**Issue by MindTooth** [ryanoasis/nerd-fonts#312]
<img width="875" alt="screenshot 2018-12-25 at 15 36 18" src="https://user-images.githubusercontent.com/33870508/50423825-ded39d80-085a-11e9-9e8a-3741748870c2.png">

_(Preview)_

#### 🎯 Subject of the issue

How easily is it to add the [Unscii](http://pelulamu.net/unscii/) font to the repo?  Tried patching it my self with the `--mono` option, but that only crashed kitty.

Thank you for the project. ❤️  I've used Hack Nerd Font Mono for a long time, but fell in love with unscii recently.  And would love to have the devicons available for Vim.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
unscii Nerd Font Mono 16-full
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
macOS

**Comment by ryanoasis** [comment]
Thanks @MindTooth!

Not sure on why the failure. There are quite a few issues at the moment so perhaps it is related to one or more of them.

**Comment by MindTooth** [comment]
Thanks for coming back to me.  And I's unfair that I've kept this open.  I recently switched to the [spleen](https://github.com/fcambus/spleen) font from the OpenBSD project.  I'll keep a watch on the project to see if I can try again later. 😄

**Comment by MindTooth** [comment]
Closing this for now as I don't use the font anymore.
