### ISSUE TITLE
Courier Prime Code could use a nerd treatment

### ISSUE THREAD

**Issue by seefood** [ryanoasis/nerd-fonts#314]
#### 🎯 Subject of the issue

New Font on the market, nice look for terminal users and code monkies, Released under SIL OFL

https://quoteunquoteapps.com/courierprime/

**Comment by seefood** [comment]
also bumped into http://b612-font.com/ but it's not interesting enough, IMHO.

**Comment by bubonicfred** [comment]
Courier Prime has been around for a while. Went looking for a PL version when I found nerd-fonts. 
I've made a version for my personal use, but will give a proper release a go when I have some free time.

**Comment by Finii** [comment]
Closing because transferred to #1095

**Comment by makccr** [comment]
Went ahead and published a [patch version](https://github.com/makccr/CourierPrime-Nerd-Font) if anyone's interested. Will do my best to keep it updated with any changes in Nerd Font's icons.

**Comment by orffen** [comment]
@makccr nice, but looks like you did the Prime version. Any chance of a Prime Code version?

**Comment by makccr** [comment]
> [@makccr](https://github.com/makccr) nice, but looks like you did the Prime version. Any chance of a Prime Code version?

I did [the thing](https://github.com/makccr/CourierPrime-Nerd-Font/releases/).
