### ISSUE TITLE
Add a font preview to the website

### ISSUE THREAD

**Issue by seefood** [ryanoasis/nerd-fonts#316]
like use the code for http://app.programmingfonts.org, nuff said.

(also, maybe adopt some of their collection :-)

**Comment by four43** [comment]
This would be great, you guys have a lot of great ones in this collection and it's hard to choose one!

**Comment by avrelaun** [comment]
I came here to write this issue, it would save users a lot of time

**Comment by xvoidee** [comment]
Please add screenshots, I would like to choose font, but instead of quick navigation over screenshots - I have to google & install each font & test it......

**Comment by nickcoad** [comment]
I'd also love this, or a way to download all fonts in a single package and just install them all so I can cycle through them and pick a favourite.

**Comment by nickcoad** [comment]
Would the maintainers be open to a PR updating the readme with some sample previews?

**Comment by ryanoasis** [comment]
So there has been _some_ movement on this but not exactly a preview on the website.

I have added links to `app.programmingfonts.org` where they do have a version of the font to preview: https://www.nerdfonts.com/font-downloads

I am a bit torn on this one. One one hand I feel like app.programmingfonts.org already does a great job of the previews and doing something similar on Nerd Fonts website would be a bit redundant. On the other hand I did add links to preview and I was thinking of maybe providing simple svg images of each font though this would require some work and it wouldn't be an interactive preview.

I am open to any PRs or other suggestions here

---

> (also, maybe adopt some of their collection :-)

Yes this is happening and needs to happen more. I see some great ones missing in Nerd Fonts

**Comment by four43** [comment]
Referencing them from your website seems like a great solution. No need to re-invent the wheel. Shout out to app.programmingfonts.org for just banging that out. That's great!

**Comment by kierun** [comment]
Personally, I would love to see an image with the fonts as a click (and resize and messing around) for each is tedious. *Yes, I am lazy.* However, I am happy about how it looks.

**Comment by ryanoasis** [comment]
@four43 I agree!

@kierun I was actually thinking pretty much this exactly. Well a sort of 'mini-preview' and a link to the larger preview on app.programmingfonts.org

---

Here is what I was thinking so far:
![Font Preview](https://user-images.githubusercontent.com/8083459/62993845-02f5e600-be0e-11e9-903f-46d46cd630f8.png)


I have this as a script that will build an image for each font, so shouldn't be _too_ bad to do them all...

**Comment by kierun** [comment]
@ryanoasis  I really like it. Is there a way to auto generate it?

**Comment by ryanoasis** [comment]
@kierun Yep! I do have a really terrible bash script that does this currently. It wasn't fully automated but mostly!

The thing about it being automated is we can easily change the text we want to preview, maybe instead of doing alphanumeric we add a small function instead...

This is now mostly done! 

https://www.nerdfonts.com/font-downloads

![screenshot-www nerdfonts com-2019 08 14-14_33_58](https://user-images.githubusercontent.com/8083459/63072964-4702ec80-bedb-11e9-8641-e223f2f37215.png)


Feel free to check it out and give any feedback

A few issues:
The font names on some are a bit strange (font styles showing up) but that could be fixed...
The font name in the images should probably be underline
Not sure if svg is the way to go, but they fonts are converted to paths because well... if you had the font you wouldn't need an image preview :smile:

**Comment by xvoidee** [comment]
Wonderful! :) This saves many hours of my previewing.

Presenting fonts as path/vector - only one choice. No rendering on client side should be done.
And you are right - some code snipped will be better, or it could be both: what you have now + many snippets in different languages on separate page (c/c++/java/python/ruby/etc)

**Comment by ryanoasis** [comment]
I'll probably iterate on this some more when I need a break from Font Land :fearful: 

I'm going to consider this issue closed, but let's feel free to discuss any improvements as well.

**Comment by verhovsky** [comment]
The website moved to https://www.programmingfonts.org/ now all the links are redirected to https://www.programmingfonts.org instead of https://www.programmingfonts.org/#aurulent.
