### ISSUE TITLE
DejaVuSansMono patched complete is not Mono

### ISSUE THREAD

**Issue by audioscavenger** [ryanoasis/nerd-fonts#319]
#### 🎯 Subject of the issue

DejaVuSansMono patched complete is not Mono. That creates noticeable lagging issue with Putty. Same issue with "windows compatible"

#### 🔧 Your Setup

- DejaVuSansMono patched complete
- Windows Putty 64 + xterm-256color

#### ★ Optional

n/a
Thanks for the release but I will stick with the powerline version

**Comment by ryanoasis** [comment]
Thanks for the report @audioscavenger

**Comment by Finii** [comment]
Should be fixed by
* #764
