### ISSUE TITLE
Separate download links for patched fonts to easier packaging

### ISSUE THREAD

**Issue by CestDiego** [ryanoasis/nerd-fonts#32]
In order to make packages for each of the patched fonts it would be nice to provide a separate download link (I think releases in github might be able to release just one dir as well so as to do it per font) per font so that each package won't clone the entire repo for each of the fonts.

**Comment by ryanoasis** [comment]
Sorry I think I need some more explanation on this.

Do you mean just a separate dir per font or do you mean individual archive package per each font? If the latter then that seems like it might be a bit of work.

Can you give an example and/or a project that does something like this?
Thanks

**Comment by ryanoasis** [comment]
@CestDiego could you provide some more info? :stuck_out_tongue:

**Comment by CestDiego** [comment]
I thought it would be nice to be able to download only one patched font instead of the whole repo :( I thought that it would be easier with the new infrastructure but it's not :(

**Comment by ryanoasis** [comment]
You mean one patched font as an archive? Because downloading a single font is possible.

**Comment by CestDiego** [comment]
Yeah but have you tried? the names are so long, one can hardly determine which font is which.

**Comment by ryanoasis** [comment]
@CestDiego Yes the names are disgusting long. I am going to at the very least re-organize the directory structure to make it at least a little more manageable (especially in regards to the font that will have all the glyphs).

I still haven't looked too far into it but it seems like using the GitHub API might be a way to do the packages per release as you mentioned.

**Comment by francoiscote** [comment]
Tip: Meanwhile, github's file search can help locate the right variation you are looking for:
https://github.com/ryanoasis/nerd-fonts/find/master

**Comment by ryanoasis** [comment]
@francoiscote Belated thank you! I will probably try to put that in at least the readme and possible in each main font directory's readme.rst

**Comment by ryanoasis** [comment]
Hey what do you guys think of this:

https://github.com/ryanoasis/nerd-fonts/releases/tag/v0.6.1

I only zipped and did an asset upload of the '3270' patched font to see how feasible this would be in a simple little script (looks pretty feasible!).

I don't think breaking these directory archives down much further would be much help.. MAYBE going down one more directory to 'complete','additional-variations', and 'minimal'.

Actually looks like this zip has all the emphasis variants (Medium, Narrow). Maybe ideally zips would be broken out such as:
* 3270 - Medium - complete
* 3270 - Medium - additional-variations
* 3270 - Medium - minimal
* 3270 - Narrow - complete
* 3270 - Narrow - additional-variations
* 3270 - Narrow - minimal

Actually I think with all of the fonts this is going to be TOO much, I think only 'complete' is useful for a zipped up ready to go solution:
* 3270 - Medium
* 3270 - Narrow

**Comment by ryanoasis** [comment]
Going to only build the 'complete' fonts by default going forward, so for the packaging will have one archive per font (e.g., one for 3270, one for Hack)

This will solve this issue _and_ #72 (**2** birds meeting **single** stone :smile:)

**Comment by ryanoasis** [comment]
This is working nicely right now :smile: https://github.com/ryanoasis/nerd-fonts/releases/tag/v0.8.0
