### ISSUE TITLE
When i run install.sh i get an error on line 212. Unexpected '<' sign in 'done < <(eval "$find_command")'

### ISSUE THREAD

**Issue by reidterror** [ryanoasis/nerd-fonts#320]
#### 🎯 Subject of the issue

When i run install.sh i get an error on line 212. Unexpected '<' sign in 'done < <(eval "$find_command")'

#### 🔧 Your Setup

- Copied the repository.
- termite
- manjaro

**Comment by ryanoasis** [comment]
Thanks for the report @reidterror 

I haven't run the install script in quiet some time.

**Comment by ryanoasis** [comment]
Can you tell us how you ran the install script? Was it just `./install.sh` ?

**Comment by reidterror** [comment]
> 
> 
> Can you tell us how you ran the install script? Was it just `./install.sh` ?

Hello, sorry for the late reply. Yes, ran into the issue by just running the script as it came.

**Comment by ryanoasis** [comment]
No worries and thanks again

**Comment by eclipseo** [comment]
Same issue here on Fedora linux. GNU bash, version 5.0.2(1)-release

**Comment by eclipseo** [comment]
Running it explicitely with bash solves this.

`bash install.sh --otf --use-single-width-glyphs --complete --install-to-user-path`

**Comment by ryanoasis** [comment]
My guess is something breaks in the scripts when running via Bourne shell (sh) and not Bash. I am guessing these distros here have a default shell that is not bash.

I am closing with @eclipseo workaround for now. Perhaps we can revisit the scripts to make them more posix compliant
