### ISSUE TITLE
font-patcher needs configparser

### ISSUE THREAD

**Issue by Flurrywinde** [ryanoasis/nerd-fonts#321]
#### 🎯 Subject of the issue

I am trying to use `font-patcher` on a font I already have. My `fontforge` is that latest version installed via `sudo apt install fontforge` on Ubuntu 18.04. (I also installed their repo, and it's the same version.) I put the `font-patcher` script in my path, and when I run it on the font, it reports: "Nerd Fonts: FontForge module is probably not installed."

Another issue said to rename `font-patcher` to `font-patcher.py` and execute `fontforge -script font-patcher.py <font file>`, but when I did this I got: "Nerd Fonts: configparser module is probably not installed. Try `pip install configparser` or equivalent"

So I did `pip install configparser` and though it installed fine, I still get the same error message. (I installed it in its own Anaconda sandbox.)

In `ipython`, `import psMat` gives a ModulesNotFoundError, but `import configparser` works.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
Inconsolata-dz-Powerline.otf
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
`gnome-terminal`
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Ubuntu 18.04

**Comment by errikos** [comment]
I think that the `font-patcher` script uses the system Python2 installation. Please try installing `configparser` via `apt`:

    sudo apt install python-configparser

**Comment by Flurrywinde** [comment]
This worked. Thank you! Unfortunately, it didn't work on the font I wanted it for: https://github.com/powerline/fonts/tree/master/InconsolataDz , but that is another issue. Thanks again.
