### ISSUE TITLE
Mono fonts lack spacing information in the metadata

### ISSUE THREAD

**Issue by resolritter** [ryanoasis/nerd-fonts#323]
#### 🎯 Subject of the issue

As reported in https://github.com/kovidgoyal/kitty/issues/1372, I'm unable to detect mono Nerd Fonts due to the missing 'spacing' attribute, which comes by default on system mono fonts. 

Example is the built-in Nimbus Mono Font Family:

```
        'nimbus mono l': [{
            'path': '/usr/share/fonts/type1/gsfonts/n022004l.pfb',
            'family': 'Nimbus Mono L',
            'style': 'Bold',
            'postscript_name': 'NimbusMonL-Bold',
            'weight': 200,
            'slant': 0,
            'index': 0,
            'scalable': True,
            'outline': True,
            'color': False,
            'spacing': 'MONO'
        }, {
            'path': '/usr/share/fonts/X11/Type1/n022023l.pfb',
            'family': 'Nimbus Mono L',
            'style': 'Regular Oblique',
            'postscript_name': 'NimbusMonL-ReguObli',
            'weight': 80,
            'slant': 110,
            'index': 0,
            'scalable': True,
            'outline': True,
            'color': False,
            'spacing': 'MONO'
        }, {
            'path': '/usr/share/fonts/type1/gsfonts/n022003l.pfb',
            'family': 'Nimbus Mono L',
            'style': 'Regular',
            'postscript_name': 'NimbusMonL-Regu',
            'weight': 80,
            'slant': 0,
            'index': 0,
            'scalable': True,
            'outline': True,
            'color': False,
            'spacing': 'MONO'
        }, {
            'path': '/usr/share/fonts/type1/gsfonts/n022024l.pfb',
            'family': 'Nimbus Mono L',
            'style': 'Bold Oblique',
            'postscript_name': 'NimbusMonL-BoldObli',
            'weight': 200,
            'slant': 110,
            'index': 0,
            'scalable': True,
            'outline': True,
            'color': False
        }, {
            'path': '/usr/share/fonts/X11/Type1/n022024l.pfb',
            'family': 'Nimbus Mono L',
            'style': 'Bold Oblique',
            'postscript_name': 'NimbusMonL-BoldObli',
            'weight': 200,
            'slant': 110,
            'index': 0,
            'scalable': True,
            'outline': True,
            'color': False
        }, {
            'path': '/usr/share/fonts/X11/Type1/n022003l.pfb',
            'family': 'Nimbus Mono L',
            'style': 'Regular',
            'postscript_name': 'NimbusMonL-Regu',
            'weight': 80,
            'slant': 0,
            'index': 0,
            'scalable': True,
            'outline': True,
            'color': False,
            'spacing': 'MONO'
        }, {
            'path': '/usr/share/fonts/type1/gsfonts/n022023l.pfb',
            'family': 'Nimbus Mono L',
            'style': 'Regular Oblique',
            'postscript_name': 'NimbusMonL-ReguObli',
            'weight': 80,
            'slant': 110,
            'index': 0,
            'scalable': True,
            'outline': True,
            'color': False,
            'spacing': 'MONO'
        }, {
            'path': '/usr/share/fonts/X11/Type1/n022004l.pfb',
            'family': 'Nimbus Mono L',
            'style': 'Bold',
            'postscript_name': 'NimbusMonL-Bold',
            'weight': 200,
            'slant': 0,
            'index': 0,
            'scalable': True,
            'outline': True,
            'color': False,
            'spacing': 'MONO'
        }],
```

While I suggested crude a workaround on the Kitty's side, it would be more appropriate for this to be fixed here.

**Comment by ryanoasis** [comment]
Thanks @reaysawa this is useful info! Upon a cursory look into fontforge python I am not seeing info on the 'spacing'. Need to look more..

**Comment by reaysawa** [comment]
I was recently able to find about something important about this!

Apparently **spacing is not a metadata field**, but a computed value specific to fontconfig.

Here's a similar issue risen in a Google Fonts' repository:
https://github.com/googlefonts/noto-fonts/issues/1128

Here's the function where it's computed:
https://github.com/behdad/fontconfig/blob/a8a6efa805fc03e790214e8a0bc55843a258d774/src/fcfreetype.c#L2348-L2415

As per [this comment from the maintainers](https://github.com/googlefonts/noto-fonts/issues/1128#issuecomment-409765692), the font doesn't get classified as "monospaced" if a single glyph deviates from the width number necessary to make `num_advances` go above 1; setting the same width for **all** glyphs (equal to some threshold which can be observed from fontconfig's code) will make fonts be correctly detected as monospaced by terminals using it.

[Linked commit](https://github.com/leogr/nerd-fonts/commit/c736714f007b772e46c46c6c7c2016adfcd51bc8#diff-3b192ccaec850d73e6540b7eddd8b50cR697) from a fork which indiscriminately sets the same width value for all glyphs. Unsure if it fixes the issue or if it has unwarranted side-effects.

Let me know if I can help!

**Comment by duganchen** [comment]
It's the fontawesome icons that break it. I'm using the fontpatcher to patch the OTF version of IBM Plex Mono 5.1.3. This works (syntax is FISH):

    for otf in OpenType/IBM-Plex-Mono/*.otf
          ./font-patcher --fontawesomeextension --fontlinux --octicons --powersymbols --pomicons --powerline --powerlineextra --material --mono --weather --out ~/.local/share/fonts/IBM-Plex-Mono-5.1.3/ $otf
    end

The minute I add --fontawesome to that command-line, the results stop showing up in "kitty list-fonts".

**Comment by resolritter** [comment]
The "real" pain related to this is explained in #268 ; in other words, because this "metadata" field is missing, Kitty was not able to find the fonts for me.

I'll close this issue in favor of #268.
