### ISSUE TITLE
Add general purpose advance indicator icons

### ISSUE THREAD

**Issue by memeplex** [ryanoasis/nerd-fonts#324]
Some time ago [I've requested](https://github.com/Templarian/MaterialDesign/issues/3334) a general purpose advance indicator icons and this guy kindly contributed a wonderful set which is available at https://materialdesignicons.com/contributor/SarinManS.

Could you please add them to nerd fonts?

**Comment by memeplex** [comment]
This may be closed in favor of the more general https://github.com/ryanoasis/nerd-fonts/issues/325

**Comment by ryanoasis** [comment]
Thanks again. TBD

**Comment by ryanoasis** [comment]
Catching up, yeah I think let's close this issue in favor of #325
