### ISSUE TITLE
Update MDI to v3.4.93 (about 1400 extra icons!)

### ISSUE THREAD

**Issue by memeplex** [ryanoasis/nerd-fonts#325]
Please read this comment: https://github.com/Templarian/MaterialDesign/issues/3334#issuecomment-462750727.

Also related: https://github.com/ryanoasis/nerd-fonts/issues/324

**Comment by ryanoasis** [comment]
Thanks @memeplex . On the radar..

**Comment by Finii** [comment]
Fixed with #773
