### ISSUE TITLE
New font: iA Writer

### ISSUE THREAD

**Issue by xasx** [ryanoasis/nerd-fonts#326]
There's a beautiful free font out there, called iA Writer Mono.

See: https://github.com/iaolo/iA-Fonts

Would probably be nice to have it officially supported as a NerdFont :heart_decoration:

**Comment by xasx** [comment]
After trying the font-patcher myself, it turns out that the left-pointing triangles on the right side are not quite proper as with other fonts.

![bildschirmfoto von 2019-02-18 16-49-50](https://user-images.githubusercontent.com/1582730/52962379-66421680-339d-11e9-94d0-a072437fe5b8.png)

Let me know what you think about the font.

**Comment by purrloftruth** [comment]
I'm unsure if the patcher/glyphs provided by this project support variable fonts, but if they do, it'd be really cool if the variable version of this font could be made available in a patched form, too.

**Comment by ryanoasis** [comment]
I'm ready to just add all the variants as is and sort out any issues as a follow-up :smiling_imp: 

One current issue though is the RFN of "iA Writer" so we need another name.

Maybe `iA writere` or `iA wryter` or ?

**Comment by purrloftruth** [comment]
...these might be a bit on the nose, but...

“iC Writing”
“iM Typing”

or something along those lines? (If pun-like things are acceptable.)

**Comment by ryanoasis** [comment]
puns are definitely acceptable. I like something like `iM Writing` because it is _close_ to the original name

**Comment by xasx** [comment]
@purrloftruth @ryanoasis I also like `iM Writing` is somehow the merge of both your insane brains :laughing:

**Comment by ryanoasis** [comment]
I think we can only patch the static fonts (not the variable ones) since FontForge looks not support it, well at least the OpenType version/spec of it. Let's see.

**Comment by hackedWifi** [comment]
I found this font to be beautiful. But why is every character so space out? I had to modify the kitty conf to get the font's width narrow.

**Comment by ryanoasis** [comment]
@hackedWifi Not sure on that but good to know.

Closing because completed: source uploaded and patched. To be included in next release.

**Comment by hackedWifi** [comment]
Is there a way to get a notification when the iA Writer repo gets updated.
