### ISSUE TITLE
Switch to Source Code Pro instead of Sauce Code

### ISSUE THREAD

**Issue by beojan** [ryanoasis/nerd-fonts#33]
Can you switch to the original Source Code Pro instead of Sauce Code. Adobe appear to have designed the powerline symbols into the recent version of Source Code Pro.

**Comment by ryanoasis** [comment]
Thanks I will take a look. I think I had wanted to patch the latest from Adobe but it required tools to build the latest font styles. I did start installing some of the reqquirements but didn't get past the dependencies.

**Comment by johnpneumann** [comment]
:+1:
