### ISSUE TITLE
Please add DaddyTimeMono

### ISSUE THREAD

**Issue by dan-and** [ryanoasis/nerd-fonts#330]
Hi,

I asked the author of DaddyTimeMono if he would be fine adding the glyphs as done here. He suggested adding his font here. See: https://github.com/BourgeoisBear/DaddyTimeMono/issues/1 

You can get DaddyTimeMono here:  https://github.com/BourgeoisBear/DaddyTimeMono

A preview of it can be seen here:
https://raw.githubusercontent.com/BourgeoisBear/DaddyTimeMono/master/DaddyTimeMono-sample.gif

Thanks and keep up the great work :-)

**Comment by ryanoasis** [comment]
Interesting, to look into. Thank you

**Comment by ryanoasis** [comment]
Closing because completed: source uploaded and patched. To be included in next release.
