### ISSUE TITLE
Problems patching impallari raleway

### ISSUE THREAD

**Issue by mainrs** [ryanoasis/nerd-fonts#334]
__Font:__ ttf-impallari-raleway-family (aur)
__Terminal Emulator:__ kitty
__Actually component using font:__ i3blocks

I am currently trying to patch the Raleway font so I can use it for my i3blocks setup. It patches successfully but displays multiple errors while doing so. Some Glyphs are not patched at the correct code point. For example, using the mute icon from fontawesome gets displayed as a half-full glass on my system.

Here is the output of the font patcher process (`./font-patcher /path/to/Raleway-Regular.ttf -c`):
https://gist.github.com/SirWindfield/5eb38ff947435549321336a55cf53dbc

**Comment by ryanoasis** [comment]
Thanks. Most of those errors are not to do with Nerd Fonts but from FontForge and I wasn't able to find a way to quite the output yet and didn't really look into it much.

**Comment by Finii** [comment]
Unfortunately the gist is gone.

I assume this is fixed with the latest patcher version. Please reopen if not.
