### ISSUE TITLE
Request: CamingoCode

### ISSUE THREAD

**Issue by FFY00** [ryanoasis/nerd-fonts#335]
#### 🎯 Subject of the issue

I would like to know if it would be possible to add CamingoCode and make it powerline compatible :grin:, thank you.

**Comment by ryanoasis** [comment]
Thanks for the request though! Interesting license: Creative Commons Attribution-No Derivative Works v3.00

**Comment by FFY00** [comment]
Yeah, it's a shame we can make any derivation :confused:.
