### ISSUE TITLE
Font loses boldness on patching

### ISSUE THREAD

**Issue by FFY00** [ryanoasis/nerd-fonts#336]
#### 🎯 Subject of the issue

When I patch CamingoCode it loses the slight bold it has.

- Before
![camingocode-before](https://user-images.githubusercontent.com/11718923/54518298-d5d70180-495b-11e9-96b9-038ebc5e9130.png)

- After
![camingocode-after](https://user-images.githubusercontent.com/11718923/54518313-da031f00-495b-11e9-9ee6-2d93e641ef31.png)

#### 🔧 Your Setup

- Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)? CamingoCode
- Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)? I tried Tilix and Terminator, urxvt is being weird but I think that's because it isn't properly picking up the font.
- Are you using OS X, Linux or Windows? And which specific version or distribution? Archlinux

**Comment by FFY00** [comment]
I just remembered this might be the antialiasing working but it's strange it doesn't get triggered when the font is added. When I get home I'll confirm this.

**Comment by Finii** [comment]
Sorry to hear of your problems.
Are they still current?
Do you have a link to that font?

Probably outdated, so I will close, please reopen if need be.
