### ISSUE TITLE
FuraCode font incorrectly formatting JavaScript spread operator `...` to `?.`

### ISSUE THREAD

**Issue by ctaylo21** [ryanoasis/nerd-fonts#337]
#### 🎯 FuraCode font incorrectly formatting JavaScript spread operator `...` to `?.`

The normal Fira code font will correctly format the `spread` operator in JS:
![image](https://user-images.githubusercontent.com/1427469/54548636-8f86a000-4965-11e9-8f81-6884c03be741.png)

This is what it looks like in the patched font:

![image](https://user-images.githubusercontent.com/1427469/54548589-7847b280-4965-11e9-85de-726594e92436.png)

#### 🔧 Your Setup

- 12pt Fura Code Regular Nerd Font Complete Mono
- iterm2
- macOS Mojave

**Comment by ryanoasis** [comment]
Thanks. Seems like a ligature issue

**Comment by ahrjarrett** [comment]
Same issue.

Size and weight don't affect it and it seems like it might occur on any client where

1. a Fura* font is used, and
2. ligatures are enabled

Examples in iTerm2 and OS X Terminal:
 
<img width="891" alt="Screen Shot 2019-04-25 at 9 29 27 PM" src="https://user-images.githubusercontent.com/15133992/56779627-6f869f80-67a1-11e9-9c9f-09c456ff9927.png">

**Comment by ahrjarrett** [comment]
Never mind, it looks like it only affects **FuraCode Nerd Font Mono**, and does not occur with any FuraMono* or FuraCode Nerd Font

**Comment by Finii** [comment]
I remember I fixed this specific bug somewhen. Should be fixed in 2.3.3
