### ISSUE TITLE
Padding broken for Hurmit on vte terminals after freetype2 update to 2.10.0

### ISSUE THREAD

**Issue by avrelaun** [ryanoasis/nerd-fonts#338]
#### 🎯 Subject of the issue

Fonts are broken in vte-based terminals after updating freetype2 from 2.9.2 to 2.10.0 in archlinux.

#### 🔧 Your Setup

Archlinux
Sway
Germinal / Termite (broken in both, both based on VTE)
Hermut font
Zsh
Powerlevel9k theme

Before (expected):
![nice-font](https://user-images.githubusercontent.com/412102/54685516-4aa26b00-4b17-11e9-81d2-00c190859a71.png)

After (broken):
![broken-font](https://user-images.githubusercontent.com/412102/54685306-ccde5f80-4b16-11e9-8f6e-2286819f0278.png)

**Comment by avrelaun** [comment]
I created a VTE issue also:
https://gitlab.gnome.org/GNOME/vte/issues/101

**Comment by avrelaun** [comment]
The bug is not present using Hermit, the original font, and VTE people confirm this is not a VTE issue.
This is definitely some problem during the font patching process which is broken.

**Comment by avrelaun** [comment]
This seems to concern Hurmit/Hermut only... tried several others Nerd Fonts but they work.

**Comment by omeryagmurlu** [comment]
I'm having this same issue on windows terminal also

**Comment by Finii** [comment]
Should be fixed by
* #1060
