### ISSUE TITLE
Patched font missing characters normally present

### ISSUE THREAD

**Issue by sudobash1** [ryanoasis/nerd-fonts#339]
#### 🎯 Subject of the issue

There seem to be missing characters in patched fonts which normally have those characters. *(Edit: Seems to be terminal specific)*

#### 🔧 Your Setup

**font:** BitstreamVeraSansMono Nerd Font Mono (also tested on Bitstream Vera Sans Mono and DroidSansMono Nerd Font Mono)
**term:** XTerm
**OS:** Linux (Ubuntu 16.04)

*(Edit: I also tested with gnome-terminal and everything works there)*

#### ★ Example

For example the [white circle character ○](https://graphemica.com/%E2%97%8B) is normally renderable in `Bitstream Vera Sans Mono`:

![circle_char](https://user-images.githubusercontent.com/1923776/54849223-dabfec00-4ca0-11e9-89ea-70812b97dde2.png)

But when I install and start to use the Nerd Font patched version (downloaded, ready patched, from github) I see the unknown character square:

![missing_char](https://user-images.githubusercontent.com/1923776/54849321-1d81c400-4ca1-11e9-9ddd-4605eefa5735.png)

I have also tested this in `Inconsolata Nerd Font Mono` and `DroidSansMono Nerd Font Mono`. Neither have the white circle character.

All the Nerd Font characters that I have tried show up fine, but some applications that I use (which don't allow character customization) are expecting common utf8 symbols, but they show as rectangles.

I tried the `test-fonts.sh` script, and it produced output like this:

![image](https://user-images.githubusercontent.com/1923776/54849563-e52eb580-4ca1-11e9-8aaa-60e9ccdfaa54.png)

The double line characters do not show. (However, I use `tmux` and it draws the single line characters just fine with the Nerd Font)

**Comment by ryanoasis** [comment]
Interesting and thanks for opening the issue!

**Comment by sudobash1** [comment]
Since my other box is an Manjaro one, I found that this is an issue only in some versions of XTerm. This is the behavior until version [326](https://invisible-island.net/xterm/xterm.log.html#xterm_326). At that point, the "missing" characters do not display at all. Then starting at version [338](https://invisible-island.net/xterm/xterm.log.html#xterm_338) the "missing" unicode characters work.

I looked through the XTerm changelog and found in version 338 the line:

> add fallback support in Xft configuration for missing glyphs

It looks like this might be what "fixed" the issue, but I don't know for sure where the fundamental issue lies. But that is enough digging for me.

So the conclusion is to use XTerm version 338 (released 2018/12/09) or higher. Unfortunately, except for Arch (and friends) this is a pretty recent release, so you may need to compile from source.
