### ISSUE TITLE
Some Powerline symbols are not shown in Source Code Pro

### ISSUE THREAD

**Issue by mumuxijili** [ryanoasis/nerd-fonts#341]
Hi, thanks for doing this fantastic project!
However, I find some problems when I'm using the Source Code Pro font family. Some symbols are not shown, like ≣(U+2263) and ≢(U+2262). 
![image](https://user-images.githubusercontent.com/19302304/55600776-2dfd6880-5790-11e9-9aed-b8cb653239f5.png)
I'm using powershell on ConEmu, and this are my settings:
![image](https://user-images.githubusercontent.com/19302304/55601277-c268ca80-5792-11e9-9a20-11acd57f349b.png)
And if I change font to other NF font, like DejaVu, these symbols will be rendered correctly.
Is this a Source Code Pro problem or my setting problem? Hope you can help me solve this problem.
Thanks again!

My environments are:
OS: Windows 10(10.0.17763.379)
Terminal: Powershell(5.1.17763.316), ConEmu x64(190331)
Software: posh-git(0.7.3), oh-my-posh(2.0.249)
Nerd Font: Source Code Pro(v2.0.0)

**Comment by ryanoasis** [comment]
Thank you @mumuxijili and for the details here.

Looking into this, those glyphs are missing in the original (un patched) SourceCodePro we are using.

This is an upstream issue: https://github.com/adobe-fonts/source-code-pro/issues/49

In the future we could add patching to fix 'missing' symbols but currently that is beyond the scope of this project.

Closing for now, but open to suggestions. Thanks.
