### ISSUE TITLE
[Request] icons for Emacs, elisp and orgmode

### ISSUE THREAD

**Issue by twlz0ne** [ryanoasis/nerd-fonts#342]
#### 🎯 Subject of the issue

It will be great for Emacs user.

- https://www.gnu.org/software/emacs/
- https://en.wikipedia.org/wiki/Emacs_Lisp
- https://orgmode.org

Some icons:

- https://commons.wikimedia.org/wiki/File:EmacsIcon.svg
- https://www.emacswiki.org/emacs/EmacsIcons

**Comment by evaryont** [comment]
Do you know of a font that already includes these?

**Comment by twlz0ne** [comment]
I know https://github.com/file-icons/source

![](https://raw.githubusercontent.com/file-icons/atom/6714706f268e257100e03c9eb52819cb97ad570b/preview.png)

Maybe Emacs & elisp could share one icon, I see all-the-icons did this:

https://github.com/domtronn/all-the-icons.el/blob/52d1f2d36468146c93aaf11399f581401a233306/data/data-fileicons.el#L135-L136

**Comment by 06kellyjac** [comment]
Adding file-icons to nerd-fonts would also fix issue #351 & help me out with a couple icons I need like: yaml, toml, terraform, vagrant

**Comment by dylanjm** [comment]
I'm dying to have this added. I can't quite seem to get the font-patcher script to work so I can simply have an emacs icon for all my .el files. File-icons is the way to go.

**Comment by seagle0128** [comment]
@dylanjm FYI. `file-icons` are compiled into  https://github.com/sebastiencs/icons-in-terminal with some scripts.

**Comment by VentGrey** [comment]
Any news on this issue? :thinking:

**Comment by seagle0128** [comment]
ping kindly...

**Comment by Finii** [comment]
I looked a bit into `file-icons`.

They have a font that we could probably ingest.
That font has not-changing codepoints per icon (:+1:).

But ... the icons are not (all) in a contiguous area:
There is a big block from `e700` - `ebb7`, but about 100 in the range below (like on '`a`' :unamused:) and 100 above, for example in the `1f000` pane, but extremely scattered.

If WE want to incorporate them, and at stable codepoints, we need to come up with our own, packed mapping. Which is possible, but do we want that? (And then we could work with the `svn` directly anyhow.)

**Comment by seagle0128** [comment]
@Finii Thank you for the detailed explanations! So how about simple icons which mentioned in https://github.com/ryanoasis/nerd-fonts/discussions/818 ? Or, just add the emacs icon listed by @twlz0ne above?

**Comment by Finii** [comment]
@seagle0128 The simple icons are even more icons. Adding just some hand selected glyphs would also be possible (and easy), but then ... maybe everyone comes up with a symbol or another - not sure that is a way we want to go. Nerd Font is an aggregator and that is not really font aggregating.

I think decisions on this (adding new sets, codepoints to use) is beyond my field of work. I can do technical stuff here, and even implement new icon sets etc pp; but the **if** and **where** - I feel that belongs solely to @ryanoasis.

I will add this to the appropriate discussion, and then we need to see
