### ISSUE TITLE
How can i chage the symbol size?

### ISSUE THREAD

**Issue by taigacute** [ryanoasis/nerd-fonts#343]
#### 🎯 Subject of the issue

how can i change these icon size? only change font size?

#### 🔧 Your Setup

-   sauce code pro nerd font completed
-  iterm 2
- mac os 10.13.6

#### ★ Optional

you can this pic . these symbol seems too small in this pic .
![123](https://user-images.githubusercontent.com/41671631/55678767-96d01680-5931-11e9-9d10-9eb754c5d2ef.png)

**Comment by layoaster** [comment]
I'm also seeing that symbols are really small after migration from the standalone version of the awesome-font. 

I'm using Hack 15pt

**Comment by ryanoasis** [comment]
Unfortunately you cannot without changing the font size. The mono fonts typically have a smaller glyph so the double width (non mono) is going to give you the largest glyphs possible.

Per your pic those sizes seem reasonable given the font size.

Please re-open if I misunderstood.
