### ISSUE TITLE
Update to Liberation 2.00.5

### ISSUE THREAD

**Issue by markuspeloquin** [ryanoasis/nerd-fonts#344]
#### 🎯 Subject of the issue

Liberation is my favorite monospace font. You include a patched version of 2.00.1, but 2.00.5 is released. The main thing I notice is that `l` no longer has a flat bottom (like an upside-down `T`), but curves to the right (like a backward `j`), making it more dissimilar from `1`. This was a part of the 2.00.4 release. Here's its commit: https://github.com/liberationfonts/liberation-fonts/commit/3714df3687c0229c8c894122b8a2ef82d1528515

#### 🔧 Your Setup

Note that I haven't used the font yet. I will patch the 2.00.5 release and use that.

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ Liberation
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ WSL
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Windows 10

**Comment by ryanoasis** [comment]
Thanks

**Comment by ryanoasis** [comment]
still latest as of now
