### ISSUE TITLE
To use a new PUA?

### ISSUE THREAD

**Issue by fabrizioschiavi** [ryanoasis/nerd-fonts#346]
Hello Ryan,
could I suggest you to move all the glyphs of the Nerd Fonts into the “new” U+F0000..U+FFFFD [PUA](http://www.unicode.org/faq/private_use.html)?

This request is just to avoid conflicts like this:

Fura:
![Screen Shot 2019-04-08 at 13 24 54](https://user-images.githubusercontent.com/1576663/55720726-cfd7bc00-5a01-11e9-851e-939835d7a525.png)

PragmataPro:
![Screen Shot 2019-04-08 at 13 25 19](https://user-images.githubusercontent.com/1576663/55720732-d2d2ac80-5a01-11e9-9507-c85a7bb11951.png)

In this area there are some important glyphs necessary for Hebrew and Arabic texts, not only in [PragmataPro](https://www.fsd.it/shop/fonts/pragmatapro/) but in every other big font family like Arial, Lucida, DejaVu etc.

I love to use your idea in my fonts but it's necessary to find a new empty area to avoid conflicts. 
All the best!

**Comment by ryanoasis** [comment]
Thanks @fabrizioschiavi I think this is something we will eventually have to do unfortunately. Perhaps next major version (3+)

**Comment by ryanoasis** [comment]
There are some good suggestions and discussion around the conflicts done here: #365 just to link the issues

**Comment by Finii** [comment]
With `v2.3.0` we started the transition to codepoints `F0000` according to plan 5+ of #365.

With `v3.0.0` the offending codepoints will be dropped.

Closing this already now, as everything is prepared and just waits for rollout.
