### ISSUE TITLE
MPlus makes Gnome shell text hard to read on Disco Dingo

### ISSUE THREAD

**Issue by dermalikmann** [ryanoasis/nerd-fonts#348]
#### 🎯 Subject of the issue

:warning: This is also an issue with [vinceliuice/matcha](https://github.com/vinceliuice/matcha)

As soon as I install it, all text in my Gnome shell increases its whitespace to a almoust ridicilous amount. Please view these screenshots for reference.

#### 🔧 Your Setup

- Ubuntu 19.04 Disco Dingo
- matcha version of 07-05-2019
- Current Nerd-Fonts (git clone on 07-05-2019)

> I already created an issue over at matcha's repo vinceliuice/matcha#65

#### ★ Screenshots

![Bildschirmfoto von 2019-05-07 15-36-42](https://user-images.githubusercontent.com/3097625/57304443-a6cd4880-70df-11e9-9bab-7be6930db290.png)
![Bildschirmfoto von 2019-05-07 15-36-59](https://user-images.githubusercontent.com/3097625/57304444-a6cd4880-70df-11e9-81d4-f47089b9c257.png)

**Comment by ryanoasis** [comment]
Thanks for the report, upon reading https://github.com/vinceliuice/matcha/issues/65 it seems to point to an issue with the patched font

**Comment by Finii** [comment]
The fonts should be fixed with #1045 'family' of PRs.
