### ISSUE TITLE
Can anybody provide a simple tutorial of how to add symbols into fonts

### ISSUE THREAD

**Issue by mudox** [ryanoasis/nerd-fonts#35]
or same references is well appreciated.

**Comment by ryanoasis** [comment]
The symbols provided by Nerd Fonts or you mean in general?

For Nerd Fonts you can use the patcher:
```
./font-patcher Inconsolata.otf
```

**Comment by mudox** [comment]
@ryanoasis, thanks for you response. I will look into it.
Actually I wanted to add symbols in range 0xe0b0 ~ 0xe0cd from [powerline-extra-symbols](https://github.com/ryanoasis/powerline-extra-symbols) into my chosen font.

**Comment by ryanoasis** [comment]
Ah those symbols. I am actually targeting to add those symbols into the next minor release [v0.6.0](https://github.com/ryanoasis/nerd-fonts/milestones/v0.6.0)

ref: #30

**Comment by mudox** [comment]
:+1:

**Comment by ryanoasis** [comment]
relates to #30
