### ISSUE TITLE
Terminus missing PSF patch

### ISSUE THREAD

**Issue by tecosaur** [ryanoasis/nerd-fonts#350]
I think this can be kept short and sweet.

The Terminus PSF patch font files seem to be missing (Useful for tty).
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Terminus/PSF

Thanks,

tecosaur.

**Comment by ryanoasis** [comment]
I think ttf is only there because the current patcher doesn't know how to patch the other types (bitmap fonts)

**Comment by Luxcium** [comment]
is this relevant to that discussion or I might be lost ...
[r/Any way to convert ttf files to psf files](https://www.reddit.com/r/linuxquestions/comments/7st7hz/any_way_to_convert_ttf_files_to_psf_files/)

`otf2bdf -p 20 -r 96 -o font.bdf font.ttf`
Play with -p parameter to change glyph size. Then convert bdf to psf:

`bdf2psf --fb font.bdf /usr/share/bdf2psf/standard.equivalents /usr/share/bdf2psf/fontsets/Uni2.512 512 font.psf`
You can use another fontset or even copy and modify an existing one to add glyphs for characters you want to see in TTY. For example, I like radioactive sign, so I've appended U+2666 to the font set file.

If bdf2psf complains for 'width is not integer number', either change glyph size or just replace AVERAGE_WIDTH in the bdf file (it's a plain text) to something round. e.g. if it is 139, change it to 140 and so on.

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
