### ISSUE TITLE
Request: icons for Common Lisp, Scheme, Guile

### ISSUE THREAD

**Issue by martinflack** [ryanoasis/nerd-fonts#351]
#### 🗹 Requirements

- [ ] A brief but descriptive _title_ of your issue
- [ ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [ ] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ ] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

It would be great to have icons for Common Lisp, Scheme, and Guile. Below are example icons from file-icons.

https://github.com/file-icons/source/blob/master/svg/Common-Lisp.svg
https://github.com/file-icons/source/blob/master/svg/Scheme.svg

I'm not sure about an example Guile entry in another font but the guilelang twitter handle has a logo that is suitably framed: https://twitter.com/guilelang

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_

**Comment by ryanoasis** [comment]
Thanks

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
