### ISSUE TITLE
Fira Code

### ISSUE THREAD

**Issue by ShalokShalom** [ryanoasis/nerd-fonts#352]
Hi there :D

The developer of the awesome font 'Fira Code' allows us the usage of the correct name:

https://github.com/tonsky/FiraCode/issues/767#issuecomment-495163622

**Comment by ryanoasis** [comment]
Great. Either I didn't realize the license had no RFN specified or it was updated some time back.. I think I just assumed it was reserved and error-ed on the safe side

**Comment by ShalokShalom** [comment]
Sure sure. So I can close this issue? Is there already a PR?

**Comment by ShalokShalom** [comment]
I did it for the Readme, already done on the homepage. Closing :hugs:
