### ISSUE TITLE
Request:  Ryan... sign up for Github Sponsor asap

### ISSUE THREAD

**Issue by brennanfee** [ryanoasis/nerd-fonts#353]
Hey Ryan,

GitHub released recently a sponsor program for developers and projects.  Please get yourself signed up to GitHub Sponsor ASAP. I for sure would like to financially support your work and my guess is that lots of others would as well.

GitHub is promising 100% matching funds for the first year (up to $5,000 per developer\project).

**Comment by ryanoasis** [comment]
Thanks for the notice @brennanfee . I wasn't even aware of the program.

Signed up, let's see what happens :man_shrugging:

**Comment by brennanfee** [comment]
Excellent.  I know there is a long waiting list so it may take a little while for you to get approved.  Also, now that it looks like you will be moving things to an organization, make sure to sign that organization up as well.

It may not amount to much $ but I am sure there are many of us (myself included) that would love to support you and the team financially as well as "in spirit".  On the other hand, it might lead to enough regular income that you could work on Nerd Fonts full time... who knows.
