### ISSUE TITLE
Request:support new powerline symbol

### ISSUE THREAD

**Issue by glepnir** [ryanoasis/nerd-fonts#360]
##  Request
@ryanoasis  Hi!
can support some symbol, i make a vim statusline plugin like spacemacs called [spaceline.vim](https://github.com/taigacute/spaceline.vim).but i found the nerdfonts only have these 3 symbols.so can add another symbols support? thanks for your work

![1](https://user-images.githubusercontent.com/41671631/60563554-de2e3d80-9d8e-11e9-88a1-2a5795382d3f.png)

**Comment by ryanoasis** [comment]
Thanks @taigacute

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
