### ISSUE TITLE
MesloLGM Nerd Font no ligatures in VSCode

### ISSUE THREAD

**Issue by ksawerykarwacki** [ryanoasis/nerd-fonts#367]
I downloaded two fonts: **MesloLGM Nerd Font** & **MesloLGM Nerd Font Mono** and set regular version as my editor font in VSCode and Mono version for my terminal within VSCode. I also enabled ligatures in editor. This should show ligatures within editor. But I cannot force editor to show ligatures. Is the font broken? Are those two fonts overlap?

**Comment by ryanoasis** [comment]
@ksawerykarwacki Thanks for the report. Does the unpatched version of Meslo (https://github.com/ryanoasis/nerd-fonts/tree/master/src/unpatched-fonts/Meslo) work and show ligatures for you?

**Comment by ksawerykarwacki** [comment]
@ryanoasis sorry for false alarm, but it seems that this font never supported ligatures in the first place. I'm closing as this was never an issue.

**Comment by ryanoasis** [comment]
@ksawerykarwacki Thanks for confirming and following up!
