### ISSUE TITLE
Make patched-fonts different project

### ISSUE THREAD

**Issue by rathod-sahaab** [ryanoasis/nerd-fonts#368]
#### 🎯 Subject of the issue
Make patched-fonts different project this would help

Those who just want the tool for patching there fonts should be able to avoid downloading and tracking each an every font
Also separating tool from fonts would provide better (more relatable) commit logs
Some-thing done with [vim-airline](https://github.com/vim-airline/vim-airline)  and [vim-airline-themes](https://github.com/vim-airline/vim-airline-themes)

**Comment by ryanoasis** [comment]
Thanks for the suggestion @rathod-sahaab 

You have good timing actually because this now more seriously underway, see ticket #67 and feel free to follow along or have suggestions there. 

I am going to close this ticket because of #67 already tracking this

Also related: #73
