### ISSUE TITLE
Add Microsoft Cascadia Code Nerd-fonts?

### ISSUE THREAD

**Issue by thuandt** [ryanoasis/nerd-fonts#373]
Microsoft releases new coding fonts for Windows Terminal here: https://github.com/microsoft/cascadia-code

Can we have Cascadia Code nerd-fonts?

**Comment by AaronFriel** [comment]
I've created a bare patched (no options to font-patcher) and a `--powerline --complete` version of Cascadia Code here: https://github.com/AaronFriel/nerd-fonts/releases/tag/v1.2.0

**Comment by AaronFriel** [comment]
@DHowett-MSFT good to know, I pinged the program manager and asked her for a suggested alternate name or a grant to use the name per the license.

**Comment by chenjuntong** [comment]
> I've created a bare patched (no options to font-patcher) and a `--powerline --complete` version of Cascadia Code here: https://github.com/AaronFriel/nerd-fonts/releases/tag/v1.2.0

Thanks so much! I love it!

**Comment by SandHilt** [comment]
> I've created a bare patched (no options to font-patcher) and a `--powerline --complete` version of Cascadia Code here: https://github.com/AaronFriel/nerd-fonts/releases/tag/v1.2.0

We need add this suggestion to main site: https://www.nerdfonts.com/

**Comment by ryanoasis** [comment]
@AaronFriel Nice, and that was quick. I do wonder about the license though, being that "Cascadia Code" is a reserved font name

**Comment by LuanVSO** [comment]
why every patched version of the font missing characters like:"ç" and "é"?

**Comment by DHowett-MSFT** [comment]
You’ll have to take that up with the distributors of the patched versions. If I had to guess, it’s because they are at least one major release out of date.

**Comment by LuanVSO** [comment]
just did it myself with the updated version of the font. plus there is no alignment issues

**Comment by LuanVSO** [comment]
just patched it without spacing issues with glyphs or ligatures.+all the new characters [https://www.github.com/LuanVSO/cascadianCodeNF/releases](url)

**Comment by ryanoasis** [comment]
I thought about something like `Kaskadia` but I think I'd like to go with @jmickey's suggestion of `Caskaydia` :smile:
1) Very close to original name, especially when sorting
2) Has enough difference to comply with the Reserved Font Name

:man_shrugging:

**Comment by aaronbell** [comment]
@ryanoasis Out of interest, when are you planning to re-work the Nerd Fonts set to move everything to PUA?

**Comment by ryanoasis** [comment]
closed via https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.1.0
