### ISSUE TITLE
The symbol '〉' can not display in powershell

### ISSUE THREAD

**Issue by zbttl** [ryanoasis/nerd-fonts#375]
Thanks for your fantastic work.
But when I use the patched fonts in powershell, I find a symbol can't work well.
![image](https://user-images.githubusercontent.com/22035093/65380883-b3adaa00-dd17-11e9-802f-793329b6f352.png)
But it can work on Windows terminal and terminus.
![image](https://user-images.githubusercontent.com/22035093/65380885-be683f00-dd17-11e9-9fcd-329b6619c9be.png)
![image](https://user-images.githubusercontent.com/22035093/65380916-169f4100-dd18-11e9-8ad4-f2943026c103.png)
and I try to change font like [Sarasa-Gothic](https://github.com/be5invis/Sarasa-Gothic) which stand by powerline, it works well.
![image](https://user-images.githubusercontent.com/22035093/65380940-bd83dd00-dd18-11e9-96b4-67aebe8472c7.png)

My environments are:
OS: Windows 10(10.0.18362.356)
Terminal: Powershell(5.1.18362.145), windows terminal, terminus(1.0.91)
Software: posh-git(1.0.0-beta3), oh-my-posh(2.0.311)
Nerd Font: Cascadia Code Nerd Font Complete, Noto Mono Nerd Font Complete Mono Windows Compatible

**Comment by ryanoasis** [comment]
@zbttl Thanks for the report and screenshots, it's very helpful. :smile: 

I don't know when I'll have time to look into this.

**Comment by ViceIce** [comment]
Seeing missing glyphs too for `CascadiaCode`
![image](https://user-images.githubusercontent.com/1798109/74141000-6e224880-4bf6-11ea-8dc5-dab3beca571f.png)

**Comment by ViceIce** [comment]
*Windows Terminal*
![image](https://user-images.githubusercontent.com/1798109/74141101-98740600-4bf6-11ea-9d13-721a1b0182c6.png)

**Comment by zbttl** [comment]
I found a tamporary solution.
Finding the path in regdit
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink
```
and create a Multi-string value named `CascadiaCode Nerd font`, changing this value to
```
MSYH.TTC,Microsoft YaHei UI,154,115
MSYH.TTC,Microsoft YaHei UI
SEGUISYM.TTF,Segoe UI Symbol
```
the key is the last line
```
SEGUISYM.TTF,Segoe UI Symbol
```
Because I am using Chinese version system, maybe do some change in English version.

**Comment by Finii** [comment]
The `〉` (unicode `3009`) is not part of Nerd Fonts patching.
