### ISSUE TITLE
B612Mono Patch request

### ISSUE THREAD

**Issue by fabiocosta0305** [ryanoasis/nerd-fonts#383]
I'm asking for a nerd-font version patch for the [B-612 font](https://b612-font.com/)

**Comment by ryanoasis** [comment]
Good suggestion thanks @fabiocosta0305 :smile: 

Repo: https://github.com/polarsys/b612

**Comment by ryanoasis** [comment]
> I'm also interested in this, is it a question of creating a PR?

Yes that's right.

> EDIT: I gave this font a try and didn't like it much. I don't expect to work on this.

Thanks for the update. Good to know

**Comment by Finii** [comment]
For me, something breaks while patching (i.e. too wide):
![image](https://user-images.githubusercontent.com/16012374/145952569-43b03094-bf79-4506-86db-f61aa3ecc18e.png)

**Comment by Finii** [comment]
The **B612Mono** works ok:
![image](https://user-images.githubusercontent.com/16012374/145953415-b24fbcf9-dc95-477b-9877-cac6df2e6907.png)

Not my style, maybe the Bold version looks more to my taste...
And I certainly would add `-l` for patching.

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
