### ISSUE TITLE
Fonts Patching requests

### ISSUE THREAD

**Issue by fabiocosta0305** [ryanoasis/nerd-fonts#386]
I would like to ask for some font patching requests

- Victor Mono - https://rubjo.github.io/victor-mono/
- CamingoCode - https://janfromm.de/typefaces/camingomono/camingocode/

**Comment by joeytwiddle** [comment]
@fabiocosta0305 I was playing around today, so I ran `./font-patcher` over those fonts for you.

https://www.dropbox.com/sh/59ou77aybqni3g7/AAAy9828unNfCxe6M5N1L0tFa?dl=0

Although it looks like Victor Mono is in the repo already.

**Comment by ApricumMedia** [comment]
I almost don’t want to ask, @joeytwiddle, but I’ve tried setting it up manually and it doesn’t seem to work right now. I reinstalled font forge on my machine but `font-patcher` crashes with an “Open failed” with an OTF file. Could you patch Apple’s beautiful SF Mono for me?

https://developer.apple.com/fonts/

**Comment by ApricumMedia** [comment]
Nevermind, my mistake was to think the patcher would download its own requirements by itself. Using a clone with `--depth=1` solved my issues.

**Comment by nwaywood** [comment]
@ApricumMedia any chance you could share the patched SF Mono?

**Comment by joeytwiddle** [comment]
@nwaywood Please take a peek at the Dropbox link today

**Comment by nwaywood** [comment]
@joeytwiddle I just downloaded it. Thank you!!!

**Comment by xfyuan** [comment]
> @nwaywood Please take a peek at the Dropbox link today

I tried to patch SF Mono but failed too. Could I get the dropbox link also?

**Comment by detly** [comment]
May I request [Envy Code R](https://damieng.com/blog/2008/05/26/envy-code-r-preview-7-coding-font-released)? There's a font named Envy Code S12 mentioned above, but it doesn't seem to be the same.

**Comment by joeytwiddle** [comment]
@detly Unfortunately that font forbids redistribution. 😞

**Comment by damieng** [comment]
I'm prepared to grant permission for Envy Code R to be included in nerd fonts. What do we need to make this happen?

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095

**Comment by Finii** [comment]
@damieng please raise a separate Issue, that I will add to 1095 then.

As you see there, a lot of fonts are on the list...
