### ISSUE TITLE
QUESTION How to get font family name?

### ISSUE THREAD

**Issue by Serhioromano** [ryanoasis/nerd-fonts#387]
I've downloaded a few fonts and want to use them in WSL terminal. So far I was only able to use Fira Code. And yet the name of the font on the site `FiraCode` but I had to write `Fira Code`.

Wheer I find those read font names in **Windows 10** to write in terminal settings or VS Code settings?

**Comment by hackedWifi** [comment]
`fc-query -f '%{family[0]}\n' Iosevka\ Nerd\ Font\ Complete.ttf`

**Comment by heavelock** [comment]
`Settings -> Personalization -> Fonts` Lists fonts according to their names instead of filename.  Unfortunately it's not a complete font name. I have a `FuraCode NF` in `Retina` and `Light` variants listed under it and only `FuraCode NF Retina` works for me.

**Comment by wawaforya** [comment]
In case someone uses Alacritty on Windows 10, you need to set the `family` to `FiraCode NF Retina` and comment out the `style`.

**Comment by ryanoasis** [comment]
Thanks all. closing for now

**Comment by Serhioromano** [comment]
That is only Firacode font. I have problem to use other fonts like monoid for instance.
