### ISSUE TITLE
Bump Victor Mono to latest + add missing readme

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#388]
#### 🎯 Subject of the issue

[Victor Mono](https://github.com/rubjo/victor-mono) should get bumped to latest version and also take opportunity to add missing readme file, per @rubjo's request.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ N/A
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ N/A
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ N/A

#### ★ Optional

N/A

**Comment by fabiocosta0305** [comment]
This font needs to take some care... I don't have screenshots here, but in KDE it misunderstood some ligatures (ff became a bizarre symbol and so) and have problems with accented chracters like `á` and `ã'

**Comment by ryanoasis** [comment]
For the `ff` ligature is related to some glyphs being overwritten, see https://github.com/ryanoasis/nerd-fonts/issues/254#issuecomment-517526427

for the accented is it the case that they aren't properly centered? Does it look similar to the screenshot here: https://github.com/ryanoasis/nerd-fonts/pull/374#issuecomment-545758315 ?
