### ISSUE TITLE
Update Hack/Knack font to v2.015

### ISSUE THREAD

**Issue by aquatix** [ryanoasis/nerd-fonts#39]
The Hack project released v2.015 a little while ago, which greatly improved some glyphs and rendering. Having it in nerd-fonts would be great.

**Comment by ryanoasis** [comment]
Thanks for the notice/update :+1:

**Comment by onnlinetool** [comment]
Downloaden Knack  Downloaden Knack  Downloaden Knack

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw
