### ISSUE TITLE
Translate readme to Ukrainian

### ISSUE THREAD

**Issue by igavelyuk** [ryanoasis/nerd-fonts#390]
To cover issue  #118 (Add internationalization and localization support to readme)
Added issue #390
Translate readme to Ukrainian #390 and push as readme_uk.md
According to [http://www.localeplanet.com/icu/uk-UA/index.html ](http://www.localeplanet.com/icu/uk-UA/index.html ) will be `uk` language code.

**Comment by igavelyuk** [comment]
I will take it. (issue #390 Translate readme to Ukrainian)

**Comment by ryanoasis** [comment]
closing since #392 is now merged :tada:
