### ISSUE TITLE
The icons of Code New Roman Nerd font are wrong

### ISSUE THREAD

**Issue by wsntxxn** [ryanoasis/nerd-fonts#391]
### 🎯 Subject of the issue

The file icons of code new roman nerd font are in wrong mapping relation with the file types. e.g. python file icons are actually php icons, markdown icons are actually json icons...
#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
Code New Roman Nerd Font
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ 
iterm2
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
OS X

#### Neovim
* neovim 0.4.0
looks just like this
<img width="256" alt="截屏2019-10-22下午6 57 50" src="https://user-images.githubusercontent.com/33143729/67279725-291abf00-f4fe-11e9-9f01-be4ff824ace3.png">

**Comment by yzlnew** [comment]
Neovim in TUI or GUI?

**Comment by wsntxxn** [comment]
TUI, iterm 2 on mac

**Comment by wsntxxn** [comment]
The icons are loaded by Plugin "vim-devicons". They  appear normal under other nerd fonts like Firacode or Furacode but appear abnormal under CodeNewRoman.

**Comment by wsntxxn** [comment]
This only occurs on Mac. The icon appears normal on Ubuntu.

**Comment by wgxh** [comment]
> This only occurs on Mac. The icon appears normal on Ubuntu.

But i use archlinux, This bug occurs on archlinux.

**Comment by wsntxxn** [comment]
The bug seems to be fixed.
The setup now:
neovim v0.5.0-139-g610755ff6
