### ISSUE TITLE
Noto Sans Mono Regular Height

### ISSUE THREAD

**Issue by reddare** [ryanoasis/nerd-fonts#395]
Height of `Noto Sans Mono Regular` changed after patching (in collection too).
Successfully patched but height are changed and font get lower.
Its only affect `10` size, why?

Original:
![alt text](https://imgur.com/m31OddA.png)

Patched:
![alt text](https://imgur.com/lK5seQV.png)

**Comment by ryanoasis** [comment]
Thanks for the report @reddare , I am trying to triage issues so I am unsure about when certain issues will be taken care of, apologies.

**Comment by Finii** [comment]
Will most probably be fixed with #761

**Comment by Finii** [comment]
Please check latest release. Reopen if that does not help.
