### ISSUE TITLE
[Request] Dina Font

### ISSUE THREAD

**Issue by c4tz** [ryanoasis/nerd-fonts#399]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue
Hey, would it be possible to patch [Dina](http://www.dcmembers.com/jibsen/download/61/)? I already tried myself (using both the BDF version from the link as well as a PCF version created with `bdftopcf`), but had no luck in getting it working/installable. I would like to use it as a monospaced bitmap font in my terminal. Thank you in advance!

#### 🔧 Your Setup

- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
urxvt/uxterm
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Arch Linux

**Comment by ryanoasis** [comment]
@c4tz Thanks for the suggestion, looks interesting. I am trying to triage issues.

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
