### ISSUE TITLE
Incompatible codepoints?

### ISSUE THREAD

**Issue by ariscn** [ryanoasis/nerd-fonts#40]
I'm trying to use `M+ 1m light Plus Nerd File Types Mono Plus Font Awesome Plus Octicons Plus Pomicons` with the https://github.com/bhilburn/powerlevel9k prompt for zsh. It has mappings to https://github.com/gabrielelana/awesome-terminal-fonts, which I assumed would work with `nerd-fonts`. This seems not to be the case, as some of the icons don't work: https://github.com/bhilburn/powerlevel9k/issues/95.

I'm new to powerline/nerd-fonts/etc, so I'm not sure why this is the case? Is this project mapping codepoints differently than `awesome-terminal-fonts`? What's the formula for constructing that mapping, and what's the best way for me to sync up `powerline9k` with the `nerd-fonts` font I'd like to use?

**Comment by ariscn** [comment]
Hm...looks like it may only be an issue with some fonts? Inconsolata looks fine at a cursory glance...

**Comment by ryanoasis** [comment]
I will do my best to answer your questions

> Hm...looks like it may only be an issue with some fonts?

That's possible, and some might not look very good at the moment and are untested. However the same variation of different fonts (e.g M+ with Awesome, Octicons, and Pomicons should have the same code points for the glyphs as Inconsolata).

Ah I think I see the problem to which you are referring. Looks like M+ is missing the powerline glyphs, see image below (left is M+ and right side is Inconsolata):
![selection_01_11_15_15 47 31_684x139_001](https://cloud.githubusercontent.com/assets/8083459/10871259/0bcb9012-80b0-11e5-9caa-c9566b9733f7.png)


> What's the formula for constructing that mapping, and what's the best way for me to sync up powerline9k with the nerd-fonts font I'd like to use?

I try to match the codepoints given in the original glyph font, but in some cases there are conflicts (e.g. Awesome and Octicons, so I favor Font Awesome and move Octicons to an alternative range).

> Is this project mapping codepoints differently than awesome-terminal-fonts?

I do not believe so, just quickly looking at the mapping on awesome-terminal for Font Awesome they look to match (fyi looks like awesome-terminal is using an older version of Font Awesome).

---

FYI, this project is using an older version of Octicons. This shouldn't be too bad to update but all fonts have to be rebuilt and that probably won't be done until [v0.6.0](https://github.com/ryanoasis/nerd-fonts/milestones/v0.6.0)

**Comment by ryanoasis** [comment]
Hmm I thought I might have fixed this with  [v0.6.0](https://github.com/ryanoasis/nerd-fonts/milestones/v0.6.0) but looks like there are still issues with glyph sizes

**Comment by mudox** [comment]
I tested several Ubuntu Mono fonts (which I mainly use on iTerm2 + Tmux + Neovim) from v0.6.0, it seems all powerline extra symbols are stretched, and their horizontal position is not as good as of previous versions (left shifted). 
* * *
before v0.6.0
through following iTerm2 profile -> Text -> Font settings
![screen shot 2015-11-17 at 11 43 27 am](https://cloud.githubusercontent.com/assets/2283394/11202195/bb3e484c-8d20-11e5-838d-f921caf3ca31.png)
I can achieve this perfect looking
![left](https://cloud.githubusercontent.com/assets/2283394/11202183/8282bc40-8d20-11e5-979a-72be42db4b65.png)
![right](https://cloud.githubusercontent.com/assets/2283394/11202184/89d9338e-8d20-11e5-856d-fe30180e1ced.png)
in v0.6.0
with the same iTerm2 font setting above, I got
![new left](https://cloud.githubusercontent.com/assets/2283394/11202283/8718039a-8d21-11e5-82bd-35f3c447da2e.png)
![new right](https://cloud.githubusercontent.com/assets/2283394/11202284/8ab2965a-8d21-11e5-8d53-b70ed34a7389.png)
and also through the font book, almost all symbols are stretched vertically more or less when the font size increase
![screen shot 2015-11-17 at 11 53 14 am](https://cloud.githubusercontent.com/assets/2283394/11202317/d110cd7e-8d21-11e5-9f8a-1a1eddb46414.png)

**Comment by ryanoasis** [comment]
Thanks for this. I will try to get this fixed, I saw some issues but decided to move forward anyway. I will see if I can get something more reliable. My guess is its related to em sizes

**Comment by DanielGGordon** [comment]
So what font actually works on Mintty (Windows)?

**Comment by ryanoasis** [comment]
Sorry pushing this off so I can get more easy tickets closed out before diving into the more complex ones :disappointed:

**Comment by herrbischoff** [comment]
Is there any solution in sight? I have the same issue with the Powerline symbols not showing up in the patched M+ 1m Regular. The other icons do work though.

**Comment by ryanoasis** [comment]
@herrbischoff I was able to replicate the issue of missing powerline symbols recently. Not sure what is going on (will have to dig a bit more into it). Apologies

**Comment by ryanoasis** [comment]
This has since been fixed in [v1.0.0 release](https://github.com/ryanoasis/nerd-fonts/releases/tag/v1.0.0)

left side: v0.8.0 (pre-fix)
right side: v1.0.0 (after post-fix)

![selection_011](https://cloud.githubusercontent.com/assets/8083459/23974657/bc3b3754-09b2-11e7-96f9-f1c386cebd2b.png)
