### ISSUE TITLE
Patching InputMono overwrites the letter `j`

### ISSUE THREAD

**Issue by CPWeaver** [ryanoasis/nerd-fonts#400]
#### 🎯 Subject of the issue

I'm running font-patcher to patch InputMono font. If I use `--complete` then the icon 
`nf-mdi-decimal_increase` overwrites the letter `j`. If I do not include mdi in the patching than the letter `j` is unaffected.

Found mention of this here but no ticket was opened:
https://github.com/ryanoasis/nerd-fonts/issues/164#issuecomment-410839942

#### 🔧 Your Setup

- Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_

InputMono, all variants. e.g. `InputMono-Medium.ttf` 
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_

iterm2 though this also shows up in the OSX Font Viewer
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_

OSX Catalina. It was true on Mavericks as well.

![image](https://user-images.githubusercontent.com/4966467/67987759-d7f08680-fbf3-11e9-8544-2adef4aae273.png)

Happy to provide any additional info if it'll help.

**Comment by LKloosterman** [comment]
+1 As I have this issue too, thought I could live with it but it's very annoying.

I'm on Manjaro (Arch Linux), my terminal emulator is gnome-terminal and I'm using InputMono-Regular if it helps.

**Comment by tdemarest** [comment]
+1 for another macOS Catalina 10.15.4, iterm2 3.3.10beta3, shows up in the Font Book. I only am using InputMono-Regular.ttf.

**Comment by jackcogdill** [comment]
+1

**Comment by kmalinich** [comment]
I had the same issue, and I tried every combination of dropping different command line arguments, but I couldn't get patching with all glyphs to work (without breaking the J character) ....... until I did it like this (a couple extra lines added for context)

(this is on macOS `10.15.6 (19G2021)`, with fontforge, GNU coreutils, GNU findutils and GNU parallel installed via brew and in my `$PATH`) 

Not really sure why this makes it work properly.

```bash
git clone --depth 1 https://github.com/ryanoasis/nerd-fonts
cd nerd-fonts
mkdir -p ~/fonts/InputMonoCompressed/Patched/
find ~/fonts/InputMonoCompressed/ -maxdepth 1 -name '*.ttf' | parallel -j $(nproc) fontforge -script font-patcher --no-progressbars --careful --complete --outputdir ~/fonts/InputMonoCompressed/Patched/ {} \;
```

**Comment by tdemarest** [comment]
Thanks @kmalinich - this worked for me as well. Fully up to date with all Homebrew installed tools and macOS 10.15.6.

**Comment by MiraculousMoon** [comment]
Thanks @kmalinich It works for me. From GentooLinux
![image](https://user-images.githubusercontent.com/61657399/92922874-15a37a00-f469-11ea-9542-2a48c26b4dfe.png)
Although It have a little defect

**Comment by kmalinich** [comment]
@MiraculousMoon Do you mean the height of the arrows?

**Comment by MiraculousMoon** [comment]
> @MiraculousMoon Do you mean the height of the arrows? If so, you might try adding `--adjust-line-height` to the arguments. The `--help` states this:
> 
> ```
>  -l, --adjust-line-height
>                         Whether to adjust line heights (attempt to center powerline separators more evenly)
> ```
Thanks for your reply!
This is my command:
find ~/Input_ori/ -maxdepth 1 -name '*.ttf' | parallel -j  $(nproc ) fontforge -script font-patcher --no-progressbars  --careful --complete --adjust-line-height --outputdir ~/input/ {} \;
But it still looks like this:
![image](https://user-images.githubusercontent.com/61657399/92991588-93be5a00-f517-11ea-853e-bbfff01fc83c.png)

**Comment by MiraculousMoon** [comment]
> @MiraculousMoon Do you mean the height of the arrows? If so, you might try adding `--adjust-line-height` to the arguments. The `--help` states this:
> 
> ```
>  -l, --adjust-line-height
>                         Whether to adjust line heights (attempt to center powerline separators more evenly)
> ```

Now I find the problem is from alacritty. When I switch to kitty, it is normal.
![image](https://user-images.githubusercontent.com/61657399/93561735-50506980-f9b7-11ea-89c5-77cf9dad73a6.png)

**Comment by dabekf** [comment]
So I encountered this exact problem today, and while I don't have a solid solution, I found out some interesting things that might help out someone else. Also I have different workaround that might be a better fit.

The original problem was "`nf-mdi-decimal_increase` overwrites the letter `j`". It's more than that. 'Decimal increase' is `U+F6BE` and Input Mono actually already has a character at that spot and it looks like a "dotlessj": ȷ. For some reason updating `U+F6BE` modifies other j-like characters, for example: `U+006A` j, `U+0237` ȷ, `U+0458` ј, maybe others.

The `'--careful'` fontpatcher option kind of works, it skips the problematic characters, but then few other existing glyphs don't get updated, like `U+E0B0` `nf-pl-left_hard_divider`. That might have been the cause of arrow defects in the screenshots - Input Mono's original versions are shifted up a bit.

Anyway, I don't really need the 'decimal increase' character, so I modified the fontpatcher to skip the three private characters Input Mono has around that range. The patch is for fontpatcher-2.2.0-RC but it probably works in other versions too.

```*** font-patcher-orig   Wed Aug 17 23:51:55 2022
--- font-patcher-github Thu Aug 18 20:20:28 2022
*************** class font_patcher:
*** 688,693 ****
--- 688,698 ----
              # Prepare symbol glyph dimensions
              sym_dim = get_glyph_dimensions(sym_glyph)

+             # Input Mono tmp fix for weird 'j' and possibly other characters
+             if self.sourceFont.familyname == "InputMono NF" and copiedToSlot in ['F6BE', 'F6C3', 'F8FF']:
+                 print("  Input Mono weird glyph at {}. Skipping...".format(copiedToSlot))
+                 continue
+
              # check if a glyph already exists in this location
              if careful or 'careful' in sym_attr['params']:
                  if copiedToSlot.startswith("uni"):```

**Comment by dabekf** [comment]
Here is the updated patch for version 2.2.1, some changes made the previous one incompatible:

```
*** font-patcher.orig	Fri Aug 26 23:58:07 2022
--- font-patcher.new	Mon Sep  5 23:39:47 2022
*************** class font_patcher:
*** 932,937 ****
--- 932,942 ----
                      sys.stdout.write(progressText)
                      sys.stdout.flush()
  
+             # Input Mono tmp fix for weird 'j' and possibly other characters
+             if self.sourceFont.familyname.startswith("InputMono NF") and "{:X}".format(currentSourceFontGlyph) in ['F6BE', 'F6C3', 'F8FF']:
+                 print("  Input Mono weird glyph at {}. Skipping...".format(currentSourceFontGlyph))
+                 continue
+ 
              # check if a glyph already exists in this location
              if careful or 'careful' in sym_attr['params']:
                  if currentSourceFontGlyph in self.sourceFont:
```

**Comment by Finii** [comment]
Thanks for the input.
Do you need any of the 'strange' `j` versions, or is the ordinary one enough?

Is this the font you mean? It's not in 'our' set of (un)patched fonts I believe?

![image](https://user-images.githubusercontent.com/16012374/188548133-82051c22-2432-44fd-b89b-f7517cc02f8e.png)

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/188552787-03861948-daf3-409d-bf0e-3f8825c259fb.png)

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/188553528-0964f2af-1b16-4595-9b05-0947add981a4.png)

The small `j` is encoded as combination of the dotless-small-j `F6BE` and a dot `0307`.

Lets see if we can detect that in a generic manner.

**Comment by dabekf** [comment]
Yes, this is the font. It's not in the set for license reasons I believe (it's first on the list in the "Other Good Fonts to Patch" section of the project description). Combination looks like a good catch, explains a lot.

I personally don't need other "j"s, but I can imagine other people might (for example the cyrillic one), also it would be a shame to lose them just for aesthetic reasons.

I was thinking of a configuration file or some 'selective careful' option as a long term solution, but those have their own problems. If it's possible to automatically detect and omit combinations, that would probably be ideal.

**Comment by Finii** [comment]
> If it's possible to automatically detect and omit combinations

Seems like easy, creating PR

**Comment by Finii** [comment]
Hmm,

> `"{:X}".format(currentSourceFontGlyph) in ['F6BE', 'F6C3', 'F8FF']`

@dabekf What is it with the `F6C3` and `F8FF` ? :thinking:

**Comment by dabekf** [comment]
At the time I didn't know about the combinations so I hit all three characters from the "private use" range just to be sure. If they are not used elsewhere, they can probably be safely overwritten by NF glyphs.

**Comment by nathanielevan** [comment]
Hi, it appears that on my machine (Arch Linux) tested against master branch (font-patcher v3.4.4) this has started happening again:
![scshot-200123-003121](https://user-images.githubusercontent.com/9361126/213518115-e12afffc-6516-4a61-8b96-b64121234f0d.png)
Interestingly enough, testing against version 2.3.0-RC (font-patcher v3.1.1) and 2.2.2 (font-patcher v3.0.5) also yields the same results. Anyone else encounter this issue?
