### ISSUE TITLE
NotoSansMono bad looking

### ISSUE THREAD

**Issue by oblitzitate** [ryanoasis/nerd-fonts#401]
![2019-11-05-190252_776x340_scrot](https://user-images.githubusercontent.com/56560015/68256840-3f954000-ffff-11e9-9264-94c2a6eb6db6.png)

Font's spacing is messed up and it sometimes puts in a symbol in place of a character. Tried it on `kitty` and `polybar`.

**Comment by ryanoasis** [comment]
Thanks @oblitzitate but I am pretty sure that is _not_ NotoSansMono. I think you likely have the font name wrong and it's falling back to some system font. Can you confirm what font is loading?

**Comment by ryanoasis** [comment]
Also there are reporst that kitty works well now. Closing for now, feel free to re-open if you can provide a follow up to my question. Thanks
