### ISSUE TITLE
emojies aren't displayed in my csv file, what font shoul I install and how to do? As a beginner, I dont understand these codes.

### ISSUE THREAD

**Issue by xiaowei-xw** [ryanoasis/nerd-fonts#406]
#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?
I don't know.
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
I don't know.
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Windows-10

**Comment by ryanoasis** [comment]
Please refer to:
- https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting
- https://www.nerdfonts.com/cheat-sheet

If that is not helpful, please elaborate on the issue you are having. Thanks.

**Comment by ryanoasis** [comment]
Closing for now, feel free to re-open if you can provide a follow up
