### ISSUE TITLE
Uninstall fonts

### ISSUE THREAD

**Issue by jeusdi** [ryanoasis/nerd-fonts#407]
Is there anyway to uninstall installed fonts using `install.sh` script?

**Comment by ryanoasis** [comment]
@jeusdi Not currently no, this could be an interesting feature though. Pull requests are always welcome.

I am closing this for now, if there is enough desire for this we can re-open and evaluate :smile:

**Comment by cdmeister** [comment]
I just wanted to mention that it might be useful to have this. I ran into an issue with ubuntu 20.04 when I applied a gnome shell theme, the font got all messed up after I installed Nerd Font.

**Comment by Teeyawn** [comment]
sudo rm -f -r /share/fonts/NerdFonts/
fc-cache -fv

Works on Kali to delete NerdFonts and restore my font cache

**Comment by Finii** [comment]
This is the first time I looked into the script...

Is `install.sh --clean --minimal` not working? It should do exactly what @Teeyawn suggested if I can still read?!

Explanation:
`--clean` removes all previously installed Nerd Fonts
`--minimal` installs all minimally patched fonts, which are ... none

Well... I have created a proper PR, hold tight.

**Comment by Teeyawn** [comment]
thank you!

**Comment by Finii** [comment]
Finally merged.
