### ISSUE TITLE
Cannot display some characters in win7

### ISSUE THREAD

**Issue by matanagasauce** [ryanoasis/nerd-fonts#408]
#### 🎯 Subject of the issue

Some characters in Font Awesome and IEC Power Symbols cannot be displayed in my win7 environment, both in cmd, in putty and in ms office word, but other characters look good.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
I tried hack, meslo, dejavu, droid, consolas
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
cmd, putty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
windows 7

#### ★ Optional

Here are two snapshot in putty. Same were displayed elsewhere I tried.
![a](https://user-images.githubusercontent.com/17398258/69564944-e9f4f780-0fee-11ea-87a7-a3dbeb8551c0.png)
![b](https://user-images.githubusercontent.com/17398258/69565017-0c871080-0fef-11ea-9c81-744b4f278e16.png)

**Comment by ryanoasis** [comment]
I feel like this is probably an ambiguous character width issue.

Can you try looking at putty settings:


![putty](https://user-images.githubusercontent.com/8083459/72768330-e1aed800-3bab-11ea-8a4c-1c3b1b2b7ea3.png)

**Comment by yangyangxcf** [comment]
Thanks for replying!
I've tried but it still doesn't work:(
I don't know if it's worth to mention that it behaves the same throughout the system, including in a text editor. I'm not an expert at fonts but I guess maybe it's not an issue regarding any single app.

**Comment by mburszley** [comment]
Windows 7 is EOL now - I don't see a point in this project trying to work for a niche use-case.

**Comment by Finii** [comment]
I guess @Halkcyon is right. I would not even know how to get hands on a machine running Win7.
Even the oldest Win7 boxes at my work are shut down now. We work on replacing 10 with 11 ;-D
