### ISSUE TITLE
Retain glyph names when merging

### ISSUE THREAD

**Issue by eugenesvk** [ryanoasis/nerd-fonts#41]
I've noticed that glyph names are lost when patching fonts. For example, if I take the __Octicons__ font as a source of glyphs and patch another font with it (with the `--octicons` option), then all the glyph names (e.g. __octoface__ or __mark-github__ or __repo-forked__ for some of the standard GitHub glyphs) are lost and instead replaced by Unicode glyph codes (e.g. __uniF008__ for __octoface__).

Is there a chance to retain those names? They are very useful in finding specific glyph codes (remembering a name is much easier than remembering a code, especially since codes can change between font versions, while name is usually more stable).
Thank you!

**Comment by ryanoasis** [comment]
@eugenesvk 

I think I have found a solution to this :smile:, I will include this with the [next release](https://github.com/ryanoasis/nerd-fonts/milestones/v0.6.0) if it tests out well. Thanks for reporting this :+1: 


somewhat related (in that info is lost): #43

**Comment by eugenesvk** [comment]
Ok, thanks a lot! Will be looking forward to it.
By the way, I've noticed another thing - some of the glyphs in the end of __Octicons__ are not appended (e.g. F0E0 for 'watch' or F27C for 'device-desktop). I've downloaded the latest version before embedding (which has a few extra glyphs), so my guess would be that the address range is not updated yet. If that is the case, would you kindly update the range to for the `--octicons` option so that all glyphs get embedded?
Thanks!

P.S.
Never used github before, so not sure whether I should close this issue myself or you will do it after you release an update.

**Comment by ryanoasis** [comment]
@eugenesvk 

Yes you are correct Octicons I am using is not up to date, see: https://github.com/ryanoasis/nerd-fonts/issues/34#issuecomment-153050037

No worries I was actually late to the GitHub party as well :smile: . For this issue we can leave it open and I will close it on the next release.
