### ISSUE TITLE
Windows Install Script

### ISSUE THREAD

**Issue by roysubs** [ryanoasis/nerd-fonts#410]
I found no method of reliably automating the installation of these fonts to Windows in the project documentation along with the Terminal-Icons module to enable these fonts on gci / dir / ls output in PowerShell so wrote the below. The following can be thrown into any PowerShell console (with *Admin* rights) and should set everything up.

### Install Terminal-Icons (get LiterationMono NF Nerd font, install, add required Console registry key, then install required Modules)
```
$url = 'https://github.com/haasosaurus/nerd-fonts/raw/regen-mono-font-fix/patched-fonts/LiberationMono/complete/Literation%20Mono%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf'
$name = "LiterationMono NF"
$file = "$($env:TEMP)\$($name).ttf"
Start-BitsTransfer -Source $url -Destination $file   # Download the font

$Install = $true  # $false to uninstall (or 1 / 0)
$FontsFolder = (New-Object -ComObject Shell.Application).Namespace(0x14)   # Must use Namespace part or will not install properly
$filename = (Get-ChildItem $file).Name
$filepath = (Get-ChildItem $file).FullName
$target = "C:\Windows\Fonts\$($filename)"

If (Test-Path $target -PathType Any) { Remove-Item $target -Recurse -Force } # UnInstall Font

If ((-not(Test-Path $target -PathType Container)) -and ($Install -eq $true)) { $FontsFolder.CopyHere($filepath, 16) }   # Following action performs the install, requires user to click on yes

$key = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Console\TrueTypeFont'   # Need to set this for console
Set-ItemProperty -Path $key -Name '000' -Value $name

Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force   # Always need this, required for all Modules
Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted   # Set Microsoft PowerShell Gallery to 'Trusted'
Install-Module Terminal-Icons -Scope CurrentUser
Import-Module Terminal-Icons
Install-Module WindowsConsoleFonts
Set-ConsoleFont $name
Set-TerminalIconsColorTheme -Name DevBlackOps   # After the above are setup, can add this to Profile to always load

```

**Comment by ryanoasis** [comment]
@roysubs There is a [PowerShell script](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/install.ps1) for installation on Windows. 

does https://github.com/ryanoasis/nerd-fonts/pull/357 help you here?

**Comment by codingjustahobby** [comment]
Well , if you do python then you can check out my stuff , I have a project that automatically installs downloaded fonts . Even if you don't, I have a vbs script on github that takes the font file (.ttf or .otf) as parameter and installs it . Hope those help

**Comment by Finii** [comment]
Thanks for the code. But I guess this got obsolete after #570 has been merged?
