### ISSUE TITLE
Powerline glyphs has space on patched FiraCode

### ISSUE THREAD

**Issue by nivv** [ryanoasis/nerd-fonts#411]
#### 🎯 Powerline glyphs has space on patched FiraCode

Left pointing angle shape has a small transparent line. Right pointing angle seems to  be correct. 

#### 🔧 Your Setup

- _Which font are you using (e.g. `l`)?_  FiraCode Nerd Font Mono Normal
- _Which terminal emulator are you using_ iterm2
- _Are you using OS X, Linux or Windows?_  macOS Catalina

#### ★ Optional

![image](https://user-images.githubusercontent.com/4033930/70866884-566c7200-1f6f-11ea-8d89-bf2495fd4baa.png)

![image](https://user-images.githubusercontent.com/4033930/70866902-8c115b00-1f6f-11ea-9083-3c520c83748e.png)

**Comment by nivv** [comment]
When I have a monitor attached the space is gone. Above screenshot is from my MBP Retina.

From my monitor today:
![image](https://user-images.githubusercontent.com/4033930/70887554-8acb4700-1fde-11ea-9402-1234857aa8fd.png)

**Comment by ImGamez** [comment]
Same happens with Hack Nerd Font Normal, had to repatch without powerline glyphs to fix it.
It's really annoying 😖.
Using Konsole here.
Ps: Right pointing angle has the same transparent line, but is more subtle because of the color combination you are using.

**Comment by Finii** [comment]
This should be fixed by now, if not it should at least be far less obvious.
There is one open PR still #780, but I'm not sure it is really needed anymore.
Try using monochrome antialiasing, that helps.
