### ISSUE TITLE
Request: Add U+276F (prompt cursor of pure and powerlevel10k theme)

### ISSUE THREAD

**Issue by jh-min** [ryanoasis/nerd-fonts#414]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [ ] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ ] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

It seems that Nerd Fonts 2.0 does not add `U+276F`, HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT (and `U+276E`, its counterpart), even if `--complete` option was set. But this glyph is used frequently in popular Zsh themes such as [pure](https://github.com/sindresorhus/pure) or [powerlevel10k](https://github.com/romkatv/powerlevel10k) so it would be better if Nerd Fonts supports this glyph _by default_.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
Consolas Nerd Font Complete Windows Compatible
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
[Terminus](https://github.com/randy3k/Terminus), a package of Sublime Text 3
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Ubuntu 18.04.3 LTS via WSL (Windows 10 Build 18363.476)

#### ★ Optional

using `src/glyphs` folder from [2.0 release](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.0.0), font was generated by:

```bash
fontforge -script font-patcher "path/to/consola.ttf" -w -c
```

<img width="405" alt="consolasnot" src="https://user-images.githubusercontent.com/57447828/71582321-0552a580-2b4d-11ea-9272-3a764c7fa190.PNG">

Note: `Hack` seems to have this glyph by default. I tried 10+@ fonts from [2.0 release](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.0.0) and only `Hack`, `Dejavu Sans` and `Meslo` supported `U+276F`. (So I set `Hack` as custom font to patch `Consolas` but I dont want to add _all new_ glyphs without knowing exactly what will be added...)

<img width="405" alt="hackhas" src="https://user-images.githubusercontent.com/57447828/71582410-7c883980-2b4d-11ea-9b1e-1c33e60b9d78.PNG">

**Comment by ryanoasis** [comment]
Thanks @jh-min good suggestion. I was thinking about adding missing symbols such as these to fonts that don't have them, though some might not match up with the 'style' of each font.

**Comment by DoCode** [comment]
How can we integrate these symbols into the Consolas font?

**Comment by ryanoasis** [comment]
@DoCode Yeah we'd add these symbols by default to all fonts that don't have them so Consolas would also be possible. However Consolas won't be part of the patched fonts because of the license

**Comment by jmederosalvarado** [comment]
Hi. Is there any progress on this. I've had the same problem with these glyphs with various fonts wich don't include them. It would be great to have them here. Thank you so much for the project, it's great 💪

**Comment by Finii** [comment]
Good idea and very simple. Adding to `v3.0.0`

**Comment by Finii** [comment]
Fixed (i.e. implemented) via 59c5cb5a1f33139b79838f010fafea26623ed046
