### ISSUE TITLE
Victor Mono the dot on the lowercase i is mis-aligned

### ISSUE THREAD

**Issue by ghost** [ryanoasis/nerd-fonts#415]
As the title describes, I am using the Medium and regular font styles an the dot in the lowercase i is shifted to the right.

**Comment by ryanoasis** [comment]
Thanks. Strange, can you provide a screenshot?

**Comment by maturanomx** [comment]
I guess is the same as #494 which has a screenshot

**Comment by Finii** [comment]
Hmm, the `i` is in fact a conbination of dotless-i and a dot.

![image](https://user-images.githubusercontent.com/16012374/216775757-cf7650d8-bb67-45c9-8881-b65167fcdc25.png)

But as you see it looks good in current release.
There are at least two commits that fix stuff in this direction.
To debug further we would need more information: Concrete font, OS, terminal etc.
Please open completely filled **new issue** if you still have the problem.
