### ISSUE TITLE
Question: Non programming fonts

### ISSUE THREAD

**Issue by FredHappyface** [ryanoasis/nerd-fonts#417]
- [x ] A brief but descriptive _title_ of your issue
- [ x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x ] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
N/A
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
Microsoft Terminal (Preview)
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Windows 10 

Whilst I am aware that these fonts are largely dev orientated would submitting non dev fonts such as Fira Sans to the project be of any use to anyone? I have already asked in the gitter chat though the question got pretty buried and I therefore never got a response.

Oh and PS: Thanks for the project - I have found these fonts to be very useful

**Comment by ryanoasis** [comment]
Thanks for creating the issue. It's a good question. I would say it could be useful to add "non programming" fonts.

Typically requests for new fonts do make it in... eventually. What helps are how popular they are or the request is or if someone submits a PR that patched it and updated the necessary things.

> Oh and PS: Thanks for the project - I have found these fonts to be very useful

Very glad! Thanks, and thank you for using and being active :smile:

**Comment by ryanoasis** [comment]
@FredHappyface I hope that answered your question. I'm going to close this issue for now.

Don't be afraid to reopen if there is more to it or feel free to just comment as well.

Thanks
