### ISSUE TITLE
Download link to Gohufont broken on website

### ISSUE THREAD

**Issue by somospocos** [ryanoasis/nerd-fonts#418]
On https://www.nerdfonts.com/font-downloads , the download link for Gohufont https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Gohu.zip is broken. As https://github.com/ryanoasis/nerd-fonts/releases shows, for some reason the zip archive for Gohufont did not make it into the 2.0.0 release. I had to scroll down and manually download it from previous 1.2.0 release.

**Comment by ryanoasis** [comment]
Thanks @somospocos ! Good catch, this is a problem with the archive script. I can see why Gohu was not being generated. I have a working fix..

**Comment by ryanoasis** [comment]
This is fixed because the Gohu archive is now generating, will be present in the next release
