### ISSUE TITLE
Add Jetbrains Mono font

### ISSUE THREAD

**Issue by rickard-von-essen** [ryanoasis/nerd-fonts#420]
JetBrains recently released a developer focused font called [JetBrains Mono](https://www.jetbrains.com/lp/mono/) that would be great to get in.

**Comment by damnskippy** [comment]
See also: https://github.com/ryanoasis/nerd-fonts/pull/421

**Comment by ryanoasis** [comment]
Checked license, looks good to include. No RFN restriction so meaning we don't have to rename it.. can simply be Jetbrains Mono Nerd Font or something :smile:

**Comment by damnskippy** [comment]
Also: https://github.com/JetBrains/JetBrainsMono/pull/10

**Comment by ryanoasis** [comment]
@damnskippy Thanks for the linking and @rickard-von-essen for the tracking issue.

Closing now because #421 is merged.

**Comment by jrop** [comment]
Since I am a new user of this repo, I have a stupid question: about how long does it take once the merge-request has landed for Brew packages and the website to be updated?

**Comment by ryanoasis** [comment]
@jrop No that is a not a stupid question :smile: 

Merge requests don't really kick off anything in terms of releases or website updates. Master branch is almost a develop branch in that sense.

The brew packages I am aware of target the release archives so we would have to cut a new release. This process is mostly automated with some manual work involved.

Typically the website is updated after the release is pushed out.

Hope that helps.

**Comment by danielwaltz** [comment]
Any chance of a new release in the near future? I'm interested in getting the nerd font patched version of this font added to `homebrew-cask-fonts`.

**Comment by ryanoasis** [comment]
@danielwaltz There's always a chance :wink: 

But seriously, yes there is a very good chance there will be a release very soon. I don't want to give a date to avoid disappointment.

I am not just being optimistic but I have reasons:

1) I've just gotten back into serious efforts to make a much overdue release (PRs merged, triaging some overdue issues)
2) The archiving script wasn't working and was not adding a few fonts
3) I am trying to mentally shift from making sure everything is perfect but instead just make reasonable tests

**Comment by danielwaltz** [comment]
That's good to hear! Take as long as you need. Really appreciate your contributions!
