### ISSUE TITLE
Update Fira Code Font to 2.0

### ISSUE THREAD

**Issue by smacintyre** [ryanoasis/nerd-fonts#424]
Please update the [Fira Code Font to v2](https://github.com/tonsky/FiraCode). It recently went through a major redesign. Currently the patched font is [v1.206](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode).

**Comment by ryanoasis** [comment]
Great to know, thanks for the heads up. Now updated!
