### ISSUE TITLE
Update JetBrains Mono to 1.0.2 (or newer)

### ISSUE THREAD

**Issue by pro-sumer** [ryanoasis/nerd-fonts#425]
Thank you for including [JetBrains Mono](https://www.jetbrains.com/lp/mono/)!

Unfortunately they had a few issues in version 1.0, which they fixed in two additional releases (so far).

Can you please update it to version [1.0.2](https://github.com/JetBrains/JetBrainsMono/releases/tag/v1.0.2) (or newer)?

**Comment by ryanoasis** [comment]
this is done
