### ISSUE TITLE
Ligatures lost when patching PragmataPro

### ISSUE THREAD

**Issue by shayne** [ryanoasis/nerd-fonts#43]
The official unpatched PragmataPro supports many ligatures for programming. Using the font produced by the patcher produces file type icons, but ligatures are lost.

**Comment by ryanoasis** [comment]
Thanks! :+1: Yes this looks to be the case :disappointed: 

I found a nice script that outputs the ligatures and I was able to verify before and after that they do become lost.

I have just quickly tried experimenting with fontforge methods trying to copy the ligatures with no success so far.

I will update if any news.

**Comment by jordwalke** [comment]
:+1:

**Comment by ryanoasis** [comment]
Okay so it might be as simple as adding a flag on generating a font, I have been able to keep the ligatures, however there is another issue: The location of the ligatures is conflicting with devicons, so devicons is clobbering some of the ligatures.

See below (left side is without the font, right side is the font):

![selection_10_11_15_10 51 03_1255x879_001](https://cloud.githubusercontent.com/assets/8083459/11067188/657103d2-8799-11e5-80d1-920f78f39175.png)

![selection_10_11_15_10 51 53_1265x860_001](https://cloud.githubusercontent.com/assets/8083459/11067192/698bbd36-8799-11e5-893e-7896f33ba9ba.png)

Before adding the flag, none of the ligatures were showing up.

**Comment by ryanoasis** [comment]
Just a quick update I added a flag that will _not_ overwrite glyphs (ligatures as well in this case). At least you'll get the option :smile: 

Should be ready to go this weekend if all is well:

![selection_13_11_15_21 58 40_950x960_001](https://cloud.githubusercontent.com/assets/8083459/11161693/cc5c85a2-8a51-11e5-994a-200a3bf57ab5.png)

**Comment by shayne** [comment]
Thanks for looking into this!

**Comment by esn89** [comment]
@shayne @ryanoasis 

I've ran the script with:

./font-patcher --fontawesome --careful ../PragmataPro\ Mono\ Regular.ttf

My ligatures are still lost, any ideas why?
