### ISSUE TITLE
Unexpected Characters in FiraCode Nerd Font Mono

### ISSUE THREAD

**Issue by parkerbxyz** [ryanoasis/nerd-fonts#432]
## 🎯 Subject of the issue

The  **FiraCode Nerd Font Mono** appears to have a problem in the latest release (v2.1.0) that did not exist in v2.0.0. The **FiraCode Nerd Font** appears to be unaffected. I have attached screenshots of both below for comparison.

A few examples of the issues I'm seeing in **FiraCode Nerd Font Mono** v2.1.0: 

- `i` displays as `j` if proceeded by `f` (`files` displays as `fjles`)
- `:` displays as `(` when adjacent to a number or `(` or `)`
- `-` displays as `≪` when adjacent to a letter

There are too many examples to list them all here. The screenshots below show more examples.

## 🔧 My Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
  
    **FiraCode Nerd Font Mono**

- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_

  **Terminal.app**

- _Are you using OS X, Linux or Windows? And which specific version or distribution?_

  **macOS 10.15.3**

### FiraCode Nerd Font

<img width="762" alt="Screen Shot 2020-02-04 at 12 27 48 PM" src="https://user-images.githubusercontent.com/17183625/73770418-65d79280-474a-11ea-80b0-164c6fb81795.png">
<img width="762" alt="Screen Shot 2020-02-04 at 12 25 18 PM" src="https://user-images.githubusercontent.com/17183625/73770215-07121900-474a-11ea-87a1-9d2157c2eef7.png">

### FiraCode Nerd Font Mono

<img width="762" alt="Screen Shot 2020-02-04 at 12 24 01 PM" src="https://user-images.githubusercontent.com/17183625/73770432-6c660a00-474a-11ea-866e-3b4a222d71ff.png">
<img width="762" alt="Screen Shot 2020-02-04 at 12 25 46 PM" src="https://user-images.githubusercontent.com/17183625/73770228-0c6f6380-474a-11ea-9391-95bdd7d58bf4.png">

**Comment by austinmatherne-wk** [comment]
I'm also seeing this issue

**Comment by ianhomer** [comment]
Started seeing this too recently - switching to FiraCode Nerd Font looks better for me.  Just reading around the subject and see - https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode -  "By the Nerd Font policy, the variant with the 'Mono' suffix is not supposed to have any ligatures. Use the non-Mono variants to have ligatures". Maybe firacode, nerd, mono and ligatures are never meant to mix.  When I use FiraCode Nerd Font mono in iterm and disable ligatures, the text renders OK, albeit without ligatures.

**Comment by parkerbxyz** [comment]
If you installed this font with Homebrew, running the following command may fix your issue:

```sh
brew cask reinstall font-firacode-nerd-font-mono
```

I'm no longer seeing this problem after reinstalling the font.

**Comment by ryanoasis** [comment]
Seems like I can close this issue. Anyone still having the problem?
