### ISSUE TITLE
FiraCode's Ellipsis ligature "..." displayed as "?."

### ISSUE THREAD

**Issue by alessandro-calo** [ryanoasis/nerd-fonts#435]
#### 🎯 Subject of the issue

When typing three dots ("..."), the resulting ligature looks like "?." instead of the expected three-dots-slightly-closer-together.

#### 🔧 Your Setup

- font: FuraCode Nerd Font Mono
- terminal emulator: `iterm2` (but also any other editor, e.g. SublimeText)
- macOS 10.15.3

#### ★ Optional

Here are screenshots of the following file 
```
.
..
...
```
with normal Fira Code:
![FiraCode](https://user-images.githubusercontent.com/55374095/74035345-66766000-49ba-11ea-8f85-f336b607b20f.png)
and with FuraCode Nerd Font Mono:
![FuraCode Nerd Font Mono](https://user-images.githubusercontent.com/55374095/74035347-670ef680-49ba-11ea-814a-8e2a0a5d3707.png)

**Comment by ryanoasis** [comment]
Thanks for the report

**Comment by taw00** [comment]
Off-topic, but I don't know where else to ask this question to all you font people: The ellipsis is implemented two different ways according to style guides: 1) as three dots close together ... (AP styleguide), or 2) as three dots with a space between . . . (Chicago).

A lot of fonts have the three dots close as a single character, but I don't know that I have seen any font _also_ provide the other common way of implementing the ellipsis. Is this something font-people argue about at all? I can't be the only person to bring this up.

Any thoughts?

**Comment by Finii** [comment]
Duplicate #337
Fixed.
