### ISSUE TITLE
Cascadia Code Preview Image is ... wrong?

### ISSUE THREAD

**Issue by Jaykul** [ryanoasis/nerd-fonts#438]
## The screenshot in the downloads section is just not the right font:

![current screenshot](https://www.nerdfonts.com/assets/img/previews/Caskaydia%20Cove%20Nerd%20Font.svg)

### What it actually looks like:

![image](https://user-images.githubusercontent.com/192942/74209404-9ee59a80-4c55-11ea-82c8-1424e5ed4dcb.png)

Note that it's actually monospaced?
Also notice the distinctive "c" and "k", the dotted zero, and the `iIlL1` sequence?

**Comment by ryanoasis** [comment]
thanks. I regenerated, please take a look now

**Comment by Jaykul** [comment]
Looks good (can even see that here in the issue). Thanks 😁
