### ISSUE TITLE
missing voidlinux os icon glyph

### ISSUE THREAD

**Issue by borysn** [ryanoasis/nerd-fonts#443]
#### 🎯 Subject of the issue

nerd fonts is missing an os icon glyph for [voidlinux](https://voidlinux.org)

#### 🔧 Your Setup

using `MesloLGS NF Regular.ttf` a patched meslo font. but the glyph is missing in all fonts 

urxvt/linux

**Comment by ryanoasis** [comment]
Did you find an alternative solution? Just wondering

**Comment by borysn** [comment]
@ryanoasis no we got into a fight because the channers wouldn't stop gaslighting me, then voidlinux irc banned me, then the channers started harassing me and stalking me for a few days, so i left voidlinux and i closed the issue. add the icon if you want, idc, maybe i'll go back to voidlinux someday after they resolve their community issues because it's actually pretty awesome
