### ISSUE TITLE
Kubernetes icon looks too small

### ISSUE THREAD

**Issue by simonrouse9461** [ryanoasis/nerd-fonts#444]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Kubernetes icon looks too small

The Kubernetes icon looks too small comparing to the python icon.
It looks more like an asterisk rather than a helm.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ 
`Sauce Code Pro Nerd Font`
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
`iterm2`
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
`MacOS Catalina`

#### ★ Optional

<img width="184" alt="Screen Shot 2020-02-20 at 2 09 36 AM" src="https://user-images.githubusercontent.com/10589586/74909696-d9061900-5386-11ea-97a5-08676d054bf5.png">

**Comment by simonrouse9461** [comment]
Another problem is that the Kubernetes icon is a helm with 7 spokes rather than 6.
Six spokes make it look really like an asterisk.
![58480a44cef1014c0b5e4917](https://user-images.githubusercontent.com/10589586/74995764-cf7cbf80-541f-11ea-9b6f-283156555a0f.png)

**Comment by Zebradil** [comment]
What is the unicode code of this char? I couldn't find it.

**Comment by tmoschou** [comment]
It looks like your Kubernetes prompt plugin (assuming [Oh My ZSH - kube-ps1](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/kube-ps1)) is using the [Unicode Helm Symbol](https://www.compart.com/en/unicode/U+2388) U+2388 ⎈, not a nerd fonts icon. Nerd fonts doesn't have Kubernetes icon, but the latest version of Material Design Icons does (`mdi-kubernetes` `F10FE`). 

* https://github.com/Templarian/MaterialDesign/blob/master/svg/kubernetes.svg
* https://pictogrammers.github.io/@mdi/font/5.4.55/

It seems that nerd fonts is using an outdated version of Material Design Icons? It would be great if Material Design Icon pack could be updated.

**Comment by ksawerykarwacki** [comment]
Any chance this will be updated and included?

**Comment by Finii** [comment]
@ksawerykarwacki 
* #773

**Comment by simonrouse9461** [comment]
Will the [website](https://www.nerdfonts.com/cheat-sheet) be updated soon as well? I'm searching for `nf-mdi-kubernetes`, I still don't see it.

**Comment by Finii** [comment]
It will be updated on release of `v2.3.0`

Which reminds me that I forgot to check if the cheat sheet can display 5 digit code :grimacing:

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/216776602-30e4641e-c540-4fd7-b0e6-6c9d758c7e86.png)

About the 'too small' this affects all `mdi` icons, see #1061
