### ISSUE TITLE
Iosevka Nerd Font tofu glyphs in terminal and elsewhere

### ISSUE THREAD

**Issue by maricn** [ryanoasis/nerd-fonts#445]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

Nerd Fonts don't display properly, ie. as box/tofu - in my terminal, rofi, firefox, etc.

They show up in `fc-list`:
```
nikola@work-x1c-mx19 ~ » fc-list | grep -i "iosevka nerd font complete"                           
/home/nikola/.local/share/fonts/NerdFonts/Iosevka Nerd Font Complete.ttf: Iosevka,Iosevka Nerd Font:style=Regular,Book
/home/nikola/.local/share/fonts/NerdFonts/Iosevka Nerd Font Complete Mono.ttf: Iosevka,Iosevka Nerd Font Mono:style=Regular,Book
```

Also, emojis match on `fc-match` (i've tried https://gist.github.com/cole-h/8aab0ed9d65efe38496e8e27b96b6a3d just with "Iosevka Nerd Font" instead of Noto font):
```
nikola@work-x1c-mx19 ~ » fc-match --sort emoji
Iosevka Nerd Font Complete.ttf: "Iosevka" "Regular"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
Arial.ttf: "Arial" "Regular"
fonts-japanese-gothic.ttf: "VL Gothic" "regular"
wqy-microhei.ttc: "WenQuanYi Micro Hei" "Regular"
FreeSans.ttf: "FreeSans" "Regular"
FreeMono.ttf: "FreeMono" "Regular"
FreeSerif.ttf: "FreeSerif" "Regular"
opens___.ttf: "OpenSymbol" "Regular"
MathJax_AMS-Regular.otf: "MathJax_AMS" "Regular"
...
...
```

My `sakura` config:
```
[sakura]
background=none
font=Iosevka Nerd Font,monospace 11
show_always_first_tab=No
scrollbar=false
resize_grip=false
closebutton=true
tabs_on_bottom=false
less_questions=false
audible_bell=Yes
visible_bell=No
blinking_cursor=No
cursor_type=VTE_CURSOR_SHAPE_BLOCK
word_chars=-A-Za-z0-9,./?%&#_~
palette=xterm
...
...
```

My `userChrome.css` setup for Firefox:
```
/* #tabbrowser-tabs, #navigator-toolbox, menuitem, menu, ... */
* {
    font-family: "Iosevka Nerd Font Mono" !important;
    font-size: 16px !important;
}
```

So, all my software loads the font properly, but `sakura` and `rofi` don't display emojis. Please note this `font=Iosevka Nerd Font,monospace 11` line in `sakura.conf`. I've tried changing it to `font=Iosevka Nerd Font Mono,monospace 11` but that doesn't help - only messes up letters with dots like `i` and `j`.

#### 🔧 Your Setup

- I'm using `Iosevka Term Nerd Font Complete.ttf`
- Running `sakura` (also tried `xfce4-terminal` and `alacritty`)
- Linux (MXLinux 19, Linux work-x1c-mx19 5.5.0-2.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.5-3.1~buster (2020-02-06) x86_64 GNU/Linux)

#### ★ Optional

`firefox` in urlbar:
<img width="400" src="https://user-images.githubusercontent.com/3995223/75080722-185e7200-550d-11ea-97d5-57df90ec83b2.png" />
`firefox` on a page:
<img width="400" src="https://user-images.githubusercontent.com/3995223/75080725-18f70880-550d-11ea-8deb-dfcaaed7e7ca.png" />

`sakura`:
![desktop-20200222-005042](https://user-images.githubusercontent.com/3995223/75080986-fdd8c880-550d-11ea-8bed-470cd70fae5f.png)

`vim` with `vim-devicons`:
<img width="400" src="https://user-images.githubusercontent.com/3995223/75080891-b18d8880-550d-11ea-9981-583af3053c44.png" />

EDIT 2020-04-11: also tried `alacritty`

**Comment by ryanoasis** [comment]
Thanks for the report and the details, I would need some time to unpack things here

**Comment by maricn** [comment]
Could anyone give me a hand here pls? I'm still experiencing this issue...

**Comment by maricn** [comment]
This solves my problem - https://github.com/alacritty/alacritty/issues/153#issuecomment-630636358.

Now I fallback to "Noto Color Emoji" (full color emojis), which fallbacks to "Twitter Color Emoji" (which shows outlines in alacritty and st, but full color in sakura).

**Comment by adsick** [comment]
Wow, thanks a lot, bro. my attempts to configure Iosevka Nerd font were not successful and I was getting this ***:
![image](https://user-images.githubusercontent.com/24528839/140616852-5ce24a77-7867-4b76-a705-5b1c5b46fcb4.png)
but then I looked at your config and now it's ok!
