### ISSUE TITLE
Text list of nerdfont characters

### ISSUE THREAD

**Issue by ranebrown** [ryanoasis/nerd-fonts#448]
Is there a full list of all nerdfont characters available similar to http://www.unicode.org/Public/UNIDATA/UnicodeData.txt? I'm looking for something that could be used with Unicode.vim. See https://github.com/chrisbra/unicode.vim/issues/39.

**Comment by ryanoasis** [comment]
Hey, at first I was going to suggest https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/test-fonts.sh but that isn't for parsing just a formatted visually grep-able table.

https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/lib/i_all.sh is probably the closest script to get a list of characters but probably still not quite what you're looking for but likely needs to be tweaked as it's mostly a convenience for having variables represent the glyphs

**Comment by meased** [comment]
I was looking for this as well. I couldn't find it so I made a quick script that parses the files mentioned above and outputs a nicer file with just the icon and the name of the icon. I posted it at https://gitlab.com/dmease/nerd-font-dmenu.

You can generate the file yourself, or just grab `nerdfont.map` from my repo and be done with it.

**Comment by Jake-Gillberg** [comment]
Done again here, in the format like:

```
e717 dev github full                                                                                      
e718 dev nodejs small                                                                                     
e719 dev nodejs                                                                                           
e71a dev hackernews  
```

**Comment by Finii** [comment]
?! Reminds me of https://github.com/ryanoasis/nerd-fonts/issues/1059#issuecomment-1404891287

The next comments have the commands how to create the lists. Very easy. What do you need?
And of course with hex numbers ;-)

**Comment by mochaaP** [comment]
Hey @Finii, I changed it to return the glyphs directly.

I'm wondering can we have a list (preferably csv) in the repository or in the releases? Currently the only stable way to do that is parsing the scripts in `bin/scripts/lib/` or parsing the CSS. If those metadata could be provided, integrations can update their codepoints easily in case a future breaking change occurs.

**Comment by Finii** [comment]
@mochaaP Creating such a list is very easy for Nerd Fonts (*). We just need to define how it shall look like. It can then be autocreated by the CI on any changes and be part of the Release packages.

Must admit did not read all the text above very carefully. Just define some format all people can live with. And then I also like `csv` but nowadays everyone uses `jq` and it _does_ have its benefits, so maybe json? This all depends of course what the **use** of the list is :-D

Looking on the original poster above the UNIDATA list looks like this

```
00AC;NOT SIGN;Sm;0;ON;;;;;N;;;;;
00AD;SOFT HYPHEN;Cf;0;BN;;;;;N;;;;;
00AE;REGISTERED SIGN;So;0;ON;;;;;N;REGISTERED TRADE MARK SIGN;;;;
00AF;MACRON;Sk;0;ON;<compat> 0020 0304;;;;N;SPACING MACRON;;;;
00B0;DEGREE SIGN;So;0;ET;;;;;N;;;;;
```

Hmm, colon separated values ;-)

> return the glyphs directly

I'm not sure if putting the glyphs directly into the file is a good idea :thinking: Otoh we have it in the `i_*.sh` also.



(*) I mean, we autocreate everything from the names stored in the font files: `i_*.sh`, `css`, `cheat-sheet`, ... It's a bit convoluted, but the data ORIGIN is the font files itselfs.

**Comment by Finii** [comment]
@mochaaP 
 
Is this a good format an data?

```
23fb nf-iec-power
23fc nf-iec-toggle_power
23fd nf-iec-power_on
23fe nf-iec-sleep_mode
2665 nf-oct-heart
26a1 nf-oct-zap
2b58 nf-iec-power_off
e000 nf-pom-clean_code
e001 nf-pom-pomodoro_done
e002 nf-pom-pomodoro_estimated
e003 nf-pom-pomodoro_ticking
e004 nf-pom-pomodoro_squashed
e005 nf-pom-short_pause
e006 nf-pom-long_pause
e007 nf-pom-away
e008 nf-pom-pair_programming
e009 nf-pom-internal_interruption
e00a nf-pom-external_interruption
e0a0 nf-pl-branch
e0a1 nf-pl-current_line
e0a1 nf-pl-line_number
e0a2 nf-pl-hostname
e0a2 nf-pl-readonly
e0a3 nf-ple-column_number
e0a3 nf-ple-current_column
e0b0 nf-pl-left_hard_divider
e0b1 nf-pl-left_soft_divider
e0b2 nf-pl-right_hard_divider
e0b3 nf-pl-right_soft_divider
e0b4 nf-ple-right_half_circle_thick
e0b5 nf-ple-right_half_circle_thin
e0b6 nf-ple-left_half_circle_thick
e0b7 nf-ple-left_half_circle_thin
e0b8 nf-ple-lower_left_triangle
e0b9 nf-ple-backslash_separator
e0ba nf-ple-lower_right_triangle
e0bb nf-ple-forwardslash_separator
e0bc nf-ple-upper_left_triangle
e0bd nf-ple-forwardslash_separator_redundant
e0be nf-ple-upper_right_triangle
[...]
```

What would be the name for that list in the repo? Where to put it?

**Comment by Finii** [comment]
@mochaaP Hmm, I believe your list at https://nerd-fonts-glyph.deno.dev/ is wrong? The 5 hex-digit `nf-md-*` entries have wrong codepoints?

Copy and pasted from the `raw` view

![grafik](https://user-images.githubusercontent.com/16012374/222372941-bb9370dc-f00f-4f66-9784-33ed317457d6.png)

Or here:

![grafik](https://user-images.githubusercontent.com/16012374/222373439-264b65f4-fcc7-4e79-8071-c27801b65192.png)

**Comment by mochaaP** [comment]
Thanks for the feedback! On it.

**Comment by Finii** [comment]
If you like we can put your generator into this repo and activate a workflow for it so that it is always automatically updated.
In this way I do not need to write my own ;-)

**Comment by Finii** [comment]
The changes to the CSS script are so simple, I just added writing a json to that script.
Thanks for the comments and inspriation @mochaaP !

**Comment by Finii** [comment]
Also add a bit of meta information, hope this is useful:

![image](https://user-images.githubusercontent.com/16012374/222421150-70367287-646a-434e-9b44-591e8fa259c5.png)

**Comment by mochaaP** [comment]
Glad to hear that! 😀
I'm pointing nerd-fonts-glyph.deno.dev to that JSON now.

**Comment by Finii** [comment]
> I'm pointing nerd-fonts-glyph.deno.dev to that JSON now.

Note that I dropped the `nf-` prefix, so that is not 100% compatible.
Tell me if it would be better to have the prefix; I thought it is pointless.

**Comment by Finii** [comment]
Unrelated comment...

This is so ridiculous:

![image](https://user-images.githubusercontent.com/16012374/222431724-d06f145f-e304-4777-9d9e-26531288d4a2.png)

The small arrows are in fact bigger than the non-small arrows, because all glyphs are individually scaled. Maybe we should fix that one group at least.
