### ISSUE TITLE
problem with segmentation not on the terminal but in whole gnome

### ISSUE THREAD

**Issue by MsAfro12** [ryanoasis/nerd-fonts#450]
After installation nerd-font-complete in linux manjaro i have to big spaces on gnome shel like prompt in callendar or clock on cetner bar, and only on matcha family theme. If i change font in gnome gtk3 config to something else still bar and prompts use font from top bar
![Zrzut ekranu z 2020-03-11 19-39-28](https://user-images.githubusercontent.com/58358907/76452433-690d1080-63d1-11ea-999a-765fa8881f38.png)

**Comment by Finii** [comment]
Fixed by one of the #1045 #1062
