### ISSUE TITLE
Add ligatures to DejaVu Sans Mono

### ISSUE THREAD

**Issue by giggio** [ryanoasis/nerd-fonts#452]
#### 🔧 Your Setup

- _Which font are you using?_
- _Which terminal emulator are you using?_
`DejaVuSansMono NF` and `DejaVuSansMono Nerd Font Mono`
- _Are you using OS X, Linux or Windows?_
Latest Windows 10 with Microsoft Terminal

#### ★ Optional

You can see Ligatures for `=>` are not showing (this is with `DejaVuSansMono Nerd Font Mono`):
![image](https://user-images.githubusercontent.com/334958/76987787-8175b180-6922-11ea-9d8c-041e455fbb9e.png)

**Comment by Finii** [comment]
Well, that policy changed
* #977 

So now all patched fonts preserve the ligatures.

But the original font does not have ligatures:

![image](https://user-images.githubusercontent.com/16012374/216779458-fbabd4b8-1820-4eb7-ba20-83c9ae8ba7c8.png)

Why do you think that ligatures should be there?
No ligatures mentioned on their homepage: https://github.com/dejavu-fonts/dejavu-fonts
