### ISSUE TITLE
golang icon error

### ISSUE THREAD

**Issue by sain801028** [ryanoasis/nerd-fonts#453]
I use Manjaro  Linux 19.0.2
I use v.2.1.0 FiraCode.zip
I user FuraCOde Nerd Font Bold

![螢幕快照_2020-03-25_02-34-59](https://user-images.githubusercontent.com/17377422/77508660-9631d800-6e41-11ea-981d-13369b5cecc0.png)

**Comment by ryanoasis** [comment]
@sain801028 Can I ask what was the issue?

that glyph looks like a different character (not in Nerd Fonts)
