### ISSUE TITLE
How to install all DejaVu font variations at once using git?

### ISSUE THREAD

**Issue by in2Rafi** [ryanoasis/nerd-fonts#454]
I want to install Dejavu fonts but I don't see any single download link. There are seperate folders to download font variations Bold, Italic etc. But I want to download all these variations at once. I am on windows and use vim.

#### 🗹 Requirements

- [ ] A brief but descriptive _title_ of your issue
- [ ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [ ] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ ] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_

**Comment by ryanoasis** [comment]
The only way to do this currently is from the [release page](https://github.com/ryanoasis/nerd-fonts/releases/latest)

you can download dejavu as an archive: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/DejaVuSansMono.zip

closing for now, thanks.
