### ISSUE TITLE
Update Iosevka to 2.3.3

### ISSUE THREAD

**Issue by rafi** [ryanoasis/nerd-fonts#455]
It would be great if anybody has the time to upgrade Iosevka to 2.3.3 https://github.com/be5invis/Iosevka/releases/tag/v2.3.3

Thanks :)

**Comment by FollieHiyuki** [comment]
I use Iosevka and am having some free time. I will try taking the job and bumping to 5.0.3 :)

@ryanoasis 1 question: how should I change `config.json` file? Iosevka has added quite a few ligatures over the years I believe.

Sorry for the ping, I know nothing about font customizing and stuff.
