### ISSUE TITLE
"FuraCode" bugged in Windows Terminal

### ISSUE THREAD

**Issue by privacyguy123** [ryanoasis/nerd-fonts#456]
I've posted the bug over there too - not sure if this is a font issue or Terminal issue anymore.

What I can't get my head round is these fonts looking totally different as well? Aren't they the same font essentially? I think Fura looks a lot more pleasing to the eyes.

![image](https://user-images.githubusercontent.com/50337995/77956135-49c71c00-72c9-11ea-954b-1e21a28a930f.png)

**Comment by marblewraith** [comment]
Doesn't that depend on how the font is being rendered? For example if it's using direct write, also what kind of aliasing method is being used if any?

**Comment by privacyguy123** [comment]
As far as I understood, the 2 fonts are based on the same thing (FiraCode) so what makes them look so different?

**Comment by paulorsjr** [comment]
First the ligatures, FiraCode NF draws them correctly:

![image](https://user-images.githubusercontent.com/10064019/78559584-03068400-77eb-11ea-97bf-de6ea20cd457.png)

FuraCode NF does not:

![image](https://user-images.githubusercontent.com/10064019/78559636-1ca7cb80-77eb-11ea-9553-c0a6978b5c71.png)

Then, the font appearance as a whole, FiraCode NF:

![image](https://user-images.githubusercontent.com/10064019/78559770-5678d200-77eb-11ea-9cf7-6dbaef05f06e.png)

FuraCode NF:
![image](https://user-images.githubusercontent.com/10064019/78559843-77d9be00-77eb-11ea-8a5a-08b6e4651b3b.png)

These snips were taken using the same default rendering method in Windows Terminals.

**Comment by privacyguy123** [comment]
This is the exact bug I've reported over on the Windows Terminal Github - they are saying it's an issue on their end and not nerdfonts ... however, this doesn't explain how different these 2 fonts look, I'm not understanding why?

**Comment by privacyguy123** [comment]
Bump?

**Comment by privacyguy123** [comment]
Repatching my own Fira Code file with the font-patcher fixed this visual bug for me.

**Comment by Luiz-Monad** [comment]
I have this same problem 
![image](https://user-images.githubusercontent.com/4574729/202925078-14db8bf8-5591-4b52-87d5-45d81270889b.png)

Affected:
Windows Notepad 11.2209.6.0
Microsoft Visual Studio Community 2022 (64-bit) Version 17.2.4
VsCode Version: 1.73.1
Windows Terminal 1.16.2642

**Comment by Finii** [comment]
> so what makes them look so different?

> First the ligatures, FiraCode NF draws them correctly:

Well, Fira had a RFN some years back. So the patched font needed to change the name to Fura.
Then the RFN had been dropped from the license.

I believe I remember that we had both (Fira NF and Fura NF) in the repo because the old fonts were not removed on an update.
There is no Fura anymore since some time.

> I have this same problem

I guess @Luiz-Monad means the `==` ligature? There were a lot fixes meanwhile, I guess that is fixed. Please try the new release 3.0.0. Please raise a new Issue if the problem persists.
