### ISSUE TITLE
the height of  Aurulent Sans Mono Nerd font

### ISSUE THREAD

**Issue by glepnir** [ryanoasis/nerd-fonts#458]
#### 🗹 Requirements

- [ ] A brief but descriptive _title_ of your issue
- [ ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [ ] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ ] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ 
          AurulentSansMono Nerd Font Mono
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
        iterm2
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
         macos 10.15.4
#### ★ Optional
   set the iterm2 font ` AurulentSansMono Nerd Font Mono`
   then open vim

   
![image](https://user-images.githubusercontent.com/41671631/78333709-eab12200-75bc-11ea-81d0-baff33f7db01.png)

**Comment by taigacute** [comment]
The problem is the inverted slant symbol，Normal slant works fine。
![image](https://user-images.githubusercontent.com/41671631/78336104-657c3c00-75c1-11ea-92b2-940e83eae718.png)

**Comment by ryanoasis** [comment]
Were you able to find a solution?
