### ISSUE TITLE
Sauce Code Powerline Fonts?

### ISSUE THREAD

**Issue by AustinMatherne** [ryanoasis/nerd-fonts#46]
First, thanks for the project, it has significantly improved my development experience.

With the 0.6.0 release the Sauce Code Pro Powerline fonts appears to have vanished from under patched-fonts. Was that intentional?

Thank again!

**Comment by ryanoasis** [comment]
Thanks glad to hear feedback.

Nope! It was not intentional. I was too eager to push it out without testing multiple fonts.

I will look into this :+1:

**Comment by ryanoasis** [comment]
@AustinMatherne They are still there it is just the names of the fonts have been changed (hopefully for the better).

Try one of the "complete" versions (includes all glyphs):

e.g. https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/SourceCodePro/Regular/complete/Sauce%20Code%20Pro%20Nerd%20Font%20Complete.ttf

Actually even the "minimal" variations should by default have the Powerline glyphs.

Let me know if I misunderstood or if this solves your question. Cheers :smile:

**Comment by AustinMatherne** [comment]
Thanks! I was previously specifying the exact font (Sauce Code Powerline Plus...) in my .Xresources config. Replacing it with just "Sauce Code Pro" did the trick.

Out of curiosity, why the switch from OTF to TTF?
