### ISSUE TITLE
Question Mark (U+003F) ? of gohu nerd font is flipped vertically

### ISSUE THREAD

**Issue by OrcaXS** [ryanoasis/nerd-fonts#460]
#### 🎯 Subject of the issue
I've also checked the original gohu font and the question mark orientation is correct there.

#### 🔧 Your Setup

`GohuFont Nerd Font Complete.ttf`, using iterm2 on macOS.  

![image](https://user-images.githubusercontent.com/1764123/78568025-1a2d8c00-7854-11ea-859c-af05ee2c7430.png)

**Comment by ryanoasis** [comment]
Thanks for finding this...

I think you partly correct, it is correct in the original gohu font but not in the original latin1 gohu font (non unicode one).

### gohu latin1 nerd font vs gohu latin1

![Selection_040](https://user-images.githubusercontent.com/8083459/79034494-21fa7280-7b6b-11ea-9826-a0a14a2fe0e6.png)

### gohu unicode nerd font vs gohu unicode

![Selection_041](https://user-images.githubusercontent.com/8083459/79034493-1e66eb80-7b6b-11ea-82ed-8d756bfaf615.png)

Can you try the unicode one? https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Gohu/uni-14/complete ?

closing for now

**Comment by OrcaXS** [comment]
OK, I can confirm the `GohuFont Nerd Font Complete Mono` uni14 contains the correct glyph. Thanks.
