### ISSUE TITLE
Update Fira Code to latest version

### ISSUE THREAD

**Issue by gitfool** [ryanoasis/nerd-fonts#464]
#### 🎯 Subject of the issue

A newer version of Fira Code was recently [released](https://github.com/tonsky/FiraCode/releases) and it would be nice to update the nerd fonts too.

#### 🔧 Your Setup

- Fira Code * Nerd Font Complete Windows Compatible.ttf
- Windows Terminal 1.0.1402.0
- Windows 10 2004

**Comment by SharakPL** [comment]
Also please make sure Retina version is available in terminals. I can set all styles of original Fira Code 3.1 in Powershell. I also can use FiraCode NF 2.0.1 there, but FiraCode NF Retina 2.0.1 is not available 😢

**Comment by j1nxie** [comment]
I think this should be changed to "Update Fira Code to v4", considering Fira Code was freshly updated to v4 only a few hours ago.

**Comment by gitfool** [comment]
Note: I added the patched fonts to the above PR in `FiraCode.zip` for anyone that wants to try it.;
