### ISSUE TITLE
Arch linux icon  has (TM) at the end

### ISSUE THREAD

**Issue by AtifChy** [ryanoasis/nerd-fonts#467]
#### 🎯 Subject of the issue

Arch linux icon has (TM) at the end 

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
Fira Mono Nerd Font Complete.ttf
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
konsole
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Linux

**Comment by ryanoasis** [comment]
Nerd Fonts consumes most of the OS logos from [font-logos](https://github.com/lukas-w/font-logos). Arch is one from font-logos, this would be an upstream issue there not here. Thanks though!
