### ISSUE TITLE
Inconsolata Nerd Font 2.1.0 U+FB01 ligature renders improperly

### ISSUE THREAD

**Issue by hakamadare** [ryanoasis/nerd-fonts#469]
#### 🎯 Inconsolata Nerd Font 2.1.0 U+FB01 ligature renders improperly

After upgrading to Inconsolata Nerd Font 2.1.0, I see the "fi" ligature replaced by what looks like an icon of a telephone?  See attached screenshots.  I've reproduced this in iTerm2 3.3.7, VimR 0.32.0, and Chrome 81.0.4044.113.  In each case disabling ligatures makes the characters render correctly.

I installed the font via the Homebrew [Cask](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-inconsolata-nerd-font.rb).

#### 🔧 Your Setup

- _Inconsolata Nerd Font Complete.otf_
- _iTerm2, VimR, Chrome_
- _OS X 10.15.4_

#### ★ Optional

* sample text [ligatures.txt](https://github.com/ryanoasis/nerd-fonts/files/4511929/ligatures.txt)
* ligatures enabled (default) <img width="906" alt="bad" src="https://user-images.githubusercontent.com/154395/79900233-ed44b180-83db-11ea-8dd5-bd8f897f4fd6.png">
* ligatures disabled via CSS <img width="973" alt="good" src="https://user-images.githubusercontent.com/154395/79900263-fd5c9100-83db-11ea-8f9f-ce09cb950a31.png">

**Comment by hakamadare** [comment]
the same issue also occurs in Inconsolata Nerd Font Mono Complete.otf from the same release (but the phone icon is smaller?)

**Comment by anvarich** [comment]
same here with fl symbols glytch as described here https://github.com/ryanoasis/nerd-fonts/issues/477

**Comment by 0xRainy** [comment]
I also am experiencing this issue

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
Inconsolata NF
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
WindowsTerminal and Neovide
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Windows10 Build 2004

**Comment by Finii** [comment]
This should have been fixed by https://github.com/ryanoasis/nerd-fonts/pull/711.

I'm not sure which files are patched with that PR in place, maybe the v2.2.0RC has them already, else please use the font files directly from the repo: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts
