### ISSUE TITLE
Fira Code 1.2 font style?

### ISSUE THREAD

**Issue by privacyguy123** [ryanoasis/nerd-fonts#475]
Long story short I prefer the style of 1.2 compared to 2 or 3 - is it possible to have all the benfits of 3 rolled into the old 1.2 "style"? 

Perhaps you guys could share the specifics of the font so I could edit it myself somehow?

**Comment by FredHappyface** [comment]
I'd think it might be best to ask upstream. I'd think you could (hopefully) do it in these steps

Get Fira Code 1.2 and 3 (5 is out now if you'd prefer that) from upstream

Use software like font forge to apply the V3 ligatures to 1.2 (I've only used font forge for things like making glyphs italic/ bold so I'm not sure how one would go about that - I would assume copy and paste?)

Use the nerd-fonts font patcher to apply the extended glyphs

Hope that helps

**Comment by Finii** [comment]
Sorry have to day what @FredHappyface says is the only way to go.
