### ISSUE TITLE
Can not install Caskaydia fonts manually; "invalid font" error

### ISSUE THREAD

**Issue by ShrykeWindgrace** [ryanoasis/nerd-fonts#476]
#### 🎯 Subject of the issue
Can not install Caskaydia fonts manually; "invalid font" error.

I downloaded directly "windows-compatible" versions of this font and then double-clicked on them. Got a "windows font viewer" error "The requested file `full path to the ttf file`" is not a valid font file".

Issue is present for both master and 2.1.0 branches.

#### 🔧 Your Setup
win10, winver==1809

**Comment by Marvinoo** [comment]
Same happens with the Arimo font

![isgQYHyE39](https://user-images.githubusercontent.com/45720537/95060447-923d1780-06fa-11eb-8d10-c40d53f43e54.gif)

Plz HELP

**Comment by Marvinoo** [comment]
> 
> #### 🎯 Subject of the issue
> 
> Can not install Caskaydia fonts manually; "invalid font" error.
> 
> I downloaded directly "windows-compatible" versions of this font and then double-clicked on them. Got a "windows font viewer" error "The requested file `full path to the ttf file`" is not a valid font file".
> 
> Issue is present for both master and 2.1.0 branches.
> #### 🔧 Your Setup
> 
> win10, winver==1809



> 
> 
> Same happens with the Arimo font
> 
> ![isgQYHyE39](https://user-images.githubusercontent.com/45720537/95060447-923d1780-06fa-11eb-8d10-c40d53f43e54.gif)
> 
> Plz HELP


Problem solved. 
It turns out that when I download the font files directly they get corrupted but when I downloaded the whole repo (1.02GB) and unzipped the files then tried again to install the desired fonts, they were installed smoothly.

**Comment by ShrykeWindgrace** [comment]
@Marvinoo thanks for this workaround! I will try it later with Cascaydia fonts and report my experience.

**Comment by ryanoasis** [comment]
I think we can mark this as closed. Sounds like something was likely corrupted while downloading.

I tested Arimo on windows 10 and seemed fine to me.

![Selection_095](https://user-images.githubusercontent.com/8083459/146714928-ea028259-2a2c-4ab8-997e-bbb4bed678ed.png)
