### ISSUE TITLE
[Suggestion] Improve icons-only "Symbols Nerd Font"

### ISSUE THREAD

**Issue by hpfr** [ryanoasis/nerd-fonts#479]
The implementation of the icons-only font in #84 is very useful, and I think it could be improved.

1. Based on 3b5dff7, it appears the icons-only font is just a ttf file in `src/glyphs`. Instead of just providing the ttf in the repo, could you somehow leverage the standard patcher and just provide an empty font as input? Or maybe you could add an option to the patcher like `--no-input`? I'm not sure of the best way to go about it since I'm not familiar with the code, but this way, the icons-only font won't get out of date and will keep up with all the other Nerd Fonts. Right now, I think the icons-only ttf is missing the Crystal icon added in `original-source.otf` in 3bdc094, based on the fact that it was added 4 months ago and the ttf's are from 2 years ago. Scripting them like the other Nerd Fonts would eliminate this problem. Also, should you generate otf's instead of ttf's since they have more features? Since it's just icons, you get to choose, right? I guess you could even do both.
2. Generate proportional and monospaced variants as with standard Nerd Fonts, i.e. "Symbols Nerd Font" and "Symbols Nerd Font Mono". This would allow users to select the proportional font for use outside of monospaced contexts (terminal emulators) to get full-size icons. For example, in window manager status bars.
3. Provide these two font variants in the releases instead of burying them in the repo for users to find ;D.

Thank you for your work on this excellent project!

**Comment by polyzen** [comment]
> Right now, I think the icons-only ttf is missing the Crystal icon added in original-source.otf in 3bdc094, based on the fact that it was added 4 months ago and the ttf's are from 2 years ago.

This PR has the symbols fonts rebuilt for recent changes: https://github.com/ryanoasis/nerd-fonts/pull/461

> Scripting them like the other Nerd Fonts would eliminate this problem.

👍

**Comment by ryanoasis** [comment]
Yes good suggestions and you are totally right that right now they are buried and easily out dated

**Comment by hpfr** [comment]
Cool, it looks like 1 and 3 will be taken care of thanks to #461 in the next release. Is that coming up anytime soon?

Does the `2048` variant address point 2? I'm guessing that's full-width non-monospaced icons?

**Comment by ryanoasis** [comment]
> Is that coming up anytime soon?

😟 I don't want to promise anything, I'm catching up on PRs but yeah the releases have been really poor lately. Hoping to automate things and just release monthly or something. Since you asked

The 2048 is just the em size, good question on monospaced vs non. I believe currently both symbol only fonts are non-monospaced 🤔

**Comment by hpfr** [comment]
> I don't want to promise anything

No problem; I was just curious :)

> currently both symbol only fonts are non-monospaced

Is it possible to make a monospaced symbols-only font? I'm interested in just installing one monospaced symbols-only font (which my terminal can fall back to from my text font) since I change monospaced fonts often and don't want to install the entire 2GB of Nerd fonts on my system.

**Comment by polyzen** [comment]
You can try the 1000-em symbols fonts along with the font configuration file:
https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/Symbols-1000-em%20Nerd%20Font%20Complete.ttf
https://github.com/ryanoasis/nerd-fonts/blob/master/10-nerd-font-symbols.conf

Here's an example package available in Arch and its derivatives (seems I've named the 1000-em font incorrectly if it's not monospaced):
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/ttf-nerd-fonts-symbols
https://git.archlinux.org/svntogit/community.git/tree/trunk/ttf-nerd-fonts-symbols.install?h=packages/ttf-nerd-fonts-symbols

**Comment by hpfr** [comment]
Glad to see you're back working on release automation @ryanoasis. Just checking in to make sure the fixed- and double-width symbols-only fonts will be first-class citizens of the new automated GitHub Actions releases? I think this issue can be closed if that's the case.

**Comment by ryanoasis** [comment]
@hpfr hey! thanks. Actually I had forgotten about this but yeah it definitely needs to happen. Automation is key to making this monster somewhat maintainable going forward 😬

**Comment by ryanoasis** [comment]
@hpfr They are basically "first-class citizens" now: 

https://github.com/ryanoasis/nerd-fonts/blob/877887cac2d6ccc7354a8d95e8c39fff10bf120b/bin/scripts/lib/fonts.json#L363-L378 which is used to build the matrix of the fonts in the release

![Selection_099](https://user-images.githubusercontent.com/8083459/148709046-1a17f9da-0c9a-4a15-8a52-8580cf96fd0c.png)

**Comment by ryanoasis** [comment]
This ticket can be closed with `2.2.0` release as the files have been moved to the `patched-fonts/` directory AND added to the release process which will build all fonts (including the symbol only ones)
