### ISSUE TITLE
Typo in FiraCode in v2.1.0 github release

### ISSUE THREAD

**Issue by eNV25** [ryanoasis/nerd-fonts#480]
That's a typo in the bottom half right?
26/01/2020  07:52         3.471.216 Fira Code Bold Nerd Font Complete Mono Windows Compatible.otf
26/01/2020  07:47         1.141.572 Fira Code Bold Nerd Font Complete Mono Windows Compatible.ttf
26/01/2020  07:47         3.471.168 Fira Code Bold Nerd Font Complete Mono.otf
26/01/2020  07:28         1.141.528 Fira Code Bold Nerd Font Complete Mono.ttf
26/01/2020  07:49         2.341.084 Fira Code Bold Nerd Font Complete Windows Compatible.otf
26/01/2020  07:37         1.168.504 Fira Code Bold Nerd Font Complete Windows Compatible.ttf
26/01/2020  07:27         2.341.000 Fira Code Bold Nerd Font Complete.otf
26/01/2020  07:18         1.168.432 Fira Code Bold Nerd Font Complete.ttf
26/01/2020  07:52         3.471.792 Fira Code Light Nerd Font Complete Mono Windows Compatible.otf
26/01/2020  07:47         1.102.304 Fira Code Light Nerd Font Complete Mono Windows Compatible.ttf
26/01/2020  07:47         3.471.744 Fira Code Light Nerd Font Complete Mono.otf
26/01/2020  07:29         1.102.260 Fira Code Light Nerd Font Complete Mono.ttf
26/01/2020  07:49         2.338.196 Fira Code Light Nerd Font Complete Windows Compatible.otf
26/01/2020  07:37         1.129.232 Fira Code Light Nerd Font Complete Windows Compatible.ttf
26/01/2020  07:27         2.338.112 Fira Code Light Nerd Font Complete.otf
26/01/2020  07:18         1.129.160 Fira Code Light Nerd Font Complete.ttf
26/01/2020  07:52         3.474.580 Fira Code Medium Nerd Font Complete Mono Windows Compatible.otf
26/01/2020  07:47         1.111.908 Fira Code Medium Nerd Font Complete Mono Windows Compatible.ttf
26/01/2020  07:47         3.474.532 Fira Code Medium Nerd Font Complete Mono.otf
26/01/2020  07:29         1.111.868 Fira Code Medium Nerd Font Complete Mono.ttf
26/01/2020  07:49         2.342.644 Fira Code Medium Nerd Font Complete Windows Compatible.otf
26/01/2020  07:37         1.138.840 Fira Code Medium Nerd Font Complete Windows Compatible.ttf
26/01/2020  07:28         2.342.560 Fira Code Medium Nerd Font Complete.otf
26/01/2020  07:18         1.138.768 Fira Code Medium Nerd Font Complete.ttf
26/01/2020  07:52         3.475.044 Fira Code Regular Nerd Font Complete Mono Windows Compatible.otf
26/01/2020  07:47         1.116.128 Fira Code Regular Nerd Font Complete Mono Windows Compatible.ttf
26/01/2020  07:47         3.475.004 Fira Code Regular Nerd Font Complete Mono.otf
26/01/2020  07:29         1.116.092 Fira Code Regular Nerd Font Complete Mono.ttf
26/01/2020  07:49         2.341.216 Fira Code Regular Nerd Font Complete Windows Compatible.otf
26/01/2020  07:37         1.143.060 Fira Code Regular Nerd Font Complete Windows Compatible.ttf
26/01/2020  07:27         2.341.136 Fira Code Regular Nerd Font Complete.otf
26/01/2020  07:18         1.142.992 Fira Code Regular Nerd Font Complete.ttf
26/01/2020  07:52         3.471.480 Fira Code Retina Nerd Font Complete Mono Windows Compatible.otf
26/01/2020  07:47         1.112.076 Fira Code Retina Nerd Font Complete Mono Windows Compatible.ttf
26/01/2020  07:47         3.471.432 Fira Code Retina Nerd Font Complete Mono.otf
26/01/2020  07:28         1.112.036 Fira Code Retina Nerd Font Complete Mono.ttf
26/01/2020  07:49         2.338.872 Fira Code Retina Nerd Font Complete Windows Compatible.otf
26/01/2020  07:37         1.139.008 Fira Code Retina Nerd Font Complete Windows Compatible.ttf
26/01/2020  07:27         2.338.788 Fira Code Retina Nerd Font Complete.otf
26/01/2020  07:18         1.138.936 Fira Code Retina Nerd Font Complete.ttf
03/11/2019  17:54         3.434.588 Fura Code Bold Nerd Font Complete Mono Windows Compatible.otf
03/11/2019  17:54         1.047.520 Fura Code Bold Nerd Font Complete Mono Windows Compatible.ttf
03/11/2019  17:54         3.434.540 Fura Code Bold Nerd Font Complete Mono.otf
03/11/2019  17:54         1.047.476 Fura Code Bold Nerd Font Complete Mono.ttf
03/11/2019  17:54         2.295.108 Fura Code Bold Nerd Font Complete Windows Compatible.otf
03/11/2019  17:54         1.064.000 Fura Code Bold Nerd Font Complete Windows Compatible.ttf
03/11/2019  17:54         2.295.024 Fura Code Bold Nerd Font Complete.otf
03/11/2019  17:54         1.063.928 Fura Code Bold Nerd Font Complete.ttf
03/11/2019  17:54         3.482.832 Fura Code Light Nerd Font Complete Mono Windows Compatible.otf
03/11/2019  17:54         1.015.672 Fura Code Light Nerd Font Complete Mono Windows Compatible.ttf
03/11/2019  17:54         3.482.780 Fura Code Light Nerd Font Complete Mono.otf
03/11/2019  17:54         1.015.628 Fura Code Light Nerd Font Complete Mono.ttf
03/11/2019  17:54         2.288.920 Fura Code Light Nerd Font Complete Windows Compatible.otf
03/11/2019  17:54         1.031.920 Fura Code Light Nerd Font Complete Windows Compatible.ttf
03/11/2019  17:54         2.288.836 Fura Code Light Nerd Font Complete.otf
03/11/2019  17:54         1.031.848 Fura Code Light Nerd Font Complete.ttf
03/11/2019  17:54         3.485.264 Fura Code Medium Nerd Font Complete Mono Windows Compatible.otf
03/11/2019  17:54         1.013.264 Fura Code Medium Nerd Font Complete Mono Windows Compatible.ttf
03/11/2019  17:54         3.485.220 Fura Code Medium Nerd Font Complete Mono.otf
03/11/2019  17:54         1.013.224 Fura Code Medium Nerd Font Complete Mono.ttf
03/11/2019  17:54         2.291.812 Fura Code Medium Nerd Font Complete Windows Compatible.otf
03/11/2019  17:54         1.029.516 Fura Code Medium Nerd Font Complete Windows Compatible.ttf
03/11/2019  17:54         2.291.728 Fura Code Medium Nerd Font Complete.otf
03/11/2019  17:54         1.029.444 Fura Code Medium Nerd Font Complete.ttf
03/11/2019  17:54         3.483.720 Fura Code Regular Nerd Font Complete Mono Windows Compatible.otf
03/11/2019  17:54         1.015.020 Fura Code Regular Nerd Font Complete Mono Windows Compatible.ttf
03/11/2019  17:54         3.483.680 Fura Code Regular Nerd Font Complete Mono.otf
03/11/2019  17:54         1.014.984 Fura Code Regular Nerd Font Complete Mono.ttf
03/11/2019  17:54         2.290.192 Fura Code Regular Nerd Font Complete Windows Compatible.otf
03/11/2019  17:54         1.031.272 Fura Code Regular Nerd Font Complete Windows Compatible.ttf
03/11/2019  17:54         2.290.112 Fura Code Regular Nerd Font Complete.otf
03/11/2019  17:54         1.031.204 Fura Code Regular Nerd Font Complete.ttf
03/11/2019  17:54         3.483.636 Fura Code Retina Nerd Font Complete Mono Windows Compatible.otf
03/11/2019  17:54         1.015.948 Fura Code Retina Nerd Font Complete Mono Windows Compatible.ttf
03/11/2019  17:54         3.483.588 Fura Code Retina Nerd Font Complete Mono.otf
03/11/2019  17:54         1.015.908 Fura Code Retina Nerd Font Complete Mono.ttf
03/11/2019  17:54         2.289.984 Fura Code Retina Nerd Font Complete Windows Compatible.otf
03/11/2019  17:54         1.032.200 Fura Code Retina Nerd Font Complete Windows Compatible.ttf
03/11/2019  17:54         2.289.900 Fura Code Retina Nerd Font Complete.otf
03/11/2019  17:54         1.032.128 Fura Code Retina Nerd Font Complete.ttf

**Comment by ryanoasis** [comment]
Ah so I think when we were able to use Fira instead of having to use Fura due to licensing but the old "Fura" fonts must not have been removed prior to generating the build.
