### ISSUE TITLE
v2.1.0: powerline glyphs spill over vertically

### ISSUE THREAD

**Issue by krkhan** [ryanoasis/nerd-fonts#481]
#### 🔧 Your Setup

Have tried with Inconsolata, Monoid, monofur and agave. I'm on Linux with Alacritty. The prbolem repros across all my machines (Arch, Gentoo, Fedora, Ubuntu).

#### ★ Optional

![image](https://user-images.githubusercontent.com/697967/82963523-0a8b1380-9f78-11ea-9f1b-5b77c3946514.png)

![image](https://user-images.githubusercontent.com/697967/82963566-1e367a00-9f78-11ea-825e-0683684235d3.png)

**Comment by krkhan** [comment]
To be clear, I never had luck with these before anyway. nerdfonts would always give me these vertical spills with alacritty, powerline fonts work fine but obviously don't have as much stuff.

**Comment by krkhan** [comment]
Closing this, `SauceCodePro Nerd Font Mono` works without the issue.

**Comment by ryanoasis** [comment]
Thanks for the follow up
