### ISSUE TITLE
Support for Braille Characters?

### ISSUE THREAD

**Issue by dominikheinz** [ryanoasis/nerd-fonts#482]
#### 🎯 Subject of the issue
Just a request/suggestion :)
Would be nice to have an option to add a braille font (https://aur.archlinux.org/packages/ttf-ubraille/)
Some popular tools such as gotop use this font to render pixelart, such as graphs, in the terminal.
An example is shown below.

![image](https://user-images.githubusercontent.com/32770080/83197779-538cc480-a13e-11ea-81ba-5969b9c83372.png)

**Comment by MartenBE** [comment]
Is there any update or solution for this?

**Comment by Karamaz0V1** [comment]
I can't wait to use bpytop!

![Screenshot from 2020-10-28 11-49-32](https://user-images.githubusercontent.com/3886316/97426470-cda2be80-1913-11eb-9b49-166359057538.png)

**Comment by GarlandKey** [comment]
I recommend modifying the existing fonts by adding braille.  The UTF-8 location of the braille fonts should be U+2800 - U+28FF.

**Comment by Chaz6** [comment]
Please can we get braille added!

**Comment by clort81** [comment]
Please also see this braille issue: https://github.com/ryanoasis/nerd-fonts/issues/1064

**Comment by Finii** [comment]
Also moving to Parallel Universe

**Comment by Finii** [comment]
Finally added via

* #1980
