### ISSUE TITLE
Borg-sans-mono patching

### ISSUE THREAD

**Issue by aminya** [ryanoasis/nerd-fonts#483]
#### 🎯 Subject of the issue

It would be nice if you can add more ligatures to borg-sans-mono
https://github.com/marnen/borg-sans-mono

#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

**Comment by marnen** [comment]
If you want more ligatures in Borg Sans Mono, why not open up an issue on the [font repo](https://github.com/marnen/borg-sans-mono) itself?

**Comment by Finii** [comment]
Nerd Fonts is about adding symbols. Ligatures are nothing one can add singlehandedly to a lot of fonts.
So as @marnen pointed out, you need to ask the original font designers. Sorry.
