### ISSUE TITLE
Add font patcher in release

### ISSUE THREAD

**Issue by xsrvmy** [ryanoasis/nerd-fonts#484]
Currently the releases do not contain the font patcher. The only way to download the patcher and its fonts is to manually download, or to use some obscure feature of git or svn to download the individual folder of the patcher. Can this be made into a release?

**Comment by Strahinja** [comment]
It would be great to have some kind of option to cherry-pick only parts of this repository, or a separate `font-patcher`-only repository (with all the necessary files to patch custom fonts). Just a simple `git fetch` takes ages and unnecessary disk space.

**Comment by betaboon** [comment]
i wanted that too and realy didnt feel like downloading 2GB just for the patcher.
until the maintainers found a solution for that i created a repo for that purpose: https://github.com/betaboon/nerd-fonts-patcher
it contains just the minimum required files from this repository.

**Comment by ryanoasis** [comment]
Things are going to be changing. Patcher and it's required files are going to live in a separate repo.

Putting the patcher in the release is still an interesting idea. Releases are one of my main focuses ATM since they are a PITA and really slowing everything down. Have made progress but nothing public yet.

**Comment by ryanoasis** [comment]
> Things are going to be changing. Patcher and it's required files are going to live in a separate repo.

I've for the moment done a 180º upon more consideration, I think now that having the font patcher part of the release solves most/all problems as it'll come bundled with the necessary files. Also moving to a separate repo seems like it'll only cause maintenance issues without providing much benefit. Open to more discussion: #716 

for `2.2.0-RC` see: https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC/FontPatcher.zip
