### ISSUE TITLE
Regression from 2.0.0: icons shifted to the right

### ISSUE THREAD

**Issue by powerman** [ryanoasis/nerd-fonts#485]
#### 🎯 Subject of the issue

Looks like there is a regression since 2.0.0: icons in 2.1.0 doesn't fit their boxes because they're shifted to the right.

#### 🔧 Your Setup

Linux, urxvt with https://github.com/powerman/wcwidth-icons.
I'm using [D2Coding font](https://github.com/naver/d2codingfont/) and initially noticed this issue while trying to use `font-patcher` to update to the latest version both font and icons. But I belive this issue affect all fonts - below screenshots use `3270-Medium Nerd Font Complete.otf` downloaded from 1.2.0, 2.0.0 and 2.1.0 release archive.

#### ★ Optional
```
URxvt*font:             xft:3270Medium Nerd Font:style=Medium:size=24
URxvt*boldFont:         xft:3270Medium Nerd Font:style=Medium:size=24
```

- `3270-Medium Nerd Font Complete.otf` version **1.2.0** (icons shifted left)
![3270-1 2 0-1](https://user-images.githubusercontent.com/1354301/84006188-9afd2700-a96e-11ea-94f8-7be2c304dcaf.png)
![3270-1 2 0-2](https://user-images.githubusercontent.com/1354301/84006190-9b95bd80-a96e-11ea-86d0-3ba5a5a79a24.png)
- `3270-Medium Nerd Font Complete.otf` version **2.0.0** (icons at right position)
![3270-2 0 0-1](https://user-images.githubusercontent.com/1354301/84006191-9c2e5400-a96e-11ea-8de7-e4385d9491c2.png)
![3270-2 0 0-2](https://user-images.githubusercontent.com/1354301/84006192-9c2e5400-a96e-11ea-9ac8-14cc7127d8f8.png)
- `3270-Medium Nerd Font Complete.otf` version **2.1.0** (icons shifted right)
![3270-2 1 0-1](https://user-images.githubusercontent.com/1354301/84006194-9cc6ea80-a96e-11ea-89a9-7de957ad898f.png)
![3270-2 1 0-2](https://user-images.githubusercontent.com/1354301/84006195-9cc6ea80-a96e-11ea-8db4-b6e49d5baae2.png)

For mentioned above D2Coding results are the same: font-patcher from 2.0.0 produce correct font, from current master produce invalid font with icons shifted to the right.

**Comment by umnyaga** [comment]
I found similar issue, Font:"MesloLGS NF", style:regular, size:9 in putty on Windows for symbol 'f43a' (clock). It's shifted right and right portion on the glyph is truncated.

**Comment by qenya** [comment]
Same issue with Fira Code and Fira Code Mono, style=Regular, with every glyph and font size I tried to use.

**Comment by Finii** [comment]
@umnyaga and @qenya Are your issues also related to `urxvt` and/or `wcwidth-icons`.

I would need to install such a thing, I have the gut feeling that might be a `wcwidth` issue.

In the fonts the glyphs are all left aligned.

Maybe you can try the current `v2.3.3` and tell me if it is still an issue.
If so, I would appreciate some more hints about your setup.

This `F4A3` glyph in your images, it IS left aligned in the 'cell' ... :thinking: (of course that is `v2.3.3`)

![image](https://user-images.githubusercontent.com/16012374/216781361-43531de6-73d2-46ba-bc27-c3e5df2b25cd.png)

**Comment by powerman** [comment]
> I would need to install such a thing, I have the gut feeling that might be a `wcwidth` issue.

This is really unlikely. The wcwidth is just one 48-line file in C (so you can easily [review](https://github.com/powerman/wcwidth-icons/blob/master/wcwidth-icons.c) it), and all it does is patch `wcwidth(3)` result (which is int - e.g. char width 1 or 2) for some character codes.

**Comment by Finii** [comment]
I saw the code and thought that can not be all :grimacing: 
But that is only patching the library.
This is all very shady ;-)

So if I understand correctly I build the lib, point `LD_LIBRARY_PATH` or `LD_PRELOAD` to the dir it is in and then I shall the the issue with `xterm` like `LD_LIBRARY_PATH=. xterm --` ... what were the options to set the font? Oh my god all these X86 old school terminals remind me of 1980s and tkl/tk and HP machines :-D

I would really appreciate a dummy howto reproduce.

**Comment by powerman** [comment]
Not to the dir, but to the file - as shown in wcwidth's README: `export LD_PRELOAD=/usr/lib/libwcwidth-icons.so`.

**Comment by powerman** [comment]
Text from screenshots to reproduce:
```
# 
# 
# 
# ♥
```

**Comment by powerman** [comment]
So, test command may be e.g. `LD_PRELOAD=/path/to/libwcwidth-icons.so urxvt --font 'xft:3270Medium Nerd Font:style=Medium:size=24' -e vi /path/to/test-icons.txt`

**Comment by powerman** [comment]
As for xterm - it's probably better to avoid it. :) The option you was looking for is `-fa`, but it looks like xterm ignores `wcwidth(3)` - so LD_PRELOAD has no effect - and instead uses own algorithms for detecting char width (enabled by options `-cjk_width` or `-mk_width`). All of this works really weird at a glance and I don't believe anyone who wants nice modern icons still works in xterm. :smiley:

**Comment by Finii** [comment]
Tnx for info, will check out tomorrow.

**Comment by Finii** [comment]
Installed on Ubuntu `apt install rxvt-unicode`.

Created resource file `~/.Xdefaults`
```
URxvt*foreground: Green
URxvt*background: Black
```

Install some fonts
```
cp ~/git/nerd-fonts/patched-fonts/CascadiaCode/Regular/complete/Caskaydia\ Cove\ Nerd\ Font\ Complete\ Regular.otf ~/.local/share/fonts
cp ~/git/nerd-fonts/patched-fonts/CascadiaCode/Regular/complete/Caskaydia\ Cove\ Nerd\ Font\ Complete\ Mono\ Regular.otf ~/.local/share/fonts
cp ~/git/nerd-fonts/patched-fonts/CascadiaCode/Regular/complete/Caskaydia\ Cove\ Nerd\ Font\ Complete\ Italic.otf ~/.local/share/fonts
```

(Using italic font to see that I really get what I want)

Running
```
LD_PRELOAD=/home/fini/git/wcwidth-icons/libwcwidth-icons.so urxvt --font 'xft:CaskaydiaCove Nerd Font:style=Italic:size=12' -e vi ~/testtext
```

![image](https://user-images.githubusercontent.com/16012374/216812674-56503bce-bf55-484d-9d13-fd25f5869c23.png)

If I switch to a size different from 12 (here 24):

![image](https://user-images.githubusercontent.com/16012374/216812800-a4d57f98-888b-4d48-bf2d-483f4bacc6ab.png)

Some symbols vanish??!

Whatever, the symbols are left aligned.
The width is only '1', though. In the bottom line I interspaced the symbols with blanks.

?

**Comment by Finii** [comment]
Btw the 3270 name changed meanwhile, there is no Medium anymore...

```
$ fc-list  | grep 'Cask|327'
/home/fini/.local/share/fonts/Caskaydia Cove Nerd Font Complete Regular.otf: CaskaydiaCove Nerd Font:style=Regular
/home/fini/.local/share/fonts/Caskaydia Cove Nerd Font Complete Italic.otf: CaskaydiaCove Nerd Font:style=Italic
/home/fini/.local/share/fonts/IBM 3270 Nerd Font Complete.ttf: 3270 Nerd Font:style=Regular
/home/fini/.local/share/fonts/Caskaydia Cove Nerd Font Complete Mono Regular.otf: CaskaydiaCove Nerd Font Mono:style=Regular
```

**Comment by powerman** [comment]
```
$ fc-list ':charset=f4a3' | grep -E 'Cask|327'
/home/powerman/.local/share/fonts/NerdFonts-2.3.3/Caskaydia Cove Nerd Font Complete Mono Regular.otf: CaskaydiaCove Nerd Font Mono:style=Regular
/home/powerman/.local/share/fonts/NerdFonts-2.3.3/Caskaydia Cove Nerd Font Complete Italic.otf: Cas aydiaCove Nerd Font:style=Italic
/home/powerman/.local/share/fonts/NerdFonts-2.3.3/Caskaydia Cove Nerd Font Complete Regular.otf: CaskaydiaCove Nerd Font:style=Regular
/home/powerman/.local/share/fonts/NerdFonts-2.3.3/Caskaydia Cove Nerd Font Complete Mono Italic.otf: CaskaydiaCove Nerd Font Mono:style=Italic
/home/powerman/.local/share/fonts/NerdFonts-2.3.3/Caskaydia Cove Nerd Font Complete Bold.otf: CaskaydiaCove Nerd Font:style=Bold
/home/powerman/.local/share/fonts/NerdFonts-2.3.3/Caskaydia Cove Nerd Font Complete Mono Bold.otf: CaskaydiaCove Nerd Font Mono:style=Bold
/home/powerman/.local/share/fonts/NerdFonts-2.3.3/IBM 3270 Nerd Font Complete Mono.otf: 3270 Nerd Font Mono:style=Regular
```

Cask Mono font looks okay, except icons are small (AFAIR it's configurable at build time, but I took released fonts as is):
`urxvt --font 'xft:CaskaydiaCove Nerd Font Mono:style=Italic:size=20'`
![image](https://user-images.githubusercontent.com/1354301/216816494-b407f051-5ee9-451f-95d2-5300cf8276e5.png)
Same for 3270 Mono:
`urxvt --font 'xft:3270 Nerd Font Mono:style=Regular:size=24'`
![image](https://user-images.githubusercontent.com/1354301/216816561-8ae57b68-4dc1-4a6c-9282-7ead5e462e8a.png)
But Cask non-Mono shows shifted icon position (and also icons are not small anymore):
`urxvt --font 'xft:CaskaydiaCove Nerd Font:style=Regular:size=20'`
![image](https://user-images.githubusercontent.com/1354301/216816652-6308e227-5193-4574-a3d0-89f12df54cc2.png)
(The underlines are from vim syntax checker, forget to disable it, sorry.)

**Comment by powerman** [comment]
Here is what I get using Cask Mono (one with small icons) without wc-width and without patching vim (using patch from wcwidth repo):
`LD_PRELOAD= urxvt --font 'xft:CaskaydiaCove Nerd Font Mono:style=Italic:size=20'`
![image](https://user-images.githubusercontent.com/1354301/216816910-975fc3fd-6bd0-4b3d-aada-afe3bc3e634e.png)
and here is same command without wc-width but using patched vim (note there are no real "space" symbol between icons, while moving cursor jumps from icon right to next icon):
![image](https://user-images.githubusercontent.com/1354301/216816997-41084b60-6098-4335-bae5-4d40203ec0df.png)

**Comment by powerman** [comment]
Anyway, lets leave alone vim and it's patch (which is needed for large icons case).

1. Non-Mono font with wcwidth: large icons, shifted.
```
LD_PRELOAD=/usr/lib64/libwcwidth-icons.so urxvt --font 'xft:CaskaydiaCove Nerd Font:style=Italic:size=20'
```
![image](https://user-images.githubusercontent.com/1354301/216817564-4bfdb727-be22-4cef-8db7-53deafe662b5.png)

2. Non-Mono font without wcwidth: large icons fit into width 1, so they overlap, some missing (maybe some side-effect of trying to fit wide icons into width 1)
```
LD_PRELOAD= urxvt --font 'xft:CaskaydiaCove Nerd Font:style=Italic:size=20'
```
![image](https://user-images.githubusercontent.com/1354301/216817620-1bcd720f-1fee-4bb8-bb42-6cd2b22db9b9.png)

3. Mono font with wcwidth: small icons, okay.
```
LD_PRELOAD=/usr/lib64/libwcwidth-icons.so urxvt --font 'xft:CaskaydiaCove Nerd Font Mono:style=Italic:size=20'
```
![image](https://user-images.githubusercontent.com/1354301/216817815-f8c74b7b-eaec-4c6d-a7ff-5c02ad8b1c87.png)

4. Mono font without wcwidth: small icons, okay (actually there is some issue with zsh prompt, but, again, this may be related to my wcwidth-expecting setup, so let's ignore it).
```
LD_PRELOAD= urxvt --font 'xft:CaskaydiaCove Nerd Font Mono:style=Italic:size=20'
```
![image](https://user-images.githubusercontent.com/1354301/216817868-7929b2ec-82b1-4825-a5bc-af30c1e1b5ae.png)

P.S. Regular works mostly same way as Italic, except in case "2. Non-Mono font without wcwidth" there are much more missing icons:
```
LD_PRELOAD= urxvt --font 'xft:CaskaydiaCove Nerd Font:style=Regular:size=20'
```
![image](https://user-images.githubusercontent.com/1354301/216818066-080d4d6f-d5af-4e51-8d8b-02752a15ad35.png)

**Comment by Finii** [comment]
Still trying to reproduce.

If I take the simplest image from here https://github.com/ryanoasis/nerd-fonts/issues/485#issuecomment-1417657315
The second case "Non-Mono font without wcwidth"

That works and looks exactly the same. Note that we see identical icons _not_, mostly from the `F4xx` range it seems:

![image](https://user-images.githubusercontent.com/16012374/217799352-ba6c8339-c6f4-457c-8f78-25894263c676.png)

_Icons leak into next cell **as intended**, unless next cell is empty-block thing_

But then, when I PRELOAD your lib (and it actually happens, see here:)

![image](https://user-images.githubusercontent.com/16012374/217800104-06ac5d3f-62d1-44ba-8a1a-e489c5d52682.png)

what `urxvt` shows is exactly the same as before. No change at all.

My `urxvt` version is this:
```
$ urxvt -h
rxvt-unicode (urxvt) v9.30 - released: 2021-11-27
options: perl,xft,styles,combining,blink,iso14755,unicode3,
encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,
tint,pixbuf,XIM,frills,selectionscrolling,wheel,slipwheel,smart-resize,
cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
Usage: urxvt [-help] [--help]
```

Further debugging shows that neither of the two functions in your library is ever called.
I experimented a bit with the `LC_` locales, but to no avail.
Also tried to build `urxvt` from source, but `make` fails with some `../libev/ev++.h` that is obviously not there?

**Comment by powerman** [comment]
`urxvtc` uses already running `urxvtd` daemon, so it does not actually run just-installed `urxvt` binary, so just don't use it for testing.
```
$ urxvt -h
rxvt-unicode (urxvt) v9.30 - released: 2021-11-27
options: perl,xft,styles,combining,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
...
```

**Comment by powerman** [comment]
And for the same reason it doesn't makes sense to set `LD_PRELOAD` for `urxvtc`, it should be set for `urxvtd` to have effect. Anyway, just avoid both and run only `urxvt` for testing.

As for missing fonts - I've no idea, but it's unlikely urxvt issue, maybe `fc-cache` should be executed or it's because urxvtc/urxvtd (e.g. already running urxvtd doesn't detected newly installed fonts).

**Comment by Finii** [comment]
Ah, re`configure`d with `--enable-everything`...

![image](https://user-images.githubusercontent.com/16012374/217820818-ffe2821e-e6e8-44e4-8f41-42a74aefd0a5.png)

At colors do not work but the rest looks good. At last.

ahh...

![image](https://user-images.githubusercontent.com/16012374/217821356-ae684292-a555-4491-8724-6fa68310ccc9.png)

Now we can start actual work.

**Comment by Finii** [comment]
Some glyphs look centered but the majority looks indeed right aligned.

![image](https://user-images.githubusercontent.com/16012374/217822143-991e6082-a85b-4127-9dd5-cae0f70c6ee4.png)

Lets find out why, because they are left aligned in the font. And what is the difference between the centered and the right aligned glyphs?

**Comment by powerman** [comment]
It's also important to do final testing using Mono font built with wide icons, because it's an actual use case.

**Comment by Finii** [comment]
Ah I guess I know...
All glyphs are centered, but the wider glyphs have a right side bearing (overhang), that is rendered but not taken into account when placing.

Yes.

![image](https://user-images.githubusercontent.com/16012374/217825158-d046ac7e-a4be-4f11-bd90-fd8674d7d5ad.png)

They are not right aligned, they are centered and some even extend into the next cell.

Here, the heart `F004`

![image](https://user-images.githubusercontent.com/16012374/217825713-e980abc3-340a-4b18-88d1-f64f026c5599.png)

The advance width is the box (which is one monospace width wide), but the visual width is of course wider.

I guess what you need is the `Nerd Font Propo` variant. There the glyphs do not have bearings (overhang) and advance width is the same as visual width.

See also

* #969 
* #1103 
* #764 (why it did work for some NF versions)

---

Let me quickly check

![image](https://user-images.githubusercontent.com/16012374/217828563-d95df08a-8b17-44b0-a9d2-e9c614d2d5d3.png)

'Fixed'.

**Comment by Finii** [comment]
> It's also important to do final testing using Mono font built with wide icons, because it's an actual use case.

Hmm? `Mono`? But that did work as far as I remember our discussion, \*scroll scroll\*

**Comment by Finii** [comment]
I guess I do not get the meaning of `Mono` in your comment.

In `Nerd Font Mono` all glyphs have the same width -> completely monospaced. There can be no 'wide icons'.
But you never mention `Nerd Font Mono` above, and there would be no issue and no need to use the wcwidth-patch (because it is strictly monospaced).

From the two fonts with 'wide' icons most clients need the 'I pretend to be monospaced' (`Nerd Font` without suffix), and some need the `Nerd Font Propo` variant which is just a normal font where all glyphs claim the space they need.

Obviously `rxvt` works best with
* `Nerd Font Mono`
* `Nerd Font Propo` and `wcwidth`-patch

**Comment by powerman** [comment]
> I guess I do not get the meaning of Mono in your comment.

Well, when the issue was reported (2.5 years ago) there was no "Propo" thing (or at least I don't remember it), but there was Mono font which can be compiled using two ways - one with non-wide but small icons, second with large but wide icons. So, I was talking about using Mono font in second way, as it was a couple of years ago. I don't tend to update fonts unless I get some annoying "missing icon" issue, so I'm still using D2Coding font patched using Nerd's Mono wide icons.

Sounds like today I should learn how to patch D2Coding using modern Nerd's Propo to fix the issue? :)

**Comment by Finii** [comment]
Yes, 2.5 years ago was just discussions about that and what the actual requirements are, what possible solutions could be etc.

Somewhere I commented with a 'History' writeup that explains all the decisions with reasons then and in retrospect.

`Nerd Font Propo` is rather new, meaning it is not available prepatched, and the NAME is not even in the code, that is #1028.
As a third variant would take quite some space I would like to get rid of the `Windows Compatible` fonts first. In principle there is no need for them (and I never use them on Windows machines), but that also takes quite some considerations...

This will all come in `v3.0.0` which is to be ready soon (for some definitions of `soon` ;-)

> Sounds like today I should learn how to patch D2Coding using modern Nerd's Propo to fix the issue?

You can use the [`FontPatcher.zip']() from the release, or the docker image (which is up to date with `master` always). There should also be a zip archive in sync with `master`, but that is also not ready (#1041)

You just need to specify `--variable` when patching. Probably
`fontforge font-patcher --complete --variable your-font.ttf`
or
`docker run --rm -v ~/myfont_dir:/in -v ~/myfontdir:/out nerdfonts/patcher --complete --variable`
(You specify `in` and `out` directories and all fonts in the `in` dir will be patched.)

**Comment by powerman** [comment]
Used docker way, looks like everything works. Thanks!

**Comment by powerman** [comment]
BTW, `--variable` is not documented in docker's readme: https://hub.docker.com/r/nerdfonts/patcher

**Comment by Finii** [comment]
Thanks for the feedback!

Yes. Unfortunately I have no access rights for the docker account and I can just push new versions because Ryan put the key into this repo's secrets... I also have very few right here, that prevent some clean up. But maybe at some point Ryan will have a day or so and we resolve access issues. The (his) plan was to move the project to the https://github.com/nerdfonts organization, but ... sigh.

The full `font-patcher` documentation is only [here](https://github.com/ryanoasis/nerd-fonts#font-patcher) or on www.nerdfonts.com. Or call the docker image with `--help`.
I keep the websites up to date, they show only `2.2.2` but nothing changed since then, parameter-wise.
