### ISSUE TITLE
Consider adding D2Coding font

### ISSUE THREAD

**Issue by powerman** [ryanoasis/nerd-fonts#486]
#### 🎯 Subject of the issue

I like D2Coding font very much, and while it's possible to just use `font-patcher` it would be nice to have it added officially and avoid manual patching.

It is licensed under the SIL Open Font License, Version 1.1, so I suppose there should be no licensing issues.

https://github.com/naver/d2codingfont

**Comment by ryanoasis** [comment]
Thanks for the suggestion
