### ISSUE TITLE
Ligatures remain in "Fantasque Sans Mono Regular Nerd Font Mono"

### ISSUE THREAD

**Issue by iTakeshi** [ryanoasis/nerd-fonts#487]
#### 🎯 Subject of the issue

Although the [readme](https://github.com/ryanoasis/nerd-fonts/blob/25eec39954c5d9232a80752bfb8d088a15fb3c01/patched-fonts/FantasqueSansMono/readme.md) says
> By the Nerd Font policy, the variant with the 'Mono' suffix is not supposed to have any ligatures. Use the non-Mono variants to have ligatures.

but the generated `Fantasque Sans Mono Regular Nerd Font Complete Mono.ttf` contains ligatures, like `=>` or `!=`

#### 🔧 Your Setup

- Fantasque Sans Mono Regular Nerd Font Complete Mono.ttf (installed via AUR `nerd-fonts-fantasque-sans-mono 2.1.0-1`
- kitty
- ArchLinux (rolling release)

#### ★ Optional

![kitty-fantasqueNF](https://user-images.githubusercontent.com/1460175/84110845-99139080-aa60-11ea-93a5-34dc418afd02.png)

**Comment by danielbayley** [comment]
@ryanoasis This also seems to be the case for many other fonts in the `patched-fonts` directory for me on macOS 11.0.1… The same ligatures appear regardless of the `Mono` suffixed variant 😕

**Comment by Finii** [comment]
Ligatures are _not_ removed by Nerd Fonts anymore.

A lot people like to have programming ligatures.
Most clients have the option to turn them off or on.
For the others there are tools that remove all ligs.

See current [readme](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FantasqueSansMono)

![image](https://user-images.githubusercontent.com/16012374/220377591-91076435-2502-45b9-b253-8f5e30616490.png)
