### ISSUE TITLE
PRR: Add batch directory processing to font patcher python script

### ISSUE THREAD

**Issue by FredHappyface** [ryanoasis/nerd-fonts#488]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

Probably about a month ago I made a fork of the font patcher as I found that I was using it quite a lot to keep up with Fira Code releases. Anyway I wanted it to be self contained rather than cloning a rather large repo.

Two main questions from this:

1. I modified the script to batch process fonts under a directory - is this something that you would find useful? Shall I open a pull request for this?

2. Would it be possible to move/ copy the font patcher to a new repo to avoid the manual 'cherry picking'?

Thank you 😊

**Comment by ryanoasis** [comment]
Appreciate the interest.

1. Yes though we have this "gotta patch em all" script that batch patches fonts. Could you explain more your solution? How is it different than that?

2. I know this has been a very obvious annoyance and pain point and source of confusion. I keep meaning to create a separate repo but have dropped the ball here so far. No news yet but I'd like to address sooner than later as we now have many unofficial repos of just the patcher 😃

**Comment by FredHappyface** [comment]
Thanks for getting back to me 😄 

1.  By adding this functionality to a .py script it's possible to run this under Windows with a bit more ease (tbf wsl is a thing). I guess I just missed it really (I must admit I cannot remember if I fiddled with other parts of the script or not in the end). I do remember that the addition of that functionality was fairly simple to implement and made my life a bit easier when it came to patching the new octicons onto some webfonts 

2. That would be great if you were able to pull it out as I'd assume that it would ease maintenance in the long run. I've certainly got one to add to the list :D 

Thanks again for your time
