### ISSUE TITLE
Incorrect font image for Gohu & Proggy on main website

### ISSUE THREAD

**Issue by CosmosAtlas** [ryanoasis/nerd-fonts#489]
#### 🎯 Incorrect font image for Gohu & Proggy on main website

On the main website's download page: https://www.nerdfonts.com/font-downloads

For each font supported, a preview image is also provided. However, for some bitmap fonts, mainly Gohu and Proggy, the preview is clearly not how the font look like. 

#### ★ Optional

Gohu font preview on downloads page
[Preview on main website](https://www.nerdfonts.com/assets/img/previews/Gohu%20Nerd%20Font.svg)

What Gohu font actually look like
[on source website](https://font.gohu.org/14-chars.png)

#### My thoughts on why it happen

Probably some font rendering issue when generating these previews.

**Comment by Finii** [comment]
Thanks for reporting!

I think I recreated the images in 2021, maybe you want to check if they are still wrong?

**Comment by CosmosAtlas** [comment]
Glad to hear an update. :D

Unfortunately, they are still probably displayed as a fallback font. The case is also true for ProggyClean.

Could be an issue with bitmap fonts. There has been a couple of foundamental changes in the recent years regarding how bitmap fonts are taken care of.

Anyway, given the fonts popularity, I don't think this is a big issue.

**Comment by Finii** [comment]
Family name of image preview font is wrong, that means fallback ... :-(

Was there not a warning if fallback occurs?

![image](https://user-images.githubusercontent.com/16012374/215340635-5c71f1e4-2c3e-4071-8cda-ee0ca8681bff.png)

The Family name is `ProggyCleanTT Nerd Font`.

![image](https://user-images.githubusercontent.com/16012374/215340707-f186cff2-8fca-4c7e-b2b0-2cec32e99b46.png)

**Comment by Finii** [comment]
Thanks for reporting and your persistence that finally fixed this :tada:
