### ISSUE TITLE
feat: update Octicons to latest

### ISSUE THREAD

**Issue by jef** [ryanoasis/nerd-fonts#490]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

Update the Octicons to [10.0.0](https://github.com/primer/octicons/releases/tag/v10.0.0). Released on 06/10/2020.

#### ★ Optional

Link to new Octicons: https://primer.style/octicons/

**Comment by djensenius** [comment]
Any update on this?

**Comment by Finii** [comment]
@djensenius This has a v3.0.0 tag. That release is due ... some days ago.

See https://github.com/ryanoasis/nerd-fonts/discussions/1074. Updated all source fonts, only some few issues open, this is one of them. Hope to finish this month.

**Comment by djensenius** [comment]
Awesome! Thanks @Finii !

**Comment by Finii** [comment]
Hmm, there seems to be no updated opticons font anymore in the original repo.
At least according to Arch, who build the font on their own from the svgs:

![image](https://user-images.githubusercontent.com/16012374/227575914-8b1a58b0-c78d-40ed-a8d8-9cd639986b97.png)

https://aur.archlinux.org/packages/ttf-octicons

They use `fantasticon`, but that breaks the codepoint stability, or not? Checking.
That would mean we need to self-create that font.
Do you have any information on this @djensenius ? Tnx.

**Comment by Finii** [comment]
Hmm, the produced font has completely different codepoints / sorting, this is not useful... :-(

![image](https://user-images.githubusercontent.com/16012374/227619582-021f4a7b-8b1b-4ded-9f84-a3a01d417d8d.png)

**Comment by Finii** [comment]
The mapping here https://github.com/microsoft/vscode-octicons-font seems to be the old one / the one we use.
We can use that to resurrect and update the font generation with current svgs.

**Comment by Finii** [comment]
At the moment the octicons are at `F400` with length `105` which after gap removal turns into end codepoint `F4A9`.
Currently at `F500` Material Design starts...:

![image](https://user-images.githubusercontent.com/16012374/227702651-0ba4fb0e-f86d-4193-b3b3-b6a9736092ee.png)

In Octicons 18.2.0 there are `107` icons, making the new end `F507`, which just penetrates a little bit into old MDI territory.

**Comment by Finii** [comment]
```
Reading mapping file
Found 172 entries
Fetching octicons archive "v18.2.0.tar.gz"
Unpacking octicons archive
Found 308 icons

Renamed cloud-download -> download
Renamed cloud-upload -> upload
Renamed gist -> logo-gist
Renamed radio-tower -> broadcast
Renamed clippy -> paste
Renamed mail-read -> read
Renamed mail-reply -> reply
Renamed primitive-dot -> dot-fill
Renamed primitive-square -> square-fill
Renamed settings -> sliders
Renamed dashboard -> meter
Renamed trashcan -> trash
Renamed paintcan -> paintbrush

Missing octoface
Missing keyboard
Missing file-text
Missing file-pdf
Missing jersey
Missing broadcast
Missing repo-force-push
Missing arrow-small-right
Missing gist-secret
Missing no-newline
Missing arrow-small-up
Missing arrow-small-down
Missing arrow-small-left
Missing logo-gist
Missing file-symlink-directory
Missing circuit-board
Missing watch
Missing text-size
Missing ellipses
Missing plus-small
Missing reply

Found 151 (of 172, missing 21) and new 157
```
