### ISSUE TITLE
Apple  symbol replacement

### ISSUE THREAD

**Issue by gubler** [ryanoasis/nerd-fonts#492]
#### 🎯 Subject of the issue

On macOS there is the  symbol that can be entered with `Option-Shift-K`. I don't know the code-point that is used here and I am fairly sure it is handled via a fallback font.

In pre-2.0 this symbol worked:

<img width="291" alt="old" src="https://user-images.githubusercontent.com/3446/84933894-8cb4b680-b0a4-11ea-9e0b-622b44a6aa8e.png">

but since 2.0 it is replaced with this symbol:

<img width="284" alt="new" src="https://user-images.githubusercontent.com/3446/84933909-91796a80-b0a4-11ea-92fc-dddcd87a8ab1.png">

I have kept using the older font because I use this symbol in a bunch of my documentation.

#### 🔧 Your Setup

- Post 2.0 - `Anonymous Nerd Font Regular` and Pre-2.0 `AnonymousPowerline Nerd Font`
- `iterm2` and any other text editor (VS Code, vim, etc.)
- macOS High Sierra, Mojave, and Catalina

**Comment by gibfahn** [comment]
+1 this is rather painful, using `Hasklug Nerd Font` and seeing the same problem.

I have this in my Kitty [`~/.config/kitty/unicode-input-favorites.conf`](https://sw.kovidgoyal.net/kitty/kittens/unicode-input.html):

```shell
f8ff #  - Apple Emoji
```

So looks like it's the private-use character [U+F8FF](https://www.fileformat.info/info/unicode/char/f8ff/index.htm).

**Comment by gubler** [comment]
I have tried the JetBrains Mono nerdfont and it has the same issue.

**Comment by YashKarthik** [comment]
yeah fira code also has the same issue

**Comment by notDavid** [comment]
Hi there, anyone know if there's a temporary workaround for this? (i'm using FiraCode Nerd Font)

**Comment by Finii** [comment]
@notDavid https://github.com/ryanoasis/nerd-fonts/issues/603#issuecomment-1056287130

**Comment by Finii** [comment]
`F8FF` will no longer be overwritten with `Nerd Fonts v3.0.0`, because
* #773

I mark this as solved already, but it will be active with v3.0.0 only.

See also https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3 section "Next Release Outlook"
