### ISSUE TITLE
Victor mono complete's italic ligatures are buggered

### ISSUE THREAD

**Issue by GTMxCode** [ryanoasis/nerd-fonts#494]
Hey started using a bunch of these cause I got sick of FF crashing when making my own, thanks for all the work.

I did notice that the victor mono fonts from the "victor mono complete mono" branch are messed up in the italic variants above 500 weight.  I havnt opened this particular font up, but I did notice a few of the others which had a random computer screen glyph unioned with random other glyphs from another lang set... Either way I'm pretty sure the tables got dickered and things like 
See: [Imgur](https://imgur.com/63VQb6J)

Thats VSCode you see. I tested in Hyper as well, but also in windows new terminal and they all showed the same (and win terminal really dicks with fonts good). Tried all weights and as I said above 500 its good, which seems strange but I guess there must be some oddity/gremlin causing it

take it easy!

**Comment by lfom** [comment]
The problem seems to be the ligatures for Latin letters at the end of the file. For some reason, even tho Victor Mono is already a mono-spaced font, the `font-patcher` is changing the font when using the `--mono` toggle. The weird thing is that the Bold Italics works fine...
Anyway, as a workaround you can either copy the characters from the non-Mono font (and to be very precise also change their width afterwards to 601), or delete them (you will lose those ligtures, of course).

**Comment by mbirth** [comment]
On a sidenote, MacOS seems to think all italic variants are the same. It doesn't differentiate between the various weights and instead suggests to delete all but one. Same for all the Oblique variants. No problem with the non-italic variants, though.

**Comment by McAllaster** [comment]
> On a sidenote, MacOS seems to think all italic variants are the same. It doesn't differentiate between the various weights and instead suggests to delete all but one. Same for all the Oblique variants. No problem with the non-italic variants, though.

Looks like that is similar to https://github.com/ryanoasis/nerd-fonts/issues/257

**Comment by tienbuigia** [comment]
a workaround for me is using Victor Mono before the nerd's one
[example](https://ibb.co/dctrpPx)

**Comment by Finii** [comment]
Fixed in 3.0.0 at least

![image](https://user-images.githubusercontent.com/16012374/236414236-6c42d149-45dd-4859-a73c-065b14693ec7.png)
