### ISSUE TITLE
font patcher fails

### ISSUE THREAD

**Issue by doums** [ryanoasis/nerd-fonts#495]
### 🎯 Subject of the issue

I installed FontForge from my distribution's package manager (`pacman` on Arch Linux).

I tried to patch several ttf fonts: JetbrainsMono (downloaded [here](https://www.jetbrains.com/lp/mono/)) and Inconsolata (downloaded from google fonts), in various style. All fail with the same error message:

```
$ fontforge -script font-patcher --octicons static/Inconsolata-Bold.t
tf
Copyright (c) 2000-2020. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20200314
 Based on sources from 2020-03-18 19:16 UTC-ML-D-GDK3.
The following tables are ignored by FontForge
  'STAT' style attributes table
Use-my-metrics flag set on at least two components in glyph 631
File original-source.otf does not exist
Traceback (most recent call last):
  File "font-patcher", line 924, in <module>
    main()
  File "font-patcher", line 919, in main
    patcher.patch()
  File "font-patcher", line 88, in patch
    symfont = fontforge.open(__dir__ + "/src/glyphs/" + patch['Filename'])
OSError: Open failed
```
I don't know what is the problem ?

#### 🔧 Your Setup

Arch Linux

**Comment by cfbender** [comment]
It doesn't make it very clear, but you cannot just run the script on it's own - you need to first clone the repo with `--depth 1` and run the script from there. You may be able to get away with only downloading the files you need from `src`, but cloning will definitely fix this for you.

**Comment by Etherian** [comment]
I ran into this issue as well.

@ryanoasis, could what tools and resources are needed and where to find them be clarified in the Font Patcher section? For example, it wasn't immediately clear that the `font-patcher` script was in the repo, and I didn't know from where the script was expecting to pull the glyphs until I decyphered the Python code in the error message.

**Comment by Etherian** [comment]
I ran into this issue as well.

@ryanoasis, could what tools and resources are needed and where to find them be clarified in the Font Patcher section? For example, it wasn't immediately clear that the `font-patcher` script was in the repo, and I didn't know from where the script was expecting to pull the glyphs until I decyphered the Python code in the error message.

**Comment by wimstefan** [comment]
There is a [new repository](https://github.com/betaboon/nerd-fonts-patcher) with just the font-patcher and all the necessary files as long as @ryanoasis is too busy to create a different repo for the font-patcher only (as he intends to do) ...

**Comment by mtsolmn** [comment]
Hi, I would just like to +1 @Etherian and @cfbender comments above. It is completely unclear that you need to have the repo cloned locally in order to run the `font-patcher`. It makes sense after the fact, as the glyphs to patch have to come from somewhere, but it is not mentioned anywhere in the documentation. I ran into this problem when I first tried patching my own fonts as well.

The default values for the font-patcher could also be added in the documentation. For instance, it is unclear which glyph packs are patched by default until you actually run the script. It would be nice to know this priori.

Great project though and works great when you know what to do! Thanks for all the work.

**Comment by doums** [comment]
I ran into the exact same problem. You should mention this in the doc. It's important.

**Comment by ryanoasis** [comment]
I think this is definitely confusing. Yes @wimstefan is right the goal is to create a separate repo for the patcher (and its required files) and I believe that would mean removing it from this repo to reduce confusion. Thoughts?

This was created a while back but just haven't gotten around to moving stuff yet: https://github.com/NerdFonts/patcher

It's not as simple as just copying the files.. or well if we keep the files in both repos it _could_ be. There is a lot of automation for the builds where things are pretty tightly coupled. Haven't looked into this for some time but understand it is a pain point

**Comment by cfbender** [comment]
Maybe something like a submodule could be useful if you're worried about the file duplication

**Comment by reportaman** [comment]
@ryanoasis Yes that's super confusing. Its under a user NerdFonts, and NerdFonts themselves are under your profile. If I had not come across this discussion, I wouldn't have been able to find. Please move that repo under your profile too, I bet most people don't know of it (it has only 3 stars vs 26k stars for nerd-fonts).

<img width="1655" alt="Screen Shot 2021-02-05 at 3 00 48 PM" src="https://user-images.githubusercontent.com/71736629/107098521-3f688f00-67c4-11eb-8d84-e4086a54c4d3.png">


<img width="1954" alt="Screen Shot 2021-02-05 at 3 06 03 PM" src="https://user-images.githubusercontent.com/71736629/107098531-44c5d980-67c4-11eb-8d3d-25aea9198b1a.png">

**Comment by ryanoasis** [comment]
@reportaman it's still a WIP. the org is setup but i want to copy things over so commit and contribution history is not lost

**Comment by Finii** [comment]
Can you not just fork, then drop the 'unneeded' half in one of the repos?

What came to my mind first was
* The error message is bad
* It could try to download the src-fonts :->

**Comment by NuraliMedeu** [comment]
Instead of splitting this repo into nerdfonts and font-patcher, and thus introducing more maintenance burden, maybe we should edit the font-patcher script to automatically download the necessary files from this repo? That way, all a user will have to do is to download one script file from [the website](nerdfonts.com).

**Comment by ryanoasis** [comment]
There will be some readme adjustments but the font patcher is now going to be archived with the necessary source files each release, should no longer be a need to clone any repo just for the patcher, for the 2.2.0 RC here: https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC/FontPatcher.zip

On the subject of a separate repo, I created the NerdFonts org and repos when I thought separating them was the best idea, I'm no longer sold on that being a solution.

The reason being as @NuraliMedeu mentions I also agree I think that may just mean harder maintenance when all most people want is a place to grab the patcher and go (solved by an archive file).
Another reason why I thought having the patcher in a separate repo would be beneficial is for patching all the fonts for a release but we also want to commit those changes back to the repo (not just create the archives) so we'd have to checkout the repo with the fonts anyway..

I think having a downloadable archive for the font patcher probably solves 99% of the issues

**Comment by Finii** [comment]
@ryanoasis 
> but we also want to commit those changes back to the repo (not just create the archives)

You never explain the why. Who and why wants the patched fonts in the repo :-D

**Comment by ryanoasis** [comment]
@Finii 

> You never explain the why. Who and why wants the patched fonts in the repo :-D

Sure I'll try to clarify. I see 2 main reasons to commit back to the repo.

1) There is definitely a subset of users who drill down the folder structure on the repo itself to download fonts. I've seen that circumstantially on a few videos but also it is based on actual data on Github (`insights` > `data` > `popular content`).

![Selection_100](https://user-images.githubusercontent.com/8083459/152662113-07194049-1059-4531-b154-67ec67cdb656.png)

2) Less important but for historical reasons, we've always just had them directly available in the repo and this was how it was done before proper releases.

I'd be in favor of changing that starting in `3.0` release to go along with other breaking changes but not for `2.x` releases.

**Comment by icy-comet** [comment]
@ryanoasis why not update the main readme and include a 2.2.0-RC font patcher link right now? Font Patcher usage is really confusing right now since the Docker image doesn't work as well.

The readme can be updated once again when 2.2.0 is dubbed stable.

**Comment by Finii** [comment]
Release is in repo, release as packages pending.
