### ISSUE TITLE
Patching Cascadia Code v2007 with Nerd Fonts patcher produces segmentation fault

### ISSUE THREAD

**Issue by BladeMF** [ryanoasis/nerd-fonts#498]
#### 🎯 Subject of the issue

When I try to patch the latest version of the font I get segmentation fault (see screenshot). When I patched the 2005 version it was patched successfuly. The reason I patch it is because I want to use it with Powerlevel 10 and oh-my-zsh.

This is what [the guys at Cascadia Code repo said](https://github.com/microsoft/cascadia-code/issues/313):

> The new version of Cascadia Code is built as a variable font—which is to say that it has the full weight range contained within the single font file.
> 
> From your screenshot, Font Forge does not understand at least some aspects of Variable font technology (for example, the HVAR and STAT table), so it would not surprise me if it encountered other things it didn't understand and errored out.
> 
> Unfortunately, this is something that the Nerd Font patcher or Font Forge is going to need to sort out.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
[v2007.01](https://github.com/microsoft/cascadia-code/releases/tag/v2007.01)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
Windows Terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
WSL 2 Ubuntu

![86222548-137e8e80-bb8f-11ea-8e84-74c43b8bca00](https://user-images.githubusercontent.com/12109622/86257878-cae0c880-bbc2-11ea-9622-73f8eeb89423.png)

**Comment by DoctorBizzle** [comment]
Any news on when the PR is likely to be merged?

**Comment by BladeMF** [comment]
Just a heads up, not sure if you need to fix this as the new version came out and there are static fonts in addition to the variabla-width ones and they patch OK.

**Comment by Finii** [comment]
We now issue a warning if a VF is opened. Unfortunately the limitation in `fontforge` is still there.

* a56a4fad8e5d4564b58331e9bcb5e9fe4137a121`font-patcher: Warn if sourcefont is a VF`
