### ISSUE TITLE
Fonts is too close to the files and folders

### ISSUE THREAD

**Issue by roboticsai** [ryanoasis/nerd-fonts#500]
In my vim the fonts eg. folder, files and comming very close to the its font itself, which is not looking nice. Screen shot https://github.com/roboticsai/cv_camera/blob/master/nerdfonts.png

**Comment by MinerChAI** [comment]
What font do you use? `xxx Nerd Font` or `xxx Nerd Font Mono`?

**Comment by Finii** [comment]
How is the output produced?

Usually command line tools that use the symbols add a blank after the icon to accommodate for the symbols that extract into the following 'cell'. Obviously the tool you use does not.

So you can switch to a font with small (i.e. only one cell wide) icons (`Nerd Font Mono` as @thecaralice suggested), or use a proportional font (`Nerd Font Propo`) if your terminal supports it.

But in fact, I question the command line tool, did you check if there is a switch to add the blank after icons?

Closing this as tool problem.
