### ISSUE TITLE
Install some single fonts, say, DejaVu Sans Mono Nerd Font Complete Mono.ttf

### ISSUE THREAD

**Issue by hongyi-zhao** [ryanoasis/nerd-fonts#501]
Hi,

I want to install some single fonts, say, DejaVu Sans Mono Nerd Font Complete Mono.ttf.

Any hints for the command to do this job?

**Comment by ryanoasis** [comment]
Hey @hongyi-zhao I believe this is what you want:

`./install.sh --ttf --use-single-width-glyphs "DejaVuSansMono"`

let me know if that is correct or if the documentation was lackin. Thanks!

**Comment by hongyi-zhao** [comment]
> ./install.sh --ttf --use-single-width-glyphs "DejaVuSansMono"

I tried the above command and it will install the following fonts:

```
 $ ls ~/.local/share/fonts/NerdFonts/
'DejaVu Sans Mono Bold Nerd Font Complete Mono.ttf'
'DejaVu Sans Mono Bold Oblique Nerd Font Complete Mono.ttf'
'DejaVu Sans Mono Nerd Font Complete Mono.ttf'
'DejaVu Sans Mono Oblique Nerd Font Complete Mono.ttf'
```
Then I tried the following command:

`./install.sh -C DejaVuSansMono`

 It will install the following fonts:

```
$ ls ~/.local/share/fonts/NerdFonts/
'DejaVu Sans Mono Bold Nerd Font Complete Mono.ttf'
'DejaVu Sans Mono Bold Nerd Font Complete.ttf'
'DejaVu Sans Mono Bold Oblique Nerd Font Complete Mono.ttf'
'DejaVu Sans Mono Bold Oblique Nerd Font Complete.ttf'
'DejaVu Sans Mono Nerd Font Complete Mono.ttf'
'DejaVu Sans Mono Nerd Font Complete.ttf'
'DejaVu Sans Mono Oblique Nerd Font Complete Mono.ttf'
'DejaVu Sans Mono Oblique Nerd Font Complete.ttf'

```

But I still cannot figure out what's the **single-width glyphs**. Could you please give me some more hints?

Regards,
HY
