### ISSUE TITLE
The symbols aren't right.

### ISSUE THREAD

**Issue by aasutossh** [ryanoasis/nerd-fonts#505]
### 🎯 The symbols in the patched font are not proper/right. Especially the powerline ones (check 2nd image in the original issue below.

I patched it in the WSL2 (Ubuntu 20.04), cloned `https://github.com/betaboon/nerd-fonts-patcher/` repo, installed `fontforge` using `apt`, and patched using `fontforge -script font-patcher -w -c ../Agave-Regular.ttf`

#### 🔧 Your Setup

- Font: agave (patched myself, the font from the repo is not seen by the VS code and other applications on win10)
- Terminal: alacritty
- OS: Windows 10

#### ★ Optional
original issue https://github.com/betaboon/nerd-fonts-patcher/issues/1
Please let me know if this needs more information.

**Comment by ryanoasis** [comment]
That looks to be a no longer existing fork repo and the issue therefore no longer exists. If this is still an issue please re-create a fresh issue. Thanks.
