### ISSUE TITLE
Unicode formalization of powerline glyphs?

### ISSUE THREAD

**Issue by pagerc** [ryanoasis/nerd-fonts#506]
I'd like to bring it to this groups attention that some of the powerline symbols are getting reviewed for consideration in unicode:
https://www.unicode.org/L2/L2019/19068r2-powerline-syms.pdf
http://www.unicode.org/L2/L2019/19343-script-adhoc-recs.pdf

> Recommendations: We recommend the UTC discuss the proposal and accept the following three
> characters, with code points in the (new) Graphics for Legacy Computing block:
> `U+1FBCB VERSION CONTROL BRANCH SYMBOL`
> `U+1FBCC COLUMN NUMBER INDICATOR`
> `U+1FBCD LINE NUMBER INDICATOR.`

From my understanding, they ruled out the lock icon in favor of the emoji lock and claim that existing drawing elements suffice for powerline needs. Reviewing https://en.wikipedia.org/wiki/Box-drawing_character, I'm guessing they think the following are sufficient alternatives to powerline block drawing glyphs:

### Box Drawing vs Powerline PUA
- ╱ `\U2571` vs `\UE0BB` and `\UE0BD`
- ╲ `\U2572` vs `\UE0B9` and `\UE0BF`
- ◢ `\U25E2` vs `\UE0BA`
- ◣ `\U25E3` vs `\UE0B8`
- ◤ `\U25E4` vs `\UE0BC`
- ◥ `\U25E5` vs `\UE0BE`

### CJK Symbols and Punctuation vs Powerline PUA
- 〈 \U3008 vs \UE0B3
- 〉 \U3009 vs \UE0B1

### Miscellaneous Technical vs Powerline PUA
- 〈 \U2329 vs \UE0B3
- 〉 \U223A vs \UE0B1

### Diongbats vs Powerline PUA
- ❬ \U276C vs \UE0B3
- ❭ \U276D vs \UE0B1
- ❮ \U276E vs \UE0B3
- ❯ \U276F vs \UE0B1
- ❰ \U2770 vs \UE0B3
- ❱ \U2771 vs \UE0B1

### Geometric Shapes vs Powerline PUA
- ◀ `\U25C0` vs `\UE0B2`
- ◄ `\U25C4` vs `\UE0B2`
- ▶ `\U25B6` vs `\UE0B0`
- ► `\U25BA` vs `\UE0B0`
- ◖ `\U25D6` vs `\UE0B6`
- ◗ `\U25D7` vs `\UE0B4`

### Legacy Computing (https://www.unicode.org/charts/PDF/U1FB00.pdf) vs Powerline PUA
- 🭬 `\U1FB6C LEFT TRIANGULAR ONE QUARTER BLOCK` vs `\UE0B2`
- 🭮 `\U1FB6E RIGHT TRIANGULAR ONE QUARTER BLOCK` vs `\UE0B0`
- 🮤 `\U1FBA4 BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE LEFT TO LOWER CENTRE` vs `\UE0B3`
- 🮥 `\U1FBA5 BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE RIGHT TO LOWER CENTRE` vs `\UE0B1`

### Supplemental Symbols and Pictographs vs Powerline PUA
- 🤇 `\U1F907 LEFT HALF CIRCLE` vs `\UE0B7`

There's some discussion around the legitimacy of the powerline glyphs as needed block drawing elements in this proposal. It may behoove the community to work on a new proposal to include the extra glyphs as block drawing elements under the Graphics for Legacy Computing block, i.e. https://github.com/ryanoasis/powerline-extra-symbols.

Unicode has nothing approximating `RIGHT HALF CIRCLE` that could match `\UE0B5`
`\UE0C0` onwards have no similar pre-existing unicode glyphs

**Comment by cmplstofB** [comment]
it is a very good idea to use the character code point provided by Unicode official instead to use PUA.
I hope the font developers will give this issue serious consideration.

**Comment by Finii** [comment]
I put this is Parallel Universe for future consideration.
