### ISSUE TITLE
Incorrect glyph and language tags for the Coptic block

### ISSUE THREAD

**Issue by tchristopherwhite** [ryanoasis/nerd-fonts#508]
The Coptic block seems to have incorrect language tags

I have recently added Coptic to my font. The glyph boxes register as Coptic Letters, but when I generate any of my fonts with Coptic, the language tag comes up as Tagalog. In the older versions of Fontforge the images associated with the glyph boxes actually displayed Tagalog. Does anyone know why this might be? Plus, how to fix the issue?

I am using the OS X version of Fontforge.

**Comment by Finii** [comment]
This sound like a `fontforge` problem. You should ask at https://github.com/fontforge/fontforge
