### ISSUE TITLE
`fi` shows as a telephone with `Inconsolata NF`

### ISSUE THREAD

**Issue by mangelozzi** [ryanoasis/nerd-fonts#509]
#### 🎯 `fi` shows as a telphone with `Inconsolata NF`

Type `file`, and you see `<telephone symbol>li`

#### 🔧 Your Setup

-  sudo scoop install inconsolata-nf
- windows terminal
- Windows 10 .19041

#### ★ Optional

![image](https://user-images.githubusercontent.com/19764314/88912861-38365680-d260-11ea-8722-505d62470866.png)

**Comment by Tremeschin** [comment]
Same here on Arch Linux, but somehow only italics "fi" 's show as a ☎️

**Comment by gardotd426** [comment]
This is actually an issue with other nerd fonts as well. I was on the Arch Linux forums and saw all these telephones and was like "huh?" I had a nerd font set as my monospace font.

**Comment by unfug** [comment]
Is there a workaround or can anyone release new version who know how to deal with fontpatcher?

**Comment by p-kolacz** [comment]
Ubuntu Nerd Font has the same problem.

**Comment by gardotd426** [comment]
Yeah it's definitely not just Inconsolata, I've seen it with numerous
monospace nerd fonts

**Comment by jffz** [comment]
Any temporary workaround to this ? Maybe disable ligature for a special unicode ?

**Comment by mangelozzi** [comment]
> Any temporary workaround to this ? Maybe disable ligature for a special unicode ?

I ended up just patching my own font.

**Comment by jffz** [comment]
Any hint as how to do so ?

**Comment by mangelozzi** [comment]
> Any hint as how to do so ?

https://github.com/ryanoasis/nerd-fonts#option-8-patch-your-own-font

**Comment by jef** [comment]
Duplicate https://github.com/ryanoasis/nerd-fonts/issues/254

**Comment by ewanm89** [comment]
Isn't Nerd Font Mono supposed to have ligatures disabled, this is happening there too? It is annoying cause I like the striped 0 of Inconsolata. And got things to do rather than work out how to patch without ligatures mystelf.

**Comment by JunjieLeiCoe** [comment]
Same problem here...
I am using `monaco nerd font` -- Mac OSX, native terminla, not zsh,  has the same issue

**Comment by AlbeyAmakiir** [comment]
Same for Overpass and MPlus. Also, in MPlus (but not Overpass) I'm getting a different pair of symbols with `ffi`, like you find in "office". 
![image](https://user-images.githubusercontent.com/2367996/143988174-b337ac38-1872-42b8-808d-0347851f1523.png)

**Comment by arminbw** [comment]
I am having the same issue on MacOS 12 using Inconsolata Nerd Font – but only in kitty, not in the native terminal.
<img width="498" alt="Screenshot 2021-12-09 at 19 16 51" src="https://user-images.githubusercontent.com/547849/145453154-e41eab3d-489f-4c15-a7c6-9917f53a8ab0.png">

**Comment by gardotd426** [comment]
> I am having the same issue on MacOS 12 using Inconsolata Nerd Font – but only in kitty, not in the native terminal. <img alt="Screenshot 2021-12-09 at 19 16 51" width="498" src="https://user-images.githubusercontent.com/547849/145453154-e41eab3d-489f-4c15-a7c6-9917f53a8ab0.png">

That's so  weird, cause using Kitty on  Linux  with  Inconsolata Nerd Font, I don't see the issue (I actually only see it in  non-terminal applications like browsers and some GUI  text editors)
![Screenshot_20211209_133641](https://user-images.githubusercontent.com/54234607/145455817-ad269acf-ee0d-40a9-b7a0-00ab04c6d9b1.png)

**Comment by arminbw** [comment]
I managed to solve the problem for me.

* I uninstalled the font (removed it using font book).
* I re-installed it using brew:
`brew tap homebrew/cask-fonts`
`brew install --cask font-Inconsolata-nerd-font` (this installed nerd-font release v.2.1.0)
* I got rid of the font cache (by cleaning the Apple Type Server)
`sudo atsutil databases -remove`
`atsutil server -shutdown`
`atsutil server -ping`
* I rebooted the os.

The telephone is finally gone.

@gardotd426 Maybe reinstalling and flushing all sorts of caches might help too…

**Comment by gardotd426** [comment]
Lmao look at what `fi` does with Ubuntu Nerd Font:
![Screenshot_20211209_140127](https://user-images.githubusercontent.com/54234607/145459118-e0cd21af-3111-48e7-9601-2c89844406d0.png)

**Comment by gardotd426** [comment]
@arminbw well what's weird, is that only some versions of the fonts do it. Like, `OverpassMono Nerd Font Mono` does it, but `OverpassMono Nerd Font` doesn't. When they're otherwise identical (looking). It's so weird. Some fonts don't do it at all (like CaskaydiaCove Nerd Font).

**Comment by gardotd426** [comment]
I just tried clearing the cache, no luck.

**Comment by craigfurman** [comment]
I'm not sure if this will be helpful, but one observation: using the homebrew font-inconsolata-nerd-font package on macOS, my font book shows an error message for this font: "Multiple copies of a selected font are installed". I haven't tried removing either one yet.

Potentially not relevant to the issue, sorry: additionally, if I set my terminal font to regular, non-nerd inconsolata, programs that depend on patched nerd fonts like https://github.com/kyazdani42/nvim-web-devicons manage to render the patched symbols anyway. I have no idea how this is happening, but I have to admit I know almost nothing about how fonts work.

**Comment by koopa1338** [comment]
@arminbw I'm on archlinux and not on macos but tried the following:
- uninstall the current installed version
- installed the newest version of the nerd-font package
- cleared the font cache with `fc-cache -rf` (`-r` to really force the cache cleanup)

This didn't work, I still have the telephone for `fi`

**Comment by arminbw** [comment]
@koopa1338 @gardotd426 Update: After another reboot the telephone is back. :(

**Comment by ryanoasis** [comment]
I've got a working solution and it should fix things across all the fonts and it won't require config settings but be internal to the patcher. This should also resolve #254

before
![Selection_074](https://user-images.githubusercontent.com/8083459/145761340-67bbf61d-434f-45f8-89dd-76dcd780f817.png)

![Selection_075](https://user-images.githubusercontent.com/8083459/145761461-73662a40-61cc-49a9-a691-b627e496d8fd.png)

![Selection_069](https://user-images.githubusercontent.com/8083459/145761497-f74a3504-5528-440e-a9a9-fbca2c71c6c3.png)

after

![Selection_076](https://user-images.githubusercontent.com/8083459/145761294-8a786998-4f25-42e6-b2af-8a8df5e3409e.png)

![Selection_077](https://user-images.githubusercontent.com/8083459/145761315-78a9fd28-fdb4-4583-b183-fd4e4e07698a.png)

![Selection_070](https://user-images.githubusercontent.com/8083459/145761518-5b19e84a-2ead-4e41-9748-1f071d884b1c.png)

**Comment by Finii** [comment]
Like so? ;-)

```diff
git diff                                                                                                                                                       master ✚ 1 … 80 ⚑ 5 
diff --git a/font-patcher b/font-patcher
index 0e76ab63..b4d22cff 100755
--- a/font-patcher
+++ b/font-patcher
@@ -706,16 +706,20 @@ class font_patcher:
             sym_dim = get_glyph_dimensions(sym_glyph)
 
             # check if a glyph already exists in this location
+            codepoint = int("0x" + copiedToSlot, 16)
             if careful or 'careful' in sym_attr['params']:
                 if copiedToSlot.startswith("uni"):
                     copiedToSlot = copiedToSlot[3:]
-                codepoint = int("0x" + copiedToSlot, 16)
                 if codepoint in self.sourceFont:
                     if self.args.quiet is False:
                         print("  Found existing Glyph at {}. Skipping...".format(copiedToSlot))
-
                     # We don't want to touch anything so move to next Glyph
                     continue
+            else:
+                # If we overwrite an existing glyph all subtable entries regarding it will be wrong
+                # (Probably; at least if we add a symbol and do not substitude a ligature or such)
+                if codepoint in self.sourceFont:
+                    self.sourceFont[codepoint].removePosSub("*")
 
             # Select and copy symbol from its encoding point
             # We need to do this select after the careful check, this way we don't
```

**Comment by ryanoasis** [comment]
@Finii tanks and yeah that's the same change I made essentially using `removePosSub`. I did see you marked as assigned earlier. I was talking a look because this wa really bugging me.

Would you like to submit a PR?

Let me know. I can just apply some logging fixes I found along the way, if not I'll throw in the fix in a day or 2.

**Comment by Finii** [comment]
The code is slightly different to the diff above. Is there really a change that the `copiedToSlot` starts with `"uni"` :thinking: 
Anyhow I included the existing code from the `if` branch in the solution. Does not hurt either ;)

**Comment by JBenedik** [comment]
I'm still getting the "fi" to phone change. 
![image](https://user-images.githubusercontent.com/32694017/152248546-84160046-435a-4664-b34a-37dc678f530e.png)
![image](https://user-images.githubusercontent.com/32694017/152248578-42541eed-5f3a-4463-bb26-7fdefe2b639c.png)

**Comment by Finii** [comment]
@JBenedik Which font file did you try (concrete link?)? Which application/terminal/OS?

**Comment by seokbeomKim** [comment]
@Finii I have the same problem on:
- Windows Terminal
- Windows 
- Powershell with oh-my-posh

**Comment by Finii** [comment]
@seokbeomKim Hmm, where did you download the font file? Exact name?
I have noticed that we have a mix of old and updated files in the repo #786, so you need to look out.

It works on my machine (although the font looks strange in the font preview, I just installed the one font as `.otf` and it looks good and has no telephones ;)

![image](https://user-images.githubusercontent.com/16012374/154208211-f7339971-aa2e-4042-bddd-41688ef21b99.png)

So maybe try
* Remove all font files of that family (you never mentioned which font you did use)
* Install just one font file, be careful to pick a 'new' font, not a years old one
* If it goes wrong, give a screenshot similar to mine (where one can see font files, etc pp)
* If it works ok, please also notify me ;)

**Comment by seokbeomKim** [comment]
@Finii The font name is "Inconsolata Nerd Font". 
I downloaded it from https://www.nerdfonts.com/font-downloads. (the font link: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Inconsolata.zip)
I found that only the font has the problem. Other fonts like inconsolataLGC NF, FiraCode Nerd Font Mono, CaskaydiaCove Nerd Font have no issue.

**Comment by Finii** [comment]
You use release v2.1.0.

That release has that bug, but it has been fixed in the upcoming release [v2.2.0 RC](https://github.com/ryanoasis/nerd-fonts/releases/tag/2.2.0-RC)
I hope :grimacing:

Otherwise you need to take the most recent version which is directly in the repo: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Inconsolata/complete

**Comment by laundry-96** [comment]
@Finii Thanks for looking into this! Any update on when 2.2.0 will be released?

**Comment by Finii** [comment]
> Any update on when 2.2.0 will be released?

There are still some PRs under examination, that would be nice to have in 2.2.0. Which means at least the marked **`bugfix`** -es that are ready to merge.
I guess Ryan is busy with real-work stuff and has not enough spare time for extended tests.
So, TL;DR: I have no clue.
