### ISSUE TITLE
Segfault While Patching Font on WSL2 Ubuntu

### ISSUE THREAD

**Issue by sp96296** [ryanoasis/nerd-fonts#514]
#### 🗹 Requirements

- 🗹 A brief but descriptive _title_ of your issue
- 🗹 I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- 🗹 I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- 🗹 I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

Segfault while patching a CJK Noto Sans otf font on Ubuntu

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
NotoSansCJKtc.otf
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
WSL2
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Windows 10 / Ubuntu (via WSL2)

#### ★ Optional
Log:
```
$ python3 ./font-patcher.py -c -out ./Output ./NotoSansMonoCJKtc-Regular.otf
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
  Ignoring 'VORG' vertical origin table
Segmentation fault
```

gdb error:
```
Program received signal SIGSEGV, Segmentation fault.
__strrchr_sse2 () at ../sysdeps/x86_64/multiarch/../strrchr.S:32
32      ../sysdeps/x86_64/multiarch/../strrchr.S: No such file or directory.
```

![patcher](https://user-images.githubusercontent.com/36968514/90319241-3d540080-df04-11ea-8c9e-21ee4227d5dc.png)

**Comment by Finii** [comment]
But from the screenshot your problem looks different.

Suggestions
* Do not invoke `font-patcher` directly but via `fontforge` (i.e. `fontforge -script font-patcher ...`)
* Use current `fontforge`, at least March 2022 Release

**Comment by Finii** [comment]
Correction: You need to use `fontforge` version January 2023 Release:

_With March 2022, 16 bit field error:_

![image](https://user-images.githubusercontent.com/16012374/220367206-ec1df440-493c-4f22-a3ba-23a0a311ec35.png)

_With Jan 2023:_

![image](https://user-images.githubusercontent.com/16012374/220367528-48063b8d-3e68-4fb2-aadf-6cb27402d677.png)
