### ISSUE TITLE
Different way to download complete font

### ISSUE THREAD

**Issue by huyhoang8398** [ryanoasis/nerd-fonts#515]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

Failed to download completed package through `wget` and browser download

#### 🔧 Your Setup

Distribution: Arch

**Comment by heisenberg2020** [comment]
I had the same proble +1

**Comment by polyzen** [comment]
Have you taken a look at the repos? There are packages for just the symbols https://www.archlinux.org/packages/community/x86_64/ttf-nerd-fonts-symbols/ and there are a bunch of options for the patched fonts in the AUR.

**Comment by ryanoasis** [comment]
I don't think this is a Nerd Font issue. Closing for now. Thanks all.
