### ISSUE TITLE
Incomplete Install Instructions for Patch Fonts (explain: complete, alternative, minimal choices)

### ISSUE THREAD

**Issue by cmcginty** [ryanoasis/nerd-fonts#52]
I know with enough googling someone can figure out how to install the patched fonts, but it would be nice to provide this in the README. Right now, I reloaded my font-cache and I still can't access the new fonts, so it really isn't as easy to setup as it could be.

Even better would be to create an install script that would let you select fonts that would auto download and install.

**Comment by ryanoasis** [comment]
First thanks for the feedback :+1: . I always like constructive feedback :smile: 

> I still can't access the new fonts

I thought the installation had really been improved compared to what it once was. What specifically was the issue you were running into why you could not access the fonts?

I am very open to PRs to improve things or suggestions that I can implement myself alternately.

> Even better would be to create an install script that would let you select fonts that would auto download and install.

Sounds like a cool idea, I had started on building a website that would allow you to choose the specific font and variation options to download but this idea is also a good option.

**Comment by cmcginty** [comment]
:metal: 
My first mistake was trying to download the fonts with CURL. Turns out you need to add `?raw=true` to the end of the URL. The current CURL example doesn't work anymoe. I think github remove the hostname.

Second issue was that I expected the font name to show up as with "NERD" in the name, but actually i was the same name as my powerline font (i.e. `Ubuntu Mono derivative Powerline 12`)

I guess it would help to list the names of the fonts in a table.

Also I was confused about which font set to use; complete, alternative, minimal. I ended up going with complete, but I'm not sure what the recommend one is or the differences between them.

**Comment by ryanoasis** [comment]
Hey thanks for the details :+1: 

> The current CURL example doesn't work anymoe

Yep I believe there was another ticket about this

> Second issue...

Hmm I will have to look into this

> which font set to use

This could be easily improved at least in the readme or additional readme per font directory

**Comment by ryanoasis** [comment]
> The current CURL example doesn't work anymore

It should work now because of #50 being fixed/closed and pushed

Your other points are still TBD/TODO :stuck_out_tongue:

**Comment by ryanoasis** [comment]
This concern has been now partially addressed in the wiki: https://github.com/ryanoasis/nerd-fonts/wiki/FAQ#which-font

However, I am going to be adding some readme.rst files to various directories to make it even more obvious and helpful :smiley:
