### ISSUE TITLE
Incorrect vue icon

### ISSUE THREAD

**Issue by epszaw** [ryanoasis/nerd-fonts#521]
#### 🎯 Subject of the issue

Incorrect `vue` icon rendering. Other icons work fine.

#### 🔧 Your Setup

- `Pragmata Pro Mono Liga Nerd Font.ttf`, `JetBrains Mono Nerd Font.ttf`
- `kitty`, `gnome`
- Ubuntu 20.04

#### ★ Optional

![image](https://user-images.githubusercontent.com/13414205/92083770-26038700-edcf-11ea-9168-cec506ee6401.png)

**Comment by lamartire** [comment]
@ryanoasis, any info here?

**Comment by corporal9736** [comment]
I meet the same problem here, the vue icon just cannot show properly. Are there any solutions?

**Comment by ryanoasis** [comment]
do other glyphs show up for you? If so you may have an older Nerd Font. Try from the latest release.

Can you try this from your terminal and provide a screenshot: `echo -e "\ufd42"`.

**Comment by UltraStudioLTD** [comment]
Hello @ryanoasis,
I also have this issue. Should I continue in this thread or create new?

Just in case here is information about font and terminal:

> **Terminal**: **Termux** *v0.118.0* (**F-Droid** version) with **Termux:Styling** *v0.29* (also from **F-Droid**). *Both are at **LATEST STABLE** versions **at the time of writing***.

> **Font**: **Fira Code Regular Nerd Font Complete.ttf**. *Latest file at the time of writing in repository, meaning commit **df6d602440f06695d3db372b45465632de264cc2** (https://github.com/ryanoasis/nerd-fonts/blob/df6d602440f06695d3db372b45465632de264cc2/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete.ttf)*

> Here is how it should look: 
![IMG_20220605_160134](https://user-images.githubusercontent.com/57063715/172049485-9de14844-830c-41c1-a6d8-c460191ecd05.jpg)

> And how it looks: 
![Screenshot_2022-06-05-16-02-33-656_com termux](https://user-images.githubusercontent.com/57063715/172049522-981967b2-82be-4cd9-8cd9-7910c995e53c.jpg)

**Comment by Finii** [comment]
Hmm, original reporter's terminals (`kitty` and `gnome-terminal`) seem to find the glyph, as does
```
$ fc-list ':charset=fd42'
/home/fini/.local/share/fonts/Fira Code Regular Nerd Font Complete Mono.ttf: FiraCode Nerd Font Mono:style=Regular
```

**Comment by UltraStudioLTD** [comment]
What's more strange is that when viewing specific glyph (not previewing it on list but holding on it) it shows it correctly

![Screenshot_2022-06-07-21-22-12-927_jp ddo hotmist unicodepad](https://user-images.githubusercontent.com/57063715/172444884-c8cc3b77-949d-4229-a4f2-6fe811f80040.jpg)

**Comment by UltraStudioLTD** [comment]
I tried to copy-pasting it:
![IMG_20220607_212231](https://user-images.githubusercontent.com/57063715/172445128-d0fdf48d-1d16-48a5-ac79-440de09d55c5.jpg)
But it shows same invalid glyph (question mark in diamond or whatever it is) as shown on terminal

**Comment by UltraStudioLTD** [comment]
<kbd>FEFF</kbd> is blank in both viewer and terminal

**Comment by UltraStudioLTD** [comment]
Also off topic question but ...

> *The font you linked **<ins>to (great!)</ins>** does have the glyph:*

What do you mean by **to (great!)** ?

**Comment by Finii** [comment]
> > _The font you linked **to (great!)** does have the glyph:_
> 
> What do you mean by **to (great!)** ?

That I appreciate people that link to concrete stuff where I can check and not just let me poke around with 100 possible other versions of fonts with the same name :-) Read it as _'Great report, thank you!'_

**Comment by UltraStudioLTD** [comment]
Also I am curious about one thing — why do patched fonts overlap with for example arabic glyps? There are tons of free space in Private Area and if I am not wrong there is also second Private Area

**Comment by Finii** [comment]
Regarding this screenshot

![image](https://user-images.githubusercontent.com/16012374/172448623-3eff72fe-d0d9-4ebe-acff-74216dcde656.png)

Interesting that the first 7 glyphs are one-slashed-out, while the following are crossed-out.
The first 7 should be filled, while the others are indeed empty.
Maybe the glyphs could not be rendered for some reason? I had that with other glyphs too, where they show up correct in one renderer but not in another.

Hmm, but the glyph looks trivial:

![image](https://user-images.githubusercontent.com/16012374/172450068-5b0eb17b-3e59-45f2-817e-c32553bfdb44.png)

Can the terminal show that HDMI plug `FD3F` thing?

**Comment by Finii** [comment]
I tried on my phone
* downloaded same file you linked to above
* show in [font viewer](https://play.google.com/store/apps/details?id=com.skaldebane.fontviewer&hl=en&gl=US)
* Because my keyboard does not allow to enter codepoints, send `X` `ctrl` + `shift` + `U` `F` `D` `4` `2` `enter` `X` via signal desktop to phone
* Copy and paste text from signal to font viewer
* (Ok, that is not the font installed, so probably rendered by font viewer)

![signal-2022-06-08-062059](https://user-images.githubusercontent.com/16012374/172531148-e8b0a809-6ba2-4e28-998d-71ebfbcba75b.jpg)

**Comment by Finii** [comment]
Hmm,

> Termux doesn't implement own font renderer, it uses an instance of android.graphics.Paint with typeface being set.

https://github.com/termux/termux-styling/issues/105#issuecomment-689523214

Strange. I checked the font in the repo, and it contains the `FD42` thing.

**Comment by Finii** [comment]
Well, installed this termux-style thing, and it is the same for all fonts (that I tried): `FD3F` is visible, `FD42` is unknown:

![image](https://user-images.githubusercontent.com/16012374/172545861-527706ca-ae80-450d-b04a-d14574dcdd83.png)

**Comment by Finii** [comment]
All those glyphs, `FD40` and upward, they are originally only ligatures. `FD3F` and below are normal glyphs.
Not that the ligatures table is filled, but the codepoints are intended to be for ligatures.
Maybe the font renderer thinks it smarter then the font data.

**Comment by Finii** [comment]
@lamartire Tried a lot with `kitty` and I can not reproduce the problem.

See details here: https://github.com/kovidgoyal/kitty/issues/5156

Maybe you can do/show us a `fc-list ':charset=fd42'` and/or start kitty like this:
`kitty --debug-font-fallback`

**Comment by UltraStudioLTD** [comment]
> ... and/or start kitty like this:
`kitty --debug-font-fallback`

I don't use kitty or GUI in general (except Termux).

> Maybe you can do/show us a `fc-list ':charset=fd42'` ...

Here is output of `fc-list ':charset=fd42'`:

```
❯ fc-list ':charset=fd42'
/data/data/com.termux/files/usr/share/fonts/TTF/IosevkaTermNerdFontComplete-Regular.ttf: Iosevka Term,Iosevka Nerd Font:style=Regular
/data/data/com.termux/files/usr/share/fonts/TTF/FiraCodeNerdFontComplete-Regular.ttf: FiraCode Nerd Font Mono:style=Regular
```

**Comment by willchao612** [comment]
> All those glyphs, `FD40` and upward, they are originally only ligatures. `FD3F` and below are normal glyphs. Not that the ligatures table is filled, but the codepoints are intended to be for ligatures. Maybe the font renderer thinks it smarter then the font data.

Same here. Also using kitty. Is there any possible workaround already?

**Comment by Finii** [comment]
> Also using kitty. Is there any possible workaround already?

Hmm, for me it works with `kitty`:
![image](https://user-images.githubusercontent.com/16012374/184627636-4574e961-de7c-49d8-8b95-d49be069a68b.png)

(Bottom windows shows `shift`-`ctrl`-`f2` settings)

**Comment by willchao612** [comment]
Weird. The glyph can show correctly when searched with <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>u</kbd> in kitty, but not with `echo -e "\ufd42"`.

**Comment by Finii** [comment]
My `echo` is the `zsh` builtin...

**Comment by willchao612** [comment]
I am using zsh too. The problem is that `fd40` and upwards cannot show correctly with `echo`, but with kitty's own unicode searcher it is fine.

**Comment by Finii** [comment]
What system are you using? shift-ctrl-u is the normal linux keyboard thing and has nothing to do with the shell or terminal, in my case. And as you can see, the `echo` works on my system.

I have `kitty 0.21.2 created by Kovid Goyal`

```
$ kitty --debug-font-fallback
[227 14:59:56.397158] Preloaded font faces:
[227 14:59:56.397197] normal face: /home/fini/.local/share/fonts/JetBrains Mono Regular Nerd Font Complete Mono.ttf:0
[227 14:59:56.397213] bold face: /home/fini/.local/share/fonts/JetBrains Mono Regular Nerd Font Complete Mono.ttf:0
[227 14:59:56.397227] italic face: /home/fini/.local/share/fonts/JetBrains Mono Regular Nerd Font Complete Mono.ttf:0
[227 14:59:56.397242] bi face: /home/fini/.local/share/fonts/JetBrains Mono Regular Nerd Font Complete Mono.ttf:0
```

Check this output while/after running `echo` in the started `kitty`.

Hmm, `kitty --debug-config` seems to be not there anymore?

**Comment by willchao612** [comment]
Thanks for your response. Ubuntu 20.04 is what I am using. Here is the output of `kitty --debug-font-fallback`.

```bash
[227 22:06:31.694397] Preloaded font faces:
[227 22:06:31.694436] normal face: /usr/local/share/fonts/OperatorMono-Medium.otf:0
[227 22:06:31.694451] bold face: /usr/local/share/fonts/OperatorMono-Bold.otf:0
[227 22:06:31.694463] italic face: /usr/local/share/fonts/OperatorMono-MediumItalic.otf:0
[227 22:06:31.694481] bi face: /usr/local/share/fonts/OperatorMono-BoldItalic.otf:0
U+279c bold Face(family=DejaVu Sans Mono, style=Bold, ps_name=DejaVuSansMono-Bold, path=/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf, index=0, is_scalable=True, has_color=False, ascender=1901, descender=-483, height=2384, underline_position=-175, underline_thickness=90, strikethrough_position=530, strikethrough_thickness=102) (new face)
```

I have `kitty 0.25.2 created by Kovid Goyal`.

**Comment by Finii** [comment]
`OperatorMono` ... is that self patched? Does not look like a NerdFont. Does not have the ugly `font-patcher` file names.

What does `fc-cache -f && fc-list ':charset=fd42'` show?
What is the contents of your kitty config?

**Comment by willchao612** [comment]
> What does `fc-cache -f && fc-list ':charset=fd42'` show?

`Operator Mono` not in the list. [Here](https://github.com/keyding/Operator-Mono) is the font's repo. Maybe it is not patched with the glyph? But other glyphs like filetype icons can show correctly.

> What is the contents of your kitty config?

```conf
include gruvbox_material_dark_hard.conf

font_family Operator Mono Medium
bold_font Operator Mono Bold
italic_font Operator Mono Medium Italic
bold_italic_font Operator Mono Bold Italic
font_size 22

disable_ligatures never
cursor_blink_interval 0
enable_audio_bell no
shell_integration no-cursor
copy_on_select no
```

**Comment by willchao612** [comment]
@Finii I have mislocated the problem. All glyphs can show properly in kitty, but those above fd42 fail once I am under tmux.

**Comment by willchao612** [comment]
@Finii Is this a tmux issue or font issue? Cuz it doesn't seem to work with other patched fonts either...

**Comment by Finii** [comment]
For me, it works in `tmux`

![image](https://user-images.githubusercontent.com/16012374/186103342-3f7b6122-b235-4963-80b7-ae94fe5d7ef5.png)

even on `kitty & tmux`

![image](https://user-images.githubusercontent.com/16012374/186104501-fcf66b11-18b7-44da-9fe9-cc2343f0ac48.png)

Maybe you should raise a new Issue, as it seems distinct from the TO's.
Please add how your system exactly is set up, download links to the font you have installed etc

**Comment by willchao612** [comment]
> Please add how your system exactly is set up, download links to the font you have installed etc

Thanks for your patience. Here's my setup:

- Ubuntu 20.04
- Kitty
- Tmux
- [Font](https://github.com/willchao612/Operator-Mono-Patched)

**Comment by Finii** [comment]
This must be some local setting, maybe fontconfig. Works on all scenarios I checked.

![image](https://user-images.githubusercontent.com/16012374/215752313-87e92742-a613-4989-968f-355906676df2.png)
