### ISSUE TITLE
monofurbold smooth and rounding so love it. Only bad one, 'a' and '!' thick make border space get broken

### ISSUE THREAD

**Issue by eypsume** [ryanoasis/nerd-fonts#523]
#### 🗹 Requirements
'monofurbold nerd font mono' need a little bit of border space.

- [O ] A brief but descriptive _title_ of your issue
- [ O] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [ ] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ ] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue
monofurbold smooth and rounding so love it. Only bad one, 'a' and '!' thick make borders get broken

'monofurbold nerd font mono' smooth and rounding so love it. It's clear.
I'm using monofurbold nerd mono in the vscode with size 16.
Only bad one, the thickness makes character's border or space get broken.
Character 'a' and '!' look like below. that get difficult distinct.
![image](https://user-images.githubusercontent.com/38209036/92417240-253a6e80-f19c-11ea-845a-80b34d170bf1.png)

#### 🔧 Your Setup
Usage on the Visual Studio Code under Ubuntu Gnome 16.04.6
editor.fontFamily: 'Monofurbold Nerd Font Mono' 
editor.fontSize: 16
editor.fontWeight: "normal"
editor.lineHeight: 20

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
monofur bold Nerd Font Complete Mono.ttf
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   gnome terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
  Linux

**Comment by Finii** [comment]
Hard to say what happened here. The current font looks ok:

![image](https://user-images.githubusercontent.com/16012374/220370184-16eb25d7-6563-4226-8f1c-0933d45335e1.png)

Maybe try the current version (`2.3.3`).

Did you install all Monofur or only that one? Original Monofur in parallel?
If you have multiple Monofur font files installed (different weights, like bold etc), it might be that the problem will only be solved by `v3.0.0`'s new naming scheme.

Please reopen if problem is still there.
