### ISSUE TITLE
Fira code retina path showing weird glyphs for __(double underscore)

### ISSUE THREAD

**Issue by YashKarthik** [ryanoasis/nerd-fonts#524]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🔧 Your Setup

- _Fira code retina_
- _GUI macvim_
- _MacOS mojave: 10.14.6  _

#### ★ Optional
The patched version of Fira code retina shows weird glyphs for __ 

Screenshots :
1. With Fira Code Retina NERD font:
<img width="253" alt="Screenshot 2020-09-09 at 9 44 38 AM" src="https://user-images.githubusercontent.com/52369876/92554348-c1d73c00-f282-11ea-9f39-2379c1e00b96.png">

2. With regular fira code retina:
<img width="253" alt="Screenshot 2020-09-09 at 9 43 24 AM" src="https://user-images.githubusercontent.com/52369876/92554398-e59a8200-f282-11ea-844b-950fec953478.png">

thanks !!

**Comment by Finii** [comment]
We fixed a lot ligature related code in the meantime.

Seems to be fixed in current master:

![image](https://user-images.githubusercontent.com/16012374/220372167-42faafed-2706-4272-a425-7106f42ab81d.png)
