### ISSUE TITLE
DroidSansMono not patched with powerline-extra-symbols

### ISSUE THREAD

**Issue by 2O4** [ryanoasis/nerd-fonts#527]
#### 🎯 Subject of the issue

The [Droid fonts](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/DroidSansMono) are not patched with the extra symbols in this repo, but in the [powerline-extra-symbols](https://github.com/ryanoasis/powerline-extra-symbols) they are.

#### 🔧 Setup

- Droid Sans Mono for Powerline Regular
- gnome-terminal
- Linux

#### ★ Screenshots
![image](https://user-images.githubusercontent.com/35725720/93596988-94913900-f9ba-11ea-8013-eab5af7def11.png)

**Comment by Finii** [comment]
I guess you used the source font and not the patched font.

* https://github.com/ryanoasis/nerd-fonts/tree/master/src/unpatched-fonts/DroidSansMono
* https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/DroidSansMono

**Comment by Finii** [comment]
No sorry, you link to the patched fonts.

But all symbols are there:

![image](https://user-images.githubusercontent.com/16012374/220374208-2f6b06bf-3091-443e-b7f0-01cad80cf233.png)

Maybe solved in the years since you reported.
