### ISSUE TITLE
Mention the repo size in README

### ISSUE THREAD

**Issue by royfrancis** [ryanoasis/nerd-fonts#528]
Good idea to mention in the README that the total repo size is 6.21 GB. Useful for those in a situation with space restrictions.

**Comment by ryanoasis** [comment]
Hi @royfrancis thanks, there is this warning:
> cloning this repository is not recommended (due to Repo size) unless you are going to be contributing to development

But we could expand on it a bit but I wouldn't want to calculate the size and keep that up to date :)

**Comment by jef** [comment]
Have you considered using [`git-lfs`](https://git-lfs.github.com/)?
