### ISSUE TITLE
Hidden links in all README files?

### ISSUE THREAD

**Issue by adrian5** [ryanoasis/nerd-fonts#530]
While fixing a typo in a patched font's README file, I noticed text in the source that isn't visible in the rendered document:

```markdown
[vim-devicons]:https://github.com/ryanoasis/vim-devicons
[vorillaz-devicons]:https://vorillaz.github.io/devicons/
[font-awesome]:https://github.com/FortAwesome/Font-Awesome
[octicons]:https://github.com/primer/octicons
[gabrielelana-pomicons]:https://github.com/gabrielelana/pomicons
[Seti-UI]:https://atom.io/themes/seti-ui
[ryanoasis-powerline-extra-symbols]:https://github.com/ryanoasis/powerline-extra-symbols
[SIL-RFN]:http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web_fonts_and_RFNs#14cbfd4a
```

This section appears in most (or all) patched fonts READMEs. Is this some internal reference mechanism or and oversight?

The proper format for Markdown for named links is: `[vim-devicons](https://github.com/ryanoasis/vim-devicons)`

**Comment by figsoda** [comment]
These are [link reference definitions](https://github.github.com/gfm/#link-reference-definitions)

**Comment by adrian5** [comment]
That makes sense, I wasn't aware of that feature. Closing the issue.
