### ISSUE TITLE
Update font-logos glyphs to v0.14

### ISSUE THREAD

**Issue by figsoda** [ryanoasis/nerd-fonts#531]
https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/font-logos.ttf

Latest commit was on Feb 11, 2018. Since then [font-logos](https://github.com/lukas-w/font-logos) got 5 releases with 9 additional icons.

**Comment by ryanoasis** [comment]
Sorry for being here, but same reply: Yep! Done, via #551 (pending a full rebuild TBD)

related: #606
