### ISSUE TITLE
Discrepency between Inconsolata Nerd Font and regular Inconsolata

### ISSUE THREAD

**Issue by pvonmoradi** [ryanoasis/nerd-fonts#534]
The Nerd Font variant of Inconsolata is not exactly similar to normal (Google's) Inconsolata. For example in Nerd Font variant:  
- The `_` is lower. The bars of `=` are stretched along y-axis.
- All `()`, `[]`, `{}` are not vertically centered with the characters. 
- In general letters, numbers and greek symbols are elongated vertically.  

I've attached an mp4 to better show the problem (tested both on Alacritty and Xfce4-terminal)  :
[https://imgur.com/Mj9FSID](https://imgur.com/Mj9FSID)  

Here is individual codes (also changed the bold variant to Nerd):  
Inconsolata:  
[http://i.imgur.com/TC7xkIj.png](http://i.imgur.com/TC7xkIj.png)
Inconsolata Nerd Font:
[http://i.imgur.com/5pkHjC3.png](http://i.imgur.com/5pkHjC3.png)
#### 🔧 Your Setup
-  `Inconsolata Nerd Font Complete.ttf`
-  Alacritty, Xfce4-terminal
- Xubuntu 18.04 + i3-gaps

**Comment by Finii** [comment]
From the images above for better visibility:

![Peek 2023-02-21 17-35](https://user-images.githubusercontent.com/16012374/220405014-5f46be8f-e130-425d-ba8f-57682debfe7c.gif)

Unpatched vs patched looks similar

![image](https://user-images.githubusercontent.com/16012374/220406421-bc3f3d9e-e0c3-4f10-9b1e-d0a1913b8014.png)

Hmm, here it says image `5pkH...` is `Nerd Font`

![image](https://user-images.githubusercontent.com/16012374/220407565-01d91a0a-dd9b-4c9a-8b1b-51620cc03e34.png)

But the font in that image looks ok

![image](https://user-images.githubusercontent.com/16012374/220407978-e03e0673-947d-461d-83fe-be77ca012f35.png)

This is also the case for the movie (first link).
The Nerd Font variant looks good, and all the issues mentioned above are in the non-Nerd Font.

Unfortunately the origin of the 'reference' font is not given, so ... everything looks good here.
