### ISSUE TITLE
Commit 59c45ba4eff539d2a83a7d7004f056b9860d3253 (Remove negative bearings on 2048-em glyphs) breaks Windows compatibility

### ISSUE THREAD

**Issue by rupor-github** [ryanoasis/nerd-fonts#536]
Patched "Pragmata Pro Mono" font (version 0.828) used to work pretty well on Windows until recently.

Here is what I do: 

`FontForge-2020-03-14-67687b0-x86_64.AppImage -script ${dir}/font-patcher --careful --complete --mono --windows -out ${home}/work_done ${home}/work/PragmataPro_Mono_${variant}_${ver}.ttf `

After commit 59c45ba4eff539d2a83a7d7004f056b9860d3253 Windows 10 fails to detect patched font as monospaced and fc-scan on Linux does not show `spacing: 100(i)(s)` any more. Placing `remove_glyph_neg_bearings` back before `set_glyph_width_mono`  fixes the problem. 

I am not really sure this is proper fix (since I am not familiar with original issue "Remove negative bearings on 2048-em glyphs"...

#### 🔧 Your Setup

- Pragmata Pro Mono (no ligatures) 0.828
- Windows Terminal - all versions
- Windows 10

**Comment by PatTheMav** [comment]
Can confirm that this change breaks monospace detection on macOS as well. By reverting the order, fonts generated with the `--monospace` flag are recognised as monospace by Linux, macOS and Windows again.

**Comment by Finii** [comment]
Fixed in
* #764
