### ISSUE TITLE
CaskaydiaCove NF: Whitespaces rendering as boxes on Windows gVim

### ISSUE THREAD

**Issue by hrai** [ryanoasis/nerd-fonts#538]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

Whitespaces rendering as boxes on Windows gVim.

![image](https://user-images.githubusercontent.com/4055444/97954300-3e0b7d00-1df7-11eb-98cf-dce8df39a749.png)

This doesn't seem to be an issue on nvim on the same machine.
![image](https://user-images.githubusercontent.com/4055444/97954224-0997c100-1df7-11eb-88bc-c8f1d0e6b5a2.png)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ CaskaydiaCove
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ None
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Windows 10

**Comment by Finii** [comment]
Please try again with `v3.0.0`, can not possibly debug this old font, sorry.
Reopen if still persisting with current release.
