### ISSUE TITLE
Weather icon codepoints vs wttr.in

### ISSUE THREAD

**Issue by jetzerb** [ryanoasis/nerd-fonts#543]
#### 🎯 Subject of the issue

Data returned by `wttr.in` includes codepoints that don't align with the weather glyphs in Nerd fonts.  For instance, it may return a character [U+1F328 | 🌨 | f0 9f 8c a8 | CLOUD WITH SNOW](https://www.utf8-chartable.de/unicode-utf8-table.pl?start=127744), but that codepoint isn't provided in Nerd Fonts.

**Edit**: Hmm...not really specific to weather icons, so much as lack of codepoints in the U+1Fxxx range.

#### 🔧 Your Setup

- Font: `DejaVu Sans Mono Nerd Font Complete.ttf`
- Terminal emulator: `urxvt`
- `ssh -X`'d into a Ubuntu Linux Docker container on Windows 10.  `urxvt` rendered via [VcXSrv](https://sourceforge.net/projects/vcxsrv/)

#### ★ Optional

Here's how it looks in `urxvt`:
![image](https://user-images.githubusercontent.com/36859020/100797346-97ab9b00-33e7-11eb-8995-90a418655135.png)

Here's how my browser renders it on Windows 10:
![image](https://user-images.githubusercontent.com/36859020/100799703-1ce47f00-33eb-11eb-90ca-8cbbd91e8c0a.png)

The Nerd Font only goes up through code point 1D7FF, while `wttr.in` returns codepoints in the 1F300 range.
![image](https://user-images.githubusercontent.com/36859020/100800015-95e3d680-33eb-11eb-8d68-117a178a785a.png)
and all the Nerd Font weather icons appear to be in the [0E300 range (private use area)](https://www.utf8-chartable.de/unicode-utf8-table.pl?start=58112&number=128):
![image](https://user-images.githubusercontent.com/36859020/100800335-173b6900-33ec-11eb-9d3f-e111905b0e5f.png)

**Edit**: Other apps also use code points beyond those provided by Nerd Fonts.  For instance, I use `tmux` with config provided by "[Oh My Tmux](https://github.com/gpakosz/.tmux)", which also references glyphs in the U+1Fxxx range:
![image](https://user-images.githubusercontent.com/36859020/100802653-6cc54500-33ef-11eb-8483-35f225b21da9.png)

**Comment by miikanissi** [comment]
Anyone come up with a solution for this yet? Very frustrating not having these icons mapped.

**Comment by jetzerb** [comment]
I'm hoping for a reply from someone who knows why the weather glyphs in the Nerd Fonts are in the "private use" area rather than the ["official"(?) UTF-8 locations](https://www.utf8-chartable.de/unicode-utf8-table.pl?start=127744)
- Moon/Sun/Star symbols in U+1F311 - U+1F320
- Temperature/Weather symbols in U+1F321 - U+1F32C

Note that there are many more weather symbols in the Nerd Fonts than in the UTF-8 ranges linked above, so that undoubtedly plays into it.

I don't know how fonts work, but it would be convenient if the U+1F3xx code points could contain pointers back to the 0E300 range so the glyphs could be represented in both areas without having to specify the full definitions more than once.

**Comment by chubin** [comment]
We are working on this in https://github.com/chubin/wttr.in/issues/363#issuecomment-640260568

**Comment by jetzerb** [comment]
@chubin: If you plan to make `wttr.in` use _more_ than just the symbols in the U+1F3xx range listed above, then adding specific support for nerd fonts sounds like a worthwhile pursuit.  But the unpopulated codepoints seem like a shortcoming of the current implementation of Nerd Fonts.  There are plenty of weather glyphs; they just don't reside where the unicode specs say they should.  Countless applications in addition to `wttr.in` could be outputting codepoints in the U+1F3xx range and no one using Nerd Fonts will see a properly rendered glyph.

When I get some free time, I plan on looking into the `font-patcher` script to see if [adding a few more lines](https://github.com/ryanoasis/nerd-fonts/blob/901680ef1ddf92311da71165ac220c2b50d882d0/font-patcher#L530) to map specific glyphs to the standard codepoints is all it takes.

**Comment by chubin** [comment]
What I plan to do as the next step, I want to use the same symbols that the v2d and v2n views are using.

The v2 view already have nerd fonts variants: v2d (day) and v2n (night):

```
curl v2d.wttr.in
curl v2n.wttr.in
```

**Comment by jetzerb** [comment]
Sounds good.

But my point is that your changes to `wttr.in` do not mean that _this_ issue should be considered resolved.

**Comment by ryanoasis** [comment]
Okay, I suppose this is now more about patching to add any missing glyphs from "Miscellaneous Symbols and Pictographs". I would consider this an improvement

**Comment by epicfilemcnulty** [comment]
> The v2 view already have nerd fonts variants: v2d (day) and v2n (night):
> 
> ```
> curl v2d.wttr.in
> curl v2n.wttr.in
> ```
@chubin the full v2 view surely has them, but the short version still returns icons that are not rendered
by nerd fonts: `curl v2n.wttr.in/?format=1` =(

**Comment by Finii** [comment]
Well, Nerd Fonts (at the moment) does not patch anything beyond `FFFF`.

> The Nerd Font only goes up through code point `1D7FF`

This is not really true, or rather depends on the original font. If that has glyphs in that range, the patched font also has them.

If someone is willing to create a table with 'official' weather codepoints and its corresponding weather-icons codepoints, it is very very easy to add these codepoints as aliases. Something like this for example

```
1F311  full moon       E600
```

We take the weather icons from here: https://github.com/erikflowers/weather-icons
and move the codepoints up `500`.

These:
![image](https://user-images.githubusercontent.com/16012374/203114259-fcdcd00e-b4cf-4b2b-8d0f-82030535daeb.png)


As I see this, I have _no clue_ why we skip over **day-cloundy-gusts** (`f000`) that does not make any sense.


So someone just have to come up with some table that relates
* https://www.utf8-chartable.de/unicode-utf8-table.pl?start=127744
* https://erikflowers.github.io/weather-icons/

I would caution against @jetzerb 's solution as that patches in the same glyph multiple times, while we would rather add just an entry in the table that one glyph is to be used with two codepoints. (Something the current `font-patcher` can not, but is very easy to add.)

On the other hand, @epicfilemcnulty last comment sounds more like an Issue `wttr.in` and has nothing to do with Nerd Fonts?

So, if someone is willing to create a codepoint-alias-table, we can add that; I fear I have not really time to weed the codepoints out ;)

**Comment by Finii** [comment]
@epicfilemcnulty 

Hmm, yes

![image](https://user-images.githubusercontent.com/16012374/203121436-ed597b10-74f2-43df-83b8-48b6879aca6e.png)

But I must admit that the non-nerd-font icon looks far better ;-q

And in this case it is `26c5`. That is specifically NOT in the `1Fxxx` range.

And I get it from here:

```
$ fc-list :charset=26c5
/home/fini/.local/share/fonts/NotoColorEmoji.ttf: Noto Color Emoji:style=Regular
```

It gets selected by font-fallback; my terminal uses some Nerd Font of course.

**Comment by Finii** [comment]
I put this into The Future for now. Thanks for the input.
