### ISSUE TITLE
The fonts have some glyphs showing ripped in half. And patcher does this too.

### ISSUE THREAD

**Issue by hrqmonteiro** [ryanoasis/nerd-fonts#544]
#### 🎯 Subject of the issue

On the screenshots is the hexagon symbol on the Material Icons set (class no. f7d7), but some other icons show it like this, too (like some circles on the 'fae' set, this is just an example:

![2020-12-03_19-15](https://user-images.githubusercontent.com/17055027/101095001-0893b400-359c-11eb-809f-f6f7d4736b83.png)

I tried many patched fonts (RobotoMono, SpaceMono, Fira, Iosevka, SauceCodePro, JetBrainsMono) and all show it like this.

I tried patching my own fonts using the `-s/--mono/--use-single-width` flag, but it don't solve the problem.

#### 🔧 Your Setup

- _Font:_ As i said above, i tried with some 20 fonts: `Roboto, SpaceMono, Fira Code, Iosevka, SauceCodePro, Jetbrains` and some i patched on my own, like `PragmataPro`.
- _Terminal_: `Alacritty` and tried on `URXvt` and `kitty`, too.
- _OS:_ Void Linux

**Comment by cainy-a** [comment]
![image](https://user-images.githubusercontent.com/19270622/101218353-d1e09b00-367a-11eb-9115-fcb9cdc650b2.png)
Mine does this too in Windows Terminal (prompt is powerlevel10k)
