### ISSUE TITLE
patched Inconsolata-g font not showing up in sytem font database

### ISSUE THREAD

**Issue by lenovolobo933** [ryanoasis/nerd-fonts#547]
#### 🎯 Subject of the issue

hello, i used font patcher to  generate new font using inconsolata-g as base. after updating the fc-cache and confirming that they have been installed, i could not fint the fonts available for selection in both kde plasma system settings and terminal. i have attached the generated fonts in a zip file. thanks

#### 🔧 Your Setup

-inconsolata-g nerd font complete.ttf
- konsole
- archlinux

[Inconsolata-g-ttf.zip](https://github.com/ryanoasis/nerd-fonts/files/5659862/Inconsolata-g-ttf.zip)

**Comment by Finii** [comment]
This is rather old. Maybe try again with `font-patcher` 3.0.0
