### ISSUE TITLE
Feature Request: FiraCode iScript addition

### ISSUE THREAD

**Issue by ZacharyRizer** [ryanoasis/nerd-fonts#548]
Don't know how hard it would be to implement this font, but it would be rad to have the FiraCode with cursive italics font as seen here: 

https://github.com/kencrocken/FiraCodeiScript

But with all the lovely aspects of a nerd font!

**Comment by swag-lab** [comment]
Old issue, new solution(maybe): Download the tar.gz file (below), extract the contents, and install it according to your OS requirements.
[FiraCodeiScript.tar.gz](https://github.com/ryanoasis/nerd-fonts/files/6180852/FiraCodeiScript.tar.gz)

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
