### ISSUE TITLE
Powerline glyphs disappear after reboot

### ISSUE THREAD

**Issue by qidydl** [ryanoasis/nerd-fonts#553]
#### 🎯 Subject of the issue

When I install a font with Powerline glyphs, it works fine, until I reboot. Then some of the Powerline glyphs turn into the generic question mark symbol and stay that way.

#### 🔧 Your Setup

Font: Caskaydia Cove Nerd Font Complete Windows Compatible
Terminal: Windows Terminal
Shell: PowerShell with oh-my-posh 2
OS: Windows 10 Enterprise 20H2

#### ★ Optional

The separators in the prompt should look like a solid right-pointing triangle, but instead they're the missing glyph character:
![image](https://user-images.githubusercontent.com/5160192/103310405-899c6a80-49e5-11eb-8596-3135ff990a99.png)

**Comment by devilcrayon** [comment]
I have the same problem.  
After a restart I need to reinstall the nerd-font to get powerline glyphs back.  I've tried several fonts and it happens with all the ones I have tried.

Fonts: 
-  JetBrains Mono Regular Nerd Font Complete Windows Compatible
-  Fira Code Regular Nerd Font Complete Windows Compatible
- Hack Regular " " " " "
- Meslo LG Regular " " " " "
Terminal: Windows Terminal Version: 1.4.3243.0
Shell: zsh with oh-my-zsh & powerlever10k 
OS: Windows 10 Home 2004 Build 19041.746

**Comment by qidydl** [comment]
I just had a thought, and tried pasting my prompt into Word with the same font, and the glyphs appear there just fine. That suggests this could be a Windows Terminal bug, not a font bug. I will try to submit a bug report there and update this thread if I get any answers.

**Comment by qidydl** [comment]
Ok, definitely not a font issue, sorry for filing a spurious bug. There's a thread tracking the problem for Windows Terminal: https://github.com/microsoft/terminal/issues/3257

The short answer is, the font is not actually being used by Windows Terminal. You need to right-click the font file and select "Install for all users", and only then will it actually work in Windows Terminal, and the glyphs should show up.
