### ISSUE TITLE
Icon request : linux distro logos 

### ISSUE THREAD

**Issue by siduck76** [ryanoasis/nerd-fonts#562]
nerdfonts contains popular linux distros logos and there are many missing , would be great if it had void's/artix linux's logo as well . Can just update these fonts https://github.com/lukas-w/font-logos .

**Comment by DavidPeltz** [comment]
I too would love to see some of the newer logos in nerdfonts, specifically Pop!_OS for me :-)

**Comment by eliminmax** [comment]
[The Nerd Fonts website](https://www.nerdfonts.com/#home) lists Font Logos as a source for icons, but I can only assume it is an out-of-date version. I too would like to see the Pop!_OS logo added to Nerd Fonts.

**Comment by siduck76** [comment]
@eliminmax @DavidPeltz the issue is fixed here! #606
