### ISSUE TITLE
Caskaydia Cove Nerd Font: accent letters are boxes

### ISSUE THREAD

**Issue by DigiOhhh** [ryanoasis/nerd-fonts#568]
#### 🎯 Subject of the issue

Letters such as `à`, `è`, `ì`, `ò`, `ù` are rendered as boxes using Caskaydia Cove NF. No such issue with other fonts, f.e. MesloLGM NF and Cascadia Code PL.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ Caskaydia Cove Nerd Font
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ Cmder / ConEmu (if they qualify as terminal emulators)
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Windows 7 Ultimate

#### ★ Optional

- Caskaydia Cove NF:
![Temp](https://user-images.githubusercontent.com/37815914/105879790-e306b200-6002-11eb-8aee-5c1fed7f6f1d.PNG)

- MesloLGM NF:
![Temp](https://user-images.githubusercontent.com/37815914/105880190-59a3af80-6003-11eb-9bda-20b5c1a8da73.PNG)

**Comment by aistvan** [comment]
The problem still exists, and nobody want to do anything. I don't understand why this "Nerd font" - "Power Line" thing promoted while there is no real support. There are many nations outside of US with characters over the 7bit ASCII range. I'm really upset.

**Comment by DigiOhhh** [comment]
Why isn't anyone going to fix this?
Accented letters work on Windows Terminal, but are not using Caskaydia Cove

![image](https://user-images.githubusercontent.com/37815914/113880412-c1bd0180-97bb-11eb-9843-67024a73f231.png)

**Comment by ryanoasis** [comment]
Sorry to see this. Can you tell me if the problem occurs for you in other programs like Notepad++ or vscode? Thanks

**Comment by DigiOhhh** [comment]
Notepad++
![image](https://user-images.githubusercontent.com/37815914/114299464-a99afa00-9abb-11eb-9c73-4be9b7bc2063.png)

Visual Studio Code
![image](https://user-images.githubusercontent.com/37815914/114299477-b4558f00-9abb-11eb-8d91-eecdb82c3768.png)

Thank you for your concern.

**Comment by vtibix** [comment]
I experience the same issue with patched Cascadia. What I noticed is that it works as expected for a while in windows terminal, but today after installation I switched to the original non patched version then when I switched to the patched font it lost the proper accented characters and started to display those foreign letters.

**Comment by luizbgomide** [comment]
@Finni, indeed this version has the accents working. But I noticed some odd bugs with this, like being detected as two different faces (and at the same time, the Mono face getting lost).
![image](https://user-images.githubusercontent.com/18707781/159991506-10914b2a-505d-4289-9b41-8c4964774579.png)

I end up using FiraCode which seems to have a bit better support.

**Comment by Finii** [comment]
> as two different faces

The problem with the font grouping / family naming should be fixed in the `2111.01` version (is not yet in the RC), i.e. PR 723.

> FiraCode which seems to have a bit better support

I fear that also has family problems, but if it works :+1:

**Comment by luizbgomide** [comment]
> I fear that also has family problems, but if it works 👍

I noticed the Mono variant also disappearing, but I installed only the Fira Code a not the Mono version. It also had some weird issues like:
![image](https://user-images.githubusercontent.com/18707781/159996540-89d06225-17b3-4c6e-bfc3-a23ef7ce7950.png)

What makes me wonder if it is really worth the effort of having all those icons when the ligatures and even basic characters break now and then... :/

**Comment by luizbgomide** [comment]
> Anyhow, personally I use the patched Cascadia Code (as Delugia which is quite similar to Caskaydia) and that is my pet. If there is some issue I will give it all the love it deserves.

That is interesting, I couldn't find Delugia Font you are talking about here on the Patched Fonts. I will give the new Caskadya another try...

**Comment by Finii** [comment]
[Delugia](https://github.com/adam7/delugia-code) is a single font project from back when Cascadia was new and hot and everybody wanted a patched version. It automagically creates a new release instantly (same day, without human intervention) after Microsoft updates Cascadia.
It's almost obsolete, now that Caskaydia exists here.

**Comment by luizbgomide** [comment]
Got it, I'm using Caskaydia for now (again), but I'm using it just because I'm trying out terminal icons, otherwise it has not use for me. If I gave up on Terminal Icons I might go back to Cascadia Code PL.

**Comment by nikkehtine** [comment]
I can also confirm the problem

Cascadia Code:
![Cascadia Code](https://user-images.githubusercontent.com/27138416/163199484-a51f5dba-5f46-485a-a912-bff2fb939c25.png)

CaskaydiaCove NF:
![CaskaydiaCove NF](https://user-images.githubusercontent.com/27138416/163199368-584487df-c0ef-4901-a7cc-2be765ac94ac.png)

**Comment by Finii** [comment]
@nikkehtine Did you try the bugfixed (PR) font, which is the second link mentioned here https://github.com/ryanoasis/nerd-fonts/issues/568#issuecomment-1077823620?

**Comment by adriencarbonaro** [comment]
It works with v2.2.0, but the powerline icons seem buggy 
![image](https://user-images.githubusercontent.com/32357019/187890015-b2a80662-552f-4da2-8641-e6e0d70c0443.png)

**Comment by Finii** [comment]
@adriencarbonaro 

Hmm, just looking directly in the font file, it looks ok:

![image](https://user-images.githubusercontent.com/16012374/187892800-0c2342a2-ee96-4510-b4f6-4faad7442fc3.png)

Can you give more details like
* which font exactly
* downloaded from where
* which terminal
* terminal settings
* OS

etc ;)

BTW, current is `v2.2.1`.

**Comment by Finii** [comment]
Original Issue is fixed, so closing.

@adriencarbonaro please add information here or open new issue.

**Comment by adriencarbonaro** [comment]
It is fixed in `2.2.1`. Thanks !
