### ISSUE TITLE
Windows PS install script not finding fonts

### ISSUE THREAD

**Issue by fsackur** [ryanoasis/nerd-fonts#569]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

The install.ps1 in patched-fonts doesn't work; it makes assumptions about locations that don't hold, it uses wrong syntax for finding files.

I offer https://github.com/ryanoasis/nerd-fonts/pull/570 to resolve; only works on Windows.

**Comment by fsackur** [comment]
My PR also adds tab-completion, at the cost of losing wildcard support. I feel that's not a big deal in this case; tab-completion finds all folder names in `patched-fonts`. I prefer ArgumentCompleters over DynamicParams, but I can't see a way to make that work in the scenario of an executable script (rather than function).

**Comment by ryanoasis** [comment]
this was merged. closing
