### ISSUE TITLE
Version chaos on community/AUR

### ISSUE THREAD

**Issue by ZweiEuro** [ryanoasis/nerd-fonts#573]
Just so you are aware, it's very unclear what version is the most up to date and what version should be used.
```
[zweieuro@THECOIN ~]$ yay  -Ss spotifyd
aur/spotifyd-full-git 0.2.17.7.g8a82bec-1 (+4 1.37) 
    A spotify playing daemon (all features enabled)

community/spotifyd 0.3.0-1 (2.9 MiB 10.9 MiB) 
    Leightweigt spotify streaming daemon with spotify connect support

```

On your install page you list the aur package as most up to date, the version tag says otherwise. 
This is just confusing, which one is the most up to date? (also you got a typo in the community package)

**Comment by polyzen** [comment]
@ZweiEuro, 0.3.0 is the latest stable version. `-git` packages pull in and build off the latest commit, and would manage the `pkgver` in the process:
https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver()_function

 BTW you're posting in the wrong repo.

**Comment by ZweiEuro** [comment]
@polyzen I am so sorry !
