### ISSUE TITLE
Material Design Icons from the Community conflicts with CJK Compatibility Ideographs

### ISSUE THREAD

**Issue by strrchr** [ryanoasis/nerd-fonts#574]
https://en.wikipedia.org/wiki/Unicode_block
E000 — F8FF  	Private Use Area
F900 — FAFF  	CJK Compatibility Ideographs
FB00 — FB4F  	Alphabetic Presentation Forms
FB50 — FDFF  	Arabic Presentation Forms-A
https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points
Material Design Icons
	2000+ Material Design Icons from the Community. / (repo) / (website)
	Code Point Ranges: f500-fd46

**Comment by pstray** [comment]
This is quite annoying, especially since the arabic glyphs have an Inherent Right-to-Left property associated with them, thus causing things to get weird when trying to use them.

**Comment by Finii** [comment]
Release is in repo, release as packages pending.
