### ISSUE TITLE
Mononoki Nerd Font Needs Updating

### ISSUE THREAD

**Issue by redactedscribe** [ryanoasis/nerd-fonts#575]
#### 🎯 Subject of the issue
The source [madmalik/mononoki](https://github.com/madmalik/mononoki) recently updated Mononoki on the 31 Jan 2021 (["updated character set"](https://github.com/madmalik/mononoki/releases/tag/1.3)). Last release was 10 Jun 2016. The nerd font could be updated at some point.

**Comment by redactedscribe** [comment]
The font's updates should now be included due to https://github.com/ryanoasis/nerd-fonts/commit/c5b8b55f68f5c35aa0aef9f88ff493161ac173b2. Thanks!

**Comment by Finii** [comment]
I fear this has not been updated, there was no PR for it.

![Screenshot_20220826_153415](https://user-images.githubusercontent.com/16012374/186915801-00c8e1fd-b98b-4cf3-a936-3f6def516180.jpg)

Lets create one for 2.3.0_RC (later).

**Comment by redactedscribe** [comment]
My Nerd Fonts are managed by a Scoop bucket and it just pushed out an update for many of the NF fonts, Mononoki included, so I assumed it had been: https://github.com/matthewjberger/scoop-nerd-fonts/commit/dfded9fe717498630a4f106ef8e62d49d8dca550. After installing the font and restarting the system, at least _something_ has changed because the font in VS Code/Codium now displays double as wide as before:

![VSCodium](https://user-images.githubusercontent.com/25013746/186925513-9d7ccd7a-4d91-4f7c-816c-c6109b506271.jpg)

Not sure why, but other programs seem to be unaffected by this bug, and it can be essentially mitigated in Code/Codium by using `editor.letterSpacing": -5`.

**Comment by Finii** [comment]
Thanks for reporting the bug so quickly!

I hope v2.2.1 will hold up to your expectations.

Added comment to the v2.2.0:
> A bugfix release is already in the making: [2.2.1](https://github.com/ryanoasis/nerd-fonts/releases), but that will take about 5 hours until all fonts have been re-patched.
>
> The new release will be  https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.2.1 if ready (i.e. ~27-08-2022 00:00:00 UTC). :clock1:

**Comment by Finii** [comment]
@madmalik Dear Matthias, maybe you have heard of Nerd Fonts. We add a lot of icons the existing programming fonts and did so in the past also with your great font. We do not change the existing glyphs. The resultant patched fonts are distributed by several different packaging systems on all relevant platforms. Maybe you can consider the issue below.
Any answer (negative or positive) is appreciated.

Thank you,

   Finii

Just updated `mononoki` locally to 1.5 but noticed that now the license has a RFN clause (*)

This means that we can not distribute a `mononoki Nerd Font` anymore, except @madmalik grants us a specific exception.
I guess it would be in `mononoki`'s interrest to not introduce another name for a variant that just adds some more icons.


But for new we need to either rename the font on patching (suggestions welcome) or get an exception (like we had with `Fira` in the past).

(*) Well, it had an RFN before, but that was not `mononoki`, astonishingly, probably in error.

**Comment by madmalik** [comment]
> (*) Well, it had an RFN before, but that was not mononoki, astonishingly, probably in error.

Correct, i had neglected to update the license file, which i now fixed.

> This means that we can not distribute a mononoki Nerd Font anymore, except @madmalik grants us a specific exception. I guess it would be in mononoki's interrest to not introduce another name for a variant that just adds some more icons.

I'm fine with you using the name mononoki as part of the name for the Nerd Font version, as long as it is clear from the full name, that this is the Nerd Font version and not the original, for example by adding a suffix such as "NF".

**Comment by Finii** [comment]
@madmalik Great, thank you!!

All the names (full, font, and family) will end up as "mononoki Nerd Font" resp "mononoki NF" (for the Windows version to keep the name short).

**Comment by Finii** [comment]
The resulting naming is as shown below:

```
$ ./gotta-patch-em-all-font-patcher\!.sh -cj /Mononoki
# [Nerd Fonts]  Filter given, limiting search and patch to pathname pattern '/Mononoki'
# [Nerd Fonts]  Total source fonts found: 4
# [Nerd Fonts]  Release timestamp is Tue, 17 Jan 2023 13:31:00 +0100
# [Nerd Fonts]  Processing font 1/4
# [Nerd Fonts]  Processing font 2/4
# [Nerd Fonts]  Processing font 3/4
# [Nerd Fonts]  Processing font 4/4
Nerd Fonts Patcher v2.3.0-RC (3.4.3) executing
Nerd Fonts Patcher v2.3.0-RC (3.4.3) executing
Nerd Fonts Patcher v2.3.0-RC (3.4.3) executing
Nerd Fonts Patcher v2.3.0-RC (3.4.3) executing
Redistributing line gap of 209 (104 top and 105 bottom)
Redistributing line gap of 209 (104 top and 105 bottom)
Redistributing line gap of 229 (114 top and 115 bottom)
Redistributing line gap of 229 (114 top and 115 bottom)
[...]
```
```
$ fontforge name_parser/query_names ../../check-fonts/Mononoki/**/*.ttf  2>/dev/null
Examining 16 font files
 |Filename                                           | | Fullname                                                          | | Family                                                  | | Subfamily                      | | Typogr. Family                           | | Typogr. Subfamily
 |-------------------------------------------------- |-| ------------------------------------------------------------      |-| ------------------------------------------------------- |-| ------------------------------ |-| ---------------------------------------- |-| ----------------------------------------
 |mononoki Bold Nerd Font Complete Mono.ttf          | | mononoki Bold Nerd Font Complete Mono                             | | mononoki Nerd Font Mono                                 | | Bold                           | | mononoki Nerd Font Mono                  | | Bold
 |mononoki Bold Nerd Font Complete Mono Windows Comp | | mononoki Bold Nerd Font Complete Mono Windows Compatible          | | mononoki NFM                                            | | Bold                           | | mononoki NFM                             | | Bold
 |mononoki Bold Nerd Font Complete.ttf               | | mononoki Bold Nerd Font Complete                                  | | mononoki Nerd Font                                      | | Bold                           | | mononoki Nerd Font                       | | Bold
 |mononoki Bold Nerd Font Complete Windows Compatibl | | mononoki Bold Nerd Font Complete Windows Compatible               | | mononoki NF                                             | | Bold                           | | mononoki NF                              | | Bold
 |mononoki BoldItalic Nerd Font Complete Mono.ttf    | | mononoki BoldItalic Nerd Font Complete Mono                       | | mononoki Nerd Font Mono                                 | | Bold Italic                    | | mononoki Nerd Font Mono                  | | BoldItalic
 |mononoki BoldItalic Nerd Font Complete Mono Window | | mononoki BoldItalic Nerd Font Complete Mono Windows Compatible    | | mononoki NFM                                            | | Bold Italic                    | | mononoki NFM                             | | BoldItalic
 |mononoki BoldItalic Nerd Font Complete.ttf         | | mononoki BoldItalic Nerd Font Complete                            | | mononoki Nerd Font                                      | | Bold Italic                    | | mononoki Nerd Font                       | | BoldItalic
 |mononoki BoldItalic Nerd Font Complete Windows Com | | mononoki BoldItalic Nerd Font Complete Windows Compatible         | | mononoki NF                                             | | Bold Italic                    | | mononoki NF                              | | BoldItalic
 |mononoki Italic Nerd Font Complete Mono.ttf        | | mononoki Italic Nerd Font Complete Mono                           | | mononoki Nerd Font Mono                                 | | Italic                         | | mononoki Nerd Font Mono                  | | Italic
 |mononoki Italic Nerd Font Complete Mono Windows Co | | mononoki Italic Nerd Font Complete Mono Windows Compatible        | | mononoki NFM                                            | | Italic                         | | mononoki NFM                             | | Italic
 |mononoki Italic Nerd Font Complete.ttf             | | mononoki Italic Nerd Font Complete                                | | mononoki Nerd Font                                      | | Italic                         | | mononoki Nerd Font                       | | Italic
 |mononoki Italic Nerd Font Complete Windows Compati | | mononoki Italic Nerd Font Complete Windows Compatible             | | mononoki NF                                             | | Italic                         | | mononoki NF                              | | Italic
 |mononoki Regular Nerd Font Complete Mono.ttf       | | mononoki Regular Nerd Font Complete Mono                          | | mononoki Nerd Font Mono                                 | | Regular                        | | mononoki Nerd Font Mono                  | | Regular
 |mononoki Regular Nerd Font Complete Mono Windows C | | mononoki Regular Nerd Font Complete Mono Windows Compatible       | | mononoki NFM                                            | | Regular                        | | mononoki NFM                             | | Regular
 |mononoki Regular Nerd Font Complete.ttf            | | mononoki Regular Nerd Font Complete                               | | mononoki Nerd Font                                      | | Regular                        | | mononoki Nerd Font                       | | Regular
 |mononoki Regular Nerd Font Complete Windows Compat | | mononoki Regular Nerd Font Complete Windows Compatible            | | mononoki NF                                             | | Regular                        | | mononoki NF                              | | Regular
```

**Comment by Finii** [comment]
Changed naming algorithm (cant stand the old one any longer)...
Looks so much nicer and cleaner:
```
Fullname                                                          | | Family                                                  | | Subfamily                      | | Typogr. Family                           | | Typogr. Subfamily
------------------------------------------------------------      |-| ------------------------------------------------------- |-| ------------------------------ |-| ---------------------------------------- |-| ----------------------------------------
Mononoki Nerd Font Complete Bold                                  | | Mononoki Nerd Font                                      | | Bold                           | |                                          | |
Mononoki Nerd Font Complete Mono Bold                             | | Mononoki Nerd Font Mono                                 | | Bold                           | |                                          | |
Mononoki Nerd Font Complete Mono Windows Compatible Bold          | | Mononoki NF Mono                                        | | Bold                           | |                                          | |
Mononoki Nerd Font Complete Windows Compatible Bold               | | Mononoki NF                                             | | Bold                           | |                                          | |
Mononoki Nerd Font Complete Bold Italic                           | | Mononoki Nerd Font                                      | | Bold Italic                    | |                                          | |
Mononoki Nerd Font Complete Mono Bold Italic                      | | Mononoki Nerd Font Mono                                 | | Bold Italic                    | |                                          | |
Mononoki Nerd Font Complete Mono Windows Compatible Bold Italic   | | Mononoki NF Mono                                        | | Bold Italic                    | |                                          | |
Mononoki Nerd Font Complete Windows Compatible Bold Italic        | | Mononoki NF                                             | | Bold Italic                    | |                                          | |
Mononoki Nerd Font Complete Italic                                | | Mononoki Nerd Font                                      | | Italic                         | |                                          | |
Mononoki Nerd Font Complete Mono Italic                           | | Mononoki Nerd Font Mono                                 | | Italic                         | |                                          | |
Mononoki Nerd Font Complete Mono Windows Compatible Italic        | | Mononoki NF Mono                                        | | Italic                         | |                                          | |
Mononoki Nerd Font Complete Windows Compatible Italic             | | Mononoki NF                                             | | Italic                         | |                                          | |
Mononoki Nerd Font Complete Mono Regular                          | | Mononoki Nerd Font Mono                                 | | Regular                        | |                                          | |
Mononoki Nerd Font Complete Mono Windows Compatible Regular       | | Mononoki NF Mono                                        | | Regular                        | |                                          | |
Mononoki Nerd Font Complete Regular                               | | Mononoki Nerd Font                                      | | Regular                        | |                                          | |
Mononoki Nerd Font Complete Windows Compatible Regular            | | Mononoki NF                                             | | Regular                        | |                                          | |
```

**Comment by redactedscribe** [comment]
> Just updated mononoki locally to 1.5

@Finii Looking forward to 1.5.

It's unfortunate that, at least via Windows' Settings > Personalization > Fonts, it's only possible to see the Nerd Fonts' version number. It would be useful if the reported version could note the NF version _and_ the original version it is based off:

![ApplicationFrameHost_2023-01-17_21-28-10](https://user-images.githubusercontent.com/25013746/212993978-cbc45337-2d9e-44fd-bf59-34af79966213.png)

I'm not sure what the `Version 1.001` is, but since there's two version numbers already present, it would appear another could be included `;NF @ Mononoki 1.5` for example. Not a critical change, and I don't know its negative implications, if any, but it'd make understanding which version of an original font that NF is using easier than having to visit NF's repo and click around (unless there's a simpler way)?

Thanks.

**Comment by Finii** [comment]
Nerd Font adds `; Nerd Fonts 2.2.2` to the version string of the original font.
So `Version 1.001` is what mononoki originally has.

I can only guess why they use that version; it looks like the sfnt revision (a number not a string).
But they set it explicitly.

Even more strange, with `mononoki 1.5` they set `Version 1.004` :thinking: 

![image](https://user-images.githubusercontent.com/16012374/213121075-de4f6a36-f77b-4f58-abc2-5f7473f292b0.png)

![image](https://user-images.githubusercontent.com/16012374/213121135-843df1a4-bcd5-4f25-9913-784002c749fd.png)

https://github.com/madmalik/mononoki/blob/main/src/mononoki-Regular.ufo/fontinfo.plist#L58-L61

Hmm, from `git blame` I assume they just forget to change it with 1.5 and that is still 1.4:

![image](https://user-images.githubusercontent.com/16012374/213121909-4cd7bcd5-bf04-4e89-85ee-f5162d470ed9.png)

So, concluding:
The original font's version is preserved. If you think that version-string is ~~useless~~ not very useful, you need to complain at the original font's repo.

_Note: And `mononoki`'s version is rather useful, there are fonts that have `1.000` for all versions_ :grimacing:

**Comment by redactedscribe** [comment]
@Finii By the sounds of it, it's not possible to rely upon the version string from within a font since many are inaccurate. Anyway, thank you for looking into it.

**Comment by redactedscribe** [comment]
@Finii I just updated to 2.3.0 NF fonts and Mononoki's mono font has been renamed from "Mononoki NFM" to "Mononoki NF Mono". Not sure why this was necessary when the other NF fonts on my system still use "NFM" in their name, or perhaps this was a mistake? The past two times Mononoki has updated I've had to fiddle with application font settings to get things working again.
