### ISSUE TITLE
Import latest Cascadia Code release

### ISSUE THREAD

**Issue by cprivitere** [ryanoasis/nerd-fonts#577]
Just tossing in an issue to get Caskaydia Cove re-built from the latest upstream: https://github.com/microsoft/cascadia-code. 

I don't know if it will take care of a number of the other Caskaydia Cove related issues, but hey maybe it'll help!

**Comment by oldium** [comment]
I tried to build it, here is the result (generated _complete_ from the static TTF Cascadia Code folder of 2102.03 version).
[caskaydia-cove-nerd-fonts.zip](https://github.com/ryanoasis/nerd-fonts/files/5976477/caskaydia-cove-nerd-fonts.zip)

**Comment by oldium** [comment]
For some reason on Windows the Semi Light version is sorted after Bold, not between Light and Regular, like it is for the original Cascadia Code font.

**Comment by RomelSan** [comment]
> 
> 
> I tried to build it, here is the result (generated _complete_ from the static TTF Cascadia Code folder of 2102.03 version).
> [caskaydia-cove-nerd-fonts.zip](https://github.com/ryanoasis/nerd-fonts/files/5976477/caskaydia-cove-nerd-fonts.zip)

Can you please update to CascadiaCode-2102.25

**Comment by oldium** [comment]
Done. Updated from version 2102.25.
[caskaydia-cove-nerd-fonts.zip](https://github.com/ryanoasis/nerd-fonts/files/6289393/caskaydia-cove-nerd-fonts.zip)

**Comment by BobSilent** [comment]
to reference similar items: #601, #628

**Comment by MrJmpl3** [comment]
I clone Cascadia Code and Nerd Fonts.

1) Build the Cascadia Code with Italic names fixed.
2) Patch the new Cascadia Code (of the point 1) with Nerd Fonts

[Caskaydia Cove.zip](https://github.com/ryanoasis/nerd-fonts/files/6570437/Caskaydia.Cove.zip)

**Comment by RomelSan** [comment]
CascadiaCode-2106.17 Released.
https://github.com/microsoft/cascadia-code/releases/tag/v2106.17

**Comment by coxackie** [comment]
any updates here? (or, maybe, wait for a little while, I think a new version is coming up...)

**Comment by zzhaolei** [comment]
Looking forward to any updates here 😚

**Comment by trallnag** [comment]
@MrJmpl3, have you checked if your patched font matches the original variable TTF? I tried patching yesterday and I noticed that the patched font looks quite different from the original variable TTF.

**Comment by Finii** [comment]
@trallnag 

> have you checked if your patched font matches the original variable TTF? I tried patching yesterday and I noticed that the patched font looks quite different from the original variable TTF.

The hints are different. The static fonts are just pushed through default `ttfautohint`. I found that TTH would create better hints, and even unhinted looks better. Maybe I can come up with a solution together with Aaron, but that will be after `v3.0.0` I guess.

Must admit that I never closely looked at Windows, and both Linux and Mac do not need hints to render (i.e. ignore them anyhow) :grimacing: 

---

As for the issue here, Nerd Fonts has Cascasdia Code 2111.01 since ... some releases already. So this is solved.

**Comment by Finii** [comment]
Ah, additional comment: Ah, Windows **also** does ignore the hints (and the fonts render equal) in `WordPad` and I have heard in `Word` but that I do not have. There are different settings in Windows for the antialiasing, maybe there are settings that work better with the static (and patched) fonts.

**Comment by aaronbell** [comment]
@Finii 

It is worth keeping in mind that there are multiple rendering engines in Windows—the older GDI engine and newer DirectWrite engine.

The hints included in Cascadia Code (and pretty much all modern fonts) are intended for the newer environment and will not render as well under the older one. So what might look like Windows ignoring hints is actually just a surface where GDI is still used.
