### ISSUE TITLE
Nerd Font icon dosen't work in urxvt

### ISSUE THREAD

**Issue by NickTonEZanimal** [ryanoasis/nerd-fonts#578]
Nerd Font icon dosen't work in urxvt but in another terminal (sakura) its work
https://i.imgur.com/20UPtsn.png left - urxvt; right - sakura
My Xresources - https://dpaste.com/5RZALZF4Q

**Comment by NickTonEZanimal** [comment]
My distro is Gentoo

**Comment by donragui** [comment]
I have the same issue.

**Comment by kierun** [comment]
In `~/.Xdefault` add the following:

```
urxvt256c-ml*font: xft:mplus Nerd Font:pixelsize=19:style=Regular:pixelsize=19:antialias=true:autohint=true
```

What you really want is the `xft` bit, the rest should be more or less self-explanatory. 

You seem to have that in your `.Xresources` but that is not the set up I have. In addition, I use `urxvt256c-ml` which might be slightly different.

Is urxvt compiled with `xft` support?

Here is a screen shot of what I see:

![screenshot](https://user-images.githubusercontent.com/3079575/108257935-64abb480-7157-11eb-9953-d8b061f2ae9f.png)
