### ISSUE TITLE
Patch the latest version of DaddyTimeMono

### ISSUE THREAD

**Issue by tulemizh** [ryanoasis/nerd-fonts#580]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🔧 Your Setup

- _`DaddyTimeMono Nerd Font Book Complete.ttf`_

#### ★ Optional

Hello there, the author of `DaddyTimeMono` just pushed a [commit](https://github.com/BourgeoisBear/DaddyTimeMono/commit/f6a8dc479d9efca351f1f8fcd660b8fa6048ac19) for supporting Unicode characters. Please patch the new Nerd Font version for DaddyTimeMono. Thank you very much!

**Comment by Finii** [comment]
Release is in repo, release as packages pending.
