### ISSUE TITLE
backtick for Inconsolata NF overlaps with character afterwards

### ISSUE THREAD

**Issue by abelcheung** [ryanoasis/nerd-fonts#582]
## 🔧 Your Setup

- Windows 7
- Inconsolata NF Mono (Windows compatible, TTF)
- Visual Studio code (not sure if non-terminal usage warrants an issue report; trying anyway since it is a regression from unpatched font)

## Issue description

One can refer to screenshots below. Backtick from Inconsolata NF would overlap with char that follows. On that particular position, cursor would not advance at all, behaving like a zero-wdith glyph.

So far no character other than backtick has such behavior observed.

### Using unpatched Inconsolata downloaded from Google

![圖片](https://user-images.githubusercontent.com/83110/107895561-b4a63380-6f2b-11eb-8265-0226ac43df36.png)

### Using Inconsolata NF

![圖片](https://user-images.githubusercontent.com/83110/107895646-fc2cbf80-6f2b-11eb-9c68-a86f33cb3212.png)

**Comment by Mazyod** [comment]
Seems like it's still an issue?

![image](https://user-images.githubusercontent.com/860511/120412628-8d9b3280-c35f-11eb-83d7-d438e47ba9fb.png)

**Comment by Finii** [comment]
Will work on this in 858 because this is closed.

**Comment by inostia** [comment]
Status update on this one? I just encountered it in VSCode.
