### ISSUE TITLE
way to disable individual ligature in Fira Code Nerd Mono

### ISSUE THREAD

**Issue by con-f-use** [ryanoasis/nerd-fonts#583]
Is there way to get rid of just the Haskel `***` operator ligature in Fira Code Nerd Mono? It's the one, where the middle asterisk is a bit higher than the outer two.

![image](https://user-images.githubusercontent.com/11145016/108519331-d146c080-72c9-11eb-9838-03a73e967896.png)

**Comment by Finii** [comment]
This depends on your terminal. Usually terminals that are able to display ligatures have an option to turn them off.

I remember there is also a tool on github where one can remove ligatures or 'burn in' stylistic sets. Unfortunately I can not remember its name right now :thinking:
