### ISSUE TITLE
Fix Font Awesome Glyphs

### ISSUE THREAD

**Issue by TechieAndroid** [ryanoasis/nerd-fonts#584]
I initially thought nerd fonts included font awesome but after installing everything in nerd fonts I checked my fonts dir and font awesome is not in there.

**Comment by meisme-dev** [comment]
Font awesome is included, read the readme.

**Comment by TechieAndroid** [comment]
> Font awesome is included, read the readme.

Redundant comment but okay.

Care to share what you got that from because I'm looking in the repo and it doesn't contain font awesome. And it also doesn't list it among the other patches fonts in the readme, so idk what you saw.

**Comment by polyzen** [comment]
> Care to share what you got that from because I'm looking in the repo and it doesn't contain font awesome.

https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/FontAwesome.otf

> And it also doesn't list it among the other patches fonts in the readme, so idk what you saw.

It doesn't patch Font Awesome with extra glyphs, it bundles the Font Awesome glyphs with other [glyph sets](https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points), to be used alongside your font/s of choice.

**Comment by TechieAndroid** [comment]
Then why do the glyphs not match the website's cheatsheet? It's as if I don't have them installed or they're conflicting with another glyphs IDs. I installed everything from nerdfonts so I should have font awesome.

**Comment by flibX0r** [comment]
You seem to misunderstanding the purpose of these fonts. These existing monospaced fonts are patched with the icons from FontAwesome, Material Design, Devicons and others so you can use them without switching fonts for each icon. It doesn't install the FontAwesome font itself, it allows you to use the FontAwesome icons (albiet only v4.7.0) at their original glyph points within another font. So you can use the icons in source code, or console output, or any other monospaced environment.

Is your issue more that it's only patched with FontAwesome v4.7.0? That is an valid existing issue (#221) and one that I don't understand the massive delay behind. You can manually patch them in yourself but you'll have to pull down the repo and update the config yourself (a pain, I know)

**Comment by TechieAndroid** [comment]
> You seem to misunderstanding the purpose of these fonts. These existing monospaced fonts are patched with the icons from FontAwesome, Material Design, Devicons and others so you can use them without switching fonts for each icon. It doesn't install the FontAwesome font itself, it allows you to use the FontAwesome icons (albiet only v4.7.0) at their original glyph points within another font. So you can use the icons in source code, or console output, or any other monospaced environment.
> 
> Is your issue more that it's only patched with FontAwesome v4.7.0? That is an valid existing issue (#221) and one that I don't understand the massive delay behind. You can manually patch them in yourself but you'll have to pull down the repo and update the config yourself (a pain, I know)

That may be the root problem then.

My main issue as I mentioned in my previous comment, is that I have no way to confirm the glyphs are there since they don't correlate to the official font awesome glyph cheat sheet, e.g. I cant copy them from their website and like I can with nerd font's cheat sheet. Speaking of nerd fonts cheat sheet, why aren't font awesome glyphs in there?

**Comment by TechieAndroid** [comment]
![image](https://user-images.githubusercontent.com/17918163/110045744-c26ffd00-7d10-11eb-98e5-4db28a1be131.png)

I'm guessing all the missing glyphs are also apart of the problem I'm having.
I really wish someone who knew something about nerd fonts / font awesome could help me out on this.

**Comment by flibX0r** [comment]
The FontAwesome glyphs in the nerd fonts use the same codepoints as the original font.
You can find them on the [Nerd Fonts Cheat Sheet](https://www.nerdfonts.com/cheat-sheet) by searching for the `nf-fa-` prefix (all of the icons have the `nf-` prefix, font awesome icons then have the `fa-` prefix)
They're also available here: https://fontawesome.com/v4.7.0/icons/

The glyphs you're looking at in that screenshot are in the **Miscellaneous Symbols and Pictographs** (`U+1F300 - U+1F5FF`) unicode block and is where emoji are stored, not the icons used in these fonts. The icons used in Nerd Fonts are stored in the **Private Use Area** (`U+E000 - U+F8FF`). I don't know if any of the fonts available in this repo have emoji glyphs, it's not the purpose of these patched fonts to support emojis, it's largely up to the operating system and text renderer to support them.

Given the tiny icon at the bottom of your screenshot I'm guessing you're running Gentoo Linux (nice), Google's Noto emoji font is available on portage as `media-fonts/noto-emoji` if you need emoji support. Twemoji and Emojione fonts are also available in some overlays

**Comment by ryanoasis** [comment]
I believe we can resolve this as fixed. Thanks all.

@TechieAndroid, I believe @flibX0r summarizes it well there.

**Comment by TechieAndroid** [comment]
> I believe we can resolve this as fixed. Thanks all.
> 
> @TechieAndroid, I believe @flibX0r summarizes it well there.

Yeah and I think the problem was just that the nerd fonts repo had a old version of font awesome as I later found out.
