### ISSUE TITLE
Iosevka Nerd Font does not work in Windows Terminal or putty

### ISSUE THREAD

**Issue by jeffrson** [ryanoasis/nerd-fonts#586]
#### 🎯 Subject of the issue

While Windows Terminal says it cannot find the font "Iosevka NF", putty does not offer it in font selection dialog. Old powershell or cmd however seem to accept it.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
Iosevka Term Nerd Font Complete Mono Windows Compatible.ttf
and a couple of others

- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
Windows Terminal

- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Windows 10 20H2

**Comment by mfocko** [comment]
there is a naming issue with iosevka, try using it without the NF / Nerd Font suffix

**Comment by tatsuya0619** [comment]
I had the same issue. However as you said I could solve it by using "Iosevka" not "Iosevka NF". Thank you.

**Comment by jeffrson** [comment]
Unfortunately for me it doesn't work (with Windows Terminal).

**Comment by Finii** [comment]
Maybe you can try the `v3.0.0`: Iosevka Term NFM (there is no Windows Compat anymore).

**Comment by jeffrson** [comment]
I can confirm now, that these fonts work in both Windows Terminal and Putty.

Needed to restart Windows Terminal, though.
