### ISSUE TITLE
Hope to add Sarasa-Gothic(更纱黑体)

### ISSUE THREAD

**Issue by DustinWin** [ryanoasis/nerd-fonts#587]
Hope to add Sarasa-Gothic(https://github.com/be5invis/Sarasa-Gothic). When displaying Chinese, the font size can be matched with English.
Use Sarasa-Gothic:
![QQ截图20210305040617](https://user-images.githubusercontent.com/45238096/110023586-4a352600-7d68-11eb-979d-87f9f539600f.png)
Use JetBrainsMono NF:
![QQ截图20210305040650](https://user-images.githubusercontent.com/45238096/110023656-61741380-7d68-11eb-8187-68bbbd6255b5.png)
It can be seen that when the JetBrainsMono NF is used, Chinese is squashed up and down.

Thans!

**Comment by FollieHiyuki** [comment]
I don't think this is gonna be accepted. Sarasa has so many flavors, and its counterpart (Iosevka) already is here.

**Comment by DustinWin** [comment]
> I don't think this is gonna be accepted. Sarasa has so many flavors, and its counterpart (Iosevka) already is here.
I tried to install Iosevka, and found that the font can be set in PowerShell, but the Chinese is garbled and the "code page"（代码页） needs to be changed. The font cannot be selected in cmd.

**Comment by MountComb** [comment]
When mixing CJK and Latin characters, a “monospace” font providing exactly 2:1 CJK to Latin character width would be needed for proper character alignment.

Unfortunately, Sarasa Gothic is the only option as far as I know. Iosevka does not provide CJK characters.

If it's difficult to supporting all Sarasa Gothic flavors, adding only the Term or Mono flavor would be of great help.

**Comment by ChiefMikeK** [comment]
I though [Iosevka features - Wikipedia](https://en.wikipedia.org/wiki/Iosevka#Features ) included DOUBE WIDTH MONO CJK

**Comment by zhiyuanzhai** [comment]
> I think you can try [Sarasa-Gothic-Nerd-Fonts](https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts)

@ifplusor That project excludes `material design` icons.

**Comment by DustinWin** [comment]
> @DustinWin I think you can try [Sarasa-Gothic-Nerd-Fonts](https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts)

Thans!

**Comment by Finii** [comment]
The material design icons will be moved (for exactly that reason), see
* #773 
* #365

Funny, https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts takes Delugia's workflow :-D
But it still takes Nerd Fonts v2.1; I updated Delugia in the meantime to v2.2.2.

**Comment by Finii** [comment]
If I see this correctly they have

```
Sarasa | Gothic     | CL | Extralight | -         
       | Fixed      | HC | Light      | Italic
       | Fixed Slab | J  | Regular    |
       | Mono       | K  | Semibold   |
       | Mono Slab  | SC | Bold       |
       | Term       | TC |            |
       | Term Slab  |    |            |
```

That is really a whole lot, especially as the font files are huge.
A good candidate would be the `.ttc`, but unfortunately - although we can process them finally - I have found no way to keep them concise (keep sharing glyphs).

Maybe we can cut that number of fonts downs dramatically, and/or help @jonz94 to keep up with Nerd Font changes.

**Comment by Finii** [comment]
Ah, they assemble the separate fonts into ttcs afterwards
* https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts/issues/3

Would be interesting to see if the tool they use is better with repacking than we are (which is `fontforge`, which's ttc support seems to be rudimentary).

Our ttc support has been added here:
* #783

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095

**Comment by cloud-yu** [comment]
[Sarasa-Gothic-Nerd-Fonts](https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts) patch failed because SNFT limits 65535 glyph, any help?

**Comment by Finii** [comment]
@cloud-yu 

https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts/actions/runs/10542676278/job/29209788923
> `The 'sfnt' format is currently limited to 65535 glyphs, and your font has 65910 of them.`

That is a limitation of the fonts in general and can not be changed / extended.

Nerd Fonts adds up to ~10`000 glyphs, Sarasea already has many many, so the total is too many glyphs.
Possible solutions:
* Do not patch in sets that are not needed (i.e. do not patch in the material design icons). That reduces the number of glyphs `font-patcher` adds and helps to keep the total number below 64k.
* Use the Symbols Only font and fontfallback, then you do not need a patched font at all. But that
  * Is not possible in all situations
  * does not always place the icons in good position relative to the cell

And/or you can drop some of the original glyphs of Sarasea that are seldom/never used (if there are any).

There is in fact not any complete nice solution, sorry.

**Comment by Finii** [comment]
Ah jonz94 already did drop some icons ... \*sigh\*

https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts/issues/29#issuecomment-2112336266

As the number of glyphs of Nerd Fonts increases over time this will get worse :-(

**Comment by Finii** [comment]
Hmm, happened out of the blue with same commit?!

![image](https://github.com/user-attachments/assets/c36021f8-d6e9-4b03-8b07-93caaf2c409f)

Did you inform / seek help from jonz94?

**Comment by cloud-yu** [comment]
same commit, but sarasa version is different.  
things get worse as you said, more glyphs should be dropped
