### ISSUE TITLE
Installation via option 1 doesn't install glyphs

### ISSUE THREAD

**Issue by uber6** [ryanoasis/nerd-fonts#588]
#### 🎯 Subject of the issue

None of the glyphs were working when I followed the Option 1 and 2 of the installation for Hack font on Fedora 33. I unzipped and copied the fonts files to ~/.local/share/fonts, ran `fc-cache -v -r`, confirmed that the font was installed using `fc-list | grep Hack`. However none of the glyphs displayed.

Solution: I cloned the repo and used `./install.sh Hack`. I think the fonts in the .zip file doesn't contain the right font files maybe. I'm quite new to this so I wasn't really able to troubleshoot.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?
  - I'm using Hack
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?
  - GNOME Terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
  - Linux (Fedora 33)

**Comment by ryanoasis** [comment]
Sounds like you came to a solution. going to close this. please re-open if i'm wrong. thanks
