### ISSUE TITLE
add option to include/patch trigrams (`2630` through `2637`)

### ISSUE THREAD

**Issue by poetaman** [ryanoasis/nerd-fonts#589]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

Some powerline glyphs are not added by font-patcher. These are the same ones listed there: https://github.com/ryanoasis/nerd-fonts/issues/100#issuecomment-242726762. The terminal emulator I use also slows down as a side effect, but that's not the main point. It will be good if font-patcher src fonts are updated to include these glyphs. Not all the terminal emulators support fallback fonts either, so can't really rely on that as a fix.

#### 🔧 Your Setup

- _Which font are you using?_ 
        -- OperatorMono (commercial font)
- _Which terminal emulator are you using?_ 
        -- WezTerm
- _Are you using OS X?_ 
        -- macOS

**Comment by Finii** [comment]
I believe at least 2630 should be added to the core set.
