### ISSUE TITLE
Missing ligatures after patching Iosevka

### ISSUE THREAD

**Issue by mfocko** [ryanoasis/nerd-fonts#591]
#### 🎯 Subject of the issue

After patching Iosevka 5.0.5 (recently released), I noticed I'm missing ligatures in the fonts (I've patched both Iosevka and Iosevka Curly Slab variant), but they're not missing in the Extended variant of the font. I simply thought it's the problem with the font. However I've also noticed no stylistic sets in those problematic fonts, so it might be a problem with the patcher.

Issue at Iosevka repository: https://github.com/be5invis/Iosevka/issues/910

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ Iosevka 5.0.5
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Fedora 33 (built on archLinux)

**Comment by mfocko** [comment]
Seems to be fine with 5.0.6 release, not sure what is going on :D

**Comment by Finii** [comment]
Did you self patch, or use font from here? Can you give links where downloaded exactly?
And copy and paste the glyphs as text please, so I can try.

**Comment by mfocko** [comment]
I self patch, using latest latest `nerd-fonts` and TTF Iosevka package, e.g. https://github.com/be5invis/Iosevka/releases/download/v15.1.0/ttf-iosevka-15.1.0.zip

I use `Term` variant lately, so not sure if it's still broken or not, since I stopped patching the fonts.

**Comment by mfocko** [comment]
yeah, still broken, even with `Term` variant

**Comment by Finii** [comment]
When you self patch, do you get the 16 bit warning from `fontforge`?
Of course you use an up to date `fontforge` (i.e. after [my fix in fontforge](https://github.com/fontforge/fontforge/pull/4883)), which probably means self building `fontforge` or using [`fontforge release March 2022`](https://github.com/fontforge/fontforge/releases/tag/20220308)?

If the ligatures are still missing when you use the bugfixed `fontforge` I can have a look at `font-patcher`, but the likelihood is slim.

**Comment by Finii** [comment]
See #742

**Comment by Finii** [comment]
See hints in the bottom of #742
