### ISSUE TITLE
RobotoMono "Mono" variant is too widely spaced

### ISSUE THREAD

**Issue by rrobertobt** [ryanoasis/nerd-fonts#597]
#### 🎯 Subject of issue

The "RobotoMono Nerd Font Mono" seems to have been spaced more widely than the **non-mono** version "RobotoMono Nerd Font"
Seems like this issue has been reported once in the past but didn't find a solution: #220 
It partly affects terminals like kitty and Alacritty but these have cell spacing and sizing configuration options so it can be solved

Screenshots with detailed description are below

#### 🔧 My current set-up

- _RobotoMono Nerd Font 11_
- _GNOME Terminal, Tilix, Kitty_
- _Fedora Linux 33 x86_64_

#### ★ Screenshots

**Tilix terminal** - Using the "Mono" variant
![Screenshot from 2021-03-21 23-13-30](https://user-images.githubusercontent.com/44622828/111944698-ddc36200-8a9d-11eb-9a45-35961194adb3.png)

**Tilix terminal** - After setting the non-Mono variant in GNOME Tweaks, wide spacing issue is resolved but icons and glyphs look bigger than "Mono" variant
![Screenshot from 2021-03-21 23-14-07](https://user-images.githubusercontent.com/44622828/111944808-119e8780-8a9e-11eb-97a2-580a6ae75546.png)

**kitty terminal** - Solved the issue after setting "adjust_column_width" to "-1" in kitty's config file. Using the "Mono" variant, icon's size is correct
![Screenshot from 2021-03-21 23-31-00](https://user-images.githubusercontent.com/44622828/111945028-8bcf0c00-8a9e-11eb-9bb3-77c8a5c3b8db.png)

**Comment by Finii** [comment]
Examined this after creating #830

In Roboto there are some 'special' glyphs that are 'wider than normal' in the original font.
These are for example `Eth` Ð , `Dcroat` ď and `ldot` ŀ.

The Nerd Font Mono variant takes the widest glyph and makes the font 'really monospaced', thus it needs to increase the 'normal' glyph's width.

We could exclude these specific glyphs, like in #830, but it is not so obvious if that is the right thing to do.

**Comment by Finii** [comment]
`Eth` and `Dcroat` have some negative bearing, but not enough to keep the width constant.

![image](https://user-images.githubusercontent.com/16012374/168443800-f0995b8f-3b45-49b5-8b21-a839128e5fb8.png)

I think this is a font specific quirk, they call themselves `mono` :roll_eyes:

**Comment by delinx** [comment]
Any updates on this? I really love the font, but it's unusable as is, could someone make a version with forced char width even if it breaks some characters? Sorry, I am a total noob about the process, just trying to get font working

**Comment by Finii** [comment]
Maybe we should add a font specific handling for the too-wide-chars, so that at least the release fonts are ok?

**Comment by Finii** [comment]
Fixed by #1062
