### ISSUE TITLE
Unable to patch Inconsolata variable font variant

### ISSUE THREAD

**Issue by moodyknurd** [ryanoasis/nerd-fonts#598]
#### 🎯 Subject of the issue

Experiencing a segfault when I attempt to patch a font. I get a series of `Bad device table` prompts, ending with a progress bar halt and a segfault.

#### 🔧 Your Setup

I am attempting to patch a variable `.ttf` font file of [Inconsolata](https://github.com/googlefonts/Inconsolata/releases/download/v3.000/Inconsolata-VF.ttf), through the Konsole terminal emulator on Fedora 33 with
```
./font-patcher -s -c location/to/font
```
It works fine for other non-variable fonts in my experience.

#### ★ Optional

![image](https://user-images.githubusercontent.com/15681865/112187022-110a0c00-8bd8-11eb-8520-0440050c1b8a.png)

**Comment by adrian5** [comment]
Unless things changed, I think variable fonts currently [aren't supported](https://github.com/ryanoasis/nerd-fonts/issues/512) due to fontforge downstream.

I'm not sure how the future of these projects looks, if someone else can/should pick up the slack eventually, maybe with a new framework.

**Comment by ryanoasis** [comment]
Interesting thanks

**Comment by Finii** [comment]
If one tries to patch a VF `font-patcher` issues a warning now. Usually it should patch the Regular weight then, but that is completely dependent on Fontforge.
