### ISSUE TITLE
Ligatures simply doesn't work

### ISSUE THREAD

**Issue by hrqmonteiro** [ryanoasis/nerd-fonts#599]
I am trying to set `VictorMono` in my kitty, and i want the ligatures to be working.

But the Nerd Fonts patched font simply doesn't have it.

If i set the regular VictorMono, as downloaded in their [website](https://rubjo.github.io/victor-mono/), it works fine:

![2021-03-24_21-45](https://user-images.githubusercontent.com/17055027/112402139-bad9bd80-8cea-11eb-8497-426341f8cc1a.png)

If i set VictorMono Nerd Font, it doesn't:

![2021-03-24_21-48](https://user-images.githubusercontent.com/17055027/112402271-faa0a500-8cea-11eb-9371-6a0fb9ffccb6.png)

**Comment by rrobertobt** [comment]
Are you sure you're setting them correctly? I tried setting them and ligatures are working for me, even on (neo)vim:

![Screenshot from 2021-03-30 21-51-43](https://user-images.githubusercontent.com/44622828/113088309-937b6880-91a2-11eb-858e-92c7851ff983.png)

![Screenshot from 2021-03-30 21-52-04](https://user-images.githubusercontent.com/44622828/113088315-95ddc280-91a2-11eb-9e0c-e02730e36135.png)

**Comment by carlosvigil** [comment]
@rrobertobt What is the correct setting then?
