### ISSUE TITLE
[Adobe Source Code Pro] Powerline Symbols not aligned.

### ISSUE THREAD

**Issue by beanaroo** [ryanoasis/nerd-fonts#60]
I believe this is due to the switch from Sauce Code Pro to Adobe Source Code Pro by issue #33.
I'm not sure if nerd fonts patches over the existing glyphs.
This could also be an upstream issue, as [shown here](https://github.com/adobe-fonts/source-code-pro/issues/43#issuecomment-93478072).

**Comment by ryanoasis** [comment]
It should not be patching over the powerline glyphs unless you run the patcher with the `--powerline` flag. 

I just checked the [script logic](https://github.com/ryanoasis/nerd-fonts/blob/master/gotta-patch-em-all-font-patcher!.sh#L65) that generates all the patched fonts and it should not be overriding the powerline symbols for Hack or Source Code Pro. However it is possible the conditional is not catching the proper case (I would need to run it and see).

**Comment by beanaroo** [comment]
The problem exists without patching the font, so I believe it could be upstream.

**Comment by ryanoasis** [comment]
Interesting thanks. I'll have to keep my eyes open for developments.

**Comment by ryanoasis** [comment]
Things have been looking pretty good for a while now on powerline glyph alignments and also yes Nerd Fonts does not by default patch over existing glyphs (there is even a specific config for powerline).

Here are some latest results of Sauce Code Pro at different sizes with v1.1.0:

### 13pt

![selection_014](https://user-images.githubusercontent.com/8083459/28990780-a5d92000-794e-11e7-968f-f461d2f8f02e.png)

### 9pt

![selection_015](https://user-images.githubusercontent.com/8083459/28990784-aac8b33c-794e-11e7-9f71-420768d02f92.png)

### 16pt

![selection_016](https://user-images.githubusercontent.com/8083459/28990786-aeac374e-794e-11e7-8592-765c4f702e28.png)

Closing for now. Thanks. :smile:
