### ISSUE TITLE
SauceCodePro shows smiley after some glyphs

### ISSUE THREAD

**Issue by pinpox** [ryanoasis/nerd-fonts#602]
#### 🎯 Source Code Pro (SauceCodePro) shows an extra smiley after some glyphs

The Source Code Pro font shows an extra smiley after some glyphs. E.g. this is what my shell prompt looks like:

![image](https://user-images.githubusercontent.com/1719781/113123578-00c7e180-9215-11eb-8318-7b81fb334de1.png)

This is a copy/paste of the actual text:
```
nixos on  main via ❄️  impure (shell)
➜
```
As you can see, there is an extra smiley shown after the NixOS logo (snowflake). I'm not sure where this comes from, but other fonts don't show it.

#### 🔧 Your Setup

- SauceCodePro Semibold
- Alacritty
- Linux (NixOS)

**Comment by rrobertobt** [comment]
I'm using Sauce Code Pro and tried 'echoing' your text and I don't get that 'smile' glyph you say, maybe you didn't chose the "Mono" variant of the font in your settings of your terminal?
![Screenshot from 2021-04-01 21-22-39](https://user-images.githubusercontent.com/44622828/113377069-7bd1ea80-9330-11eb-9031-ca439f54045e.png)

**Comment by pinpox** [comment]
@rrobertobt I have the Mono variant enabled, the crystal you are getting is colored though, letting me thing your fallback emoji font is a different one, maybe that overrides the <fe0f>  char which seems to be the emoji?

I tried the exact same echo command as you, it gives me the same result.

**Comment by rrobertobt** [comment]
Yup, I can still see the smile icon/glyph.
What prompt are you using? Is it 'starship' or something like that? Maybe it has something to with that, do you have a custom config file for your prompt? If yes you should check it

**Comment by pinpox** [comment]
I found the cause: It's a bug/incompatibility of alacritty, see: https://github.com/alacritty/alacritty/issues/4937#event-4547369617
