### ISSUE TITLE
Caskaydia Code Ligth and Extralight do not work with ConEmu

### ISSUE THREAD

**Issue by belotn** [ryanoasis/nerd-fonts#604]
#### 🎯 Subject of the issue

When i try to use Caskadya version Light ou Extralight, ConEmu do not seems to recognize the font and do not display in Fonts List Selection

#### 🔧 Your Setup

- Caskadya ligth 
- ConEmu
- Windows10

#### ★ Optional

![image](https://user-images.githubusercontent.com/3379936/113717241-b8fcfa80-96eb-11eb-86b9-1b81771c664f.png)

**Comment by Finii** [comment]
Sorry to notice your problem!

Unfortunately I can not see the version you used.
If I remember correctly we had (inherited) a bug in the Panose properties of Cascadia Code - that would affect all weights and not only Light and SemiLight :thinking:

Maybe try again with a more recent release?

**Comment by Finii** [comment]
Hmm, looking more closely at your screenshot. You use Cascadia Mono. Does ConEmu show Cascadia Code or only Cascadia Mono? Maybe you have to try CaskaydiaCove NFM instead of NF? :thinking:

**Comment by Finii** [comment]
I guess you need to install the `Nerd Font Mono` (`NFM`) variants.
And try with 3.0.0.
Reopen if still a problem :-)
