### ISSUE TITLE
Code New Roman's i, j and l shift to the right when bolded

### ISSUE THREAD

**Issue by Atemu** [ryanoasis/nerd-fonts#605]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

![image](https://user-images.githubusercontent.com/18599032/114276211-ee745180-9a25-11eb-9abb-f52b33d9cca9.png)
![image](https://user-images.githubusercontent.com/18599032/114276251-1b286900-9a26-11eb-9227-c2d85bd66dea.png)

(Notice the larger gap between the `a` and `l`)

#### 🔧 Your Setup

- Code New Roman Mono
- Emacs
- NixOS 21.05

**Comment by Finii** [comment]
Thanks for reporting. You are right:

![image](https://user-images.githubusercontent.com/16012374/220410647-a3006bcf-c0e3-4e39-87eb-fe5760ed2ab1.png)
_Bold as green outline_

But that is already the case with the original font:

![image](https://user-images.githubusercontent.com/16012374/220411281-1195c45b-57c0-4d7f-a11c-a5f49de5035d.png)

So this is how Code New Roman is intended to look, obviously.

**Comment by Finii** [comment]
(I would say that is a bug in the original font. Maybe we need to update, if there is a newer version.)

**Comment by Finii** [comment]
I guess there is no update.
The effect can also be seen here for example:

![image](https://user-images.githubusercontent.com/16012374/220412550-4335c904-74ab-4332-8461-fcd46d7cad67.png)
