### ISSUE TITLE
Update font-logos 

### ISSUE THREAD

**Issue by siduck76** [ryanoasis/nerd-fonts#606]
font-logos font (Formerly Font Linux),  must be updated , some new linux distro logos have been added in their font . Glpyhs for voidlinux , artix , archlabs , popos  etc are missing in nerdfonts . Those would be fixed if font-logos is updated
lukas-w/font-logos#59 (comment) .

**Comment by siduck76** [comment]
> font-logos font must be updated , some new linux distro logos have been added in their font  . Glpyhs for voidlinux , artix , archlabs , popos are missing in nerdfonts . Those would be fixed if font-logos is updated 
[lukas-w/font-logos#59 (comment)](https://github.com/lukas-w/font-logos/issues/59#issuecomment-816794965) .

**Comment by siduck76** [comment]
> font-logos  (Formerly Font Linux),   font must be updated , some new linux distro logos have been added in their font . Glpyhs for voidlinux , artix , archlabs , popos etc are missing in nerdfonts . Those would be fixed if font-logos is updated
> [lukas-w/font-logos#59](https://github.com/lukas-w/font-logos/issues/59) (comment) .

**Comment by ryanoasis** [comment]
Yep! Done, via #551 (pending a full rebuild TBD)

closing this, but thanks for the nudge.

**Comment by siduck76** [comment]
I use Jetbrainsmono Nerd font , how do I update them? are there any newer releases ? @ryanoasis

**Comment by siduck76** [comment]
> I use Jetbrainsmono Nerd font , how do I update them? I dont find them on the cheatsheet either! @ryanoasis

**Comment by ryanoasis** [comment]
@siduck76 Ah sorry to get your hopes up but fonts will need to be rebuild and the cheatsheet updated.

You can however now use the patcher to create a font with those glyphs.

**Comment by siduck76** [comment]
@ryanoasis that seems complex,  No worries I'll wait for the next release :)

**Comment by marcomeyerVFX** [comment]
any chance you could bump the font-logos version to 0.18 before the 2.2.0
