### ISSUE TITLE
Code New Roman doesn't have bold parens

### ISSUE THREAD

**Issue by Atemu** [ryanoasis/nerd-fonts#607]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

There doesn't seem to be a bold weight for Code New Roman's parens which makes Emacs fall back to a different font which does have one. This is problematic beause CNR's parens have a very distinct style and the change to a different font is a very significant jump. 

#### 🔧 Your Setup

- Code New Roman Mono
- Emacs
- NixOS 21.05

**Comment by Finii** [comment]
Hmm, but the bold weight does have parens?
They are not very bold, but ever so slightly more thick than regular.

![image](https://user-images.githubusercontent.com/16012374/208858008-d321bef8-24b8-4d67-86c9-0579693a48d9.png)

**Comment by Finii** [comment]
(Maybe you just do not have the bold version installed? If you have, can you give the version number?)

**Comment by Atemu** [comment]
I assumed it didn't have bold parens because they look *so* differently. The Code New Roman parens style is very distinct and the "bold" parens look nothing like the non-bold ones (other than also being parens).
