### ISSUE TITLE
Discord icon is replaced with Urdu / Arabic symbol

### ISSUE THREAD

**Issue by KSPAtlas** [ryanoasis/nerd-fonts#614]
#### The discord icon in Literation Mono Complete nerd font is replaced with a symbol.

I use Nerd fonts on DWM and I love it! However, the discord icon is replaced with a strange symbol as attached. ![screenshot](https://user-images.githubusercontent.com/72895702/116449567-37177180-a852-11eb-8fa5-5f43770a656c.png)
ur Setup
#### 🔧 Your setup
- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ Literation Mono Nerd Font Complete.ttf
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ st, but this is for DWM.
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Arch Linux

**Comment by TheGamingCoderNoob** [comment]
Funnily enough, It works on ST.

**Comment by iLuiizUHD** [comment]
For me too, I'm using FiraCode NF and it's an Arabic symbol. I think this is an issue with all fonts.

**Comment by JamesMowery** [comment]
Seeing this as well.

**Comment by ArthurHydr** [comment]
> For me too, I'm using FiraCode NF and it's an Arabic symbol. I think this is an issue with all fonts.

Switch to another font from the nerd-fonts group and it will work, some don't load on discord, I recommend "Source Code Pro". Hope this helps the next ones who look for the error.

**Comment by Finii** [comment]
Do you mean `U_FB6E`?

It certainly is in the font:
![image](https://user-images.githubusercontent.com/16012374/151927729-6b037f90-0911-4f7d-8fdf-ed1f539cd886.png)

Unfortunately the icon sits on a codepoint that is reserved for arabic glyphs.
Anyhow, if you select `Literation` as you main font it should use the glyphs embedded there. What you see looks like font fallback.

Are you sure you set the main font to `Literation`?

To help you we would need more details on what you use and how. I was never on Discord. Is there a terminal based client or something? What do I need to reproduce it, and which steps do I need to take for a from-scratch setup?

**Comment by Finii** [comment]
Ah, the suckless window manager... How do I set the font it shall use? :->

**Comment by Finii** [comment]
Hmm, more then 30 years ago I could work with this X11 stuff ;-)

I can't remember how the fontsel stuff worked, but if the information in the font file is honored, it is correct to NOT display the discord icon but search for some fallback font.

`FB6E` is in `Arabic Presentation Forms A`, which the font claims it does not contain (blue items are active):

![image](https://user-images.githubusercontent.com/16012374/151932869-c1301cc1-3336-4a94-90e1-98173c62c7ca.png)

I could prepare a font that has that set, if you are willing to try it out?
There is the possibility that fontconfig uses that information and then the behavior you see is justified.
The change afterwards would be trivial.

**Comment by Finii** [comment]
Release is in repo, release as packages pending.
