### ISSUE TITLE
Support for Academicons

### ISSUE THREAD

**Issue by shervinsahba** [ryanoasis/nerd-fonts#616]
#### 🎯 Subject of the issue

[Academicons](https://jpswalsh.github.io/academicons/) provides the nerdiest glyphs out there. It was built by [jpswalsh](https://github.com/jpswalsh/academicons/issues) to supplement Font Awesome 5. I haven't Academicons mentioned in issues, nor have I seen support for several of these glyphs. It'd be really useful for those of us who use services like those below. Thanks!

#### 🔧 Your Setup

Fira Code Nerd Font Complete in the Kitty terminal emulator on Manjaro Linux 5.4.

#### ★ Optional

![sample of academicons](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcssauthor.com%2Fwp-content%2Fuploads%2F2014%2F06%2FAcademicons.jpg&f=1&nofb=1)

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
