### ISSUE TITLE
Wondering if the fonts included are free to use for personal use.

### ISSUE THREAD

**Issue by apoorv569** [ryanoasis/nerd-fonts#617]
I'm making a application, and a website, and I want to use the `Heavy Data` font from this collection, but was wondering if the license allows to do so, do I need to attribute the creator? If so where can I find the creator or licensing information about the particular font?

**Comment by ryanoasis** [comment]
Hey. You should be good but here is more info:

* https://www.fontsquirrel.com/license/Heavy-Data
* https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/HeavyData/complete
