### ISSUE TITLE
Add Codocons' glyphs

### ISSUE THREAD

**Issue by Mayrixon** [ryanoasis/nerd-fonts#620]
Microsoft provides [vscode-codicons](https://github.com/microsoft/vscode-codicons) under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) lisence. The famous text editor VS Code is also using this font as LSP hint glyphs.

Is it possible to add codicons' glyphs into nerd-fonts?

**Comment by cstrahan** [comment]
FWIW, looks like some of the work involved has been done here: https://github.com/ram02z/nerd-fonts-patcher
