### ISSUE TITLE
Any way to reduce the size of a repo clone?

### ISSUE THREAD

**Issue by paddor** [ryanoasis/nerd-fonts#621]
#### 🎯 Subject of the issue

The checked out repo is huge, even with `git clone --depth 1`. I just learned this the hard way when VimPlug tried to update this repo using `--depth 1 --no-single-branch`. I managed to update manually using `--no-single-branch`, but it still takes a lot of space.

Since you have a branch for every patch version (why?), maybe you could create a branch for each font?

#### 🔧 Your Setup

- Hack Nerd Font Mono
- iTerm2
- Ubuntu 20.04 VM inside macOS

**Comment by paddor** [comment]
Ignore this. It seems that this repo isn't even needed.

**Comment by joeytwiddle** [comment]
I wonder if this new git new "sparse index" feature may help, for those who want a small clone of the repo:

https://github.blog/2021-11-10-make-your-monorepo-feel-small-with-gits-sparse-index/
