### ISSUE TITLE
The glyphs of CascadiaCode are slightly above the centerline.

### ISSUE THREAD

**Issue by myy1966** [ryanoasis/nerd-fonts#623]
#### 🔧 Your Setup

- _Font: All Caskaydia Cove Regular Nerd Font_
- _Terminal emulator: Windows Terminal, buildin terminal of VSCode_
- _OS: Windows 10 20H2_

#### ★ Optional

CaskaydiaCove NF in Windows Terminal, the glyphs are slightly above the centerline.
![wt_cc](https://user-images.githubusercontent.com/10590090/117541351-11564d80-b046-11eb-997a-8dd13a73f277.png)

MesloLGS NF in Windows Terminal, the glyphs are on the centerline.
![wt_m](https://user-images.githubusercontent.com/10590090/117541355-17e4c500-b046-11eb-902f-ab5e263e3e54.png)

**Comment by ryanoasis** [comment]
There have been some updates to the patcher. if you are able to, could you try repatching yourselves? If not i'll follow up with changes in the release candidate 2.2

**Comment by myy1966** [comment]
I have tried, the CLI command I used is 
`fontforge -script font-patcher CascadiaMono-Regular.otf -c`.
The version of CascadiaMono is 2110.31.

The result is shown in the image:
![cascadia](https://user-images.githubusercontent.com/10590090/145699375-f9dc3b3a-53cb-48d3-9f4c-fa84c931651f.PNG)
It looks like the powerline symbols are correct. However, the windows icon and the python icon are slightly below the centerline. And compared to the original "CaskaydiaMono Nerd Font", the windows icon and python icon are slightly smaller. The image below uses the original version:
![cascadia_1](https://user-images.githubusercontent.com/10590090/145699474-e944f2c8-6aad-4c93-8d1e-b59a5d03f900.PNG)

Now I am using another font, "MesloLGS NF". It is perfect under Windows:
![cascadia_2](https://user-images.githubusercontent.com/10590090/145699549-813f802c-3357-4096-99fe-1547ee90a6c8.PNG)
Have you had any idea why MesloLGS is so different from CascadiaMono?

**Comment by Finii** [comment]
The icons look smaller, because it looks like a 'Nerd Font Mono' version (i.e. _Caskaydia Mono Nerd Font Mono_), where all glyphs are just 'one space' wide. In the 'original' version the icons are allowed to occupy up to 'two spaces':

![image](https://user-images.githubusercontent.com/16012374/145709764-a8c9fb86-a40e-4193-815a-b2839e028eec.png)

I will have a look.

**Comment by Finii** [comment]
Can not reproduce.
```
$ fontforge font-patcher ~/Downloads/CascadiaCode-2110.31/otf/static/CascadiaMono-Regular.otf -c
$ fontforge Caskaydia\ Mono\ Regular\ Nerd\ Font\ Complete.otf
```
Windows icon u_F17A is wider than 'normal' (1902 vs 1200):
![image](https://user-images.githubusercontent.com/16012374/145710298-2653ea2b-db7f-4dcf-8a2d-bf0d7ac377ad.png)

Maybe you can copy and paste your text into a comment, so that I can see which codepoints you use exactly.

Can of course be a Windows problem. Can you reproduce it with something more common (not VScode) that I might have already on my Windows box?

Alternatively you could check the font yourself by opening the font in `fontforge` (there is a Windows executable available).

I guess there is some font substitution and/or installation problem on your machine ;-)

(At first I thought you forgot the `--complete` ... because it is the last option you give (I usually give it as first argument - not that it matters. BUT maybe you first patched it without `--complete`, installed it, repatched it and reinstalled it - often it will not work because of the font handling blah of Windows)

**Comment by myy1966** [comment]
When patching the font, I haven't added the "-s" flag, and the patcher generates the glyphs as double-width.
I found that it has something to do with what terminal emulator is used. In the previous comment, I was using the windows terminal. However, when I change to the Tabby, the windows icon and the python icon are rendered normally:
![cascadia_3](https://user-images.githubusercontent.com/10590090/145704965-c110df76-5125-4c28-bb88-1879b1345272.PNG)
But with the Tabby, a vertical line appears in the triangle symbol of the powerline symbols.

**Comment by Finii** [comment]
If you are willing, can you try if the vertical lines are still there on Tabby when you also give `--careful`?

**Comment by Finii** [comment]
something along the lines of
```
$ fontforge font-patcher ~/Downloads/CascadiaCode-2110.31/otf/static/CascadiaMonoPL-Regular.otf -c --careful
```
(i.e. give `--careful` and use a `Cascadia PL` variant. The result is that you do not use 'our' powerline triangular thing, but Cascadia's original powerline triangular thing.)

**Comment by myy1966** [comment]
The vertical line seems to be a common problem. Many terminal emulators under Linux, such as Konsole, Gnome Terminal, and Alacritty, will render vertical lines. The only one I found under Linux that does not render vertical lines is Kitty.

**Comment by Finii** [comment]
Hmm, you seem to be right ;) I never noticed them, but I have them on the left one (not on the right):
![image](https://user-images.githubusercontent.com/16012374/145710974-05d85c99-d485-4cde-8c17-5e9c9cfc978f.png)

My font is `--careful` with the Cascadia Code PL symbols...

**Comment by myy1966** [comment]
> something along the lines of
> 
> ```
> $ fontforge font-patcher ~/Downloads/CascadiaCode-2110.31/otf/static/CascadiaMonoPL-Regular.otf -c --careful
> ```
> 
> (i.e. give `--careful` and use a `Cascadia PL` variant. The result is that you do not use 'our' powerline triangular thing, but Cascadia's original powerline triangular thing.)

Tabby will render vertical lines when using the original Cascadia Mono PL font. This should not be a problem with nerd-fonts, but a problem with the way tabby renders the font.

**Comment by Finii** [comment]
I use Tilix btw.

Well, I guess the vertical lines are very hard to get right and/or depend on the terminals or font rendiering engine and how good the rounding (of glyph points) is in each.

I do not know what to do now, shall I try something on Windows regarding your too small icons? I have Visual Studio installed, which is maybe similar to VS Code? Or do you mean that? I never used that for work. If I should try something there I would need a hint what I need to click ;-)

**Comment by myy1966** [comment]
> I use Tilix btw.
> 
> Well, I guess the vertical lines are very hard to get right and/or depend on the terminals or font rendiering engine and how good the rounding (of glyph points) is in each.
> 
> I do not know what to do now, shall I try something on Windows regarding your too small icons? I have Visual Studio installed, which is maybe similar to VS Code? Or do you mean that? I never used that for work. If I should try something there I would need a hint what I need to click ;-)

Thanks！I have already tried it on the Visual Studio 2019 and the Cmder, it seems they render the double-width icon currently. I think this is a problem with the Windows Terminal, I should go to the GitHub repo of the Windows Terminal to raise a new issue.

Visual Studio 2019:
![cascadia_4](https://user-images.githubusercontent.com/10590090/145712383-cdfe45ca-fab2-4a0f-8dde-bcbe8ea853fd.PNG)
Cmder:
![cascadia_5](https://user-images.githubusercontent.com/10590090/145712393-42c40589-46aa-4773-9795-84ced6fd6e6a.PNG)

**Comment by Finii** [comment]
Windows terminal ... I remember on that one had to set the Panose stuff (which font-patcher does not) ... ponder

**Comment by Finii** [comment]
Ah, or maybe Terminal was the thing that allows only strictly monospaced fonts (i.e. one space for one glyph). Where is the Panose commit ;-) need to read my comments

**Comment by myy1966** [comment]
> Ah, or maybe Terminal was the thing that allows only strictly monospaced fonts (i.e. one space for one glyph). Where is the Panose commit ;-) need to read my comments

I think the Windows Terminal can support double-width glyphs. Now I use "MesloLGS NF" with the Windows Terminal, and all glyphs are rendered correctly.

**Comment by Finii** [comment]
Ah this is another case of https://github.com/ryanoasis/nerd-fonts/issues/731#issuecomment-1003071050

Need to open a proper Issue number and or PR.

**Comment by Finii** [comment]
Ah this is another case of https://github.com/ryanoasis/nerd-fonts/issues/731#issuecomment-1003071050

Need to open a proper Issue number and or PR.

**Comment by Jaykul** [comment]
I was having a problem with the block characters (0x2588..0x258f) of CaskadiaCove NF being center-aligned, and this evening I downloaded the [2.2.0-RC](https://github.com/ryanoasis/nerd-fonts/releases/tag/2.2.0-RC) CascadiaCode.zip and replaced my font with those .otf versions ...

The block characters are right, but the PowerLine characters there are a _total mess_...

Not only are many of them too high, all the extended ones are ... shrunken:
![image](https://user-images.githubusercontent.com/192942/167994135-2c7f4db8-b3c2-4a90-96d2-d2f8ff2f521b.png)

I tried the mono version, and it's stretching the extend characters, but still putting them all too high and cutting off the tops:
![image](https://user-images.githubusercontent.com/192942/167994443-db1f6929-02a1-46d2-b3e8-d00e9ece2008.png)

**Comment by Finii** [comment]
@Jaykul This looks bad. What is your terminal?

I must say I have forgotten about this issue. But maybe you can try the hidden "2.2.0-RC", which is here, instead. A lot of fixes go into that. https://github.com/Finii/nerd-fonts/tree/feature/cascadia-2111.01-patched/patched-fonts/CascadiaCode

**Comment by Jaykul** [comment]
*that* one looks a lot better, @Finii solves both my problems with the previous 2.1 and the previous RC

**Comment by Finii** [comment]
Good to hear :sweat_smile: Thank you.
Hopefully @ryanoasis will merge #723 into the RC, before it is released.
