### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by rpearce** [ryanoasis/nerd-fonts#627]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

Hi there and thank you for nerdfonts! It looks like the Latest release was `v2.1.0` from `2020-02-02`; as it seems there have been a bit of changes since then (like `Lilex` being included, I think?), would it make sense to cut a new release? [Nixpkgs relies on the latest release](https://github.com/NixOS/nixpkgs/blob/acb51e6ca3b5b6f491a34fadd2232b3745f8eb20/pkgs/data/fonts/nerdfonts/update.sh#L4), and Lilex, for example, isn't available in `nixpkgs`, for I don't believe it's included in the last release.

#### 🔧 Your Setup

_Not relevant, but I'm on macOS 10.15.7._

**Comment by saumyajyoti** [comment]
Need to update patched font for Iosevka with latest Iosevka release, with curly and extended variant.

**Comment by ryanoasis** [comment]
This is being actively worked on now. There is a release candidate for `v2.2.0` with limited subset of fonts. The goal is to drive this by github actions workflow and I think that's getting pretty close.

Future releases should be much more frequent.

**Comment by rpearce** [comment]
Thanks a lot, @ryanoasis! We appreciate you.

**Comment by rami3l** [comment]
@rpearce 
A gentle ping :)

**Comment by rpearce** [comment]
@rami3l it's not me that needs pinging; I just opened the issue!

**Comment by rpearce** [comment]
Looks like this is recently handled. Thanks, @ryanoasis
