### ISSUE TITLE
Cascadia received italics, please add to Caskaydia

### ISSUE THREAD

**Issue by ruffson** [ryanoasis/nerd-fonts#628]
#### 🎯 Subject of the issue

Cascadia just received italics [2 days ago](https://github.com/microsoft/cascadia-code/commit/82b5b9b2b8a45a7cec959c5016d4a07b6f23184e). It would be nice if Caskaydia Cove could get those as well.

#### 🔧 Your Setup

- _Caskaydia Cove_
- _kitty_
- _Fedora 34_

**Comment by trallnag** [comment]
Use the following: https://github.com/adam7/delugia-code

It is patched Cascadia Code and up to date

**Comment by Finii** [comment]
Would be solved by #723
