### ISSUE TITLE
Bold font "Hack" doesn't have all Powerline symbols.

### ISSUE THREAD

**Issue by chevysniff** [ryanoasis/nerd-fonts#63]
Hello,
  I'm using bold fonts as my regular font weight in terminal.  I wanted to use available prepatched fonts, but I found that bold version fonts doesn't have all powerline symbols. Missing are: e0a0-e0a3 and e0b0-e0b3. 
Pics related:
![2016-03-12-213953_954x1057_scrot](https://cloud.githubusercontent.com/assets/4434640/13725221/899695ca-e89b-11e5-8916-8a9d3a1f2da6.png)
![2016-03-12-214021_950x1050_scrot](https://cloud.githubusercontent.com/assets/4434640/13725222/8996ee08-e89b-11e5-98eb-5614a9fd9e8a.png)

**Comment by ryanoasis** [comment]
I see. Thanks for the report. I will look into this. :+1:

**Comment by ryanoasis** [comment]
Turns out this is an issue with Hack itself which has since been fixed in 2.020 (see: https://github.com/chrissimpkins/Hack/issues/181#issuecomment-214938967) version but we are using 2.019
