### ISSUE TITLE
Patcher does not check for illegal characters in output filename

### ISSUE THREAD

**Issue by nobuyukinyuu** [ryanoasis/nerd-fonts#632]
#### 🎯 Subject of the issue

As stated in title.  Fonts which have fullnames containing characters illegal to the filesystem are not accounted for, and will cause the patcher to fail when producing final output.  This could be worked around with an output file flag, or code to substitute illegal characters before final output.

#### 🔧 Your Setup

- _Which font are you using ?_
int10h -- *Px437 DOS/V re. JPN16*  (`Px437_DOS-V_re_JPN16.ttf`)

- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
Windows Terminal 1.8
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_  
  Windows 10.  The issue most likely exists (with slight variants in allowed characters) for all systems.

**Comment by Finii** [comment]
The font names should (imho) change to be the postscript names of that fonts (see #722).
That would solve your issue en passant.

Unfortunately changing the font file name will probably upset people ;)

But you are right and I should create a proper PR and not only a discussion.

**Comment by Finii** [comment]
Ah, this would be not enough...

```python
    @staticmethod   
    def postscript_char_filter(name):
        """Filter out characters that are not allowed in Postscript names"""
        # The name string must be restricted to the printable ASCII subset, codes 33 to 126,
        # except for the 10 characters '[', ']', '(', ')', '{', '}', '<', '>', '/', '%'
        out = ""
        for c in name:
            if c in '[](){}<>/%' or ord(c) < 33 or ord(c) > 126:
                continue
            out += c
        return out
```

I will add this Issue to the discussion.
