### ISSUE TITLE
Create RPM to install with

### ISSUE THREAD

**Issue by kurczynski** [ryanoasis/nerd-fonts#636]
#### Create RPM to install with

This would make it easier to install and maintain Nerd Fonts installations for RHEL-based systems.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ Nerd Fonts Complete
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ `gnome`
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ GNU/Linux: Fedora

**Comment by ryanoasis** [comment]
great suggestion. just don't have capacity for this right now

**Comment by Finii** [comment]
While it is not at all hard to create the package, I have no clue how to get that into some package repository.
Same goes for `deb` packages.

We could in principle put the packages just here to download, as release artefacts; but will that help?
If you can install a self-downloaded package you can probably also just download the `zip` and throw the contents in a folder.

Other package types like Nix or Arch also have 3rd party package maintainers, and I guess that is the way to go.

I'll close this now, but feel free to reopen if you think a standalone package file would make sense.
