### ISSUE TITLE
Characters from the range U+F900 to U+FAFF are displayed with a width of two

### ISSUE THREAD

**Issue by ariasuni** [ryanoasis/nerd-fonts#637]
#### 🎯 Subject of the issue

[ogham/exa](https://github.com/ogham/exa) can display icons using Nerd Fonts codepoints. However, it seems that some icons are displayed with one character more than expected, like U+FABF, and there’s no way, as far as I know, to accurately find out which size it is to workaround this problem.

#### 🔧 Your Setup

- Hack Nerd Font Mono.tff 2.1.0 and Hack Regular Nerd Font Complete.ttf 2.1.0
- Konsole, Kitty
- Ubuntu 20.04, Arch Linux

#### ★ Screenshots

![Screenshot_20210627_234208](https://user-images.githubusercontent.com/2446451/123560340-dd73ea80-d7a1-11eb-92a0-26acaef4c214.png) ![Screenshot_20210627_234232](https://user-images.githubusercontent.com/2446451/123560342-de0c8100-d7a1-11eb-9f4d-7cdc5d5d366f.png)

**Comment by izhakjakov** [comment]
### Same thing happens to me on MacOS using iTerm
![image](https://user-images.githubusercontent.com/18270061/140318431-20d641ef-6c8a-4dcc-b9e7-349aa1ab4a9d.png)

**Comment by eliminmax** [comment]
Ran into the same issue on gnome-terminal and kitty

**kitty:**
![kitty-nf](https://user-images.githubusercontent.com/33302691/144477304-50d5e467-d5bf-4cdb-858a-3deca98aa04e.png)

**gnome-terminal:**
![gnome-terminal-nf](https://user-images.githubusercontent.com/33302691/144477375-51f095b9-dcb2-44b7-9a8a-cbb436e2de5b.png)

**Comment by xsrvmy** [comment]
The U+F900 to U+FAFF range is used for CJK characters actually, so the terminal is expected double width characters there.

**Comment by Finii** [comment]
Just [stumbled](https://github.com/ryanoasis/nerd-fonts/issues/731#issuecomment-1002929396) over this in [**Windows Terminal** code:](https://github.com/microsoft/terminal/blob/main/src/types/CodepointWidthDetector.cpp)
```c++
        UnicodeRange{ 0xe000, 0xf8ff, CodepointWidth::Ambiguous },
        UnicodeRange{ 0xf900, 0xfaff, CodepointWidth::Wide },
```
The font (i.e. Nerd Font) has no influence on rendering if the terminal overrides our info.

**Comment by ariasuni** [comment]
I feel like Nerd Fonts should avoid this Unicode range if a lot of terminal have problem with it, to be honest, but I’m not sure how practical or feasible it is.

**Comment by tywtyw2002** [comment]
I suggest we should skip the range `F900` - `FAFF`. 

This range is design for CJK, and lots of programs hard code `CJK` features in this range.

Also, this is a problem for CJK users.

For example,
- Icons display as Chinese without use nerd fonts.
<img width="887" alt="Screen Shot 2022-03-02 at 18 05 46 " src="https://user-images.githubusercontent.com/576954/156476538-b55e0083-66d1-49af-9caa-bc1326fb92b8.png">

**Comment by Finii** [comment]
@tywtyw2002 see #574 and finally #716

**Comment by DHowett** [comment]
> The font (i.e. Nerd Font) has no influence on rendering if the terminal overrides our info.

In general--because there is no guarantee that a terminal-based application is even running on the same host as the terminal emulator--you cannot rely on the font to tell you how big a glyph is supposed to be. An application trying to simply print text would need to know what font is set (and perhaps even load it up and parse it, when it may not even exist on that system) to accurately determine how to do so. Terminals *must* therefore override all font info based on a standard that font authors and terminal emulator authors agree upon. :smile:

**Comment by Finii** [comment]
Glyphs finally dropped with v3.0.0
