### ISSUE TITLE
provide postmarketOS icon

### ISSUE THREAD

**Issue by JuniorJPDJ** [ryanoasis/nerd-fonts#638]
ATM there's no PMOS icon here.

**Comment by ryanoasis** [comment]
Hey, thanks for the suggeston. Similar to #660 I believe this is better to be done in font-logos.

see my comment https://github.com/ryanoasis/nerd-fonts/issues/660#issuecomment-993668545

For now let's keep this open

**Comment by Finii** [comment]
As Ryan already pointed out, distro logos should be added to font logos and then we get the logos from them.
Please raise an issue / create a PR over there, thank you.

https://github.com/lukas-w/font-logos
