### ISSUE TITLE
A request 

### ISSUE THREAD

**Issue by Photonico** [ryanoasis/nerd-fonts#639]
My font production Fira Comp(forked from FiraCode) does not have icons.
Could you merge my font to Nerd Fonts?

Fira Comp: https://github.com/Photonico/Fira_Comp

**Comment by ChiefMikeK** [comment]
Have you tried patching it yourself?   
> https://github.com/ryanoasis/nerd-fonts#font-patcher

**Comment by Photonico** [comment]
> Have you tried patching it yourself?
> 
> > https://github.com/ryanoasis/nerd-fonts#font-patcher

Thank you, but I have no experience on that. I also hope that author could add my font and show it on nerd-fonts website.

**Comment by ryanoasis** [comment]
What are the distinguishing features from FiraCode?

**Comment by Photonico** [comment]
> What are the distinguishing features from FiraCode?

Hi, I developed it from FiraCode, I maintain all its features, and I personalized some characters.
For example: "Q"
![image](https://user-images.githubusercontent.com/17745311/148105596-687fc7c7-75b2-4332-9f83-507f79f7e469.png)
and other characters.

However, I don't have the time, energy, and ability to develop it. I earnestly hope you can merge my font and develop it in the future.

Sincerely,
Lu
