### ISSUE TITLE
Extra spacing after installing patched Hack font

### ISSUE THREAD

**Issue by benedu** [ryanoasis/nerd-fonts#64]
Hi,

I don't know if I am doing something wrong, but after installation of the patched Hack font my terminal is looking wired. It seems that there is some extra spacing when the cursor is over a character. Please see my attached screenshots.

![footer1](https://cloud.githubusercontent.com/assets/14878247/13729998/941324c6-e942-11e5-86d9-cdfe93837fb0.png)

Please note that I am not added any extra whitespace after the slash.

**My setup:**
OS: Kubuntu 15.10
Font: Hack
Fontsize: 8pt

**Comment by ryanoasis** [comment]
Thanks for the report :+1: 

I will look into this when I can :blush:

**Comment by benedu** [comment]
I should have installed the Mono version of Hack. Problem solved :)

Sorry :S

**Comment by ryanoasis** [comment]
Ah that makes sense thanks :smile:
