### ISSUE TITLE
Nerd Fonts not working in urxvt terminal

### ISSUE THREAD

**Issue by 3301n** [ryanoasis/nerd-fonts#640]
#### 🎯 Subject of the issue
No glyphs have been displayed correctly instead a box is shown even though i have set a nerd font in my .Xresources. Iam using urxvt terminal with iosevka nerd font installed into .fonts.

I tried to run echo $'\ue62b' in my terminal and a box is being displayed. I have configured my urxvt with a nerd font still not working. I even tried Firacode nerd font but still the same. Glyphs not being displayed.
#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_Iosevka Nerd Font:style=Regular
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_urxvt
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_Kali Linux, Debian 

#### ★ Optional

![github_2](https://user-images.githubusercontent.com/69240615/124962967-df109e80-e03c-11eb-8618-bff53a7e5dfe.png)

**Comment by kierun** [comment]
![screenshot](https://user-images.githubusercontent.com/3079575/125265014-52940380-e2fc-11eb-82d5-b094aacaac0b.png)

This is what you need in `~/.Xdefaults`:

```
urxvt256c-ml*font: xft: PragmataPro Nerd Font Mono:style=Regular:pixelsize=19:antialias=true:autohint=true
```

It is possible that `urxvt` and `urxvt256c-ml` are different enough that the above only works on the latter.

**Comment by 3301n** [comment]
URxvt supports nerd fonts which end with mono only. So i figured that i should should download mono nerd fonts and it worked.
