### ISSUE TITLE
Problem with VictorMono in VSCode with ligatures enabled.

### ISSUE THREAD

**Issue by tefloon** [ryanoasis/nerd-fonts#643]
#### 🎯 Subject of the issue
The issue is similar but not identical to #415 and #494
For some reason, the ligatures in italics don't work properly in VSCode. They seem to be shifted to the right by one space, overlapping the next character: 
![NormalLigatures](https://user-images.githubusercontent.com/14832278/126724278-fea3f821-5dc1-4164-aee9-2f703ba10120.png)

What's even stranger, when the ligatures are turned on in VSCode settings (`"editor.fontLigatures": true`), a bunch of ligatures  appear that shouldn't exist. As far as I could tell they mostly involve "a", "e" and "l" (lowercase L) creating complexes with all lower-case letters. This results in a complete gibberish in certain places: 
![WithLigaturesOn](https://user-images.githubusercontent.com/14832278/126724672-4f5a5b86-e905-4bc3-a896-6c951fcaafaa.png)

Turning off the ligatures in the settings (`"editor.fontLigatures": false`) causes these to go away:
![WithLigaturesOff](https://user-images.githubusercontent.com/14832278/126724677-3ae27c86-cc1f-444f-bb19-197f3e1941c9.png)

Below are some more examples I created to try and work out what's happening. I also made a screenshot of the lines selected so that it's possible to see spaces and other unprintable characters. **Note**: there is always just one space between the slashes and the word.
![VS_examples (Zmienione)](https://user-images.githubusercontent.com/14832278/126724360-23442d0f-5be6-44ab-b427-f3b836388494.png)![VS_examples_selected (Zmienione)](https://user-images.githubusercontent.com/14832278/126724362-d16b7d3d-565a-4c13-9755-9f4b28712022.png)

Sublime Text 3 with the same settings on the same system works perfectly without any weird behaviour:
![ST_examples (Zmienione)](https://user-images.githubusercontent.com/14832278/126724395-d1787918-625f-4ea5-a34f-6d762a23470b.png)![ST_examples_selected (Zmienione)](https://user-images.githubusercontent.com/14832278/126724399-e9cff8cb-3217-4722-81ff-a82896b51820.png)

#### 🔧 Your Setup

- Font: **VictorMono Nerd Font Mono** (downloaded as is from the NF website)
- System: **Windows 10 Pro**, Version 21H1, build 19043.1110
- Editor: **Visual Studio Code**, Version: 1.58.2
   - Commit: c3f126316369cd610563c75b1b1725e0679adfb3
   - Date: 2021-07-14T22:10:15.214Z
   - Electron: 12.0.13
   - Chrome: 89.0.4389.128
   - Node.js: 14.16.0
   - V8: 8.9.255.25-electron.0
   - OS: Windows_NT x64 10.0.19043

**Comment by laundmo** [comment]
im experiencing the same issue. the issue does not exist with the base Victor Mono

**Comment by eltariel** [comment]
This isn't just in vscode...

I had initially installed all of the "windows compatible" variants and I was seeing the same issue in a couple of other apps on Windows10 (neovide and nvui in particular). I didn't actually attempt to run either of these with ligature support disabled.

I removed all of the font files and then reinstalled just the non-mono subset (i.e. `Victor Mono X Windows Compatible.ttf` and not `Victor Mono X Mono Windows Compatible.ttf`) and the issue has gone away.

**Comment by Finii** [comment]
Installed 
```
patched-fonts/VictorMono/Regular/complete/Victor Mono Regular Nerd Font Complete Mono Windows Compatible.ttf
patched-fonts/VictorMono/Italic/complete/Victor Mono Italic Nerd Font Complete Mono Windows Compatible.ttf
```
In writer the ligatures break when italic is turned on:

![image](https://user-images.githubusercontent.com/16012374/147853978-494548da-c917-42fe-8ee4-19ad65657768.png)

I have seen something similar already :thinking:

**Comment by Finii** [comment]
I suspect either a2f0958ae or d307a7335

lets see if that fixes this.

**Comment by Finii** [comment]
Unfortunately not. It's already visible on Linux just in the font opener :unamused: 

![image](https://user-images.githubusercontent.com/16012374/147854443-a74958e4-2174-4845-9960-10358e20dd6e.png)

Otoh, that will make it more easy to find the reason :+1:

**Comment by AlexPoulsen** [comment]
i get the same issue on macos, well just in the quicklook preview, haven't gone past that point yet. just mono versions and windows compatible doesn't affect it.

just these files, and their ... Windows Compatible versions, are affected for me:
```
Victor Mono ExtraLight Italic Nerd Font Complete Mono.ttf
Victor Mono Italic Nerd Font Complete Mono.ttf
Victor Mono Light Italic Nerd Font Complete Mono.ttf
Victor Mono Medium Italic Nerd Font Complete Mono.ttf
Victor Mono Thin Italic Nerd Font Complete Mono.ttf
```

**Comment by Finii** [comment]
Can not reproduce with `v3.0.0` anymore.

![image](https://user-images.githubusercontent.com/16012374/235899931-c11bcd30-fc46-4e64-bc19-7683a4c9a885.png)

**Comment by dbGIS** [comment]
It appears to be fine for VictorMonoNerdFont-*.ttf but not for VictorMonoNerdFontMono-*.ttf

VictorMonoNerdFont-Regular
![VictorMonoNF](https://github.com/ryanoasis/nerd-fonts/assets/10089074/6221e2b9-6f0e-4cdd-bbce-6f6cbad97e55)

VictorMonoNerdFontMono-Regular
![VictorMonoNFM](https://github.com/ryanoasis/nerd-fonts/assets/10089074/503682c0-1b06-4123-aefd-50c4a03cb298)
