### ISSUE TITLE
Please patch Cascadia Code italic fonts to Fira Code since it does not have any italics.

### ISSUE THREAD

**Issue by lakshits11** [ryanoasis/nerd-fonts#645]
### Issue:
Fira Code does not have italic fonts, where cascadia code have. So please provide a patch for firacode so that it can have italic fonts of cascadia code and regular font of itself as usual. Hope you understood the problem.

#### 🔧 Your Setup

- _Which font are you using -  `FiraCode Nerd Font Complete.ttf`_
- _Which terminal emulator are you using - `Powershell`_
- _Are you using OS X, Linux or Windows? - `Windows 10`_

**Comment by maxxnino** [comment]
Yes, I want that too

**Comment by trallnag** [comment]
Use the following: https://github.com/adam7/delugia-code

It is patched Cascadia Code and up to date

**Comment by maxxnino** [comment]
@trallnag thank you

**Comment by lakshits11** [comment]
No, you didn't understood the question I think. I am saying that patch
italic fonts pf cascadia code to fira code. So that fira code will also
have italic fonts.
Thanks.

**Comment by Finii** [comment]
Well, that would mix to different fonts. That is a very special request and I believe it is not generally useful.
I can help you do that yourselves, but this is not a general 'output' of Nerd Fonts.
