### ISSUE TITLE
FuraCode, three dots are displayed as a space, a question mark and a dot

### ISSUE THREAD

**Issue by Sean-214** [ryanoasis/nerd-fonts#646]
#### 🎯 Subject of the issue

Using the FuraCode font, three dots are displayed as a space, a question mark and a dot

#### 🔧 Your Setup

- Fura Code Retina Nerd Font Complete Mono Windows Compatible.ttf
- Windows Terminal（PowerShell 7），VS Code
- Windows 10

#### ★ Optional

input: `echo ...`

![echo](https://user-images.githubusercontent.com/10695861/127606306-65098bbc-aee0-4691-aebe-6ba2ced10df1.png)

![image](https://user-images.githubusercontent.com/10695861/127606493-72c10af5-de2b-4721-a53e-03fac943ed51.png)

**Comment by Finii** [comment]
Thanks for the bug report. Sorry to hear you have a problem.

That is most likely a broken ligature-removal. Some have been fixed meanwhile.

Have some problems recreating the Issue:
There is no `Fura Code Retina Nerd Font Complete Mono Windows Compatible.ttf` in `HEAD`.
There is no such file in any `Release v2.2.2` archives.

Only `Fira Code Retina Nerd Font *` and some `Fura Mono Nerd Font *` (no _Retina_).

Please specify font version and/or where you downloaded it.

As I guess that has already been fixes, closing. Reopen if problem persisting with `v2.2.2`.
