### ISSUE TITLE
update fira code to latest

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [ryanoasis/nerd-fonts#649]
#### Add Ligatures to Fira Code

Some of the ligatures offered in the original [Fira Code](https://github.com/tonsky/FiraCode) are not included in the Nerd Font version, including but not limited to:
- infinites (`--------` and `==========`)
- arrows (`|=====|`, `==>>`, etc.)

Edit: this also applies to other fonts, such as JetBrains Mono and Caskaydia Cove (NF version of Cascadia Code)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
`Fira Code Regular Nerd Font Complete Windows Compatible`
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
`Windows Terminal`
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
`Ubuntu 20.04` on `Windows Terminal`

#### ★ Comparison Screenshots

**Original**
![image](https://user-images.githubusercontent.com/79387351/128629310-5e4e65c1-e516-47b0-8795-59464c5c74ee.png)

**Nerd Font**
![image](https://user-images.githubusercontent.com/79387351/128629324-5a652edb-72a6-4ac1-bcfa-46a4bbdb32f8.png)

**Comment by awilkins** [comment]
Fira Code has now (April 2020) disabled the horrible traditional ligatures like Fl since version 3.0 ; current release is 5.2, Nerd Font version is back at version 2.

Arrows got a major overhaul in version 4 and this may be the basis of your issue.

**Comment by HudsonMC16** [comment]
You ever figure anything else out here? This issue is in each font I want to use, apparently, and it looks like I'm running an identical setup. Is this only a Windows issue?

**Comment by g-e-o-m-e-t-r-i-c** [comment]
no @HudsonMC16, i think the issue is with the version of the font that is being patched. the original fonts have all been updated since the time of patching, so the version of the font being used **in this repo** is outdated.

**Comment by ryanoasis** [comment]
@g-e-o-m-e-t-r-i-c I've updated the title of the issue. Thanks for follow up

**Comment by Finii** [comment]
Latest right now: https://github.com/tonsky/FiraCode/releases/tag/6.2

**Comment by Finii** [comment]
This has already been updated with commit
  78be0e1e74 `Add unpatched FiraCode v6.2`
