### ISSUE TITLE
There is uncomfortable space after airline-arrow-left

### ISSUE THREAD

**Issue by alpertuna** [ryanoasis/nerd-fonts#65]
Hello,
I'm using xterm and xterm's font-face setting to use patched font so not gvim but it doesnt matter, anyway.
This is DejaVu Sans Mono font and there is a problem.
![2016-03-14-015303_536x49_scrot](https://cloud.githubusercontent.com/assets/12586695/13732272/a5c038fe-e987-11e5-803d-27bfb5d01b36.png)
As you see at right side there is a little space after airline arrow icon, at left side there is not problem like that. Furthermore, font size is 10 now and when I increase it, space width also increases.

My old DejaVu font which patched only for airline, there was no problem like this.
Also this problems appears on many of that fonts, I didnt try all of them but.

This is unconfortable. If we can fix this, I will appreciate it.

**Comment by ryanoasis** [comment]
@alpertuna Hey thanks for the report. :+1: 

I have seen and/or had this problem before as well.

I am not sure how much can be done to eliminate this 100% but I will look into it nonetheless when I get some time

**Comment by ryanoasis** [comment]
@alpertuna Can you try downloading again with latest release?

**Comment by alpertuna** [comment]
+1 Perfect, it seems problem solved.
![2016-05-16-150906_444x274_scrot](https://cloud.githubusercontent.com/assets/12586695/15289041/0ef0788a-1b78-11e6-8fc9-687b141b8fca.png)

By the way this is DejaVu... mono one. And terminal is xterm, not gvim.
When I try non-mono font, left and right letter spacing is very huge in xterm but for gvim no problem again.
In the past also had this issue. However mono one does the job now so not problem for me, thanks :)

**Comment by ryanoasis** [comment]
Yeah mono one looks fairly good, here is my vim in xterm with DejaVu:

![selection_16_05_16_10 07 05_814x108_001](https://cloud.githubusercontent.com/assets/8083459/15291889/4cfd2742-1b4e-11e6-8cab-b4c2b57d9e75.png)

And non glyph mono of DejaVu:

![selection_16_05_16_10 11 05_836x109_001](https://cloud.githubusercontent.com/assets/8083459/15291941/979fafe0-1b4e-11e6-9381-664041b461fd.png)

**Comment by alpertuna** [comment]
I think problem is solved :relaxed:
