### ISSUE TITLE
The Chocolatey package for Fira Code NF is out of date

### ISSUE THREAD

**Issue by brian6932** [ryanoasis/nerd-fonts#650]
![image_240](https://user-images.githubusercontent.com/18603393/128866094-54fa1229-7777-4347-87a5-ef9d400907df.png)

**Comment by tigerinus** [comment]
FiraCode has just released v6. Time to update its NF version?

**Comment by ryanoasis** [comment]
Hey thanks for the heads up. I'm not a maintainer of that so not much we can do here.

I see you already opened another issue... looks like you just needed to fill the issue template...?
