### ISSUE TITLE
How to patch nerd fonts with emoji support?

### ISSUE THREAD

**Issue by jiangjianshan** [ryanoasis/nerd-fonts#651]
#### 🗹 Requirements

- [ ] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [ ] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ ] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

nerd-fonts is really an very good project. For Font Patcher, I have try to patch the nerd fonts for myself but still cannot find a way to patch the nerd font with emoji support.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_FiraCode Nerd Font
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_konsole
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_Kali Linux 2021.3

**Comment by Finii** [comment]
I do not really know what you propose here.

As you are on Kali it should be sufficient to install for example _Noto Color Emoji_ and rely on font-fallback.

Usually on _any_ system there are Emoji configured for fallback in any situations. That's also the case for Windows or Mac.

The emoji are not very critical with the scaling, so there is not really a need to have them in the current font.

Despite all the up-votes, I can possibly not grasp the reasons and goals. Closing for now. Reopen if there is something more concrete. Someone should write more here.

**Comment by Starry-Tacos** [comment]
I think that instead of using CJK unified ideographic glyphs for glyphs that already have a emoji character should be reassigned to their emoji counterparts.

> (I didn't research on the glyph assigning stuff, so if you find any problems do feel free to tell me)

**Comment by Finii** [comment]
> I think that instead of using CJK unified ideographic glyphs for [other] glyphs

That will stop with v3.0.0 ?

**Comment by Finii** [comment]
@jiangjianshan To be more concrete, your question is

> How to patch nerd fonts with emoji support?

I wound say (untested)

```
fontforge --script font-patcher --complete --makegroups --custom NotoEmoji-Regular.ttf FiraCode-Regular.ttf
```

Is that not working?
Of course after downloading the emoji font from https://fonts.google.com/noto/specimen/Noto+Emoji and putting it into the `src/glyphs/` directory.

**Comment by Finii** [comment]
If you want to patch a complete set of FiraCode Nerd Font, you probably want to
* shallow clone this repo
* add `config_patch_flags=--custom NotoEmoji-Regular.ttf`on a line to `src/unpatched-fonts/FiraCode/config.cfg`
* `cd bin/scripts`
* `./gotta-patch-em-all-font-patcher\!.sh -j /FiraCode`
