### ISSUE TITLE
fontforge cannot detect configparser in wsl2 debian

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [ryanoasis/nerd-fonts#653]
#### 🎯 Subject of the issue

I'm trying to patch `Fira Code` due to it having updated font ligatures, however the `font-patcher` script cannot seem to detect `configparser`, which I have installed with `pip3`.

#### 🔧 Your Setup
- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
      - `Fira Code`, original
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
      - WSL2, out-of-the-box terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
      - WSL Debian 10.10
  
 #### ★ Optional
![image](https://user-images.githubusercontent.com/79387351/129429975-055c9663-d7a6-45f2-a514-49fbddcb294c.png)

**Comment by Finii** [comment]
Probably your fontforge executes python2. Did you try to also `pip install` the `configparser` for 2?

And/or try the docker container?

**Comment by Finii** [comment]
Closed due to no response.
