### ISSUE TITLE
Please add missing from font-logos

### ISSUE THREAD

**Issue by Minecodes** [ryanoasis/nerd-fonts#656]
font-logos added new logos for Linux distros like Parrot OS, Kali Linux, Pop OS or Deepin OS.
Can you please add them? Because a Pull request has added them already ([github.com/ryanoasis/nerd-fonts/pull/551](https://github.com/ryanoasis/nerd-fonts/pull/551)).

**Comment by siduck76** [comment]
the next release will have the updated icons

**Comment by ryanoasis** [comment]
if you aren't particular about which font you use, you can try out https://github.com/ryanoasis/nerd-fonts/releases/tag/2.2.0-RC which has a small subset of fonts patched w/ the latest changes.

**Comment by siduck** [comment]
> if you aren't particular about which font you use, you can try out https://github.com/ryanoasis/nerd-fonts/releases/tag/2.2.0-RC which has a small subset of fonts patched w/ the latest changes.

oh I use jetbrainsmono font , I'll wait :(

**Comment by ryanoasis** [comment]
@siduck Added JetBrainsMono to the [2.2.0 RC](https://github.com/ryanoasis/nerd-fonts/releases/tag/2.2.0-RC) if you want to try it out. Thanks

**Comment by Minecodes** [comment]
@ryanoasis does FiraCode have that update already?

**Comment by ryanoasis** [comment]
@Minecodes sorry, what's the context? which update?

**Comment by Minecodes** [comment]
> @Minecodes sorry, what's the context? which update?

for the new symbols like the Kali Linux icon

**Comment by ryanoasis** [comment]
Ah, no FiraCode isn't updated. The RC is only doing a limited set of fonts.. I suppose we can change that soon. Just wanted to prove it out

**Comment by siduck** [comment]
> @siduck Added JetBrainsMono to the [2.2.0 RC](https://github.com/ryanoasis/nerd-fonts/releases/tag/2.2.0-RC) if you want to try it out. Thanks

thanks! it works :D

![image](https://user-images.githubusercontent.com/59060246/146627697-6ad7ab87-9cfd-44ec-9aa7-572f4fa74616.png)

**Comment by ryanoasis** [comment]
Just FYI all fonts are now being built in the RC

**Comment by marcomeyerVFX** [comment]
are you planning to update to font logos v0.18 before the next release? seems like they are not in the latest RC fonts yet.

**Comment by siduck** [comment]
> are you planning to update to font logos v0.18 before the next release? seems like they are not in the latest RC fonts yet.

they are, I got the void glyph from the RC version. Using it in my prompt and widget

![image](https://user-images.githubusercontent.com/59060246/150889104-b4531041-74d1-4774-a046-03d08512bad3.png)

**Comment by Finii** [comment]
v0.18 added Rocky Linux (at `0xF12F`): https://github.com/lukas-w/font-logos/releases/tag/v0.18
and that is not in the RC (after shifting it should end up somewhere like `0xF32F`).

We updated font logos only in december 2020 [commit](https://github.com/ryanoasis/nerd-fonts/commit/557b8da5c5ccdd918feabf8e1ecf386184273428) probably 0.16 (but not specified in the commit message :-()

https://github.com/lukas-w/font-logos/releases

So @marcomeyerVFX's request is a valid one.

**Comment by Finii** [comment]
Hmm, bug in font-logos release?

![image](https://user-images.githubusercontent.com/16012374/150956149-b3586ef7-9510-4ab4-aec7-34d6df085d79.png)

(last codepoint `0xF12D`)

**Comment by Finii** [comment]
Oh my ...

https://github.com/lukas-w/font-logos/commit/f161cf60da18815780bc48dacc0810490a1a8dfd broke it.

Lets see what we have / do and what they have done.

**Comment by Finii** [comment]
@marcomeyerVFX

 > are you planning to update to font logos v0.18 before the next release? seems like they are not in the latest RC fonts yet.

Which glyph are you missing? Any specifics?

Note differences in symbols ...

![image](https://user-images.githubusercontent.com/16012374/150967859-facfd4e8-f973-4833-9612-eb5a22605007.png)

**Comment by marcomeyerVFX** [comment]
rockylinux is the one I'm after

**Comment by Finii** [comment]
Ok.

We had a `font-logos` update here: #551
It updates to v0.16

Rock Linux is indeed only added in v0.18.
Unfortunately we could only update to v0.17 without problems.

With v.018 `font-logos` changes the codepoint of all symbols :sob:.
Maybe that is in error, thus I created https://github.com/lukas-w/font-logos/issues/72

I believe **no one** here wants to shift any glyph codepoints.
If we update to v0.18 (i.e. include Rocky Linux) we would need to shift all glyphs, most of them individually and not as block.

I would wait if `font-logos` reacts somehow to the Issue I raised, maybe they fix the glyph codepoints and release v0.19 or v0.18b or whatever. Than we can easily update. If they want to keep the new codepoints ... well ... :unamused: 

Lets hope.

----

Here is what happened. Left is the `font-logos` we use at the moment (i.e. v0.16).
The right one is v0.18. They added two glyphs and then ... shuffled all logos (to fill the gaps?)

![image](https://user-images.githubusercontent.com/16012374/151056373-19d53ba9-63d4-4fd6-a7c9-359bdec5b8fb.png)

**Comment by Finii** [comment]
We could update `font-logos` if they pull https://github.com/lukas-w/font-logos/pull/75 and re-release.

This is how v0.18.1 (or v0.19) would look like (compare with the v0.17 and v0.18 in the bottom of previous comment)

![image](https://user-images.githubusercontent.com/16012374/151150522-fc87dbc9-23f9-46f6-8bf8-134de736a2c2.png)

**Comment by Finii** [comment]
When I looked on the screenshot above I realized we can fill the other gap also, with no extra breaking...
https://github.com/lukas-w/font-logos/pull/75#issuecomment-1022124249

**Comment by siduck** [comment]
@Finii thanks! my prompt has a void logo now :)

![image](https://user-images.githubusercontent.com/59060246/192074494-7c9e988c-e4b1-4bc3-bd18-1a1205c94c06.png)
