### ISSUE TITLE
font-patcher crashes when patching Agave

### ISSUE THREAD

**Issue by ThoriumTextile** [ryanoasis/nerd-fonts#659]
#### 🗹 Requirements

- [X] A brief but descriptive _title_ of your issue
- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [X] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [X] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue
Whenever i try to patch (no output dir specified) `Agave-Regular-slashed` (from [here](https://github.com/blobject/agave)), font-patcher crashes with the following details/log:
**This happens with the regular Agave version (not slashed) too.**
```
The following table(s) in the font have been ignored by FontForge
  Ignoring 'TTFA'
The requested file, original-source.otf, does not exist
Traceback (most recent call last):
  File "/home/gabri/Downloads/./font-patcher", line 929, in <module>
    main()
  File "/home/gabri/Downloads/./font-patcher", line 924, in main
    patcher.patch()
  File "/home/gabri/Downloads/./font-patcher", line 88, in patch
    symfont = fontforge.open(self.args.glyphdir + patch['Filename'])
OSError: Open failed
```

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
- _Agave_
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
- _kitty_
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
- _Fedora 34, Linux_

**Comment by ryanoasis** [comment]
were you using the font-patcher from this repo? If so how did you download it? It sounds like you are missing the source files that the patcher relies upon.

**Comment by NuraliMedeu** [comment]
Hello! I have the same issue when patching [Kawkab Mono](https://github.com/aiaf/kawkab-mono).

## 🗹 Requirements
- [x] A brief but descriptive title of your issue
- [x] I have searched the issues for my issue and found nothing related and/or helpful
- [x] I have read or scanned the FAQ
- [x] I have read or scanned the Wiki

## 🎯 Subject of the issue
The same as above.

## 🔧 Your Setup
* _Which font are you using (e.g. Anonymice Powerline Nerd Font Complete.ttf)?_
Kawkab Mono
* _Which terminal emulator are you using (e.g. iterm2, urxvt, gnome, konsole)?_
Windows Terminal v1.11.3471.0
* _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Windows 11 Pro 21H2 Build 22000.376
* **_How did you get font-patcher?_**
I downloaded it from [the Nerd Fonts website](https://nerdfonts.com/) without any additional files from this repo.

**Comment by NuraliMedeu** [comment]
I just learned from reading other similar issues that the user needs to clone the entire repo for the font patcher to work. I think the script should automatically download its dependencies rather than rely on the user to install them.

**Comment by Finii** [comment]
I believe we are going to split this into one repo with the patcher (and what it needs) and one with the fonts.
But even then is an automatism to fetch missing parts nice. At least when it is an option, because I know enough ppl that dislike downloads not manually triggered.

**Comment by NuraliMedeu** [comment]
I think it's more frustrating when you expect a script file to work on its own and then realize that you need to manually download extra files for it to function, than when the said script works standalone, even if that means it automatically downloads its dependencies. As long as the need for those automatic downloads is explicitly communicated to the user and the script gives an option for their installation path, I think most people would accept this.

**Comment by Finii** [comment]
Hint has been added to `font-patcher`
Maybe use the prepared FontPatcher.zip from the release page?
Docker?
