### ISSUE TITLE
[Request] Add Endeavour OS icons

### ISSUE THREAD

**Issue by memesforlife1** [ryanoasis/nerd-fonts#660]
#### 🎯 Subject of the issue
Theres no Endeavour OS Icon

When I Open Up My terminal it uses the opensuse icon rather than a Endeavour OS Because the Icon does not exist yet.
#### 🔧 Your Setup

RobotoMono Nerd Font Bold, Gnome Terminal and Linux(Endeavour OS).
#### ★ Optional

![Screenshot from 2021-08-28 10-34-43](https://user-images.githubusercontent.com/68858960/131221534-a5f98635-54fa-4d33-9fac-55aa3fd1a02e.png)

**Comment by lokesh-krishna** [comment]
I don't think Nerd Fonts itself adds any icons. You'll have to make this request to one of the icon fonts that Nerd Fonts patches into the fonts.

**Comment by ryanoasis** [comment]
We do at times add individual glyphs if they are not already apart of a consumed glyph set collection.

That said Endeavour might make more sense to be added into https://github.com/lukas-w/font-logos which Nerd Fonts consumes. Then there wouldn't be conflict if font logos adds it later

**Comment by ronan696** [comment]
> Have opened PR [lukas-w/font-logos#71](https://github.com/lukas-w/font-logos/pull/71) to add the Endeavour OS logo

This PR is now approved and merged and into the main branch of https://github.com/lukas-w/font-logos!

**Comment by Finii** [comment]
Unfortunately Lukas did not pull https://github.com/lukas-w/font-logos/pull/75  ...
Did not even comment on it.
Hmm.

**Comment by Finii** [comment]
Done (icon is in Nerd Fonts via Font Logos)
