### ISSUE TITLE
Include Feather icons

### ISSUE THREAD

**Issue by reeseovine** [ryanoasis/nerd-fonts#665]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

I'm not sure if this has been brought up before but I couldn't find anything. It would be nice if the [Feather](https://github.com/feathericons/feather) icon set was included in the icons that are patched into Nerd Fonts. It has an MIT license so I believe this would be possible but correct me if I'm wrong.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_    
FiraCode Retina Nerd Font Complete.otf
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_    
kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_    
Ubuntu Linux 20.04

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
