### ISSUE TITLE
Wiki Error: Logo Font range should include up to f31c

### ISSUE THREAD

**Issue by NickCraver** [ryanoasis/nerd-fonts#667]
This one's a simple issue, but for the life of me I can't figure out how to edit the wiki here: https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points (I'm guessing permissions issue)

Under the [Font Logos](https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points#font-logos-formerly-font-linux), it says the range is `f300`-`f313`, but the actual range is a big wider: `f300`-`f31c`, verifiable here: https://www.nerdfonts.com/cheat-sheet?set=nf-linux-

I was using these ranges for a rendering thing and noticed because a character was missing, hope this wiki update helps others!

**Comment by ryanoasis** [comment]
Thanks for the heads up. Added you

**Comment by NickCraver** [comment]
All fixed up, thanks @ryanoasis!

**Comment by ryanoasis** [comment]
Thank _you_
