### ISSUE TITLE
build: provide a font file only having the added glyphs

### ISSUE THREAD

**Issue by esdnm** [ryanoasis/nerd-fonts#668]

**Comment by Finii** [comment]
I guess you would mean [`src/glyphs/Symbol-2048-em Nerd Font Complete.ttf`](https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/Symbols-2048-em%20Nerd%20Font%20Complete.ttf)?

It is a bit under-documented, as it seems (#670).

**Comment by ryanoasis** [comment]
They will now be in the releases as a specific/separate archive so that should _help_ but yes the docs on them need updating and such.

![Selection_094](https://user-images.githubusercontent.com/8083459/146702771-a0058f63-7862-4bbe-9871-5ceb58366f41.png)

**Comment by ryanoasis** [comment]
I am considering this a duplicate now that they _will_ be in the build of the release as we already have #670 to track improving the docs. Thanks
