### ISSUE TITLE
Collaborators and/or converting to an organization

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#67]
Debating converting to an organization or at least possibly inviting collaborators.

I would probably target starting with those who have already submitted PRs.

Any thoughts? Ping here if interested or have any suggestions.

---

I have not decided anything yet :stuck_out_tongue: just jotting my thoughts down

**Comment by her** [comment]
Hey @ryanoasis 

I'd be happy to help. I'm taking a second to kinda catch up, I've been really busy with work and so I haven't had a lot of time to keep an eye on what's happened. 

Is there any particular place that needs attention? 

I noticed that in this issue [discussing undocumented configuration](https://github.com/ryanoasis/vim-devicons/issues/152) and so that sort of pops out as needing to be added. I can start working on that this weekend.

**Comment by ryanoasis** [comment]
@her Hey thanks :smile: . No worries, I've actually been very busy with work as well.

Particular? Not that I can think of. Anything that improves things I am open to :+1: 

For [#152](https://github.com/ryanoasis/vim-devicons/issues/152) I am not exactly sure there is a bug but probably options do need to be clarified in the readme.

I've been doing [a lot of work on the readme lately](https://github.com/ryanoasis/vim-devicons/commits/0.8.4), so if you want feel free to tweak things in the [0.8.4 branch](https://github.com/ryanoasis/vim-devicons/tree/0.8.4)

--

Thinking about making a collaborators only gitter chat or something as well.

I just thought it was about time I add some collaborators.. well the main reason just in case but also it is a good thing to do.

**Comment by her** [comment]
Nice! Okay, got it. 🙂

As far as an Organization is concerned, were you thinking that would just make it easier to arrange the various repositories supporting the larger devicon concept? It may be beneficial to have them all organized in a central Devicon organization, with maybe a single point of release for users. Just kinda spit balling here 😄

Also, a collaborator gitter is a really good idea, I think. That way going forward it would be easier to just pop in to the chat and if people have been stating their efforts and work you can catch up efficiently.

**Comment by kierun** [comment]
I would be willing to help… Although I am not sure how much help I would be ;)

**Comment by ryanoasis** [comment]
@kierun Cool thank you and yes I understand. I will take any help that is offered large or small 😄

**Comment by evaryont** [comment]
Bringing this up again, I think it might be worth it now.

**Comment by kierun** [comment]
@ryanoasis I am been massively inefficient here. My apologies.

**Comment by ryanoasis** [comment]
@evaryont Yeah I think it's only inevitable at this point To be completely honest the main hold back is a very selfish reason, the other reasons after that are all just logistics and planning. I am not there yet :disappointed:

@kierun You shouldn't have anything to apologize for! Glad to have you on board. :smile:

**Comment by LuRsT** [comment]
Hey @ryanoasis what can I do to help out with splitting this repo into just the patcher and something that builds all the fonts?

**Comment by ryanoasis** [comment]
Thanks @LuRsT I know this is a late reply. I'm thinking about this now again..

**Comment by ryanoasis** [comment]
This is a WIP, Organization was created a while back: https://github.com/NerdFonts

Next steps: adding collaborators, moving the website, the patcher, etc.

**Comment by her** [comment]
@ryanoasis congratulations! 🍾 

What’s next? How can we help?

**Comment by ryanoasis** [comment]
@her Thanks and thanks for all you were able to contribute.

Good question. I already added everyone who was already a collaborator here. I am not sure exactly what help particularly at this moment but I am completely open to any feedback/suggestions/PRs that make things easier/better/faster.

I don't see this repo going away anytime soon but my goal is to have the website and patcher at separate repos and maybe even removed from this repo..

**Comment by LuRsT** [comment]
This is great, I'll do something when I got some time to spare regarding splitting the patcher from this repo

**Comment by ryanoasis** [comment]
I actually started on this but I wanted to preserve the git history of the patcher and relevant files, ran into some issues where I could see in git log but not github UI or something. This was months ago

**Comment by LuRsT** [comment]
Are you planning to restart that work @ryanoasis ?

**Comment by ryanoasis** [comment]
Yep 😄 . Right now working on a release pipeline so we don't have to wait on one person to make releases.

I really would prefer to keep the git history of the files especially the patcher script

**Comment by TamaMcGlinn** [comment]
Using `git subtree split` or `filter-branch` you could keep only that history. The size of the repo will be much smaller if we don't keep all those binary diffs around.

**Comment by ryanoasis** [comment]
I am no longer in a big hurry to do this as I think providing the patcher (with all of it's required source files) in the release solves most problems, for example: https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC/FontPatcher.zip

I'd appreciate any feedback though, also see: #716

**Comment by Finii** [comment]
Additionally to [`FontPatcher.zip`](https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC/FontPatcher.zip) (which is excellent!) I believe a simple non-archive font-patcher script that fetches what it needs would further improve usability (#741).

**Comment by Finii** [comment]
Closing this to clean up. Will be found via future tag.
