### ISSUE TITLE
Overlapping Arabic characters in MesloLGS

### ISSUE THREAD

**Issue by Farzat07** [ryanoasis/nerd-fonts#674]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_    MesloLGS-NF-Regular.ttf
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_    st
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_    Arch Linux

#### ★ Optional

![fonts](https://user-images.githubusercontent.com/55144155/136211810-6dbbc09f-5118-4992-8be7-a016864d7885.png)
The left terminal is using the Kawkab font, while the right one uses the MesloLGS font. As you can see, some characters are too wide in Meslo, causing the letters to overlap.

The problem occurs when the terminal doesn't support right-to-left rendering. Actually, for some uses, having left-to-right rendering even for Arabic can make editing easier (for example when the markup is in English), so I'm happy with that. However, having the letters overlap makes the text nearly impossible to read. If possible, I would like to have the Arabic characters resized so that they all fit within the space.

Btw, the screenshot above is using the regular font, but the same result happens when the mono font is used.

**Comment by Finii** [comment]
Hi!

Can you post your `echo` command into a comment box (as text not as image), so that I can copy and paste it?
I'm too stupid to enter arab text :grimacing: 

Thank you

**Comment by Farzat07** [comment]
شؤون إسلامية
