### ISSUE TITLE
dina nerd font

### ISSUE THREAD

**Issue by pjhalsli** [ryanoasis/nerd-fonts#679]
#### 🎯 Subject of the issue

I use Dina font but when using tmux and nvim the statusbar does lok horrible - I wonder if there is a way to fix this
#### 🔧 Your Setup
Linux (arch)
- _Dina
- _termite and alacritty
- _Linux - arch
![2021-10-27-152506_2880x1620_scrot](https://user-images.githubusercontent.com/12110311/139075003-6e5a70e0-dc5c-42ad-bf31-770e108b579f.png)

**Comment by DaBabyXD** [comment]
Patch Dina yourself using the patcher.
