### ISSUE TITLE
ProggyClean - Some broken icons

### ISSUE THREAD

**Issue by F1LT3R** [ryanoasis/nerd-fonts#68]
I was excited to see ProggyClean in your font list. This is my favorite programming font. Unfortunately it seems the icon set may be incomplete? (I'm using OSX El Capitan)

Look at the tabs/status bar in this screen shot. I get the [?] icon. :( 

**ProggyCleanTT Nerd Font Complete Mono.ttf:**
<img width="723" alt="screen shot 2016-03-14 at 10 52 27 am" src="https://cloud.githubusercontent.com/assets/1218446/13748406/199aa94e-e9d3-11e5-944f-2caf84c1d8a3.png">

However, Sauce Code Pro does work with all the icons, so I am thinking this is not my setup, but the Proggy Font itself?

**Sauce Code Pro Light Nerd Font Complete Mono.ttf**
<img width="724" alt="screen shot 2016-03-14 at 10 52 45 am" src="https://cloud.githubusercontent.com/assets/1218446/13748398/0df5c68c-e9d3-11e5-9b93-e7e5e1150b11.png">

Here is my font section from my `.vimrc` file:

```vim
set noantialias       " Turn on/off Anti-Aliased Fonts

if has("gui_running")
  set transparency=2
  if has("gui_gtk2")
    set guifont=Inconsolata:12
  elseif has("gui_macvim")
    set guifont=Sauce\ Code\ Pro:h15
    "set guifont=ProggyCleanTT:h16
  elseif has("gui_win32")
    set guifont=Consolas:h11:cANSI
  endif
endif
```

**Comment by ryanoasis** [comment]
@F1LT3R Ah yes looks like they are missing.. not sure what is going on but I did confirm powerline glyphs are indeed missing. :worried: 

Thanks for the heads up! :+1: 

--

**update:** so...... apparently there was a typo which prevents the powerline symbol font from being copied at all! D'oh! This was a PR and I did not catch it (it's all good).

Here is an after the fix (right) and before the fix (left):

![selection_14_03_16_12 27 59_506x142_001](https://cloud.githubusercontent.com/assets/8083459/13751470/bcf52242-e9e0-11e5-96c4-28bd4c9fd590.png)

Here is the point of the issue: 

Actually this issues seems to have been introduced in https://github.com/ryanoasis/nerd-fonts/commit/9d3e60ac6631d4fd07c46bf1f90396dc0287eca8#diff-3b192ccaec850d73e6540b7eddd8b50cR360

**Comment by F1LT3R** [comment]
That was quick! :)

Looking forward to updates.

Perhaps this is the wrong place to ask, but I'll try anyway: I wondered if
we can get ProggyCleanTTSZ on the list? That would be ProggyCleanTT with
slashed zeros instead of dotted zeros.

**Comment by ryanoasis** [comment]
> can get ProggyCleanTTSZ on the list

Sure :smile:,  just make a separate issue or I will make one soon if you'd rather.

I think I came across a bunch of ProggyClean variations and in my ignorance wasn't sure exactly what the differences were and picked only a few to patch.

**Comment by F1LT3R** [comment]
I did try checking out `nerd-fonts` and patching `ProggyCleanTT` myself changing line: 421

```python
if args.powerline:
    copy_glyphs(sourceFont, symbolsPowerlineRange1Start, symbolsPowerlineRange1End, powerlineSymbols, symbolsPowerlineRange1Start, symbolsPowerlineRange1End)
```

I ran:

```shell
ontforge -script font-patcher unpatched-sample-fonts/ProggyClean/Regular/ProggyClean.ttf --fontawesome --octicons --pomicons --powerline --powerlineextra
```

And also with `--careful`..

But these did not seem to fix the issue for me :(

**Comment by F1LT3R** [comment]
What program are you using in your screenshot where you are checking that the correct glyphs are at the correct registers?

**Comment by F1LT3R** [comment]
Ah, I changed the next line also and it seems like I have glyphs! :smile: 

But... they seem to be a funny size. Maybe I can live with that?

![screen shot 2016-03-15 at 9 58 21 am](https://cloud.githubusercontent.com/assets/1218446/13780121/8208c918-ea94-11e5-9b1b-b6cddba13f8c.png)

**Comment by F1LT3R** [comment]
Created PR: https://github.com/ryanoasis/nerd-fonts/pull/71

**Comment by ryanoasis** [comment]
> What program are you using in your screenshot where you are checking that the correct glyphs are at the correct registers?

FontForge gui. Not an extensive check sorry just quickly opened the patched fonts to verify my theory.

> ... I have glyphs! :smile:

Glad it worked for you as well! :smile: Thanks for checking it too.

> But... they seem to be a funny size. Maybe I can live with that?

This something a bit tricky I need to improve and work on and there are similar issues currently open related to glyph sizing and/or positioning issues.

> PR

Great thanks, I'll get it in to the next release :+1:
