### ISSUE TITLE
Using xterm256 'echo $'\ue62b'"

### ISSUE THREAD

**Issue by kingram6865** [ryanoasis/nerd-fonts#683]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

Using ohMyZsh and the glyphs are not showing, just the box representing the location.

#### 🔧 Your Setup

- fixed (xterm256 system default)
- xterm256
- Debian Linux

#### ★ Optional

![image](https://user-images.githubusercontent.com/13263318/141888062-e72a8c7b-2f0b-4e96-bf01-98fd9cd2fc0a.png)

**Comment by Finii** [comment]
I'm not really sure which font you are using?
Maybe you can specify it.

What you show in your screenshot looks like 'the default xterm font', which has the boxes in them, just as you show.
Did you really select a different font?

Here what I tried:
![image](https://user-images.githubusercontent.com/16012374/143824662-c8ead76a-c488-4879-8990-6618811d4104.png)

**Comment by kingram6865** [comment]
> I'm not really sure which font you are using? Maybe you can specify it.
> 
> What you show in your screenshot looks like 'the default xterm font', which has the boxes in them, just as you show. Did you really select a different font?
> 

> Here what I tried: ![image](https://user-images.githubusercontent.com/16012374/143824662-c8ead76a-c488-4879-8990-6618811d4104.png)

Thanks for responding. I forgot about posting this issue.
I realized that I need to change my xterm font. I'm using SecureCRT and realized 
I needed to change the font option in my settings. I also downloaded a couple of Nerd Fonts and it works fine now.

Apologies if I wasted your time.
