### ISSUE TITLE
Icons appear smaller than expected after installing Nerd Fonts

### ISSUE THREAD

**Issue by isak102** [ryanoasis/nerd-fonts#688]
The icons appear very small compared to when I only had Font Awsome installed, as you can see in the screenshot I provided below. The left terminal is the icon size after installing a nerd font and the right terminal is the icon size before installing a Nerd Font. Notice that the FontAwesome icons are the correct size before installing nerd fonts but after installing a nerd font the FontAwesome icons became smaller aswell. I tried many different nerd fonts and the same thing happened for all of them, however some were smaller than others. 

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
`Roboto Mono Nerd Font Complete Mono.ttf`
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
`kitty`
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
`Arch Linux 5.15.4`

#### ★ Optional
![fonts_bug](https://user-images.githubusercontent.com/90389894/143320454-61076217-5633-46bf-b1aa-85f86fa201e7.png)

**Comment by Finii** [comment]
Lets have a closer look at your screenshot:
![image](https://user-images.githubusercontent.com/16012374/143393680-e307eee1-aa9f-49e6-9048-24561d33a7c6.png)

On the left the folder icons are as wide as the numbers/letter -> monospaced.
On the right the folder icons are 1.5 times as wide as the letters/numbers -> not monospaced

What people want is diverse, some like the left some like the right. It also depends on your setup.

Of course you get the left (monospaced) if you select a _Nerd Font Mono_.
Probably you should use a non-Mono variant:
`Roboto Mono Nerd Font Complete Mono.ttf` -> `Roboto Mono Nerd Font Complete.ttf`

Please reopen if this does not help :-)

**Comment by isak102** [comment]
> Lets have a closer look at your screenshot: ![image](https://user-images.githubusercontent.com/16012374/143393680-e307eee1-aa9f-49e6-9048-24561d33a7c6.png)
> 
> On the left the folder icons are as wide as the numbers/letter -> monospaced. On the right the folder icons are 1.5 times as wide as the letters/numbers -> not monospaced
> 
> What people want is diverse, some like the left some like the right. It also depends on your setup.
> 
> Of course you get the left (monospaced) if you select a _Nerd Font Mono_. Probably you should use a non-Mono variant: `Roboto Mono Nerd Font Complete Mono.ttf` -> `Roboto Mono Nerd Font Complete.ttf`
> 
> Please reopen if this does not help :-)

Thanks alot, this worked. Sorry for opening an issue on this, I completely missed the information about monospaced fonts
