### ISSUE TITLE
Trying to convert latest Cascadia Code PL font, Nerd Fonts cannot open font

### ISSUE THREAD

**Issue by ThaDaVos** [ryanoasis/nerd-fonts#691]
#### 🗹 Requirements

- [X] A brief but descriptive _title_ of your issue
- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [X] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [X] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

Trying to convert eh Cascadia Code font myself with the following command;
`fontforge -script "/home/dylan/projects/font-patcher/nerd-fonts/font-patcher" "/home/dylan/projects/font-patcher/CascadiaCode/otf/static/CascadiaCodePL-ExtraLight.otf" -c --careful -out ./out`

But it throws an error and I cannot figure out what's going wrong

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ CasCadia Code PL
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ Tmux inside WSL 2
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Linux through Windows -> WSL 2

#### ★ Optional

![image](https://user-images.githubusercontent.com/5251028/143691094-4b6fa3bc-3532-46c2-b43e-18e051d93e05.png)

**Comment by ryanoasis** [comment]
This should be fixed now. Please re-try.

see my comment for more info: https://github.com/ryanoasis/nerd-fonts/pull/687#issuecomment-980831193

**Comment by Finii** [comment]
Ah, `fontforge` changed:

![image](https://user-images.githubusercontent.com/16012374/143763144-3e4f01cd-6a55-4056-a903-4355d2f495dd.png)

Lets see how we keep the `fstype` fix for older `fontforge`s...

**Comment by Finii** [comment]
They added the plain name options only in 2020: https://github.com/fontforge/fontforge/commit/4a76712f0c74090f8aaab7ba67612d1941f05779

![image](https://user-images.githubusercontent.com/16012374/143763395-afc17ed6-a06d-44dc-bf15-162bcd35c7cb.png)

So wie have to use the dump numbers instead of modern names...
Will create MR with reverted reverted fix fixed ;-D

**Comment by ThaDaVos** [comment]
So I am running an older FontForge version - even though I just installed it yesterday? 😂

**Comment by ThaDaVos** [comment]
I can confirm, it works now :D

**Comment by Finii** [comment]
> I can confirm, it works now :D

Thanks. 

Did you use `master` or the `bugfix` branch from #692?

What is the version number of your `fontforge`?

**Comment by ThaDaVos** [comment]
I used master and fontforge is version 20190801 (as can be seen in the screenshot)

But I am gonna use the AppImage from now on as the PPA seems broken and installing an old version

**Comment by Finii** [comment]
> as can be seen in the screenshot

:see_no_evil: Sorry :-)

Maybe you can try the `fsType` fix on the old `fontforge` (*)?

Use the `font-patcher` script from [here](https://github.com/ryanoasis/nerd-fonts/blob/bugfix/fstype-font-does-not-open/font-patcher)
or just add a `, 1` to your existing script like so:
```diff
@@ -52,7 +52,7 @@ class font_patcher:
        self.setup_arguments()
        self.config = configparser.ConfigParser(empty_lines_in_values=False, allow_no_value=True)
        try:
-            self.sourceFont = fontforge.open(self.args.font)
+            self.sourceFont = fontforge.open(self.args.font, 1)
        except Exception:
            sys.exit(projectName + ": Can not open font, try to open with fontforge interactively to get more information")
        self.setup_font_names()
```

(*) Although I could build it from source I have issues with the python binding that I would rather not debug ;)

**Comment by ThaDaVos** [comment]
The latest from `master` with FontForge 20190801 works, it's patching them - but I guess you mean newer FontForge versions are broken by the fix on `master`?

**Comment by Finii** [comment]
I mean `nerd-fonts` not `master` but `bugfix/fstype-font-does-not-open` together with your 20190801 `fontforge`.

The bugfix just adds a `,1` to line 55 of `font-patcher`.

Older `fontforge`s were broken after fixing `fsType`.
Ryan reverted the fix, that is what is now `master`.
Then I re-did the `fsType` fix to work with older `fontforge`s like yours, not yet merged into master.

**Comment by ThaDaVos** [comment]
Oh, I am gonna try that fix once I done - so I can verify if it works with the older versions again and then you can merge it

**Comment by Finii** [comment]
Exactly, thats it! Thank you!!

**Comment by ThaDaVos** [comment]
Can confirm - it works

I use the following script to patch stuff:
```zsh
#!/usr/bin/env zsh

if ls Cascadia* 1> /dev/null 2>&1; then
    echo "Cleaning existing source files"
    rm -rf Cascadia*
fi

if [ -d "out" ]; then
    echo "Cleaning existing output files"
    rm -rf out
fi

if [ ! -d "nerd-fonts" ]; then
    git clone -b bugfix/fstype-font-does-not-open https://github.com/ryanoasis/nerd-fonts.git --depth=1
fi

curl -s https://api.github.com/repos/microsoft/cascadia-code/releases/latest \
  | grep "browser_download_url.*CascadiaCode.*zip" \
  | cut -d : -f 2,3 \
  | tr -d \" \
  | wget -qi -

mv CascadiaCode*.zip CascadiaCode.zip

curl -s https://api.github.com/repos/fontforge/fontforge/releases/latest \
  | grep "browser_download_url.*FontForge.*AppImage" \
  | cut -d : -f 2,3 \
  | tr -d \" \
  | wget -qi -

mv FontForge*.AppImage FontForge.AppImage

unzip CascadiaCode.zip -d CascadiaCode

chmod +x FontForge.AppImage

for file in $PWD/CascadiaCode/otf/static/*(.); do
    echo "calling \"fontforge -script \"$PWD/nerd-fonts/font-patcher\" \"$file\" -c --careful -out ./out\""
    #./FontForge.AppImage -script "$PWD/nerd-fonts/font-patcher" "$file" -c --careful -out ./out
    fontforge -script "$PWD/nerd-fonts/font-patcher" "$file" -c --careful -out ./out
done
```

**Comment by ThaDaVos** [comment]
Getting an error with the AppImage:
![image](https://user-images.githubusercontent.com/5251028/143767488-fb8cd23a-1169-478f-8b26-d0d2a1a69b8e.png)

**Comment by ThaDaVos** [comment]
Which is version `20201107`

**Comment by ThaDaVos** [comment]
And I know for sure, the system is not readonly

**Comment by ThaDaVos** [comment]
Forget that... missed the note on using the AppImage, works fine:
```zsh
#!/usr/bin/env zsh

if ls Cascadia* 1> /dev/null 2>&1; then
    echo "Cleaning existing source files"
    rm -rf Cascadia*
fi

if [ -d "out" ]; then
    echo "Cleaning existing output files"
    rm -rf out/
fi

if [ ! -d "nerd-fonts" ]; then
    git clone -b bugfix/fstype-font-does-not-open https://github.com/ryanoasis/nerd-fonts.git --depth=1
fi

curl -s https://api.github.com/repos/microsoft/cascadia-code/releases/latest \
  | grep "browser_download_url.*CascadiaCode.*zip" \
  | cut -d : -f 2,3 \
  | tr -d \" \
  | wget -qi -

mv CascadiaCode*.zip CascadiaCode.zip

curl -s https://api.github.com/repos/fontforge/fontforge/releases/latest \
  | grep "browser_download_url.*FontForge.*AppImage" \
  | cut -d : -f 2,3 \
  | tr -d \" \
  | wget -qi -

mv FontForge*.AppImage FontForge.AppImage

unzip CascadiaCode.zip -d CascadiaCode

chmod u+x FontForge.AppImage

if [ ! -d "out" ]; then
    mkdir out
fi

for file in $PWD/CascadiaCode/otf/static/*(.); do
    echo "calling \"fontforge -script \"$PWD/nerd-fonts/font-patcher\" \"$file\" -c --careful -out ./out\""
    ./FontForge.AppImage -script "$PWD/nerd-fonts/font-patcher" "$file" -c --careful -out "$PWD/out"
    #fontforge -script "$PWD/nerd-fonts/font-patcher" "$file" -c --careful -out ./out
done
```

**Comment by Finii** [comment]
\*confused looking\* So it did work with both `20190801` and with the AppImage?

Nice script btw. :-)

(Sorry to spam you with requests)

**Comment by ThaDaVos** [comment]
Yeah it works perfectly - I mean the `bugfix/fstype-font-does-not-open` branch

Thanks

Oh no problem, I have the issue page open - haven't checked mail yet 😂
