### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by masonzaizhe2** [ryanoasis/nerd-fonts#696]
#### 🔧 OWASP dependency check scan 
- The OWASP dependency check tool is used to check if there are vulnerable dependencies in the source code. From the result 14 vulnerable dependencies are found and some of them can be false positive. However, could you please confirm if some versions of the dependencies are being used? If yes, could you please update them to the latest version for security concern?

#### ★ Optional

Please check the attachment for the complete dependency scan report
[nerd-fonts_dependency-check_2021-11-26 (3).zip](https://github.com/ryanoasis/nerd-fonts/files/7618927/nerd-fonts_dependency-check_2021-11-26.3.zip)
.

**Comment by pcjmfranken** [comment]
This sketchy zip - which contains only a single HTML file that executes a bunch of obfuscated JS - is hilariously inappropriate considering the subject of your concerns.

Couldn't you just provide a plaintext summary of the report?

**Comment by ryanoasis** [comment]
Assuming the best intentions here, please can you open a new issue with the summary of the report instead of an attachment?

which as @pcjmfranken alluded to relies on a heavy dose of trust.

This looks to be finding issues with node dependencies. We only have one dev dependency (no prod ones)

**Comment by pcjmfranken** [comment]
> Assuming the best intentions here

Just to clarify that I am too, only pointing out the incongruity 😉
