### ISSUE TITLE
Update Fira Code to version 6

### ISSUE THREAD

**Issue by thegcat** [ryanoasis/nerd-fonts#697]
#### 🎯 Subject of the issue

[Fira Code version 6](https://github.com/tonsky/FiraCode/releases/tag/6) has been released, it would be nice to have an updated Nerd Fonts version.

**Comment by mathomp4** [comment]
Ahh. This explains why I haven't seen it yet. I `brew install`ed the Nerd Font version! Duh.

**Comment by tigerinus** [comment]
There is https://github.com/tonsky/FiraCode/releases/tag/6.1 now.

**Comment by gitfool** [comment]
Note: I added the patched fonts to the above PR in FiraCode.zip for anyone that wants to try it.
