### ISSUE TITLE
[Request] Neovim icon

### ISSUE THREAD

**Issue by zbirenbaum** [ryanoasis/nerd-fonts#700]
I was wondering if it would be possible to add an icon for neovim to nerdfonts, especially since vim has its own: 

Something like this without the circle background would be perfect!

<img src="https://user-images.githubusercontent.com/32016110/144163322-f2649d6b-0b90-43f6-93bd-82c4fb295039.png" width="250" height="250"/>

**Comment by Finii** [comment]
Hej :-) I'm `neovim` user myself.

![image](https://user-images.githubusercontent.com/16012374/144178689-9d3dbf36-ba53-415e-9b50-1d45415319c5.png)

But someone would have to create the icon.
Maybe it's best to ask this upstream at devicons https://github.com/vorillaz/devicons.

Until there is a font glyph I fear we can not do much. Closing this, but please reopen if you have something.

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/144184726-e645dc6e-0dd6-4e5e-9e34-060a1930ca21.png)
 They do have a monochrome svg... technically it should be no problem to patch it in, but I believe it does not make sense if `nerd-fonts` does it on its own; sooner or later there will be a codepoint clash.
On the other hand, if you really want to and need it, you could patch it into your fonts just for yourself.
