### ISSUE TITLE
`iosevka` font failed to install in Windows 11

### ISSUE THREAD

**Issue by mangkoran** [ryanoasis/nerd-fonts#701]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue
Latest `iosevka` font failed to install in Windows 11.

Latest `iosevka` font (79d1d79f8790bae29afac57c0b8b2d73c97f4b9f) failed to install in Windows 11. I have tried both regular and Windows Compatible version, and none of them managed to be installed. `iosevka` from https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.1.0 works fine.

#### 🔧 Your Setup

- Edition	Windows 11 Pro
Version	21H2
Installed on	‎30/‎07/‎2021
OS build	22000.348
Experience	Windows Feature Experience Pack 1000.22000.348.0

#### ★ Optional

![image](https://user-images.githubusercontent.com/57625126/144241929-f87b0734-95d4-4961-b71d-395047bbb1bc.png)

**Comment by Finii** [comment]
Thanks for reporting, but duplicate to #694

It will take some time till I come to that, if you need the font urgently try patching yourself without ligature removal.

**Comment by Finii** [comment]
Waait, that is not `mono`? \*grr\*

Thank you.

**Comment by mangkoran** [comment]
May you elaborate what made it unable to install? Is it "Font Patcher" issue or something?

**Comment by Finii** [comment]
@mangkoran the fonts are corrupted (by font-patcher's ligature removal) see #694

**Comment by mangkoran** [comment]
Alright. Thank you!

**Comment by Finii** [comment]
But then, the non-mono fonts, do they remove the ligatures? I would have to check...

```
 ~  git  nerd-fonts  ../fontforge/build/bin/fontforge patched-fonts/Iosevka/Regular/complete/Iosevka\ Nerd\ Font\ Complete.ttf
Copyright (c) 2000-2021. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20201107
 Based on sources from 2021-11-29 12:07 UTC-ML-D-GDK3.
 Based on source from git with hash: c771abdbd30a26b51d2066a185a0fa2a695f98b4
Failed to open resource file: /home/fini/git/fontforge/build/share/fontforge/pixmaps/resources
Internal Error:
Subtable status not filled in for 0th subtable of 'calt' Contextual Alternates lookup 26
Subtable status not filled in for 1th subtable of 'calt' Contextual Alternates lookup 26
Subtable status not filled in for 2th subtable of 'calt' Contextual Alternates lookup 26
Subtable status not filled in for 0th subtable of 'dlig' Discretionary Ligatures lookup 32
Subtable status not filled in for 1th subtable of 'dlig' Discretionary Ligatures lookup 32
Subtable status not filled in for 2th subtable of 'dlig' Discretionary Ligatures lookup 32
Subtable status not filled in for 0th subtable of Reverse Contextual Chaining Substitution lookup 35
Subtable status not filled in for 1th subtable of Reverse Contextual Chaining Substitution lookup 35
Subtable status not filled in for 2th subtable of Reverse Contextual Chaining Substitution lookup 35
Subtable status not filled in for 0th subtable of Reverse Contextual Chaining Substitution lookup 38
Subtable status not filled in for 1th subtable of Reverse Contex
```

![image](https://user-images.githubusercontent.com/16012374/144254110-2f75f2db-e46e-4447-bcbd-91f0838de5b9.png)

The **source** opens ok:
```
 ~  git  nerd-fonts  ../fontforge/build/bin/fontforge src/unpatched-fonts/Iosevka/Regular/iosevka-regular.ttf
Copyright (c) 2000-2021. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20201107
 Based on sources from 2021-11-29 12:07 UTC-ML-D-GDK3.
 Based on source from git with hash: c771abdbd30a26b51d2066a185a0fa2a695f98b4
```

**Comment by Finii** [comment]
The font files were broken, should be ok since `v2.2.1`
