### ISSUE TITLE
Lilex VF can not be patched

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#709]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

`Lilex VF` is included in the `src/unpatched_fonts/` **and** there is a `patched_fonts/Lilex/VF', but the later is empty.

The `VF` designator says it's a variable font, which we can not patch.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ `src/unpatched_fonts/Lilex/VF/Lilex-VF.ttf`
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Ubu21.10, `fontforge` HEAD self built

#### ★ Optional
I guess it should at least be removed from the `patched_fonts`, but possibly also from the `src/`.

![image](https://user-images.githubusercontent.com/16012374/145586874-fbcd94fc-4c9c-4cdb-b4cf-1d4dcf60014d.png)

**Comment by Finii** [comment]
Well, the `font-patcher` behavior is expected, but why is it included if we know beforehand it is impossible to patch?

**Comment by ryanoasis** [comment]
Yeah Lilex VF should not have been included. Though I believe there were some rumblings of later FontForge versions possibly being able to edit variable fonts I have not kept up nor do I think it's official yet.
