### ISSUE TITLE
GitHub Discussions vs Issues

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#714]
Hello, hello. Going forward we are going to leverage one of the newer Github features, [Discussions](https://docs.github.com/en/discussions), which is now enabled on the repo.

### Now what?

Going forward we ask that you create discussions instead of issues for the following:

* [You have a general question that isn't an issue](https://github.com/ryanoasis/nerd-fonts/discussions/categories/q-a)
* [You have a request to add a new font, icon/glyph, update a font, or some other enhancement](https://github.com/ryanoasis/nerd-fonts/discussions/categories/ideas)
* [You have any ideas for new features in general](https://github.com/ryanoasis/nerd-fonts/discussions/categories/ideas)

#### To have a better place to synchronously communicate

We have issues and we have the gitter chat. The problem with gitter chat is threads get lost and it's better as a stand in for ad hoc random chat and help. Whereas issues are very good for structured and organized issues. There seems to be a gap here that Discussions would fill.

Previously discussions like future major releases (i.e. `3.0`), converting to an organization, replacing old or unmaintained glyph sets with newer versions or community forks have been relegated to issues which never really seemed to fit in that format.

For additional thoughts that are said better by others see:
* https://dev.to/dzhavat/my-thoughts-on-github-discussions-29me

The [Nerd Fonts gitter chat](https://gitter.im/ryanoasis/nerd-fonts) will remain open in parallel for the time being.

#### To have a cleaner separation of issues vs other

To better delineate issues vs other community questions, ideas, and general comments. We could continue to use issue labels but the issues end up never being closed resulting in an overall inflated open issue number as well some discussions don't really have a final ending point so having them as issues doesn't align well.

Sometimes we'll want to propose an idea to the community or have someone open an issue where it doesn't align best in an issue format

#### Overall

Overall, this is something we're going to try out.  We'll want to see if it: improves organization, fosters more open discussion and ideas. If this doesn't work out we can always go back.

Thanks! 🔡

**Comment by MichaelRumpler** [comment]
What happens to existing issues? Will you move them over?

**Comment by ryanoasis** [comment]
> What happens to existing issues? Will you move them over?

Good question. Only certain issues will get moved. Mostly the ones tagged as discussion or ones that are not easily actionable.

**Comment by Finii** [comment]
Closing this to avoid listing it in the normal Issues list.
It is still pinned above, though.
