### ISSUE TITLE
Add crypto glyphs: Ethereum, Solana, Shiba Inu, Avalanche, etc.

### ISSUE THREAD

**Issue by pcgeek86** [ryanoasis/nerd-fonts#728]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki) for help

#### 🎯 Subject of the issue

Add glyphs for common crypto currencies, such as Solana, Ethereum, Shiba Inu, Doge Coin, Avalanche, and others.

https://github.com/monzanifabio/cryptofont

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ UbuntuMono Nerd Font Mono
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ Windows Terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Windows 11 Dev Preview

**Comment by Finii** [comment]
Solved via #978 and #773
