### ISSUE TITLE
Extract the patched fonts into separate repository?

### ISSUE THREAD

**Issue by logarytm** [ryanoasis/nerd-fonts#73]
I should not have to clone/download +1GiB repository just to patch one non-free font. No, optical fiber cables aren't available in every location yet on this planet.

**Comment by ryanoasis** [comment]
Yeah I am sorry about that. :disappointed: 

You are correct they really should be in a different/separate repo. :+1: 

It is something that has come to my mind several times but I have yet to address the issue (mostly due to a backlog of other issues).

**workaround:** I know this isn't ideal but you can actually patch any font you want without downloading the entire repo. 
The only things you should need are `font-patcher` and the `glyph-source-fonts` folder.


--

> No, optical fiber cables aren't available in every location yet on this planet.


Yeah, it is something I know we all need to think more about if we are lucky enough to have decent connections.

**Comment by ryanoasis** [comment]
Just to be clear I would probably only get around to this if there is enough interest to form a GitHub organization (see #67)

**Comment by ryanoasis** [comment]
This is going to be at least partially fixed in 1.0.0 release (the size issue is addressed)

**Comment by ryanoasis** [comment]
I am very tempted to close this but... I still think it is a valid concern/question. 

This does depend on #67 though. I **will not** separate out the fonts from the patcher (and various dependencies) without converting this project to an organization :smile:

**Comment by perrin4869** [comment]
It would be amazing if this landed!

**Comment by egeesin** [comment]
I researched about getting specific subdirectories of a repository and I found out that GitHub supports 2.19 git version which has ``filter`` option and the commands below should only gets ``src`` and ``font-patcher``. This [answer](https://stackoverflow.com/a/52269934/4357874) explains how's that command works.
```sh
$ git --version
git version 2.31.1
```
```sh
git clone --depth 1 --filter=blob:none --sparse https://github.com/ryanoasis/nerd-fonts
cd nerd-fonts
git sparse-checkout set font-patcher src/
```
At the time I wrote this comment, if I clone whole repository (with --depth 1), the directory size was ~5.7GB. As a user who wants to just patch a font family, running the commands above gives me 467.5MB.

**Comment by earboxer** [comment]
[git-filter-repo](https://github.com/newren/git-filter-repo/) is the newish, easy, efficient, and recommended way to clean up a repository like this one. If you don't care about keeping a separate repo around (after all, the built fonts are included in GitHub's release artifacts), do the following.

```sh
git-filter-repo --force --invert-paths --path patched-fonts
git push --force
```

* whole folder 12.5 GiB => 748.3 MiB
* .git directory 7.4 GiB => 247.6 MiB

You could further save space in the repo by doing this to `src/unpatched-fonts/` (those could be replaced by symbolic links to their canonical repositories, though it would take a little restructuring to keep the `config.cfg` files).

**Comment by Finii** [comment]
Unfortunately the new Gitlab workflow again stores all build artifacts INSIDE the repo. I am not really sure why.
(`Commit and push ...` in picture below)

The workflow should just create artifacts. Who is interested can download them from the RC release page. If new actions run the old artifacts will be forgotten (except when they are proper releases).

![image](https://user-images.githubusercontent.com/16012374/151311550-c3a3f359-6079-43f9-b965-165215755d71.png)

I believe the workflow must be fixed first.

For the workflow to be fixed I would also propose to externalize the build process out of gitlab actions, some script, Makefile, Meson build definition, whatever, that does all the work. That can also be invoked locally by users and developers and create the same artifacts that Gitlab would create.

But then the repo filter is excellent! Good suggestion.

**Comment by Finii** [comment]
I put this on the "future" milestone and close.

At the moment I can not work on that because of missing access rights, though.
