### ISSUE TITLE
Li*t*eration instead of Li*b*eration in the name of the font in the "downloads" page

### ISSUE THREAD

**Issue by liar666** [ryanoasis/nerd-fonts#740]
Just a quick note: in the "downloads" page of your web site (https://www.nerdfonts.com/), the "Li*b*eration" font is misnamed "Li*t*eration".

Since the error is in the SVG that "demo"es this font appearance, the bug might be in some code that generates this SVG.

![Screenshot 2021-12-24 at 15-23-10 Nerd Fonts - Iconic font aggregator, glyphs icons collection, fonts patcher](https://user-images.githubusercontent.com/3216927/147358892-0c8c9ca6-d112-4a5e-b6d7-aba2e86790c0.png)

**Comment by Finii** [comment]
Well, the font is not 'misnamed', it has been renamed.

Some of the original fonts allow modifications to the font, but the modified fonts need to have a different name.
You see a `Reserved Font Name` comment under that fonts, and it is also the case with Liberation.

The fonts are under the SIL open font license. You find details about the reserverd font names (RFN) [here](https://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web_fonts_and_RFNs)

It's the same with AnonymousPro -> Anonymice; Cascadia Code -> Caskaydia Cove; Hasklig -> Hasklug, ...

So, it is as intended; but thank you for reporting :-)
