### ISSUE TITLE
File didn't pass sha256sum (AUR)

### ISSUE THREAD

**Issue by jtbx** [ryanoasis/nerd-fonts#743]
#### 🎯 **Subject of the issue**
File didn't pass sha256sum (AUR)

#### 🔧 Your Setup

- Font: Not a problem with the font, couldn't even download them
- Terminal: Alacritty
- OS: Arch Linux w/ kernel 5.15.11-arch2-1

#### 📄 Description

I `git clone`d this package here from the AUR: [nerd-fonts-complete](https://aur.archlinux.org/packages/nerd-fonts-complete/) then I cd'd into its directory, and ran `makepkg -sci`. The tar.gz archive took a long time to download (understandable, considering the archive's size), then it displayed the messages seen in the screenshot below.
Is this the package maintainer's fault, or is something fishy going on here?

#### ★ Screenshots

![Error while running makepkg -sci](https://i.ibb.co/hH3KSkT/Untitled.png)

**Comment by Finii** [comment]
Hmm, validating the source manually works for me...
I have no explanation for your fail, something with the download?

![image](https://user-images.githubusercontent.com/16012374/147730287-c1e5f0ca-0ced-4547-bd9c-66f5e213b2c8.png)

**Comment by Finii** [comment]
They say to manually download the tar, for whatever reason?

![image](https://user-images.githubusercontent.com/16012374/147730602-a23438ba-99f2-498a-801f-3c3a27bc61df.png)

**Comment by jtbx** [comment]
Sorry about the delay, but it verifies successfully now. :)
