### ISSUE TITLE
Symbols-2048-em Nerd Font Complete Mono broken

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#753]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki) for help

#### 🎯 Subject of the issue

In folder `nerd-fonts/patched-fonts/NerdFontsSymbolsOnly/complete/`:

`Symbols-2048-em Nerd Font Complete Mono` and `Symbols-2048-em Nerd Font Complete Mono Windows Compatible.ttf` contain **only empty glyphs**.

Originally reported by @jamapy https://github.com/ryanoasis/nerd-fonts/commit/2d03a39223d76a1eb87f233cd03ba5e365cc68f5#commitcomment-62991279

Additionally:
All `1000-em` variants contain an empty glyph at codepoint `U+0045` (Latin capital letter E) !??

_Guess: The rescaling?_

Also noticed that all variants contain no glyph at codepoint `U+0000`. But that is mandatory, iirc. But I can not find that 'rule' right now, and a lot of fonts don't, so maybe I remember wrongly so: i-dont-care.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/16012374/148344546-6ff106ae-4d6e-413c-9cf3-452963b53916.png)

**Comment by ryanoasis** [comment]
fixed in d2cd41e4c59f1f791cefea13e635d8a1c9857993
