### ISSUE TITLE
Sauce Code Pro Doesn't Look Right

### ISSUE THREAD

**Issue by DakshG07** [ryanoasis/nerd-fonts#755]
#### 🗹 Requirements

- [x ] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [ x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x ] I have searched the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki) for help

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
  - **Using Sauce Code Pro Complete fonts. (All of them)**
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
  - **Using alacritty**
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
  - **Linux, Pop!_OS, Gnome, BSPWM**

#### ★ Screenshots (Optional)
![image](https://user-images.githubusercontent.com/48651837/148625487-9a7ec03b-083b-46ee-be35-f4253d3a728d.png)

**Comment by sanchay9** [comment]
You gotta write the correct name of the font i.e. 'SauceCodePro Nerd Font' in this case.
You can find what a font is called by something like `$ fc-list | grep "Sauce"`

**Comment by Finii** [comment]
The font files are from HEAD of this repo `patched-fonts/SourceCodePro/`?

Is the issue also present if you just install one of the font files?

I can not run `alacritty` (Snap), it seems to lack support for my graphics (Radeon).
Do you see the issue in any other program? I tried Libre Writer and Tilix with no issues (for _Regular_).

**Comment by Finii** [comment]
Ah, as @sanchay9 said, you have the wrong family maybe?

Now I use another (old) machine with NVIDIA (:vomiting_face:), and can run `alacritty`.

Filling in the correct family and it seems to work:

![image](https://user-images.githubusercontent.com/16012374/148645269-05607495-091e-4c70-b270-b7a3f996b64a.png)

Used this file: https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/SourceCodePro/Regular/complete/Sauce%20Code%20Pro%20Nerd%20Font%20Complete.ttf

(I have no clue if that font is really Source Code Pro, I know of know distinctive feature)

Please close this if the issue goes away after filling in the correct family name.

**Comment by DakshG07** [comment]
Thanks! Renaming the font worked. Closing the issue now.
