### ISSUE TITLE
Inconsolata Nerd Font not Working in URxvt

### ISSUE THREAD

**Issue by amarakon** [ryanoasis/nerd-fonts#756]
I am currently using rxvt-unicode. I have the Inconsolata patched font installed on my system. But the icons don't work, they show up as just boxes. Here is my Xresources:

`! Copyright (c) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
! Copyright (c) 2016-present Sven Greb <code@svengreb.de>

! Project:    Nord XResources
! Version:    0.1.0
! Repository: https://github.com/arcticicestudio/nord-xresources
! License:    MIT

#define nord0 #2E3440
#define nord1 #3B4252
#define nord2 #434C5E
#define nord3 #4C566A
#define nord4 #D8DEE9
!#define nord5 #E5E9F0
#define nord5 #AEB3BB
#define nord6 #ECEFF4
#define nord7 #8FBCBB
#define nord8 #88C0D0
#define nord9 #81A1C1
#define nord10 #5E81AC
#define nord11 #BF616A
#define nord12 #D08770
#define nord13 #EBCB8B
#define nord14 #A3BE8C
#define nord15 #B48EAD

*.foreground:   nord4
*.background:   nord0
!*.cursorColor:  nord4
*.cursorColor:  nord13
*.highlightColor: nord3

!*fading: 35
!*fadeColor: nord3

*.color0: nord1
*.color1: nord11
*.color2: nord14
*.color3: nord13
*.color4: nord9
*.color5: nord15
*.color6: nord8
*.color7: nord5
*.color8: nord3
*.color9: nord11
*.color10: nord14
*.color11: nord13
*.color12: nord9
*.color13: nord15
*.color14: nord7
*.color15: nord6

!URxvt.color
!#858381

URxvt.secondaryScreen: 1
URxvt.secondaryScroll: 0

URxvt.font: xft:Inconsolata Nerd Font:size=11
URxvt.letterSpace: -1
URxvt.linespace: 1

URxvt.scrollBar: true
URxvt.scrollBar_right: true
URxvt.scrollBar_floating: true
URxvt.scrollstyle: plain

! scroll with output
URxvt.scrollTtyOutput: false

! scroll in relation to buffer (with mouse scroll or Shift+Page Up)
URxvt.scrollWithBuffer: true

! scroll back to the bottom on keypress
URxvt.scrollTtyKeypress: false

!! Common Keybinds for Navigations
URxvt.keysym.Shift-Up: command:\033]720;4\007
URxvt.keysym.Shift-Down: command:\033]721;4\007

URxvt.clipboard.autocopy: false
! Disable ISO 14755 unicode input so we can use Ctrl-Shift bindings
URxvt.iso14755:        false
URxvt.iso14755_52:     false

! Disable Ctrl-Alt-c & Ctrl-Alt-v bindings (optional)
URxvt.keysym.C-M-c:    builtin-string:
URxvt.keysym.C-M-v:    builtin-string:

! Bind Ctrl-Shift-c & Ctrl-Shift-v to copy and paste
! I dont know why, but I needed to use hex keysym values to get it to work
URxvt.keysym.C-S-0x43: eval:selection_to_clipboard
URxvt.keysym.C-S-0x56: eval:paste_clipboard

URxvt.perl-ext-common: default,matcher,font-size,-confirm-paste
URxvt.url-launcher: xdg-open
URxvt.matcher.button: 1

URxvt.keysym.C-Delete: perl:matcher:last
URxvt.keysym.M-Delete: perl:matcher:list
URxvt.keysym.C-equal: perl:font-size:increase
URxvt.keysym.C-BackSpace: perl:font-size:reset
URxvt.keysym.C-plus: perl:font-size:incglobal
URxvt.keysym.C-underscore: perl:font-size:decglobal
URxvt.keysym.C-backslash:  font-size:show

URxvt.internalBorder: 0
URxvt.externalBorder: 0

!URxvt.matcher.rend.0: Uline fg6

! Disable fading
!URxvt*fading: false

! Bell
!URxvt.bell-command: setsid mpv --keep-open=no /usr/share/sounds/freedesktop/stereo/bell.oga &>/dev/null
Sxiv.font: Inconsolata:size=11`

**Comment by kierun** [comment]
> URxvt.font: xft:Inconsolata Nerd Font:size=11

`urxvt256c-ml*font: xft: PragmataPro Nerd Font Mono:style=Regular:pixelsize=19:antialias=true:autohint=true`

This is what I use and it works fine for my font. I am not sure how up to date `urxvt` is compared to `urxvt256c-ml` since I moved to `Alacritty`.

**Comment by amarakon** [comment]
This didn't work for me, but I switched to Alacritty.
