### ISSUE TITLE
Fonts look blurry

### ISSUE THREAD

**Issue by arjanfrans** [ryanoasis/nerd-fonts#76]
I am using Ubuntu with a resolution of 1920x1080 and the patched fonts look verry blurry. I was using [powerline fonts](https://github.com/powerline/fonts) before, which looked much sharper.

This is how it looks in my terminal with nerd-fonts:

![screenshot from 2016-04-10 22 47 37](https://cloud.githubusercontent.com/assets/3588470/14413018/7a79782a-ff6e-11e5-9f4c-8b129157f5e4.png)

This font is Sauce Code Pro Medium, Bold size 10.  However, it looks blurry for every font. It also appear too large for size 10.

This is how it looks with the powerline font:
![screenshot from 2016-04-10 22 53 15](https://cloud.githubusercontent.com/assets/3588470/14413039/0cede40c-ff6f-11e5-96bf-e7833f2b83e8.png)

**Comment by ryanoasis** [comment]
That is weird, I will try to check that out

**Comment by ryanoasis** [comment]
Sorry, been busy but I promise to check this out (if of course it is still an issue for you?)

**Comment by arjanfrans** [comment]
I recently upgraded to the new Ubuntu version. I can not reproduce it anymore.

I think you can close this issue.

**Comment by ryanoasis** [comment]
@arjanfrans Hey thanks for the update I appreciate it!

Closing for now.
