### ISSUE TITLE
symbols decrease size afetr install

### ISSUE THREAD

**Issue by ralpheeee88** [ryanoasis/nerd-fonts#77]
When i install nedr fonts the icons decrease in size (are squashed together)

before nerd fonts: (have a look chrome icone for example)
https://i.imgur.com/Pp45FRX.png
after
https://i.imgur.com/Urg49Id.png

also wanted to use powerlevel9k and if I install nerd fonts again the icons get mixed up and the wrong symbols are used with the theme....

hope you can point me in the right direction...thxs!

**Comment by ryanoasis** [comment]
It looks to me like one of them is 'true Mono' and the other the glyphs are double width.

Which font are you using?

**Comment by ralpheeee88** [comment]
Droid Sans Mono for Powerline

**Comment by ryanoasis** [comment]
Is that a patched version from one of the nerd fonts (https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/DroidSansMono/complete) ?

**Comment by ralpheeee88** [comment]
yes it is, i also tried different fonts and still have issue..(also look at the graphs as they reduced in size as well)

**Comment by ryanoasis** [comment]
Ah okay I see. But which one those did you install? E.g. `Droid Sans Mono for Powerline Nerd Font Complete.otf` or `Droid Sans Mono for Powerline Nerd Font Complete Mono.otf`

To me it looks like the 'Mono' version which would explain why those graphs are getting squished

**Comment by dritter** [comment]
The answer to the powerlevel9k question is quite simple: we do not support nerd fonts yet. But you can built your own set of glyphs based on nerd fonts, if you want. Just override every icon variable with an according code point from you chosen font. Type `get_icon_names` to get a full list of icon variables.

**Comment by ralpheeee88** [comment]
Nice....Thxs so much dritter.....also ryanoasis with arch I discovered its better not to install from AUR or use your script to install once cloned as I get the glyph issue....just git clone....copy fonts to ~/.fonts and fc-cache -vf that did the trick for me....

**Comment by ryanoasis** [comment]
@dritter Thanks for the response on powerlevel9k I completely missed that in the message :blush: 

--

@ralpheeee88

Thanks for the updates.

> I discovered its better not to install from AUR or use your script to install once cloned as I get the glyph issue

That's odd but I am glad you got it sorted out
