### ISSUE TITLE
Tamil Fonts not displaying correctly, overlapping with other characters

### ISSUE THREAD

**Issue by sharand** [ryanoasis/nerd-fonts#777]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki) for help

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
     -_Font Used: `MesloLGS NF`_
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
     -_`iterm2`_
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
    -_OS X_

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/8002203/152430236-b4c19d98-7480-4c4c-952a-477e7734a1e9.png)

Tested Tamil Text: அகர முதல எழுத்தெல்லாம்; ஆதி பகவன் முதற்றே உலகு.

**Comment by Finii** [comment]
Thanks for the good issue report (useful data given and glyphs to copy and paste for experiments) :+1: 

The first letter in your example is this I assume:

![image](https://user-images.githubusercontent.com/16012374/152492933-e32ae153-5f8d-449e-a672-27c6cd9c88ab.png)

Which is empty in the patched Meslo as well as our source:

![image](https://user-images.githubusercontent.com/16012374/152493094-1ae9bc6f-6067-4ed5-9e51-f7109baaf419.png)

The only font I have installed that contains that letter:

![image](https://user-images.githubusercontent.com/16012374/152494387-cb19ab61-7b1d-423a-ada6-83df891df759.png)

has it with no negative bearings (overlap into next character). Despite of that my terminal (`tilix`) renders the fallback font like in your `iterm`, with overlap.

In (Libre Office) `writer` on the other and it renderes with the correct width (no blanks typed in here):

![image](https://user-images.githubusercontent.com/16012374/152495187-e0e305b7-9808-4704-b0c6-bcd8b2a8e9ac.png)

So this issue has nothing to do with the patched font but with your terminal and how it handles font fallback.
Sorry there is nothing we can do about it (except adding tamil letters to the patch set ;).

#### Addendum:

When I use FreeSerif in my terminal, it ... 'works' but the advance width in the monospaced terminal is then adjusted to fit the widest glyph which looks kind of ugly for roman letters:

![image](https://user-images.githubusercontent.com/16012374/152497221-dab77bb4-0e83-4f2b-b052-a1791d294abb.png)

The only terminal that I am aware of that handles double width characters in some way is the (new?) MS Windows Terminal.


Maybe other people have more ideas, especially with IOS my knowledge is very limited. So I leave this open for a while, albeit I deem this closed.
