### ISSUE TITLE
Powerline symbols not correctly rendered

### ISSUE THREAD

**Issue by saschagrunert** [ryanoasis/nerd-fonts#78]
#### Powerline symbols not correctly rendered on v0.7.0

When using the latest release v0.7.0 the powerline symbols are not correctly rendered. All other icons are rendered well. For example, within vim:

![screenshot](https://cloud.githubusercontent.com/assets/695473/14634538/a7338f9e-0622-11e6-8fb8-69a4552b6c74.png)

#### Setup

- Font: `Meslo LG M DZ Regular for Powerline Nerd Font Complete.otf`, but it affects different other fonts as well
- Terminal: Termite
- OS: Arch Linux / Kernel 4.5.1

**Comment by ryanoasis** [comment]
Apologies and thanks for the report. I will look into it

**Comment by ryanoasis** [comment]
Ah yeah I was growing impatience in getting v0.7.0 out :blush: 

Good news is this is a somewhat easy fix, fonts that already have powerline glyphs should not get patched by Nerd Fonts. Currently only Hack and Source Code Pro are working correctly in this scenario.

--

Also, just wondering if you find the issue template helpful or annoying?

**Comment by saschagrunert** [comment]
Ah alright, no the issue template is a quite good starting point. :)
