### ISSUE TITLE
ShureTechMono Nerd Font Mono display problem（Windows Terminal）

### ISSUE THREAD

**Issue by wesley7891** [ryanoasis/nerd-fonts#784]
![image](https://user-images.githubusercontent.com/94120374/153387572-e6f130d1-ece6-481b-8b98-b6f1206aabf6.png)

When I entered #find# in the terminal, #fi# will change to the telephone icon, I don't know how to fix it. And I think this is a little bug ^_^

**Comment by Finii** [comment]
Should have been fixed with #711 

Can you check out if the font file you use is a 'current' one?

![image](https://user-images.githubusercontent.com/16012374/153410337-32ffcb05-b489-4c1c-8aa8-eb24060506b1.png)

I see no problem with a freshly downloaded file

![image](https://user-images.githubusercontent.com/16012374/153410744-cc93e9f3-d045-4856-bbd3-7d7ded4f4301.png)

**Comment by wesley7891** [comment]
![image](https://user-images.githubusercontent.com/94120374/153542274-2538aae5-dba1-4c74-9e2d-055b7a7a0747.png)

I downloaded the latest font, but When I installed them the Windows Operating system notified to me these fonts are not valid fonts.

**Comment by Finii** [comment]
Ok I will check

**Comment by Finii** [comment]
Ah, on Windows you probably need `'Shure Tech Mono Nerd Font Complete Windows Compatible.ttf'`

Will take some time until I can get my fingers on a Windows box.

**Comment by Finii** [comment]
Hmm, on my Windows box even the non-Windows version (which might have longer names inside, Windows limits the names to 31 letters or something, and we abbreviate that in the Windows Comp version) can be installed.

![image](https://user-images.githubusercontent.com/16012374/153549199-364a94e2-713f-40ae-832b-bef8b1e7bb7d.png)

And there is no `fi` ligature problem

![image](https://user-images.githubusercontent.com/16012374/153549304-a166a782-1d4d-4546-bda4-190c2fadb22d.png)

Make sure to uninstall all Shure Tech Mono, then install the new font from the Repo https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/ShareTechMono/complete

**Comment by wesley7891** [comment]
![image](https://user-images.githubusercontent.com/94120374/153577418-b543bcc8-8f8d-432a-809e-7b2480ef98f2.png)
It works, thank you very much ^_^, and I truly love this #ShureTechMono# font, and you guys do a great job! Thanks!!
