### ISSUE TITLE
Caskaydia Cove not displaying on visual studio code, but displayed correctly in the integrated terminal.

### ISSUE THREAD

**Issue by mina-atef-00** [ryanoasis/nerd-fonts#785]
#### 🗹 Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki) for help

#### 🎯 Subject of the issue

Same as Title, Using the same property `CaskaydiaCove NF` on both the integrated terminal font and the editor font family. But the font is only displayed properly in the integrated terminal.
#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
Caskaydia Cove Regular Nerd Font Complete Windows Compatible.otf
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
Visual Studio Code
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Windows 10 21H1

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/52796958/153759040-4488b9db-df1e-4f48-8a82-045ccc8a9d02.png)

**Comment by Finii** [comment]
I'm sorry I have no Visual Studio Code installed. Anyhow, I have Visual Studio; but that seems to look completely different:
![image](https://user-images.githubusercontent.com/16012374/153873302-41aed133-1d01-40e9-a232-65f60c40300a.png)

And there the font shows up and is usable.

Where did you download the font from? Direkt from the `Code` file list?
![image](https://user-images.githubusercontent.com/16012374/153873707-17fe31ca-1f69-4008-98c7-c71f34d14bce.png)
In subdir [`patched-fonts/CascadiaCode/Regular/complete`](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CascadiaCode/Regular/complete).

If that does not show up, maybe you should try the `Caskaydia Cove Regular Nerd Font Complete Mono Windows Compatible.otf` font?

**Comment by Finii** [comment]
Hmm, `Visual Studio Code` is small :-D
Quickly installed.

Works on my machine?

![image](https://user-images.githubusercontent.com/16012374/153894440-5128ccd9-67a4-4a91-9e67-4841ec97acf1.png)

I downloaded the fonts here: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CascadiaCode/Regular/complete

And just installed one file: `Caskaydia Cove Nerd Font Complete Windows Compatible.ttf`

**Comment by pure-cheekbones** [comment]
Weird, I downloaded it from the link you provided and installed it again, same output.

**Comment by Finii** [comment]
That is strange. Did you remove all `Caskaydia *` with this _Fonts_ dialog and then install just that one font file? And restart VSCode afterwards?

**Comment by miloradowicz** [comment]
Having the same issue in Visual Studio. To me it seems Visual Studio might have a problem with PostScript outlines.

**Comment by Finii** [comment]
I could not reproduce (i.e. works on my machine) with

https://github.com/Finii/nerd-fonts/tree/feature/cascadia-2111.01-patched/patched-fonts/CascadiaCode/Regular/complete

@miloradowicz Did you remove all `Caskaydia*`, reboot and install just one of the 2111.01 Caskaydias?

**Comment by miloradowicz** [comment]
I tried that, it didn't work. To be clear, my issue is with Visual Studio, VS Code seems to work fine.
Here are some other things I tried:
1) version 1911.210 from [here](https://eng.m.fontke.com/font/69661501/detail/). It's ttf, and it worked;
2) BlexMono (ttf), FiraCode (ttf), Fantasque (ttf) worked;
3) Hasklig (otf), FuraMono(otf) didn't work.

**Comment by Finii** [comment]
I have this:
![image](https://user-images.githubusercontent.com/16012374/166449108-6c333844-9d37-4726-a100-92a8635b3349.png)

Download and install this
https://github.com/Finii/nerd-fonts/blob/feature/cascadia-2111.01-patched/patched-fonts/CascadiaCode/Regular/complete/Caskaydia%20Cove%20Nerd%20Font%20Complete%20Windows%20Compatible%20Regular.otf

I have no other Caskaydias installed.

![image](https://user-images.githubusercontent.com/16012374/166450032-9dbeb23d-4a7a-4d4f-9585-911131875912.png)


And I can select it:

![remmina_HaskStep7_localhost:1111_20220503-120624](https://user-images.githubusercontent.com/16012374/166449791-33448602-d6c2-43bc-abaa-90914d82b3fc.png)

**Comment by miloradowicz** [comment]
Doesn't work for me on Win11/VS2022.

**Comment by Finii** [comment]
Unfortunately no screenshot.

Maybe it allows only monospaced fonts now?
Probably https://github.com/Finii/nerd-fonts/blob/feature/cascadia-2111.01-patched/patched-fonts/CascadiaCode/Regular/complete/Caskaydia%20Cove%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible%20Regular.otf (`... Nerd Font Complete Mono... `) 
Not shure if that contains "Make NerdFonts Monospaced Again" and just only on mobile right now.

**Comment by miloradowicz** [comment]
Mono doesn't work either. I guess that's the VS2022 thing, I'll stick to ttf fonts for now.

**Comment by Finii** [comment]
@miloradowicz `Caskaydia Code Whatever.ttf` works?
Or do you mean `some other font`.

**Comment by miloradowicz** [comment]
> * version 1911.210 from [here](https://eng.m.fontke.com/font/69661501/detail/). It's ttf, and it worked;
> 
> * BlexMono (ttf), FiraCode (ttf), Fantasque (ttf) worked;

All those worked above. I'm not sure about the origin of the Caskaydia in the link, since it's coming from an outside source. But it was Caskaydia Code Regular, and I needed Light. BlexMono, FiraCode and Fantasque are from this repo.

I tried all the font faces of Caskaydia Code.otf and none of them worked. I've only tried light versions of Hasklig and FuraMono.otf, and they didn't work either. I'm actually not sure if it's a ttf vs otf thing; I tried converting PostScript outlines to TrueType with FontForge, and it didn't help, although I'm not proficient with the tool, so I probably did something wrong.

**Comment by Finii** [comment]
Is VS 2022 (as the versions I have) still free for open source users? Then I can install that and install. Maybe you can link me to some MS page, to help me :-)

And you still did not say how 'not working' shows up? The font not in the selector dialog? The font not working if selected? etc?

**Comment by Finii** [comment]
What I see with VS2019 ist that `Cascadia` is **bold** while `Caskaydia` is not, meaning it is not detected as monospaced.
If that is the problem, one can work on that. But VS2019 took non-mono-detected fonts no questions asked...

**Comment by Finii** [comment]
Hmm, installed VS2022 and was able to select Caskaydia Cove same way as with VS2019:

![remmina_HaskStep7_localhost:1111_20220509-142809](https://user-images.githubusercontent.com/16012374/167432253-e25db47d-bb7b-4f1b-bf72-eaefe39e4698.png)

The font face looks a bit thinner, and **bold** is missing, but then, I didn't install bold.

**Comment by Finii** [comment]
Hmm, but the issue author claims it happened on Win 10...

This is strange. I installed the font just by double click on the font file, and then ... click 'install' in the font preview window.

And I'm 'admin' on the machine, have no clue if that makes a difference where the font is installed or something.

**Comment by Finii** [comment]
You use 'light'. Is the problem also present with 'regular' that I used :thinking:

**Comment by Finii** [comment]
Your Caskaydia version number is strange ... `2007.001` that's definitive an old font file.

![image](https://user-images.githubusercontent.com/16012374/167434705-a4add1ff-fe68-4e13-beb0-b39044837a45.png)

**Comment by Finii** [comment]
Looks like **I** have installed it into some strange personal folder (and it works) and you have it in the system folder :thinking:

**Comment by Finii** [comment]
Hmm, `Delugia` works and is even **bold** ;-)

![image](https://user-images.githubusercontent.com/16012374/167436334-e7ae7771-3d85-4951-a48c-f98c2c908f10.png)

[Delugia](https://github.com/adam7/delugia-code/releases/tag/v2111.01) is where I deviate with the patching a bit from the usual 'Nerd Fonts path' in patching `Cascadia Code`.

**Comment by miloradowicz** [comment]
Well, I narrowed down the issue to the Terminal in VS.
Here Caskaydia shows up for the Text Editor font.
![image](https://user-images.githubusercontent.com/16267644/167439633-5713cb0e-d837-44f9-8c3e-7f6e3acb4fdd.png)
And here it doesn't for the Terminal window.
Tried with the font you linked above [version 2111.01-patched](https://github.com/Finii/nerd-fonts/blob/feature/cascadia-2111.01-patched/patched-fonts/CascadiaCode/Regular/complete/Caskaydia%20Cove%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible%20Regular.otf)
![image](https://user-images.githubusercontent.com/16267644/167439788-f41dca3d-deff-4190-8118-aeacdf983c9d.png)

**Comment by Finii** [comment]
Waah, there are different 'show settings for', I never noticed that.

**Comment by Finii** [comment]
Possible work around: #831

**Comment by madjxatw** [comment]
It seems that CaskaydiaCove_NF is not rendered as thick as Cascadia Code for me in VS2022. But it has no problem in Windows terminal or even GVim.

**Comment by Finii** [comment]
I guess this is solved with `v2.2.2`?

**Comment by madjxatw** [comment]
It seems better, but still has issues. 1) Caskaydia looks much smaller than Cascadia; 2) Cascadia still looks fuller and smoother than Caskaydia.

Left side is Caskaydia, right side is Cascadia Code PL
![kascadia_issue](https://user-images.githubusercontent.com/6035833/188947092-2fac6317-3126-4832-b668-6133de7d9871.png)

**Comment by Finii** [comment]
Maybe just one question before I try to reproduce...
Did you try the static Cascadia Code font files, or the variable font one, where all weights are in one file?

**Comment by madjxatw** [comment]
I am using the OTF files from [Microsoft official repo](https://github.com/microsoft/cascadia-code), each weight has a separate file.

**Comment by Finii** [comment]
Thank you, I will try to reproduce.

**Comment by Finii** [comment]
Ok, at the moment I have the dynamic font installed, because that is bundled with `Windows Terminal` and it is a hassle (at least I am too dump for a simple solution) to remove just the font but keep the app.

Anyhow, @madjxatw issue is visible on my machine. VS2022:
![grafik](https://user-images.githubusercontent.com/16012374/189617602-59eb2b1c-c932-4074-9b1e-08445b98c12f.png)

`Caskaydia` is wider and the lines are less tall.
Additionally it seems the antialliasing has been turned off:

![grafik](https://user-images.githubusercontent.com/16012374/189618547-032ef5a1-65a6-4c64-88dc-8ad751510c65.png)

**Comment by Finii** [comment]
Hmm, the size is identical in both fonts, if looked at with `fontforge`...

![grafik](https://user-images.githubusercontent.com/16012374/189624984-60d0ed7c-d9a8-499e-922d-f2efd2bfd021.png)

(In the bottom the path to the `Windows Terminal` 'installed' font.)

**Comment by Finii** [comment]
Uninstalled `Windows Terminal` app, installed the 4 basic `Cascadia.otf` from Nerd Fonts `src/unpatched-fonts/`...
Same behavior in VS2022.

But indistinguischable in `Writer` 🤔 
![grafik](https://user-images.githubusercontent.com/16012374/189629510-4ab28595-dad0-4eb1-bc53-9f61057507f3.png)

**Comment by Finii** [comment]
Hmm, opening the original `otf` in `fontforge` and generatig a new font works (i.e. looks good).
This is strange, but will take some time until I come round to check that in detail (sorry).

**Comment by Finii** [comment]
Tried `Visual Studio Code` (original issue) and there I see no difference in rendering. VSCode Version 1.71.0

Interestingly the problem is not in VS2019 - there the fonts are rendered equally bad :->

![image](https://user-images.githubusercontent.com/16012374/189642881-e328639d-0a76-48e7-a4d2-989312494050.png)

Also note that the 'Sample:' box in VS2022 shows the same 'bad looking' font, the antialiasing is just at work in the main editor window :thinking:

**Comment by espenja** [comment]
I tried to enable `CaskaydiaCove NF` as my VSCode terminal font and it wouldn't work. Tried restarting VSCode and my running Terminal instances. The solution for me was simply to kill `explorer.exe` in Task Manager and restart it by running `File -> Run new task -> explorer.exe` to force a refresh of . Sounds silly, but hey, if it works... 🙄

**Comment by wswind** [comment]
For my issue ( win 11 / VS 2022)  `CaskaydiaCove NF` is not selectable for vs terminal. [Delugia](https://github.com/adam7/delugia-code/releases/tag/v2111.01)  is a good workaround. I'll wait for this to fix.

**Comment by Finii** [comment]
Hmm, @wswind , is Delugia `v2111.01.1` still working for you? You reference `v2111.01`.

**Comment by Finii** [comment]
Just installed Delugia `v2111.01.1` on my test-box, and it seems to work as expected:
![image](https://user-images.githubusercontent.com/16012374/194748483-df353d96-be10-4da5-9d70-6920b90d64eb.png)

Delugia and Delugia Mono can be selected but not Delugia Book.

**Comment by Finii** [comment]
Now the question is: Why is Delugia working but Caskaydia Cove not? As the latest Delugia uses (almost) vanilla Nerd-Fonts-v2.2.2.

Well, `CaskaydiaCove NF` should not be selectable, because that is the equivalent to `Delugia Book`. But what is with `NFM` (`Nerd Font Mono`)?

Okay, even `CaskaydiaCove NFM` is not showing up, but `Cascadia Code` is **also** missing.

**Comment by Finii** [comment]
Could it be that the `VS terminal` thing does only work with `ttf` and not with `otf` at all?

**Comment by wswind** [comment]
> Could it be that the `VS terminal` thing does only work with `ttf` and not with `otf` at all?

Yes, this may be the reason.  I tried [CascadiaCode-2111.01](https://github.com/microsoft/cascadia-code/releases/tag/v2111.01).   `CascadiaCodePL.ttf` can be selected in vs terminal, but  `CascadiaCodePL-Regular.otf`  can not. So I think the issue has noting to do with this project.

**Comment by johnholliday** [comment]
Is there a workaround to enable CaskaydiaCove NF and Terminal-Icons in the VS terminal?  I'm using oh-my-posh in PowerShell and VSCode, but not in VS 2022.

**Comment by Finii** [comment]
You could use Delugia [1] instead of Caskaydia Cove, if their settings suit you.
Otherwise you can use a tool like TransType ($$$) or other open source tools to convert the `otf`s to `ttf`s.

Hmm, that answer springs from the conclusion above:
>  the VS terminal thing does only work with ttf and not with otf at all?

while this Issue's title talks about Visual Studio Code.
I'm confused :grinning: 
You state you use Caskaydia in VSCode.

[1] https://github.com/adam7/delugia-code

**Comment by johnholliday** [comment]
@Finii I can't use oh-my-posh in Visual Studio 2022 because it does not support CaskaydiaCove NF like both PowerShell and VSCode do.  I will try using the delugia-code font to see if that works with Terminal-Icons.

**Comment by Finii** [comment]
Ok, please report back. Can try to check if problem still.
I guess I do not understand what 'Terminal-Icons' means, but maybe that is not important.

**Comment by bevanshaw** [comment]
> Ok, please report back. Can try to check if problem still. I guess I do not understand what 'Terminal-Icons' means, but maybe that is not important.

This is what terminal icons means. They are the small triangles and pictures that work with nerd fonts. Below is an image from Visual Studio Code where the icons are working followed by Visual Studio 2022 Developer Powershell 7 Terminal where they are not:

VS Code icons working:
![image](https://user-images.githubusercontent.com/40314714/228401709-fa78eeeb-6dac-4a4b-977f-abcfd7eafcba.png)

VS 2022 icons not working:
![image](https://user-images.githubusercontent.com/40314714/228401602-df0caadf-fda8-4b50-bece-a582ddf7e76b.png)

**Comment by Finii** [comment]
With the Nerd Font v3.0.0 Release Caskaydia Cove is now `ttf` and not `otf` any longer. That was needed to get the hints in the font match expectations (i.e. compare almost equal to the variable Cascadia Code font that a lot people have installed out of the box and that they use to compare.

Regarding the missing icons, if that is still a problem with 3.0.0, please open a new Issue.

To make sure the correct fonts are installed
* Uninstall all Caskaydia Cove
* Reboot
* Install from Release package

**Comment by Finii** [comment]
That is Visual Studio 'proper', not Visual Studio Code, I guess.

Is that in the code editor or the terminal? Screenshot, also of the settings?

**Comment by Finii** [comment]
Hmm, it happens in both, the editor and the terminal.
It also happens with VS 19

(O_o)

**Comment by alexis35115** [comment]
any news on this, i have the same issue on Visual Studio 2022 and the lastest version of the font.

It was working on W10 but not longer works on W11.

**Comment by johnholliday** [comment]
Caskaydia Code doesn't work, but Hack Nerd works just fine.  First, go to nerdfonts.com and download the [Hack Nerd Font](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Hack.zip).  Then install the font onto your system.  Finally, restart Visual Studio and select "Hack Nerd Font Mono" for the Terminal font.
