### ISSUE TITLE
support for julia icons in UbuntuMono

### ISSUE THREAD

**Issue by AbhimanyuAryan** [ryanoasis/nerd-fonts#792]
Requesting support for Julia Icons for `UbuntuMono Nerd Font` using the font in `iTerm` `macOS` with [exa](https://the.exa.website/features/grid-view)

![Screenshot 2022-02-21 at 5 45 25 PM](https://user-images.githubusercontent.com/8083613/154953488-f71103b8-1373-4c29-bb61-0a260854a60f.png)

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/155952319-8fd93885-5fff-4579-85a0-b5dcbbf70035.png)

`exa` seems to support it on `u_E624`

And that is in our patch results... took from `HEAD`:

![image](https://user-images.githubusercontent.com/16012374/155952953-74da2f5a-16fb-4a73-8b6b-fc4ff5342112.png)

**Comment by AbhimanyuAryan** [comment]
Thanks for confirming. Any idea why it doesn't work in my case? How might I debug this? @Finii

**Comment by Finii** [comment]
Maybe your `exa` is not new enough?

![image](https://user-images.githubusercontent.com/16012374/155953593-775dc823-cbe0-4294-8a52-60eb0a1d09dc.png)

**Comment by Finii** [comment]
It's **not** in `exa` `v0.10.1` which is the newest release. So you probably need to self build.

**Comment by AbhimanyuAryan** [comment]
I'm using default one with homebrew

```shell
 ~  brew info exa
exa: stable 0.10.1 (bottled), HEAD
Modern replacement for 'ls'
https://the.exa.website
/opt/homebrew/Cellar/exa/0.10.1 (12 files, 1.3MB) *
  Poured from bottle on 2022-02-15 at 21:52:08
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/exa.rb
License: MIT
==> Dependencies
Build: pandoc ✘, rust ✘
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 5,396 (30 days), 17,904 (90 days), 74,838 (365 days)
install-on-request: 5,393 (30 days), 17,906 (90 days), 74,804 (365 days)
build-error: 1 (30 days)
```

Do you think I should uninstall this and install a specific version? If so which version?

**Comment by AbhimanyuAryan** [comment]
> .

aah missed this new reply. Do you think it's possible to build it with `brew`?

**Comment by Finii** [comment]
The trick did your report message. If you'd left out the link to the `exa` repo I would not have followed up :grimacing:, lazy me.

**Comment by AbhimanyuAryan** [comment]
thanks building from source worked. 

<img width="570" alt="Screenshot 2022-03-01 at 12 28 26 AM" src="https://user-images.githubusercontent.com/8083613/156042347-2f2b5f4e-b7e9-497b-907e-048ded5c52df.png">
