### ISSUE TITLE
Add Fantasque Sans Mono

### ISSUE THREAD

**Issue by davewongillies** [ryanoasis/nerd-fonts#80]
https://github.com/belluzj/fantasque-sans

**Comment by ryanoasis** [comment]
Nice I really like this font!

The idea of the "wibbly-wobbly handwriting" partly reminds me of Operator Mono... :smile: 

Thanks

**Comment by rosshadden** [comment]
:+1: I can't wait to use this project1  Just waiting for Fantasque support, which I see you added to the next milestone :smile:

**Comment by ryanoasis** [comment]
@rosshadden Thanks, yep next milestone (well next minor milestone)

**Comment by rosshadden** [comment]
Actually I'm using it now, by simply adding a patched Nerd font as a fallback font in my terminal, as suggested in some other issue here.  Great stuff!
