### ISSUE TITLE
FuraCode: why '...' is rendered as ' ?.' ?

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#800]
### Discussed in https://github.com/ryanoasis/nerd-fonts/discussions/799

<div type='discussions-op-text'>

<sup>Originally posted by **stark-zhang** March  1, 2022</sup>
as title said, the `...` is rendered as ` ?.`. Is it a bug? Or how to disable it?

Font:
 + `FuraCode NF` with "windows compatible"

Terminal:
 + Windows Terminal On Windows 10 20H2

Others:
 + bash 4.2 on CentOS 7
 + neovim 0.6.1
</div>

**Comment by chromatic-aberration** [comment]
I have the same issue with the FuraCode font from the release v2.1.0
![image](https://user-images.githubusercontent.com/45171340/157518088-c59ad7ec-aac3-4d7a-bec4-95f2618b9c41.png)
![image](https://user-images.githubusercontent.com/45171340/157518319-29a0870f-8efb-40e9-982a-bc8d40853a3d.png)

**Comment by Finii** [comment]
I can not reproduce, at least not with the 3 and a half tries I did so far.

The gif ... where do you type the dots into?

But maybe you can use https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC/FiraCode.zip instead?
Would be good to see if it will be fixed anyhow.

And then, in the v2.1.0 `FiraCode.zip`, there seem to be two sets of the same font (one times called `Fira` and one times called `Fura`, where `Fura` is older (11/2019 vs 01/2020).

On the other hand, we may not call the patched Fira `Fira`, and need to rename it to `Fura`. Seems broken.

**Comment by chromatic-aberration** [comment]
I've already switched to v2.2.0-RC FiraCode version and everything seems to be working great there so ill stick to that.

I've typed the dots into VScode, but for Windows Terminal, the behavior was the same.

**Comment by Finii** [comment]
Hoh!! I could reproduce...:

![image](https://user-images.githubusercontent.com/16012374/157526737-270b27de-1cea-479e-b037-13cc43257b3a.png)

Ubuntu 21.10, Writer, v2.1.0's `Fura Code Regular Nerd Font Complete Mono Windows Compatible.otf`

Interestingly it worked with other `Fura Code Regular`s?

**Comment by Finii** [comment]
> But I think, that since the v2.2.0 already seems to be fixing that issue, there probably is no reason to do anything about the older one.

Well, we can not change the old release, we can just issue a new one :->

And there the problem is fixed, probably by #711.

Will close this now, please reopen if need be.

**Comment by Finii** [comment]
Hmm, more ligatures are off, like `***` (3 asterisks) become `/*` (slash asterisk).

Then I examined the source `Fira` font (that was probably current then), and that works ok. Maybe the `fontforge` used back then had a bug :grimacing: :wink: 

I don't know. I stop here now ;)
