### ISSUE TITLE
Wrong glyphs displayed

### ISSUE THREAD

**Issue by gordonwinship** [ryanoasis/nerd-fonts#808]
Experienced behavior:

I installed the Hack Nerd Font. Before installation glyphs were displayed as empty boxes. After installing the font some glyphs are displayed incorrectly as Japanese or Chinese characters. Other glyphs are displayed correctly. This holds true for both alacritty and firefox.

Expected behavior:

Glyphs are displayed similar to the icons provided at https://www.nerdfonts.com/cheat-sheet .

Example symbols:

nf-mdi-function is not displayed correctly but instead rendered as a Japanese "ru" (s. screenshots). 

nf-mdi-onedrive is displayed correctly.

These examples are not exhaustive for either correctly or incorrectly displayed glyphs.

### Setup

- Using Hack Nerd Font Mono
- Hack Regular Nerd Font Complete.ttf
- The files were downloaded from: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf
- Terminal: alacritty
- OS: Linux (Pop!_Os 21.10, Gnome 40.5)

I installed the Hack Nerd Font via fc-cache
~$ fc-list | grep "Hack"                                                    
/home/user/.local/share/fonts/Hack Regular Nerd Font Complete.ttf: Hack Nerd Font:style=Regular
/home/user/.local/share/fonts/Hack Bold Italic Nerd Font Complete.ttf: Hack Nerd Font:style=Bold Italic
/home/user/.local/share/fonts/Hack Italic Nerd Font Complete Mono.ttf: Hack Nerd Font Mono:style=Italic
/home/user/.local/share/fonts/Hack Bold Nerd Font Complete Mono.ttf: Hack Nerd Font Mono:style=Bold
/home/user/.local/share/fonts/Hack Regular Nerd Font Complete Mono.ttf: Hack Nerd Font Mono:style=Regular
/home/user/.local/share/fonts/Hack Italic Nerd Font Complete.ttf: Hack Nerd Font:style=Italic
/home/user/.local/share/fonts/Hack Bold Nerd Font Complete.ttf: Hack Nerd Font:style=Bold
/home/user/.local/share/fonts/Hack Bold Italic Nerd Font Complete Mono.ttf: Hack Nerd Font Mono:style=Bold Italic

#### Screenshots
Instead of nf-mdi-function
![image](https://user-images.githubusercontent.com/47249134/158060252-955c2430-a541-4b93-8450-f4544f6f1d40.png)

the following character is displayed

![image](https://user-images.githubusercontent.com/47249134/158060345-fdb869eb-bde5-4398-ac02-e28e8b3693c8.png)

**Comment by Finii** [comment]
All mandatory fields from `New Issue` -> `Bug report` missing.

**Comment by gordonwinship** [comment]
> All mandatory fields from `New Issue` -> `Bug report` missing.

Fixed the issue description.

**Comment by Finii** [comment]
For some reason I can not run `alacritty` on two Ubuntu machines I tried. The snap (I hate snaps) seems broken or whatever.

It is in the font at codepoint `F794`:

![image](https://user-images.githubusercontent.com/16012374/158160006-5dc9217c-fb96-4b5a-a907-386245c90e1a.png)

Can you copy and paste the wrong glyph into a comment window and/or give the codepoint you use?

**Comment by Finii** [comment]
Katakana RU should be at `30EB`, this does not make sense. (or `31FD`, `FF99`)

Did you try entering the code manually, like `SHIFT` + `CTRL` + `U`, `F`, `7`, `9`, `4`, `ENTER` ?

**Comment by gordonwinship** [comment]
The codepoint is F794
the glyph is: 
Manually entering the code yields the same result.

**Comment by gordonwinship** [comment]
The problem regarding firefox displaying glyphs incorrectly no longer exists after rebooting the machine. Alacritty, however, still behaves the same.

**Comment by gordonwinship** [comment]
I just checked a few other glyphs. All glyphs from F700 to F740 don't seem to work. Similarly F579-653 is not displayed correctly. Potentially there exist more intervalls.

**Comment by Finii** [comment]
Self-built alacritty, how do I select the font :grimacing: 

![image](https://user-images.githubusercontent.com/16012374/158165544-99314742-6b75-4f6a-a0d6-5bbe833a5867.png)

**Comment by Finii** [comment]
After your comment I guess it (alacritty) might depend on charset settings in the font file, which is ... wrong.

**Comment by gordonwinship** [comment]
The font is set in the alacritty.yml file
font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic
  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic
  size: 14.0

**Comment by gordonwinship** [comment]
Alright, I guess I found the culprit. In the alacritty file I called "font:" a second time to set the size. This apparently reset the font family. Because I had Hack as default font system-wide the text looked exactly the same, but glyphs weren't working.

**Comment by gordonwinship** [comment]
Thank you very much for your patience!

**Comment by Finii** [comment]
:tada: Great

Glad it work for you now. I just also found the font setting stuff... feels like back in 1990 or so, when ppl hat do edit X resources :grimacing:

**Comment by Finii** [comment]
> called "font:" a second time to set the size

Hmm, as commandline options this works:

```
fini@Ryzen:~/git/alacritty$ ./target/release/alacritty -o "font.normal.family=CaskaydiaCovePL Nerd Font" -o font.normal.style=Regular -o font.size=24
```

Despite `font.` being in there multiple times. \*shrug\*
