### ISSUE TITLE
Victor Mono semibold is missing some icons

### ISSUE THREAD

**Issue by mrjones2014** [ryanoasis/nerd-fonts#809]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Only the "SemiBold" variant is missing some icons

Expected behavior:
SemiBold should have all the same icons

Example symbols:
```
⇣
```

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Victor Mono SemiBold Nerd Font Complete.ttf
   - Installed via Homebrew
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ Kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ OS X

#### ★ Screenshots (Optional)

Victor Mono SemiBold:

![CleanShot-2022-03-18-at-12 58 23](https://user-images.githubusercontent.com/8648891/159048504-430fc459-929a-43c5-8c63-0a87bb84eaa7.png)

Victor Mono:

![CleanShot-2022-03-18-at-12 58 59](https://user-images.githubusercontent.com/8648891/159048572-b2f3badc-d9bf-42d1-9a42-90617dc6e3e3.png)

Victor Mono Bold:

![CleanShot-2022-03-18-at-12 59 15](https://user-images.githubusercontent.com/8648891/159048635-e222e246-b25a-4af1-87d0-49ab457cc342.png)

**Comment by mrjones2014** [comment]
Same issue for the "Medium" variant.

**Comment by Finii** [comment]
I guess you mean this?

![image](https://user-images.githubusercontent.com/16012374/159058819-9ce848c2-24d5-493e-b4d8-f5cdeea85ddb.png)

This is not a glyph that Nerd Fonts patches in. If it's there or not depends on the original font.

**Comment by mrjones2014** [comment]
dang. guess it's time to pick a new font for the hundredth time :/

**Comment by Finii** [comment]
Or just patch it in yourselves? It's not really hard.

**Comment by Finii** [comment]
Like, just from the top of my head with, approximately

```python
import fontforge

source = fontforge.open('BlahblahBOLD.ttf')
target = fontforge.open('BlahblahMEDIUM.ttf')

source.selection.select(0x21e3)
source.copy()
target.selection.select(0x21e3)
target.paste()

target.generate('new name')
```

**Comment by mrjones2014** [comment]
Oh sick. I might just do that.
