### ISSUE TITLE
Add Iosevka programming font

### ISSUE THREAD

**Issue by aternummus** [ryanoasis/nerd-fonts#81]
Hi Ryan, 
this is the suggested reminder ;-)
PLEASE work your magic on the Iosevka font familiy:
https://github.com/be5invis/Iosevka

**Comment by ryanoasis** [comment]
Yep thanks for creating an issue. I'll aim for next release. Cheers :smile:

**Comment by be5invis** [comment]
There are some very low-level operations are performed when building Iosevka (like forcing a `OS/2.xCharWidth` and adding a `DSIG`), I'm not sure whether this patching script can preserve this.
Perhaps you can checkout [otfcc](https://github.com/caryll/otfcc), which is used to build the fonts with direct control (and optimizations).

**Comment by ryanoasis** [comment]
@be5invis Thanks for chiming in :smile: 

I appreciate your feedback and warnings. :+1: 

I will have to look more into it but I think FontForge can only provide a 'dummy' `DSIG` which I only currently understand to provide Windows compatibility.

You are right possibly the current patch script can't do a complete job and given your feedback maybe it is best to link to a new issue with the items you mentioned from the readme (we did [something similar with Hack](https://github.com/ryanoasis/nerd-fonts/commit/081fe333436c5cc739add5fbb2da64edc2e8d575?short_path=0730bb7#diff-0730bb7c2e8f9ea2438b52e419dd86c9) linking to #70).

Overall I am pretty naive about the points you mentioned, so unless you are highly against us patching your font I will move forward. Please let me know either wary :blush: 

--

Side note: I am really liking the look of Iosevka so far and will be giving it a test run in my editor for a while. :smile:

**Comment by be5invis** [comment]
@ryanoasis A patching proposal:

1. Dump Iosevka and your symbol font (as .ttf, without Powerline symbols) into JSON using `otfccdump`.
2. Write a program to merge them. Two main tables: `cmap` and `glyf` should be dealed with. (I do not think that this symbol font has OpenType features. If so, OpenType-related tables should be also merged.)
3. (optional) Re-hint it using `ttfautohint`
4. Build a patched font using `otfccbuild --keep-average-char-width --ship`.

**Comment by ryanoasis** [comment]
@be5invis Hey thanks a lot. I will seriously consider drastically changing certain build processes. I am going to open a separate ticket however since this one will be closed for [0.8.0 release](https://github.com/ryanoasis/nerd-fonts/milestones/v0.8.0)

**Comment by be5invis** [comment]
@ryanoasis Opened #83

**Comment by ryanoasis** [comment]
@be5invis Great, perfect. Thanks
