### ISSUE TITLE
Cascadia Code: Cyrillic letters look ugly

### ISSUE THREAD

**Issue by valery-kirichenko** [ryanoasis/nerd-fonts#810]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful

- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Cyrillic letters in Caskaydia Cove have inconsistent size and are thin in the Windows Terminal

Expected behavior:
Cyrillic letters the same as in Cascadia Code

Example symbols:
АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Caskaydia Cove Nerd Font Complete Windows Compatible.ttf
   - Download link
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ Windows Terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Windows 10 21H2

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/3050013/159139229-83cdbb24-a581-44a6-8b45-78eeb7ce530e.png)

**Comment by Finii** [comment]
> *    Caskaydia Cove Nerd Font Complete Windows Compatible.ttf
> *    Download link

Unfortunately we have too many 'download links' that point to different version.

Maybe you downloaded the Release 2.1.0 Files, from https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.1.0
That release is from Feb 2020 based on Cascadia Code 1909.16., but Cyrillic has been added to Cascadia only later: https://github.com/microsoft/cascadia-code/releases/tag/v1911.20

Please try release candidate 2.2.0: https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC/CascadiaCode.zip
That is based on Cascadia Code 2007.1, and you should have no problems.

An even more up-to-date Cascadia Code patch (based on 2111.01) can be found ... I guess I need to reupload it.

**Comment by Finii** [comment]
> An even more up-to-date Cascadia Code patch (based on 2111.01) can be found ... I guess I need to reupload it.

We are lucky, it's still there:
https://github.com/Finii/nerd-fonts/tree/feature/cascadia-2111.01-patched/patched-fonts/CascadiaCode

**Comment by valery-kirichenko** [comment]
2111.01 works fine.
It's a bit weird that I got the same result after patching it myself but maybe I was doing something wrong :)

**Comment by Finii** [comment]
Glad it works for you.

Did you try the 2.2.0 RC and it did not work?

**Comment by valery-kirichenko** [comment]
Yep, RC also looks good

**Comment by Finii** [comment]
Thanks!

Otherwise we would have to do something with the RC. But if the RC is ok I guess this Issue can be closed.
