### ISSUE TITLE
 Icon not show question

### ISSUE THREAD

**Issue by reaink** [ryanoasis/nerd-fonts#812]
#### 🗹 Requirements

![image](https://user-images.githubusercontent.com/45023042/159839473-ba145b42-94b9-49a9-8677-0b8fd7da4918.png)
This icon does not always show up properly here.
Iterm2, Jetbrains Nerd font that I use. 

 Telescope search icon is not shown either.
![image](https://user-images.githubusercontent.com/45023042/159839559-7884e157-948e-4e93-af3b-06be00d19c2f.png)

**Comment by Finii** [comment]
Unfortunately you did not fill the whole Issue report form.

Here I can not see which icons are missing. At least we would need a copy-and-paste text into a comment.
If they are in the Nerd Font icon set the other question is which version does the font have you use?
And where did you acquire it from (probably homebrew, if you are on mac?)

As this is already a year old and propably solved I close this now. But do not hesitate to reopen with more details if you still have problems!
