### ISSUE TITLE
Material Design Lambda Icon renders text right-to-left

### ISSUE THREAD

**Issue by jessicah** [ryanoasis/nerd-fonts#813]
#### 🎯 Material Design Lambda Icon triggers right-to-left text input

Experienced behavior:
Text input switches to right-to-left behaviour

Expected behavior:
Text input remains in left-to-right mode

Example symbols:
U+FB26

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ Operator Mono XLight Nerd Font
   - _Please give the full filename_ Operator Mono XLight Nerd Font Mono.otf
   - _Where did you get the file from (download link, self patched, source downloaded from link...)_ self patched
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ PuTTY
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Windows 10

#### ★ Screenshots (Optional)

Seems that would need #365 to be resolved to fix, but adding as a tracking issue if it gets resolved.

**Comment by Finii** [comment]
Will be solved after the glyph moved to its new location, i.e. `v3.0.0`

**Comment by Finii** [comment]
Release is in repo, release as packages pending.
