### ISSUE TITLE
add font  support Chinese 

### ISSUE THREAD

**Issue by bestv5** [ryanoasis/nerd-fonts#814]
**Requirements**

I hope  can add some fonts   support Chinese

**Comment by Finii** [comment]
Maybe you can explain a bit more what you hope for?

I have no experience with Chinese glyphs, but I guess most fonts have only latin letters, some have cyrillic additionally, few have more.
If you have a nice (Chinese) font where you would like to have all the icons and symbols added to it, that can probably be done. I believe there are some Google-`Noto` fonts. But I guess you need a 'westener' font installed and used in parallel anyhow?

Sorry, would need more input. What you use, how you use it, what you expect, ... :-)

**Comment by bestv5** [comment]
@Finii 
 Microsoft yaheihe or JetBrains Mono  is just an example. You can maintain several license free Chinese fonts and make them into nerd font.
In fact, I want an equal width font for programming, which supports both Chinese and symbols。

**Comment by kix99aug** [comment]
你好 偶然看到這個Issue
若你是想要已經打好補釘的中文字體
這邊有個Repe是我自己已經使用很久的
https://github.com/tsunesan3/awsome-jp-coding-fonts
雖然是作者是日本人 但像是NasuM這個字體是使用思源黑體衍生字體修改而來
故有著與思源黑體一樣的中文字覆蓋度（當然有些字會變成日文漢字慣用寫法，但我覺得無傷大雅）

---

This repo contains a lot of nerd fonts pathched CJK fonts, which I've used for a long time.
https://github.com/tsunesan3/awsome-jp-coding-fonts

**Comment by cloud-yu** [comment]
可以看看Sarasa字体，作者提供了支持英文和中文字符同时还能完美保证等宽。

**Comment by Finii** [comment]
> 可以看看Sarasa字体，作者提供了支持英文和中文字符同时还能完美保证等宽。

Translate:
You can take a look at the Sarasa font. The author provides support for English and Chinese characters and can perfectly guarantee equal width.
