### ISSUE TITLE
ShareTechMono fi ligature telephone

### ISSUE THREAD

**Issue by catbabylon** [ryanoasis/nerd-fonts#817]
Hi I've just installed ShareTechMono-NF-Mono via Scoop on windows and noticed in Powershell, when I type the letters f and i with no space, they are replaced by an icon of a telephone.

If I change to any other nerd font, the issue goes away.

**Comment by catbabylon** [comment]
Ah OK thanks, they are on 2.1.0 so I'll just hang on for it to update and use a different font in the meantime.

Everything about scoop is at https://scoop.sh/ and https://github.com/ScoopInstaller/Scoop . There is a scoop bucket specifically for nerd fonts: 
https://github.com/matthewjberger/scoop-nerd-fonts  which I presume updates directly from here.

**Comment by Finii** [comment]
Ah, yes, they [download a fixed release](https://github.com/matthewjberger/scoop-nerd-fonts/blob/master/bucket/ShareTechMono-NF-Mono.json):

```json
{
    "version": "2.1.0",
    "license": "MIT",
    "homepage": "https://github.com/ryanoasis/nerd-fonts",
    "url": "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/ShareTechMono.zip",
    "hash": "99b7f0cf4de6446ffdb8bf5ae19b2b95f38ca56eee658677f672f80abcafe9c0",
```

I guess I never understood why people want a 'meta installer' for fonts. Usually I just download the`zip`, unpack it and double click on the fonts to install them. But then, I usually buy fonts and that naturally limits the amount of fonts. On the other hand, who wants the system cluttered with hideous amounts of fonts that makes selection a burden? Using a font manager to limits the amount of installed fonts _per project_ :grimacing: 

Who would use the 'install all nerd fonts that there are' script in this repo.

Just musing :-D

So my tip ... just download the v2.2.0 ShareTech zip file, and the double-click install the fonts you want (i.e. `Windows compatble`). This is just 1 and a half click more than using scoop.

**Comment by Finii** [comment]
Hmm, did you reboot after deinstallation?
The font installation stuff on Windows is a mystery for me. I never needed to reboot after uninstall but some ppl claim they need to (to clear the font cache or something?).

If that does not help I can retry on my Windows VM.

**Comment by catbabylon** [comment]
Yeah double checked the scoop versions are gone, removed the 2.2.0, rebooted, reinstalled 2.2.0 still got the issue.

**Comment by catbabylon** [comment]
however, the version here works...

https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/ShareTechMono/complete/Shure%20Tech%20Mono%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf

**Comment by Finii** [comment]
This is strange....

```
mkdir tmp
cd tmp
curl -LO https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/ShareTechMono/complete/Shure%20Tech%20Mono%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf
curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC/ShareTechMono.zip
unzip *.zip
cmp *Complete*Mono*Windows*.ttf
ll *Complete*Mono*Windows*.ttf
```

![image](https://user-images.githubusercontent.com/16012374/162208245-8ee3de0e-36b7-4945-85ed-80390fa54df6.png)

WAT?! The RC should always be the same as the current HEAD files? Will investigate.

**Comment by Finii** [comment]
Solved in release
