### ISSUE TITLE
Unable (or not obvious) to install a font through brew

### ISSUE THREAD

**Issue by CyborTronik** [ryanoasis/nerd-fonts#819]
I've tried to install Meslo font through brew and got: 
```
brew tap homebrew/cask-fonts && brew install --cask font-meslo-nerd-font                                   in bash at 15:50:05
Error: Cask 'font-meslo-nerd-font' is unavailable: No Cask with this name exists.

```
Also it's quite easy to missuse it - would be cool to have a command that install all the fonts at once via a package manager (brew/pip or similar).

**Comment by Finii** [comment]
Is that not rather an issue of https://github.com/Homebrew/homebrew-cask-fonts ?

Maybe you should use one of the existing ones:
![image](https://user-images.githubusercontent.com/16012374/162625210-bc4544ed-e0f2-4c23-91f2-f1e473c034c3.png)

_Remarks:_
* _I do not use brew, whatever that is, it does not work on Linux I believe ;)_
* _I also can not understand why people want to install hundredth of fonts they never need_

**Comment by CyborTronik** [comment]
Then looks like docs shall be update. So the natural experience is that you copy/paste the name of the font name from the site and try it to install. Currently is not described that there is a difference in names and you have to lookup for them

**Comment by Finii** [comment]
> Then looks like docs shall be update.

Can you point me to the exact sport where the (our) docs are wrong/misleading/incomplete?

What do you think should be added? `brew search meslo`, i.e. `brew search font-name-here`? Is that not obvious for brew users?

**Comment by airtonix** [comment]
I mean instead of making us run around and find the magical package name... if you're the team that creates these artifacts, chooses the brew package name under which to upload them, then surely you could just tell us what the actual package name is.

**Comment by airtonix** [comment]
so it's not obvious at all that to install the FiraCode font with these instructions: 

```
brew tap homebrew/cask-fonts &&
brew install --cask font-<FONTNAME>-nerd-font
```

that you need to : 

1. scroll up the page
2. work out what human name the nerd font team have decided to call the font
3. magically know that you need to change FiraCode to `fira-code` 
4. run the above template.

👎🏻

**Comment by Finii** [comment]
You sound not satisfied, which is sad. But do you need to lash out at other people that merely try to help?

Whatever, to keep the facts straight, consider this
* I do not use `brew`
* Although I neither use nor care about `brew` I try to help people that seem to depend on it to use it
* For them we have documentation here, but that can obviously be improved

So my 'strange' questions are for `brew` users to tell me what could help them to use `brew` in relation to Nerd Fonts.

So instead of spitting out insults you could dedicate your time to other fellow `brew` users, formulate a proposal for a documentation improvement (maybe in form of a PR), and thus spread your knowledge and keep friendly.

 ¯\\\_(ツ)_/¯

**Comment by Finii** [comment]
> magically know that you need to change FiraCode to `fira-code`

Do you think it is easy enough to grasp if we add the brew name as one bullet point here:

![image](https://user-images.githubusercontent.com/16012374/204469574-3e9d9ddb-508c-487c-8e89-630293d1a248.png)

And maybe change the instruction in the bottom a bit (maybe you have a suggestion)?

**Comment by Finii** [comment]
Or is it better to have a 'dedicated page' with just all the cask names?

**Comment by Finii** [comment]
Hmm, no reply.

Anyhow, I simple search in `brew` could be expected, no?

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/16012374/220910790-e0db5394-76af-403a-ac43-286436902e6c.png">
