### ISSUE TITLE
whitspace-mode issue when using CaskaydiaCove Nerd Font Mono in Emacs

### ISSUE THREAD

**Issue by c02y** [ryanoasis/nerd-fonts#826]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

When I use `CaskaydiaCove Nerd Font Mono` in `emacs -q --no-splash` using 
```
(set-face-attribute 'default nil :font "CaskaydiaCove Nerd Font Mono" :height 150)
```
then open a buffer, `M-x whitespace-mode` for the buffer, the whitespace of space is narrower than turning `whitespace-mode` off, so the whole text will be moved to the left a little bit, check the screenshot.

If I install the original cascadia-code font (`ttf-cascadia-code` package for Archlinux), use the same `(set-face-attribute 'default nil :font "CaskaydiaCove Nerd Font Mono" :height 150)` line for Emacs, it works fine, so weird, use `(set-face-attribute 'default nil :font "Cascadia Mono PL" :height 150)` works fine too.

Expected behavior:

the whitespace of space should look normal.

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - `CaskaydiaCove Nerd Font Mono`
   - `nerd-fonts-cascadia-code 2.1.0-4` package for Archlinux
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)? `emacs -q --no-splash`
- _Are you using OS X, Linux or Windows? And which specific version or distribution? `Archlinux`

#### ★ Screenshots (Optional)
1. Normal spaces:
![2022-04-25_05-40](https://user-images.githubusercontent.com/2135996/164997890-1eaddd4e-099f-46bf-b218-15971fd917a4.png)

2. `(set-face-attribute 'default nil :font "CaskaydiaCove Nerd Font Mono" :height 150)` without installing `ttf-cascadia-code` which is original cascadia-code font, and turn on whitespace-mode
![2022-04-25_05-47](https://user-images.githubusercontent.com/2135996/164998098-0b9433b9-0ede-487b-8889-8f8e4727686f.png)
3. `(set-face-attribute 'default nil :font "CaskaydiaCove Nerd Font Mono" :height 150)` with `ttf-cascadia-code` which is original cascadia-code font installed (or use `(set-face-attribute 'default nil :font "Cascadia Mono PL" :height 150)` ), and turn on whitespace-mode
![2022-04-25_05-44](https://user-images.githubusercontent.com/2135996/164998108-0d1641e6-d293-4645-bf3e-836a250b6c24.png)

**Comment by Finii** [comment]
I am not sure this was tackled by any of the fixed that came with `v3.0.0`, but maybe you can check if this is still an issue or can be closed.
Note the the latest Caskaydia package has `ttf` fonts now (like the Cascadia package), before we had `otf`s. That `otf-` package still exists at version 2.3.3, do not use that, use the Arch `ttf-` v 3.0.0 package.

And if this is still an issue... `emacs` has its own terminal emulator now? Years ago it was a normal command line application you needed to start within a terminal, and in that case that would not be an `emacs` but a problem of that (unspecified by you) terminal... Hmm.

**Comment by Finii** [comment]
> `nerd-fonts-cascadia-code 2.1.0-4`

Uuuh, that is very very old, pleas try https://archlinux.org/packages/community/any/ttf-cascadia-code-nerd/

**Comment by c02y** [comment]
Although I don't use Cascadia-code or CaskaydiaCove anymore, `ttf-cascadia-code-nerd 3.0.0-2` works fine, thanks.

**Comment by Finii** [comment]
Thank you for trying and reporting :-)
