### ISSUE TITLE
CaskaydiaCove Font Does not Include Any Accent Characters

### ISSUE THREAD

**Issue by manuth** [ryanoasis/nerd-fonts#828]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
The CaskaydiaCove Font linked in the [release 2.1.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.1.0) doesn't contain German umlauts.

Expected behavior:
The CaskaydiaCove Font should contain German umlauts as the original Cascadia Code Font does contain them.
Furthermore, running `fontforge -script font-patcher src/unpatched-fonts/CascadiaCode/Regular/CascadiaCode-Regular.otf -c --mono --out .` generates a font which contains German umlauts as well.

Example symbols:
German Umlauts are affected.
However, I'm not sure whether there are more accent characters which are affected.

  - German umlauts
    `äöü`

Update: *All* accent characters are missing

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - Caskaydia Cove Regular Nerd Font Complete Mono
   - _Where did you get the file from (download link, self patched, source downloaded from link...)_
     - This repo's v2.1.0 download: https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.1.0
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
  - Windows Terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
  - Windows

#### ★ Screenshots (Optional)
![image](https://user-images.githubusercontent.com/7085564/165894592-ab97638b-7297-41c5-9b86-a3a1939689ca.png)
**Ordinary characters compared to their accent counterparts**

![image](https://user-images.githubusercontent.com/7085564/165895499-b63a384d-e7d8-4c4e-92d4-eda111dee8ec.png)
**The same in Windows Terminal**

**Comment by Finii** [comment]
As expected this is fixed in `2.2.0`.

If interested in Cascadia, maybe #723 is useful, which's artifacts can be found here: https://github.com/Finii/nerd-fonts/tree/feature/cascadia-2111.01-patched/patched-fonts/CascadiaCode

Thanks for the report!
I close this, because it has already been addressed (and the 2.1.0 release will not be changed retroactively).

**Comment by Finii** [comment]
Btw, technically, `Cascadia` constructs the umlauts by overlaying the base glyph with the two-dots-only-glyph. Well the font rendering engine has to do that.
This is different from more simple fonts that have a dedicated single glyph for umlauts etc.

**Comment by manuth** [comment]
> As expected this is fixed in `2.2.0`.
> 
> If interested in Cascadia, maybe #723 is useful, which's artifacts can be found here: https://github.com/Finii/nerd-fonts/tree/feature/cascadia-2111.01-patched/patched-fonts/CascadiaCode
> 
> Thanks for the report! I close this, because it has already been addressed (and the 2.1.0 release will not be changed retroactively).

I btw just tried your patched font and it's working out great 😄 

I just noticed, that the circular powerline character is off by 1 pixel - this is the case for the 2111.01 patch, the CaskaydiaCove font in the 2.1.0 package and the one produced using the workaround I've posted:

![image](https://user-images.githubusercontent.com/7085564/165911092-0fd96406-8d8a-4402-b6a3-95dc77149eaf.png)

@Finii is this something worth reporting?

**Comment by Finii** [comment]
I will look into that maybe today afternoon.
Some PR comes to my mind, hmm, searching

**Comment by Finii** [comment]
Hmm. If you are bored you could try #761, as that fixes some font rendering engine internal rounding errors.
But I'm not sure that is really related. If it would be related also other sizes like 9 pt or so should have problems.
So ... will try to find time in the afternoon and fire up my Windows VM ;)

**Comment by manuth** [comment]
Thanks - I was quite bored during the last few minutes, so I just gave it a go 😂 
Didn't work - it's just a 1px gap... but even though, I just can't manage to unsee it

Thanks for your great support tho 😄

**Comment by Finii** [comment]
Finally came round to simulate your prompt:

![image](https://user-images.githubusercontent.com/16012374/166409492-6441583e-8529-4989-8369-4dd998a5da6a.png)

This is 16 pt. `Caskaydia Cove NF`. Lets see 12 pt:

![image](https://user-images.githubusercontent.com/16012374/166409733-89e892ad-74e9-4e18-94db-44cebf2a7762.png)

At 400%:

![image](https://user-images.githubusercontent.com/16012374/166409917-9e038f97-4059-4896-92e1-eefbf22e8c5f.png)

GAP! ... I have no clue which Caskaydia it is lets check...

**Comment by Finii** [comment]
I guess the screenshots are not exact enough, because I connect to the Windows Box via RDP and take the screenshot on my side of the connection - instead directly on the Windows side. RDP is anyhow bad for this, because the 'simulated graphics card' lacks some enhanced features iirc. Let's compare a Windows scrrenshot at 400%:

![image](https://user-images.githubusercontent.com/16012374/166410736-53f69b0b-20a9-4fbf-8a99-598422bc74ae.png)

Looks better, but still not nice ;)

**Comment by Finii** [comment]
Ok, the font I have installed is really one with a smaller round symbol.
Need to dig out the font I suggested for you :->

**Comment by manuth** [comment]
> I guess the screenshots are not exact enough, because I connect to the Windows Box via RDP and take the screenshot on my side of the connection - instead directly on the Windows side. RDP is anyhow bad for this, because the 'simulated graphics card' lacks some enhanced features iirc. Let's compare a Windows scrrenshot at 400%:
> 
> ![image](https://user-images.githubusercontent.com/16012374/166410736-53f69b0b-20a9-4fbf-8a99-598422bc74ae.png)
> 
> Looks better, but still not nice ;)

The second one (the one you took on the remote side) looks more similar to what. I see on my 1080p monitor.

That said, the Screenshots I took in this issue have all been taken on a 4k monitor (with scaling in the Windows settings set to 200%)

Do you think such an issue exists already or is it safe to create a new one?
I couldn't find any issues related to Powerline characters in CaskaydiaCove.

Thanks for all your effort, that's awesome 😄

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/166421606-0a84cdb7-37b2-4ad7-b8c3-158046270e62.png)

This is a font patched with #780 from the Cascadia Code 2111.01

Looks still a bit too low on the left round thing.

But in fact, I think the step is also there with the triangular things:

![image](https://user-images.githubusercontent.com/16012374/166421928-bbe88d71-1e75-4cca-9915-37d617b58510.png)

The upper diagonal does not really come to the corner.

Terminal seems to detect the box height differently, lets see.

**Comment by Finii** [comment]
Added as a test the `E0D2` glyph, and it indeed is not as high as the box that Terminal assumes:

![image](https://user-images.githubusercontent.com/16012374/166428904-6b221327-18e1-412e-ac80-248ccbf35aab.png)

I.e. all powerline glyphs have the same size, but the inverted-blank is bigger.

**Comment by Finii** [comment]
Hmm.

This here is the SAME image from above, but with 48 pt and at 500%.
There is no height problem visible.

![image](https://user-images.githubusercontent.com/16012374/166437724-bd9b3b1b-e5a4-4c69-8397-a3fb498f8c4b.png)

Seems to be a small rendering problem only. I fear that it is a `Windows Terminal` bug, but will check the font flags now.

```
Dumping File:/home/fini/Downloads/ttf/static/CascadiaCode-Regular.ttf

'head' Table - Font Header
--------------------------
	 'head' version:	 1.0
	 fontReversion:		 2111.0
	 checkSumAdjustment:	 0x6b356b07
	 magicNumber:		 0x5f0f3cf5
	 flags:			 0x0007
	 unitsPerEm:		 2048
	 created:		 0x00000000d8cfe165
	 modified:		 0x00000000dddd63fd
	 xMin:			 -980
	 yMin:			 -989
	 xMax:			 4520
	 yMax:			 2304
	 macStyle bits:		 0x0000
	 lowestRecPPEM:		 6
	 fontDirectionHint:	 2
	 indexToLocFormat:	 1
	 glyphDataFormat:	 0
```
```
Dumping File:Caskaydia Cove Regular Nerd Font Complete Windows Compatible.ttf

'head' Table - Font Header
--------------------------
	 'head' version:	 1.0
	 fontReversion:		 2111.0
	 checkSumAdjustment:	 0x9af17c2b
	 magicNumber:		 0x5f0f3cf5
	 flags:			 0x001f
	 unitsPerEm:		 2048
	 created:		 0x00000000d8cfe165
	 modified:		 0x00000000de96ab57
	 xMin:			 -1877
	 yMin:			 -989
	 xMax:			 4520
	 yMax:			 2304
	 macStyle bits:		 0x0000
	 lowestRecPPEM:		 8
	 fontDirectionHint:	 2
	 indexToLocFormat:	 1
	 glyphDataFormat:	 0
```

Hmm, PPEM and flags differ, lets see if #761 fixes it.

**Comment by Finii** [comment]
`showttf` decodes the flags for us (above I used `ttfdump`):

         flags=7  baseline_at_0 lsb_at_0 instrs_depend_on_size
         flags=1f baseline_at_0 lsb_at_0 instrs_depend_on_size ppem_to_int instr_set_width

**Comment by Finii** [comment]
Not really a change:
![image](https://user-images.githubusercontent.com/16012374/166439937-a6807224-278a-4a5b-b781-34883edd01bc.png)

(12pt at 400%)

I must admit I have no clue. This is probably a `Windows Terminal` problem; maybe raise an Issue there.

**Comment by Finii** [comment]
Btw, I **see** the step in the prompt, but not always. If I move the terminal window around, sometimes it looks smooth, sometimes not. The reason could be RDP, or antialiasing, or the font rendering engine, or ...

**Comment by Finii** [comment]
I don't want to link the `Windows Terminal`-issues, but these are two I found that are not related but somehow similar-ish enough:

https://github.com/microsoft/terminal/issues/

* Some of the extended Unicode characters are rendered with incorrect size and placement **6738**
* Remember to have block and line drawing characters fill their cells properly **455** (further down after closing)
* 1px line between powerline glyphs **8993** (we also always fight with these)

Maybe even your issue is already there ;)

**Comment by manuth** [comment]
Thanks for the research, I'll have a look at these 😄

**Comment by Finii** [comment]
Interestingly it also happens with Microsoft's own Powerline implementation:

![image](https://user-images.githubusercontent.com/16012374/166443179-ae0067df-779e-4259-bc3c-e96d6edb0bc2.png)
_(Cascadia Code PL static ttf, 12 pt)_

Worth to mention this in a possible issue report over there.
Did not try the VF version, though.

**Comment by Finii** [comment]
:sob: 

When using their static `otf` instead of the `ttf` we get a variation of the bug...

![image](https://user-images.githubusercontent.com/16012374/166443871-2b489e6f-db14-436b-a026-94c7cbbdfc95.png)

At least that solves the issue 'top of powerline glyph has a step' :grimacing:

**Comment by Finii** [comment]
Lets see what they come up with :-)

**Comment by manuth** [comment]
Thanks for looking it up 😄

**Comment by manuth** [comment]
> Fixed windows Terminal has just been released.
> See closed issue there that is shown some comments up. 

I can confirm it's working
Thank you very much for keeping me updated 😄
