### ISSUE TITLE
otfcc-driven patching workflow

### ISSUE THREAD

**Issue by be5invis** [ryanoasis/nerd-fonts#83]
Given that some of the programming fonts (like [Iosevka](https://github.com/be5invis/Iosevka)) may contain special metadata to achieve some special targets (like being used within Windows console window). Therefore the current patching script (using FontForge) may not be appropriate since FontForge cannot generate a font with such specialized data. A replacement used for patching may be involved with [otfcc](https://github.com/caryll/otfcc), which is a high-performance font manipulator dumps a font into JSON, and vice versa.

We can investigate an alternative patching script using otfcc, to create a “special-data-preserving” font patching workflow.

---

**PROPOSAL**
1. Dump `<target.ttf>` into JSON `<target.otd>` using `otfccdump`.
2. Build a `<patch.ttf>` containing Nerd symbols matching `<target.otd>`’s `head.unitsPerEm`.
3. Dump `<patch.ttf>` into JSON `<patch.otd>` with glyph names prefixed.
4. Merge `<patch.otd>` into `<target.otd>` (using some script. Python?), with the following tables merged:
   - `cmap`
   - `glyf`
5. Build `<product.ttf>` from `<target.otd>` using `otfccbuild` with `--keep-average-char-width` and `--ship` options.
6. (optional) Autohint `<product.ttf>` with `ttfautohint`.

**Comment by be5invis** [comment]
@ryanoasis I've made a sample code using Node.js and otfcc: [nerdpatcher.7z](http://7xpe0v.com1.z0.glb.clouddn.com/nerdpatcher.7z)
The `nerd.ttf` is a TrueType font matching the target font's upm. The current patching script simply drops the hints of the Nerd part. You can re-hint it using ttfautohint after the patched `.ttf` is created.

**Comment by ryanoasis** [comment]
@be5invis I really appreciate all this thanks. Not sure when I will get around to trying it out but I want to! :+1:

**Comment by be5invis** [comment]
ps. I suggest that the name of the patched font is “Imposevka” :ghost: 
Means “Io<u>sevka</u> with <u>impo</u>rted glyphs”

**Comment by ryanoasis** [comment]
@be5invis Good idea and that is a pretty clever name :smile: 

I will update the name in the next release (the otfcc patching ... probably will not be soon though :blush:).

---

Are you wanting or saying you are Reserving the **Iosevka** name ?

I did not see the typical 'Reserved Font Name' declaration in the [Iosevka License](https://github.com/be5invis/Iosevka/blob/master/LICENSE) even though the license is **SIL OFL** like I typically do on **OFL** licensed fonts (e.g. [Hack License](https://github.com/chrissimpkins/Hack/blob/master/LICENSE.md))

Maybe you want to add that to the license (unless I am behind or misunderstanding the license)?

source: http://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#9d7a93f7

**Comment by be5invis** [comment]
@ryanoasis I thought that name reservation does not need to declare it explicitly in LICENSE. :cry: 
It is now added.

**Comment by ryanoasis** [comment]
Heh that is what I wasn't exactly sure about either but it *sounds* like it from what I was reading. Either way I would have done the name change as it is **your** font after all :wink:

**Comment by be5invis** [comment]
My suggested patching workflow is to use the script in my previous comment, which preserves all “good” properties of Iosevka. Perhaps you can create a ttf with only NERD glyphs, and set upm to 1000, and char width to 500.

**Comment by ryanoasis** [comment]
Ah here we go:

related: [5.6](http://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#cbd32a36)

per [5.7](http://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#caa50365)
> 
> Question: 5.7 Are any names (such as the main font name) reserved by default?
> 
> Answer: No. That is a change to the license as of version 1.1. If you want any names to be Reserved Font Names, they must be specified after the copyright statement(s).

**Comment by be5invis** [comment]
@ryanoasis I've added the declaration into `LICENSE.md`.

**Comment by ryanoasis** [comment]
Thanks for the info on the ttf i'll give that a try sometime

**Comment by be5invis** [comment]
@ryanoasis I’ve made a full script to build Imposevka, and sample fonts built from the latest 1.9.0 release. Link: http://7xpe0v.com1.z0.glb.clouddn.com/imposevka-patcher.7z

To build:

1. Prepare nodejs and [otfcc](https://github.com/caryll/otfcc)
2. Put Iosevka files into `src/`
3. Put Nerd’s additional characters into `nerd.ttf`
4. `make`

**Comment by ryanoasis** [comment]
@be5invis Wow really great stuff thanks :+1: 

Apologies, I hope you don't take my slow response for lack of interest.

**Comment by vbauerster** [comment]
Any plans to update patched iosevka to the latest version 1.9.3?

**Comment by ryanoasis** [comment]
@vbauerster oh wow didn't see your comment. We can target it for v1.2.0 release. I'll make a ticket so it's not lost

**Comment by ryanoasis** [comment]
> update patched iosevka to the latest version 1.9.3
> We can target it for v1.2.0 release. I'll make a ticket so it's not lost

@vbauerster Looks like I dropped the ball on this :cry:

**Comment by ryanoasis** [comment]
@vbauerster done: #229

**Comment by OJFord** [comment]
The linked script is no longer availablee, though it is fortunately preserved in fmthoma/config-files/6403f759c6a231cb016e48ccf993f17d6210efbe, what I'm not clear on however is how to generate `nerd.ttf`? `./font-patcher` from the repo requires an extant font to patch.

**Comment by ashb** [comment]
@OJFord The way I did it was to create a new font in FontForge, draw one rubbish character (had to be non-empty to let FontForge create it) -- patch that, then remove the character I added from the patched font.

If it would useful to anyone I can put my patched version somewhere -- just let me know which variant/style of Iosevka you would like patched.

**Comment by J3m5** [comment]
Hi @ryanoasis , would it be possible to update Iosevka to the latest version 3.6.2 ? 
Thanks

**Comment by ELLIOTTCABLE** [comment]
Does Iosevka still not patch properly with the FontForge patcher-script? It's in the middle of running (slowly!) on my machine, but the output looks sensible so far …

**Comment by be5invis** [comment]
It looks like that latest FontForge finally fixed exporting reverse chaining sub.
Using original patcher should work now.
Closing.
