### ISSUE TITLE
Not Supported in VSCode terminal [solved]

### ISSUE THREAD

**Issue by md-siam** [ryanoasis/nerd-fonts#831]
Nerd fonts are not supported in VS Code terminal

![Screen Shot 2022-05-16 at 8 01 59 AM](https://user-images.githubusercontent.com/21225918/168507828-12d47fba-5895-43d3-a602-c1a5cde3e32d.png)

I am using Mononoki Nerd Font v2.1

**Comment by md-siam** [comment]
You can see that the icons are cut in half.

**Comment by felipecrs** [comment]
This only started to happen after VS Code 1.67. If you downgrade to 1.66 they should work.

**Comment by felipecrs** [comment]
I believe we should track it at: https://github.com/microsoft/vscode/issues/148857

**Comment by md-siam** [comment]
This solution is working for me:
![Screen Shot 2022-05-16 at 8 37 32 PM](https://user-images.githubusercontent.com/21225918/168618221-6c58cc93-cd8c-42f0-8fdd-297a19b4b314.png)

**Comment by Finii** [comment]
Thank you all.
I would keep this open so that people can find the solution (default is to search only for open issues...).

**Comment by JulianH99** [comment]
Sorry I'm late to the party

I have a similar problem with self patched Recursive arrow type font, but in the windows terminal
![image](https://user-images.githubusercontent.com/16496346/226665110-2d264f27-e84d-412c-b5a8-c72c9674723c.png)

It does not happen with all the icons,
for example, here only the "recent files" icon is cut in half
![image](https://user-images.githubusercontent.com/16496346/226665332-88204498-a7b6-4cb5-990a-dda90002ddba.png)

**Comment by ClHg2** [comment]
Same issue as @JulianH99.

It works in VS Code:

![](https://pic2.imgdb.cn/item/645e194a0d2dde57777b5c98.jpg)

But doesn't work in Windows Terminal:

![](https://pic2.imgdb.cn/item/645e194a0d2dde57777b5c85.jpg)

**Comment by Finii** [comment]
@ClHg2 Could you say in words what does not work? I can not see anything obvious from the images.

Side-question: Is there a reason you use `-l`?

**Comment by ClHg2** [comment]
@Finii I mean the blue tick is not shown on the right side.

I just thought it might look better if I specify `-l`, maybe I'm using the flag in a wrong way...

**Comment by Finii** [comment]
Slightly strange... THIS Issue is about **Not Supported in VSCode terminal**,
and you write "It works in VS Code" :grimacing: ;-)

> I just thought it might look better

I never saw any difference and believe it does nothing. I thought maybe someone has hard evidence that it really does something.

Will try your Issue after lunch.

**Comment by Finii** [comment]
@ClHg2 

Hmm, but the tick is shown, just not the green one:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/fa910674-e425-479d-905a-663a1a2c2ac0)

Do you know the codepoint? Please copy&paste the line as text into a comment here, I can then examine.

Is the green coloring from your powerline theme?

**Comment by ClHg2** [comment]
@Finii

It's strange. The icon is ✔. But it displays differently in VS Code and Windows Terminal.

**Comment by Finii** [comment]
@JulianH99 

Hmm, that looks like the wrong font :thinking: 
Can you show the font settings of `Windows Terminal` and that font in Settings->Fonts that I can see the version etc

**Comment by Finii** [comment]
@ClHg2 

The codepoint of the tickmark is `2714` which is not part of Nerd Fonts patched in codepoints.

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/2b3958c7-b117-4706-9397-8996eef0178d)

You need to change your powerline to use a Nerd Font codepoint, examples:

![image](https://github.com/ryanoasis/nerd-fonts/assets/16012374/940d2145-75f7-4dd9-9ee4-39cc720c6c97)

**Comment by ClHg2** [comment]
@Finii I see. Many thanks!

**Comment by Finii** [comment]
Locking this, kept it open only so that the solution can be found more easy.
