### ISSUE TITLE
Font-Patcher fails when applied to Operator Mono SSm with Ligatures on Arch Linux

### ISSUE THREAD

**Issue by iRo0t** [ryanoasis/nerd-fonts#834]
```
    -`                    
                  .o+`                   --------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                   
               `+oooooo:                 Kernel: 5.17.8-zen1-1-zen 
               -+oooooo+:                 
             `/:-:++oooo+:                
            `/++++/+++++++:              Shell: zsh 5.9 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: Xfce 4.16 
         ./ooosssso++osssssso+`          WM: Xfwm4 
        .oossssso-````/ossssss+`         WM Theme: Os-Catalina 
       -osssssso.      :ssssssso.        Theme: MyTheme 
      :osssssss/        osssso+++.       Icons: Papirus
     /ossssssss/        +ssssooo/-       Terminal: kitty 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i5-4210U (2) @ 
  `+sso+:-`                 `.-/+oso:    GPU: 00:0f.0 VMware SVGA  
 `++:.                           `-/+/   Memory: 2157MiB / 2943MiB 
 .`                                 `/
```

I am currently using a version of Operator Mono SSm Book.otf to which I have applied @kiliman's ligature patch. I have tried to use it and I get the following error message: "OSError: Open Failed":

`./FontForge.AppImage -script $PWD/font-patcher $PWD/OperatorMonoSSmLig-Book.otf -s -c --careful`

And this is what I get in the terminal:

```
Copyright (c) 2000-2022. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20220308
 Based on sources from 2022-03-08 10:15 UTC-ML-TtfDb-D-GDK3.
 Based on source from git with hash: 582bd41a9bf04326300fc02a677fe3610d6d3ccd
The following table(s) in the font have been ignored by FontForge
  Ignoring \'DSIG\' digital signature table
Warning: Mac string is a subset of the Windows string in the \'name\' table
  for the Family string in the English (US) language.
Warning: Mac and Windows entries in the \'name\' table differ for the
  Styles (SubFamily) string in the language English (US)
  Mac String: Book
  Windows String: Regular
Warning: Mac and Windows entries in the \'name\' table differ for the
  Version string in the language English (US)
  Mac String: Version 1.201
  Windows String: Version 1.200
No configfile given, skipping configfile related actions
Nerd Fonts Patcher v2.1.0 executing

The requested file, original-source.otf, does not exist
Traceback (most recent call last):
  File \"/home/user/Descargas/font-patcher\", line 1037, in <module>
    main()
  File \"/home/user/Descargas/font-patcher\", line 1032, in main
    patcher.patch()
  File \"/home/user/Descargas/font-patcher\", line 110, in patch
    symfont = fontforge.open(self.args.glyphdir + patch[\'Filename\'])
OSError: Open failed

```
**what's wrong?**

Best Regards

Israel Rosas

**Comment by Finii** [comment]
You just have the script, but not the needed resource files (i.e. glyphs to patch in); at least not in the expected location.

Would be fixed by #741 

Did you just download the `font-patcher` script?
Maybe use the 'release' package instead: https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC/FontPatcher.zip

Addiional info:

I do not what you use `$PWD` for.

Whatever, if you have the glyphs somewhere else, you can use `--glyphdir`.

**Comment by Davincible** [comment]
Also ran into this. Would be useful to put it in the docs next to install instructions

**Comment by Finii** [comment]
> Would be useful to put it in the docs next to install instructions

You mean that the `2.2.0 RC` can be used?

There are still some other documentation fixes 'in the pipeline' (read this as 'stalled' :-( ): #847 

I can not change the docs on my own, that needs review. It is very very hard to write 'normal user' instructions if you are not one. :grimacing: 

_(In fact we should rather release `2.2.0` instead of recommending using the RC over the current release.)_

**Comment by Davincible** [comment]
I see. I meant that just downloading the script isn't enough, that you need the `src` dir with all the glyphs in it. docs make it sound like "just get the script and away you go"

**Comment by Finii** [comment]
Ah, ok. Thanks for the reply. That means just what is suggested in #847, to get it up and running ;-)
I'll come up with something.
