### ISSUE TITLE
Source Code Pro nerd font looks different compared to unpatched Source Code Pro

### ISSUE THREAD

**Issue by fuwa-fuwa-fapmachine** [ryanoasis/nerd-fonts#842]
#### 🗹 Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Patched source code pro looks different(taller and/or thinner) compared to unpatched source code pro of the same weight(medium)

Expected behavior:
They look identical aside from the added icons.

Example symbols:
0123456789
abcdefghijklmnopqrstuvwxyz

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_
       - Sauce Code Pro Medium Nerd Font Complete Mono.ttf
   - _Where did you get the file from (download link, self patched, source downloaded from link...)_
       - downloaded from [here](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/SourceCodePro/Medium/complete/Sauce%20Code%20Pro%20Medium%20Nerd%20Font%20Complete%20Mono.ttf)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
    - konsole
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
    - Linux, Fedora 35, KDE

#### ★ Screenshots (Optional)
nerd font:
![2022-06-05_729x431_000](https://user-images.githubusercontent.com/96286470/172057836-43aedff3-a58a-406c-b7e3-876c7c1be1d3.jpeg)
normal:
![2022-06-05_729x431](https://user-images.githubusercontent.com/96286470/172057869-1329a739-6dc6-400d-9c26-cf1c86444e7f.jpeg)

**Comment by Finii** [comment]
Hmm, having a look at the two fonts the glyphs look identical:

![image](https://user-images.githubusercontent.com/16012374/172322176-a479da0b-aab3-4350-959f-32863662f726.png)

You specified your patch font download link is [this](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/SourceCodePro/Medium/complete/Sauce%20Code%20Pro%20Medium%20Nerd%20Font%20Complete%20Mono.ttf)
Did you download the unpatched one [here](https://github.com/ryanoasis/nerd-fonts/blob/master/src/unpatched-fonts/SourceCodePro/Regular/SourceCodePro-Regular.ttf) ?

I see some flags are amiss, but that should not be an issue at 14 pt (what you used):
```
$ showttf src/unpatched-fonts/SourceCodePro/Medium/SourceCodePro-Medium.ttf | grep ppem
	flags=b baseline_at_0 lsb_at_0 ppem_to_int 
	lowestppem=9

$ showttf Sauce\ Code\ Pro\ Medium\ Nerd\ Font\ Complete\ Mono.ttf| grep ppem
	flags=1f baseline_at_0 lsb_at_0 instrs_depend_on_size ppem_to_int instr_set_width 
	lowestppem=8
```

Maybe you can try turning off antialiasing and see if that makes a difference?
But first please confirm which font you use as 'unpatched'.


Ah, and then, what is that for a font viewer? I see that it seems to rely on font grouping (you can select the style for a given font family). The grouping is broken (there is a PR pending to fix it). Maybe you should uninstall all other variants for testing purposes and just keep the `Regular` of both fonts in question, because it can easily mix it up :-(

**Comment by Finii** [comment]
Typographic naming seems to be correct:

```
 |Filename                                           | | Fullname                                                          | | Family                                                  | | Subfamily                      | | Typogr. Family                           | | Typogr. Subfamily
 |-------------------------------------------------- |-| ----------------------------------------------------------------- |-| ------------------------------------------------------- |-| ------------------------------ |-| ---------------------------------------- |-| ------------------------------

>|SourceCodePro-Medium.ttf                           | | Source Code Pro Medium                                            | | Source Code Pro Medium                                  | | Regular                        | | Source Code Pro                          | | Medium
-|Sauce Code Pro Medium Nerd Font.ttf                | | Sauce Code Pro Medium Nerd Font                                   | | SauceCodePro Nerd Font                                  | | Regular                        | | SauceCodePro Nerd Font                   | | Medium

>|SourceCodePro-Semibold.ttf                         | | Source Code Pro Semibold                                          | | Source Code Pro Semibold                                | | Regular                        | | Source Code Pro                          | | Semibold
-|Sauce Code Pro Semibold Nerd Font.ttf              | | Sauce Code Pro Semibold Nerd Font                                 | | SauceCodePro Nerd Font                                  | | Regular                        | | SauceCodePro Nerd Font                   | | Semibold
```

So last paragraph of previous comment is maybe moot. But because 'normal' Family naming is broken, who knows.

**Comment by fuwa-fuwa-fapmachine** [comment]
It was installed by default in my distro.

I uninstalled both of them and downloaded the unpatched font from your link and the regular nerd font and then they looked identical:

![2022-06-07_729x431_000](https://user-images.githubusercontent.com/96286470/172382130-1fca5c43-8cca-4aa8-bacb-e0888ae43d18.jpeg)
![2022-06-07_729x431](https://user-images.githubusercontent.com/96286470/172382420-b38c42dd-5a9e-4345-83f1-5c14c4e07d3f.jpeg)

But this is the "wrong" look! Fonts based on source code pro look like the font I had installed at first:

![2022-06-07_729x431_003](https://user-images.githubusercontent.com/96286470/172384165-792e4389-97e9-437f-8879-6966540990d7.jpeg)
![2022-06-05_729x431_002](https://user-images.githubusercontent.com/96286470/172383177-7d6bbc47-f3dc-4aad-b23f-ca48b5850f6c.jpeg)

So I once again reinstalled source code pro this time downloading the TTF from [the source code pro repo](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.038R-ro%2F1.058R-it%2F1.018R-VAR)

And it looked identical to the one in your link.

But I wasn't satisfied so I reinstalled it once again this time downloading the OTF (from [this release](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.038R-ro%2F1.058R-it%2F1.018R-VAR) again)

And this time it looks like the font I initially had installed:
![2022-06-07_729x431_002](https://user-images.githubusercontent.com/96286470/172386218-bb599240-2d41-4b0b-97b1-4184c473b97c.jpeg)

So it seems like source code pro.ttf and source code pro.otf look different? IDK where the issue is might be my system's handling of fonts or source code pro itself. Doesn't seem like a nerd font issue i guess. I'll try patching the .otf myself when I get the time.

**Comment by Finii** [comment]
Great findings!

The Source Code Pro we have as source is `2.030;PS 1.000;hotconv 16.6.51;makeotf.lib2.5.65220`.
While the [current version](https://github.com/adobe-fonts/source-code-pro/releases) is `2.038;hotconv 1.0.116;makeotfexe 2.5.65601`, which might or might not have changed the looks.

You can try these two versions, one is ttf one is otf, which are patched from the 2.038 for you testing convenience.

[Souce Code 2.038 ttf](https://github.com/Finii/nerd-fonts/blob/gist/up-to-date-sourcecode/Sauce%20Code%20Pro%20Nerd%20Font%20Complete%20Mono.ttf)
[Souce Code 2.038 otf](https://github.com/Finii/nerd-fonts/blob/gist/up-to-date-sourcecode/Sauce%20Code%20Pro%20Nerd%20Font%20Complete%20Mono.otf)

**Comment by fuwa-fuwa-fapmachine** [comment]
The .otf looks correct:
![2022-06-08_729x431](https://user-images.githubusercontent.com/96286470/172608326-45b5588a-c3a1-41a1-8a93-e3b544b5d03b.jpeg)
The .ttf still looks wrong, however.

**Comment by Finii** [comment]
> So it seems like `source code pro.ttf` and `source code pro.otf` look different?

Probably the hints are different. The postscript fonts (otf) have a more primitive mechanism for hints, while truetype fonts (ttf) allow the font designer very specific and complicated adjustments. As the methodology is different there are no ways to translate them (if the source has been hand-hinted).

If the difference vanishes for big sizes (like 64+) it is most likely the hinting (adjusting the outline for small size rendering).

We do not touch the hinting at all, so there is nothing Nerd Fonts can do about this.
