### ISSUE TITLE
Powerline glyphs have smaller height than the character box

### ISSUE THREAD

**Issue by mux** [ryanoasis/nerd-fonts#843]
#### 🗹 Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

I found a number of seemingly related issues but unless I missed something, none of them match my specific problem.

#### 🎯 Subject of the issue

Experienced behavior:
Some powerline glyphs seem to be smaller than the box height. This is most annoying with the arrow glyphs used to separate sections in vim-airline (both left and right). Additionally, the left arrows also show a one pixel vertical line with a darker color.

It seems to be related to the line spacing setting in the font selection window. It is 1 by default, and the issue is exacerbated if I increase it, and disappears if I set it down to about 0.8 (but then the window is nearly unreadable of course). The bigger the font, the more visible the problem is - I used 14pt in my screenshots.

It also seems to be an issue with the vertical lines characters used in the fortune chat bubble of vim-startify.

Expected behavior:
I would expect those glyphs to align all the way to the top, but there is a visible gap there instead.

Example symbols:
 and  (separation arrows)
│ (maybe)

#### 🔧 Your Setup

- Fira Code Regular Nerd Font Complete Mono.ttf

I tried many other Fira Code variants (Regular / Retina, Mono or not, otf / ttf) and they all show the same problem.

- Downloaded from nerdfonts.com
- Terminal.app
- OS X 12.4

#### ★ Screenshots (Optional)

![Screen Shot 2022-06-11 at 11 13 32 AM](https://user-images.githubusercontent.com/1478358/173193920-89de662b-3ebb-4364-a928-da2566e23742.png)
![Screen Shot 2022-06-11 at 11 34 27 AM](https://user-images.githubusercontent.com/1478358/173194535-5dfc2975-fed1-4c2e-be75-03d6e629bbfc.png)
![Screen Shot 2022-06-11 at 11 20 13 AM](https://user-images.githubusercontent.com/1478358/173193938-e100fb24-dde1-441a-aa14-9b210f9640fd.png)

**Comment by mux** [comment]
I just realized that the left arrows also show a one pixel vertical line with a darker color:

![Screen Shot 2022-06-11 at 11 34 27 AM](https://user-images.githubusercontent.com/1478358/173194535-5dfc2975-fed1-4c2e-be75-03d6e629bbfc.png)

**Comment by mux** [comment]
Both issues don't happen with iTerm 2, and without using the built-in powerline glyphs.

**Comment by Finii** [comment]
> Downloaded from nerdfonts.com

A lot problems are solved in the 2.2.0 Release Candidate, so maybe you want to use https://github.com/ryanoasis/nerd-fonts/releases/tag/2.2.0-RC instead. That would be the powerline triangular things.

The gaps with the vertical bars ... hmm. It could be that out `overlap` causes that issue, need to examine that.

The faint vertical lines should be fixed with #780.

**Comment by Finii** [comment]
I believe this is the HHEA vs TYPO vs WIN problem. See
* #1060
