### ISSUE TITLE
font request: Recursive Mono

### ISSUE THREAD

**Issue by laxtiz** [ryanoasis/nerd-fonts#845]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
no problem, but a new font family.

**Describe the solution you'd like**
i want use patched font with neovim.

**Describe alternatives you've considered**
i tried to patch by myself, but i don't know why my os(Fedora Linux 36 with gnome 42) not recognized as monospaced font.
i need help from others.

**Additional context**
the font's info:
- offical website: [Recursive Sans & Mono](https://www.recursive.design/)
- Github Repo: https://github.com/arrowtype/recursive

**Comment by Finii** [comment]
Maybe my answer here: https://github.com/ryanoasis/nerd-fonts/discussions/847 is useful.

You need to specify `--mono` to get a really monospaced font.

I run my `neovim` with a non-monospaced font. Why do you need it monospaced?
That is probably dependend on the terminal you run `neovim` in. But you did not specify any. I use `tilix` ;-)

**Comment by ghe0** [comment]
If you do patch recursive, I would also like to use it.

**Comment by mystrdat** [comment]
Would love to see Recursive available for download pre-patched!

**Comment by Finii** [comment]
Added to #1095

**Comment by Jobin-Nelson** [comment]
Any update on this one, Would really be happy to see this font added

**Comment by Finii** [comment]
@joaomcarlos Thanks for reminding me!

We should start choosing fonts for the next release. After xmas probably.

>Sad to see Recursive Mono Casual was not added :/
>
>Its an insanely good font for UI and Terminal displays and for code its specially fun.
>
>https://www.recursive.design/
>
>These types of handwritten style fonts reduce fatigue and improve readability in high vibration environments (a similar font is used in the B1 bomber [for example](https://theaviationgeekclub.com/the-first-ever-video-filmed-inside-the-cockpit-of-the-b-2-stealth-bomber-one-of-the-most-secret-places-on-earth-finally-revealed/))

**Comment by yaaama** [comment]
I really do have to bump this thread because Recursive is probably my new favourite font.

I was using source code pro (NF patched) for 5+ years in the terminal without change but "Rec Mono Semicasual" variant took its place because of how nice it is to use and its legibility is superb even with tired eyes.

so a +1 from me!

**Comment by Finii** [comment]
Tnx for the feedback!

**Comment by joaomcarlos** [comment]
I've switched to Rec Mono Casual in both terminal and code editors. It works pretty well for code and interfaces in the terminal like NeoVim menus. It also works extremely well with vibrant colors which many fonts fail at while working well with muted colors like almost all others, so very versatile on that front. It also works with pastel colors like Catpuccin theme.

And doesnt look terrible when subpixel rendering isnt available like the Ubuntu font, or when the font rendering pipeline is a little wonky (linux) which is a plus when working with multiple systems (tested on Mac and PopOs).

This xmas surprise (for me anyway) keeps on giving
