### ISSUE TITLE
Update the chart / diagram in the README

### ISSUE THREAD

**Issue by Snailedlt** [ryanoasis/nerd-fonts#846]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
[This diagram](https://github.com/ryanoasis/nerd-fonts/raw/master/images/sankey-glyphs-combined-diagram.svg) displaying which icon packs are gathered together in the README is outdated. It hasn't been updated since 2018.
![image](https://user-images.githubusercontent.com/43886029/174279794-9261df3b-c8a8-4e51-afe7-fd12a3e6bbf9.png)

**Describe the solution you'd like**
Update with new icon packs, and new numbers (maybe make it autoupdate if possible?)

**Describe alternatives you've considered**
Not many alternatives except ignoring it

**Additional context**

**Comment by Snailedlt** [comment]
Yeah, seems like it

**Comment by Finii** [comment]
Sankey data to create 'original' graph:

```
Powerline Symbols [7] Nerd Fonts
Powerline Extra Symbols [30] Nerd Fonts
Font Awesome [675] Nerd Fonts
Font Awesome Extension [170] Nerd Fonts
Devicons [197] Nerd Fonts
Weather Icons [228] Nerd Fonts
Seti UI + Custom [52] Nerd Fonts
Octicons [172] Nerd Fonts
Font Linux [29] Nerd Fonts
IEC Power Icons [6] Nerd Fonts
Pomicons [8] Nerd Fonts
Material Design [2119] Nerd Fonts

:Powerline Symbols #b6cceb
:Powerline Extra Symbols #b6cceb
:Font Awesome #ff8b25
:Font Awesome Extension #ff8b25
:Devicons #ffc186
:Weather Icons #40aa40
:Seti UI + Custom #a3e395
:Octicons #db3d3e
:Font Linux #ff8b25
:IEC Power Icons #fed4d4
:Pomicons #bb9ed4
:Material Design #cab8da
:Nerd Fonts #3585bc
```
Size 558x558
Node Width 18 px
Node Spacing 38%
Flow Curviness 0.82
Labels Size 14 px
Units Suffix `" icons"`

I'm too stupid to get the right hand side label bigger in text size.

![image](https://user-images.githubusercontent.com/16012374/174610080-2b5e70d3-0ac7-45d9-8d8b-e7b6cbaca975.png)

Generating this should in principle be possible 'offline' with https://github.com/d3/d3-sankey, and I tried that a bit, but ... this is not my expertise. And I do not want to go down the `npm` hole, I really hate that stuff. It pulls in:

![image](https://user-images.githubusercontent.com/16012374/174610870-38007dff-6222-43be-9483-d704dbcd1c5f.png)

Me thinks: Yes right, ... experts at work

**Comment by Snailedlt** [comment]
@Finii 
I think maybe labels were disabled, and added in later
<img width="735" alt="image" src="https://user-images.githubusercontent.com/43886029/174633265-2868a678-c87c-4373-a6fb-d8b6d9729af8.png">

Not sure though

**Comment by Finii** [comment]
Just found this manual ...

https://github.com/ryanoasis/nerd-fonts/wiki/Release-Workflow#update-the-sankey-diagram-if-glyph-changes

**Comment by Snailedlt** [comment]
That looks promising!
Did you get any further with this, and is there anything you need help with?

**Comment by Finii** [comment]
Waaahhh :sob:

Forgot to rename `font-linux` to `font-logos`.

Maybe some other day.

**Comment by Finii** [comment]
> Maybe some other day.

Fixed :sweat_smile:
