### ISSUE TITLE
Add Code New Roman font

### ISSUE THREAD

**Issue by rhssk** [ryanoasis/nerd-fonts#85]
https://sourceforge.net/projects/codenewroman/

Already tried patching it myself, but I must doing something wrong because the statusline symbols aren't centered correctly (https://i.imgur.com/vHNAW2A.png).

**Comment by ryanoasis** [comment]
Good suggestion thanks.

The issues you are having are probably to do with the em size, you probably aren't doing anything wrong. There are still glyph sizing issues we need to work out when patching :worried:
