### ISSUE TITLE
Patcher reduces the spacing between lines making fonts difficult to read.

### ISSUE THREAD

**Issue by BoltsJ** [ryanoasis/nerd-fonts#850]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
After patching a font, the line height is reduced which makes 

Expected behavior:
Line height should remain the same after patching.

Example symbols:
N/A

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - `Comic Code Regular Nerd Font Complete.otf`
   - Self-patched using the oci image.
- `gnome-terminal`, Blackbox, `gnome-text-editor`
- Fedora 36 Silverblue

#### ★ Screenshots (Optional)

Unpatched font: 
![image](https://user-images.githubusercontent.com/182554/176006195-c036f961-1855-4777-8516-2877835a49ef.png)

Patched font:
![image](https://user-images.githubusercontent.com/182554/176006340-522025b3-29a1-4cf0-929d-aaab6bac6a5b.png)

**Comment by bartdorsey** [comment]
The same thing happens to me when patching comic code ligatures

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/180990674-36c57058-2df0-42df-83b9-a7af4c8c34c5.png)

I guess that is very easy to fix. Believe I know where the size is lost.

**Comment by DanBenHa** [comment]
> ![image](https://user-images.githubusercontent.com/16012374/180990674-36c57058-2df0-42df-83b9-a7af4c8c34c5.png)
> 
> I guess that is very easy to fix. Believe I know where the size is lost.

Could you share your insights?

**Comment by tusharsnn** [comment]
I am facing the same issue, is there a known fix yet ?

**Comment by Finii** [comment]
@tusharsnn :+1: 

I'm not sure the `font-patcher` code is correct in this regard anyhow.

:thinking:  Obviously I commented already some time back :grimacing: 

This needs some research in the `src/unpatched-fonts` base, which might take me some time.
Feel free to ping me from time to time :grimacing: 

This is the commit that added the lnes you mention:
9770856f83 ` Zero out linegap values to allow power line glyphs to fill properly `

And probably it is right, but we have to keep the gap in another property then, we can not just silently remove it without replacement.

**Comment by tusharsnn** [comment]
I should point out that MonoLisa is aligned towards the top instead of being centered, which means there is more gap on the bottom then it is on the top. Is that fonts with this characteristic is effected by mentioned code ?

**Comment by Finii** [comment]
Fonts that have a linegap set (only regular shown):

```
3270Medium                                         Line gap: 90 (90)
Arimo                                              Line gap: 67 (307)
VeraMono                                           Line gap: 0 (410)
DejaVuSansMono                                     Line gap: 0 (410)
FantasqueSansMono                                  Line gap: 50 (100)
gohufont*                                          Line gap: 377 (377)
Go-Mono                                            Line gap: 0 (393)
Hack                                               Line gap: 0 (410)
heavy_data                                         Line gap: 67 (307)
iAWriter*                                          Line gap: 0 (300)
IBMPlexMono                                        Line gap: 0 (300)
Inconsolata-LGC                                    Line gap: 205 (0)
iosevka*                                           Line gap: 68 (0)
LiberationS*                                       Line gap: 67 (307)
Lilex                                              Line gap: 0 (600)
Meslo LG *                                         Line gap: 0 (1210)
mononoki                                           Line gap: 0 (229)
mplus-*                                            Line gap: 90 (90)
RobotoMono                                         Line gap: 0 (102)
Terminus                                           Line gap: 90 (90)
Tinos                                              Line gap: 87 (307)
Ubuntu-*                                           Line gap: 28 (56)
VictorMono*                                        Line gap: 200 (200)

Name ...                                           hhea_linegap  (os2_typolinegap)
```

**Comment by Finii** [comment]
Victor Mono:

![image](https://user-images.githubusercontent.com/16012374/192282254-9f9b7948-6aa8-47fd-9cba-529266e8de96.png)

VictorMono Nerd Font:

![image](https://user-images.githubusercontent.com/16012374/192282476-3897ec68-7f64-4153-ba6b-eb5a8e914880.png)

Hmm, for my eye the spacing is 'too loose' in the original font. If we fix this people might complain now the patched fonts are wrong :grimacing:

**Comment by Finii** [comment]
Downloaded `Comic Code` from `myfonts` ...:

```
ComicCodeDemo                                      Line gap: 200 (200) [x]
```

![image](https://user-images.githubusercontent.com/16012374/192288101-c32de839-832e-46ac-aec8-7c00fc593ef1.png)

After patching:

![image](https://user-images.githubusercontent.com/16012374/192289121-f6ef10f1-103c-4ca0-83b4-31f1981fd102.png)

**Comment by tusharsnn** [comment]
IMO the tool (or at least the `./font-patcher`) should not override original font properties by default. For already patched fonts this should be explicitly mentioned that spacing has been modified.

**Comment by Finii** [comment]
But people will complain if the visuals of their beloved patched fonts change with an Nerd Font update. They do not care what is 'right' or 'wrong' as long as it is the same as before the update :grimacing: ;-)

**Comment by Finii** [comment]
IF we use the line gap, there is another thing to decide on:

![image](https://user-images.githubusercontent.com/16012374/192290804-f0977047-1d80-4564-a697-887d98074df3.png)

You see that the Powerline Triangular Thing is exactly on the same height as the middle of `X` `-` etc...
If the Powerline glyph needs to fill further down, what will happen with that?
* Move the tip further down, too low compared with `-` etc
* Keep tip on middle X height, but clip (make unsymmetric)
* Vary angles of the triangle (too much work probably)

**Comment by tusharsnn** [comment]
> But people will complain if the visuals of their beloved patched fonts change with an Nerd Font update. They do not care what is 'right' or 'wrong' as long as it is the same as before the update 😬 ;-)

I agree with that, patched font should stay the same. And for self patching, 'keep line distance' flag should be enough.

**Comment by tusharsnn** [comment]
> You see that the Powerline Triangular Thing is exactly on the same height as the middle of `X` `-` etc... If the Powerline glyph needs to fill further down, what will happen with that?
> 
> * Move the tip further down, too low compared with `-` etc
> * Keep tip on middle X height, but clip (make unsymmetric)
> * Vary angles of the triangle (too much work probably)

I don't pretend to understand `fontforge` completely, but is it possible to centre the text AND divide the original line space evenly on top and bottom? that way we don't need to workaround glyphs to look right.

**Comment by Finii** [comment]
Patched without removing line gap...:

![image](https://user-images.githubusercontent.com/16012374/192294079-b477b99e-b968-44e6-9898-3dce537116ba.png)

> but is it possible to centre the text AND divide the original line space evenly on top and bottom?

Excellent idea!

**Comment by Finii** [comment]
AH! This font has no headroom! I have seen such patched fonts before, and they 'break' if people like to use diacritics like `&Ouml;` (Big O with dots, `Ö`) because it has no room. I have an issue about that somewhere... that would be solved if we keep the gap.

**Comment by Finii** [comment]
Hmm....

Gap distributed to top and bottom, equally:

![image](https://user-images.githubusercontent.com/16012374/192303511-ea146dcf-84b6-4c09-90eb-f5b9b61f458f.png)

**Comment by Finii** [comment]
This looks ok-isch? I will clean up the commit and test with some of the other problematic (i.e. gap-having) fonts.

**Comment by Finii** [comment]
Here is the issue where the headroom is too small for umlauts.. tested with text `Übelst`...

* https://github.com/ryanoasis/nerd-fonts/pull/593#issuecomment-801270215

**Comment by Finii** [comment]
Looks identical... (200% view)
Note the vertical spacing between the `?` boxes.

### Original

![image](https://user-images.githubusercontent.com/16012374/192321284-73f928ad-706f-4e25-ac4b-4bc142f88086.png)

### Patched, with HEAD

![image](https://user-images.githubusercontent.com/16012374/192322806-1a98a219-d408-4246-8caf-cadd023ee451.png)

### Patched, gap left intact

![image](https://user-images.githubusercontent.com/16012374/192321515-8e0f9270-252a-4658-8875-334e655e1783.png)

### Patched, gap redistributed top/bottom

![image](https://user-images.githubusercontent.com/16012374/192321869-1432e65d-efce-4069-bb32-63f3d278667d.png)

### Next to each other

![image](https://user-images.githubusercontent.com/16012374/192323878-893b1884-762f-4556-9a71-49da542da296.png)

**Comment by Finii** [comment]
Superimposed 1st (original) and 4th (split gap) variant at 400%:

![image](https://user-images.githubusercontent.com/16012374/192325212-1d8157d3-bd87-4040-87cf-dd50d94be1e2.png)

**Comment by tusharsnn** [comment]
patched with equal gaps looks good to me 👍

**Comment by paldepind** [comment]
I have the same issue as @snpefk. I patched Comic Code with `font-patcher` version  `v2.3.3 (3.5.1)` and the line height is now much reduced and very cramped.

**Comment by Finii** [comment]
* #1116 (bottom)
* 62b972b4310a320dadbe6f89fa1903cf4f0ab039  `font-patcher: Fix: Use WIN metrics in all conflicting cases`
* b112fe12de77ca506dba366be0a7754d5988525b  `font-patcher: Fix: Fix line gap redistribution`

**Comment by Finii** [comment]
I did not initiate a bugfix `2.3.x` release because I believe we are very near `3.0.0`; lthough ... I keep being pushed back :grimacing:

**Comment by paldepind** [comment]
Thanks a lot for the quick reply @Finii 🙂

I got the patch script through the ZIP archive. How do I get `3.5.7`? Then I'll be happy to check if this fixes the issue.

**Comment by Finii** [comment]
@paldepind would be great if you could check this out :+1:

Thanks to @b- (#1044) we have now not only a always-up-do-date docker image, but also a zip archive:

https://github.com/ryanoasis/nerd-fonts/blob/-/FontPatcher.zip

**Comment by paldepind** [comment]
I just ran the script at version `3.5.10` and this fixed the issue 🙂 Thanks!

**Comment by Finii** [comment]
You are not on Mac 🤦‍♀️

**Comment by Finii** [comment]
That font comes out unchanged in height:

<img width="937" alt="Screenshot 2023-03-22 at 19 03 13" src="https://user-images.githubusercontent.com/16012374/226997086-0ba00710-98fa-4fa5-aff4-7bb3c6758c9d.png">

[...]

<img width="937" alt="Screenshot 2023-03-22 at 19 03 29" src="https://user-images.githubusercontent.com/16012374/226997123-1a19a782-3ccd-4cbe-b197-c20b09da5864.png">

**Comment by snpefk** [comment]
Yeah, I'm on linux (`Linux 5.15.96-1-MANJARO` specifically). 
I'm noticed this warning about font vertical, maybe this is why height is so big 
```
❯ ./font-patcher ComicCodeLigatures-Regular.otf -cl
Nerd Fonts Patcher v2.3.3 (3.6.1) (ff 20230101) executing
Nerd Fonts: WARNING Font vertical metrics inconsistent (HHEA 1667 / TYPO 1200 / WIN 1667), using WIN
Redistributing line gap of 200 (100 top and 100 bottom)
Info: Extended glyphs wider bounding box than basic glyphs
Warning: Font has negative right side bearing in extended glyphs
```

**Comment by Finii** [comment]
Ah, yes.

Different companies worked on the TrueType format, and they all had different ideas. That resulted in the baseline to baseline distance being encoded in 3 places. Apple's HHEA, Microsoft's WIN, and the newer TYPO.

> Nerd Fonts: WARNING Font vertical metrics inconsistent (HHEA 1667 / TYPO 1200 / WIN 1667), using WIN

Unfortunately the font you use has contradicting values. Different OS's and even applications use different line heights with that font.
Because the original font has a gap between lines, and powerline symbols can have no gaps - you want them to touch line to line - we need to rewrite the metrices on patching. For that one metric is selected (in your case the WIN line height, which is equal to Apple's HHEA) and written to the other metrices. Your OS/client uses the TYPO value.

The one I tried is `Comic Code Ligatures` by `Toshi Omagari - Tabular Type Foundry` (Nov 2019 / version 1.0) [1].

You could use `font-line` to fix your font's line-height information, then patch it again.
Or use the same sourcefont I used.

[1] https://tosche.net/fonts

**Comment by snpefk** [comment]
Pardon me, but what is `font-line`?

**Comment by Finii** [comment]
> Pardon me, but what is `font-line`?

https://github.com/source-foundry/font-line

Can be installed via pip for example.

```
$ pip3 install font-line
$ font-line report my_cosmic_font.ttf
```
_Example usage_

**Comment by Sycha** [comment]
I am was having similar problems. Here is my font-line report for the unpatched 'Comic Code Regular.otf'

```
=== Comic Code Regular.otf ===
1.000
SHA1: 5e2a8bfcb29b617af8b7c748b220f2f4b5d47eda

::::::::::::::::::::::::::::::::::::::::::::::::::
  Metrics
::::::::::::::::::::::::::::::::::::::::::::::::::
[head] Units per Em:   1000
[head] yMax:           1096
[head] yMin:          -454
[OS/2] CapHeight:      700
[OS/2] xHeight:        550
[OS/2] TypoAscender:   800
[OS/2] TypoDescender: -200
[OS/2] WinAscent:      1136
[OS/2] WinDescent:     331
[hhea] Ascent:         1136
[hhea] Descent:       -331

[hhea] LineGap:        0
[OS/2] TypoLineGap:    200

::::::::::::::::::::::::::::::::::::::::::::::::::
  Ascent to Descent Calculations
::::::::::::::::::::::::::::::::::::::::::::::::::
[hhea] Ascent to Descent:              1467
[OS/2] TypoAscender to TypoDescender:  1000
[OS/2] WinAscent to WinDescent:        1467

::::::::::::::::::::::::::::::::::::::::::::::::::
  Delta Values
::::::::::::::::::::::::::::::::::::::::::::::::::
[hhea] Ascent to [OS/2] TypoAscender:       336
[hhea] Descent to [OS/2] TypoDescender:     131
[OS/2] WinAscent to [OS/2] TypoAscender:    336
[OS/2] WinDescent to [OS/2] TypoDescender:  131

::::::::::::::::::::::::::::::::::::::::::::::::::
  Baseline to Baseline Distances
::::::::::::::::::::::::::::::::::::::::::::::::::
hhea metrics: 1467
typo metrics: 1200
win metrics:  1467

[OS/2] fsSelection USE_TYPO_METRICS bit set: True

::::::::::::::::::::::::::::::::::::::::::::::::::
  Ratios
::::::::::::::::::::::::::::::::::::::::::::::::::
hhea metrics / UPM:  1.47
typo metrics / UPM:  1.2
win metrics  / UPM:  1.47
```

I used this command on the unpatched files: 
```
font-line percent 20 *
```

Then patched them with the docker container and the -c argument and it all looks okay now

```
docker run --rm -v ./in12:/in -v ./out12:/out nerdfonts/patcher -c
```

![image](https://user-images.githubusercontent.com/18023836/230641651-8f07f830-4838-43a6-be1c-06df664110ee.png)


![image](https://user-images.githubusercontent.com/18023836/230641125-2a7bf981-6fce-47ee-a4db-79b67ed98c37.png)

Cheers for the pointer to font-line @Finii
