### ISSUE TITLE
add Raku icon

### ISSUE THREAD

**Issue by ignamartinoli** [ryanoasis/nerd-fonts#851]
- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**

It would be nice to have a **Raku** icon

**Describe the solution you'd like**

The addition of a **Raku** icon

**Describe alternatives you've considered**

None

**Additional context**

This is the official **Raku** mascot

![raku](https://user-images.githubusercontent.com/103866722/177941817-a998c6f0-57a6-44b2-aca4-7fc00ce3e8c1.png)

**Comment by ignamartinoli** [comment]
Now it's properly filled

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
