### ISSUE TITLE
Add progress bar icon set

### ISSUE THREAD

**Issue by carlosV2** [ryanoasis/nerd-fonts#855]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
No problem, just a suggestion

**Describe the solution you'd like**
To add a set of icons to act like a minimal progress bar. It could be useful for installers, media players, etc

**Describe alternatives you've considered**
I've considered using the battery icon set but it doesn't fit the purpose as when you see a battery icon, you thing on something being depleted, not completed. I've also considered using an ascii-based progress bar but it either takes lot of space or it must have such huge steps that defeat the point of having it.

**Additional context**
I'm building a custom widget to show the current song being played and I think adding a minimal horizontal progress bar would look neat.
Alternatively (or, additionaly), it could be a radial progress bar which would look better in an square-like character space.

**Comment by Finii** [comment]
There are other glyphs that can be used, like the 1/8th filling blocks.
Someone would need to develop something, or find in another icon set.
I'm not really sure many people would need this.
