### ISSUE TITLE
Add Netwide Assembler (NASM) icon

### ISSUE THREAD

**Issue by ignamartinoli** [ryanoasis/nerd-fonts#857]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**

It would just be a nice add-on

**Describe the solution you'd like**

It would be cool to have an icon for **Assembly** languages for `nvim-web-devicons` and `exa` to use

**Describe alternatives you've considered**

I don't know any other solution

**Additional context**

There is no icon nor mascot for Assembly `.asm` files in general, but Netwide Assembler is quite popular and with its icon could fit that spot

![Netwide_Assembler](https://user-images.githubusercontent.com/103866722/177392704-2e090995-4c68-4c94-a19c-ec4b9d5ee329.svg)

**Comment by Finii** [comment]
Related:

https://github.com/ogham/exa/issues/1080

`exa` does not handle `.asm` at the moment at all: https://github.com/ogham/exa/blob/master/src/output/icons.rs

**Comment by ignamartinoli** [comment]
As an update, I was able to get this icon, which resembles the **C**/**C++** but has a different shape orientation.
Does it seem like a good idea? Any feedback before creating a PR?

![asm](https://user-images.githubusercontent.com/103866722/194773833-8571f323-4fa8-4036-a51c-57b9d29c683b.svg)

**Comment by Finii** [comment]
I must admit I think it looks quite good :grimacing:

**Comment by ignamartinoli** [comment]
Thanks @Finii! I will figure out how to create a PR and link the issue

**Comment by Finii** [comment]
Some hints are in https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md#contributing-guide

The link in our documentation is broken I just noticed, it is https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

You need to turn your attention to the files in `src/svgs/` in this repo. In principle... read that README, put your `.svg` there, and add the appropriate data to `icons.tsv`. After pushing the repo to github it will automatically rebuild `src/glyphs/original.source.ttf` with your icon included. Download that and check with `fontforge` or other font examination program.

(The font rebuild via github action can also be 'imitated' on your local machine, by running `cd bin/scripts && ./generate-source-source.py`, but that needs some stuff to be existing on your machine.) Do not put the generated font file into the PR.

:-) :+1:

**Comment by ignamartinoli** [comment]
@Finii I just opened a PR.

I'm not that experienced neither with Git nor this project so if there is any mistake please tell me so I can improve for my next contribution.

I wasn't able to use FontForge to verify, it would show me almost no icons.
