### ISSUE TITLE
Backtick character overlaps with the next character in patched font

### ISSUE THREAD

**Issue by krish-r** [ryanoasis/nerd-fonts#858]
Hello,

#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
The backtick (`` ` ``) character overlaps with the next character in the following patched fonts.
* Monolisa (paid)
* Inconsolata (open-source)

(There was already an issue #582 on this topic. However, it was closed and I could not find any solution there.)

Expected behavior:
The backtick (`` ` ``) character should not overlap with the next character like the original font.
 
Example symbols:
`` `i `` (or backtick with any other alphabet should also work)

#### 🔧 Setup

| Font        | Font Version | Format  | Font File Name                                                | Font Source                                                                      |
| ----------- | ------------ | ------- | ------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| MonoLisa    | v1.808       | TTF/OTF | MonoLisa Regular Nerd Font Complete.ttf                       | Self Patched - using Nerd Fonts Docker image with `--complete` option               |
| Inconsolata | v2.012       | TTF/OTF | Inconsolata Regular Nerd Font Complete Windows Compatible.ttf | https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Inconsolata.zip |

System Information
|              |                                                 |
| ------------ | ----------------------------------------------- |
| Applications | VS Code v1.68.1, Windows Terminal v1.13.11432.0 |
| OS           | Windows 11, Linux (Ubuntu)                      |
 

#### ★ Screenshots

| Font        | Original Font                                                                                                   | Patched Font                                                                                                    |
| ----------- | --------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------- |
| MonoLisa    | ![image](https://user-images.githubusercontent.com/54745129/177486100-c7ce2cd3-e14e-45b5-b24d-5989e0dc8167.png) | ![image](https://user-images.githubusercontent.com/54745129/177485968-42a7f8a9-9533-4ebb-ad1a-42a3afed0b50.png) |
| Inconsolata | ![image](https://user-images.githubusercontent.com/54745129/177486228-29e307f5-116a-4cdd-9445-fe189cc0fce7.png) | ![image](https://user-images.githubusercontent.com/54745129/177486312-ad58db1a-c457-4886-8b31-c9ef8110d96c.png) |

Thanks!

**Comment by krish-r** [comment]
Thanks for the detailed analysis and PR. 

Sure, I'll follow the instructions and try patching the font via command line.

**Comment by krish-r** [comment]
Thanks @Finii, I was able to patch the fonts from the command line using the latest fontforge appimage by following your instructions in #847. 

I was getting errors when using relative path in the command line (I believe that's due to appimage), so I had to use absolute path everywhere.
I also had to update "font-patcher" to use the absolute path of the output directory as argument instead of `self.args.outputdir` during font generation in `self.sourceFont.generate` method. (The `make_sure_path_exists(self.args.outputdir)` did not throw any error though.)

**Comment by Finii** [comment]
> I was getting errors when using relative path in the command line (I believe that's due to appimage)

I guess that is documented, no?

![image](https://user-images.githubusercontent.com/16012374/178672718-39b915aa-6fe7-44d5-a05d-34c1e2b70cbe.png)

So your problems are all 'expected' (after reading the docs).

But it is unexpected for a casual user. I use other appimages (like `neovim`), and they do NOT behave this way, of course, because that borders on unusable. So you are right, the actual issue should probably be addressed (documented but unexpected).

**Comment by krish-r** [comment]
ah! my bad. I just look into your instructions, but missed to check the documentation. 😞
