### ISSUE TITLE
Terminus distorted glyphs after patch

### ISSUE THREAD

**Issue by lcorsini** [ryanoasis/nerd-fonts#86]
Hello,
Since Terminus doesn't seem to be provided because of some issues in patching the original bdf files,
I tried to use the script to patch this TTF version http://files.ax86.net/terminus-ttf/ which includes at least the basic powerline symbols
the patch works, but the font gets very distorted as you can see in the screenshot (this font is very clear at 12points without antialiasing)

![font](https://cloud.githubusercontent.com/assets/1501930/15286472/92c1e0ba-1b5d-11e6-9ee2-9622c5edeb19.JPG)

any ideas on why this happens?

**Comment by ryanoasis** [comment]
@lcorsini Thanks for the details. Nothing particular is coming to my mind right now but I will try to take a look. :smile:

**Comment by lcorsini** [comment]
Thanks, 
Maybe if there is no particular licensing problem you could include this TTF in your distribution (I use Terminus a Lot, it's one of the best in readability, and this TTF works cross platform even on windows and osx)

**Comment by ryanoasis** [comment]
Yes if the license is fine it would be better to just try to patch the TTF like you have done 😄 

As for the issues you mentioned I just haven't gotten around to looking into it yet 😞

**Comment by ryanoasis** [comment]
@lcorsini Can you give more info on the screenshot you provided? What system, editor etc?

This appears to be a problem with the `ttf` file not the patching. I was able to replicate the very distorted characters without antialiasing turned on, on the original `ttf` and the patched ttf file.

Another option would be to patch the bitmap fonts but this would require more work, something similar to how https://bitbucket.org/ZyX_I/bitmap-font-patcher works

**Comment by lcorsini** [comment]
Ok, in the meantime I moved away from that setup, it was on windows, the editor is vim, and probably this was under putty
The Terminus font is better without antialias and on 12pt that's why I was using it like that

**Comment by ryanoasis** [comment]
@lcorsini Thanks for the details. Yeah I can see that being a bitmap font that would be the typical usage. I am marking this as 'future' as I believe it will take a good amount of effort to be able to patch the bitmap version of this font _and_ I think most people will have antialiasing on.

**Comment by QtheConqueror** [comment]
I have the same problem with patched Terminus TTF it looks all distorted.
No matter if I download the pre-patched font or if I patch it myself (using the Terminus TTF that displays correctly).

Unpatched font:
![Screen Shot 2019-03-28 at 11 08 17 PM](https://user-images.githubusercontent.com/44992697/55206874-6f00e600-51ae-11e9-8ff6-9af59b42583f.png)

Patched font:
![Screen Shot 2019-03-28 at 10 55 47 PM](https://user-images.githubusercontent.com/44992697/55206891-7aeca800-51ae-11e9-9cd7-27f0d6d0b24d.png)

System Details:
macOS 10.14.3
iTerm 2 build 3.2.8
zsh (oh-my-zsh powerlevel9k theme) 
Terminus TTF
16pt (I've used the unpatched font and it looks fine at this size)
Anti-aliasing disable for both patched and unpatched

**Comment by DoctorKnowsBetter** [comment]
I fixed this crap :)
[https://github.com/DoctorKnowsBetter/TerminessNerdFont-FixBlur](url)

**Comment by Slabity** [comment]
Nice! Did you make a fix for the font patcher itself or did you end up fixing it manually? Can you get the change pulled into this repo?

**Comment by DoctorKnowsBetter** [comment]
I did it manually. The script (font-patcher) does not transfer bitmap layers, I had to create and transfer all bitmap layers from the original Terminus.

**Comment by Finii** [comment]
Nice! :+1: @DoctorKnowsBetter 

I never ever bothered about bitmap fonts :-}

**Comment by Finii** [comment]
@DoctorKnowsBetter 
Which option did you use on generate?
![image](https://user-images.githubusercontent.com/16012374/191893523-1079609b-822c-4bc3-8e6f-51847c689ce0.png)

**Comment by Finii** [comment]
Fonts containing bitmaps:

```
Examining 601 font files
bitmap (11,) (gohufont-11)
bitmap (14,) (gohufont-14)
bitmap (11,) (gohufont-uni-11)
bitmap (14,) (gohufont-uni-14)
bitmap (7, 9, 10, 12, 14, 18, 24) (ProFontIIx)
bitmap (12, 14, 16, 18, 20, 22, 24, 28, 32) (TerminusTTF-Bold Italic-4.40.1)
bitmap (12, 14, 16, 18, 20, 22, 24, 28, 32) (TerminusTTF-Bold-4.40.1)
bitmap (12, 14, 16, 18, 20, 22, 24, 28, 32) (TerminusTTF-Italic-4.40.1)
bitmap (12, 14, 16, 18, 20, 22, 24, 28, 32) (TerminusTTF-4.40.1)
```

**Comment by Finii** [comment]
Maybe you could try #939 @DoctorKnowsBetter @Slabity ?

**Comment by DoctorKnowsBetter** [comment]
@Finii This options:
![2022-09-23_13-00](https://user-images.githubusercontent.com/111871367/191937623-db345b34-185a-4c8e-b76c-fb1c9567e37e.png)

**Comment by Finii** [comment]
@DoctorKnowsBetter Thank you. That is what I implemented in #939.

**Comment by Finii** [comment]
Seems to work :-)

Previously:

![image](https://user-images.githubusercontent.com/16012374/191957792-cbf3caa3-a5d8-414c-9a68-9fc0bcb838cf.png)

With this PR applied...:

![image](https://user-images.githubusercontent.com/16012374/191958307-9f1bc0de-689c-48aa-8463-c18973f782f0.png)

Now it looks equal.

**Comment by Finii** [comment]
Well, I see nothing with my terminal `tilix` (which probably can do nothing with bitmap fonts).

But here, with Libre `writer`:

![all](https://user-images.githubusercontent.com/16012374/192012076-50297975-3eca-4e3d-aaef-c6c7f152c314.png)

* uninstalled all fonts that are able to supply `E61A` (checked with `fc-list ':charset=e61a'`.
* Install `src/unpatched-fonts/Terminus/terminus-ttf-4.40.1/Regular/TerminusTTF-4.40.1.ttf`
* -> Uppermost image
* Uninstall Terminus and install `patched-fonts/Terminus/terminus-ttf-4.40.1/Regular/complete/Terminess\ \(TTF\)\ Nerd\ Font\ Complete.ttf`
* -> Middle image
* Uninstall Terminess and install newly patched Terminus with this PR in effect
* -> Bottom image
* All images 14 pt at 200% maginification after screenshot

But someone should test that with a terminal :grimacing:

**Comment by DoctorKnowsBetter** [comment]
@Finii Yes, there is such a problem, some terminals do not see bitmap layers in TTF fonts. Terminals that I use and tested by me (fonts are displayed correctly):
- xterm;
- lxterminal;
- alacritty.

**Comment by Finii** [comment]
So the fix works? Then i will merge?

**Comment by DoctorKnowsBetter** [comment]
@Finii I guess so. If someone does not display fonts correctly in the terminal, then the issue should be resolved with the developers of this terminal. Most terminals will not have these problems.

**Comment by Finii** [comment]
Great! Thanks for testing and for showing your fix! Without it we would not have the PR. :heart:
