### ISSUE TITLE
Add Kotlin icon

### ISSUE THREAD

**Issue by ignamartinoli** [ryanoasis/nerd-fonts#861]
- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**

It would be nice to have a Kotlin icon

**Describe the solution you'd like**

The addition of a Kotlin icon

**Describe alternatives you've considered**

Cry

**Additional context**

This is the latest official **Kotlin** icon

![kotlin](https://user-images.githubusercontent.com/103866722/177941491-1947c6b0-6e38-4880-8bd7-01dac36165df.png)

**Comment by Finii** [comment]
Would it not make (more) sense to add these programming language icons to the devicons?
https://github.com/vorillaz/devicons

Well, or rather https://github.com/file-icons/DevOpicons?

Otoh, they do not have Julia (why not?) and we add that ourselves. Strangeness.

Are you into Kotlin? What happened to the 2-colored icon? 
![image](https://user-images.githubusercontent.com/16012374/177971744-8b118306-6363-4e93-9565-262f87eef984.png)

\*opening svg editor\*

**Comment by ignamartinoli** [comment]
> Would it not make (more) sense to add these programming language icons to the devicons?
> https://github.com/vorillaz/devicons
> 
> Well, or rather https://github.com/file-icons/DevOpicons?

I didn't knew those projects, I mainly look at `nerd-fonts` because iirc `nvim-web-devicons` and `powerlevel10k` both uses it.

> Are you into Kotlin?

I like **Android** development and the language in general. It feels satisfying using it after being forced by university to write **Java**.

> What happened to the 2-colored icon?

It got changed this year (https://kotlinlang.org/docs/kotlin-brand-assets.html#kotlin-logo). Actually, I like the two-colored icon a ton more, I didn't suggested using it to not sound opinionated, but using a single color feels like a regression to me

**Comment by Finii** [comment]
Got that thing ready, but need time to create the PR...

![image](https://user-images.githubusercontent.com/16012374/178010747-6559600d-45e7-4c52-ae76-4421ec5500e2.png)

**Comment by ignamartinoli** [comment]
Thanks! What editor do you use for this? So the next time I can create the icon and directly do a PR?

**Comment by Finii** [comment]
`inkscape` to create the icon as `svg`, `fontforge` to patch it in.

In fact I searched for `kotlin logo svn`, found the colored icon, took that into InkScape and ... redrew the icon with the color icon in the background. The color icon has been drawn with 'thick lines' anyhow, that is not supported in fonts. There everything must be a border that encloses something. Fill it with 'unspecified' (will look black in InkScape).

**Comment by ignamartinoli** [comment]
Sounds good, thanks, I'll learn that workflow

**Comment by Finii** [comment]
> learn that workflow

Some hints can be found here https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md
And some here https://github.com/file-icons/DevOpicons/blob/master/README.md
And ... all over.

The most important thing as a beginner - imho - is that in fonts everything is an area surrounded by a closed stroke/border/edge (however that is called). Assume the lines you draw in `inkscape` to be invisible. Want a line? draw a very thin long box. All boxes will be filled. Two overlapping boxes will be not-filled in the intersection. Hmm. Maybe that does not make sense :-)
(Not all valid `svg`s are suitable for fonts, some features like line-thickness are meaningless in fonts.)
Whatever, you will see the result after importing into `fontforge`. There is View -> Show -> Preview in `fontforge`'s Outline-View.

Good luck :-)
