### ISSUE TITLE
font-patcher showing me oserror

### ISSUE THREAD

**Issue by human9182** [ryanoasis/nerd-fonts#864]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
When I run `fontforge -script font-patcher --fontawesome --glyphdir ./src/glyphs Inconsolata-Regular.ttf` I got this
```
Copyright (c) 2000-2022. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20220308
 Based on sources from 2022-03-11 17:46 UTC-ML-D-GDK3.
Core python package 'pkg_resources' not found: Cannot discover plugins
The following table(s) in the font have been ignored by FontForge
  Ignoring 'STAT' style attributes table
Use-my-metrics flag set on at least two components in glyph 631
No configfile given, skipping configfile related actions
Nerd Fonts Patcher v2.1.0 executing

The requested file, original-source.otf, does not exist
Traceback (most recent call last):
  File "/home/user/font-forge/font-patcher", line 1037, in <module>
    main()
  File "/home/user/font-forge/font-patcher", line 1032, in main
    patcher.patch()
  File "/home/user/font-forge/font-patcher", line 110, in patch
    symfont = fontforge.open(self.args.glyphdir + patch['Filename'])
OSError: Open failed
```
I didn't download the entire git since it's too big. What I did is run `mkdir -p src/glyphs/font-awesome` and downloaded the otfs from fontawesome website and put three of them(when you download and extract zip you get three otfs) in `src/glyphs/font-awesome` directory. The `src` directory is relative to `font-patcher`(both are in the same directory).

Expected behavior:
This shouldn't give not found error cause everything is fine to me.

#### 🔧 Setup

Font: Inconsolata-Regular.ttf
Source: Google Fonts
OS: arch linux

**Comment by Finii** [comment]
Will be fixed by #741 

Usually you should not download 'just' the `font-patcher` script. Of course you also should not download the whole repo. But there is a `FontPatcher.zip` on the Release page, that include the script and all symbol fonts.

But you are right, that bit of information is missing from the instructions: https://github.com/ryanoasis/nerd-fonts#option-8-patch-your-own-font :sob: 

I already tried to assemble all information here: #847, but did not yet came round to pour the into the actual README.me file. Sorry.

Is your problem / would your problem be solved by the information given in the discussion if it is in the main documentation?

**Comment by waydegg** [comment]
@human9182 I was dealing w/ a similar issue patching my own fonts, and I wrote an article [here](https://wayde.gg/articles/how-to-patch-a-font.html) detailing how to patch a custom font. Hope this helps!

**Comment by Finii** [comment]
Now (at least) a message is displayed:
```
Nerd Fonts: Can not find symbol glyph directory /home/fini/git/src/glyphs/ (probably you need to download the src/glyphs/ directory?)
```
