### ISSUE TITLE
Add Deno Icon

### ISSUE THREAD

**Issue by suimong** [ryanoasis/nerd-fonts#869]
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
I use starship with nerd fonts presets and it would be nice to have a deno icon built in nerd fonts.

**Describe the solution you'd like**
Deno icon is part of the simpleicon collection (ref: https://simpleicons.org/icons/deno.svg). The source of icon comes from the official Deno repo, per this issue (https://github.com/denoland/deno/issues/1823)

**Comment by Finii** [comment]
Related:
* https://github.com/ryanoasis/nerd-fonts/discussions/716#discussion-3742714 (bottom of that 1st comment)
* #818

**Comment by suimong** [comment]
Thanks @Finii for the quick reply! Looking forward to v3!

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095

**Comment by Finii** [comment]
This should probably be in Font logos instead.
Font logos subsequently will be included here.

**Comment by Finii** [comment]
<img width="511" alt="Screenshot 2024-11-20 at 14 33 11" src="https://github.com/user-attachments/assets/2c22c793-3459-415a-ad46-29a870b85324">
