### ISSUE TITLE
Add more fruit icons

### ISSUE THREAD

**Issue by naturalmechanics** [ryanoasis/nerd-fonts#871]
**Requirements**

- [ x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [ x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [ x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like a glyph for a melon, and berry fruit. There are apple, pear, peach, cherry, banana - a few more fruits would be nice.

**Describe alternatives you've considered**
For now - i am using svg cliparts. But having them in the font would be nice.

**Comment by ChiefMikeK** [comment]
![Symbola-sample](https://user-images.githubusercontent.com/20070053/181270565-135bdcce-a736-4353-9136-108b0ecdbaff.png)
melon-water melon-strawbery-berries rendered with symbola.otf (2020 edition)

**Comment by Finii** [comment]
Thanks @ChiefMikeK for the nice font link!

I am a bit in doubt that there are many (or at least more then 2.5) people who would ever use fruit icons.
This also did not get any upvote yet.

So I guess it would be better to not add them, as every addition increases font sizes for everyone, increases the maintenance work for years to come, and compete with the scarce codepoints resource.
