### ISSUE TITLE
NF icons in Ubuntu gnome terminal are small

### ISSUE THREAD

**Issue by sabah1994** [ryanoasis/nerd-fonts#876]
Hi, 

Icons in Ubuntu terminal are smaller in comparison to text. Also, on MacOs (iTerm2) they seem to be the right size.

Experienced behavior: 
Icons in Ubuntu terminal
Notice how small debug (red icon) is compared to 0.
![Screenshot from 2022-08-12 13-56-11](https://user-images.githubusercontent.com/73726199/184377044-048500e1-3ee8-4868-a4d3-89fe1c219cea.png)

Expected behavior:
Icons in MacOs (iterm2)
<img width="439" alt="Screenshot 2022-08-12 at 13 43 18" src="https://user-images.githubusercontent.com/73726199/184376459-32ec8993-dbe7-4804-8fb6-c4907881476d.png">

Example symbols:
f188


#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   JetBrainsMonoNL Nerd Font Mono 

   - _Where did you get the file from (download link, self patched, source downloaded from link...)_
      From this repo
    `cd ~ && git clone --filter=blob:none --sparse git@github.com:ryanoasis/nerd-fonts
    cd nerd-fonts
    git sparse-checkout add patched-fonts/JetBrainsMono install.sh
    ./install.sh JetBrainsMono`

- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?
   gnome

- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

**Comment by Finii** [comment]
I did not check in detail, but I guess:

> JetBrainsMonoNL Nerd Font Mono

The "Nerd Font Mono" variants have symbols that are downsized to fit into one 'cell'. A lot people want the symbols to be wider than one cell. One cell is approximately the width of `M` for example.

See this fast example:
![image](https://user-images.githubusercontent.com/16012374/184615997-29645855-6857-4cc5-8208-274ae5e6f855.png)

The bug-thingys are so wide I could never align 3 of them above `1:1`. But that is what _Nerd Font Mono_ is designed to do.

You probably want to use the non-Mono variant instead, i.e. _JetBrainsMonoNL Nerd Font_

I guess on Mac you use the non-Mono variant.

**Comment by sabah1994** [comment]
You are right. 

On gnome terminal it doesn't give you the option to select non-mono font. 
I ended up using "kitty" terminal and by specifying non-mono it solved my issue. 
Thanks, again
