### ISSUE TITLE
CaskaydiaCove NF: Block glyphs starting at U+2588 (present in Cascadia Code) are missing

### ISSUE THREAD

**Issue by sba923** [ryanoasis/nerd-fonts#883]
#### 🗹 Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

The latest `winget` uses glyphs U+2588 (Full Block) through U+258F (Left One Eight Block) to display its progress bar.

The result is incorrect when using `CaskaydiaCove NF`:

![image](https://user-images.githubusercontent.com/12860484/185506226-7c851211-ab6d-4b2a-99e1-b418fbd70cdf.png)

Expected behavior:

Using `CaskaydiaCove NF` should yield the same result as with its "parent font" `Cascadia Code`:

![image](https://user-images.githubusercontent.com/12860484/185506333-011efe2d-dac7-4916-a6c0-315b06a2f992.png)

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_: CaskaydiaCove NF version 1909.16
   - _Please give the full filename_: `Caskaydia Cove Nerd Font Complete Mono Windows Compatible.ttf`
   - _Where did you get the file from (download link, self patched, source downloaded from link...)_: downloaded, can't remember source (see below for the behavior with a more recent version)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_: Windows Terminal Preview 1.15.2003.0
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_: Windows 11 version 10.0.22000.856.amd64fre.co_release.210604-1628

#### ★ Screenshots (Optional)

Windows Terminal is configured as follows:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/12860484/185507054-f1fff88b-6900-418e-9d09-4a31bbe844df.png">

The Character Map application reports those glyphs don't exist at all in `CaskaydiaCove NF` whereas they do exist in `Cascadia Code`:

![image](https://user-images.githubusercontent.com/12860484/185507217-28275c86-50f8-45ef-a6e4-043cd61ba01f.png)

![image](https://user-images.githubusercontent.com/12860484/185507230-e1ddfbf5-7ebb-42f2-965b-303b8c4273a4.png)

With a more recent version of the font downloaded from https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/CascadiaCode/Regular/complete/Caskaydia%20Cove%20Regular%20Nerd%20Font%20Complete%20Windows%20Compatible.otf the glyphs are also not rendered as expected:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/12860484/185507943-65b2cd93-5f87-4586-8256-02013f683737.png">

**Comment by Finii** [comment]
This is because the _Cascadia Code_ on which that font is based is so old.

Will be fixed by the _Cascadia Code update_ #723, whose artifacts can be downloaded for testing [here](https://github.com/Finii/nerd-fonts/tree/feature/cascadia-2111.01-patched/patched-fonts/CascadiaCode).

Will be hopefully in `master` [soon](https://github.com/ryanoasis/nerd-fonts/discussions/881)

**Comment by sba923** [comment]
> This is because the _Cascadia Code_ on which that font is based is so old.
> 
> Will be fixed by the _Cascadia Code update_ #723, whose artifacts can be downloaded for testing [here](https://github.com/Finii/nerd-fonts/tree/feature/cascadia-2111.01-patched/patched-fonts/CascadiaCode).
> 
> Will be hopefully in `master` [soon](https://github.com/ryanoasis/nerd-fonts/discussions/881)

Great! 

Test with `Caskaydia Cove Nerd Font Complete Windows Compatible Regular.otf` OK:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/12860484/185585857-f43baacd-197a-418d-b676-2f9a13ce4823.png">
