### ISSUE TITLE
Can't find the Kali-Linux icon

### ISSUE THREAD

**Issue by shivangswain** [ryanoasis/nerd-fonts#888]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behaviour:

I cannot find the Kali-Linux icon from the font-logos library in the latest release and pre-release of nerd fonts. I am using CodeNewRoman if that is of any help and I tried to manually type in all the references to Kali-Linux I could find in the PRs of this and the font-logos repo.

Expected behavior:

Find Kali-Linux in the font more easily

Example symbols:

`\f12d`

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_: Code New Roman Bold Nerd Font Complete Mono Windows Compatible.otf
   - _Where did you get the file from (download link, self patched, source downloaded from link...)_: https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC/CodeNewRoman.zip
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_: Windows Terminal
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_: Windows

**Comment by Finii** [comment]
Why are you expecting it at `F12D`?

According to Font Logos it is at `F327`
https://github.com/Lukas-W/font-logos#usage
![image](https://user-images.githubusercontent.com/16012374/185871688-65fb0e77-8993-45af-a521-76abde238096.png)

and there it is:
![image](https://user-images.githubusercontent.com/16012374/185872060-6a31da07-3501-4376-812c-aa475a8f47ea.png)

**Comment by shivangswain** [comment]
Still can't find it there, the Nerd Font only goes till F31C:

![image](https://user-images.githubusercontent.com/33395916/185876112-95bd6f68-bde5-4ad7-8390-eec168ce516a.png)
![image](https://user-images.githubusercontent.com/33395916/185876639-524fdd27-e1a9-46f9-9220-3f2c17d7e8d6.png)

**Comment by Finii** [comment]
Checked the current https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC/CodeNewRoman.zip just now (before I just checked it in the git repo).

![image](https://user-images.githubusercontent.com/16012374/185879615-0a867fd7-02d5-4e22-bbae-1b6b3737ba69.png)

It's there?

Did you download the zip archive recently? The last update was
![image](https://user-images.githubusercontent.com/16012374/185880052-f68948b6-b3ae-43e4-8802-e199620373de.png)

**Comment by shivangswain** [comment]
Okay, I downloaded this 2 day-old font package and it has the Kali-Linux icon in it. Thanks for the help. The icon looks weird when rendered but I guess that'll get fixed when nerd-fonts updates its font-logos version. I'll be closing the issue now.

**Comment by Finii** [comment]
We just updated. Please specify 'weird' :->

This should be ok, because I am about to release the RC :grimacing:

**Comment by shivangswain** [comment]
I can't describe it well, it just looks like the size and alignment are messed up. Here:

![image](https://user-images.githubusercontent.com/33395916/185885227-1e114099-6d14-4728-8013-1252bc02c5e5.png)

![image](https://user-images.githubusercontent.com/33395916/185885512-cdf8d247-88fe-408b-be4b-a13655340257.png)

![image](https://user-images.githubusercontent.com/33395916/185886289-9ef9947c-d2d1-403d-879e-d93ca69c7221.png)

**Comment by Finii** [comment]
Thank you, will check

**Comment by Finii** [comment]
What we see in the screenshot is `Windows Terminal` magic glyph rescaling. It shrinks the symbol to fit into exactly one cell (and not being very smart about the alignment at that). This is triggered under some circumstances.

The Ubuntu icon on the other hand is _not_ scaled down.

Maybe it is because Kali is more than 2 cells big, while Ubuntu is less the 2 (but more than 1) cell big.
This reminds me of #748. Let me start up a Windows box...

Well, even in the source, the Kali icon is so much more big then the others, so that we can no use our own `ScaleGlyph` mechanism :-/

![image](https://user-images.githubusercontent.com/16012374/185932042-c2e6ab58-c003-4cb2-a104-4d7199b7d81b.png)
_(683 vs 512)_

Indeed `Windows Terminal` lists both as `ambigous width` characters: https://github.com/microsoft/terminal/blob/deffbbc7f52a3e41aaf760977a907d326382848b/src/types/CodepointWidthDetector.cpp#L246

**Comment by Finii** [comment]
Done in latest release.
