### ISSUE TITLE
Some fonts displays double as wide as before

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#895]
@Finii My Nerd Fonts are managed by a Scoop bucket and it just pushed out an update for many of the NF fonts, Mononoki included, so I assumed it had been: https://github.com/matthewjberger/scoop-nerd-fonts/commit/dfded9fe717498630a4f106ef8e62d49d8dca550. After installing the font and restarting the system, at least _something_ has changed because the font in VS Code/Codium now displays double as wide as before:

![VSCodium](https://user-images.githubusercontent.com/25013746/186925513-9d7ccd7a-4d91-4f7c-816c-c6109b506271.jpg)

Not sure why, but other programs seem to be unaffected by this bug, and it can be essentially mitigated in Code/Codium by using `editor.letterSpacing": -5`.

Also, the other NF fonts just updated display the same double-wide behaviour: Switching to Consolas renders with the correct letter spacing. Maybe Code/Codium has a preference that I've altered which is affecting the NF fonts' rendering, but why not Consolas for example? Hmm.

_Originally posted by @redactedscribe in https://github.com/ryanoasis/nerd-fonts/issues/575#issuecomment-1228557605_

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/186953317-ea03a870-9c3b-4319-af3d-71a4cf665ca0.png)

I can not see an issue with the non-mono font.

Examining reason.

**Comment by Finii** [comment]
Released anew ... @redactedscribe https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.2.1

**Comment by redactedscribe** [comment]
Thanks for the quick fix. I'm hoping [the Scoop bucket](https://github.com/matthewjberger/scoop-nerd-fonts) will push out the 2.2.1 update as that'll be the least messy way for me to test it. Once it does, I can confirm the fix.

**Comment by adelarsq** [comment]
@Finii Good job! I was thinking that was some miss config on my side. 😄 
Thanks for the quick update. 🥇

**Comment by redactedscribe** [comment]
> Once it does, I can confirm the fix.

Fixed. Thanks!

**Comment by blacktop** [comment]
I think Hack Mono has the same issue?

**Comment by Finii** [comment]
Hack Mono `v2.2.1`?

Looks good at first glance:

![image](https://user-images.githubusercontent.com/16012374/187086149-7b91cbc9-317f-4a32-8de9-7805a73a3e10.png)

@blacktop Please check which version you have.

**Comment by blacktop** [comment]
![hack](https://user-images.githubusercontent.com/6118188/187089341-84126d74-ecd9-4d9c-94cd-5fa38461db9e.png)

Looks like I'm still on 2.2.0, I'll try and update, but I think brew hasn't updated it yet?

**Comment by Finii** [comment]
> Looks like I'm still on 2.2.0, I'll try and update, but I think brew hasn't updated it yet?

The update is here https://github.com/Homebrew/homebrew-cask-fonts/commit/7530545fbb7424a5edd896467670b787ee387b55

**Comment by adastx** [comment]
Jet Brains Mono doesn't look right after the update.

**Comment by Finii** [comment]
@adastx can you provide a screenshot?
Shure you are on `v2.2.1` and not `v2.2.0`?
Reboot or similar after update?

**Comment by adastx** [comment]
Here are some screenshots. The issue is more subtle than what people were having before with mono fonts.

It's most obvious by looking at the arrow symbol.

## 2.1.0
![2 1 0](https://user-images.githubusercontent.com/56338480/187599904-6be696e6-e3cd-4cf0-b9d7-b8233464f56f.png)

## 2.2.1
![2 2 1](https://user-images.githubusercontent.com/56338480/187599907-ee37539c-e499-4bcd-b364-20b7e3abda06.png)

**Comment by Finii** [comment]
Ah, you mean *vertically*?

![image](https://user-images.githubusercontent.com/16012374/187608461-767c033e-73cc-499c-b41b-2b4232c76b43.png)

Or do you mean the green arrow? Are you using `Windows Terminal`?

**Comment by adastx** [comment]
Im using alacritty on arch linux. vertically and the green arrow...

**Comment by Finii** [comment]
> `Windows Terminal`

unlikely if you are on Arch. Hmm.

Sure you do not use the `Nerd Font Mono` variant?

**Comment by adastx** [comment]
![2022-08-31-082817_398x94_scrot](https://user-images.githubusercontent.com/56338480/187608858-a50623bb-fa62-4ddc-8d9c-2233ba066c51.png)

from my alacritty.yml

**Comment by adastx** [comment]
> Ah, you mean _vertically_?
> 
> Or do you mean the green arrow? Are you using `Windows Terminal`?

The real issue is that there is a difference between the two pictures.
That is what I'm trying to fix.
The two images should be the same on both versions. Agree?

**Comment by Finii** [comment]
> The two images should be the same on both versions. Agree?

Not necessarily. Maybe the source changed or bugs got fixed.
The 2.2.1 version should look like JetBrains 2.251 (except added symbols).
The 2.1.0 version is based on JetBrains 1.0.2.

**Comment by Finii** [comment]
The vertical stuff did change in the source (i.e. JetBrains):

![image](https://user-images.githubusercontent.com/16012374/187611654-c4ea8d59-8509-4f06-854e-b0520b0aa511.png)

And I guess the green-arrow thing is something about #900

**Comment by adastx** [comment]
Ok, thanks for the info. I guess I'll just be sticking to 2.1.0 for now.
