### ISSUE TITLE
Since 2.2.1, character spacing for jetbrainsmono-nf is incorrect

### ISSUE THREAD

**Issue by g-berthiaume** [ryanoasis/nerd-fonts#899]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
After upgrading from 2.1.0 to 2.2.1, the jetbrainsmono-nf characters have incorrect spacing.

Expected behavior:
Correct spacing.

Example symbols:
(See screenshot)

#### 🔧 Your Setup

- jetbrainsmono-nf installed with `scoop`
- VsCode
- Windows 10 pro
![image](https://user-images.githubusercontent.com/19377511/187212746-e882300b-61b2-4fc7-8e9a-d8fa710cc355.png)

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/19377511/187212669-d57bed02-cb4f-4cff-b570-364d98a0ad67.png)

**Comment by g-berthiaume** [comment]
> Did you reboot or something?

I have a meeting, but just after that, I'm going to test that theory.

**Comment by adastx** [comment]
I'm having more subtle issues but with the same font. See my post in #895

**Comment by Finii** [comment]
> I have a meeting, but just after that, I'm going to test that theory.

@g-berthiaume Any chance yet? :-)

**Comment by g-berthiaume** [comment]
It seems to be fixed. 
My apology for the false flag.

I'm not sure why this behaviour would arise. 
If you have recommended readings let me know.
