### ISSUE TITLE
Add GohuFont

### ISSUE THREAD

**Issue by xdaimon** [ryanoasis/nerd-fonts#90]
Could you add Gohufont to this collection?

https://github.com/hchargois/gohufont

it has a very simple license, one of my favorites. :)

**Comment by ryanoasis** [comment]
@xdaimon Yep we can do that :smile: 

The license is very... um.. permissive :stuck_out_tongue_closed_eyes: 

--

I see there is a TTF format available on the website, that is the one that will probably be easiest to work with given the current state of the patcher
