### ISSUE TITLE
Failing to update/download.

### ISSUE THREAD

**Issue by LeonardoBeleffi** [ryanoasis/nerd-fonts#902]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful.
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help.
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help.

#### 🎯 Subject of the issue

Experienced behavior:
when trying to download **nerd-fonts-dejavu-complete-2.2.1-1** from [the aur](https://aur.archlinux.org/packages/nerd-fonts-dejavu-complete), the installation process stops.

Expected behavior:
correct download and installation.

#### 🔧 Your Setup

- Dejavu:
   - nerd-fonts-dejavu-complete-2.2.1-1;
   - got it with paru package manager. [Here](https://aur.archlinux.org/packages/nerd-fonts-dejavu-complete) the reference site.
- Yakuake and Konsole.
- Arch linux.

`$ paru nerd-fonts-dejavu-complete`
```bash
1 aur/nerd-fonts-dejavu-complete 2.2.1-1 [+19 ~0.03]
    All variants of Nerd-Font-patched DejaVu Sans Mono
:: Packages to install (eg: 1 2 3, 1-3):
```
`1`
```bash
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) nerd-fonts-dejavu-complete-2.2.1-1

:: Proceed to review? [Y/n]: 
```
`y`
```bash
:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: nerd-fonts-dejavu-complete 2.2.1-1 (2022-08-31T01:59:05 CEST)
==> Retrieving sources...
  -> Found DejaVu-Sans-Mono-Bold-Nerd-Font-Complete.ttf
  -> Found DejaVu-Sans-Mono-Bold-Nerd-Font-Complete-Mono.ttf
  -> Found DejaVu-Sans-Mono-Bold-Oblique-Nerd-Font-Complete-Mono.ttf
  -> Found DejaVu-Sans-Mono-Bold-Oblique-Nerd-Font-Complete.ttf
  -> Found DejaVu-Sans-Mono-Oblique-Nerd-Font-Complete.ttf
  -> Found DejaVu-Sans-Mono-Oblique-Nerd-Font-Complete-Mono.ttf
  -> Found DejaVu-Sans-Mono-Nerd-Font-Complete.ttf
  -> Found DejaVu-Sans-Mono-Nerd-Font-Complete-Mono.ttf
  -> Found LICENSE
==> Validating source files with sha512sums...
    DejaVu-Sans-Mono-Bold-Nerd-Font-Complete.ttf ... FAILED
    DejaVu-Sans-Mono-Bold-Nerd-Font-Complete-Mono.ttf ... FAILED
    DejaVu-Sans-Mono-Bold-Oblique-Nerd-Font-Complete-Mono.ttf ... FAILED
    DejaVu-Sans-Mono-Bold-Oblique-Nerd-Font-Complete.ttf ... FAILED
    DejaVu-Sans-Mono-Oblique-Nerd-Font-Complete.ttf ... FAILED
    DejaVu-Sans-Mono-Oblique-Nerd-Font-Complete-Mono.ttf ... FAILED
    DejaVu-Sans-Mono-Nerd-Font-Complete.ttf ... FAILED
    DejaVu-Sans-Mono-Nerd-Font-Complete-Mono.ttf ... FAILED
    LICENSE ... FAILED
==> ERROR: One or more files did not pass the validity check!
error: failed to download sources for 'nerd-fonts-dejavu-complete-2.2.1-1': 
error: packages failed to build: nerd-fonts-dejavu-complete-2.2.1-1
```

**Comment by Finii** [comment]
I do not know what is going wrong there.

This is the PKGBUID you referenced
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nerd-fonts-dejavu-complete

```
# Maintainer: Knut Ahlers <knut at ahlers dot me>
# Contributor: Tiago Brait <tiagobrait AT gmail DOT com>

pkgname=nerd-fonts-dejavu-complete
pkgver=2.2.1
pkgrel=1
pkgdesc="All variants of Nerd-Font-patched DejaVu Sans Mono"
arch=('any')
url="https://github.com/ryanoasis/nerd-fonts"
_raw_base_url="https://raw.githubusercontent.com/ryanoasis/nerd-fonts/v${pkgver}"
_raw_font_url="${_raw_base_url}/patched-fonts/DejaVuSansMono"
license=(MIT)
provides=(ttf-font)
source=(
  "${pkgname}-${pkgver}_DejaVu-Sans-Mono-Bold-Nerd-Font-Complete.ttf::${_raw_font_url}/Bold/complete/DejaVu%20Sans%20Mono%20Bold%20Nerd%20Font%20Complete.ttf"
  "${pkgname}-${pkgver}_DejaVu-Sans-Mono-Bold-Nerd-Font-Complete-Mono.ttf::${_raw_font_url}/Bold/complete/DejaVu%20Sans%20Mono%20Bold%20Nerd%20Font%20Complete%20Mono.ttf"

  "${pkgname}-${pkgver}_DejaVu-Sans-Mono-Bold-Oblique-Nerd-Font-Complete-Mono.ttf::${_raw_font_url}/Bold-Italic/complete/DejaVu%20Sans%20Mono%20Bold%20Oblique%20Nerd%20Font%20Complete%20Mono.ttf"
  "${pkgname}-${pkgver}_DejaVu-Sans-Mono-Bold-Oblique-Nerd-Font-Complete.ttf::${_raw_font_url}/Bold-Italic/complete/DejaVu%20Sans%20Mono%20Bold%20Oblique%20Nerd%20Font%20Complete.ttf"

  "${pkgname}-${pkgver}_DejaVu-Sans-Mono-Oblique-Nerd-Font-Complete.ttf::${_raw_font_url}/Italic/complete/DejaVu%20Sans%20Mono%20Oblique%20Nerd%20Font%20Complete.ttf"
  "${pkgname}-${pkgver}_DejaVu-Sans-Mono-Oblique-Nerd-Font-Complete-Mono.ttf::${_raw_font_url}/Italic/complete/DejaVu%20Sans%20Mono%20Oblique%20Nerd%20Font%20Complete%20Mono.ttf"

  "${pkgname}-${pkgver}_DejaVu-Sans-Mono-Nerd-Font-Complete.ttf::${_raw_font_url}/Regular/complete/DejaVu%20Sans%20Mono%20Nerd%20Font%20Complete.ttf"
  "${pkgname}-${pkgver}_DejaVu-Sans-Mono-Nerd-Font-Complete-Mono.ttf::${_raw_font_url}/Regular/complete/DejaVu%20Sans%20Mono%20Nerd%20Font%20Complete%20Mono.ttf"

  "${pkgname}-${pkgver}_LICENSE::${_raw_base_url}/LICENSE"
)
sha512sums=('2d03d7a8692d5826e9103b04e8bcf6ae0943fbc5a893ceee43e31ec72168c94dcd0bf2592264332e7d229383ac464b2922e14b53dc761574a407f5e095292f1f'
            'fd137e1be01519ceb91cdcd38aad4a3453d6bd390c2ec71a1900acf5d4763b636fa3934524f49e87989548451cce090be8c1b29c7fa73fca0f86714d1827a1a2'
            '8a4ba7bdfe001c350149f75c36efbfcbb948dd4d515fe627224c697b68558046054a6927b9a1f807e65a20482b3203a8f1a2e70b0a7defa9362fa9710114da84'
            'c83a311075c4c52358a9c029802cbfb65c56b6e590193f9216e35f696192487dbc70707dc2996da5a4e76de79081a0a73d8464a87082f43a8d945756d779a844'
            'bb8ee4fe9e821486097f0e0749424e12dfd91e78b650271bd1368db8974f0ff9362b6791a55416f5ef43ed3678874b99348efdcdc45026d5b2ac34fa5d8a85db'
            '6519ea0ca623d19ebd133d875d271d523735008b8510f2cdbbf20beca31e4d62544360f7ebbbc49f0e62df6456ce847921a724971b9261336354722080976d20'
            '79e06decba0613126fa386b3be7866fd91d8a715d235772cb949d0dd0af455eed998593b2605baf9f3dc422c96a52ed80630aadeedcbfa082f47d410c56da410'
            'bd4922c080690d852b9408aab18f66d78fe785fb6df470ccb9c044b6ea2ebc043996de16ddd80421394a49b6c8ee7e4ca45e1658860abc43f9564e09202359d3'
            '941169ae9f04d4d706fead04cc2391c57b681c934f5d646a1444d9a1240ba42500a5ea79ae5d1bb172666f6d48d44d95fa757a5785593088d887736d58f4cc82')
```

Tried the 2nd from bottom (the Regular normal font):

![image](https://user-images.githubusercontent.com/16012374/187747985-ded5e100-4d3b-4f12-9f0c-cdc2ec06fb2d.png)

The hash matches. Well, at least the first digits `79e06`

**Comment by Finii** [comment]
https://aur.archlinux.org/packages/nerd-fonts-dejavu-complete#comment-879549

**Comment by Finii** [comment]
Maybe this?

https://aur.archlinux.org/packages/nerd-fonts-dejavu-complete#comment-727918

The removal stuff changed.

**Comment by LeonardoBeleffi** [comment]
I fond out that the checksum of LICENSE.txt does not match

**Comment by LeonardoBeleffi** [comment]
> https://aur.archlinux.org/packages/nerd-fonts-dejavu-complete#comment-879549

Yes, exactly the same errors.

**Comment by LeonardoBeleffi** [comment]
> Maybe this?
> 
> https://aur.archlinux.org/packages/nerd-fonts-dejavu-complete#comment-727918
> 
> The removal stuff changed.

Removing the cached package worked, thanks!
Is there a chance you know why that occurred?
2 days ago I updated and this error came out, so I tried removing the package (obviously without removing the cache). I hadn't been able to reinstall it since then.

**Comment by Finii** [comment]
> Is there a chance you know why that occurred?

Sorry, not really. The package is maintained over at AUR. You should ask there (Knut or Luzifer?).

Knut addid this commit to the package [`Add workaround for people not building with clean source` (link)](https://aur.archlinux.org/cgit/aur.git/commit/?h=nerd-fonts-dejavu-complete&id=07d6dabbbdf5978fb9142d06f7e8c03214c29f14), but it seems to be not working? Unfortunately his commit message is ... spartan.

**Comment by Finii** [comment]
It's just `LICENCE` that has the wrong checksum? The messages you pasted look different.

Anyhow, this part of Knut's commit looks fishy, at least for my untrained eye:

```diff
diff --git a/.gitignore b/.gitignore
index b3ff5d176e7..cd6689ec0b0 100644
--- a/[.gitignore](https://aur.archlinux.org/cgit/aur.git/tree/.gitignore?h=nerd-fonts-dejavu-complete&id=430c64c16ff56c96274f8d0b313a50fddb713eef)
+++ b/[.gitignore](https://aur.archlinux.org/cgit/aur.git/tree/.gitignore?h=nerd-fonts-dejavu-complete&id=07d6dabbbdf5978fb9142d06f7e8c03214c29f14)
@@ -17,5 +17,6 @@ src/
 *.sig
 
 LICENSE
+*LICENSE
 
 .AURINFO
```

If you add `*LICENCE` to  the gitignore, the `LICENCE` (without glob) line becomes obsolete, why not remove?

But that is not the reason ;-)

And then, why is that in gitignore at all? :grimacing:

**Comment by Finii** [comment]
Maybe ... his fix did not take into account re-releases of the AUR package, which `2.2.1-1` is (it is the second `2.2.1`):

```diff
 provides=(ttf-font)
 source=(
-  "${pkgname}-${pkgver}_DejaVu-Sans-Mono-Bold-Ne ...
+  "${pkgname}-${pkgver}-${pkgrel}_DejaVu-Sans-Mono-Bold-Ne ...
```

**Comment by Finii** [comment]
Well, a lot of AUR packages seem to have that issue :-o

Added a comment over there https://aur.archlinux.org/packages/nerd-fonts-dejavu-complete#comment-879914

**Comment by LeonardoBeleffi** [comment]
> It's just `LICENCE` that has the wrong checksum? The messages you pasted look different.
> 
> Anyhow, this part of Knut's commit looks fishy, at least for my untrained eye:
> 
> ```diff
> diff --git a/.gitignore b/.gitignore
> index b3ff5d176e7..cd6689ec0b0 100644
> --- a/[.gitignore](https://aur.archlinux.org/cgit/aur.git/tree/.gitignore?h=nerd-fonts-dejavu-complete&id=430c64c16ff56c96274f8d0b313a50fddb713eef)
> +++ b/[.gitignore](https://aur.archlinux.org/cgit/aur.git/tree/.gitignore?h=nerd-fonts-dejavu-complete&id=07d6dabbbdf5978fb9142d06f7e8c03214c29f14)
> @@ -17,5 +17,6 @@ src/
>  *.sig
>  
>  LICENSE
> +*LICENSE
>  
>  .AURINFO
> ```
> 
> If you add `*LICENCE` to the gitignore, the `LICENCE` (without glob) line becomes obsolete, why not remove?
> 
> But that is not the reason ;-)
> 
> And then, why is that in gitignore at all? grimacing

Well, I removed the post because I noticed I was wrong: even LICENSE's checksum matched.

Anyway thank you for your time.

Have a great day!
