### ISSUE TITLE
Why is FiraCode font in .otf format in v2.1.0 and only .ttf in v2.2.1?

### ISSUE THREAD

**Issue by DustinWin** [ryanoasis/nerd-fonts#903]
For example：
v2.1.0
![QQ截图20220831091448](https://user-images.githubusercontent.com/45238096/187571341-3af3a2c9-e755-483f-afd1-930df50cd10c.png)

v2.2.1
![QQ截图20220831091503](https://user-images.githubusercontent.com/45238096/187571363-8409155b-ba6e-4b23-b381-36ce8505988c.png)

**Comment by Finii** [comment]
Well, the sources are just `ttf` files: https://github.com/ryanoasis/nerd-fonts/tree/master/src/unpatched-fonts/FiraCode/Regular

and the font type is not changed on patching.

Un updating to 5.2 the `otf`s have been dropped with Fira Code 5.2
* #497 : 338497d

and kept that way for Fira Code 6.2:
* #704 

Maybe @gitfool knows something? Although I personally think we do not need both formats. `ttf` is enough if there are no OTF features in the source; and nowadays everyone can use `otf`, so no need to provide _also_ `ttf`.

Why do you need it?

**Comment by DustinWin** [comment]
> Well, the sources are just `ttf` files: https://github.com/ryanoasis/nerd-fonts/tree/master/src/unpatched-fonts/FiraCode/Regular
> 
> and the font type is not changed on patching.
> 
> On updating to 5.2 the `otf`s have been dropped with Fira Code 5.2
> 
> * [Update Fira Code to latest version #497](https://github.com/ryanoasis/nerd-fonts/pull/497) : [338497d](https://github.com/ryanoasis/nerd-fonts/commit/338497d1e9301b949063ea749403d048b5a7240d)
> 
> and kept that way for Fira Code 6.2:
> 
> * [Update Fira Code to latest version #704](https://github.com/ryanoasis/nerd-fonts/pull/704)
> 
> Maybe @gitfool knows something? Although I personally think we do not need both formats. `ttf` is enough if there are no OTF features in the source; and nowadays everyone can use `otf`, so no need to provide _also_ `ttf`.
> 
> Why do you need it?

Thanks for your answer. I'm just asking, it doesn't have to be in .otf format.
