### ISSUE TITLE
Add Hacklang icon

### ISSUE THREAD

**Issue by 4e554c4c** [ryanoasis/nerd-fonts#904]
**Requirements**
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
I write a lot of Hack code, but the closest icon in nerd-fonts is the php elePHPant. 

**Describe the solution you'd like**
I would like to have a Hacklang icon in nerd-fonts

**Describe alternatives you've considered**
I have considered upstreaming the icon to one of the fonts that nerd-fonts sources, but none seem as viable as adding it to this project.

**Additional context**
The Hacklang icon and other artifacts can be found on the [hacklang.org](https://hacklang.org/) website, which is licensed CC-BY and is [open-source](https://github.com/hhvm/hacklang.org) on Github.
The icon that is probably desired is
<details>
  <summary> Hack image</summary>
  <img src="https://raw.githubusercontent.com/hhvm/hacklang.org/main/website/static/img/hack.svg">
</details>

**Comment by Finii** [comment]
Solved via #978
