### ISSUE TITLE
add manjari font to font collection 

### ISSUE THREAD

**Issue by nerdpanda-ir** [ryanoasis/nerd-fonts#913]
hello 
is it possible add this font 
``https://fonts.google.com/specimen/Manjari ``
and add ligatures to that ? 

manjari font is very round !!!! 
![image](https://user-images.githubusercontent.com/39291525/188411687-978e7714-94c3-4424-b5bb-07656904b690.png)

**Comment by Finii** [comment]
Nerd Font does not add ligatures. What do you mean?

**Comment by nerdpanda-ir** [comment]
@Finii 
manjari is not have ligatures 
can nerd font  add ligatures to that : 
![image](https://user-images.githubusercontent.com/39291525/188425978-c6b344e4-ed11-46af-8f0f-ac1cf88dfdd6.png)
and add to nerd font collection ?

**Comment by Finii** [comment]
> can you add ligatures to that

Well that is not the purpose of Nerd Fonts. So sorry, the answer is no.
