### ISSUE TITLE
Nerd Font Mono font with too-wide glyphs

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#917]
Some CI warning, need to check it out

#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
```
Nerd Fonts Patcher v2.2.2 (3.0.5) executing
  Warning: Scaled glyph U+F077 wider than one monospace width (977 / 976 (overlap None))
  Warning: Scaled glyph U+F078 wider than one monospace width (977 / 976 (overlap None))
Done with Patch Sets, generating font...
Changing flags from 0x1F to 0x17
Changing lowestRecPPEM from 8 to 6
Generated: Noto Serif SemiCondensed Medium Nerd Font Complete Mono in '/home/runner/work/nerd-fonts/nerd-fonts/patched-fonts/Noto/Serif/complete//Noto Serif SemiCondensed Medium Nerd Font Complete Mono.ttf'
```

Expected behavior:
no warning
#### 🔧 Your Setup

This is the Nerd Font Github CI itself

#### ★ Screenshots (Optional)

https://github.com/ryanoasis/nerd-fonts/actions/runs/3007632280 `build(Noto)` line 5066 for example

**Comment by blacktop** [comment]
It looks like it happened again w/ `font-meslo-lg-nerd-font` as well

**Comment by Finii** [comment]
> It looks like it happened again w/ `font-meslo-lg-nerd-font` as well

Apart from the warning, can you elaborate on the effect you see?

**Comment by Finii** [comment]
Ah, something wrong with the scale group code? Codes were `F077` and `F078`.

```python
        FONTA_SCALE_LIST = {'GlyphsToScale': [
            [0xf005, 0xf006, 0xf089], # star, star empty, half star
            range(0xf026, 0xf028 + 1), # volume off, down, up
            range(0xf02b, 0xf02c + 1), # tag, tags
            range(0xf031, 0xf035 + 1), # font et al
            range(0xf044, 0xf046 + 1), # edit, share, check (boxes)
            range(0xf048, 0xf052 + 1), # multimedia buttons
            range(0xf060, 0xf063 + 1), # arrows
            [0xf053, 0xf054, 0xf077, 0xf078], # chevron all directions
```

**Comment by cprivitere** [comment]
> > It looks like it happened again w/ `font-meslo-lg-nerd-font` as well
> 
> Apart from the warning, can you elaborate on the effect you see?

Not 100% sure this is the same issue, but after the 2.2.2 update all the glyphs in meslo-lg are smaller than they were on 2.2.1.

**Comment by Finii** [comment]
@blacktop @cprivitere There are many fonts in that package? I would need more details, in fact best would be to open a new issue and answer all the questions in the issue template.

**This** issue is about to be closed, fixed it in the afternoon.

**Comment by Finii** [comment]
You are probably referring to the cask https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-meslo-lg-nerd-font.rb

Which 'house'?

![image](https://user-images.githubusercontent.com/16012374/189192697-b8dc668e-07d9-42e8-8995-0989dd4ace9b.png)

Maybe Font Awesome Home?

There are a lot of fonts, `M`, `L`, `S` and all three with `DZ`.
I try M=medium, no DZ...

![image](https://user-images.githubusercontent.com/16012374/189192475-3be9ed8a-5f53-42a3-a3d7-b95edc1a4459.png)

The houses are exactly same size.

You see, too many variables, need more details.

**Comment by cprivitere** [comment]
Well, you probably know how this is going to go...I started doing all the data collection to open a new issue and get you all the correct font settings. And during the course of that (and playing around with the M, L, and S sizes) and the issue disappeared. I blame something weird in iTerm2 on my Mac.
