### ISSUE TITLE
Fontconfig file does not include regular Fira Code variant

### ISSUE THREAD

**Issue by Scrumplex** [ryanoasis/nerd-fonts#918]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Since v2.2, the fontconfig file in the root of this repo doesn't include configuration for `Fira Code` (or `Fira Code Regular`).
https://github.com/ryanoasis/nerd-fonts/blob/5454877c01e5efb4b902151655f75d950678dc34/10-nerd-font-symbols.conf#L1036-L1051

Expected behavior:
Prior to v2.2, the fontconfig file in the root of this repo included configuration for `Fira Code` (or `Fira Code Regular`).
https://github.com/ryanoasis/nerd-fonts/blob/fa69496f5a3291fbcb6c0ad5bcec9c8bcab842fc/10-nerd-font-symbols.conf#L24-L39

Example symbols:
N/A

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - `FiraCode-Regular.ttf` (unpatched Fira Code)
   - `Symbols-2048-em Nerd Font Complete.ttf` (From AUR package, v2.2)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
  - kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
  - Linux

#### ★ Screenshots (Optional)
N/A

**Comment by Finii** [comment]
@Scrumplex could you test this please: https://github.com/ryanoasis/nerd-fonts/blob/bugfix-fontconfig/10-nerd-font-symbols.conf

Just fixed the obvious errors, never used a fontconfig :grimacing:

**Comment by Finii** [comment]
It does not make any sense to produce `Symbols Nerd Font Mono`, right?

```
$ fc-query --format='%{family}\n' ../../patched-fonts/NerdFontsSymbolsOnly/complete/Symbols*
Symbols Nerd Font Mono
Symbols NFM
Symbols Nerd Font
Symbols NF
Symbols Nerd Font Mono
Symbols NFM
Symbols Nerd Font
Symbols NF
```

Or does it? :thinking: 

Anyhow, the fontconfig prescribes the non-mono substitute.   ... ?

**Comment by Scrumplex** [comment]
> @Scrumplex could you test this please: [https://github.com/ryanoasis/nerd-fonts/blob/bugfix-fontconfig/10-nerd-font-symbols.conf](https://github.com/ryanoasis/nerd-fonts/blob/bugfix-fontconfig/10-nerd-font-symbols.conf?rgh-link-date=2022-09-08T10%3A44%3A26Z)

This seems to work fine :+1:

**Comment by Scrumplex** [comment]
I don't think we need to produce the Mono version, but I guess it doesn't hurt? Arch Linux packages both the Mono versions: https://archlinux.org/packages/?q=ttf-nerd-fonts-symbols

**Comment by Finii** [comment]
> I don't think we need to produce the Mono version, but I guess it doesn't hurt? Arch Linux packages both the Mono versions: https://archlinux.org/packages/?q=ttf-nerd-fonts-symbols

Where I read this ... just realized that it is a real Arch package and not an AUR, that explains something... :woman_facepalming: 

If there are people who see value in that fonts... great :-) Thanks for the feedback!
