### ISSUE TITLE
Feature request: organize content of release archives differently

### ISSUE THREAD

**Issue by ksze** [ryanoasis/nerd-fonts#919]
Right now, in the release archive zip file, the Windows-compatible versions of the ttf files are mixed together with the _regular_ ttf files.

This makes it annoying to install the fonts via a graphical shell like Windows Explorer because the files are listed in an interleaved way. I could type "Windows Compatible" in the search box to filter, but that's an extra step that I need to repeat with every new release, for every typeface. I suspect Linux and Mac users suffer the same problem in something like Nautilus and Finder.

Could you organize the content differently such that Windows-compatible ttf files are all put in a separate subfolder in each zip file?

**Comment by Finii** [comment]
:heart:

I would even separate `Mono` and `non-Mono`, as I would seldom require both.
Or what was it `JetBrains` with and without ligatures is mixed together :grimacing: 

The problem are all the autogenerated install packages (AUR, scoop, etc) which will break on a change.
It is so meaningless, that the AUR packages install the `Windows Compat` fonts on Arch, for example.
These are maintained by a lot different individual projects, by different people, even for one package platform.
Some install from the zip files, some fetch the files from the repo directly.

And what I would like to change are the file names (#722). They should resemble 'standard font file names' and not what we have now.

And using the new `--makegroups` would break the filenames (again).

So this should all be done together in one release, probably in a major version like `3.0.0`.

**Comment by Finii** [comment]
My secret dream is that we can drop `Windows Compat` completely. I do not believe that the length restriction still applies to modern Windows systems - I personally use the 'normal' fonts on Windows and never had any issue.

And then a lot `Mono` fonts are broken by design (could not work), we should drop them completely (#912)

**Comment by ChiefMikeK** [comment]
As an additional thought since iosevka.zip is so LARGE could it be split up into at least IosevkaTerm.zip, IosevkaFixed.zip, and IosevkaQuasi.zip or even be further broken down?
> https://typeof.net/Iosevka/

+ Noto.zip but, I'm not she how to break it down :neckbeard:

**Comment by Finii** [comment]
@ksze "Windows Compatible" is a thing of the past with v3.0.0 (there is no need anymore)
@ChiefMikeK I did the split, at least in half, with v3.0.0
