### ISSUE TITLE
Add Space Mono Font (Google Fonts)

### ISSUE THREAD

**Issue by rscircus** [ryanoasis/nerd-fonts#93]
See: https://fonts.google.com/specimen/Space%20Mono which runs under the [Open Font License](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web).

![image](https://cloud.githubusercontent.com/assets/1167114/16179748/96aa624c-366f-11e6-8ebc-5281d70ea3f1.png)

Thanks. :-)

**Comment by ryanoasis** [comment]
This looks like a cool font. I like it :smile:

**Comment by rscircus** [comment]
Thanks, @ryanoasis! :-)
