### ISSUE TITLE
Yay install failed

### ISSUE THREAD

**Issue by Exordio** [ryanoasis/nerd-fonts#933]
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
Attempts to update via yay manager fail. 
`curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.`
I've tried clearing yay/pacman caches and other tricks. I also tried to download directly via wget from github. Download drops around 2GB.

Expected behavior:
I would like yay to download and install the update normally

Example symbols:
The problem is not related to fonts

#### 🔧 Your Setup
- urxvt
- Manjaro Linux x86_64, kernel: 5.15.65-1-MANJARO, i3wm

#### ★ Screenshots (Optional)

![2022-09-17-192505_841x260_scrot](https://user-images.githubusercontent.com/45700369/190866726-3a126880-25b6-40c8-a543-b8cd2fa44db3.png)

**Comment by Finii** [comment]
I do not know what `yay` wants to to, but downloading the complete repo just to install the fonts is not what it **should do**.
:sob: 

There is a release page, with release files, it should download these.

I guess you should report the issue(s) with the `yay` package maintainers. They could for sure do better.

But whatever the problem, I can download the archive, (although I'm shocked that a font installer does this):

![image](https://user-images.githubusercontent.com/16012374/190887561-d45eb672-04e1-4ed3-bb26-1c4287f1c45a.png)
