### ISSUE TITLE
Hasklug ligature issue

### ISSUE THREAD

**Issue by akosradler** [ryanoasis/nerd-fonts#934]
#### 🎯 Subject of the issue

Experienced behavior:
Turning ligatures on for Hasklug turns ```||``` into a single line ```|```
As these are separate operations in various languages, this behaviour is not desired. (and likely a bug)

#### 🔧 Your Setup

- Tried with Hasklug Nerd Font Complete Mono Windows Compatible.otf
- Terminal agnostic
- Using Windows

**Comment by Finii** [comment]
Can reproduce:

![image](https://user-images.githubusercontent.com/16012374/190995096-9c18157f-440e-46a0-941d-8cfbdfbae4bd.png)

`==` ligature works, `||` jumps to just one (right) bar on entering 2nd char

**Comment by Finii** [comment]
Somehow the rule is missing in the `Mono` font:

![image](https://user-images.githubusercontent.com/16012374/191001651-2ae26237-9e1d-4563-b367-c0eefc6e01b3.png)

(`E104` is the double-bar glyph)

Ah, yes, it is the old/dysfunctional attempt to remove ligatures from `Nerd Font Mono` fonts...

![image](https://user-images.githubusercontent.com/16012374/191002018-04156fad-5189-4cae-bfb2-d6c3f313a4f1.png)

**Comment by Finii** [comment]
The code in `font-patcher` is wrong.

Original code (commit by Ryan 557fc00 `ryanoasis 2016-03-18 23:15 -0400`):
```python
# let's deal with ligatures (mostly for monospaced fonts)
if args.configfile and config.read(args.configfile):
  if args.removeligatures:
    print("Removing ligatures from configfile `Subtables` section")
    ligature_subtables = json.loads(config.get("Subtables","ligatures"))
    for subtable in ligature_subtables:
      print("Removing subtable:", subtable)
      try:
        sourceFont.removeLookupSubtable(subtable)
        print("Successfully removed subtable:", subtable)
      except Exception:
        print("Failed to remove subtable:", subtable)
elif args.removeligatures:
  print("Unable to read configfile, unable to remove ligatures")
else:
  print("No configfile given, skipping configfile related actions")
```

That code has been touched once by Jimmy (commit 0a480bb `Jimmy Haas 2018-08-04 03:39 -0700`):
```python
def remove_ligatures(self):
    # let's deal with ligatures (mostly for monospaced fonts)
    if self.args.configfile and self.config.read(self.args.configfile):
        if self.args.removeligatures:
            print("Removing ligatures from configfile `Subtables` section")
            ligature_subtables = json.loads(self.config.get("Subtables", "ligatures"))
            for subtable in ligature_subtables:
                print("Removing subtable:", subtable)
            try:
                self.sourceFont.removeLookupSubtable(subtable)
                print("Successfully removed subtable:", subtable)
            except Exception:
                print("Failed to remove subtable:", subtable)
        elif self.args.removeligatures:
            print("Unable to read configfile, unable to remove ligatures")
        else:
            print("No configfile given, skipping configfile related actions")
```

Note how the indentation changed ... now we have a loop that just prints ... :-(

The bottommost `elif` and `else` were also corrupted, but that has already been fixed with c72b0d9 `fracsinus 2021-07-26 06:24 +0900) with #644.

**Comment by Finii** [comment]
Fixed, thanks for reporting.

**Comment by akosradler** [comment]
Thank you for fixing it :)
