### ISSUE TITLE
Add icon for aws

### ISSUE THREAD

**Issue by laminko** [ryanoasis/nerd-fonts#936]
It would be better if we had aws icon in the nerd fonts.

<img width="212" alt="image" src="https://user-images.githubusercontent.com/543138/191493549-596d6c69-6901-4fcc-b2b2-915e5b4e8476.png">

REF: https://fontawesome.com/icons/aws?s=solid&f=brands

**Comment by Finii** [comment]
What is 'wrong' with the aws icon we have?

![image](https://user-images.githubusercontent.com/16012374/191762258-a6dd5677-52c6-437d-8d00-b69d30c85353.png)

Otoh when we update Font Awesome I guess you also have what you want?

**Comment by laminko** [comment]
It does not represent AWS if we use together with starship prompt (or may be similar kind). And, I think it represents specific service instead of the brand. I believe it will be resolved after updating font-awesome as you said.

**Comment by Finii** [comment]
Will be solved by #773
