### ISSUE TITLE
Feature request: Add the IEC Power symbols glyph sets until the original fonts do

### ISSUE THREAD

**Issue by evaryont** [ryanoasis/nerd-fonts#94]
It would be appreciated if you could add another font variation to add the IEC power symbols to these fonts.

http://unicodepowersymbol.com/

Of course, a bunch of fonts will probably be updated to include them eventually anyways, as these are standardized unlike the rest of the glyph sets. And adding yet another variation would add a whole bunch of files for each combination of this glyph set included or not.

**Comment by ryanoasis** [comment]
Very cool and great idea. I like.

Since these seem to be standardized maybe we don't need 'yet another variation' and we can just include these by default :smiley:
