### ISSUE TITLE
2048 em for Space Mono

### ISSUE THREAD

**Issue by Llamach** [ryanoasis/nerd-fonts#941]
It would be nice to add a 2048em symbols for Space Mono instead of 1000em

**Comment by Finii** [comment]
I think I do not understand. Space Mono is 1000em.

Why do you think the symbols should be 2048em? The em-size is a font property, there is only one value for the complete font.
Maybe show screenshot with issue?

**Comment by Llamach** [comment]
![20220926_22h04m41s_grim](https://user-images.githubusercontent.com/106749236/192332669-2ddbff1e-d7bd-4e33-987f-e1139f030283.png)

**Comment by Llamach** [comment]
Closing the issue since the issue was solved by changing the terminal. Sorry for wasting your time.
