### ISSUE TITLE
`nf-linux-ferris` text symbol renders differently to the website preview

### ISSUE THREAD

**Issue by T-727** [ryanoasis/nerd-fonts#946]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
ferris renders half-empty.
![image](https://user-images.githubusercontent.com/74924917/192881767-7f27656b-2135-49cb-a137-1075f0052c72.png)

Expected behavior:
ferris renders filled all the way.
![image](https://user-images.githubusercontent.com/74924917/192881596-03cbc29b-4ac1-4593-acf2-4362f37c8381.png)

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Caskaydia Cove Nerd Font Complete Mono Windows Compatible Regular.otf_
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - _[the official font downloads](https://www.nerdfonts.com/font-downloads)_
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
  - _Alacritty, tried Windows-Terminal with the same result_
-  _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - _Windows11 Home 22H2_

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/193085498-dc7d7cf4-7143-4d95-adce-18e9d361e6e6.png)

Hmm, looks good in font directly in the repo:

![image](https://user-images.githubusercontent.com/16012374/193086781-5e9f8f61-89bd-4d64-b08c-9f3b8d2c55ea.png)
_Rendering preview shown_

Taking font from zip from link you provided:

![image](https://user-images.githubusercontent.com/16012374/193087530-4f0eb63f-685a-4b3c-8442-3870d9e820f8.png)

Hmm, the construction looks ... questionable. But `fontforge` says it will render correct, trying `alacritty`

![image](https://user-images.githubusercontent.com/16012374/193098151-1e476271-78ce-44ee-b09a-3c2aa0e2921b.png)

Very small, but full.

You run Linux in this strange Windows subsystem thing?

**Comment by Finii** [comment]
Win 11 ... hmm, only machine I have available is my child's Legion 😬 

... ah, indeed:

![grafik](https://user-images.githubusercontent.com/16012374/193102605-f8170458-58df-4071-82cc-14f2dc0dd30a.png)

**Comment by Finii** [comment]
Fix is underway: https://github.com/lukas-w/font-logos/pull/87

But it will take some time until it trickles down into Nerd Fonts ...

**Comment by Finii** [comment]
Can be closed when we update to font-logos > 1.0.1

**Comment by T-727** [comment]
Alrighty, Thanks you!

**Comment by Finii** [comment]
Still broken in upstrream, maybe fix on our own for `v2.3.0`
