### ISSUE TITLE
UbuntuMono for Windows is missing some symbols

### ISSUE THREAD

**Issue by igordovgaluk** [ryanoasis/nerd-fonts#949]
*Windows Compatible fonts are missing some symbols available in other non-Windows ttf files.

★ Screenshots

screenshot from Windows (installed font files *Windows Compatible.ttf)
![symbol-missing-on-Windows](https://user-images.githubusercontent.com/4215041/193044435-30badd66-14a8-4527-b475-e96e139c4a0e.png)

screenshot from Linux 
![symbol-on-Linux](https://user-images.githubusercontent.com/4215041/193044466-2fb2f254-ebf4-44a1-82fd-44a1dc2266da.png)

**Comment by Finii** [comment]
I believe that symbol is one of
* `276D` Medium right-pointing angle bracket
* `276F` Heavy right-pointing angle quotation mark
* `2771` Heavy right-pointing angle bracket

These are not patched-in by Nerd Fonts.

Find out where they come from under Linux:
```
$ fc-list ':charset=276d' family
```

I will close this now. If you believe the symbol should be a different one, please copy and paste the symbol into a comment window here. Even if it shows wrong I will be able to extract the codepoint from it.

If you have the codepoint, you can check with `fc-list` which font(s) provide a glyph for that codepoint.

**Comment by igordovgaluk** [comment]
@Finii thank you for the clarification!

**Comment by Finii** [comment]
We added these glyphs now, via commit 59c5cb5a1f33139b79838f010fafea26623ed046  `font-patcher: Patch in heavy angle brackets`
