### ISSUE TITLE
Glyph Request : Anaconda (conda)

### ISSUE THREAD

**Issue by aarmn** [ryanoasis/nerd-fonts#952]
**Requirements**

- [-] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [-] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [-] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**
I'm sad about not having anaconda glyph

**Describe the solution you'd like**
adding anaconda glyph

**Describe alternatives you've considered**
living without anaconda glyph

**Additional context**
it would be good if we had anaconda glyph

**Comment by Finii** [comment]
Seems to be in `simple-icons` which is on the `v3.0.0` list #716 iirc.

![image](https://user-images.githubusercontent.com/16012374/193414543-79013334-9e1c-4267-b685-945a4d1317dd.png)

**Comment by aarmn** [comment]
Sorry, how may I get ver3? is it under devel or on main? if its available where? (on which branch)
also where can I search on all font glyphs, because nerd-font website search do not contain many of these names! (e.g. git-cherrypick, this one and way more)

**Comment by Finii** [comment]
Still working on `2.3.0`, devel on `v3.0.0` starts thereafter.

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
