### ISSUE TITLE
Feature request: Add font-awesome-extension glyphs

### ISSUE THREAD

**Issue by KabbAmine** [ryanoasis/nerd-fonts#96]
A request here, is it possible to add glyphs from [font-awesome-extension](https://github.com/AndreLGava/font-awesome-extension)?

**Comment by ryanoasis** [comment]
Yes should be possible. I would want to check it out more but looks like adding them should not  cause any specific issues except maybe conflicts

**Comment by KabbAmine** [comment]
Great then :smiley:

**Comment by KabbAmine** [comment]
:+1:
