### ISSUE TITLE
'Not equal (!=)' ligature is broken for all JetBrains Mono Light/ExtraLight weights.

### ISSUE THREAD

**Issue by xbladesub** [ryanoasis/nerd-fonts#963]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
'Not equal (!=)' ligature is broken on all JetBrains Mono ExtraLight/Light weights. Draws it incorrectly.

Expected behavior:
Expecting working 'not equal (!=)' ligature for Light/ExtraLight font weights.

Example symbols:
So far I recognized only one issue - '!=' draws incorrectly.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_
   
   
Bug occurs in all Light/ExtraLight fonts:
1) JetBrains Mono ExtraLight Nerd Font Complete Mono Windows Compatible.ttf
2) JetBrains Mono ExtraLight Nerd Font Complete Mono.ttf
3) JetBrains Mono ExtraLight Nerd Font Complete Windows Compatible.ttf
4) JetBrains Mono ExtraLight Nerd Font Complete.ttf

   - _Where did you get the file from (download link, self patched, source downloaded from link...)_
   
Fonts are downloaded from:
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono/Ligatures/ExtraLight/complete
(also tried to download from website - same)

- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_

All text editors are affected (JetBrains IDEs, Neovim, Neovide...)

- _Are you using OS X, Linux or Windows? And which specific version or distribution?_

MacOS Monterey 12.6 (M1 Pro)

#### ★ Screenshots (Optional)

<img width="355" alt="Screen Shot 2022-10-12 at 10 09 51 AM" src="https://user-images.githubusercontent.com/45129790/195237138-e8b7dbd8-4c81-44c0-9025-fea650c52468.png">
<img width="710" alt="Screen Shot 2022-10-12 at 10 29 37 AM" src="https://user-images.githubusercontent.com/45129790/195237146-8e09ccba-59fe-4222-bd72-7b1ca288e7ba.png">

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/195251975-fe5725f9-7039-4321-8881-7bb388c8492a.png)

**Comment by Finii** [comment]
`Light` also affected. `ExtraLight Italic` and `Light Italic` ok.

**Comment by Finii** [comment]
The glyph itself looks ok in ff :thinking: 

Already broken upstream

![image](https://user-images.githubusercontent.com/16012374/195254087-c733c4e9-ca6f-4681-a1cc-36fc5194dcf3.png)

**Comment by Finii** [comment]
See https://github.com/JetBrains/JetBrainsMono/issues/532

**Comment by Finii** [comment]
We could update to the not-yet-published `JetBrains Mono 2.301`, but I'd rather avoid that.

**Comment by Finii** [comment]
Glyph is broken in `ff`:

![image](https://user-images.githubusercontent.com/16012374/195262216-5fb0d967-d2a5-42c8-848d-1613b8197afd.png)

We could transplant that one glyph.

**Comment by Finii** [comment]
@xbladesub Thanks for reporting. Maybe you can try the new (Extra)Light versions?

**Comment by Finii** [comment]
Grr, just noticed I rebuilt the stuff with `fontforge 2020 March Release` instead of `fontforge March 2022 Release`.
Hope it went all well and no fontforge bugs crept up :roll_eyes: Lost track of what is broken and what not.

**Comment by xbladesub** [comment]
> @xbladesub Thanks for reporting. Maybe you can try the new (Extra)Light versions?

No it's perfect. Thanks!
