### ISSUE TITLE
font request: monaco

### ISSUE THREAD

**Issue by moralground** [ryanoasis/nerd-fonts#970]
Hi. Would be be possible to merge https://github.com/Karmenzind/monaco-nerd-fonts into the collection? Monaco is quite a good terminal font. There's also https://github.com/taodongl/monaco.ttf

**Comment by Finii** [comment]
I believe the following is still true:

https://www.quora.com/Can-you-download-Apples-Monaco-font-for-Windows?share=1

> Thus, any free or paid download you find online is going to be a knock-off of the original and/or illegal. It's entirely possible that someone has taken the original, repackaged the font completely in-tact, and posted it online for download (I don't know what kind of license Monaco comes with, but I'm pretty sure this is not allowed).

Is that not true? Did Apple release the font freely (I can hardly believe that, given the usual demeanor of Apple :grimacing: )
