### ISSUE TITLE
Fonts Patching requests

### ISSUE THREAD

**Issue by Photonico** [ryanoasis/nerd-fonts#972]
I hope these awesome fonts can be included in the nerd-fonts project.

+ Dse typewriter: https://github.com/dse/dse-typewriter-font
I love this font, but it is too thin, I'd appreciate it if you can make the bold version.

+ Rursus Compact Mono: https://fontlibrary.org/en/font/rursus-compact-mono

+ Maple font:  https://github.com/subframe7536/Maple-font

+ Century Schoolbook Monospace

+ TT2020: https://copypaste.wtf/TT2020/

+ Special-elite: https://aur.archlinux.org/packages/ttf-special-elite

I sincerely hope this project can include some typewriter-style fonts (serif monospace fonts).

**Comment by Finii** [comment]
Thanks for the suggestion list of nice fonts.

>  I'd appreciate it if you can make the bold version.

We cant (except automatically, which always looks bad).

And these are a lot of fonts you propose to add. You know that it involves considerable amounts of work for each of them? Maybe concentrate on 'important' once, for some definition of important?

**Comment by Finii** [comment]
Closing because transferred to #1095
