### ISSUE TITLE
Hasklug: additional ligature issues

### ISSUE THREAD

**Issue by akosradler** [ryanoasis/nerd-fonts#973]
#### 🎯 Subject of the issue

Experienced behavior:
Turning ligatures on for Hasklug deletes the first character from a two char ligature:
The two issues I've found:
- ```\\``` becomes ``` \```
- ```==``` becomes ``` =```
- ```>>``` becomes ```*>```

🔧 Your Setup
Tried with Hasklug Nerd Font Complete Mono Windows Compatible.otf
Terminal agnostic
Using Windows

A similar issue has been solved on this ticket: https://github.com/ryanoasis/nerd-fonts/issues/934 (that one works fine now)

**Comment by Finii** [comment]
I'm tempted to remove to ligature removal feature altogether. Other Nerd Fonts fonts also have ligatures, and people who do not want them can usually turn them off in their client. If the client can not turn it off, it usually does not see them anyhow :grimacing: 

That feature requires tedious manual work, on every update :roll_eyes:

**Comment by akosradler** [comment]
Not sure if this helps, but Hasklig is essentially just Source Code Pro with ligatures. At least in this case, if someone does not want them, they can just switch to SCP.
