### ISSUE TITLE
Update Seti UI

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#974]
When we would update our core set (which is mostly Seti UI), this will solve

![image](https://user-images.githubusercontent.com/16012374/196602346-8d45d727-2630-4a9e-916d-4b874d3a10fa.png)

* #904 (their `e014`)
* #857 (their `e004`)
* #852 (their `e05b`)
* #657 (their `e07e` f)

**Comment by Finii** [comment]
Came up in #929 thanks to @4e554c4c

**Comment by Finii** [comment]
They do not have stable codepoints, which is good because we can rearrange them in a stable codepoint manner together with our current codepoints:

![image](https://user-images.githubusercontent.com/16012374/196603848-ac7802b3-ce3f-4a27-86ef-9a6a288d1638.png)

**Comment by Finii** [comment]
Notes:

* Their `crystal` icon looks wrong (rotationwise), compare with https://github.com/crystal-lang/crystal
* Their C logo misses the standard's hex shape
* Their C++ logo misses the standard's hex shape
* Their Elixir icons has a dent in the reflextion?
* Their Elm icon is colored
* Their Git Folder is not a folder
* Their Kotlin icon is colored
* Their Puppet icon is more correct
* Their Pursescript icon is identical
* Their Windows icon is more modern

That means:
* Do not include their `crystal`, `elixir`, `elm`, `kotlin`, `purescript`
* Do not include our `puppet`, `windows`
* Keeping both `c`, `c++`, `git-folder`

**Comment by Finii** [comment]
I'm underwhelmed by Seti ...

The outlines have defects, what should be 'holes' are filled instead.

![image](https://user-images.githubusercontent.com/16012374/196665920-bb9bdd37-3200-4e0a-b17f-be4154639a42.png)

**Comment by ignamartinoli** [comment]
Until Friday I'm going to be submerged by exams.

I expect to be opening a PR on Saturday (Sunday at most) to close this [Issue](https://github.com/ryanoasis/nerd-fonts/issues/857).

Sorry for the delay

**Comment by Finii** [comment]
Solved via #978
