### ISSUE TITLE
Fira Code Nerd Font Mono is not displaying == sign correctly

### ISSUE THREAD

**Issue by Goku-San** [ryanoasis/nerd-fonts#975]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
**==** sign not displaying properly with **FiraCode Nerd Font Mono Medium**.  Few days ago ( Saturday or Sunday ) I updated the Fira Code Nerd Font. Before that everything was displaying correctly.

Expected behavior:
Expect to display properly as with original Fira Code Medium or FiraCode Nerd Font Medium.

If I use **FiraCode Nerd Font Medium** or **Fira Code Medium** than icons in vim are clipped.
So if you can please fix the **==** sign or revert to the patch from 9 days ago, when all was good.

Example symbols:

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - _Please give the full filename_ 
       Fira Code Medium Nerd Font Complete Mono.ttf

   - _Where did you get the file from (download link, self patched, source downloaded from link...)_ 
       https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode

- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
    **st** terminal with ligatures patch 
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
    Linux - Manjaro XFCE

#### ★ Screenshots (Optional)

![st_correct](https://user-images.githubusercontent.com/22682262/196760515-ed8ab056-ec4c-4902-ac3b-0b126fd57ebf.png)

st call inside config.h 
``static char *font = "FiraCode Nerd Font:style=Medium:size=12:antialias=true:autohint=true";``

![st_incorrect](https://user-images.githubusercontent.com/22682262/196760682-a6f010f0-ff6a-489e-84cc-7b8bac9a8829.png)

st call inside config.h
``static char *font = "FiraCode Nerd Font Mono:style=Medium:size=12:antialias=true:autohint=true";``

**Comment by Finii** [comment]
Thank you for reporting the issue! This reminds me of #973 

Wondering why this shows all up now, was I am not aware of any related changes.

The one working was also directly from master ~9 days ago?

**Comment by Goku-San** [comment]
The working was from master and according to the https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode its from ~9 days ago. I can only confirm for Fira Code because I only use them. I install them manually. I check every weekend for updates.
I checked the reported signs from #973 and #934, only the equal sign == is not working.

**Comment by Finii** [comment]
Can see it :+1: or :-(

![image](https://user-images.githubusercontent.com/16012374/196790128-b048621f-b0e3-4631-a86a-12c80f9e5365.png)

This is definitively the same issue, broken ligature. Let see

**Comment by Goku-San** [comment]
Nope can't see it... 🙁

**Comment by Finii** [comment]
"Lets see" means ... wait, I start searching for the reason :)

The commit is question in 5d218b1cd

There I fixed the ligature removal code. Before the commit the code ... did not do much. Afterwards it removed all the tables it was intended to remove.

But obviously the ligature removal data is outdated. It never showed because the ligature removal never happened because it was broken. ...

I guess we should just remove ligature-removal (as it never worked anyhow, at least not in the more recent past).

Do you want or not want ligatures?

**Comment by Finii** [comment]
And then the next question (because here is night and I have to sleep soon):

I was working in the Seti Icons update and am almost finished. Shall we wait with a bugfix (for the == bug) until Seti update is ready? That will be only in 24h or something.

**Comment by Goku-San** [comment]
First question --->  I want ligatures

Second question --> Yes, no problem I can wait.... 

You have I good night rest... we are in the same time zone :)

Thanks for your hard work...

**Comment by Finii** [comment]
Ah yes...

Here the history of font updates:

```
$ git log --pretty=format:"%h %ad -- %s by %an" src/unpatched-fonts/FiraCode/Medium/FiraCode-Medium.ttf
78be0e1e7 Tue Dec 7 12:14:51 2021 +1300 -- Add unpatched FiraCode v6.2 by Sean Fausett
d23d0e008 Sat Dec 4 14:36:29 2021 +1300 -- Add unpatched FiraCode v6.1 by Sean Fausett
dea135924 Mon Apr 27 21:31:40 2020 +0200 -- Add unpatched FiraCode v3.1 files by Oliver Hoffmann
2d32a1f44 Sat Jan 18 16:08:10 2020 -0800 -- Updates Fira Code source to v2.0 (#424) by Ryan L McIntyre
dfc31db1d Mon Sep 9 20:27:00 2019 +0200 -- Update unpatched Fira Code fonts to 2.0 by Hugo van Rijswijk
d9ea69ac6 Thu Oct 4 16:21:01 2018 +0200 -- updated FiraCode to version 1.206 by mashehu
ad162ace7 Sat Mar 10 17:39:23 2018 -0500 -- Adds sources for 'ttf' format of FiraCode (WIP #244) by Ryan L McIntyre
```

But the ligature removal table has never been updated along with it

```
$ git log --pretty=format:"%h %ad -- %s by %an" src/unpatched-fonts/FiraCode/config.json
a2f56206e Sun Feb 25 15:18:48 2018 -0500 -- Adds new config files (WIP #186) by Ryan L McIntyre
```

:grimacing:

**Comment by Finii** [comment]
> Thanks for your hard work...

You are welcome :-)

The solution is simple and the same as in the Hasklug Issue. Will change that along with the Seti update, like, tomorrow.
