### ISSUE TITLE
UbuntuMono has no license file

### ISSUE THREAD

**Issue by moralground** [ryanoasis/nerd-fonts#979]
The UbuntuMono.zip file doesn't include any kind of license like most of the others. Could this be fixed?

**Comment by Finii** [comment]
Thanks for reporting this. Of course.
Put it on the v2.3.0 list #962

I will have to investigate why it is missing in some and not in others. Probably because it is `LICENCE.txt` for Ubuntu and not just `LICENCE` :roll_eyes:

**Comment by Finii** [comment]
... `LICENSE` vs `LICENCE` :roll_eyes:

**Comment by Finii** [comment]
Affected:
Archive:  ./FantasqueSansMono.zip
Archive:  ./Ubuntu.zip
Archive:  ./UbuntuMono.zip  
Archive:  ./Tinos.zip
Archive:  ./Inconsolata.zip 
Archive:  ./ProggyClean.zip  
Archive:  ./NerdFontsSymbolsOnly.zip
Archive:  ./Monoid.zip 
Archive:  ./HeavyData.zip
Archive:  ./InconsolataGo.zip 
Archive:  ./Lekton.zip
Archive:  ./BitstreamVeraSansMono.zip
Archive:  ./SpaceMono.zip
Archive:  ./JetBrainsMono.zip            
Archive:  ./AurulentSansMono.zip
Archive:  ./ShareTechMono.zip
