### ISSUE TITLE
Caskaydia Cove naming pattern does not match all the other fonts

### ISSUE THREAD

**Issue by sbivol** [ryanoasis/nerd-fonts#980]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Caskaydia Cove files have been renamed in a way that breaks automation since it doesn't match any of the other fonts.
This happened at some point in the last few months.

Experienced behavior:
File names look like "Caskaydia Cove Nerd Font Complete SemiBold.otf"

Expected behavior:
File names should look like they did before: "Caskaydia Cove SemiBold Nerd Font Complete.otf"
This pattern is used by all other fonts in this repository.

Example symbols:
N/A

#### 🔧 Your Setup
N/A

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/6907850/197522058-8b2b83f9-f362-4ebb-a60e-79db902af99c.png)

**Comment by Finii** [comment]
Well, the naming of all other fonts is broken (i.e. against how fonts are customarily named).

The normal naming follows the pattern `name style weight`. Nerd Fonts has that wrong, except for Cascadia Code.
The naming has been fixed with #723 - just for Cascadia Code. The original PR with more explanations is #717.

It is planned to change the naming scheme for all fonts (to fix numerois issues for example #542).

How is the naming change breaking your automation? Maybe I can help transitioning?

**Comment by Finii** [comment]
In fact even the blanks in the font names have to go sooner or later. But that is not so near.

**Comment by Finii** [comment]
More naming changes on the list:
* Drop `Windows Compatible`
* Add `Nerd Font Proportional`
* Drop `complete/` subdirectory, as there is nothing else anymore anyhow

The current naming of Caskaydia Cove still has one ... glitch, that also needs to be fixed.

**Comment by sbivol** [comment]
> How is the naming change breaking your automation?
I download some fonts from this repo using a mapping of names and weights, with URLs generated from those values.

Any naming pattern works for me as long as it's consistent across all fonts, which currently it isn't (but used to be, hence the bug report).

**Comment by Finii** [comment]
Understood.

We wanted to test the new naming pattern with one font first, so the mismatch.

I read that as 'you download directly out of the repository directories'? So that can/will be unified if we have at least a release candidate with the naming change enabled 'globally'. Hmm.

Have no easy solution right now... thinking.

**Comment by Finii** [comment]
* #962 

seems to be still a lot of work. And I do not really like the currently active 'rolling release candidate' scheme in `master`, as that explodes the repo size and I can not force-push anything away on master. A release branch would have been much better.

**Comment by sbivol** [comment]
> I read that as 'you download directly out of the repository directories'?

This is the case, yes. I can download from a specific branch if need be, or even extract the fonts I need from release tarballs, as long as naming is consistent. 

So I'm not insisting that the master branch has to carry files with updated names, although it would be less work for me if it did :-)

**Comment by Finii** [comment]
Well, I try to delay `master` updates as long as possible :grimacing: 
If it just helps your for 'now' until the release I can create the `2.3.0-RC` branch ans enable the rolling release candidate there (would be better maybe anyhow)?

**Comment by sbivol** [comment]
Sure, that sounds like it would work.

Please note that this issue isn't impacting me in a "production is down and we're losing millions" way, I can wait until the naming update happens naturally as you have already planned.
Also, apologies for not looking harder for related issues.

**Comment by Finii** [comment]
Release is in repo, release as packages pending.
