### ISSUE TITLE
Source and license of FiraMono

### ISSUE THREAD

**Issue by Scorpion2185** [ryanoasis/nerd-fonts#982]
Could you provide a clear source code and license?
If I understood correctly the characters are from Mozilla fonts but the glyphs are from other fonts.
So the source code is scattered in this repo.

**Comment by Finii** [comment]
# Nerd Fonts Licensing

There are various sources used under various licenses:

* Nerd Fonts source fonts, patched fonts, and folders with explict OFL SIL files are licensed under SIL OPEN FONT LICENSE Version 1.1 (see below).
* Nerd Fonts original source code files (such as `.sh`, `.py`, `font-patcher` and others) are licensed under the MIT License (MIT) (see below).
* Many other licenses are present in this project for even more detailed breakdown see: [License Audit](https://github.com/ryanoasis/nerd-fonts/blob/-/license-audit.md).

## Source files not in folders containing an explicit license are using the MIT License (MIT)

----

FiraMono upstream: https://github.com/mozilla/Fira

**Comment by Scorpion2185** [comment]
Could you provide a clearer source for FiraMono https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraMono? Some glyphs seem to be taken from Awesome?

**Comment by Finii** [comment]
All glyphs patched in and their licenses are in the [License Audit _Glyphs Sources_](https://github.com/ryanoasis/nerd-fonts/blob/master/license-audit.md#glyphicon-sources)

**Comment by Scorpion2185** [comment]
How do you know where all the glyphs from Fira Mono Nerd Fonts are taken? 
For example to package it and put all the correct licenses.

**Comment by Scorpion2185** [comment]
It seems that a clear source won't be provided, thank you anyway for this repo.

**Comment by Finii** [comment]
Well, it is all in License Audit. I do not understand what you want, sorry.

**Comment by Finii** [comment]
You always use the phrase "clear source", whatever that means.
You have the actual sources of the font and all the glyphs.
You have links to the original repos of the font and all the glyphs.
You have a table of all licenses (font and all glyphs).

/shurg

**Comment by Scorpion2185** [comment]
Isn't the source of Fira Mono Nerd Fonts scattered all over the repo?
