### ISSUE TITLE
`nerd-fonts-hack` disappeared from Arch Linux AUR

### ISSUE THREAD

**Issue by Invertisment** [ryanoasis/nerd-fonts#983]
Today I updated my system and package `https://aur.archlinux.org/packages/nerd-fonts-hack` is not there anymore.
This package is mentioned in your README here: https://github.com/ryanoasis/nerd-fonts#option-7-unofficial-arch-user-repository-aur

I installed `ttf-hack` but there are no icons in that one. :thinking:

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/197821140-d8f88fe7-367f-4f6d-9f48-c15263ccffae.png)

Hmm.

**Comment by Invertisment** [comment]
There is no such package anymore. It existed and I used it.

**Comment by Finii** [comment]
You can still see it here:

https://web.archive.org/web/20220525051815/https://aur.archlinux.org/packages/nerd-fonts-hack

but now it seems to be gone.

On the other hand, the git repo is still accessible:

```
$ git clone https://aur.archlinux.org/nerd-fonts-hack.git
Cloning into 'nerd-fonts-hack'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 40 (delta 4), reused 39 (delta 4), pack-reused 0
Receiving objects: 100% (40/40), 9.30 KiB | 4.65 MiB/s, done.
Resolving deltas: 100% (4/4), done.
```

and even updated to 2.2.2:

```
2022-09-08 09:18 +0200 Mickaël Bourgier o Upgrade to version 2.2.2
2022-08-27 10:37 +0200 Mickaël Bourgier o Upgrade to version 2.2.1
2022-08-26 14:04 +0200 Mickaël Bourgier o Fix license file
2022-08-26 13:37 +0200 Mickaël Bourgier o Upgrade to version 2.2.0
2021-12-27 08:56 +0100 Mickaël Bourgier o Make this package provide ttf-font-nerd
2020-05-29 00:24 +0200 Mickaël Bourgier o Remove unnecessary make dependencies
2020-02-06 08:29 +0100 Mickaël Bourgier o Add the version number to Hack.zip to prevent caching
2020-02-05 17:53 +0100 Mickaël Bourgier o Forgotten .SRCINFO
2020-02-05 17:31 +0100 Mickaël Bourgier o Upgrade to version 2.1.0
2018-07-18 00:48 +0200 Mickaël Bourgier I First commit, version 2.0.0
```

Maybe ask Mickael directly?

```
commit e29d84750033ccfa16abb537a87426d73da7dc52
Refs: [master], {origin/master}, {origin/HEAD}
Author:     Mickaël Bourgier <mickael.bourgier@gmail.com>
AuthorDate: Thu Sep 8 09:18:26 2022 +0200
Commit:     Mickaël Bourgier <mickael.bourgier@gmail.com>
CommitDate: Thu Sep 8 09:18:26 2022 +0200

    Upgrade to version 2.2.2
---
 .SRCINFO | 8 ++++----
 PKGBUILD | 4 ++--
 2 files changed, 6 insertions(+), 6 deletions(-)
```

This must be some kind of bug. The AUR are maintained by their respective authors...

**Comment by Invertisment** [comment]
I thought that the owners would somehow come and read issues in this repo. If it's not up for some time I may ping the author.
This is a font. It's fine if it's missing for a couple of days.

**Comment by Finii** [comment]
:+1: And as you say it's a font, you can just install it from the release zip package and there is no need for an AUR at all (apart from dependencies maybe).

Just throw the contents of [Hack.zip](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Hack.zip) into your fonts folder, maybe `~/.local/share/fonts`.

The AUR installs into the system dir, though:

```
pkgver=2.2.2
source=("Hack-$pkgver.zip::https://github.com/ryanoasis/nerd-fonts/releases/download/v$pkgver/Hack.zip")
sha256sums=("1f031b6d08d51f4830eacd00853dddc7fbd4ae0a05e169f2c13f3037dd3359b3")
  
package() {
    install -d "${pkgdir}/usr/share/fonts/TTF"
    install -d "${pkgdir}/usr/share/licenses/${pkgname}
    rm "${srcdir}/"*"Windows Compatible.ttf"
    install -Dm644 "${srcdir}/"*.ttf "${pkgdir}/usr/share/fonts/TTF"
    install -Dm644 "${srcdir}/LICENSE.md" "${pkgdir}/usr/share/licenses/${pkgname}"
```

(`install` is the same as `cp`, more advanced ;) )

**Comment by Invertisment** [comment]
I copied the font and uninstalled `ttf-hack`. After session restart it worked. But I'll somehow have to remember that this will be resolved at some point :thinking: 
Thanks though.

**Comment by dvzrv** [comment]
The package is now in the official repositories: https://archlinux.org/packages/community/any/ttf-hack-nerd/
It replaces `nerd-fonts-hack` (unless you are not on Arch Linux).

**Comment by Invertisment** [comment]
But then why the doc isn't updated? Also why different naming scheme? Why not keep the old package name?

**Comment by Finii** [comment]
@dvzrv Thank you for the information.

@Invertisment Well, packaging is done independently from Nerd Fonts. There are just too many different ways people want the fonts to be packaged in. Information flow is difficult (in both directions). Someone adds a new package to AUR, some other user notices it and raises an Issue here, our docu is corrected, etc ...

Of course I can correct the docu, which means ... just removing the `Hack` link? Because it's a list auf AUR packages and when it vanishes from AUR (which does not make much difference probably for Arch users, but how about other distro users? I have no clue.)

 I have no clue about all the packaging systems and never ever used one of them for fonts (it's just fonts, what does one need an installer for that? I will probably never understand that.) So I can just add to the doc what users tell me would help them. :grimacing: I tried to collect them all, but there is virtually no feedback: https://github.com/ryanoasis/nerd-fonts/discussions/881#discussioncomment-3488054

**Comment by Finii** [comment]
Addendum: I will just change the the link now.

But still I do not understand the packaging (even our own). So maybe you can explain me why AUR (targetting only Linux systems I asume) includes the `Windows Compatible` fonts in the packages? It's a mystery for me.

**Comment by Invertisment** [comment]
I use package manager for everything.
When updates come then it's easy to handle without having `next-next-next` installers.

I have no idea why it's included. Maybe because of wine: https://www.winehq.org/
