### ISSUE TITLE
Symbols Only font with broken Powerline glyphs?

### ISSUE THREAD

**Issue by Finii** [ryanoasis/nerd-fonts#984]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

A picture says more than 1000 words

![image](https://user-images.githubusercontent.com/16012374/198108657-ab442ec6-5f00-4b6d-a24b-0fa85f773534.png)

#### 🔧 Your Setup

Directly from current `HEAD` (925885c8d1c), locally checked out repo.

**Comment by mfasman95** [comment]
Hello! I am currently experiencing an issue with both the `FiraCode` and `JetBrainsMono` nerd fonts where they both appear to be failing to show powerline characters while still showing some other symbols I would expect from a nerd font, such as the NodeJS icon. Could this be related to this bug?
![image](https://user-images.githubusercontent.com/6910389/198143745-38164d80-a579-4ac3-9e6e-42594fbcdb9a.png)

**Comment by Finii** [comment]
In your prompt more seems to be missing than only powerline symbols? Color switching seems to work, but all the `\[` and `\]` look lilke broken escape sequences? Ignoring those, the prompt reads `~ via @ v18.12.0 >`, is that the full expected text (except poweline symbols)?

**Comment by Finii** [comment]
@GitFenixZ: You left a thumbs up ... do you have this problem?

I do not see it with current HEAD anymore, which is 2.2.0-RC-302-g 1e134ca8f
I do not see it even with the commit I gave myself above (https://github.com/ryanoasis/nerd-fonts/commit/925885c8d1c4953d25363f19efd926fc7afa7070)
Probably that was some intermediate commit.

**Comment by GitFenixZ** [comment]
I'm sorry I took this long to reply, I was busy with some projects.

I don't have this problem anymore.

**Comment by Finii** [comment]
Great!
Thanks for reporting back!
