### ISSUE TITLE
Lilex font ligatures have alignment issues

### ISSUE THREAD

**Issue by DavidWiebe** [ryanoasis/nerd-fonts#988]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

##### Lilex Nerd Font
![image](https://user-images.githubusercontent.com/12297853/199549288-22aeffef-fc18-422d-8037-585e5dc41dda.png)

As can be seen in the image the ligatures seem to be offset by a whole character width to the left. Here is a screenshot of that same piece of code using Iosevka Nerd Font

##### Iosevka Nerd Font

![image](https://user-images.githubusercontent.com/12297853/199549627-5f133b7a-0bca-46a9-b66a-6b3e9d0dfe36.png)

Expected behavior:

I expect the ligatures to be as crispy and beautiful as the lilex curly braces.

Example symbols:

===
==
!==
etc

#### 🔧 Your Setup

- Lilex Nerd Font (Lilex Regular Nerd Font Complete.ttf). This file was downloaded from github. I clone the repo and copy the patched files into /usr/local/share/fonts with `sudo rsync -harvP . /usr/local/share/fonts/nerd-fonts --exclude "*Windows*" --include "*.ttf" --delete`
- Visual Studio Code 1.72.2
- Linux, Ubuntu 22.10

#### ★ Screenshots (Optional)

![image](https://user-images.githubusercontent.com/12297853/199554378-def52783-f4c6-45f7-98ea-311dc0f79678.png)

**Comment by Finii** [comment]
Well, I can not reproduce _when I install only one font_:

```
cd ~fini/git/nerd-fonts/patched-fonts/Lilex
cp Regular/complete/Lilex\ Regular\ Nerd\ Font\ Complete.ttf ~/.local/share/fonts
```

![image](https://user-images.githubusercontent.com/16012374/199556939-c32f4515-5375-4774-9888-816c7e51604c.png)

I have the gut feeling this is a Family naming problem. I'm not sure what VS Code 22 uses, but the Family naming is broken with Nerd Fonts.

![image](https://user-images.githubusercontent.com/16012374/199557966-88af2699-089b-43d7-a4a8-87e6173685c4.png)

The fix is already implemented but we still collect experiences with it (i.e. it is not used).
I can create you a new Lilex set with corrected naming; would you like to try that?

**Comment by DavidWiebe** [comment]
Yeah, I would like to try that thank you. I tried with just one font and that did not solve my problem

![image](https://user-images.githubusercontent.com/12297853/199560420-5d3aba36-201b-4634-b520-8aee885f6b14.png)

**Comment by Finii** [comment]
Ok, when it does not work with just one file, it is not the naming ;)
Which VS Code do you use? Snap, apt package, ... whatever? That I install the same thing,

**Comment by Finii** [comment]
Installing this 
![image](https://user-images.githubusercontent.com/16012374/199561976-f98938c3-5e0b-47e3-9ef3-fad6443ac852.png)

as flatpak

**Comment by DavidWiebe** [comment]
Oh that did it thank you. I had vscode installed through the snap store. Installing the flatpak version fixed the font rendering problem. I'm confused but content to close this.

**Comment by Finii** [comment]
Strange indeed. (I hate snap just out of principle ;)

Maybe it was some cached data from the old fonts.

The flatpak version is ok with one font or with all fonts?

**Comment by DavidWiebe** [comment]
The flatpak version works with both one font and all fonts. And yeah, must be cache... that or dns. It's always one of the two.

**Comment by Finii** [comment]
Just noticed that we patch Lilex as `otf` and `ttf`, and all the people with "install all" approach will have two different fonts each (identical Family/Subfamily name) but different font files, which can result in funny errors :-/

Just uploaded the naming-correct Lilex as `Lilex_makegroups.zip` to the `v2.3.0-RC` release page:
https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.0-RC
