### ISSUE TITLE
InputMono font patching failure…

### ISSUE THREAD

**Issue by kierun** [ryanoasis/nerd-fonts#99]
#### Subject of the issue

I downloaded the [InputMono font](http://input.fontbureau.com/download/) and tried to patch it using this command (`zsh`):

```
(master|✓); git log | head -1
commit c232226d395b6c067a4c9ccd65a6193ac3d7ffef
(master|✓); for x in ~/downloads/input/Input_Fonts/InputMono/*/*.ttf
do ./font-patcher $x -q --fontawesome --fontlinux --octicons --pomicons --powerline --powerlineextra --careful --out ~/.local/share/fonts/
done
```

I got the font installed no problem but none of the glyths (for example powerline ones) are in the font: all I get are sigmas. In addition, I cannot set the height of the font.

#### Your Setup

- **Linux** nightwatch 4.5.7-300.fc24.x86_64 #1 SMP Wed Jun 8 18:12:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **; fontforge -version**
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 22:31 UTC  3-Feb-2016-ML-D.
 Based on source from git with hash:
no xdefs_filename!
TESTING: getPixmapDir:/usr/share/fontforge/pixmaps
TESTING: getShareDir:/usr/share/fontforge
TESTING: GResourceProgramDir:/usr/bin
trying default theme:/usr/share/fontforge/pixmaps/resources
fontforge 22:31 UTC  3-Feb-2016
libfontforge 20160203
- [**st terminal**](http://st.suckless.org/) but irrelevant since I am using neovim-qt…
-  **; nvim --version**
NVIM 0.1.4
Build type: Release
Compilation: /usr/bin/cc -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/builddir/build/BUILD/neovim-0.1.4/build/config -I/builddir/build/BUILD/neovim-0.1.4/src -I/builddir/build/BUILD/neovim-0.1.4/.deps/usr/include -I/usr/include -I/builddir/build/BUILD/neovim-0.1.4/.deps/usr/include/luajit-2.0 -I/builddir/build/BUILD/neovim-0.1.4/.deps/usr/include -I/builddir/build/BUILD/neovim-0.1.4/.deps/usr/include -I/builddir/build/BUILD/neovim-0.1.4/.deps/usr/include -I/usr/include -I/usr/include -I/builddir/build/BUILD/neovim-0.1.4/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.1.4/build/include
Compiled by mockbuild
Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences
system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/usr/share/nvim"

#### Optional

This is what I see:

![screenshot](https://cloud.githubusercontent.com/assets/3079575/17728783/e6665504-6458-11e6-84e1-c507664d1a18.png)

**Comment by kierun** [comment]
This is what I see with `GuiFont Terminess Powerline:h8`:

![screenshot](https://cloud.githubusercontent.com/assets/3079575/17729374/d822a53a-645b-11e6-9f0d-03cadeec7e52.png)

The previous screen shot used `GuiFont! InputMono Nerd Font`.

**Comment by kierun** [comment]
God dammit! It was neovom-qt that was at an old release that did not support `GuiFont!`… Well, now that's fixed, I get the glyths but they look ugly:

![screenshot](https://cloud.githubusercontent.com/assets/3079575/17731142/eb3cf21c-6463-11e6-86e1-199aa00dcda1.png)

**Comment by ryanoasis** [comment]
@kierun hey sorry about the frustration but glad you solved it.

As for the "ugly" glyphs do you mean because the height is a bit too tall or because they are all white with black background?

**Comment by kierun** [comment]
@ryanoasis Ugly as in the font just looks blurry to my eyes. It does not seem as crisp as Terminus. It could be an artefact of `neovim-qt` or how I compiled or am running it.

For example, using `gvim` I get this "pretty" screenshot:
![gvim](https://cloud.githubusercontent.com/assets/3079575/17774208/65b3a630-654a-11e6-8fa7-5444a8999894.png)

Using `neovim-qt` with the same font (I think it is the same font!), I get this:
![neovim-qt](https://cloud.githubusercontent.com/assets/3079575/17774209/65b785e8-654a-11e6-8acb-75510148eb39.png)

The thing is, I really like this project and want to get it working 'cause you know, it's kinda cool. ;)

**Comment by ryanoasis** [comment]
Sorry for the delay. Does it still look blurry?

Glad you like the project :smile: , I know there are still several bugs.

**Comment by kierun** [comment]
Yes it does. There's some discussion on the `neovim-qt` page (see [issue 164](https://github.com/equalsraf/neovim-qt/issues/164)) about what can be done about it.
