### ISSUE TITLE
Can't select Nerd Fonts in built-in CMD and PowerShell

### ISSUE THREAD

**Issue by ThePython10110** [ryanoasis/nerd-fonts#994]
#### 🗹 Requirements

- 🗹 I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful. I found #269 and several other similar issues, but none of the workarounds I tried worked.
- 🗹 I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- 🗹 I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue
Caskaydia Cove (and probably other Nerd Fonts) does not appear in the list of fonts in either CMD or PowerShell.

Experienced behavior:
Caskaydia Cove Nerd Font Complete Mono Windows Compatible Regular works fine with Windows Terminal and VSCode, but doesn't appear in the font list in the build-in CMD or PowerShell.

Expected behavior:
The font appears in the list.

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
`Caskaydia Cove Nerd Font Complete Mono Windows Compatible Regular.otf`, downloaded from the latest GitHub Release (v2.2.2)

#### ★ Screenshots (Optional)
![image](https://user-images.githubusercontent.com/87204246/200635500-0777f6b7-def3-4645-9c36-0e974f017df7.png)

**Comment by Finii** [comment]
Sorry to hear of your problems.

Quick shot: I believe `cmd` does only work with our `ttf` files, not the `otf` one.

If you are after a patched Cascadia Code, you could use as workaround [Delugia](https://github.com/adam7/delugia-code/releases/tag/v2111.01.1) (another project, not Nerd Fonts) which has it as `ttf` font, and it is selectable on my `cmd` at least:

![image](https://user-images.githubusercontent.com/16012374/200652589-44a5e0b4-9ebc-4995-905d-759f08af2a75.png)

**Comment by Finii** [comment]
Hmm, just wanted to say that `mononoki.ttf` works, but that is `2.2.1` I have.
This needs more investigation.

![image](https://user-images.githubusercontent.com/16012374/200653788-f1508af4-d280-4cab-acff-e02a883ffa6b.png)

**Comment by ThePython10110** [comment]
It appears that CMD and PowerShell don't support OpenType fonts. `mononoki.ttf` worked for me.
