### ISSUE TITLE
New font: Photonico Code

### ISSUE THREAD

**Issue by Photonico** [ryanoasis/nerd-fonts#995]
Font name: Photonico Code

It is a new front, that is developed from FiraCode, and inherits its programming ligatures and HiDPI support. 
All glyphs are redesigned and remade.
It is slab-serif style font, that supports Latin, Greek letters, and many mathematical notations.

![IMG](https://raw.githubusercontent.com/Photonico/Photonico_Code/main/Images/overview_1.0.png)
![IMG](https://raw.githubusercontent.com/Photonico/Photonico_Code/main/Images/latin_1.0.png)
![IMG](https://raw.githubusercontent.com/Photonico/Photonico_Code/main/Images/greek_1.0.png)
![IMG](https://raw.githubusercontent.com/Photonico/Photonico_Code/main/Images/sym_1.0.png)
![IMG](https://raw.githubusercontent.com/Photonico/Photonico_Code/main/Images/stem_1.0.png)

GITHUB repo: https://github.com/Photonico/Photonico_Code

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
