### ISSUE TITLE
JetBransMono Regular ~~> ligature 

### ISSUE THREAD

**Issue by mhbkamaei** [ryanoasis/nerd-fonts#996]
In JetBrainsMono Regular the ~~> ligature is broken.

**Comment by Finii** [comment]
Issue template not filled, no details given.

**Comment by Finii** [comment]
![image](https://user-images.githubusercontent.com/16012374/201290329-84378720-7d22-470c-b486-19ec43bf1d37.png)

(using `v2.2.2` and `writer`)
