### ISSUE TITLE
Crash without error when patching custom Iosevka .ttc

### ISSUE THREAD

**Issue by Bahnschrift** [ryanoasis/nerd-fonts#997]
#### 🗹 Requirements

- [X] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [X] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [X] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:
When trying to patch a custom build of Iosevka with the complete set of icons, the patcher eventually crashes with no error message. When patching on windows, it crashes when patching the 6th font in the `.ttc`. However, on WSL, it crashes when patching the 51st font (out of 54). The crash does not occur if I use the `--careful` flag, however this is not a desirable workaround.

#### 🔧 Steps to reproduce
The Iosevka build script I am using is as follows:
```toml
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "slab"
export-glyph-names = false

[buildPlans.iosevka-custom.ligations]
enables = [
    "centre-ops",
    "arrow",
    "arrow2",
    "trig",
    "eqeq",
    "exeq",
    "ineq",
    "eqeqeq",
    "exeqeq",
    "exeqeqeq",
    "eqexeq",
    "ltgt-diamond",
    "ltgt-slash-tag",
    "brst",
    "plusplus",
    "kern-dotty",
    "kern-bars",
    "logic",
    "llgg",
    "llggeq",
    # "dot-as-operator",
    "bar-triggers-op-centering",
    "html-comment",
    "brace-bar",
    "brack-bar",
    "connected-underscore",
    "connected-number-sign",
    "connected-tilde-as-wave",
    "connected-hyphen-as-semi-dashed-line"
]

[buildPlans.iosevka-custom.variants]
inherits = "ss20"

[buildPlans.iosevka-custom.variants.design]
zero = "dotted"
asterisk = "penta-low"
caret = "high"
paren = "flat-arc"
ampersand = "lower-open"
at = "fourfold-solid-inner"
lig-ltgteq = "slanted"
question = "corner"

[collectPlans.iosevka-custom]
from = ["iosevka-custom"]
```
I've uploaded the `.ttc` for this font [here](https://drive.google.com/file/d/16WQeNqtQSiqaabQa2BASFiHSQwgh_jzD/view?usp=sharing).

On windows, I am patching the font with `fontforge.exe -lang py --script font-patcher iosevka-custom.ttc -c --mono -w`, and on WSL I am patching with `./font-patcher iosevka-custom.ttc -c --mono`.

**Comment by Finii** [comment]
I guess this is a out-of-memory situation.

Iosevka is rather big, and then holding that 50 times in memory, that is just not possible.

I would recommend patching one font after another and then combining all fonts into one ttc.

**Comment by Bahnschrift** [comment]
That could be the case, but I'm not entirely convinced. Unless it's I *should* have enough system memory to hold all the fonts (32GB), and on windows at least the crash occurs when fontforge is still using less than 2GB.

If this is the problem, maybe it would be possible for me to modify the patcher script so that each font is saved and closed after patching, then give all the filenames as arguments to `fontforge.generateTtc`? I'll give that a try a bit later.

Is there any way I could get the patcher / fontforge to produce more logs and information about what's happening?

**Comment by Finii** [comment]
Hmm,

lets try...

![image](https://user-images.githubusercontent.com/16012374/202848370-424ab34d-2695-4ae8-89c7-9a4dce867840.png)

### after some time

![image](https://user-images.githubusercontent.com/16012374/202848206-0705bc0f-88df-4c9e-9682-bf995fdeba94.png)

Being at font 15 the size is at ~5G, so maybe 18G at the end, lets see... (tumble thumbs)

### 27 -> 10G:
![image](https://user-images.githubusercontent.com/16012374/202848509-ceb01db9-9911-4388-b113-79d724bd2dd4.png)

### 35 -> 12.4G

### 42 -> 15G

### 47 -> 16.7G

### 50 -> 17.8G

### 53:

![image](https://user-images.githubusercontent.com/16012374/202849080-b61b5ff4-8c67-4a38-bb58-5c86187903f5.png)

### 54

![image](https://user-images.githubusercontent.com/16012374/202849091-735981eb-a045-4680-b081-6ab6213f325d.png)

### 54 finished

![image](https://user-images.githubusercontent.com/16012374/202849147-8f485206-e9c3-4a7d-b06d-a58b0737e1bc.png)

Now it's exporting ...

(uups I still have debug code in my `fontforge`...)

![image](https://user-images.githubusercontent.com/16012374/202849164-0cc6ca40-e83d-4a52-8491-1947ba42447e.png)

**Comment by Finii** [comment]
Export finished, now it's tweaking:

![image](https://user-images.githubusercontent.com/16012374/202849301-12a360d3-c3c9-40c1-9dbc-deb09f8f0eb3.png)

**Comment by Finii** [comment]
Tweaking will probably take a long time, but the result-font-file has already been created.

(Tweaking is a post-run script that manipulates the font file directly without `fontforge` (because that can not do some stuff).

![image](https://user-images.githubusercontent.com/16012374/202849385-b7c6bbbd-4842-46ec-a179-335c585181ef.png)

**Comment by Finii** [comment]
Tweaking progresses slowly, memory constant.

It does in fact binary patch the file on disc to correct some info in the generated font file directly, here the lowestppem; `fontforge` does not support to even _read_ that, let alone write.

![image](https://user-images.githubusercontent.com/16012374/202849531-62c6ce5c-a410-45e9-98a4-52f25eefdf32.png)

I used a rather recent (self built) `fontforge`:

![image](https://user-images.githubusercontent.com/16012374/202849654-46b4b33c-33c2-44f2-9bc4-3e40716b6d95.png)

Maybe older (released) `fontforge` versions have a memory problem, or your system resources are not big enough? ulimits?
This was the PR I have been working on: https://github.com/fontforge/fontforge/pull/5136 (thus the debug code)

**Comment by Bahnschrift** [comment]
Interesting, so it seems to be working fine for you? It seems a bit odd that is behaves differently on windows and WSL, and I'm guessing you're running native linux?

I also tried patching the same font but without the serifs (commented out `serifs = "slab"` in the build plans), resulting in a slightly smaller .ttc (6MB less), and it worked fine on WSL.

I'm using the latest release of fontforge (20220308), but it looks like the memory on WSL is capped at 16GB + 4GB swapfile, so I'll try increasing that and see if makes a difference.

**Comment by Finii** [comment]
> windows [...] WSL

I must admit ... suggestion: Use proper linux ;-)
 
> Is there any way I could get the patcher / fontforge to produce more logs and information about what's happening?

Not really. The script does not prevent any `fontforge` output. I guess it crashed within a `fontforge` call and so you see nothing in the script output.

> If this is the problem, maybe it would be possible for me to modify the patcher script so that each font is saved and closed after patching, then give all the filenames as arguments to `fontforge.generateTtc`? I'll give that a try a bit later. If that doesn't work, I'll follow your suggestion patching them all individually.

Well, `fontforge` needs to hold all fonts in memory before a ttc generate can be initiated. Saving the individual font files ... and then opening all files will not help here. You could patch all files individually and use some other tool to combine them into one ttc.

Just looked at the [fonttools](https://fonttools.readthedocs.io/en/latest/) and they also need to hold all `ttf` fonts in memory before the `ttc` can be generated. Probably there is no memory-friendly 'just copy from many input files to one destination file' tool.

**Comment by Finii** [comment]
I guess it's working here, yes. Well, the patching worked, the tweaking (which is just one raw file byte manipulation script I wrote) is till in progress because it is so slow :grimacing: 

![image](https://user-images.githubusercontent.com/16012374/202850520-73d8e802-ae02-40b6-b39a-9f7a9740c403.png)

The March 2022 Release is definitively good, older revisions could not even patch Iosevka **at all**.

If you just need this one patch run, I can give you my `ttc`; but that will not help you if you expect to do it again in the future.

Maybe it is also worth to try the Nerd Font docker container? I have no clue how Windows handles memory resources of those.

A yes, I'm on Ubuntu 22.10 here, just my small laptop 'log into the company's servers via NX' frontend thing, not very powerful.

**Comment by Finii** [comment]
> give all the filenames as arguments to `fontforge.generateTtc`?

It does not take filenames, it does only take font objects (`others`, i.e. opened fonts):

![image](https://user-images.githubusercontent.com/16012374/202851364-6bc23902-6d15-4be3-a4c7-ad1377f32186.png)

**Comment by Bahnschrift** [comment]
I just tried with more memory allocated to WSL, and it works fine. Not sure what the issue was on windows, but at least for WSL memory was definitely the issue.

**Comment by Bahnschrift** [comment]
Now I'm getting a problem with ligatures not working in IDEs (but still working in windows terminal?) on the patched fonts. Guess I'll take a look around and see if I can see if I can find anything related.

**Comment by Finii** [comment]
> Now I'm getting a problem with ligatures not working in IDEs (but still working in windows terminal?)

Not working at all, or misbehaving?
It should not be a difference if you use some IDE or a barebone-IDE called `windows terminal`.
Often you can disable ligatures and/or some might not support ligatures at all.
The ligatures do work with the unpatched fonts in that specific IDEs?

**Comment by Bahnschrift** [comment]
The ligatures work fine with the unpatched fonts in all scenarios that I would expect ligatures to work. They also work with the patched fonts in my terminal emulator - Windows Terminal. They don't however work in either IntelliJ IDEA or VSCode, even with all the appropriate ligature settings enabled.

I'll do some more poking around and try and work it out. Maybe I should open another issue?

**Comment by Finii** [comment]
> Maybe I should open another issue?

That's always best :-) Thank you
