### ISSUE TITLE
Glyph request: Flutter

### ISSUE THREAD

**Issue by hanskokx** [ryanoasis/nerd-fonts#999]
I would like to see an icon for Flutter added. Google has made a Dash icon which would suffice. (Dash is the mascot for Flutter.)

**Describe the solution you'd like**
Google has made a Dash icon which would suffice. (Dash is the mascot for Flutter.)

**Describe alternatives you've considered**
The Dart icon, which is already in the font, is the closest I can get but is insufficient for my needs.

**Additional context**
https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aflutter_dash%3A

<img width="97" alt="image" src="https://user-images.githubusercontent.com/1911919/202869921-dbb3dfe0-0dc2-46be-832d-1718d734b440.png">

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095
